CPP-220 S3135 "sizeof" should not be called on pointer parameters
SonarSource/rspec pull request #1030
Opened 2022-06-06 17:10 UTC by loic-joly-sonarsource

Undeprecate S1913

2022-06-09 07:19 UTC, amelie-renard-sonarsource requested changes

2022-06-09 07:19 UTC, amelie-renard-sonarsource commented on rules/S3135/cfamily/rule.adoc
> +This rule raises issues when `sizeof` is used to compute the array size of a pointer passed as a function argument or used in an arithmetic operation.
I find the last part of the sentence a bit misleading: the problem is not when `sizeof` itself is part of an arithmetic operation but when it takes an arithmetic operation involving an array as an argument. 
What about something like:
```suggestion
This rule raises issues when:
* `sizeof` is used to compute the array size of a pointer passed as a function argument
* `sizeof` is called with an arithmetic operation involving an array
```

2022-06-09 07:22 UTC, amelie-renard-sonarsource requested changes

2022-06-09 07:22 UTC, amelie-renard-sonarsource commented on rules/S3135/cfamily/metadata.json
>        "ARR01-C.",
```suggestion
      "ARR01-C."
```

2022-06-09 22:34 UTC, loic-joly-sonarsource commented on rules/S1913/cfamily/metadata.json
> +  "status": "ready",
Yes, we should.

2022-06-10 06:41 UTC, amelie-renard-sonarsource requested changes
Minor comment, and after that the PR can be merged

2022-06-10 06:41 UTC, amelie-renard-sonarsource commented on rules/S3135/cfamily/rule.adoc
> +* `sizeof` is called on the result of an arithmetic operation involving an array.
```suggestion
* `sizeof` is used to compute the array size of a pointer passed as a function argument
* `sizeof` is called on the result of an arithmetic operation involving an array
```

2022-06-15 22:51 UTC, loic-joly-sonarsource commented on rules/S3135/cfamily/rule.adoc
> +* `sizeof` is called on the result of an arithmetic operation involving an array.
I don't like these dots either, but I checked in the style guides that we use, and there is very little leeway for that: We cannot omit them because they form a full sentence...:
https://www.codot.gov/business/grants/safetygrants/assets/APStyleGuideCheatSheet.pdf
https://www.instructionalsolutions.com/blog/bulleted-list-punctuation

2022-06-16 11:19 UTC, amelie-renard-sonarsource commented on rules/S3135/cfamily/rule.adoc
> +* `sizeof` is called on the result of an arithmetic operation involving an array.
[Styling guide](https://github.com/SonarSource/rspec/blob/master/docs/styling_guide.adoc) is not precise on this subject.
Having a quick look at how rpsecs were currently written, we chose to keep the dots.

2022-06-16 11:19 UTC, amelie-renard-sonarsource approved these changes

2022-06-16 11:20 UTC, merged