Modify rule S2225: Add VB.NET
SonarSource/rspec pull request #1062
Opened 2022-06-19 11:34 UTC by Corniel

See https://github.com/SonarSource/sonar-dotnet/pull/5741

2022-06-28 11:07 UTC, Corniel commented
@arseniy-sonar The tests failed due to insufficient rights. Why is that? I assume it was not triggered by my (I obviously do not have the rights)?!

2022-06-28 11:40 UTC, arseniy-sonar commented
Hi @Corniel 
Can you, please, retrigger the analysis?

2022-06-28 14:13 UTC, Corniel commented
> Hi @Corniel Can you, please, retrigger the analysis (by committing an insignificant change)?

A re-base will do, I suppose. :)

2022-06-28 14:22 UTC, arseniy-sonar commented
> A re-base will do, I suppose. :)
Yep. Thank you.
The repository was misconfigured (hiding secrets from CI triggered by external collaborators). Now it does not do that, but still requires approval from a SonarSourcer to run the CI for security purposes.

2022-06-28 14:54 UTC, Corniel commented
@pavel-mikula-sonarsource I assume you're the candidate to review this?

2022-06-29 06:35 UTC, pavel-mikula-sonarsource commented
@Corniel Yes, thanks. I've assigned myself to all VB.NET related PRs.

2022-06-29 12:28 UTC, Corniel commented
@pavel-mikula-sonarsource 
> ERROR: Connection error HTTPSConnectionPool(host='dl.packetstormsecurity.net', port=443): Max retries exceeded with url: /papers/attack/HTML5AttackVectors_RafayBaloch_UPDATED.pdf (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
Welcome into certificate hell.

2022-09-12 20:20 UTC, Corniel commented
@pavel-mikula-sonarsource  Might be worth picking this up?

2022-09-13 13:36 UTC, pavel-mikula-sonarsource requested changes
Some copy/paste issues

2022-09-13 13:36 UTC, pavel-mikula-sonarsource commented on rules/S2225/vbnet/rule.adoc
> +[source,csharp]
```suggestion
[source,vbnet]
```

2022-09-13 13:36 UTC, pavel-mikula-sonarsource commented on rules/S2225/vbnet/rule.adoc
> +Calling ``++ToString()++`` on an object should always return a string. Returning ``++Nothing++`` instead contravenes the method's implicit contract.
The original encoding is some noise from importing data
```suggestion
Calling `ToString()` on an object should always return a string. Returning `Nothing` instead contravenes the method's implicit contract.
```

2022-09-13 13:36 UTC, pavel-mikula-sonarsource commented on rules/S2225/vbnet/rule.adoc
> +{
Copy/paste issue, should not be here
```suggestion
```

2022-09-13 13:36 UTC, pavel-mikula-sonarsource commented on rules/S2225/vbnet/rule.adoc
> +}
Same
```suggestion
```

2022-09-13 13:36 UTC, pavel-mikula-sonarsource commented on rules/S2225/vbnet/rule.adoc
> +[source,csharp]
```suggestion
[source,vbnet]
```

2022-09-14 06:26 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2022-09-19 11:57 UTC, pavel-mikula-sonarsource commented on rules/S2225/vbnet/rule.adoc
> +End Functio
Typo
```suggestion
End Function
```

2022-10-18 10:11 UTC, merged