Modify rule S4225: Add VB.NET
SonarSource/rspec pull request #1063
Opened 2022-06-19 18:54 UTC by Corniel

2022-07-11 13:42 UTC, pavel-mikula-sonarsource requested changes

2022-07-11 13:42 UTC, pavel-mikula-sonarsource commented on rules/S4225/vbnet/rule.adoc
> +Creating an extension method that extends ``++Object++`` is not recommended because it makes the method available on _every_ type. Extensions should be applied at the most specialized level possible,
This rule structure is a bit messy. 
Please do this same change in C# version as well:
- move the introduction to `csharp/rule.adoc`, because there's the difference between `Object` and `object`. If the intro would be the same, than including `/rule.adoc` would be the correct way.
- move the C# example to `csharp/rule.adoc` file

2022-07-13 11:53 UTC, Corniel commented on rules/S4225/vbnet/rule.adoc
> +Creating an extension method that extends ``++Object++`` is not recommended because it makes the method available on _every_ type. Extensions should be applied at the most specialized level possible,
@pavel-mikula-sonarsource Can you answer this?

2022-07-13 11:57 UTC, pavel-mikula-sonarsource requested changes
Ah, sorry. I had my comments hanging here without posting them.

2022-07-13 11:58 UTC, pavel-mikula-sonarsource commented on rules/S4225/vbnet/rule.adoc
> +Creating an extension method that extends ``++Object++`` is not recommended because it makes the method available on _every_ type. Extensions should be applied at the most specialized level possible,
Done, sorry. I've answered them and GitHub was showing them. I didn't notice that they are in "pending" state.

2022-07-14 10:16 UTC, Corniel commented
I'm willing to help out. But as there is zero documentation on how this works, there is no way I could even run it myself, I ask you to take the lead here. I have no problems with discovering how a black box works. Unless the person I'm trying to help, already knows...

2022-07-15 08:18 UTC, pavel-mikula-sonarsource commented
I'd say that it's fine if you do the changes blindly, without testing them. Just as you did for the VB part. I'll take care of validating / adjusting details.

The repo structure is documented in the readme https://github.com/SonarSource/rspec

As general concept:
* `rules/Sxxxx` is a common part of the rule. Whatever is here is meant to be shared by all languages
* `rules/Sxxxx/vbnet` starting point for a language-specific data. It can override stuff inherited from root (like metadata.json). It can include fragments of adoc files from root if it makes sense.

2022-07-15 08:19 UTC, pavel-mikula-sonarsource commented
To merge this, we need:
* update the C# part in a similar style as you did for VB
* remove namespace from VB.NET example
* add `title` to VB metadata.json to override it

2022-07-18 15:19 UTC, pavel-mikula-sonarsource commented
@Corniel do you plan to process this? Once it's done, we should be able to merge the rule.

2022-07-18 18:50 UTC, Corniel commented
@pavel-mikula-sonarsource As mentioned, I'm willing to put some effort in, but given the fact that Sonar (for whatever reason) does not allow contributors like me to have access to the full development kit, I think it should be someone with that full access to do most of the work.

2022-07-19 10:20 UTC, pavel-mikula-sonarsource commented
We don't have much more to do changes than what you have. Except the rule-api that is outside this repo.

2022-07-25 10:22 UTC, pavel-mikula-sonarsource commented on rules/S4225/csharp/metadata.json
> +  "title": "Extension methods should not extend \"object\""
Not needed - will be picked up from the root. I'll fix it.

2022-07-25 11:40 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2022-07-25 11:40 UTC, merged