Modify Rule S3649: Education Framework (APPSEC-46 & APPSEC-47)
SonarSource/rspec pull request #1109
Opened 2022-07-19 15:04 UTC by loris-s-sonarsource

This PR covers:
- [x] Java
- [x] C#

2022-07-22 09:58 UTC, pierre-loup-tristant-sonarsource requested changes
Looks pretty good! I feel the first part or the MMF could be improved. Please look at the question and suggestions I made.

2022-07-22 09:58 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/csharp/how-to-fix-it/system.data.adoc
> +//=== Pitfalls
```suggestion
```

2022-07-22 09:58 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/java/how-to-fix-it/java-se.adoc
> +=== How to fix it in Java Standard Edition
```suggestion
=== How to fix it in Java SE
```

2022-07-22 09:58 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/common/fix/code_rationale.adoc
> +In this particular case, the query can be exploited with the following string:
Maybe mention the name of the parameter where this payload can be injected too.

2022-07-22 09:58 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/common/fix/prepared_statements.adoc
> +String query = "SELECT * FROM users WHERE user = ? AND pass = ?";
```suggestion
SELECT * FROM users WHERE user = ? AND pass = ?
```

2022-07-22 09:58 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/common/fix/prepared_statements.adoc
> +As a rule of thumb, the best approach to protecting against injections is to
>As a rule of thumb
I am not familiar with this expression but it seems a bit informal.

2022-07-22 09:58 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/common/fix/prepared_statements.adoc
> +data can cause the database to execute malicious code.
Not sure what third party data you refer to here.

2022-07-22 13:13 UTC, loris-s-sonarsource commented on rules/S3649/summary.adoc
> +directly into a database query, such as SQL.
Oh, my bad - It seemed natural for me to write it

2022-07-22 13:50 UTC, loris-s-sonarsource commented on rules/S3649/impact.adoc
> +custom queries that are refined to fit into the existing application query.
Actually, maybe less is more in that case - I removed attempts to explain exploit, and it may be clearer

2022-07-22 13:53 UTC, loris-s-sonarsource commented on rules/S3649/csharp/how-to-fix-it/system.data.adoc
> +=== How to fix it in the Entity Framework Core
actually it's `system.data.entity`, yeah - I updated it

2022-07-22 13:59 UTC, loris-s-sonarsource commented on rules/S3649/common/fix/prepared_statements.adoc
> +As a rule of thumb, the best approach to protecting against injections is to
https://dictionary.cambridge.org/dictionary/english/rule-of-thumb

It doesn't look like it - and I don't really see it informal either tbh

2022-07-22 14:04 UTC, loris-s-sonarsource commented on rules/S3649/impact.adoc
> +custom queries that are refined to fit into the existing application query.
Actually, I got inspiration from your text, and removed the genre him to they

2022-07-25 08:26 UTC, pierre-loup-tristant-sonarsource requested changes
As discussed, please test the code example to make sure they are valid:
- Every variable that is used is defined somewhere
- An issue is raised on noncompliant code example
- No issue is raised on compliant code example

2022-07-25 08:26 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/csharp/how-to-fix-it/dapper.adoc
> +=== How to fix it in Java Standard Edition
```suggestion
=== How to fix it in Dapper
```

2022-07-25 11:28 UTC, pedro-oliveira-sonarsource commented on rules/S3649/common/fix/code_rationale.adoc
> +The following code is an overly simple authentication function, as an example.
The following code is an example of an overly simple authentication function.

2022-07-26 07:09 UTC, pedro-oliveira-sonarsource reviewed
Some minor suggestions.

2022-07-26 07:09 UTC, pedro-oliveira-sonarsource commented on rules/S3649/threats.adoc
> +from one or more databases. This threat is the most widespread impact.
```suggestion
from one or more databases. This threat has the most widespread impact.
```

2022-07-26 07:09 UTC, pedro-oliveira-sonarsource commented on rules/S3649/threats.adoc
> +The malicious query makes it possible for the attacker to delete everything. +
```suggestion
The malicious query makes it possible for the attacker to delete data in the affected databases. +
```

2022-07-26 07:09 UTC, pedro-oliveira-sonarsource commented on rules/S3649/threats.adoc
> +Most of the time, organizations overlook some defense in depth because they
```suggestion
Most of the time, organizations overlook some defense in depth measures because they
```

2022-07-26 07:09 UTC, pedro-oliveira-sonarsource commented on rules/S3649/threats.adoc
> +* If server-side OS permissions are misconfigured, injection can lead to remote code execution (RCE).
```suggestion
* If server-side OS and/or DB permissions are misconfigured, injection can lead to remote code execution (RCE).
```

2022-07-26 07:27 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/common/resources/standards.adoc
>  * https://cwe.mitre.org/data/definitions/943[MITRE, CWE-943] - Improper Neutralization of Special Elements in Data Query Logic
I think we only need CWE-89 and CWE-20 the other two are either childs or parents form CWE-89

2022-07-26 07:36 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/common/resources/articles.adoc
> +* https://wiki.sei.cmu.edu/confluence/x/ITdGBQ[CERT, IDS00-J.] - Prevent SQL injection
This is a security standard so it should be moved to standards.adoc

2022-07-26 07:42 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/common/fix/prepared_statements.adoc
> +systematically ensure that third-party data cannot break out of an interpreted
In this context, I think we should use "untrusted data" instead of "third party" which is too vague in my opinion.

2022-07-26 09:42 UTC, loris-s-sonarsource commented on rules/S3649/impact.adoc
> +application, knowing that a database server executes them.
Yeah, that's a specific nuance that may cause ambiguities to users, agreed. Technically we could say the attackers create a query, and then inject the query into another query - the sentence I wrote is ambiguous about this, I will change it

2022-07-26 09:51 UTC, pierre-loup-tristant-sonarsource requested changes
Please fix:
- Broken ascii doc references (check is red)
- C# code examples

Next time please remove placeholder files and directories from the PR (`docs.adoc`, `images`). For the reviewer, it's just noise.

2022-07-26 09:51 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/csharp/how-to-fix-it/dapper.adoc
> +}
This code example has multiple problems:
- Variable name collisions (`user`)
- Use of undefined variables (`sql`)
- `QueryFirst` does not throw (apparently)

```suggestion
public class ExampleController : Controller
{
    private readonly string ConnectionString;

    public IActionResult Authenticate(string user, string pass)
    {
        using (var connection = new SqlConnection(ConnectionString))
        {
            var query = "SELECT * FROM users WHERE user = '" + use + "' AND pass = '" + pass + "'";
            
            var result = connection.QueryFirst<User>(query); // Noncompliant
            if (result == null) {
                Unauthorized();
            }
        }
        return Ok();
    }
}
```

2022-07-26 09:51 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/csharp/how-to-fix-it/dapper.adoc
> +}
```suggestion
public class ExampleController : Controller
{
    private readonly string ConnectionString;

    public IActionResult Authenticate(string user, string pass)
    {
        using (var connection = new SqlConnection(ConnectionString))
        {
            var query      = "SELECT * FROM users WHERE user = @UserName AND password = @Password";
            var parameters = new { UserName = user, Password = pass };
            
            var result = connection.QueryFirst<User>(query, parameters);
            if (result == null) {
                Unauthorized();
            }
        }
        return Ok();
    }
}
```

2022-07-26 09:51 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/csharp/how-to-fix-it/system.data.entity.adoc
> +}
- Applying[ naming conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions)
- Removing `AUTHENTICATION_SUCCESS` because it's not defined

```suggestion
public class ExampleController : Controller
{
    private readonly UserAccountContext Context;

    public IActionResult Authenticate(string user, string pass)
    {
        var query = "SELECT * FROM users WHERE user = '" + user + "' AND pass = '" + pass + "'";

        var queryResults = Context
            .Database
            .ExecuteSqlCommand(query); // Noncompliant

        if (queryResults == 0)
        {
            return Unauthorized();
        }

        return Ok();
    }
}
```

2022-07-26 09:51 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/impact.adoc
> +application, knowing that a database server executes them.
@pedro-oliveira-sonarsource although it's called `impact.adoc` this part is an introduction to what comes next and it's expected that it puts the following scenario in a more specific context.

2022-07-26 09:51 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/impact.adoc
> +application, knowing that a database server executes them.
I feel like Pedro, this sentence is ambiguous. The application does the "database query" not the attacker who only influences it.
Also, as I shared last week, I think we should try to be more specific. We should pick a specific context like web application + SQL rather than staying abstract/high level and try to cover all cases. Therefore I reiterate the suggestion I did in my last review.

```suggestion
An attacker discovered an SQL injection in a web application. He will try to inject pieces of SQL statements and refine them until they fit into the existing SQL query.
```

2022-07-26 09:51 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/rationale.adoc
> +it is exposed to attacks that target any database where that query is used.
```suggestion
If an application contains a database query that is vulnerable to injections,
it is exposed to attacks that target any database where that query is used.
```
It's the application itself that contains the vulnerability.

2022-07-26 09:56 UTC, loris-s-sonarsource commented on rules/S3649/csharp/how-to-fix-it/system.data.entity.adoc
> +=== How to fix it in the Entity Framework Core
There are ambiguities in docs about system.data.entity actually being the Entity Framework Core - So I thought that "Entity Framework Core" was the human name of this namespace. I'll change the title because I just found out that the Entity Framework Core has actually been replaced at one point by the System.Data.Entity lib.

2022-07-26 13:18 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/common/fix/code_rationale.adoc
> +The following code is an overly simple authentication function, as an example.
One last comment: prefer `code-rationale.adoc` over `code_rationale.adoc` as it's the naming convention convention that is generally used for rspec files and folders.

2022-07-26 15:07 UTC, loris-s-sonarsource commented on rules/S3649/common/fix/prepared_statements.adoc
> +On the other hand, the application does not automatically sanitize third-party
there is already a `does`

2022-07-26 15:16 UTC, loris-s-sonarsource commented on rules/S3649/common/fix/prepared_statements.adoc
> +systematically ensure that third-party data cannot break out of an interpreted
the issue is that "untrusted" is subjective and makes sense for infosec people like us, and I think that non-security-aware developers can easily fall into the trap of "the user is trusted". On the other hand, third-party data refers to anything coming from the outside world in general, so... Yeah that's a tricky one

2022-07-26 15:21 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/csharp/how-to-fix-it/system.data.entity.adoc
> +=== How to fix it in the Entity Framework Core
It looks like Entity Framework is still being used https://devblogs.microsoft.com/dotnet/announcing-entity-framework-7-preview-1/.
`System.Data.Entity` is the namespace and I think we say we should avoid that.

2022-07-26 15:25 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/common/fix/prepared_statements.adoc
> +SELECT * FROM users WHERE user = ? AND pass = ?
@pedro-oliveira-sonarsource this part is shared across multiple languages so I think it's ok to show how the SQL prepared statement looks without showing the language-specific API that allows to use it.

2022-07-26 15:32 UTC, loris-s-sonarsource commented on rules/S3649/impact.adoc
> +application, knowing that a database server executes them.
Ok, I thought I processed your message from last week. I am taking your advice in my next commit

2022-07-27 07:24 UTC, pierre-loup-tristant-sonarsource approved these changes
LGTM.
see my last comment regarding System.Data.Entity vs Entity Framework Core.

2022-07-27 07:24 UTC, pierre-loup-tristant-sonarsource commented on rules/S3649/csharp/how-to-fix-it/system.data.entity.adoc
> +=== How to fix it in System.Data.Entity
It looks like Entity Framework is still being used https://devblogs.microsoft.com/dotnet/announcing-entity-framework-7-preview-1/. It feels like the natural name to use here.
`System.Data.Entity` is the namespace and we said we should avoid using that.
You can use both "Entity Framework", "Entity Framework Core" or "EF Core here" and "entity.framework.core" as technical name.

2022-07-27 09:56 UTC, pierre-loup-tristant-sonarsource commented
@loris-s-sonarsource before merging, can you please add the framework to `docs/allowed_framework_names.adoc` so that "validate_asciidoc" can pass?

2022-07-27 12:46 UTC, merged