[APPSEC-48] Modify rule S2083[java]: Educational content
SonarSource/rspec pull request #1112
Opened 2022-07-21 09:39 UTC by pierre-loup-tristant-sonarsource

2022-07-22 08:46 UTC, loris-s-sonarsource requested changes

2022-07-22 08:46 UTC, loris-s-sonarsource commented on rules/S2083/java/rule.adoc
> +== Why is this an issue?
This is lacking the `summary.adoc` file (example: https://github.com/SonarSource/rspec/blob/feature/education/rules/S5131/java/rule.adoc)

2022-07-22 08:46 UTC, loris-s-sonarsource commented on rules/S2083/impact.adoc
> +=== What is the potential impact?
As discussed, explaining concrete impacts in this introduction is redundant with the `threats.adoc` file (I suggest keeping an eye on what we already produced: https://github.com/SonarSource/rspec/blob/feature/education/rules/S5131/java/rule.adoc)

We should produce a mere introduction there.

2022-07-22 08:46 UTC, loris-s-sonarsource commented on rules/S2083/java/how-to-fix-it/java-se.adoc
> +The following code is vulnerable to path injection and can be leveraged by an attacker to delete arbitrary files.
This sentence should also quickly explain `why` it is vulnerable to path injection

2022-07-22 08:46 UTC, loris-s-sonarsource commented on rules/S2083/java/how-to-fix-it/java-se.adoc
> +* Check that the canonical path is within the directory where the file should be located.
I suggest adding numbering to emphasize that both steps should be done:

```suggestion
1. Resolve the canonical path of the file by using methods like java.io.File/getCanonicalPath. This will resolve relative path or path components like `../` and removes any ambiguity regarding the file's location. 
2. Check that the canonical path is within the directory where the file should be located.
```

2022-07-22 08:46 UTC, loris-s-sonarsource commented on rules/S2083/resources.adoc
> +== Resources
The `Resources` section is composed of subsections. I suggest adding the `Standards` subsection. See https://raw.githubusercontent.com/SonarSource/rspec/feature/education/rules/S5131/java/rule.adoc for hints on how it is done

2022-07-22 08:46 UTC, loris-s-sonarsource commented on rules/S2083/threats.adoc
> +The injected path component tempers with the location of a file the application is supposed to delete or write into. The vulnerability is exploited to remove or corrupt files that are critical for th
```suggestion
The injected path component tampers with the location of a file the application is supposed to delete or write into. The vulnerability is exploited to remove or corrupt files that are critical for the application or for the system to work properly.
```

2022-07-22 08:46 UTC, loris-s-sonarsource commented on rules/S2083/threats.adoc
> +The injected path component tempers with the location of a file the application is supposed to read and output. The vulnerability is exploited to leak the content of arbitrary files from the file sys
```suggestion
The injected path component tampers with the location of a file the application is supposed to read and output. The vulnerability is exploited to leak the content of arbitrary files from the file system, including sensitive like SSH private keys.
```

2022-07-25 07:04 UTC, pierre-loup-tristant-sonarsource commented on rules/S2083/java/rule.adoc
> +== Why is this an issue?
To me, this is out of scope for this MMF.

2022-07-25 08:10 UTC, pierre-loup-tristant-sonarsource commented on rules/S2083/impact.adoc
> +=== What is the potential impact?
Agreed. I will update the content. I also don't think it makes sens to have a file called `threats.adoc` and I will merge it in `impact.adoc`

2022-07-25 16:13 UTC, loris-s-sonarsource approved these changes
LGTM, 1 minor suggestion

2022-07-25 16:13 UTC, loris-s-sonarsource commented on rules/S2083/java/how-to-fix-it/java-se.adoc
> +The following code is vulnerable to path injection as it's contructing a path using untrusted data. This path is then use to delete a file without being validated first. Therefore, it can be leverage
```suggestion
The following code is vulnerable to path injection as it is constructing a path using untrusted data. This path is then used to delete a file without being validated first. Therefore, it can be leveraged by an attacker to delete arbitrary files.
```
grammar + it's->it is (writing standard initiative)

2022-07-26 07:39 UTC, pedro-oliveira-sonarsource reviewed
Minor suggestions.

2022-07-26 07:39 UTC, pedro-oliveira-sonarsource commented on rules/S2083/impact.adoc
> +A web application is vulnerable to a path injection and an attacker is able to exploit it.
```suggestion
A web application is vulnerable to path injection and an attacker is able to exploit it.
```

2022-07-26 07:39 UTC, pedro-oliveira-sonarsource commented on rules/S2083/rationale.adoc
> +A user with malicious intents would inject specially crafted values, such as ``++../++``, to change the initial path and, when accessed, resolve to a path on the filesystem where the user should norm
```suggestion
A user with malicious intent would inject specially crafted values, such as ``++../++``, to change the initial intended path. The resulting path would resolve somewhere in the filesystem where the user should not normally have access to.
```

2022-07-26 13:09 UTC, merged