add mobile security standards, links and tags to mobile rules
SonarSource/rspec pull request #112
Opened 2021-06-08 15:30 UTC by eric-therond-sonarsource

2021-06-09 13:01 UTC, agigleux requested changes

2021-06-09 14:11 UTC, eric-therond-sonarsource commented on rules/S4507/xml/metadata.json
> -    "owasp-a3"
s4507 for xml targets only the android debug mode for the moment, and there is an owasp mobile top 10 category for that: https://www.owasp.org/index.php/Mobile_Top_10_2016-M10-Extraneous_Functionality

Owasp A3 (Sensitive Data Exposure) is for **web** (not mobile) debug mode

2021-06-09 14:16 UTC, eric-therond-sonarsource commented on rules/S5324/see.adoc
>  * https://cwe.mitre.org/data/definitions/20.html[MITRE, CWE-20] - Improper Input Validation
Yeap I will do that

2021-06-09 14:42 UTC, agigleux commented on rules/S4507/xml/metadata.json
> -    "owasp-a3"
My bad, I thought you removed it at top level. All good then.

2021-06-10 07:50 UTC, agigleux approved these changes

2021-06-10 08:04 UTC, merged