Modify Rule S3649(common text): Education Framework (APPSEC-54)
SonarSource/rspec pull request #1120
Opened 2022-07-26 09:18 UTC by loris-s-sonarsource

Specification ticket: [APPSEC-54](https://sonarsource.atlassian.net/browse/APPSEC-54).

2022-08-04 08:41 UTC, pierre-loup-tristant-sonarsource requested changes
As discussed please rework the Impacts section.
I also added some improvement suggestions.

2022-08-04 08:41 UTC, pierre-loup-tristant-sonarsource commented on rules/S2076/impact.adoc
> +==== Chain OS injections with other vulnerabilities.
```suggestion
==== Root privilege escalation and rebound.
```

2022-08-04 08:41 UTC, pierre-loup-tristant-sonarsource commented on rules/S2076/common/fix/introduction.adoc
> +language's native SDK. +
```suggestion
Anything that can be done via operating system commands can usually be done via a
language's native SDK. +
```

2022-08-04 09:42 UTC, loris-s-sonarsource commented on rules/S2076/impact.adoc
> +After detecting the injection, attackers inject data into the vulnerable field
This is an assumption that the attack vector is actually a web application field. I found that the context where people would identify the most

2022-08-04 09:43 UTC, loris-s-sonarsource commented on rules/S2076/impact.adoc
> +After detecting the injection, attackers inject data into the vulnerable field
I'm going to use `parameter` instead, to make it aligned with the code samples

2022-08-04 15:08 UTC, loris-s-sonarsource commented on rules/S2076/impact.adoc
> +After detecting the injection, attackers inject data into the vulnerable field
No, I know. I will add a small disclaimer saying that we assume it's a field

2022-08-04 15:23 UTC, loris-s-sonarsource commented on rules/S2076/impact.adoc
> +attacker exploiting the vulnerability.
I created APPSEC-65 for this. And I will revert to the old format

2022-08-04 15:38 UTC, loris-s-sonarsource commented on rules/S2076/impact.adoc
> +After detecting the injection, attackers inject data into the vulnerable field
what about `text field` ? I made the modif a few minutes ago

2022-08-04 15:40 UTC, pierre-loup-tristant-sonarsource commented on rules/S2076/impact.adoc
> +After detecting the injection, attackers inject data into the vulnerable field
Yes, works too.

2022-08-04 16:03 UTC, loris-s-sonarsource commented on rules/S2076/rationale.adoc
> +underlying operating system.
I'm not a fan of sticking to patterns actually. I think it adds unnecessary constraints to our creativity when writing.

Do you think we should keep patterns in our texts for our users? Does it change something?

2022-08-04 16:06 UTC, loris-s-sonarsource commented on rules/S2076/common/fix/pre-approved-list.adoc
> +characters by using `^[a-zA-Z]{1-10}$`.
done

2022-08-04 16:09 UTC, loris-s-sonarsource commented on rules/S2076/rationale.adoc
> +underlying operating system.
To clarify : I'm doing the changes

2022-08-05 12:24 UTC, pierre-loup-tristant-sonarsource commented on rules/S2076/impact.adoc
> +section. The kicker is that the attacker also manages to elevate his privileges
"The kicker" seems familiar. What about "game changer"?

2022-08-05 12:28 UTC, pierre-loup-tristant-sonarsource approved these changes
LGTM. Two minor fixes to apply to the impact section.

2022-08-05 12:28 UTC, pierre-loup-tristant-sonarsource commented on rules/S2076/impact.adoc
> +section. The kicker is that the attacker also manages to elevate his privileges
"The kicker" seems familiar. What about "game changer"?

2022-08-05 12:28 UTC, pierre-loup-tristant-sonarsource commented on rules/S2076/impact.adoc
> +Depending on the underlying servers of the web application,
This pending sentence looks like it should be removed.
```suggestion
```

2022-08-05 12:32 UTC, loris-s-sonarsource commented on rules/S2076/impact.adoc
> +section. The kicker is that the attacker also manages to elevate his privileges
I didn't have the right word, but maybe even more simple would be "the difference", no ? "Game changer" looks like a happy impact

2022-08-05 12:32 UTC, loris-s-sonarsource commented on rules/S2076/impact.adoc
> +section. The kicker is that the attacker also manages to elevate his privileges
```suggestion
section. The difference is that the attacker also manages to elevate his privileges
```

2022-08-05 12:33 UTC, loris-s-sonarsource commented on rules/S2076/impact.adoc
> +Depending on the underlying servers of the web application,
you are right

2022-08-05 13:17 UTC, merged