Modify rule S1116: Add exception paragraph
SonarSource/rspec pull request #1124
Opened 2022-07-28 14:56 UTC by francoismora

Modify rule S1116: Add exception paragraph

2022-07-28 15:36 UTC, saberduck commented on rules/S1116/javascript/message.adoc
> +This rule does not apply when the semicolon is after a line break and before ``++(++`` or ``++[++``.
if possible we should explain why we added the exception

2022-07-28 15:36 UTC, saberduck requested changes
can you pls add the reason for exception (why)

2022-07-29 09:41 UTC, francoismora commented on rules/S1116/javascript/message.adoc
> +This rule does not apply when the semicolon is after a line break and before ``++(++`` or ``++[++``.
Updated

2022-07-29 09:42 UTC, francoismora commented
Fixes SonarSource/SonarJS#3250

2022-07-29 13:11 UTC, saberduck approved these changes

2022-07-29 13:11 UTC, merged