Modify rule S3358: Add an exception for JSX expressions.
SonarSource/rspec pull request #1125
Opened 2022-07-28 15:24 UTC by francoismora

Modify rule S3358: Add an exception for JSX expressions.

2022-07-28 15:37 UTC, saberduck requested changes

2022-07-28 15:37 UTC, saberduck commented on rules/S3358/javascript/rule.adoc
> +This rule does not apply in JSX expressions.
we should briefly explain the reason behind exception (eg. this is common pattern to nest ternaries)

2022-07-29 08:52 UTC, francoismora commented on rules/S3358/javascript/rule.adoc
> +This rule does not apply in JSX expressions.
Updated.

2022-07-29 09:41 UTC, francoismora commented on rules/S3358/javascript/rule.adoc
> +This rule does not apply in JSX expressions.
Fixes SonarSource/SonarJS#3244

2022-07-29 13:10 UTC, saberduck approved these changes

2022-07-29 13:11 UTC, merged