[APPSEC-57] Modify rule S5146: Educational content (Commons)
SonarSource/rspec pull request #1132
Opened 2022-08-02 08:19 UTC by pedro-oliveira-sonarsource

Specification ticket: [APPSEC-57](https://sonarsource.atlassian.net/browse/APPSEC-57).

2022-08-02 15:05 UTC, loris-s-sonarsource requested changes
Overall it looks good, I made suggestions about conciseness in general and about removing unnecessary files (and I hope it won't block the PR merge)

2022-08-03 07:45 UTC, pedro-oliveira-sonarsource commented on rules/S5146/impact.adoc
> +Redirection to an attacker's controlled website mirroring the interface of a web application trusted by the user. Due to the similarity in the application appearance and the apparently trustable clic
```suggestion
A malicious link redirects to an attacker's controlled website mirroring the interface of a web application trusted by the user. Due to the similarity in the application appearance and the apparently trustable clicked hyperlink, the user struggles to identify that they are browsing on a malicious domain. Depending on the attacker's purpose, the malicious website can leak credentials, bypass Multi-Factor Authentication (MFA), and reach any authenticated data or action.
```

Applied suggestions with two minor change.

2022-08-03 08:09 UTC, pedro-oliveira-sonarsource commented on rules/S5146/impact.adoc
> +User redirection to an attackers' controlled website which serves malicious files. On the same basis as the domain mirroring exploitation, the attacker develops a spearphishing or phishing campaign w
```suggestion
A malicious link redirects to an attacker's controlled website, which serves malware. On the same basis as the domain mirroring exploitation, the attacker develops a spearphishing or phishing campaign with a carefully crafted pretext that would result in the download and potential execution of a hosted malicious file. The worst could result in complete system compromise.
```

2022-08-03 08:21 UTC, pedro-oliveira-sonarsource commented on rules/S5146/impact.adoc
> +Manipulating the user into performing the HTTP request is usually the main task of exploiting an open redirection as, more often than not, requires an attacker to build a credible pretext to prevent
```suggestion
Manipulating the user into performing the HTTP request is usually the main task of exploiting an open redirection as, more often than not, requires an attacker to build a credible pretext to prevent any suspicions arising from the victim. Attackers commonly use open redirect exploits in mass phishing campaigns.
```

2022-08-03 08:28 UTC, pedro-oliveira-sonarsource commented on rules/S5146/impact.adoc
> +Manipulating the user into performing the HTTP request is usually the main task of exploiting an open redirection as, more often than not, requires an attacker to build a credible pretext to prevent
```suggestion
Tricking the user into performing the manipulated HTTP request is usually the main task of exploiting an open redirection. Often, it requires an attacker to build a credible pretext to prevent suspicions from the victim. Attackers commonly use open redirect exploits in mass phishing campaigns.
```

2022-08-03 08:28 UTC, pedro-oliveira-sonarsource commented on rules/S5146/impact.adoc
> +A web application redirects users to specific URLs based on user-controllable data. An attacker is able to manipulate a user to perform an HTTP request to the vulnerable web application. The HTTP req
```suggestion
A web application redirects users to specific URLs based on user-controllable data. An attacker can manipulate a user to perform an HTTP request to the vulnerable web application. The HTTP request contains maliciously injected data that would result in the user being redirected to an attacker's controlled evil domain.
```

2022-08-03 08:39 UTC, pedro-oliveira-sonarsource reviewed
Suggested changes applied.

2022-08-03 15:18 UTC, pedro-oliveira-sonarsource commented on rules/S5146/impact.adoc
> +
```suggestion
```

2022-08-03 15:22 UTC, pedro-oliveira-sonarsource commented on rules/S5146/rationale.adoc
> +An attacker with malicious intent could manipulate a user to browse into a specially crafted URL, such as ``++https://trusted.com?url=evil.com++``, in order to redirect the victim to his own evil dom
```suggestion
An attacker with malicious intent could manipulate a user to browse into a specially crafted URL, such as ``++https://example.com?url=evil.com++``, to redirect the victim to his evil domain.

Tricking users into sending the manipulated HTTP request is usually the main task of exploiting an open redirection. Often, it requires an attacker to build a credible pretext to prevent suspicions from the victim. Attackers commonly use open redirect exploits in mass phishing campaigns.
```

2022-08-04 09:39 UTC, loris-s-sonarsource requested changes
Last Changes suggestions and then it'll lgtm!

2022-08-04 09:39 UTC, loris-s-sonarsource commented on rules/S5146/impact.adoc
> +A web application redirects users to specific URLs based on user-controllable data. An attacker can manipulate a user to perform an HTTP request to the vulnerable web application. The HTTP request co
I just realized that this is a repetition of what's already said in the rationale, e.g.:
```
An attacker with malicious intent could manipulate a user to browse into a specially crafted URL, such as ``++https://example.com?url=evil.com++``, to redirect the victim to his evil domain.
```

So we can just leverage this text and say:

```suggestion
Once the attackers trick a user into opening the malicious link, the user is redirected to a malicious domain controlled by the attacker. +
From then on, the attacker can perform various malicious actions on the victim's browser, ranging from entirely harmless to extreme organizational impact.
```

2022-08-04 09:39 UTC, loris-s-sonarsource commented on rules/S5146/impact.adoc
> +A malicious link redirects to an attacker's controlled website mirroring the interface of a web application trusted by the user. Due to the similarity in the application appearance and the apparently
```suggestion
A malicious link redirects to an attacker's controlled website mirroring the interface of a web application trusted by the user. Due to the similarity in the application appearance and the apparently trustable clicked hyperlink, the user struggles to identify that they are browsing on a malicious domain. +
Depending on the attacker's purpose, the malicious website can leak credentials, bypass Multi-Factor Authentication (MFA), and reach any authenticated data or action.
```

Hard line break suggestion to make the reading breathable

2022-08-04 09:39 UTC, loris-s-sonarsource commented on rules/S5146/impact.adoc
> +A malicious link redirects to an attacker's controlled website that serves malware. On the same basis as the domain mirroring exploitation, the attacker develops a spearphishing or phishing campaign
```suggestion
A malicious link redirects to an attacker's controlled website that serves malware. On the same basis as the domain mirroring exploitation, the attacker develops a spearphishing or phishing campaign with a carefully crafted pretext that would result in the download and potential execution of a hosted malicious file. +
The worst-case scenario could result in complete system compromise.
```
hard line break to emphasize the last line

2022-08-04 09:39 UTC, loris-s-sonarsource commented on rules/S5146/rationale.adoc
> +An attacker with malicious intent could manipulate a user to browse into a specially crafted URL, such as ``++https://example.com?url=evil.com++``, to redirect the victim to his evil domain.
```suggestion
An attacker with malicious intent could manipulate a user to browse into a specially crafted URL, such as ``++https://trusted.example.com?url=evil.example.com++``, to redirect the victim to his evil domain.
```

Suggestion from Hendrik. WDYT?

2022-08-04 10:17 UTC, pedro-oliveira-sonarsource commented on rules/S5146/impact.adoc
> +A web application redirects users to specific URLs based on user-controllable data. An attacker can manipulate a user to perform an HTTP request to the vulnerable web application. The HTTP request co
```suggestion
A web application redirects users to specific URLs based on user-controllable data and an attacker is able to trick a user into submitting a domain controlled by him, thus forcing the user to be redirected.

From then on, the attacker can perform various malicious actions on the victim's browser, some more impactful than others.
```

2022-08-04 12:29 UTC, pedro-oliveira-sonarsource commented on rules/S5146/impact.adoc
> +Below are some real-world scenarios that illustrate the various effects of an attacker exploiting the vulnerability.
```suggestion
Below are some real-world scenarios that illustrate some impacts of an attacker exploiting the vulnerability.
```

2022-08-04 15:04 UTC, loris-s-sonarsource approved these changes
LGTM!

2022-08-04 15:16 UTC, merged