Modify Rule S5883(C#): Education Framework (APPSEC-53)
SonarSource/rspec pull request #1143
Opened 2022-08-04 10:09 UTC by loris-s-sonarsource

Specification ticket: [APPSEC-53](https://sonarsource.atlassian.net/browse/APPSEC-53).

2022-08-04 15:03 UTC, pierre-loup-tristant-sonarsource requested changes
Please fix:
- Broken rendering after the payload
- Payload itself
- Typo in the parameter name in the compliant code examples

Other comment are minor.

2022-08-04 15:03 UTC, pierre-loup-tristant-sonarsource commented on rules/S5883/csharp/how-to-fix-it/dotnet.adoc
> +creates a single string given to the operating system when `Process.Start()` is
```suggestion
creates a single string given to the operating system when `System.Diagnostics.Process.Start()` is
```

2022-08-05 09:55 UTC, loris-s-sonarsource commented on rules/S5883/csharp/how-to-fix-it/dotnet.adoc
> +-exec /bin/sh \; -quit
ah yeah I like the rm one, it's clearer

2022-08-05 11:34 UTC, loris-s-sonarsource commented on rules/S5883/common/fix/sanitize-meta-characters.adoc
> +internally, such as {sanitizationLib}.
```suggestion
internally, such as `{sanitizationLib}`.
```

2022-08-05 13:23 UTC, pierre-loup-tristant-sonarsource approved these changes
LGTM, one minor comment.

2022-08-05 13:23 UTC, pierre-loup-tristant-sonarsource commented on rules/S5883/csharp/how-to-fix-it/dotnet.adoc
>  In this particular case, an attacker may exploit the query with the following string:
Maybe you can mention that the payload will remove all file for the application root directory?

2022-08-05 13:27 UTC, loris-s-sonarsource commented on rules/S5883/csharp/how-to-fix-it/dotnet.adoc
>  In this particular case, an attacker may exploit the query with the following string:
yup, my bad !

2022-08-05 13:34 UTC, loris-s-sonarsource commented on rules/S5883/csharp/how-to-fix-it/dotnet.adoc
> +* -exec rm {} ;
```suggestion
'*' -exec echo rm -rf {} \; 
```

2022-08-05 13:34 UTC, loris-s-sonarsource commented on rules/S5883/csharp/how-to-fix-it/dotnet.adoc
> +to start a shell.
```suggestion
to forcefully remove files.
```

2022-08-05 13:36 UTC, loris-s-sonarsource commented on rules/S5883/csharp/how-to-fix-it/dotnet.adoc
> +to forcefully remove files in `/some/folder`.
```suggestion
to remove files in `/some/folder`.
```

2022-08-05 13:38 UTC, loris-s-sonarsource commented on rules/S5883/csharp/how-to-fix-it/dotnet.adoc
> +In this particular case, an attacker may exploit the query with the following string:
```suggestion
of characters and ignores that some characters might force the `find` command
to start a shell.

In this particular case, an attacker may remove files in `/some/folder` with the following string:
```

2022-08-05 13:43 UTC, merged