Fix the 'add language' section of the README
SonarSource/rspec pull request #115
Opened 2021-06-09 12:52 UTC by eric-therond-sonarsource

I suggest to remove this sentence in the readme:
```
 (i.e. the rule has not been implemented by any plugin)
 ````

It's a bit confusing, or I missed something, we can have the case where:
- a PR to create a rule/rspec targeting a language, for instance java, is created then merged
- the rule is not yet implemented in the sonar java plugin but we realize that this rule should target another language, let's say kotlin
- so there is no existing open PR for this rule and the rule is not yet implemented by any plugin, and thus we need to create a new PR `Create rule SXXXX[kotlin]`

2021-06-09 13:15 UTC, arseniy-sonar commented
Hi, @eric-therond-sonarsource 
The [section 4](https://github.com/SonarSource/rspec#4-implement-the-rule) in the readme is supposed to recommend merging the RSPEC PR as soon as the rule is implemented in the plugin.
If the RSPEC PR is merged immediately before the implementation ticket is merged, the situation you describe in the second bullet point is very unlikely.
If this policy (that I admit needs to be clarified) is followed we are left with two options:
- add another language to the open PR if the rule is not yet implemented
- open a new PR modifying the existing merged rule, add another language, implement it, then merge the new PR.

Now, to clarify the aforementioned Section 4: do you think the following paragraph would do the job?

## 4. Implement the rule

Implement the rule or the modification as usual.

Only once the implementation is complete, but before it is merged on the analyzer side, merge the RSPEC PR. RSPEC PR has to be merged before the implementation PR to enable rule-api to fetch the correct metadata in the analyzer. RSPEC PR has to be merged as close as possible to the merge of the implementation PR to shorten the time span of the inconsistency in the rule status ("active" in the RSPEC metadata, and not implemented on the analyzer side).

Finally, merge the rule implementation in your analyzer repository.

2021-06-09 15:13 UTC, arseniy-sonar commented
Yes, the steps you described are correct.

The issue of a rule specified for many languages and implemented for one of them sounds valid. I might be missing something but I believe our instructions do not cover this case.
I would propose the following:
- the rspecator opens an RSPEC PR and specifies a rule for multiple languages
- the analyzer developer implements the rule for their language, before all other analyzers.
- the analyzer developer adds their language to the "coveredLanguages" set in the rule metadata
- the analyzer developer merges the RSPEC PR
- the analyzer developer fetches the metadata to their analyzer
- the analyzer developer merges the implementation in their analyzer repository
- when another analyzer developer implements the rule for their language, they create a "Change rule S####" PR where they add their language to the "coveredLanguages" set; merge it; merge the implementation.


@loic-joly-sonarsource, @amelie-foulc-sonarsource, Does this process look reasonable?

2021-06-10 13:46 UTC, arseniy-sonar reviewed
Following our discussion here, as well as, over slack and e-mail, I pushed the changes directly to this pr. @eric-therond-sonarsource , could you, please, take a look and confirm that the workflow is more clear now?

2021-06-10 14:58 UTC, amelie-renard-sonarsource requested changes
Mainly typos, you can merge after the correction

2021-06-10 14:58 UTC, amelie-renard-sonarsource commented on README.adoc
> +Multi-language rule creation is more involved than the default process because it involves multiple roles that typically do not conicide.
```suggestion
Multi-language rule creation is more involved than the default process because it involves multiple roles that typically do not coincide.
```

2021-06-10 14:58 UTC, amelie-renard-sonarsource commented on README.adoc
> +The workflow below makes sure that for all rules on the main branch are implemented for all languages they are specified for or for all languages listed in `"coveredLanguages"`.
```suggestion
The workflow below makes sure that all rules on the main branch are implemented for all languages they are specified for or for all languages listed in `"coveredLanguages"`.
```

2021-06-10 14:58 UTC, amelie-renard-sonarsource commented on README.adoc
> +`"extra"."coveredLanguages"` contains the languages rule is implemented for.
```suggestion
`"extra"."coveredLanguages"` contains the languages the rule is implemented for.
```

2021-06-10 14:58 UTC, amelie-renard-sonarsource commented on README.adoc
> +.. Alice adds Ada to `"coveredLanguages"` (`"extra": {"coveredLanguages": ["Ada"]}`).
Maybe specify that this is on rspec PR side

2021-06-10 14:58 UTC, amelie-renard-sonarsource commented on rspec-tools/rspec_tools/validation/rule-metadata-schema.json
> +          "description": "The rule ids for tules that replace this rule"
```suggestion
          "description": "The rule ids that replace this rule"
```

2021-06-10 15:09 UTC, arseniy-sonar commented on README.adoc
> +.. Alice adds Ada to `"coveredLanguages"` (`"extra": {"coveredLanguages": ["Ada"]}`).
Makes sense. done.

2021-06-10 15:18 UTC, pierre-loup-tristant-sonarsource commented on README.adoc
> +. Bob opens a new RSPEC PR "Create rule S100[cobol]" to add `"Cobol"` to `"coveredLangauges"` (`"extra": {"coveredLanguages": ["Ada", "Cobol"]}`).
Here I think the PR title should follow the "Modify" convention: 
> Modify rule S100: Add Cobol support

2021-06-11 05:37 UTC, arseniy-sonar commented on README.adoc
> +. Bob opens a new RSPEC PR "Create rule S100[cobol]" to add `"Cobol"` to `"coveredLangauges"` (`"extra": {"coveredLanguages": ["Ada", "Cobol"]}`).
Sure.

2021-06-11 05:58 UTC, merged