Modify Rule S5135(common text): Education Framework (APPSEC-75)
SonarSource/rspec pull request #1171
Opened 2022-08-22 15:34 UTC by loris-s-sonarsource

2022-08-25 09:08 UTC, hendrik-buchwald-sonarsource requested changes
Left some comments.

2022-08-25 09:08 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/impact.adoc
> +* Docker or Kubernetes clusters.
Since it is an enumeration, no dots.

```suggestion
* Docker or Kubernetes clusters
```

2022-08-25 09:08 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/impact.adoc
> +* Network firewalls and routing.
Not a name (like Docker).

```suggestion
* network firewalls and routing
```

2022-08-25 09:08 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/impact.adoc
> +* OS access control OS access control
```suggestion
* OS access control
```

2022-08-25 09:08 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/impact.adoc
> +perform unwanted actions. In the context of an e-commerce application, this
I think the example is not bad to illustrate the danger but it does not seem to be related to the title "Privilege escalation within the application". Maybe a different title would fit this section better?

2022-08-25 09:08 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/impact.adoc
> +* Injecting an object of a completely different class than expected, triggering code execution.
The way it is worded, it sounds a bit like only in the second case there would be code execution.

2022-08-25 09:12 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/integrity-check.adoc
> +* Sign the object on the client side using a secure algorithm such as Hmac.
Oh yes, good point. I forgot about the required key for a moment

2022-08-25 09:16 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/pre-approved-list.adoc
> +application should be able to deserialize. +
Yes, that's what I thought too. I figured there was a reason why this was written in the rule, so I kept this, and I kept the code sample. But I totally agree. I will figure out another code sample

2022-08-25 09:22 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/common/fix/pre-approved-list.adoc
> +application should be able to deserialize. +
Maybe we were thinking of something like [`allowed_classes` from PHP](https://www.php.net/unserialize) when we wrote it (aka a feature of the deserialization library to restrict the classes) but even there it says in the red box that it should not be trusted for security purposes:

> Do not pass untrusted user input to unserialize() regardless of the options value of allowed_classes. Unserialization can result in code being loaded and executed due to object instantiation and autoloading, and a malicious user may be able to exploit this. Use a safe, standard data interchange format such as JSON (via [json_decode()](https://www.php.net/manual/en/function.json-decode.php) and [json_encode()](https://www.php.net/manual/en/function.json-encode.php)) if you need to pass serialized data to the user.
> If you need to unserialize externally-stored serialized data, consider using [hash_hmac()](https://www.php.net/manual/en/function.hash-hmac.php) for data validation. Make sure data is not modified by anyone but you.

2022-08-25 09:23 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/common/fix/pre-approved-list.adoc
> +application should be able to deserialize. +
Also, "standard data interchange format" might be a nice wording to add in your JSON-fix section.

2022-08-25 09:32 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/pre-approved-list.adoc
> +==== Pre-Approved commands
```suggestion
==== Pre-Approved classes
```

2022-08-25 09:46 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/pre-approved-list.adoc
> +application should be able to deserialize. +
Do you think this suggestion from PHP's docs also applies to other languages? We have equivalents in java's kryo lib, and Dotnet's XmlSerialize

2022-08-25 09:48 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/common/fix/pre-approved-list.adoc
> +application should be able to deserialize. +
The HMAC and JSON suggestions, yes. If limiting the classes is secure in Kryo or XmlSerialize I don't know.

2022-08-25 09:54 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/pre-approved-list.adoc
> +application should be able to deserialize. +
Yes, to clarify, I meant class limitations. I am going to check

2022-08-25 10:03 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/pre-approved-list.adoc
> +application should be able to deserialize. +
Ok, so these PHP guidelines will prevent us from including this file in the future.

WDYT:
I think that we should clarify that the pre-approved classes/types should be used during deserialization, so either by overwriting the serialization process, or using its native capabilities to limit the type deserialization.

For example, the .Net Framework takes an expected type as a parameter, and for java, we recommend overwriting the resolveClass function. So in both ways, this is not used after the deserialization process, but during the deserialization process.

Here is the new java description: https://github.com/SonarSource/rspec/blob/098d7f4384a065415067c5f60574c315ab85b231/rules/S5135/java/how-to-fix-it/java-se.adoc

Here is the new C# description: https://github.com/SonarSource/rspec/blob/06a50f224fcc55ff6ad4cc7b8797120f78038f48/rules/S5135/csharp/how-to-fix-it/dotnet.adoc

2022-08-26 12:53 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/integrity-check.adoc
> +In cases where objects are known to the backend:
I modified it to better express what I mean

2022-08-26 12:56 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/integrity-check.adoc
> +**Note**: The more objects, the less scalable this solution is.
Hmm good point, I changed the note to something about secrets.

2022-08-26 12:57 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/introduction.adoc
> +justified and led to security vulnerabilities (CVE-2017-9785).
Hey, yes good point. I wanted to keep what was already in the existing rule but I'm removing it

2022-08-26 13:09 UTC, loris-s-sonarsource commented on rules/S5135/impact.adoc
> +* Injecting an object of a completely different class than expected, triggering code execution.
Ok, I dispatched the two bullet points into the two sections

2022-08-26 15:06 UTC, hendrik-buchwald-sonarsource requested changes
In general, it looks good to me +1 I have found a few details though that I think are still worth updating.

2022-08-26 15:06 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/impact.adoc
> +In this scenario, the attacker succeed in injecting an object of the expected
```suggestion
In this scenario, the attackers succeed in injecting an object of the expected
```

2022-08-26 15:06 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/impact.adoc
> +In this worst-case scenario, the attackers succeed in injecting an object of a
```suggestion
In the worst-case scenario, the attackers succeed in injecting an object of a
```

2022-08-26 15:06 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/impact.adoc
> +* Modify data, send malware - Most likely malware that mines cryptocurrencies.
"Most likely" is quite speculative. There are many types of malware.

```suggestion
* Modify data, install malware, for instance, malware that mines cryptocurrencies.
```

2022-08-26 15:06 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/impact.adoc
> +* Stop services or exhaust resources (with fork bombs).
```suggestion
* Stop services or exhaust resources, for instance, with fork bombs.
```

As per the style guide, it is better to avoid the parentheses here.

2022-08-26 15:10 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/integrity-check.adoc
> +When the backend expects only particular objects as user input:
Yes, I mean that the developper needs to know what objects are expected if we want to match signatures, no ?

2022-08-26 15:14 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/integrity-check.adoc
> +When the backend expects only particular objects as user input:
My point is `If the application knows before deserialization which messages will need to be processed, they could sign them as part of the serialization process.` (but this is OWASP's own words haha)

2022-08-26 15:18 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/integrity-check.adoc
> +* Sign the object on the server side using a secure algorithm such as HMAC.
should we mention a shared secret ?

2022-08-26 15:24 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/integrity-check.adoc
> +When the backend expects only particular objects as user input:
My bad, I had was in a distorted mindset about signature

2022-08-29 08:23 UTC, hendrik-buchwald-sonarsource approved these changes
LGTM

2022-08-29 08:24 UTC, hendrik-buchwald-sonarsource commented on rules/S5135/common/fix/integrity-check.adoc
> +=== Integrity check
Is it really right that this one only has 3 equals?

2022-08-29 08:53 UTC, loris-s-sonarsource commented on rules/S5135/common/fix/integrity-check.adoc
> +=== Integrity check
good catch ! 
```suggestion
==== Integrity check
```

2022-08-29 09:50 UTC, merged