po/education/s5145/common
SonarSource/rspec pull request #1173
Opened 2022-08-23 07:37 UTC by pedro-oliveira-sonarsource

Specification ticket: [APPSEC-81](https://sonarsource.atlassian.net/browse/APPSEC-81).

2022-08-25 09:56 UTC, pierre-loup-tristant-sonarsource commented on rules/S5145/common/resources/standards.adoc
> +* https://owasp.org/www-project-top-ten/2017/A1_2017-Injection[OWASP Top 10 2017 Category A1] - Injection
Maybe it would make sense to update OWASP top 10 2017 and 2021 mapping because I think it fits both Injection and "Security Logging and Monitoring Failures".

2022-08-25 12:07 UTC, pierre-loup-tristant-sonarsource requested changes
I think the content should focus on the log forging attack vector. Therefore it should explain the role of newline characters.

2022-08-25 12:07 UTC, pierre-loup-tristant-sonarsource commented on rules/S5145/impact.adoc
> +If an attacker can insert arbitrary data into a log file, the integrity of the chain of events being recorded is compromised. +
Maybe you can explain that log entries are usually separated by new lines. It's not uncommon to be able to add arbitrary data to a log entry. What is the problem here is the ability to add new lines to forge artificial entries.
User should be able to understand this.

2022-08-25 12:07 UTC, pierre-loup-tristant-sonarsource commented on rules/S5145/impact.adoc
> +An attacker inserts bogus data into a log file to conceal his malicious activities. This obscures the content for an incident response team to trace the origin of the breach as the indicators of comp
Here again, explain how new line characters make it able to forge log entries.

2022-08-25 12:07 UTC, pierre-loup-tristant-sonarsource commented on rules/S5145/impact.adoc
> +A notorious vulnerability, also known as Log4Shell, found in the popular Java logging framework Log4j, is an example of such a vector.
Again, I am pretty sure the rule will not protect you against such attacks.

2022-08-25 12:07 UTC, pierre-loup-tristant-sonarsource commented on rules/S5145/impact.adoc
> +Other attacks, such as cross-site scripting (XSS) or code injection, could also occur if the logged data is fed to other vulnerable application components.
True but I am pretty sure the rule will not protect you against such attacks.

2022-08-25 12:28 UTC, pedro-oliveira-sonarsource commented on rules/S5145/impact.adoc
> +If an attacker can insert arbitrary data into a log file, the integrity of the chain of events being recorded is compromised. +
```suggestion
If an attacker can insert arbitrary data into a log file, the integrity of the chain of events being recorded is compromised. This occurs because the attacker is able to inject the log entry separator of the target system, commonly newlines and thus insert artificial log entries.  +
```

2022-08-25 12:31 UTC, pedro-oliveira-sonarsource commented on rules/S5145/impact.adoc
> +An attacker inserts bogus data into a log file to conceal his malicious activities. This obscures the content for an incident response team to trace the origin of the breach as the indicators of comp
```suggestion
An attacker, able to create independent log entries by injecting the log separator, inserts bogus data into a log file to conceal his malicious activities. This obscures the content for an incident response team to trace the origin of the breach as the indicators of compromise (IoCs) lead to fake application events.
```

2022-08-25 14:07 UTC, pedro-oliveira-sonarsource commented on rules/S5145/common/resources/standards.adoc
> +* https://owasp.org/www-project-top-ten/2017/A1_2017-Injection[OWASP Top 10 2017 Category A1] - Injection
I think we can drop the 2021 A9, nowhere in the OWASP page mentions injection, rather it scopes lack of scope, event reaction or improper storage.

2022-08-26 11:46 UTC, pedro-oliveira-sonarsource commented on rules/S5145/impact.adoc
> +Other attacks, such as cross-site scripting (XSS) or code injection, could also occur if the logged data is fed to other vulnerable application components.
Kept the mention of the other attacks, but added some clarification over the coverage

2022-08-26 12:48 UTC, pierre-loup-tristant-sonarsource approved these changes
LGTM

2022-08-26 13:09 UTC, merged