Modify S5147(Common text): Update to the education framework (APPSEC-94)
SonarSource/rspec pull request #1195
Opened 2022-08-29 15:17 UTC by loris-s-sonarsource

Related to [**APPSEC-94**](https://sonarsource.atlassian.net/browse/APPSEC-94).

2022-08-31 09:47 UTC, pedro-oliveira-sonarsource requested changes
Just some suggestions.

2022-08-31 09:47 UTC, pedro-oliveira-sonarsource commented on rules/S5147/common/fix/validation.adoc
> +data to the expression associated with it makes the query vulnerable.
Maybe we could also refer to avoid specific sensitive operators.

Example 'where' in MongoDB:
query = { $where: this.username == '${username}' }
you would be able to inject plain JavaScript syntax, e.g || 'a'=='a

2022-08-31 09:47 UTC, pedro-oliveira-sonarsource commented on rules/S5147/common/fix/validation.adoc
> +The list can be either a regex string, an array, or validators on specific
Due to the wording, it comes across to me as if you're doing a string comparison to all these elements instead of a pattern match for regexs for example.

2022-08-31 09:47 UTC, pedro-oliveira-sonarsource commented on rules/S5147/impact.adoc
> +==== Identity spoofing and data manipulation
Because you mention data deletion on the next one, might be best to be specific on this one as well.
```suggestion
==== Identity spoofing and data leakage
```

2022-08-31 09:47 UTC, pedro-oliveira-sonarsource commented on rules/S5147/impact.adoc
> +maintain a disaster recovery plan (DRP).
Just to be clear regarding the DoS.
```suggestion
maintain a disaster recovery plan (DRP) as missing data can disrupt the regular
operations of an organization.
```

2022-08-31 09:47 UTC, pedro-oliveira-sonarsource commented on rules/S5147/rationale.adoc
> +without sanitizing it first.
```suggestion
NoSQL injections occur when an application retrieves untrusted data and inserts
it into a database query without sanitizing it first.
```

2022-08-31 09:52 UTC, loris-s-sonarsource commented on rules/S5147/common/fix/validation.adoc
> +using it in a NoSQL query.
Ah yeah, maybe we should write about Neo4J somewhere. For now we don't support it so I don't see a point in adding it now

2022-08-31 12:43 UTC, loris-s-sonarsource commented on rules/S5147/common/fix/validation.adoc
> +*Important note*: The application must do validation on the server side. Not on
I don't see the difference between both versions, except wording

2022-08-31 12:44 UTC, loris-s-sonarsource commented on rules/S5147/common/fix/validation.adoc
> +First, restrict the use of operators. +
Unfortunately, we don't support them yet, so it's not really in scope for now

2022-08-31 12:47 UTC, loris-s-sonarsource commented on rules/S5147/common/fix/validation.adoc
> +data to the expression associated with it makes the query vulnerable.
Yeah, at first I thought about listing especially bad operators, and even creating a subsection about it (https://www.mongodb.com/docs/manual/core/server-side-javascript/)

But it seemed overkill at the time, and also a kind of validation. Do you think it makes sense to still create this subsection? It would list bad operators, mention the server-side scripting and the fact that we can disable it

2022-08-31 12:49 UTC, loris-s-sonarsource commented on rules/S5147/common/fix/validation.adoc
> +The list can be either a regex string, an array, or validators on specific
which elements are you talking about ? Because yeah, the goal would be to provide user input validation

2022-08-31 12:50 UTC, loris-s-sonarsource commented on rules/S5147/common/fix/validation.adoc
> +using it in a NoSQL query.
Maybe we should create a ticket about it, but I think we actually need to see which NoSQL libraries would actually be useful in the future

2022-08-31 13:01 UTC, loris-s-sonarsource commented on rules/S5147/common/fix/validation.adoc
> +using it in a NoSQL query.
I created a ticket for this: [**APPSEC-113**](https://sonarsource.atlassian.net/browse/APPSEC-113)

2022-09-01 08:00 UTC, loris-s-sonarsource commented on rules/S5147/common/fix/dangerous-operators.adoc
> +For example, a `$where` operator is excessive when only a simple search is
```suggestion
For example, using a `$where` operator is unnecessarily complex when only a simple search is
```

2022-09-01 08:02 UTC, loris-s-sonarsource commented on rules/S5147/common/fix/dangerous-operators.adoc
> +required. It also leads to performance problems.
```suggestion
For example, using a `$where` operator is unnecessarily complex when only a
simple search is required. It also leads to performance problems.
```

2022-09-01 09:10 UTC, pedro-oliveira-sonarsource approved these changes
Just some minor suggestions, LGTM.

2022-09-01 09:10 UTC, pedro-oliveira-sonarsource commented on rules/S5147/common/fix/dangerous-operators.adoc
> +Depending on your use case, you should first try all the ways to use regular
```suggestion
Depending on your use case, you should first try using regular
```

2022-09-01 09:10 UTC, pedro-oliveira-sonarsource commented on rules/S5147/common/fix/dangerous-operators.adoc
> +Regular operators can also lead to data leaks. +
Seems it requires further description.

2022-09-01 09:10 UTC, pedro-oliveira-sonarsource commented on rules/S5147/impact.adoc
> +from one or more databases. This threat is the most widespread impact.
I think this one could get a bit more improved.
Perhaps instead of 'Identity Spoofing' say 'Privilege Escalation' and on the description of it, elaborate on how the 'malicious database query enables privilege escalation', perhaps talking about database misconfigurations.

2022-09-01 09:10 UTC, pedro-oliveira-sonarsource commented on rules/S5147/impact.adoc
> +==== Chaining DB injections with other vulnerabilities
```suggestion
==== Chaining NoSQL injections with other vulnerabilities
```

2022-09-01 09:55 UTC, loris-s-sonarsource commented on rules/S5147/impact.adoc
> +from one or more databases. This threat is the most widespread impact.
This one is actually really about simple queries, so I think it could be unnecessarily complex to talk about DB misconfigs here tbh

2022-09-01 09:55 UTC, loris-s-sonarsource commented on rules/S5147/impact.adoc
> +from one or more databases. This threat is the most widespread impact.
I will mention the simple queries for clarity's sake

2022-09-01 15:08 UTC, merged