Modify rule S5334(Java): Add Educational content (APPSEC-95)
SonarSource/rspec pull request #1196
Opened 2022-08-29 15:46 UTC by loris-s-sonarsource

Related to [**APPSEC-95**](https://sonarsource.atlassian.net/browse/APPSEC-95).

2022-08-31 11:55 UTC, pedro-oliveira-sonarsource requested changes
Have a look at the non-compliant code example.

2022-08-31 11:55 UTC, pedro-oliveira-sonarsource commented on rules/S5147/java/how-to-fix-it/mongo-java-driver.adoc
> +    query.put("$where", "this.field == \"" + input + "\""); // Noncompliant
Non-compliant code is not flagging.

2022-08-31 11:55 UTC, pedro-oliveira-sonarsource commented on rules/S5147/java/how-to-fix-it/mongo-java-driver.adoc
> +enough.
We could give a bit more emphasis to these types of solutions in the how-to-fix-it section referring to them as safe built-in methods or something.

2022-08-31 13:12 UTC, loris-s-sonarsource commented on rules/S5147/java/how-to-fix-it/mongo-java-driver.adoc
> +interpreted by the `$where` expression.
I'm going to slightly adjust your suggestion, to add the technical impact:

```suggestion
The following code is vulnerable to NoSQL injections because untrusted data is
concatenated to the `$where` operator. In this case, the untrusted data will be
interpreted as code, instead of a regular string.
```

2022-08-31 13:17 UTC, loris-s-sonarsource commented on rules/S5147/java/how-to-fix-it/mongo-java-driver.adoc
> +----
I'm not sure about adding imports... It's likely to end up as a big chuck of lines in the end, and IMHO this could be more of a clutter.

Since this code will be shown to people that have the exact same library, I'm not sure I would do this. But this can be debatable. WDYT?

2022-08-31 13:19 UTC, loris-s-sonarsource commented on rules/S5147/java/how-to-fix-it/mongo-java-driver.adoc
> +enough.
Yes, I think we could definitely use a part about "why you shouldn't use operators". I keep this in mind.

2022-09-01 10:02 UTC, pedro-oliveira-sonarsource requested changes
Just the fix on the compliant solution already discussed.

2022-09-01 10:02 UTC, pedro-oliveira-sonarsource commented on rules/S5147/java/how-to-fix-it/mongo-java-driver.adoc
> +    query.put("field", input);
Since the put method is not supported, we should provide a different compliant solution (if there is any).

2022-09-01 10:07 UTC, loris-s-sonarsource commented on rules/S5147/java/how-to-fix-it/mongo-java-driver.adoc
> +    query.put("field", input);
```suggestion
    query.append("field", input);
```

2022-09-01 12:11 UTC, loris-s-sonarsource commented on rules/S5147/java/how-to-fix-it/mongo-java-driver.adoc
> +----
I added imports in the end, it should be alright 👍

2022-09-01 12:36 UTC, pedro-oliveira-sonarsource approved these changes
LGTM.

2022-09-01 15:08 UTC, merged