Modify S2078(Common text): Update to the education framework (APPSEC-121)
SonarSource/rspec pull request #1210
Opened 2022-09-05 12:40 UTC by loris-s-sonarsource

Doubts on Java encodeFor... here.

2022-09-05 14:41 UTC, loris-s-sonarsource commented on rules/S2078/common/fix/validation.adoc
> +allow sanitizing these characters automatically.
Needs discussion

2022-09-06 09:11 UTC, loris-s-sonarsource commented on rules/S2078/impact.adoc
> +=== What are the possible effects?
```suggestion
=== What is the possible impact?
```

2022-09-06 12:20 UTC, pedro-oliveira-sonarsource requested changes
Just some suggestions for you to review.

2022-09-06 12:39 UTC, pedro-oliveira-sonarsource commented on rules/S2078/common/fix/validation.adoc
> +
Disregard this, saw you already added that on the Java how-to-fix-it section which comes after including the validation.adoc.

2022-09-06 13:40 UTC, loris-s-sonarsource commented on rules/S2078/common/fix/validation.adoc
> +
Ok, and for dotnet we don't actually support one yet :(

2022-09-06 13:48 UTC, pedro-oliveira-sonarsource approved these changes
LGTM.

2022-09-08 08:58 UTC, merged