[APPSEC-122] Modify rule S6287: Educational content (Common)
SonarSource/rspec pull request #1217
Opened 2022-09-06 08:51 UTC by pedro-oliveira-sonarsource

Specification ticket: [APPSEC-122](https://sonarsource.atlassian.net/browse/APPSEC-122).

2022-09-06 13:14 UTC, loris-s-sonarsource requested changes
A few suggestions to add stuff, it's looking good already 👍

2022-09-06 13:14 UTC, loris-s-sonarsource commented on rules/S6287/impact.adoc
> +into browsing within an application session to which they also have access.
# Multiple linked suggestions

##  Introductory impact

This sentence is slightly confusing me near the end. 

Before all, I would suggest we use the same turns of phrase as in the xss rule. e.g. we introduce the subject of phishing in the rationale, and then say:

```suggestion
A well-intentioned user opens a malicious link that injects a cookie in the web
application. This cookie forces the user into unknowingly browsing into a session
that isn't theirs.
```

And then I would suggest using this premise in the following subsection. 
For example, by starting with `"If the application does X this way, Y wan happen"`

This could allow us to get rid of the introductory `An attacker manipulates a user into browsing an application using a session cookie[...]`

##  Threat examples

* In the "Sensitive Data Disclosure", section, thanks to the introductory stuff I suggest, we could talk specific handling of personal data, and talk about sensitive stuff (credit cards, names, addresses, application-specific sensitive stuff)

* In the Vulnerability chaining, maybe we could also mention some little XSS impacts, not a lot but just enough to make think about impacts

WDYT?

2022-09-06 13:14 UTC, loris-s-sonarsource commented on rules/S6287/rationale.adoc
> +data.
```suggestion
Session Cookie Injections occur in a web application when it assigns session
cookies to users using untrusted data.
```

2022-09-06 13:14 UTC, loris-s-sonarsource commented on rules/S6287/rationale.adoc
> +techniques.
I would also use what's already been done in the XSS rule for consistency:

```
When well-intentioned users open a link to a page that is vulnerable to
session cookie injection, they are exposed to attacks that target their own
browser.

A user with malicious intent carefully crafts the link beforehand, and after
creating this link, the attacker must use phishing techniques to ensure that
his target users click on the link.
```

wdyt?

2022-09-06 14:07 UTC, pedro-oliveira-sonarsource commented on rules/S6287/rationale.adoc
> +techniques.
I think moving a little outside of those constant structures is good as long as it is correct, or the readers will keep reading the same thing over and over again.

2022-09-06 15:40 UTC, loris-s-sonarsource approved these changes
LGTM, with some suggestions and discussions

2022-09-06 15:40 UTC, loris-s-sonarsource commented on rules/S6287/impact.adoc
> +on what type of data is disclosed.
Why not giving an example and talk about data sensitivity, such as personal data?
A text like the one below could actually give an example and still keep text concise, since we only have like 3 lines:

```
For example, leaks could involve strictly confidential user data or organizational data.
```

2022-09-06 15:40 UTC, loris-s-sonarsource commented on rules/S6287/rationale.adoc
> +techniques.
Well, the suggested text is correct; and this structure could also be used only in phishing-related rules, so for now that's only the XSS rule and this one. 

To be clear with my initial intention, it was not to overwrite everything but to merge and adjust them and give added value in terms of education. The goal of the XSS text is to add more pedagogy.

I think both suggestions (the PR one and the XSS one) are valid on their own, but I still think that we miss out on user-friendly education here by not merging them. And since it's already validated by the team, why not use it?

2022-09-06 15:40 UTC, loris-s-sonarsource commented on rules/S6287/impact.adoc
> +including credential stealing using mirrored login pages.
```suggestion
on the target application. +
The victim browses the vulnerable page using the attacker's session and is
affected by the XSS, which can then be used for a wide range of attacks
including credential stealing using mirrored login pages.
```

I suggest a line break to make the paragraph breathable

2022-09-07 07:07 UTC, pedro-oliveira-sonarsource commented on rules/S6287/rationale.adoc
> +techniques.
What is the added pedagogy value from the XSS text compared to what was written?

2022-09-07 07:09 UTC, pedro-oliveira-sonarsource commented on rules/S6287/impact.adoc
> +on what type of data is disclosed.
Was following along what was written in for LDAP "The impact of this vulnerability depends on how vital LDAP servers are to the organization.".

2022-09-07 08:29 UTC, loris-s-sonarsource commented on rules/S6287/rationale.adoc
> +techniques.
@pedro-oliveira-sonarsource 

> What is the added pedagogy value from the XSS text compared to what was written?
The "story-telling" writing style of the XSS is its educative added value, because it adds continuity and user-friendliness to the text.

> I think this is extremely vague 
The goal of the XSS text is to introduce the impact in a user-friendly way. Here, after reading this, the question that could be asked is "what attacks ?" And the impacts section aims to actually answer this. 

> I think it lacks concision for this rule.
This is actually the same size as the suggestion of the PR, so I'm not sure I understand. And since the initial goal is to introduce impacts, maybe we have a misalignment.

2022-09-07 09:00 UTC, loris-s-sonarsource commented on rules/S6287/rationale.adoc
> +application.
```suggestion
Session cookies are used by web applications to identify users. Thus,
controlling these enable control over the identity of the users within the
application.
```

2022-09-07 09:04 UTC, loris-s-sonarsource commented on rules/S6287/rationale.adoc
> +techniques.
Solved in internal discussion

2022-09-07 09:27 UTC, loris-s-sonarsource commented on rules/S6287/impact.adoc
> +on what type of data is disclosed.
👍

2022-09-07 13:10 UTC, merged