Modify rule S2631(Common): Update text to Education Framework structure (APPSEC-125)
SonarSource/rspec pull request #1218
Opened 2022-09-06 10:04 UTC by loris-s-sonarsource

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource requested changes
Just some suggestions.

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource commented on rules/S2631/common/fix/validation.adoc
> +Another clean method is to validate the input before using it to scan a string.
I think we can remove this line and introduce the following with something like, "As an alternative..." and refer to it as an allow-list approach.

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource commented on rules/S2631/common/fix/validation.adoc
> +attacks.
I think this is not very clear, and it appears to add some slighlty  duplicated content namely on the "validators on specific ranges of characters", maybe we can remove it.

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource commented on rules/S2631/impact.adoc
> +vulnerable field to make the application inaccessible.
```suggestion
vulnerable field to make the affected component inaccessible.
```

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource commented on rules/S2631/impact.adoc
> +carefully crafted input (thousands chars).
```suggestion
carefully crafted input (thousands of chars).
```

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource commented on rules/S2631/impact.adoc
> +failure of a container and automatically replace it.
Nice content :) Not sure if its worth mentioning or not but, if the previously used container is not properly terminated, you can still exhaust the container creation due to defined quotas which would result in DoS for other users as well.

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource commented on rules/S2631/impact.adoc
> +* When the injection is performed in a SPOF component that acts as a bottleneck.
```suggestion
* When the injection is performed in a SPOF component that acts as a bottleneck for other users.
```

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource commented on rules/S2631/impact.adoc
> +* When the attacker (or a group of attackers) performs a Distributed Denial of Service.
This second element doesn't seem to be appropriate and of the same category as the first bullet point. It's very generic to DoS attacks. I think only discussing about SPOF is aproppriate, or you need to contextualize the other case by being specific, for example referring to the quotas exhaustion on cloud service providers. Though even in the latter case, if you achieve DoS by exhausting the container quota, than the container creation architecture in place becomes a SPOF I would say.

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource commented on rules/S2631/impact.adoc
> +In both scenarios, the attacker intends to block the regular operation of the
```suggestion
In both scenarios, the attacker intends to block the regular operation of an
```

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource commented on rules/S2631/rationale.adoc
> +Regular expression pattern injections occur when the application retrieves
```suggestion
Regular expression injections occur when the application retrieves
```

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource commented on rules/S2631/rationale.adoc
> +performance problems called `catastrophic backtracking situations`.
```suggestion
performance problems also referred to as `catastrophic backtracking situations`.
```

Just an alternative.

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource commented on rules/S2631/impact.adoc
> +In the context of a web application vulnerable to regex pattern injection: +
```suggestion
In the context of a web application vulnerable to regex injection: +
```

2022-09-07 14:36 UTC, pedro-oliveira-sonarsource commented on rules/S2631/rationale.adoc
> +untrusted data and uses it as a regex pattern to scan a string with it.
```suggestion
untrusted data and uses it as a regex to pattern match a string with it.
```

2022-09-07 14:40 UTC, pedro-oliveira-sonarsource commented on rules/S2631/rationale.adoc
> +Regular expression pattern injections occur when the application retrieves
Should we call it Regex Denial of Service (ReDos) on the rationale over regular expression injection to be aligned with the rule title?

2022-09-07 14:48 UTC, loris-s-sonarsource commented on rules/S2631/common/fix/validation.adoc
> +As a rule of thumb, the best approach to protecting against injections is to
agreed 👍

2022-09-07 14:49 UTC, loris-s-sonarsource commented on rules/S2631/common/fix/validation.adoc
> +intended logic.
```suggestion
```

2022-09-07 14:49 UTC, loris-s-sonarsource commented on rules/S2631/common/fix/validation.adoc
> +As a rule of thumb, the best approach to protecting against injections is to
```suggestion
```

2022-09-07 14:50 UTC, loris-s-sonarsource commented on rules/S2631/common/fix/validation.adoc
> +vulnerability is to escape metacharacters and escapes sequences, preferably
yeah, I'd say "regex pattern" and "regex expression" are the same

2022-09-07 14:51 UTC, loris-s-sonarsource commented on rules/S2631/common/fix/validation.adoc
> +Create a list of authorized and secure strings that you want the application to
```suggestion
As an alternative, create a list of authorized and secure strings that you want the application to
```

2022-09-07 14:51 UTC, loris-s-sonarsource commented on rules/S2631/common/fix/validation.adoc
> +Another clean method is to validate the input before using it to scan a string.
Yup. I'm deleting it and adding the "alternative" expression to the next paragraph.

2022-09-07 14:54 UTC, loris-s-sonarsource commented on rules/S2631/common/fix/validation.adoc
> +Another clean method is to validate the input before using it to scan a string.
```suggestion
```

2022-09-07 14:55 UTC, loris-s-sonarsource commented on rules/S2631/common/fix/validation.adoc
> +attacks.
agreed 

```suggestion
```

2022-09-07 15:01 UTC, loris-s-sonarsource commented on rules/S2631/rationale.adoc
> +Regular expression pattern injections occur when the application retrieves
Honestly, I'm not sure, since ReDOS is more of an impact than a cause. I actually thought about this and I think it should be more technically correct to call this a regex [pattern|expression] injection than a DOS.

And now that I write this, I note that I also acknowledged that the only potential impact was a DOS... So Yeah good point, actually. I'm going to think about it in my second review round

2022-09-08 08:20 UTC, loris-s-sonarsource commented on rules/S2631/impact.adoc
> +failure, which is a software architecture weakness.
Arf, on my side I don't understand your suggestion. My point is to say SPOF = weakness, so exploit=simple

2022-09-08 08:28 UTC, loris-s-sonarsource commented on rules/S2631/common/fix/validation.adoc
> +
```suggestion
The easiest way to protect against regex injections is to escape metacharacters,
 preferably with native functions. +
The escape function instructs the regular expression engine to interpret these
characters literally and not as metacharacters.
```

2022-09-08 08:48 UTC, loris-s-sonarsource commented on rules/S2631/impact.adoc
> +offensive infrastructures.
```suggestion
```

2022-09-08 08:48 UTC, loris-s-sonarsource commented on rules/S2631/impact.adoc
> +failure, which is a software architecture weakness.
I suggest we remove this in favor of the previous paragraph

2022-09-08 08:51 UTC, loris-s-sonarsource commented on rules/S2631/impact.adoc
> +* When the attacker (or a group of attackers) performs a Distributed Denial of Service.
WDYT we change this second subsection to this, and remove what was there?:

```
==== Chaining this vulnerability with infrastructure SPOFs

However, a denial of service attack can be critical to the enterprise if it
targets a SPOF component. Sometimes the single point of failure is a software
architecture vulnerability (e.g., a single component on which multiple critical
components depend) or an operational vulnerability (e.g., insufficient
container creation capabilities).

In either case, attackers aim to exploit the infrastructure weakness by sending
as much malicious payload as possible, using potentially huge offensive
infrastructures.

These threats are particularly insidious if the attacked organization does not
maintain a disaster recovery plan (DRP).
```

2022-09-08 08:55 UTC, loris-s-sonarsource commented on rules/S2631/impact.adoc
> +failure of a container and automatically replace it.
Thanks ! To be clear about the intentions of these two subsections, I wanted to keep one "lightweight impact", and the other "critical bankrupt-inducing impact". That's why I don't mention critical stuff here, and that's why in the second subsection I mention two impacts that would not fit the same "attack category", but still would have a "critical impact".

I added what you suggest in "(e.g., insufficient container creation capabilities or failures from containers to terminate)." 
(next review comment)

2022-09-09 07:24 UTC, pedro-oliveira-sonarsource requested changes
Apply the suggestions you added to do a final read.

2022-09-09 07:24 UTC, pedro-oliveira-sonarsource commented on rules/S2631/impact.adoc
> +* When the attacker (or a group of attackers) performs a Distributed Denial of Service.
I think we are not allowed to use abbreviations like 'e.g.'? (Although I would prefer we could, both e.g. and i.e.)

2022-09-09 07:24 UTC, pedro-oliveira-sonarsource commented on rules/S2631/impact.adoc
> +* When the attacker (or a group of attackers) performs a Distributed Denial of Service.
Just minor adjustments. Looks good to me.

"==== Infrastructure SPOFs

However, a denial of service attack can be critical to the enterprise if it
targets an SPOF component. Sometimes the SPOF is a software
architecture vulnerability (e.g., a single component on which multiple critical
components depend) or an operational vulnerability (e.g., insufficient
container creation capabilities or failures from containers to terminate).

In either case, attackers aim to exploit the infrastructure weakness by sending
as much malicious payloads as possible, using potentially huge offensive
infrastructures.

These threats are particularly insidious if the attacked organization does not
maintain a disaster recovery plan (DRP)."

2022-09-09 08:17 UTC, loris-s-sonarsource commented on rules/S2631/impact.adoc
> +* When the attacker (or a group of attackers) performs a Distributed Denial of Service.
Ok, here is the final suggestion with Grammarly and without the e.g.s to respect the rspec rules:

```
==== Infrastructure SPOFs

However, a denial of service attack can be critical to the enterprise if it
targets a SPOF component. Sometimes the SPOF is a software
architecture vulnerability (such as a single component on which multiple critical
components depend) or an operational vulnerability (for example, insufficient
container creation capabilities or failures from containers to terminate).

In either case, attackers aim to exploit the infrastructure weakness by sending
as many malicious payloads as possible, using potentially huge offensive
infrastructures.

These threats are particularly insidious if the attacked organization does not
maintain a disaster recovery plan (DRP).
```

2022-09-09 08:30 UTC, pedro-oliveira-sonarsource approved these changes
LGTM.

2022-09-09 08:31 UTC, merged