[APPSEC-119] Modify rule S6287: Educational content (Java)
SonarSource/rspec pull request #1226
Opened 2022-09-06 13:44 UTC by pedro-oliveira-sonarsource

Specification ticket: [APPSEC-119](https://sonarsource.atlassian.net/browse/APPSEC-119).

2022-09-06 14:57 UTC, loris-s-sonarsource requested changes

2022-09-06 14:57 UTC, loris-s-sonarsource commented on rules/S6287/java/how-to-fix-it/java-se.adoc
> +    }
I found a code turn more concise:

```suggestion
    Optional<Cookie> cookieOpt = Arrays.stream(request.getCookies())
                                    .filter(c -> c.getName().equals("jsessionid"))
                                    .findFirst();

      if (!cookieOpt.isPresent()) {
          String cookie = request.getParameter("cookie");
          Cookie cookieObj = new Cookie("jsessionid", cookie);  // Noncompliant
          response.addCookie(cookieObj);
      }

      response.sendRedirect("/welcome.jsp");
```

wdyt?

2022-09-06 14:57 UTC, loris-s-sonarsource commented on rules/S6287/java/how-to-fix-it/java-se.adoc
> +    }
```suggestion
    Optional<Cookie> cookieOpt = Arrays.stream(request.getCookies())
                                    .filter(c -> c.getName().equals("jsessionid"))
                                    .findFirst();

      if (!cookieOpt.isPresent()) {
          response.sendRedirect("/getCookie.jsp");
      } else {
          response.sendRedirect("/welcome.jsp");
      }
```

2022-09-07 07:01 UTC, pedro-oliveira-sonarsource commented on rules/S6287/java/how-to-fix-it/java-se.adoc
> +    }
Looks cleaner.

2022-09-07 07:44 UTC, loris-s-sonarsource commented on rules/S6287/java/how-to-fix-it/java-se.adoc
> +      response.sendRedirect("/welcome.jsp");
```suggestion
    Optional<Cookie> cookieOpt = Arrays.stream(request.getCookies())
                                    .filter(c -> c.getName().equals("jsessionid"))
                                    .findFirst();

    if (!cookieOpt.isPresent()) {
        String cookie = request.getParameter("cookie");
        Cookie cookieObj = new Cookie("jsessionid", cookie);  // Noncompliant
        response.addCookie(cookieObj);
    }

    response.sendRedirect("/welcome.jsp");
```

2022-09-07 07:44 UTC, loris-s-sonarsource commented on rules/S6287/java/how-to-fix-it/java-se.adoc
> +}
```suggestion
protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
    Optional<Cookie> cookieOpt = Arrays.stream(request.getCookies())
                                    .filter(c -> c.getName().equals("jsessionid"))
                                    .findFirst();

    if (!cookieOpt.isPresent()) {
        response.sendRedirect("/getCookie.jsp");
    } else {
        response.sendRedirect("/welcome.jsp");
    }
}
```

2022-09-07 07:45 UTC, loris-s-sonarsource approved these changes
LGTM

2022-09-07 13:10 UTC, merged