Modify Multiple Rules(IAC): Remove Non-IAC-Based Standards in Metadata (APPSEC-5)
SonarSource/rspec pull request #1238
Opened 2022-09-12 10:30 UTC by loris-s-sonarsource

Related to [**APPSEC-5**]https://sonarsource.atlassian.net/browse/APPSEC-5).

2022-09-13 08:23 UTC, pedro-oliveira-sonarsource requested changes
Just have a look at this PCI DSS node overwrite.

2022-09-13 08:44 UTC, loris-s-sonarsource commented on rules/S4423/cloudformation/metadata.json
> +    ],
Oh, good point

2022-09-13 08:44 UTC, loris-s-sonarsource commented on rules/S4423/cloudformation/metadata.json
> +    ],
```suggestion
    "PCI DSS 3.2": [
      "4.1",
      "6.5.4"
    ],
    "PCI DSS 4.0": [
      "4.2.1",
      "6.2.4"
    ],
```

2022-09-13 08:45 UTC, loris-s-sonarsource commented on rules/S4423/terraform/metadata.json
> +    ],
```suggestion
    "PCI DSS 3.2": [
      "4.1",
      "6.5.4"
    ],
    "PCI DSS 4.0": [
      "4.2.1",
      "6.2.4"
    ],
```

2022-09-13 08:47 UTC, loris-s-sonarsource commented on rules/S5332/cloudformation/metadata.json
> +    ],
```suggestion
    "PCI DSS 3.2": [
      "4.1",
      "6.5.4"
    ],
    "PCI DSS 4.0": [
      "4.2.1",
      "6.2.4"
    ],
```

2022-09-14 08:18 UTC, pedro-oliveira-sonarsource approved these changes
LGTM.

2022-09-14 08:29 UTC, merged