Modify S2083&S6096(Education): Add Partial Path Traversal to pitfalls
SonarSource/rspec pull request #1243
Opened 2022-09-12 14:56 UTC by loris-s-sonarsource

Related to [**APPSEC-68**](https://sonarsource.atlassian.net/browse/APPSEC-68).

2022-09-13 09:50 UTC, pedro-oliveira-sonarsource requested changes
We should align both rules and add to S2083 the third suggested element included in the "How-does-this-work" for S6096.

2022-09-13 09:50 UTC, pedro-oliveira-sonarsource commented on rules/S6096/java/how-to-fix-it/java-se.adoc
> +validation. +
```suggestion
**Warning**: Some functions, such as `.getCanonicalPath`, remove the
terminating path separator in their return value. +
```

getCanonicalPath only can not be used to retrieve the base path value (argument for startsWith), but it can still be used in the validation like you have on the compliant solution. Think this is too strong I would remove it in both.

2022-09-13 09:50 UTC, pedro-oliveira-sonarsource commented on rules/S6096/java/how-to-fix-it/java-se.adoc
> +issue.
```suggestion
Validation code should be tested to ensure that it cannot be exploited.
```

2022-09-13 09:50 UTC, pedro-oliveira-sonarsource commented on rules/S2083/common/pitfalls/partial-path-traversal.adoc
> +validation strings.
```suggestion
When validating untrusted paths by comparing them to trusted path names,
**ensure the validator string contains a path separator as the last character**. + 
A partial path traversal vulnerability can be unintentionally introduced into the
application due to misuse of the validator method.

```

2022-09-13 09:50 UTC, pedro-oliveira-sonarsource commented on rules/S6096/csharp/how-to-fix-it/dotnet.adoc
> +issue.
Check the comment on the java-se.adoc

2022-09-13 09:50 UTC, pedro-oliveira-sonarsource commented on rules/S6096/java/how-to-fix-it/java-se.adoc
> +static private String targetDirectory = "/Users/John";
Should this be also changed to uppercase 'TargetDirectory' like you did on the other example?

I have no clue on naming nomenclature so I will leave it to you to decide.

2022-09-13 09:50 UTC, pedro-oliveira-sonarsource commented on rules/S6096/common/pitfalls/partial-path-traversal.adoc
> +
Please check the suggested changes for S2083.

2022-09-13 09:57 UTC, loris-s-sonarsource commented on rules/S6096/java/how-to-fix-it/java-se.adoc
> +static private String targetDirectory = "/Users/John";
No, I added the uppercase T because it is the C# naming convention IIRC

2022-09-13 12:04 UTC, loris-s-sonarsource commented on rules/S2083/common/pitfalls/partial-path-traversal.adoc
> +validation strings.
About your suggestion:
* I used the word "folders" because I realized that this partial path traversal attack was only relevant when the validation path was a folder. If it was something else, the validation would have been different
* I think that "a path separator as the last character of the validation strings." (initial text) is clearer than "due to misuse of the validator method." because it clearly states how the vulnerability can be introduced

2022-09-13 12:05 UTC, loris-s-sonarsource commented on rules/S6096/java/how-to-fix-it/java-se.adoc
> +validation. +
Agreed

2022-09-13 12:06 UTC, loris-s-sonarsource commented on rules/S6096/java/how-to-fix-it/java-se.adoc
> +issue.
If the issue is the word "thwarted" here, I would recommend the text below, because IMHO "exploited" can be misinterpreted, whereas talking about this issue in particular would make it clearer:

```suggestion
The validation code should be tested to ensure that it cannot be impacted by this
issue.
```

2022-09-13 12:08 UTC, loris-s-sonarsource commented on rules/S6096/csharp/how-to-fix-it/dotnet.adoc
> +issue.
```suggestion
**Warning**: Some functions remove the terminating path separator in their
return value and cannot be used for validation. +
The validation code should be tested to ensure that it cannot be impacted by this
issue.
```
Here is my suggestion from the java-se comment

2022-09-13 12:09 UTC, loris-s-sonarsource commented on rules/S6096/common/pitfalls/partial-path-traversal.adoc
> +
Here is my answer for S2083:

> About your suggestion:
>
>*    I used the word "folders" because I realized that this partial path traversal attack was only relevant when the validation path was a folder. If it was something else, the validation would have been different
>*    I think that "a path separator as the last character of the validation strings." (initial text) is clearer than "due to misuse of the validator method." because it clearly states how the vulnerability can be introduced

2022-09-14 13:56 UTC, loris-s-sonarsource commented on rules/S2083/csharp/how-to-fix-it/dotnet.adoc
> +}
```suggestion
public void Example(string folderName)
{
    string canonicalDestinationPath = Path.GetFullPath(folderName);

    if (canonicalDestinationPath.StartsWith(TargetDirectory, StringComparison.Ordinal))
    {
        System.IO.File.Delete(canonicalDestinationPath);
    }
}
```

2022-09-14 14:11 UTC, loris-s-sonarsource commented on rules/S2083/common/pitfalls/partial-path-traversal.adoc
> +character**. +
```suggestion
When validating untrusted paths by checking if they start with trusted path names,
**ensure the validation strings all contain a path separator as the last
character**. +
```

2022-09-14 14:13 UTC, loris-s-sonarsource commented on rules/S2083/common/pitfalls/partial-path-traversal.adoc
> +validation strings.
I added your suggestion here: https://github.com/SonarSource/rspec/pull/1243/files#r970864019

2022-09-14 14:14 UTC, loris-s-sonarsource commented on rules/S6096/common/pitfalls/partial-path-traversal.adoc
> +When checking untrusted folders by comparing them to trusted folder names,
```suggestion
When validating untrusted paths by checking if they start with a trusted folder name,
```

2022-09-14 14:14 UTC, loris-s-sonarsource commented on rules/S6096/common/pitfalls/partial-path-traversal.adoc
> +
done in https://github.com/SonarSource/rspec/pull/1243/files#r970867998

2022-09-14 14:22 UTC, pedro-oliveira-sonarsource approved these changes
LGTM, just a final small fix.

2022-09-14 14:22 UTC, pedro-oliveira-sonarsource commented on rules/S2083/java/how-to-fix-it/java-se.adoc
> +validation. +
```suggestion
terminating path separator in their return value. +
```

2022-09-14 14:22 UTC, pedro-oliveira-sonarsource commented on rules/S2083/csharp/how-to-fix-it/dotnet.adoc
> +return value and cannot be used for validation. +
```suggestion
**Warning**: Some functions remove the terminating path separator in their
return value. +
```

2022-09-14 14:59 UTC, loris-s-sonarsource commented on rules/S2083/csharp/how-to-fix-it/dotnet.adoc
> +issue.
```suggestion
The validation code should be tested to ensure that it cannot be impacted by this
issue.
```

2022-09-14 14:59 UTC, loris-s-sonarsource commented on rules/S2083/java/how-to-fix-it/java-se.adoc
> +Validation code should be tested to ensure that it cannot be thwarted by this
```suggestion
The validation code should be tested to ensure that it cannot be impacted by this
```

2022-09-14 17:49 UTC, merged