Modify S4423[Python]: Code examples for AWS CDK
SonarSource/rspec pull request #1273
Opened 2022-09-19 12:50 UTC by pierre-loup-tristant-sonarsource

Specification ticket: [APPSEC-103](https://sonarsource.atlassian.net/browse/APPSEC-103)
Implementation ticket: [SONARPY-1127](https://sonarsource.atlassian.net/browse/SONARPY-1127)
Preview: [S4423](https://sonarsource.github.io/rspec/#/rspec/S4423/python)

2022-09-19 14:39 UTC, egon-okerman-sonarsource requested changes

2022-09-19 14:39 UTC, egon-okerman-sonarsource commented on rules/S4423/python/message.adoc
> +Omitting "tls_security_polic" enables deprecated version of TLS. Set it to enforce TLS 1.2 or above.
```suggestion
Omitting "tls_security_policy" enables a deprecated version of TLS. Set it to enforce TLS 1.2 or above.
```

Small typo

2022-09-19 14:39 UTC, egon-okerman-sonarsource commented on rules/S4423/python/rule.adoc
> +            security_policy=apigateway.SecurityPolicy.TLS_1_0 # Noncompliant
```suggestion
            security_policy=SecurityPolicy.TLS_1_0 # Noncompliant
```

`SecurityPolicy` is imported directly, so no need to reference a module.

2022-09-19 14:39 UTC, egon-okerman-sonarsource commented on rules/S4423/python/rule.adoc
> +For  https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_apigateway/DomainName.html[aws_cdk.aws_apigateway.DomainName]:
```suggestion
For https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_apigateway/DomainName.html[aws_cdk.aws_apigateway.DomainName]:
```

Remove the extra space

2022-09-19 14:39 UTC, egon-okerman-sonarsource commented on rules/S4423/python/rule.adoc
> +            security_policy=apigateway.SecurityPolicy.TLS_1_2
```suggestion
            security_policy=SecurityPolicy.TLS_1_2
```

`SecurityPolicy` is imported directly, so no need to reference a module.

2022-09-19 14:39 UTC, egon-okerman-sonarsource commented on rules/S4423/python/rule.adoc
> +from aws_cdk.aws_opensearchservice import Domain, EngineVersion
```suggestion
from aws_cdk.aws_opensearchservice import CfnDomain, EngineVersion
```

Should be `CfnDomain`.

2022-09-19 14:39 UTC, egon-okerman-sonarsource commented on rules/S4423/python/rule.adoc
> +        Domain(self, "example",
```suggestion
        CfnDomain(self, "example",
```

Should be `CfnDomain`.

2022-09-19 14:39 UTC, egon-okerman-sonarsource commented on rules/S4423/python/rule.adoc
> +        Domain(self, "example",
```suggestion
        CfnDomain(self, "example",
```

Should be `CfnDomain`

2022-09-19 14:39 UTC, egon-okerman-sonarsource commented on rules/S4423/python/rule.adoc
> +from aws_cdk.aws_opensearchservice import Domain, EngineVersion
```suggestion
from aws_cdk.aws_opensearchservice import CfnDomain, EngineVersion
```

Should be `CfnDomain`

2022-09-19 14:39 UTC, egon-okerman-sonarsource commented on rules/S4423/python/rule.adoc
> +            tls_security_policy=opensearch.TLSSecurityPolicy.TLS_1_2
```suggestion
            domain_endpoint_options=CfnDomain.DomainEndpointOptionsProperty(
                tls_security_policy="Policy-Min-TLS-1-2-2019-07" # Compliant
            )
```

The parameter `tls_security_policy` does not exist here, and should instead be defined as shown above.

2022-09-20 11:19 UTC, egon-okerman-sonarsource requested changes
A few changes still have to be applied, but otherwise LGTM

2022-09-20 12:47 UTC, egon-okerman-sonarsource approved these changes

2022-09-20 13:44 UTC, merged

2022-09-20 14:31 UTC, pierre-loup-tristant-sonarsource commented
Merged by accident. Reverted change and opened https://github.com/SonarSource/rspec/pull/1278