Modify rule S2083Python): Update text to Education Framework structure (APPSEC-200)
SonarSource/rspec pull request #1329
Opened 2022-10-10 16:14 UTC by loris-s-sonarsource

2022-10-13 10:03 UTC, pierre-loup-tristant-sonarsource requested changes
Please update the "How does this work?" section so that its explains how `send_from_directory` prevent path traversal.

2022-10-13 10:03 UTC, pierre-loup-tristant-sonarsource commented on rules/S2083/python/how-to-fix-it/flask.adoc
> +include::../../common/fix/how-does-this-work.adoc[]
This renders the following content:

> The universal way to prevent path injection is to validate paths constructed from untrusted data.
> 
> The validation should be done as follow:
> 
> Resolve the canonical path of the file by using methods like `send_from_directory`. This will resolve relative path or path components like ../ and removes any ambiguity regarding the file’s location.
> 
> Check that the canonical path is within the directory where the file should be located.
> 
> Ensure the target directory path ends with a forward slash to prevent partial path traversal, for example, /base/dirmalicious starts with /base/dir but does not start with /base/dir/.

It's incorrect because:
- `send_from_directory` doesn't resolve the canonical path.
- it already checks that the sent file is within the specified directory

This part should simply explain that `send_from_directory` will restrict the file path to a specific folder and therefore it will prevent path traversal from happening.

2022-10-13 14:10 UTC, loris-s-sonarsource commented on docs/allowed_framework_names.adoc
> +* Python Standard Library
Good point, forgot it after removing the standard library code

2022-10-13 14:38 UTC, loris-s-sonarsource commented on rules/S2083/common/pitfalls/python-path-join.adoc
> +The standard library states:*"if a component is an absolute path, all previous
```suggestion
The standard library states: *"if a component is an absolute path, all previous
```

2022-10-13 14:51 UTC, loris-s-sonarsource commented on rules/S2083/common/fix/function-based-validation.adoc
> +Built-in APIs from libraries like {auto_canonicalization_function} benefit from
```suggestion
Built-in APIs from libraries like `{auto_canonicalization_function}` benefit from
```

2022-10-13 14:54 UTC, loris-s-sonarsource commented on rules/S2083/python/how-to-fix-it/flask.adoc
> +:auto_canonicalization_function: `send_from_directory`
```suggestion
:auto_canonicalization_function: send_from_directory
```

2022-10-13 15:22 UTC, pierre-loup-tristant-sonarsource approved these changes
LGTM. Please, have a look at the improvements I suggested before merging.

2022-10-13 15:22 UTC, pierre-loup-tristant-sonarsource commented on rules/S2083/common/fix/function-based-validation.adoc
> +==== Use functions that combine feature and validation
What about "Use secure-by-design API"

2022-10-13 15:22 UTC, pierre-loup-tristant-sonarsource commented on rules/S2083/common/fix/self-validation.adoc
> +==== Validate data yourself
What about "Validation of canonical path"

2022-10-13 15:22 UTC, pierre-loup-tristant-sonarsource commented on rules/S2083/common/fix/function-based-validation.adoc
> +injection.
Isn't it a bit too sujective?
> The cleanest way
> Benefit from quality maintenance

Here is what I would suggest
```suggestion
A common way to fix this vulnerability is to use a secure-by-design API that combines:

* the retrieval of a file
* restrict the retrieval of a file to a specific folder

Built-in APIs like `{auto_canonicalization_function}` were designed to prevent path traversal. It is usually
better to use these solutions than to develop your own.

Behind the scenes, these functions protects against both regular and partial path
injection.
```

2022-10-13 15:22 UTC, pierre-loup-tristant-sonarsource commented on rules/S2083/common/fix/self-validation.adoc
> -The universal way to prevent path injection is to validate paths constructed from untrusted data.
I think this sentence should stay with the "Validation of canonical path" content (see my other comment at the beginning of "How does this work?").

2022-10-13 15:22 UTC, pierre-loup-tristant-sonarsource commented on rules/S2083/python/how-to-fix-it/flask.adoc
> +from untrusted data.
To me, it's a bit strange to start by explaining that the universal way to fix the vuln is to validate the constructed path. No validation is required when using `send_from_directory`, devs just uses a safe-by-design API. Only at the end of the section, do users understand that the validation happens "Behind the scenes". I find it hard to reconnect with this introduction sentence.

2022-10-13 15:39 UTC, pierre-loup-tristant-sonarsource commented on rules/S2083/common/pitfalls/python-path-join.adoc
> +
This is one of the pitfalls Denis described in his blog post. https://blog.sonarsource.com/10-unknown-security-pitfalls-for-python/
It is probably worth mentioning it.

2022-10-18 13:59 UTC, loris-s-sonarsource commented on rules/S2083/common/fix/function-based-validation.adoc
> +==== Use functions that combine feature and validation
```suggestion
==== Use secure-by-design APIs
```

2022-10-18 14:27 UTC, loris-s-sonarsource commented on rules/S2083/python/how-to-fix-it/flask.adoc
> +from untrusted data.
```suggestion
:auto_canonicalization_function: send_from_directory

The universal method to prevent path injection is to validate paths created
from untrusted data. This can be done either manually or automatically,
depending on whether the library includes a data sanitization feature and the
required function.

Here, {auto_canonicalization_function} can be considered a secure-by-design API.
```

2022-10-18 14:31 UTC, loris-s-sonarsource commented on rules/S2083/common/fix/function-based-validation.adoc
> +injection.
Arf, I'm not really comfortable with this suggestion, but I think I'm onto something

2022-10-18 14:33 UTC, loris-s-sonarsource commented on rules/S2083/common/fix/function-based-validation.adoc
> +* restrict the retrieval of a file to a specific folder
```suggestion
* restrict the retrieval of a file to a specific folder
* A feature -- such as file download, or file deletion.
```

2022-10-18 14:34 UTC, loris-s-sonarsource commented on rules/S2083/common/fix/function-based-validation.adoc
> +The cleanest way to fix this vulnerability is to use a function that combines:
```suggestion
Some libraries contain APIs these three capabilities:
```

2022-10-18 14:46 UTC, loris-s-sonarsource commented on rules/S2083/common/fix/function-based-validation.adoc
> +better to use these solutions than to develop your own.
```suggestion
They can be referred to as "secure-by-design" APIs. Using this type of library,
such as '{auto_canonicalization_function}', brings multiple layers of security
to the code while keeping the code base shorter.
```

2022-10-18 14:54 UTC, loris-s-sonarsource commented on rules/S2083/common/pitfalls/python-path-join.adoc
> +
```suggestion
==== os.path.join(path, \*paths)

This function should not be used as a validator.

The standard library states: *"if a component is an absolute path, all previous
components are discarded, and linking continues from the component with the
absolute path."*

This means that including untrusted data in any of the path parameters can lead
to a full or partial path traversal vulnerability.

https://blog.sonarsource.com/10-unknown-security-pitfalls-for-python/[This Sonar blog post] talks about this issue.
```

2022-10-18 14:55 UTC, loris-s-sonarsource commented on rules/S2083/common/fix/self-validation.adoc
>  The validation should be done as follow:
```suggestion
==== Validate data yourself

==== Self-validation of canonical paths

If it is not possible to use secure-by-design APIs that do this automatically, validation should be done as follows:
```

2022-10-18 14:59 UTC, merged