Modify rule S2083(JS): Update text to Education Framework structure (APPSEC-201)
SonarSource/rspec pull request #1334
Opened 2022-10-12 14:38 UTC by loris-s-sonarsource

2022-10-13 14:55 UTC, loris-s-sonarsource commented on rules/S2083/common/fix/function-based-validation.adoc
> +
```suggestion
```

2022-10-17 12:57 UTC, gaetan-ferry-sonarsource requested changes
Left a few command. I think the code samples can be improved a little. Also one or two suggestions regarding pitfalls.

2022-10-17 12:57 UTC, gaetan-ferry-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +  const userFilename = fs.realPath(__dirname + req.query.filename);
I would also use path.join and avoid the `__dirname` here.

2022-10-17 12:57 UTC, gaetan-ferry-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +  const targetDirectory = __dirname + '/notsecret/';
And here

2022-10-17 12:57 UTC, gaetan-ferry-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +  if (!realPath.startsWith(targetDirectory)) {
I don't think `realPath` is defined here.

2022-10-17 12:57 UTC, gaetan-ferry-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +  const targetDirectory = __dirname + '/User/John';
Use `path.join` here. Also I would avoid `__dirname`

2022-10-18 15:08 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/express.adoc
> +const fs = require('fs');
```suggestion
const fs = require('fs');
const path = require('path');
```

2022-10-18 15:08 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/express.adoc
> +const fs = require('fs');
```suggestion
const fs = require('fs');
const path = require('path');
```

2022-10-18 15:08 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +const fs = require('fs');
```suggestion
const fs = require('fs');
const path = require('path');
```

2022-10-18 15:10 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +  if (!realPath.startsWith(targetDirectory)) {
```suggestion
  if (!userFilename.startsWith(resourcesDir)) {
```

2022-10-18 15:11 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +  const userFilename = fs.realPath(__dirname + req.query.filename);
```suggestion
  const resourcesDir = "/data/app/resources/"
  const userFilename = path.join(resourcesDir, req.query.filename));
  const userFilename = fs.realPath(userFilename);
```

2022-10-18 15:13 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +const fs = require('fs');
```suggestion
const fs = require('fs');
const path = require('path');
```

2022-10-18 15:14 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +  if (!realPath.startsWith(targetDirectory)) {
```suggestion
  const resourcesDir = "/data/app/resources/"
  const userFilename = path.join(resourcesDir, req.query.filename));
  const userFilename = fs.realPath(userFilename);

  if (!userFilename.startsWith(resourcesDir)) {
```

2022-10-18 15:17 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +  const targetDirectory = __dirname + '/User/John';
done in another comment

2022-10-18 15:32 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +include::../../common/fix/how-does-this-work.adoc[]
```suggestion
include::../../common/fix/self-validation.adoc[]
```

2022-10-18 15:47 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +3. `data = clean(data);`
```suggestion
3. `data = sanitize(data);`
```

2022-10-18 15:47 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +As pointed out in {tnsu_talk}[this SonarSource talk], failure to follow this exact order undoubtedly leads to security vulnerabilities.
```suggestion
As pointed out in {tnsu_talk}[this SonarSource talk], failure to follow this exact order leads to security vulnerabilities.
```

2022-10-18 15:50 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/express.adoc
> +==== Non-compliant code example
```suggestion
==== Noncompliant code example
```

2022-10-18 15:50 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +==== Non-compliant code example
```suggestion
==== Noncompliant code example
```

2022-10-18 15:54 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +As pointed out in {tnsu_talk}[this SonarSource talk], failure to follow this exact order leads to security vulnerabilities.
```suggestion
```

2022-10-18 15:57 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +
See https://github.com/SonarSource/rspec/pull/1328/files#diff-26e00bf0bb3adaf085510cde100874b7d349084c9070373acb2e848d08e6e0a8

2022-10-19 07:28 UTC, gaetan-ferry-sonarsource requested changes
LGTM in general. However, there are still a few inconsistencies in the code samples that need to be fixed.

2022-10-19 07:28 UTC, gaetan-ferry-sonarsource commented on rules/S2083/javascript/how-to-fix-it/express.adoc
> +  const userFilename = path.join(resourcesDir, req.query.filename);
`resourcesDir` is not defined here

2022-10-19 07:28 UTC, gaetan-ferry-sonarsource commented on rules/S2083/javascript/how-to-fix-it/express.adoc
> +  const targetDirectory = process.cwd();
Apparently, there is a mixup with the `targetDirectory` / `resourcesDir names` I would suggest:
```
const targetDirectory = "/data/app/resources/";
const userFilename = path.join(targetDirectory, req.query.filename);
res.sendFile(userFilename, { root: targetDirectory });
```

2022-10-19 07:28 UTC, gaetan-ferry-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +  const resourcesDir = "/data/app/resources/"
I don't think it is vulnerable if you add the forward slash here.
```suggestion
  const resourcesDir = "/data/app/resources"
```

2022-10-19 08:30 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/express.adoc
> +  const userFilename = path.join(resourcesDir, req.query.filename);
```suggestion
  const userFilename = path.join(targetDirectory, req.query.filename);
```

2022-10-19 08:31 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/express.adoc
> +  const userFilename = path.join(resourcesDir, req.query.filename);
```suggestion
  const targetDirectory = "/data/app/resources/"
  const userFilename = path.join(targetDirectory, req.query.filename);
```

2022-10-19 08:32 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/express.adoc
> +  const targetDirectory = process.cwd();
```suggestion
```

2022-10-19 08:33 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/express.adoc
> +  const userFilename = path.join(targetDirectory, req.query.filename);
```suggestion
  const userFilename = req.query.filename;
```

2022-10-19 08:35 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +  const userFilename = path.join(resourcesDir, req.query.filename);
```suggestion
  const targetDirectory = "/data/app/resources/"
  const userFilename = path.join(targetDirectory, req.query.filename);
```

2022-10-19 08:36 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +  if (!userFilename.startsWith(resourcesDir)) {
```suggestion
  const targetDirectory = "/data/app/resources/"
  const userFilename = path.join(targetDirectory, req.query.filename));
  const userFilename = fs.realPath(userFilename);

  if (!userFilename.startsWith(resourcesDir)) {
```

2022-10-19 08:36 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +  if (!userFilename.startsWith(resourcesDir)) {
```suggestion
  const targetDirectory = "/data/app/resources"
  const userFilename = path.join(targetDirectory, req.query.filename));
  const userFilename = fs.realPath(userFilename);

  if (!userFilename.startsWith(targetDirectory)) {
```

2022-10-19 08:41 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/express.adoc
> +const fs = require('fs');
```suggestion
```

2022-10-19 08:41 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +const fs = require('fs');
```suggestion
```

2022-10-19 08:41 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/node.adoc
> +const fs = require('fs');
```suggestion
```

2022-10-19 08:41 UTC, loris-s-sonarsource commented on rules/S2083/javascript/how-to-fix-it/express.adoc
> +const fs = require('fs');
```suggestion
```

2022-10-19 11:38 UTC, gaetan-ferry-sonarsource approved these changes
LGTM

2022-10-19 13:58 UTC, merged