Modify rule S2083(PHP): Update text to Education Framework structure (APPSEC-202)
SonarSource/rspec pull request #1335
Opened 2022-10-12 15:52 UTC by loris-s-sonarsource

2022-10-12 15:53 UTC, loris-s-sonarsource commented on rules/S2083/php/how-to-fix-it/core.adoc
> +$fileName = $_GET["fileName"];
```suggestion
$fileName = $_GET["filename"];
```

2022-10-12 15:53 UTC, loris-s-sonarsource commented on rules/S2083/php/how-to-fix-it/core.adoc
> +$fileName = realpath($_GET["fileName"]);
```suggestion
$fileName = realpath($_GET["filename"]);
```

2022-10-12 15:53 UTC, loris-s-sonarsource commented on rules/S2083/php/how-to-fix-it/core.adoc
> +if(safePath == "/home/foo/uploads") {
```suggestion
if (filename == "/home/example/uploads") {
```

2022-10-12 15:53 UTC, loris-s-sonarsource commented on rules/S2083/php/how-to-fix-it/core.adoc
> +    file_get_contents($safePath);
```suggestion
    file_get_contents($filename);
```

2022-10-12 15:54 UTC, loris-s-sonarsource commented on rules/S2083/php/how-to-fix-it/core.adoc
> +file_get_contents($safePath); // Noncompliant
```suggestion
file_get_contents($filename); // Noncompliant
```

2022-10-17 10:12 UTC, loris-s-sonarsource commented on rules/S2083/php/how-to-fix-it/core.adoc
> +}
```suggestion
$targetDirectory = "/path/to/target/directory/";

$path = realpath($targetDirectory . $fileName);

if (str_starts_with($path,  $targetDirectory)) {
    unlink($path);
}
```

2022-10-18 09:36 UTC, pedro-oliveira-sonarsource requested changes
Almost there, just have a look at the Complaint solution to make it aligned to the code-rationale.adoc content.

2022-10-18 09:36 UTC, pedro-oliveira-sonarsource commented on rules/S2083/php/how-to-fix-it/core.adoc
> +$fileName = realpath($_GET["filename"]);
```suggestion
$fileName = $_GET["filename"];
```

realpath here is not needed since you are calling it already on the path concatenation in line 22

2022-10-18 09:36 UTC, pedro-oliveira-sonarsource commented on rules/S2083/php/how-to-fix-it/core.adoc
> +==== Non-compliant code example
Non-compliant or Noncompliant?

2022-10-18 09:36 UTC, pedro-oliveira-sonarsource commented on rules/S2083/php/how-to-fix-it/core.adoc
> +file_get_contents($filename); // Noncompliant
This code sample is not aligned with the introduction in code-rationale.adoc.

2022-10-18 12:13 UTC, pedro-oliveira-sonarsource commented on rules/S2083/php/how-to-fix-it/core.adoc
> +file_get_contents($filename); // Noncompliant
```suggestion
file_get_contents($fileName); // Noncompliant
```

2022-10-18 15:51 UTC, loris-s-sonarsource commented on rules/S2083/php/how-to-fix-it/core.adoc
> +include::../../common/fix/code-rationale.adoc[]
```suggestion
The following code is vulnerable to path injection as it is constructing a path
using untrusted data. +
This path is then used without validation to return a file.

Therefore, it can be leveraged by an attacker to read arbitrary files.
```

2022-10-18 15:57 UTC, loris-s-sonarsource commented on rules/S2083/php/how-to-fix-it/core.adoc
> +include::../../common/fix/how-does-this-work.adoc[]
```suggestion
include::../../common/fix/self-validation.adoc[]
```

2022-10-19 11:00 UTC, pedro-oliveira-sonarsource approved these changes
LGTM.

2022-10-19 13:08 UTC, merged