Modify rule S2222:  Improve rule description
SonarSource/rspec pull request #1344
Opened 2022-10-14 12:21 UTC by martin-strecker-sonarsource

Changes based on the discussion in
https://discuss.sonarsource.com/t/10639

2022-10-14 12:32 UTC, martin-strecker-sonarsource commented on rules/S2222/csharp/description.adoc
> +If a lock is acquired and released within a method, then it must be released along all execution paths of that method.
Source is the "main" file for the rule:
https://github.com/SonarSource/rspec/blob/master/rules/S2222/description.adoc

2022-10-14 12:32 UTC, martin-strecker-sonarsource commented on rules/S2222/csharp/description.adoc
> +Failing to do so could make an application deadlock-prone because there is a risk of the lock not being released.
A mixture of Toms suggestions:
* “Failing to do so could make an application deadlock-prone”
* "If your unlock is conditional there is a risk that it won’t be released."

2022-10-14 12:32 UTC, martin-strecker-sonarsource commented on rules/S2222/csharp/metadata.json
> +  "title": "Locks should be released on all paths",
Title change was suggested by Ann (with Tom approving it).
This changes the title for CSharp only. If we do it like this, we need to change it for VB too. If we do it in the shared file, we would change the title for Java too.

2022-10-14 13:50 UTC, pavel-mikula-sonarsource requested changes

2022-10-18 06:42 UTC, martin-strecker-sonarsource commented on rules/S2222/csharp/description.adoc
> +If a lock is held or acquired and then released within a method, it must be released along all execution paths.
Which version of the sentence do you like best?

2022-10-18 06:43 UTC, martin-strecker-sonarsource commented on rules/S2222/csharp/description.adoc
> +A lock must be released along all execution paths if held or acquired and then released within the same method.
The tile uses `should be`. Should we use that phrase also?

2022-10-18 06:49 UTC, martin-strecker-sonarsource commented on rules/S2222/csharp/metadata.json
> +  "title": "Locks should be released on all paths",
I wasn't sure how to handle cross-bubble changes so I kept the change small. I put the change in the main file now.

2022-10-18 06:52 UTC, pavel-mikula-sonarsource commented on rules/S2222/csharp/metadata.json
> +  "title": "Locks should be released on all paths",
There's no strict guideline for those. Let's just do what makes sense, best to our knowledge. It can always be improved later.

2022-10-18 06:54 UTC, pavel-mikula-sonarsource commented on rules/S2222/csharp/description.adoc
> +If a lock is held or acquired and then released within a method, it must be released along all execution paths.
second one. Gives a context and then action needed. Sounds easier to understand to me.

2022-10-18 06:55 UTC, pavel-mikula-sonarsource commented on rules/S2222/csharp/description.adoc
> +A lock must be released along all execution paths if held or acquired and then released within the same method.
Sure, why not..

2022-10-18 07:09 UTC, pavel-mikula-sonarsource approved these changes
LGTM

2022-10-18 07:12 UTC, merged