Modify rule S5146(Python): Update text to Education Framework structure (APPSEC-191)
SonarSource/rspec pull request #1347
Opened 2022-10-17 11:36 UTC by pedro-oliveira-sonarsource

2022-10-17 11:36 UTC, pedro-oliveira-sonarsource commented
The validate_link issue will be solved in https://github.com/SonarSource/rspec/pull/1331 as the URL is being changed. It's missing a backslash on the https://example.commit.malicious.io URL in the starts-with.adoc.

2022-10-20 15:51 UTC, loris-s-sonarsource requested changes
Almost LGTM, one medium suggestion

2022-10-20 15:51 UTC, loris-s-sonarsource commented on rules/S5146/python/how-to-fix-it/django.adoc
> +----
```suggestion
----
from django.http import HttpResponseRedirect
```

2022-10-20 15:51 UTC, loris-s-sonarsource commented on rules/S5146/python/how-to-fix-it/django.adoc
> +----
I suggest we add some more content and make a view class, such as https://github.com/do-community/django-polls/blob/master/polls/views.py

2022-10-20 15:51 UTC, loris-s-sonarsource commented on rules/S5146/python/how-to-fix-it/django.adoc
> +----
```suggestion
----
from django.http import HttpResponseRedirect
```

2022-10-20 15:51 UTC, loris-s-sonarsource commented on rules/S5146/python/how-to-fix-it/django.adoc
> +allow_list = ['https://www.example.com', 'https://example.com']
```suggestion
allow_list = ['www.example.com', 'example.com']
```


`url.netloc` gives

```python
>>> urlparse("https://google.com/").netloc
'google.com'
>>> urlparse("https://www.google.com/").netloc
'www.google.com'
```

2022-10-20 15:51 UTC, loris-s-sonarsource commented on rules/S5146/python/how-to-fix-it/django.adoc
> +        return HttpResponseRedirect(url)
this could redirect to "http". WDYT if we do

```python
    parsed_url = urlparse(URL).netloc
    if parsed_url in allow_list:
        return HttpResponseRedirect("https://" + parsed_url)
```

2022-10-20 15:51 UTC, loris-s-sonarsource commented on rules/S5146/python/how-to-fix-it/flask.adoc
> +----
```suggestion
----
from flask import Flask, redirect, url_for

app = Flask("example")

```

2022-10-20 15:51 UTC, loris-s-sonarsource commented on rules/S5146/python/how-to-fix-it/flask.adoc
> +----
```suggestion
----
from flask import Flask, redirect

app = Flask("example")

```

2022-10-21 06:54 UTC, pedro-oliveira-sonarsource commented on rules/S5146/python/how-to-fix-it/django.adoc
> +----
So are the code samples to be more realistic or straight to the point? Because this keeps changing on each sprint.

2022-10-21 06:56 UTC, pedro-oliveira-sonarsource commented on rules/S5146/python/how-to-fix-it/flask.adoc
> +----
not sure if this is not adding clutter to the code sample

2022-10-21 07:20 UTC, pedro-oliveira-sonarsource commented on rules/S5146/python/how-to-fix-it/django.adoc
> +----
Isn't this just adding clutter to the code sample?

2022-10-21 08:59 UTC, loris-s-sonarsource commented on rules/S5146/python/how-to-fix-it/django.adoc
> +----
After internal discussion, let's keep this code as is and discuss this in a future team discussion

2022-10-21 09:01 UTC, loris-s-sonarsource approved these changes
LGTM

2022-10-21 13:17 UTC, merged