Modify rule S2076: Change text to education framework structure for Python [APPSEC-194]
SonarSource/rspec pull request #1350
Opened 2022-10-18 10:04 UTC by gaetan-ferry-sonarsource

2022-10-19 11:59 UTC, loris-s-sonarsource requested changes
Almost LGTM for what's there. I didn't challenge what framework you chose though

2022-10-20 15:24 UTC, loris-s-sonarsource approved these changes
LGTM, readability changes required, and it's gonna be all good after that. A big comment about "how does this work" section was added, but it's gonna be handled in the proxy PR.

2022-10-20 15:24 UTC, loris-s-sonarsource commented on rules/S2076/python/how-to-fix-it/paramiko.adoc
> +shell control characters, the expected `ping` command behavior will be changed.
Comma trimming
```suggestion
Especially in this example, if the *host* request parameter contains system
shell control characters, the expected `ping` command behavior will be changed.
```

2022-10-21 08:46 UTC, loris-s-sonarsource commented on rules/S2076/python/how-to-fix-it/paramiko.adoc
> +shell control characters, the expected `ping` command behavior will be changed.
Agreed. And I don't think it's a bad style, I think that removing commas can improve the paragraph's readability. 
(I assume that users need to read fast)

2022-10-21 08:55 UTC, gaetan-ferry-sonarsource commented on rules/S2076/python/how-to-fix-it/python.adoc
> +include::../../common/fix/sanitize-meta-characters.adoc[]
Some thoughts.
### 1. The Introduction
I would go further in the simplification process with:
> If pre-approved lists cannot be used in the code context, libraries or functions that provide sanitization, such as subprocess, should be used.
I would add function along with libraries, as in some cases, the same library can provide safe and less secure alternatives.
Also, I would remove "the cleanest approach". I would not recommend anything incomplete, wrong or otherwise dirty.

### 2. Argument injection paragraph
I do not really agree on this. Most sanitation libraries do not make any difference between sanitizing parameters against argument injections and other shell escaping. To go further, I even think it is counterproductive to provide lists of dangerous special characters as this could encourage developers to built homemade escaping solutions based on it. Yet, we are likely to miss some cases, which can even depend on the system shell that is used. Let alone windows vs Unix differences.
To go even further, if you observe the output of most sanitation libraries and function, most of them do not espace special characters but only focus on quotes positions and number:
```
payload:  a\'$(ls)
sanitized: 'a\'"'"'$(ls)'
```

Therefore, I feel like, if something must be changed in the text, we should go for more simplicity, without going into too many details regarding the internals of the escaping process. We don't really want developers to tinker with this.

### 3. Order

No strong opinion, except that I think in most cases, the ordering is mostly absolute. We should not have to change the order too often.

2022-10-21 08:58 UTC, loris-s-sonarsource commented on rules/S2076/python/how-to-fix-it/python.adoc
> +include::../../common/fix/sanitize-meta-characters.adoc[]
> 2. Argument injection paragraph

Do you mean we should actually remove this section, and remove the big list of dangerous characters ? (I'm in favor)

2022-10-21 09:05 UTC, gaetan-ferry-sonarsource commented on rules/S2076/python/how-to-fix-it/python.adoc
> +include::../../common/fix/sanitize-meta-characters.adoc[]
I think we should indeed remove the list of bad characters that I find error-prone and not really fitting the security best practices.
Then, I think we should open a discussion to generally simplify this whole paragraph.

2022-10-21 09:57 UTC, merged

2022-10-21 14:22 UTC, loris-s-sonarsource commented on rules/S2076/python/how-to-fix-it/python.adoc
> +include::../../common/fix/sanitize-meta-characters.adoc[]
Ok, let's just create a hardening ticket about that then. I'm on it.