BUILD-1970 migrate cirrus-ci and github workflows secrets to vault
SonarSource/rspec pull request #1352
Opened 2022-10-20 08:32 UTC by tomverin

2022-10-28 11:48 UTC, tomverin commented
https://github.com/SonarSource/rspec/blob/master/.github/workflows/update_coverage.yml#L60 needs a specific githug token to be able to push to the repo

2023-05-26 13:14 UTC, Godin requested changes

2023-05-26 13:14 UTC, Godin commented on .github/workflows/create_new_rspec.yml
> +      pull-requests: write
This change is unrelated to Vault.

2023-05-26 13:14 UTC, Godin commented on .github/workflows/main.yml
> +      contents: write
This change is unrelated to Vault.

2023-05-26 13:14 UTC, Godin commented on .github/workflows/update_quickfix_status.yml
> +      pull-requests: write
This change is unrelated to Vault.

2023-05-26 13:14 UTC, Godin commented on .cirrus.yml
> +    - npm install
This change is unrelated to Vault.

2023-05-26 13:14 UTC, Godin commented on .cirrus.yml
> +    - apt update -y && apt upgrade -y && apt update -y && apt install -y unzip
This change is unrelated to Vault.

2023-05-26 13:29 UTC, merged