Modify rule S5145(PHP): Update text to the Education Framework structure (APPSEC-227)
SonarSource/rspec pull request #1367
Opened 2022-11-01 10:50 UTC by pedro-oliveira-sonarsource

2022-11-01 15:20 UTC, pedro-oliveira-sonarsource commented
We currently only support Core PHP and CakePHP sinks, and the latter is barely supported so it was decided to be left out.

2022-11-04 09:04 UTC, gaetan-ferry-sonarsource requested changes

2022-11-04 09:04 UTC, gaetan-ferry-sonarsource commented on rules/S5145/php/how-to-fix-it/php.adoc
> +include::../../common/fix/how-does-this-work.adoc[]
LGTM in general but I am a bit afraid by the proposed compliant code.

2022-11-04 09:59 UTC, gaetan-ferry-sonarsource requested changes
A small fixed is required for the compliant solution description which does not currently match the chosen fix.

2022-11-04 09:59 UTC, gaetan-ferry-sonarsource commented on rules/S5145/php/how-to-fix-it/php.adoc
> +Here, the example compliant code uses the `preg_replace` function to remove any non safe character from the input.
This does not work with the chosen compliant solution.
```suggestion
Here, the example compliant code uses the `preg_match` function to check if the input contains any unsafe character. In which case, the `base64_encode` function is used to prevent any injection while keeping the input original content.
```

2022-11-04 15:10 UTC, gaetan-ferry-sonarsource approved these changes
LGTM

2022-11-07 07:50 UTC, merged