Modify rule S6096(JavaScript): Update text to the Education Framework structure (APPSEC-231)
SonarSource/rspec pull request #1372
Opened 2022-11-03 13:17 UTC by pedro-oliveira-sonarsource

2022-11-04 13:43 UTC, gaetan-ferry-sonarsource requested changes
I think there is a misunderstanding of the issue to raise here. The code examples focus on a classical path traversal issue while the rule is specifically about zip slip.

2022-11-04 13:43 UTC, gaetan-ferry-sonarsource commented on rules/S6096/javascript/how-to-fix-it/nodejs.adoc
> +    const zip = new AdmZip(path); // Noncompliant
I don't really get what you are trying to do here. This looks a lot like a traditional path traversal vulnerability. Shouldn't this be a read of an uploaded zip file?
```suggestion
    const zip = new AdminZip(req.files.foo.tempFilePath); // Noncompliant
```
Also, I don't get why this specific line is marked as non compliant (except if this is for a normal path traversal).

2022-11-04 13:43 UTC, gaetan-ferry-sonarsource commented on rules/S6096/javascript/how-to-fix-it/nodejs.adoc
> +        var writer = fs.createWriteStream(zipEntry.entryName);
To me, this should be the non compliant line in this case.
```suggestion
        var writer = fs.createWriteStream(zipEntry.entryName); // Noncompliant
```

2022-11-04 13:43 UTC, gaetan-ferry-sonarsource commented on rules/S6096/javascript/how-to-fix-it/nodejs.adoc
> +    if (canonicalPath.startsWith(targetDirectory)) {
I think this is fixing the old school path traversal issue and not the zip slip one.

2022-11-04 13:43 UTC, gaetan-ferry-sonarsource commented on rules/S6096/javascript/how-to-fix-it/nodejs.adoc
> +	    });
To me the zip slip issue is still there and exploitable here. Maybe refer to the existing rspec for an appropriate solution. The key is to check the entry name before extraction, not the archive name.

2022-11-04 13:43 UTC, gaetan-ferry-sonarsource commented on rules/S6096/javascript/how-to-fix-it/nodejs.adoc
> +    }
Same remarks as above. The issue is not in the right location.

2022-11-07 13:52 UTC, pedro-oliveira-sonarsource commented
Think it's required to add the following?
const fs = require('fs');
const path = require('path');

2022-11-07 16:27 UTC, gaetan-ferry-sonarsource approved these changes
LGTM

2022-11-08 07:47 UTC, merged