Modify rule S3871: Remove Java, add VB.NET
SonarSource/rspec pull request #1375
Opened 2022-11-04 12:45 UTC by pavel-mikula-sonarsource

2022-11-04 16:11 UTC, Corniel approved these changes
LGTM

2022-11-04 16:33 UTC, martin-strecker-sonarsource requested changes
There is an `+` leftover in one of the exceptions exceptions.

2022-11-04 16:33 UTC, martin-strecker-sonarsource commented on rules/S3871/csharp/rule.adoc
> +If a method throws a non-public exception, the best you can do on the caller's side is to `catch` the closest `public` base of the class. That is, you lose all that custom information you created the
```suggestion
If a method throws a non-public exception, the best you can do on the caller's side is to `catch` the closest `public` base of the class. However, you lose all that custom information the exception type passes.
```

2022-11-04 16:33 UTC, martin-strecker-sonarsource commented on rules/S3871/exceptions.adoc
> +This rule ignores Exception types that are not derived directly from `System.Exception+`, `System.SystemException`, or `System.ApplicationException`.
```suggestion
This rule ignores Exception types that are not derived directly from `System.Exception`, `System.SystemException`, or `System.ApplicationException`.
```

2022-11-04 16:33 UTC, martin-strecker-sonarsource commented on rules/S3871/vbnet/rule.adoc
> +If a method throws a non-public exception, the best you can do on the caller's side is to `Catch` the closest `Public` base of the class. That is, you lose all that custom information you created the
The changes in the C# version should be applied here too.

2022-11-07 07:12 UTC, pavel-mikula-sonarsource commented on rules/S3871/csharp/rule.adoc
> +If a method throws a non-public exception, the best you can do on the caller's side is to `catch` the closest `public` base of the class. That is, you lose all that custom information you created the
The whole sentence is a bit weird. I tried to rephrase it

2022-11-07 08:12 UTC, martin-strecker-sonarsource approved these changes
LGTM

2022-11-07 08:12 UTC, merged