Modify rule S2078: Change text to the education framework format [Python][APPSEC-269]
SonarSource/rspec pull request #1393
Opened 2022-11-14 15:01 UTC by pedro-oliveira-sonarsource

2022-11-15 07:42 UTC, pedro-oliveira-sonarsource commented
Please suggest an alternative for the allowed_framework file, do you think "Python LDAP" would be ok? my issue is that it's very generic and not library-specific as you have other ones.

2022-11-17 13:51 UTC, egon-okerman-sonarsource commented
> Please suggest an alternative for the allowed_framework file, do you think "Python LDAP" would be ok? my issue is that it's very generic and not library-specific as you have other ones.

IMO the framework is called "python-ldap" on PyPI so the most correct thing would be to leave it like that. Calling it "Python LDAP" is indeed too confusing, and even things like "PyLDAP" are just a different framework.
Looking at the frameworks we currently allow, it's e.g. not immediately clear to me which library "Python SQLite" is supposed to be (looking it up, it's sqlite3.) Maybe best to involve someone who's spent more time on the education topic to decide this.

2022-11-17 14:15 UTC, egon-okerman-sonarsource requested changes

2022-11-17 14:15 UTC, egon-okerman-sonarsource commented on rules/S2078/python/metadata.json
> +{
Can this CERT standard be moved to `S2078/metadata.json`? I don't see any other differences between this and the file above

2022-11-17 14:15 UTC, egon-okerman-sonarsource commented on rules/S2078/python/how-to-fix-it/python-ldap.adoc
> +In the compliant solution example, the `ldap.filter.escape_filter_chars`
Validation talks about escaping characters for DNs, which is different from filters. I would also put `ldap.filter.escape_dn_chars` in the example and the documentation here. I think it could be a nasty pitfall for developers otherwise.

2022-11-18 07:26 UTC, pedro-oliveira-sonarsource commented on rules/S2078/python/how-to-fix-it/python-ldap.adoc
> +In the compliant solution example, the `ldap.filter.escape_filter_chars`
Agree.

2022-11-18 07:31 UTC, pedro-oliveira-sonarsource commented on rules/S2078/python/metadata.json
> +{
This should be empty (copy paste issues), nice catch :).

2022-11-18 07:44 UTC, pedro-oliveira-sonarsource commented
What do you think about the library name? Should we go for `Python-ldap` over `python-ldap`?

2022-11-18 12:42 UTC, egon-okerman-sonarsource commented
> What do you think about the library name? Should we go for `Python-ldap` over `python-ldap`?

IMO python-ldap is better. If someone really disagrees with it, it can always be changed later.

2022-11-18 12:43 UTC, egon-okerman-sonarsource reviewed
Just some small fixes are necessary in the common validation text, otherwise LGTM!

2022-11-18 12:43 UTC, egon-okerman-sonarsource commented on rules/S2078/common/fix/validation.adoc
> +Input sanitization should be primordially done using native libraries.
I don't think "primordially" is the best word, could be "primarily" instead

2022-11-18 12:43 UTC, egon-okerman-sonarsource commented on rules/S2078/common/fix/validation.adoc
> +Alternatively, validation can be implemented using an allow-list approach by
Nitpick: "allow-list" should be ["allowlist"](https://en.wiktionary.org/wiki/allowlist). Unfortunately it is spelled as "allow-list" everywhere in the rspec repo.

2022-11-18 12:43 UTC, egon-okerman-sonarsource commented on rules/S2078/common/fix/validation.adoc
> +The most fundamental security mechanism is the restriction of LDAP
I think removing "as a last resort" changes the importance of this recommendation. I don't disagree with it necessarily, but would like to understand why it was removed.

2022-11-18 13:05 UTC, pedro-oliveira-sonarsource commented on rules/S2078/common/fix/validation.adoc
> +The most fundamental security mechanism is the restriction of LDAP
In my opinion here, when we say "the most fundamental security mechanism", this is not an alternative suggestion, it is stating the core fix of the problem. And 'as a last resort' to me sounds like we provided all the suggestions.

2022-11-18 14:40 UTC, egon-okerman-sonarsource commented on rules/S2078/common/fix/validation.adoc
> +The most fundamental security mechanism is the restriction of LDAP
That sounds good to me

2022-11-21 09:41 UTC, merged