[APPSEC-271] Modify rule S2091: Change text to the education framework format [Python]
SonarSource/rspec pull request #1396
Opened 2022-11-15 14:24 UTC by egon-okerman-sonarsource

2022-11-15 16:58 UTC, pierre-loup-tristant-sonarsource requested changes
As discussed, the `common/fix/validation.adoc` should be reworked to mention `parameterized queries` in a separate section that can also be reused for Java.

It's not in the scope of the ticket but we probably have to adjust what is included in the C# rule description, so that it doesn't mention OWASP ESAPI. 

Regarding parameterize query for C# either we don't mention it or we suggest using[XPathExpression](https://learn.microsoft.com/en-us/dotnet/standard/data/xml/user-defined-functions-and-variables?redirectedfrom=MSDN). I would rather go for not mentioning since the API documentation is a bit useless without a code example.

2022-11-15 16:58 UTC, pierre-loup-tristant-sonarsource commented on rules/S2091/python/how-to-fix-it/python.adoc
> +    return tree.xpath(expression, username=username, password=password) is not None
As we discussed maybe we should only mention switching to `lxml` in a later section. Therefore switch to a compliant code example that demonstrates the regex validation approach.

2022-11-15 16:58 UTC, pierre-loup-tristant-sonarsource commented on rules/S2091/python/how-to-fix-it/python.adoc
> +////
Not sure it's worth showing the payload.

2022-11-15 16:58 UTC, pierre-loup-tristant-sonarsource commented on rules/S2091/python/how-to-fix-it/python.adoc
> +the `ElementTree.xpath()` method defined by the https://pypi.org/project/lxml/[lxml library] to create a parameterized query, which prevents injection.
Same comment here.

2022-11-15 16:58 UTC, pierre-loup-tristant-sonarsource commented on rules/S2091/python/how-to-fix-it/lxml.adoc
> +In the example, the username and password are passed as https://lxml.de/xpathxslt.html#:~:text=The%20xpath()%20method%20has%20support%20for%20XPath%20variables%3A[XPath variables] rather than concate
Should be reworked to mention `parameterized queries` in a separate section.

2022-11-16 16:24 UTC, egon-okerman-sonarsource commented on rules/S2091/python/how-to-fix-it/python.adoc
> +////
I can take this out, but it's in a comment, so it's really just for future reference for us

2022-11-18 15:14 UTC, pierre-loup-tristant-sonarsource requested changes
Please rework the code examples, the syntax you used for the regular expression is not supported in Python 3.8 (at least). I also think noncompliant code examples should raise the expected issue and it's currently not the case.

The change on the common part looks good. Nice job, I think it's way clearer now.

2022-11-18 15:14 UTC, pierre-loup-tristant-sonarsource commented on rules/S2091/python/how-to-fix-it/python.adoc
>  def authenticate(tree: ElementTree, username: str, password: str) -> bool:
Currently no issue is raise on this code example because:
- `username` and `password` are only function parameters and therefore are not detected as sources
-  Apparently, `tree.find` is not resolved with the correct method id because type inference has limitations (see [SONARSEC-2590](https://sonarsource.atlassian.net/browse/SONARSEC-2590)). Therefore it's not resolved as a sink.

Here I suggest: 
- Updating the function to make it a Flask entry point like we do in other rule
- Create the `tree` variable using `tree = ElementTree.parse` so that the methodId of the sink is correctly resolved.

```suggestion
import re
from flask import request
from xml.etree import ElementTree

tree = ElementTree.parse('ressources/users.xml')

@app.route('/authenticate')
def authenticate():
    
    username = request.args['username']
    password = request.args['password']
```

You probably also need to adjust what the method returns.

2022-11-18 15:17 UTC, pierre-loup-tristant-sonarsource commented on rules/S2091/python/how-to-fix-it/python.adoc
> +////
Ok, works for me.

2022-11-18 15:22 UTC, egon-okerman-sonarsource commented on rules/S2091/python/how-to-fix-it/python.adoc
> +    if re.match(/^[a-zA-Z0-9]*$/, username) is None or re.match(/^[a-zA-Z0-9]*$/, username) is None:
You're right! I accidentally copied this over from a regex tester, my bad.

2022-11-18 15:28 UTC, pierre-loup-tristant-sonarsource commented on rules/S2091/python/how-to-fix-it/python.adoc
> +    if re.match(/^[a-zA-Z0-9]*$/, username) is None or re.match(/^[a-zA-Z0-9]*$/, username) is None:
I thought it was a fancy new syntax I didn't know.

2022-11-18 15:31 UTC, egon-okerman-sonarsource commented on rules/S2091/common/fix/validation.adoc
> +IMPORTANT: The application must do this validation server-side. Validating this client-side is insecure.
I spent some time looking it up yesterday, asciidoctorj does support admonitions. Still, I'll revert it and maybe it's something we can investigate for all rules instead.

2022-11-18 15:40 UTC, egon-okerman-sonarsource commented on rules/S2091/python/how-to-fix-it/python.adoc
>  def authenticate(tree: ElementTree, username: str, password: str) -> bool:
Alright, this relates to what we discussed on Wednesday about the simplicity of code samples. I'll change both this and the lxml example.

2022-11-21 09:30 UTC, pierre-loup-tristant-sonarsource requested changes

2022-11-21 10:03 UTC, egon-okerman-sonarsource commented
Oh my bad, it seems my changes weren't pushed before. Everything should be fixed.

2022-11-21 10:35 UTC, pierre-loup-tristant-sonarsource approved these changes
LGTM

2022-11-21 10:47 UTC, merged