Modify rule S2078: Change text to the education framework format [PHP][APPSEC-270]
SonarSource/rspec pull request #1400
Opened 2022-11-17 08:37 UTC by pedro-oliveira-sonarsource

2022-11-17 08:41 UTC, pedro-oliveira-sonarsource commented
The validation.adoc text is being modified on this [PR](https://github.com/SonarSource/rspec/pull/1393).

2022-11-17 08:42 UTC, pedro-oliveira-sonarsource commented
There is currently a type inference issue with the Ldap component for symfony, reflected with this [ticket](https://sonarsource.atlassian.net/browse/APPSEC-295).

2022-11-18 14:42 UTC, egon-okerman-sonarsource requested changes

2022-11-18 14:42 UTC, egon-okerman-sonarsource commented on rules/S2078/php/metadata.json
> +{
Same as the Python one, I'd remove this unless really necessary to add the CERT standard

2022-11-21 09:19 UTC, egon-okerman-sonarsource approved these changes
LGTM!

2022-11-21 09:41 UTC, merged