Modify rule S5144[Python]: Change text to the education framework format (APPSEC-285)
SonarSource/rspec pull request #1401
Opened 2022-11-17 08:39 UTC by pierre-loup-tristant-sonarsource

Ticket: [APPSEC-285](https://sonarsource.atlassian.net/browse/APPSEC-285)

2022-11-17 08:41 UTC, pierre-loup-tristant-sonarsource commented
I have the feeling the "How does this work?" could be improved. For example, it suggests restricting domains to a white list but what about webhook which should allow arbitrary URL as long as they are external?

2022-11-17 11:45 UTC, pedro-oliveira-sonarsource approved these changes
Regarding the code-rationale.adoc content 'The following code is vulnerable to SSRF as it performs an HTTP request to a URL defined by untrusted data' , when you use a payload such as `file:///etc/passwd`, does it still trigger an HTTP request?

2022-11-21 15:22 UTC, pierre-loup-tristant-sonarsource commented
@pedro-oliveira-sonarsource, should we mention the risk of local file being accessed using the `file://` scheme? `urllib.request` allows this scheme by default.

Also, I am asking again if you think "How does this work?" should be improved. For example, it suggests restricting domains to a white list but what about webhook which should allow arbitrary URL as long as they are external?

2022-11-22 10:38 UTC, pierre-loup-tristant-sonarsource commented
@pedro-oliveira-sonarsource following the discussion we had yesterday I update Python `urllib` and .Net code example so that the URL scheme is validated. I also update the common "How does this work?" to mention that both domains and schemes should be validated. I guess it's more consistent now. Let me know what you think.

2022-11-23 08:01 UTC, pedro-oliveira-sonarsource requested changes
Just some suggestions.

- Do not forget to also remove the space after `ExampleContoller` in the NonCompliant code.
> `public class ExampleController : Controller`

- The sink used in dotnet.adoc is [obsolete](https://learn.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated), we should replace it with HttpClient.

2022-11-23 13:07 UTC, pierre-loup-tristant-sonarsource commented
@pedro-oliveira-sonarsource following the discussion we add this morning as the standup I created [APPSEC-302](https://sonarsource.atlassian.net/browse/APPSEC-302) and suggest sticking with the current content that only mention validated the hostname and scheme.

Regarding the C# code example, I created [APPSEC-301](https://sonarsource.atlassian.net/browse/APPSEC-301)

2022-11-23 14:14 UTC, pedro-oliveira-sonarsource approved these changes
LGTM. Just 2 adjustments to do.

2022-11-23 14:14 UTC, pedro-oliveira-sonarsource commented on rules/S5144/csharp/how-to-fix-it/dotnet.adoc
> +        if (!allowedUrls.Contains(uri.Host) && !allowedSchemes.Contains(uri.Scheme))
```suggestion
        if (!allowedDomains.Contains(uri.Host) && !allowedSchemes.Contains(uri.Scheme))
```

2022-11-23 14:46 UTC, pierre-loup-tristant-sonarsource commented on rules/S5144/csharp/how-to-fix-it/dotnet.adoc
> +        if (!allowedUrls.Contains(uri.Host) && !allowedSchemes.Contains(uri.Scheme))
@pedro-oliveira-sonarsource I only see this one. what's the second?

2022-11-23 16:38 UTC, merged