[APPSEC-287] Modify rule S5144 (JS/TS): Change text to the education framework format
SonarSource/rspec pull request #1423
Opened 2022-11-24 15:28 UTC by pedro-oliveira-sonarsource

2022-11-25 14:14 UTC, egon-okerman-sonarsource requested changes
I made some suggestions on code style changes. Feel free to ignore, but do make sure the language of the code blocks are changed.

2022-11-25 14:14 UTC, egon-okerman-sonarsource commented on rules/S5144/javascript/how-to-fix-it/node.adoc
> +    if (schemesList.includes(url.protocol) && domainsList.includes(url.hostname)) {
```suggestion

const ALLOWED_SCHEMES = ["http:", "https:"];
const ALLOWED_DOMAINS = ["trusted1.example.com", "trusted2.example.com"];

async function example(request) {
    let url = new URL(request.query.url);

    if (ALLOWED_SCHEMES.includes(url.protocol) && ALLOWED_DOMAINS.includes(url.hostname)) {
```
Is it possible to make this change? It would look cleaner IMO, but not sure if this causes problems with detection.

2022-11-25 14:14 UTC, egon-okerman-sonarsource commented on rules/S5144/javascript/how-to-fix-it/node.adoc
> +async function example(request) {
Since it's JS/TS, it might be nice to define the type of the argument `request`, but I'll leave this up to you to decide.

2022-11-25 15:54 UTC, pedro-oliveira-sonarsource commented on rules/S5144/javascript/how-to-fix-it/node.adoc
> +async function example(request) {
Added the 'express' require.

2022-11-25 16:11 UTC, egon-okerman-sonarsource commented on rules/S5144/javascript/how-to-fix-it/node.adoc
> +async function example(request) {
I think that would be a great change, but do make sure to change the import statements if you do. As far as I remember (I might be wrong here), require doesn't play well with TypeScript and `import express from "express"` should be used instead.

2022-11-28 08:03 UTC, pedro-oliveira-sonarsource commented on rules/S5144/javascript/how-to-fix-it/node.adoc
> +async function example(request) {
I decided to keep it JS, but adjusted the axios request to a synchronous one.

2022-11-28 08:46 UTC, egon-okerman-sonarsource commented on rules/S5144/javascript/how-to-fix-it/node.adoc
> +    });
Wrapping this in an express example is great, but I'd use async/await here over `then()` for legibility

```suggestion
app.get('/example', async (req, res) => {
    try {
        const resp = await axios.get(req.query.url); // Noncompliant
        res.send("OK");
    } catch (err) {
        console.error(err);
        res.send("ERROR");
    }
});
```

2022-11-28 08:55 UTC, egon-okerman-sonarsource commented on rules/S5144/javascript/how-to-fix-it/node.adoc
> +async function example(request) {
Keeping it JS is fine, but I think asynchronous should really be preferred over synchronous for legibility, unless there is a good reason not to.

2022-11-28 09:40 UTC, pedro-oliveira-sonarsource commented on rules/S5144/javascript/how-to-fix-it/node.adoc
> +    });
Unaware I could specify this function as async, thank you!

2022-11-28 10:28 UTC, merged