Modify Rule S5725: Improved its text
SonarSource/rspec pull request #1447
Opened 2022-12-01 17:56 UTC by loris-s-sonarsource

2022-12-01 18:00 UTC, loris-s-sonarsource commented on rules/S5725/recommended.adoc
> +
```suggestion
To check the integrity of a remote artifact, hash verification is the most
reliable solution. It does ensure that the file has not been modified since the
fingerprint was computed.

In this case, the artifact's hash must:

* Be computed with a secure hash algorithm such as `SHA512`, `SHA384` or `SHA256`.
* Be compared with a secure hash that was *not* downloaded from the same source.

*Note: Use this fix together with version binding on the remote file. Avoid
downloading files named "latest" or similar, so that the front-end pages do not
break when the code of the latest remote artifact changes.*

To do so, the best option is to add the hash in the code explicitly. Follow these steps:

* download the remote artifact that is currently adding capabilities to your website
* follow https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#tools_for_generating_sri_hashes[Mozilla's tutorial on how to generate a hash string]
* prefix the value with the algorithm name, such as
** `sha512-`
** `sha384-`
** `sha256-`
* add it in the `integrity` attribute of the `<script>` tag

For example, the following bash command gives the correct integrity string for
an example script that could be stored in `https://cdn.example.com/3.5.6/framework.js`:

```

2022-12-02 13:23 UTC, loris-s-sonarsource commented on rules/S5725/recommended.adoc
> +an example script that could be stored in `https://cdn.example.com/3.5.6/framework.js`:
```suggestion
an example script that could be stored in `\https://cdn.example.com/3.5.6/framework.js`:
```

2022-12-02 13:23 UTC, loris-s-sonarsource commented on rules/S5725/recommended.adoc
> +$ wget https://cdn.example.com/3.5.6/framework.js` -q -O - \
```suggestion
$ wget https://cdn.example.com/3.5.6/framework.js -q -O - \
```

2022-12-05 09:40 UTC, gaetan-ferry-sonarsource requested changes
Looks good in general. Still some language and organization suggestions.

2022-12-05 09:40 UTC, gaetan-ferry-sonarsource commented on rules/S5725/html/rule.adoc
> +></script> <!-- Sensitive -->
This does not raise an issue. I would not include it in the noncompliant code examples.

2022-12-05 09:40 UTC, gaetan-ferry-sonarsource commented on rules/S5725/html/rule.adoc
> +></script> <!-- Sensitive -->
This does not raise an issue. I would not include it in the noncompliant code examples.

2022-12-05 09:40 UTC, gaetan-ferry-sonarsource commented on rules/S5725/javascript/rule.adoc
>  ----
This does not raise an issue. I would not include it here.

2022-12-05 09:40 UTC, gaetan-ferry-sonarsource commented on rules/S5725/message.adoc
> +Using artifacts without integrity checks exposes the end-user to various attacks. Make sure it is safe here.
I think "exposes the end-user to various attacks" a somehow a synonym for "is security sensitive". Except that, to me, "various attacks" might be a bit frightening compared to the difficulty to set up a successful supply chain attack.
```suggestion
Using artifacts without integrity checks is security sensitive. Make sure it is safe here.
```
```suggestion
Make sure using artifacts without integrity checks is safe here.
```

2022-12-05 09:40 UTC, gaetan-ferry-sonarsource commented on rules/S5725/recommended.adoc
> +
I would push that below to avoid breaking the flow with "to do so".

2022-12-05 09:40 UTC, gaetan-ferry-sonarsource commented on rules/S5725/recommended.adoc
> +To do so, the best option is to add the hash in the code explicitly. Follow these steps:
From "Follow these steps" I feel the content might become superfluous. All the steps described are detailed in Mozilla documentation. The hash generation script also is provided by Mozilla, in a shorter version.

Maybe it is sufficient to add a link to the appropriate documentation in the see section and end here.

2022-12-06 09:44 UTC, loris-s-sonarsource commented on rules/S5725/recommended.adoc
> +* add it in the `integrity` attribute of the `<script>` tag
```suggestion
To do so, the best option is to add the hash in the code explicitly, by following https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#tools_for_generating_sri_hashes[Mozilla's tutorial on how to generate a hash string].
```

2022-12-06 09:44 UTC, loris-s-sonarsource commented on rules/S5725/recommended.adoc
> +----
```suggestion
```

2022-12-06 09:44 UTC, loris-s-sonarsource commented on rules/S5725/recommended.adoc
> +break when the code of the latest remote artifact changes.*
```suggestion
```

2022-12-06 09:44 UTC, loris-s-sonarsource commented on rules/S5725/html/rule.adoc
> +----
```suggestion
The following code sample uses neither integrity checks nor version pinning:

[source,html]
----
<script
    src="https://cdn.example.com/latest/script.js"
></script> <!-- Sensitive -->
----
```

2022-12-06 09:49 UTC, loris-s-sonarsource reviewed
self-reread

2022-12-06 09:49 UTC, loris-s-sonarsource commented on rules/S5725/description.adoc
> +By ensuring that a remote artifact is exactly what it is supposed to be before
```suggestion

Likewise, a compromised software piece that would be deployed on a server-side application could badly affect the application's security. For example, server-side malware could:

* access and modify sensitive technical and business data.
* elevate its privileges on the underlying operating system.
* Use the compromised application as a pivot to attack the local network.

By ensuring that a remote artifact is exactly what it is supposed to be before
```

2022-12-06 09:49 UTC, loris-s-sonarsource commented on rules/S5725/html/rule.adoc
> +
```suggestion
```

2022-12-06 09:49 UTC, loris-s-sonarsource commented on rules/S5725/recommended.adoc
> +To do so, the best option is to add the hash in the code explicitly, by following https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#tools_for_generating_sri_hashes[Mozilla's
```suggestion
To do so, the best option is to add the hash in the code explicitly,
by following https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#tools_for_generating_sri_hashes[Mozilla's tutorial on how to generate a hash string].

```

2022-12-07 09:16 UTC, gaetan-ferry-sonarsource approved these changes
LGTM. With a slight suggestion that will not require a new review.

2022-12-07 09:16 UTC, gaetan-ferry-sonarsource commented on rules/S5725/recommended.adoc
> +by following https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#tools_for_generating_sri_hashes[Mozilla's tutorial on how to generate a hash string].
I feel the word "tutorial" might be a bit demeaning for the reader.
```suggestion
by following https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#tools_for_generating_sri_hashes[Mozilla's official documentation on how to generate integrity strings].
```

2022-12-09 16:39 UTC, merged