Modify rule S5270: Improve rule precision
SonarSource/rspec pull request #1459
Opened 2022-12-06 13:30 UTC by michael-jabbour-sonarsource

Related to CPP-3733 & SonarSource/sonar-cpp#2284.

2022-12-06 14:27 UTC, amelie-renard-sonarsource commented on rules/S5270/cfamily/rule.adoc
> +std::size_t elementsCount(...) { return 1u; }  // Compliant
The "Compliant" should be on the line where `elementsCount` is called, as in the above examples.

2022-12-06 15:29 UTC, michael-jabbour-sonarsource commented on rules/S5270/cfamily/rule.adoc
> +* https://github.com/isocpp/CppCoreGuidelines/blob/036324/CppCoreGuidelines.md#-es34-dont-define-a-c-style-variadic-function[{cpp} Core Guidelines ES.34] Don't define a (C-style) variadic function
From my perspective, the linked guidelines are only "relevant" to the rule, particularly where the rule suggests avoiding variadic functions for class types. My intention behind adding the links was to provide "further related reading material" around the topic.

I would find adding those tags to be a bit misleading here since the rule is less strict than the linked guidelines. I am also open to removing the whole "See" section if it is confusing...

2022-12-06 15:43 UTC, michael-jabbour-sonarsource commented on rules/S5270/cfamily/rule.adoc
> +#include <string_view>
Thanks for pointing that out. Includes removed from all examples.

2022-12-06 15:55 UTC, michael-jabbour-sonarsource commented on rules/S5270/cfamily/rule.adoc
> +The standard imposes some requirements on the types that can be passed as variadic arguments, and those requirements vary according to the C++ standard version in use. This rule detects any violation
I originally mentioned the rules and the difference among standard versions, but then I removed them because the paragraph looked a bit hard to follow for me. I also think that those requirements are not the main point of the rule, since the rule forbids all class types anyway.

I added a minor change to make it clearer that we are talking about "class types" here, see 3d1a0bfa43a456a0393f927fd3b15754ac299858. Do you think that it is better to add another paragraph (or maybe something like a footnote) to describe these requirements?

2022-12-08 13:49 UTC, amelie-renard-sonarsource commented on rules/S5270/cfamily/rule.adoc
> +The standard imposes some requirements on the types that can be passed as variadic arguments, and those requirements vary according to the C++ standard version in use. This rule detects any violation
Let's discuss it when you have time

2022-12-12 18:22 UTC, michael-jabbour-sonarsource commented on rules/S5270/cfamily/rule.adoc
> +* https://github.com/isocpp/CppCoreGuidelines/blob/036324/CppCoreGuidelines.md#-es34-dont-define-a-c-style-variadic-function[{cpp} Core Guidelines ES.34] Don't define a (C-style) variadic function
Done in 16ce9dd9c7a8de1c39a17fb78c116b5b0579d149.

2022-12-12 18:24 UTC, michael-jabbour-sonarsource commented on rules/S5270/cfamily/rule.adoc
> +The standard imposes some requirements on the types that can be passed as variadic arguments, and those requirements vary according to the C++ standard version in use. This rule detects any violation
As discussed, I added a small explanation about the standard requirements in bb4a7ef18ba914b33cfb4acfe5fbc7fe7f03ec0a.

2022-12-13 10:29 UTC, amelie-renard-sonarsource requested changes
Minor suggestion otherwise LGTM!
I find the description clearer with the good amount of info

2022-12-13 10:29 UTC, amelie-renard-sonarsource commented on rules/S5270/cfamily/rule.adoc
> +Most importantly, the rule detects any violations of these requirements since they can trigger undefined behavior.
```suggestion
The rule detects any violations of these requirements since they can trigger undefined behavior.
```

2022-12-13 11:00 UTC, amelie-renard-sonarsource approved these changes

2022-12-13 11:02 UTC, merged