CPP-3734 S3654 Improve on rule description
SonarSource/rspec pull request #1479
Opened 2022-12-19 10:50 UTC by pdschbrt

Adjust rule description: throwing an exception in a destructor is not necessarily undefined behavior. However, it is highly dangerous to throw in a destructor. This PR also adds an example on why that is.

2022-12-19 11:21 UTC, loic-joly-sonarsource commented
I don't think this is the full story. 

Since destructors are in many cases declared as `noexcept`, throwing from a destructor usually ends with calling `std::terminate`, even if only one exception is generated, so the scenario you describe can only happen if, in the first place, users violate this rule.

2022-12-19 11:47 UTC, abbas-sabra-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +A commonly used example that highlights the severity of the underlying problem is presented in what follows. The destructor of a standard container like ``++std::vector++`` automatically calls the de
We try to avoid long sentences and use list to make things easier to read:
```suggestion
A commonly used example that highlights the severity of the underlying problem is presented in what follows. The destructor of a standard container like ``++std::vector++`` automatically calls the destructors for all managed objects. Suppose a call to an object's destructor throws an exception. In that case, there are only two conceptional ways to proceed:
1. Abort destruction. This will result in a partially destroyed object and possibly many more objects whose destructor has not been called. 
2. Ignore the exception and proceed with destroying the remaining objects. However, if yet another exception is thrown while destroying the remaining objects, there would be two outstanding exceptions. This is disallowed by C++ exception-handling mechanism and results in a call to ``std::terminate``. 
Both of these options are undesired.
```
Also, you forgot the most common case; the destructor is noexcept. A lot of destructors are noexcept implicitly

2022-12-19 11:48 UTC, abbas-sabra-sonarsource reviewed
You have to open a PR for sonar-cpp to update the metadata there also. You can use this branch when it is approved to create the sonar-cpp PR: https://github.com/SonarSource/sonar-cpp/blob/master/docs/RuleMetadata.adoc

2022-12-19 12:22 UTC, pdschbrt commented
Thanks for your feedback. Will update the description to include the point in implicit `noexcept`.

2022-12-19 14:49 UTC, abbas-sabra-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +However, if a destructor that is declared as ``noexcept(false)`` happens to be called during stack unwinding, ``std::terminate`` is called instead.
```suggestion
Throwing an exception from a destructor may result in a call to ``std::terminate``, meaning that your program could be terminated abruptly without neatly destroying other objects.

Destructors are usually (implicitly) declared as ``noexcept`` by default such that ``std::terminate`` is called when they throw an exception.
Destructors may still throw an exception if they are explicitly declared as ``noexcept(false)``.
However, if a destructor that is declared as ``noexcept(false)`` happens to be called during stack unwinding, ``std::terminate`` is called instead.
```

2022-12-19 14:52 UTC, arseniy-sonar commented
Hi @pdschbrt 
Please follow the [PR description guideline](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule) (also pay attention to the generated commit message when you squash&merge it)

2022-12-19 14:56 UTC, abbas-sabra-sonarsource requested changes

2022-12-19 14:56 UTC, abbas-sabra-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +Throwing an exception from a destructor may result in a call to ``std::terminate``, meaning that your program could be terminated abruptly without neatly destroying others objects.
```suggestion
Throwing an exception from a destructor may result in a call to ``std::terminate``, meaning that your program could be terminated abruptly without neatly destroying other objects.
```

2022-12-19 14:58 UTC, abbas-sabra-sonarsource commented
@pdschbrt, rspec repo has different conventions for PR titles because it is shared between bubbles. have a look at modifying the rules convention:
https://github.com/SonarSource/rspec#to-modify-an-existing-rule
* You need to change the title and add a label.
* Also, can you add a link to the `sonar-cpp` rspec update PR so I can review/merge them together

2022-12-19 15:31 UTC, loic-joly-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +Destructors may still throw an exception if they are explicitly declared as ``noexcept(false)``.
```suggestion
Destructors may still propagate an exception if they are explicitly declared as ``noexcept(false)``.
```

2022-12-19 15:31 UTC, loic-joly-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +However, if a destructor that is declared as ``noexcept(false)`` happens to be called during stack unwinding, ``std::terminate`` is called instead.
```suggestion
However, even a destructor that is declared as ``noexcept(false)`` will call `std::terminate` if it throws during stack unwinding.
```

2022-12-19 15:31 UTC, loic-joly-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +A commonly used example that highlights the severity of the underlying problem is presented in what follows.
```suggestion
A commonly used example that highlights the severity of the underlying problem is presented in what follows:
```

2022-12-19 15:31 UTC, loic-joly-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +In that case, there are only two conceptional ways to proceed:
```suggestion
In that case, there are only two conceptual ways to proceed:
```
??

2022-12-19 15:31 UTC, loic-joly-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +Throwing an exception from a destructor may result in a call to ``std::terminate``, meaning that your program could be terminated abruptly without neatly destroying other objects.
In the current sentence wording, it does not seem clear that destroying other objects is a good thing...

```suggestion
Throwing an exception from a destructor may result in a call to ``std::terminate``, meaning that your program could be terminated abruptly without being allowed to perform a clean shutdown.
```

2022-12-19 15:35 UTC, pdschbrt commented on rules/S3654/cfamily/rule.adoc
> +Throwing an exception from a destructor may result in a call to ``std::terminate``, meaning that your program could be terminated abruptly without neatly destroying other objects.
Thanks for your inputs, @loic-joly-sonarsource.

2022-12-19 15:54 UTC, tomasz-kaminski-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +The destructor of a standard container like ``++std::vector++`` automatically calls the destructors for all managed objects.
If destructor of type used as elements on the vector throws in the desturctor, the behavior is undefined: https://eel.is/c++draft/requirements#res.on.functions-2.4

2022-12-19 16:05 UTC, tomasz-kaminski-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +The destructor of a standard container like ``++std::vector++`` automatically calls the destructors for all managed objects.
There are more ways:
* delete the source of the program, and other manifestation of UB
* termination
This suggests that `std::vector` has stronger guarantee, that it actually have

2022-12-19 16:07 UTC, tomasz-kaminski-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +2. Ignore the exception and proceed with destroying the remaining objects. However, if yet another exception is thrown while destroying the remaining objects, there would be two outstanding exception
Reading this. If you ignore an exception and continue with the destruction of remaining objects, you will not end up with two exceptions, as you ignored one. The phrasing seems to be unclear.

2022-12-19 16:10 UTC, pdschbrt commented on rules/S3654/cfamily/rule.adoc
> +The destructor of a standard container like ``++std::vector++`` automatically calls the destructors for all managed objects.
Indeed, I just wanted to give an example why this is a lost case and explain it on a conceptual level here.

This topic is huge; there are also exceptions (other than declaring a destructor as `noexcept(false)`) when destructors are _not_ implicitly `noexcept`. But I feel this would be too much for a reader of this rule.

2022-12-19 16:10 UTC, abbas-sabra-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +2. Ignore the exception and proceed with destroying the remaining objects. However, if yet another exception is thrown while destroying the remaining objects, there would be two outstanding exception
I agree this part needs clarification/can be misunderstood

2022-12-19 16:15 UTC, tomasz-kaminski-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +The destructor of a standard container like ``++std::vector++`` automatically calls the destructors for all managed objects.
Maybe:
```The destructor of a  container needs to call the destructors for all managed objects.```
And add clarification that for the standard container, the behavior is undefined.

2022-12-20 10:32 UTC, pdschbrt commented on rules/S3654/cfamily/rule.adoc
> +2. Ignore the exception and proceed with destroying the remaining objects. However, if yet another exception is thrown while destroying the remaining objects, there would be two outstanding exception
I've updated it.

2022-12-20 10:32 UTC, pdschbrt commented on rules/S3654/cfamily/rule.adoc
> +The destructor of a standard container like ``++std::vector++`` automatically calls the destructors for all managed objects.
Thanks, I've integrated your suggestions.

2022-12-20 11:17 UTC, tomasz-kaminski-sonarsource commented on rules/S3654/cfamily/rule.adoc
> +The destructor of a standard container like ``++std::vector++`` automatically calls the destructors for all managed objects.
Looks good.

2022-12-20 11:48 UTC, abbas-sabra-sonarsource approved these changes
LGTM

2022-12-20 11:49 UTC, merged