Modify rule S6398: Switch text to progressive education format
SonarSource/rspec pull request #1507
Opened 2023-01-23 15:50 UTC by gaetan-ferry-sonarsource

2023-01-24 16:18 UTC, gaetan-ferry-sonarsource commented on rules/S6398/java/how-to-fix-it/java-se.adoc
> +Conversion-related exceptions to avoid information leaks in case of error.
```suggestion
conversion-related exceptions to avoid information leaks in case of error.
```

2023-01-24 16:18 UTC, gaetan-ferry-sonarsource commented on rules/S6398/java/rule.adoc
> +include::how-to-fix-it/java-se.adoc[]
```suggestion
include::how-to-fix-it/java-se.adoc[]

include::how-to-fix-it/gson.adoc[]

include::how-to-fix-it/fasterxml.adoc[]
```

2023-01-26 10:44 UTC, egon-okerman-sonarsource requested changes
I have a few small notes, but overall great work.

2023-01-26 10:44 UTC, egon-okerman-sonarsource commented on rules/S6398/java/how-to-fix-it/java-se.adoc
> +    JSONObject obj = new JSONObject(json); // Noncompliant
Might be best to add a `import org.json.JSONObject;` statement to the top here, for me at least it wasn't obvious at first.

2023-01-26 10:44 UTC, egon-okerman-sonarsource commented on rules/S6398/java/how-to-fix-it/java-se.adoc
> +        JSONObject obj = new JSONObject(json);
Why not recommend

```java
JSONObject obj = new JSONObject();
obj.put("key", request.getParameter("value"));
```
instead? This is a more universal recommendation than casting to int and matches other frameworks.

2023-01-26 10:44 UTC, egon-okerman-sonarsource commented on rules/S6398/java/how-to-fix-it/gson.adoc
> +    obj.fromJson(json, Object.class); // Noncompliant
This can also throw a `JsonSyntaxException`, so I would add a try-catch here as well.

2023-01-26 10:44 UTC, egon-okerman-sonarsource commented on rules/S6398/java/how-to-fix-it/gson.adoc
> +The example compliant code uses the `JsonObject` class from the `Gson`` library
```suggestion
The example compliant code uses the `JsonObject` class from the Gson library
```
Code tags are unnecessary here, imo

2023-01-26 10:44 UTC, egon-okerman-sonarsource commented on rules/S6398/java/how-to-fix-it/fasterxml.adoc
> +The example compliant code uses the `ObjectNode` class from the `jackson``
```suggestion
The example compliant code uses the `ObjectNode` class from the Jackson
```
Code tags are unnecessary here, imo

2023-01-26 10:44 UTC, egon-okerman-sonarsource commented on rules/S6398/impact.adoc
> +authentication level and roles would be under threat of privilege escalations.
```suggestion
authentication levels and roles would be under threat of privilege escalations.
```
Small typo

2023-01-26 10:44 UTC, egon-okerman-sonarsource commented on rules/S6398/common/fix/introduction.adoc
> +strong pattern-based validation can help sanitize tainted inputs.
Type casting could be reworded to be more clear.

I think the casting is less important than the validation in this case, e.g. `Integer.parseInt(String s)` will throw a `NumberFormatException` if `s` does not contain a number.

2023-01-26 10:44 UTC, egon-okerman-sonarsource commented on rules/S6398/common/fix/casting.adoc
> +sanitation has to be applied to every user input without oversight.
```suggestion
Note that choosing this solution can be error-prone: every user input
has to be validated or sanitized without oversight.
```
A bit simpler to read

2023-01-26 13:16 UTC, gaetan-ferry-sonarsource commented on rules/S6398/java/how-to-fix-it/java-se.adoc
> +        JSONObject obj = new JSONObject(json);
Interesting, I overlooked it.

2023-01-26 13:20 UTC, gaetan-ferry-sonarsource commented on rules/S6398/java/how-to-fix-it/gson.adoc
> +    obj.fromJson(json, Object.class); // Noncompliant
I removed it to reduce the sample size and because it is a noncompliant code after all. But the code is not correct like it is. I'll just reintroduce it.

2023-01-26 13:39 UTC, egon-okerman-sonarsource approved these changes
LGTM :)

2023-01-26 14:53 UTC, merged