S5935: Fix for dead links
SonarSource/rspec pull request #1508
Opened 2023-01-23 15:53 UTC by zsolt-kolbay-sonarsource

Some of the rules contain dead links, which causes the PR checks to fail.

2023-01-23 17:14 UTC, martin-strecker-sonarsource requested changes

2023-01-23 17:14 UTC, martin-strecker-sonarsource commented on rspec-tools/rspec_tools/checklinks.py
> +              'https://www.ssi.gouv.fr/uploads/2014/11/RGS_v-2-0_B1.pdf']
Please don't do this. We need to fix the root cause which seems to be a missing root certificate on the build machine:
https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

2023-01-23 17:46 UTC, martin-strecker-sonarsource commented on rspec-tools/rspec_tools/checklinks.py
> +              'https://www.ssi.gouv.fr/uploads/2014/11/RGS_v-2-0_B1.pdf']
What is odd is that the certifi dependency has the right root CA installed:
* Root CA of ssi.gouv.fr: CN = Certigna, O = Dhimyotis, C = FR, serial number: 18364802974209362175
* certifi version 2022.5.18.1: https://github.com/SonarSource/rspec/blob/master/rspec-tools/Pipfile.lock#L143-L149
* Matching certificate in certifi: https://github.com/certifi/python-certifi/blob/2022.05.18.1/certifi/cacert.pem#L694-L722

2023-01-26 10:04 UTC, zsolt-kolbay-sonarsource commented on rspec-tools/rspec_tools/checklinks.py
> +              'https://www.ssi.gouv.fr/uploads/2014/11/RGS_v-2-0_B1.pdf']
I tried to upgrade it, but `2022.12.7` is indeed the latest version, so that doesn't resolve it.
Any other ideas? I'm currently stuck with this one. The only solution that worked so far was the inelegantly adding the link to the list of exceptions.

2023-01-26 10:49 UTC, martin-strecker-sonarsource commented on rspec-tools/rspec_tools/checklinks.py
> +              'https://www.ssi.gouv.fr/uploads/2014/11/RGS_v-2-0_B1.pdf']
I would just fix the one broken link and give the task of fixing the other one to the owners of the check_link script. Ask in our bubble who that is.

2023-01-31 13:53 UTC, zsolt-kolbay-sonarsource commented on rspec-tools/rspec_tools/checklinks.py
> +              'https://www.ssi.gouv.fr/uploads/2014/11/RGS_v-2-0_B1.pdf']
I reverted the change.

2023-01-31 18:42 UTC, martin-strecker-sonarsource approved these changes
LGTM

2023-01-31 18:47 UTC, martin-strecker-sonarsource commented
@zsolt-kolbay-sonarsource I asked the PHP bubble to also have a look. Please wait until one of them has approved too.

2023-02-01 08:03 UTC, nils-werner-sonarsource approved these changes
LGTM!

2023-02-01 09:20 UTC, merged