S3898: Add VB.NET
SonarSource/rspec pull request #1510
Opened 2023-01-24 09:33 UTC by pavel-mikula-sonarsource

2023-01-24 10:45 UTC, martin-strecker-sonarsource requested changes

2023-01-24 10:45 UTC, martin-strecker-sonarsource commented on rules/S3898/csharp/rule.adoc
> +    public bool Equals(MyStruct other)
Implementing `Equals<T>` without also implementing `object.Equals(object o)` and `object.GetHashCode()` is a violation of another rule.
From the docs:
> If you implement [IEquatable<T>](https://learn.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=net-7.0), you should also override the base class implementations of [Equals(Object)](https://learn.microsoft.com/en-us/dotnet/api/system.object.equals?view=net-7.0#system-object-equals(system-object)) and [GetHashCode()](https://learn.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=net-7.0#system-object-gethashcode) so that their behavior is consistent with that of the [Equals(T)](https://learn.microsoft.com/en-us/dotnet/api/system.iequatable-1.equals?view=net-7.0#system-iequatable-1-equals(-0)) method.

> For a value type, you should always implement [IEquatable<T>](https://learn.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=net-7.0) and override [Equals(Object)](https://learn.microsoft.com/en-us/dotnet/api/system.object.equals?view=net-7.0#system-object-equals(system-object)) for better performance.

[Source](https://learn.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=net-7.0)

I would add these methods to the compliant solution.

2023-01-24 10:45 UTC, martin-strecker-sonarsource commented on rules/S3898/vbnet/rule.adoc
> +    Public Overloads Function Equals(other As MyStruct) As Boolean Implements IEquatable(Of MyStruct).Equals
Same here. `Equals(object)` and `GetHashcode()` should be part of the compliant solution.

2023-01-24 10:45 UTC, martin-strecker-sonarsource commented on rules/S3898/description.adoc
> +If you're using a `struct`, it is likely because you're interested in performance. But by failing to implement `IEquatable<T>` you're loosing performance when comparisons are made because without `IE
In VB structs are called `Structure` and you implement `IEquatable(Of T)`

2023-01-24 10:45 UTC, martin-strecker-sonarsource commented on rules/S3898/description.adoc
> +If you're using a `struct`, it is likely because you're interested in performance. But by failing to implement `IEquatable<T>` you're loosing performance when comparisons are made because without `IE
Can we add a link to the "Notes for implementers" section to back up our claims?
https://learn.microsoft.com/dotnet/api/system.iequatable-1#notes-to-implementers

2023-01-24 10:45 UTC, martin-strecker-sonarsource commented on rules/S3898/description.adoc
> +If you're using a `struct`, it is likely because you're interested in performance. But by failing to implement `IEquatable<T>` you're loosing performance when comparisons are made because without `IE
Strictly speaking, IEquality is not about comparison but equality.

2023-01-24 12:15 UTC, pavel-mikula-sonarsource commented on rules/S3898/csharp/rule.adoc
> +    public bool Equals(MyStruct other)
That would be just a noise for this rule. The other rule should start complaining.

2023-01-24 12:21 UTC, pavel-mikula-sonarsource commented on rules/S3898/description.adoc
> +If you're using a `struct`, it is likely because you're interested in performance. But by failing to implement `IEquatable<T>` you're loosing performance when comparisons are made because without `IE
Equality that is typicaly checked as part of comparison? :) I'll leave that one as is

2023-01-24 14:45 UTC, martin-strecker-sonarsource commented on rules/S3898/csharp/rule.adoc
> +    public bool Equals(MyStruct other)
Okay, so we have https://sonarsource.github.io/rspec/#/rspec/S1206/csharp *"Equals(Object)" and "GetHashCode()" should be overridden in pairs* but it seems there seems to be no *override Equals(Object) and delegate to Equals(T) if Equals(T) is implemented* rule. Should we do a suggestion in the New rules backlog?

2023-01-24 14:48 UTC, pavel-mikula-sonarsource commented on rules/S3898/csharp/rule.adoc
> +    public bool Equals(MyStruct other)
Sounds reasonable

2023-01-24 14:53 UTC, martin-strecker-sonarsource approved these changes
LGTM. One suggestion regarding the link. And https://github.com/SonarSource/rspec/pull/1510#discussion_r1085425802 should be answered.

2023-01-24 14:53 UTC, martin-strecker-sonarsource commented on rules/S3898/see.adoc
> +* https://learn.microsoft.com/en-us/dotnet/api/system.iequatable-1
```suggestion
* https://learn.microsoft.com/dotnet/api/system.iequatable-1#notes-to-implementers[IEquatable<T> Interface (Microsoft Learn)]
```

2023-01-24 15:00 UTC, pavel-mikula-sonarsource commented on rules/S3898/see.adoc
> +* https://learn.microsoft.com/en-us/dotnet/api/system.iequatable-1
I intentionally provided link to the whole class, without the anchor. The displayed text can be improved

2023-01-24 15:05 UTC, martin-strecker-sonarsource commented on rules/S3898/csharp/rule.adoc
> +    public bool Equals(MyStruct other)
New rule description https://github.com/SonarSource/sonar-dotnet/issues/6671

2023-01-24 15:28 UTC, pavel-mikula-sonarsource commented on rules/S3898/csharp/rule.adoc
> +    public bool Equals(MyStruct other)
That should be nice new rule for the next onboarding batch :)

2023-01-24 21:58 UTC, Corniel commented on rules/S3898/csharp/rule.adoc
> +    public int Value { get; set; }
get only is a more common scenario.

2023-01-25 11:13 UTC, pavel-mikula-sonarsource commented on rules/S3898/csharp/rule.adoc
> +    public int Value { get; set; }
This is just to avoid an empty struct, it doesn't matter what exactly it is

2023-01-25 12:52 UTC, Corniel commented on rules/S3898/csharp/rule.adoc
> +    public int Value { get; set; }
I get your reasoning. I would argue that `public int Value { get; }` is just a small improvement. That's all.

2023-01-25 13:02 UTC, martin-strecker-sonarsource commented on rules/S3898/csharp/rule.adoc
> +    public int Value { get; set; }
Mutable structs make me shudder as well, but you would also have to add a constructor to an immutable struct to make it usable so `{ get; set; }` is a good compromise in this case.

2023-01-25 13:47 UTC, Corniel commented on rules/S3898/csharp/rule.adoc
> +    public int Value { get; set; }
@martin-strecker-sonarsource that is a valid argument. The documentation improved any way, getting rid of some noise.

2023-01-25 14:07 UTC, pavel-mikula-sonarsource commented on rules/S3898/csharp/rule.adoc
> +    public int Value { get; set; }
Like this one? :)
https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Point.cs,94

2023-01-26 09:24 UTC, merged