Modify rule S6399: Switch text to progressive education format (APPSEC-425)
SonarSource/rspec pull request #1522
Opened 2023-01-25 16:06 UTC by gaetan-ferry-sonarsource

2023-01-26 11:17 UTC, gaetan-ferry-sonarsource commented on rules/S6399/rationale.adoc
> +JSON injections occur when an application builds an XML-formatted string from
```suggestion
XML injections occur when an application builds an XML-formatted string from
```

2023-01-26 11:17 UTC, gaetan-ferry-sonarsource commented on rules/S6399/impact.adoc
> +The consequences of an XML injection attack into an application vary greatly
```suggestion
The consequences of an XML injection attack on an application vary greatly
```

2023-01-26 11:17 UTC, gaetan-ferry-sonarsource commented on rules/S6399/impact.adoc
> +Some applications communicate with backend micro-services API using XML-based
```suggestion
Some applications communicate with backend micro-services APIs using XML-based
```

2023-01-26 11:17 UTC, gaetan-ferry-sonarsource commented on rules/S6399/common/fix/object.adoc
> +In most cases, an application can directly create objects from user input
```suggestion
In most cases, an application can directly create documents from user input
```

2023-01-31 11:02 UTC, egon-okerman-sonarsource requested changes
A few changes are necessary, after that should be good to go 👍

2023-01-31 11:02 UTC, egon-okerman-sonarsource commented on rules/S6399/common/fix/introduction.adoc
> +constructing Java objects should be the preferred way.
```suggestion
However, directly constructing Java objects should be preferred
over handling the properties of objects as strings.
```
This is easier to read.

2023-01-31 12:38 UTC, gaetan-ferry-sonarsource commented on rules/S6399/java/rule.adoc
> +include::../common/resources/docs.adoc[]
Indeed, I left it as a placeholder for later use. Can be safely removed.

2023-01-31 13:11 UTC, egon-okerman-sonarsource approved these changes
LGTM!

2023-01-31 13:16 UTC, merged