S2198: Add C#
SonarSource/rspec pull request #1534
Opened 2023-02-01 09:11 UTC by gregory-paidis-sonarsource

https://github.com/SonarSource/sonar-dotnet/issues/6658

2023-02-14 17:46 UTC, martin-strecker-sonarsource requested changes

2023-02-14 17:46 UTC, martin-strecker-sonarsource commented on rules/S2198/csharp/rule.adoc
> +* comparing a ``++ulong++`` with a numeric constant that's outside the ``++ulong++`` range
```suggestion
These comparisons will always return ``++false++``:

* comparing a `char` with a numeric constant that's outside the `char` range
* comparing a `float` with a numeric constant that's outside the `float` range
* comparing a `long` with a numeric constant that's outside the `long` range
* comparing a `ulong` with a numeric constant that's outside the `ulong` range
```

2023-02-15 10:09 UTC, martin-strecker-sonarsource requested changes

2023-02-15 10:09 UTC, martin-strecker-sonarsource commented on rules/S2198/csharp/rule.adoc
> +These comparisons will always return ``++false++``:
```suggestion
These comparisons will always return `false`:
```

2023-02-15 10:09 UTC, martin-strecker-sonarsource commented on rules/S2198/csharp/rule.adoc
> +* comparing a `char` with a numeric constant that's outside the `char` range
The convention is to start with an upper letter and to end with a dot:
```suggestion
* Comparing a `char` with a numeric constant that's outside the `char` range.
```

2023-02-15 10:09 UTC, martin-strecker-sonarsource commented on rules/S2198/csharp/rule.adoc
> +if (f <= d) { } // Noncompliant
Simpler:
```suggestion
float f = 42.0f;
if (f <= double.MaxValue) { } // Noncompliant
```

2023-02-15 10:13 UTC, martin-strecker-sonarsource commented on rules/S2198/csharp/rule.adoc
> +* comparing a `char` with a numeric constant that's outside the `char` range
Maybe better like so?
```suggestion
* Comparing a `char` with a numeric constant that is outside of the range of `char`.
```

2023-02-15 11:01 UTC, martin-strecker-sonarsource requested changes
"always false" is not correct.

2023-02-15 11:01 UTC, martin-strecker-sonarsource commented on rules/S2198/csharp/rule.adoc
> +These comparisons will always return `false`:
```suggestion
These comparisons will always return the same value (either always `true` or always `false` depending on the kind of comparison):
```

2023-02-15 12:41 UTC, martin-strecker-sonarsource approved these changes
LGTM. Please merge once 🟢 .

2023-02-15 14:00 UTC, merged

2023-02-15 14:02 UTC, arseniy-sonar commented
Hi @gregory-paidis-sonarsource 
Please, follow [the guideline](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule) for the commit and the PR summary next time.