Modify rule S6384: Change text to the progressive education format (APPSEC-424)
SonarSource/rspec pull request #1535
Opened 2023-02-01 15:01 UTC by gaetan-ferry-sonarsource

2023-02-02 17:07 UTC, egon-okerman-sonarsource requested changes
I think the text could use some changes before it is merged.

2023-02-02 17:07 UTC, egon-okerman-sonarsource commented on rules/S6384/common/fix/destination.adoc
> +Before forwarding the intent, the application can check its destination.
```suggestion
Before forwarding the intent, the application should check its destination.
```
We can be stricter here, I think

2023-02-02 17:07 UTC, egon-okerman-sonarsource commented on rules/S6384/common/fix/destination.adoc
> +feature.
```suggestion
Most unintended usage of the forwarding feature can be prevented by
verifying whether the destination package and class names belong to a list
of accepted components.
```

Perhaps we can also explicitly mention `Intent.resolveActivity(PackageManager pm)`.

2023-02-03 10:39 UTC, gaetan-ferry-sonarsource commented on rules/S6384/java/how-to-fix-it/android.adoc
> +=== How does this work?
Yep. Those are not supported in the current config. I preferred not including them there and wait for the sonar-sec configuration to be improved.

2023-02-03 12:51 UTC, egon-okerman-sonarsource commented on rules/S6384/java/how-to-fix-it/android.adoc
> +=== How does this work?
Fair enough

2023-02-03 15:05 UTC, gaetan-ferry-sonarsource commented on rules/S6384/impact.adoc
> +An attacker can access any non-publicly exposed component of the application.
Hm I must say prefer my sentence here. There is quite a few repetitions in your version.
Can we agree on:
"An attacker can access any component of the vulnerable application, even if they are not exported" ?

2023-02-03 15:05 UTC, gaetan-ferry-sonarsource commented on rules/S6384/impact.adoc
> +=== What is the potential impact?
Nice catch, I'll add this!

2023-02-03 15:12 UTC, egon-okerman-sonarsource commented on rules/S6384/impact.adoc
> +An attacker can access any non-publicly exposed component of the application.
I agree my example isn't perfect here, it was more to point out that the "how?" is not immediately clear at the moment: how can an attacker access these private components?

For example in persistent code execution, the text follows more of a structure: some components rely on dynamic code -> intent redirection can deploy malicious code -> therefore persistent code execution is reached.

2023-02-03 15:18 UTC, gaetan-ferry-sonarsource commented on rules/S6384/common/fix/destination.adoc
> +feature.
Ok for the rewording. The resolveActivity call is already mentioned in the android.adoc file.

2023-02-03 15:23 UTC, gaetan-ferry-sonarsource commented on rules/S6384/impact.adoc
> +An attacker can access any non-publicly exposed component of the application.
I get what you mean, even if I think the two situations are different. Here, I really thought this first sentence would be a fact and introduce the actual consequence on the next paragraph. I get it's not that obvious tho.

Would this one be better for you?
"An attacker can use the affected feature as a gateway to access other components of the vulnerable application, even if they are not exported"

2023-02-03 15:24 UTC, egon-okerman-sonarsource commented on rules/S6384/impact.adoc
> +An attacker can access any non-publicly exposed component of the application.
I think that is much better!

2023-02-03 15:35 UTC, gaetan-ferry-sonarsource commented on rules/S6384/impact.adoc
> +an external application.
> An affected component that forwards a malicious externally provided intent does so using the vulnerable application's context. In particular, the new component is created with the same permissions as the application and without limitations on what feature can be reached.

2023-02-03 15:40 UTC, egon-okerman-sonarsource commented on rules/S6384/impact.adoc
> +an external application.
LGTM 👍

2023-02-03 15:51 UTC, egon-okerman-sonarsource approved these changes
There remains one typo and one repetition that should be fixed. I'll leave this up to you to finish.
Great work, the text is very extensive!

2023-02-03 15:51 UTC, egon-okerman-sonarsource commented on rules/S6384/impact.adoc
> +IF the vulnerable application has privileges on the underlying devices, an
```suggestion
If the vulnerable application has privileges on the underlying devices, an
```
Small typo

2023-02-03 15:51 UTC, egon-okerman-sonarsource commented on rules/S6384/impact.adoc
> +features that handle sensitive information, even if they are not exported.
```suggestion
features that handle sensitive information.
```
Avoids repetition on the previous line

2023-02-03 15:54 UTC, merged