Modify S1656: Update quickfix status (SONARJAVA-3959)
SonarSource/rspec pull request #1551
Opened 2023-02-06 16:32 UTC by irina-batinic-sonarsource

2023-02-06 17:00 UTC, chrislain-razafimahefa-sonarsource requested changes
I am not sure why the quickfix is 'partial'.

2023-02-06 17:00 UTC, chrislain-razafimahefa-sonarsource commented on rules/S1656/java/metadata.json
> +  "quickfix": "partial"
Why is it 'partial'? By looking quickly at the code, you have covered all the possible issues, no?

2023-02-07 08:42 UTC, irina-batinic-sonarsource commented on rules/S1656/java/metadata.json
> +  "quickfix": "partial"
The case where we have: `int b = a = a = a;` is not covered, the quick fix is not offered. It is out of the scope of this ticket because the expression needs to be simplified first.

2023-02-07 10:45 UTC, chrislain-razafimahefa-sonarsource approved these changes
Well done!

2023-02-07 10:46 UTC, merged