Modify Rule S2612: Add Docker (APPSEC-440)
SonarSource/rspec pull request #1560
Opened 2023-02-07 14:30 UTC by pedro-oliveira-sonarsource

Specification Ticket: [APPSEC-440](https://sonarsource.atlassian.net/browse/APPSEC-440)
Implementation Ticket: [SONARIAC-570](https://sonarsource.atlassian.net/browse/SONARIAC-570)

2023-02-08 17:28 UTC, loris-s-sonarsource requested changes
Small change request

2023-02-08 17:28 UTC, loris-s-sonarsource commented on rules/S2612/docker/metadata.json
> +    ]
I think we can remove that, no ?

2023-02-08 17:28 UTC, loris-s-sonarsource commented on rules/S2612/docker/ask-yourself.adoc
> +== Ask Yourself Whether
You should actually write that in the original ask-yourself rather than here, I think this can benefit all the implementations

2023-02-08 17:28 UTC, loris-s-sonarsource commented on rules/S2612/docker/impact.adoc
> +resulting Docker containers. +
I think you should adapt and add this to the main description.adoc file instead, and remove the trailing "+".

Like 

> Granting permissions to this category can lead to unintended access to files that could allow attackers to disrupt services or elevate privileges in the resulting Docker containers.

2023-02-08 17:28 UTC, loris-s-sonarsource commented on rules/S2612/docker/impact.adoc
> +set the target user and group.
This should be added right after the recommended practices inclusion

2023-02-08 17:28 UTC, loris-s-sonarsource commented on rules/S2612/docker/rule.adoc
> +'''
This is missing highlighting specs

2023-02-08 17:28 UTC, loris-s-sonarsource commented on rules/S2612/docker/ask-yourself.adoc
> +There is a risk if you answered yes to the question.
Here is a suggestion to avoid talking about sensitivity (
https://docs.sonarqube.org/latest/extension-guide/adding-coding-rules/#coding-rule-guidelines
)

```suggestion
* The container is designed to be a multi-user environment. 
* Removing permissions to `others` brings instability.

There is a risk if you answered no to these questions.
```

2023-02-08 17:28 UTC, loris-s-sonarsource commented on rules/S2612/docker/rule.adoc
> +include::./impact.adoc[]
when you include two files, it needs a new line in between two includes iirc

2023-02-08 17:34 UTC, loris-s-sonarsource commented on rules/S2612/docker/rule.adoc
> +'''
```
== Message

* Write permission
** Make sure that allowing write permission to other users is safe here.
* Write and execute permissions
** Make sure that allowing write and execute permissions to other users is safe here.

== Highlighting

Highlight the entire chmod expression i.e. `--chmod=0777`.

'''
```

2023-02-09 14:56 UTC, pedro-oliveira-sonarsource commented on rules/S2612/docker/metadata.json
> +    ]
I will remove these, but I am unsure whether the values from the main metadata will stay.

2023-02-09 15:17 UTC, pedro-oliveira-sonarsource commented on rules/S2612/docker/rule.adoc
> +'''
I will keep the old message, since its more generic because there is still the case for setuid and setgid, the Implementation tickets are now pointing to here and I will also explicitly add the Message and Highlighting definitions.

2023-02-09 15:29 UTC, pedro-oliveira-sonarsource commented on rules/S2612/docker/impact.adoc
> +resulting Docker containers. +
Contains Docker specific wording.

2023-02-09 15:33 UTC, pedro-oliveira-sonarsource commented on rules/S2612/docker/ask-yourself.adoc
> +There is a risk if you answered yes to the question.
To be honest, talking about resource sensitivity here should be the main concern in my opinion.

2023-02-09 15:57 UTC, pedro-oliveira-sonarsource commented on rules/S2612/docker/ask-yourself.adoc
> +== Ask Yourself Whether
Adjusted the Docker one, as discussed, I thinks its best to do another PR to tackle the main ask-yourself.

2023-02-09 17:02 UTC, loris-s-sonarsource approved these changes
LGTM!

2023-02-10 08:35 UTC, merged