Modify rule S6191 CPP-3876 Update the RSPEC with de-deprecation of these uses in C++23
SonarSource/rspec pull request #1564
Opened 2023-02-08 22:36 UTC by loic-joly-sonarsource

2023-02-09 11:41 UTC, phil-nash-sonarsource commented on rules/S6191/cfamily/rule.adoc
> +When a variable appears in a compound expression (for instance ``a{plus}{plus}`` or `a+=2`), the variable is accessed twice. This detail only matters for `volatile` variables, where any access is imp
a. Is it worth expanding on "where any access is important"?
b. "The standard was not explicit on this topic up until C++23" - surely it was explicit in C++20, just in a different direction. Would it be clearer to acknowledge the C++20 perspective to clarify that this has been refined in 23?

2023-02-09 11:43 UTC, phil-nash-sonarsource reviewed
Overall this reads well. The couple of comments I added, inline, are open to question and not, necessarily, showstoppers.

2023-02-15 18:16 UTC, loic-joly-sonarsource commented
@phil-nash-sonarsource: I tried a more verbose approach, that explains volatile in more detail. Let me know if you think it's any better.

2023-02-20 16:39 UTC, philsquared commented on rules/S6191/cfamily/rule.adoc
> +When a variable appears in a compound expression (for instance ``a{plus}{plus}`` or `a+=2`), the variable is accessed twice. This detail only matters for `volatile` variables. And it may not be obvio
I think this paragraph should still be first. That way if you know the whole context you'll get what you need straight away. If it is not convincing on its own (because you're not so familiar with how volatile variables work) then reading on (ie the preceding two paragraphs here) nicely fills it out.

2023-02-20 16:41 UTC, philsquared commented on rules/S6191/cfamily/rule.adoc
> +To specify that every read and write has an impact outside of the abstract machine of the language, it is possible to qualify the access to a variable as `volatile`. In that case, the program must pe
second part of first sentence could be: "access to a variable may be qualified as `volatile`"

2023-02-20 16:44 UTC, philsquared requested changes
Overall that reads great! I did have a small concern that it now takes a while to get to the meat of it by expanding on the background that the reader may already be familiar with. I think moving that third paragraph back to the start, as suggested inline, should be enough to counter that. There was one more comment along the lines of "omit needless words", too.

2023-02-20 17:50 UTC, merged