S3398: Add C# description
SonarSource/rspec pull request #1572
Opened 2023-02-14 07:49 UTC by zsolt-kolbay-sonarsource

https://github.com/SonarSource/sonar-dotnet/issues/6706

2023-02-15 10:54 UTC, antonioaversa approved these changes
LGTM, just a non-blocking remark on the use of the word `inner`.

2023-02-15 10:54 UTC, antonioaversa commented on rules/S3398/description.adoc
> +When a ``++private++`` method is only invoked by an inner class, there's no reason not to move it into that class. It will still have the same access to the outer class' members, but the outer class
Up to you actually, but I would not use the word `inner class`, but `nested class`. 

Nested is the standard way "types within types" are defined (c.p. https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/nested-types).

While calling them nested or inner doesn't make any difference in C#, it does in Java (where the rule was first implemented), where inner classes have a reference to the outer class `this` and nested classes (which are called `static class`) don't.

The example in the Java code shows that they actually meant inner, since `Outie.this.increment();` is used. So using `nested` in C# would in my opinion avoid some confusion.

2023-02-15 14:32 UTC, zsolt-kolbay-sonarsource commented on rules/S3398/description.adoc
> +When a ``++private++`` method is only invoked by an inner class, there's no reason not to move it into that class. It will still have the same access to the outer class' members, but the outer class
Couldn't agree more. Renamed it.

2023-02-15 16:38 UTC, andrei-epure-sonarsource requested changes

2023-02-15 16:38 UTC, andrei-epure-sonarsource commented on rules/S3398/csharp/rule.adoc
> +When a ``++private static++`` method is only invoked by a nested class, there's no reason not to move it into that class. It will still have the same access to the outer class' members, but the outer
no need for `++` - this is only needed for special characters.

see https://github.com/SonarSource/rspec/pull/1506#discussion_r1086269791 for details

2023-02-15 16:38 UTC, andrei-epure-sonarsource commented on rules/S3398/csharp/rule.adoc
> +When a ``++private static++`` method is only invoked by a nested class, there's no reason not to move it into that class. It will still have the same access to the outer class' members, but the outer
should you also say 
```suggestion
When a ``++private static++`` method is only invoked by a nested class, there's no reason not to move it into that class. It will still have the same access to the outer class' static members, but the outer class will be clearer and less cluttered.
```

2023-02-15 16:38 UTC, andrei-epure-sonarsource commented on rules/S3398/csharp/rule.adoc
> +    public void OuterMethod()
I don't get this : where is this used? shouldn't it be removed?

2023-02-15 16:38 UTC, andrei-epure-sonarsource commented on rules/S3398/csharp/rule.adoc
> +        Console.WriteLine(num);
you could also have a private static field inside `Outer` and have it here `num + staticNum` (that's what "It will still have the same access to the outer class' members" is mentioning)

[like this](https://sharplab.io/#v2:C4LghgzsA+ACDMACWAmRA5A9gOwMaYFsAHAGwEsxthEBvAWAChFnEiAnMgNzGAFNkAjADZEZKogBmZXiQAmAbkYtkSMdQBi0uYgC8APklaFSlieYB6c4nyz+sAAyIAktmy82Z1h259BI2AKOALK8wAAWmLIAFACUugYARAmIANSGMsYMnuxcPHZoLm4eTCz0JcrMCILBoRGyArHxiCHhkbGK5YgAvow9Wf1VqIgAwoSkFOJlyjk+dsKi4lIZHcpVaoiaGU1Lch2eltaRdo6F7ozZ3nnIBa5nnVMVzDNXAf6BzbVtcfqISanpu3OnVWSACNVa9UaPxadXaZk8fT6QA===)

2023-02-15 16:38 UTC, andrei-epure-sonarsource commented on rules/S3398/java/rule.adoc
> +include::../description.adoc[]
what about `swift`?

https://sonarsource.github.io/rspec/#/rspec/S3398/swift

2023-02-15 16:38 UTC, andrei-epure-sonarsource commented on rules/S3398/rule.adoc
> -When a ``++private++`` method is only invoked by an inner class, there's no reason not to move it into that class. It will still have the same access to the outer class' members, but the outer class
why extract this in a separate description for the rest of the languages, if anyway we don't use it in C#?

Wouldn't it be cleaner just to keep the C# changes and let everything else as it is? (as it doesn't change anything)?

2023-02-28 10:19 UTC, andrei-epure-sonarsource approved these changes
LGTM

2023-03-02 10:08 UTC, merged