Modify rule S4423: Add Docker (APPSEC-460)
SonarSource/rspec pull request #1585
Opened 2023-02-20 10:14 UTC by egon-okerman-sonarsource

Specification: [APPSEC-460](https://sonarsource.atlassian.net/browse/APPSEC-460)
Implementation: [SONARIAC-599](https://sonarsource.atlassian.net/browse/SONARIAC-599)
PoC: https://github.com/SonarSource/appsec-poc/pull/105

[Preview](https://sonarsource.github.io/rspec/#/rspec/S4423/docker)

2023-02-21 08:42 UTC, pierre-loup-tristant-sonarsource requested changes
I think the messages could be more precise, especially when an option is omitted.

2023-02-22 16:20 UTC, pierre-loup-tristant-sonarsource commented
The current message we have for most rules is: "Change this code to use a stronger protocol."
In general I think it's not great and should be updated.

For the docker rule, I suggest one of the following messages:

- "Change this code to enforce TLS 1.2 or above."
- "Change this code to disable support of older TLS versions."

2023-02-22 16:27 UTC, egon-okerman-sonarsource commented on rules/S4423/docker/metadata.json
> +        "MASVS": [],
Added to our backlog: [APPSEC-488](https://sonarsource.atlassian.net/browse/APPSEC-488)

2023-02-23 09:01 UTC, pierre-loup-tristant-sonarsource approved these changes
LGTM

2023-02-23 09:12 UTC, pierre-loup-tristant-sonarsource commented
@egon, you can maybe rebase the PR to make sure the `validate_links` check is passing.

2023-02-23 13:27 UTC, merged