Feature/education new checks
SonarSource/rspec pull request #1587
Opened 2023-02-23 12:57 UTC by ilia-kebets-sonarsource

2023-02-24 15:23 UTC, arseniy-sonar commented on docs/how_to_fix_it_subsection_names.adoc
> +* How does this work?
This starts to crowd out the actual documentation. I suggest moving the *_names.adoc files into a subdirectory

2023-02-27 16:01 UTC, ilia-kebets-sonarsource commented
The errors in the `validate_asciidoc` check are the following:

```
Rule java:S2083 has duplicate "How to fix it" subsections. There are 2 occurences of "Pitfalls"
Rule csharp:S2631 has a "Resources" subsection with an unallowed name: "Articles"
Rule java:S2631 has a "Resources" subsection with an unallowed name: "Articles"
Rule javascript:S2631 has a "Resources" subsection with an unallowed name: "Articles"
Rule php:S2631 has a "Resources" subsection with an unallowed name: "Articles"
Rule python:S2631 has a "Resources" subsection with an unallowed name: "Articles"
Rule csharp:S3649 has a "Resources" subsection with an unallowed name: "Articles"
Rule java:S3649 has a "Resources" subsection with an unallowed name: "Articles"
Rule javascript:S3649 has a "Resources" subsection with an unallowed name: "Articles"
Rule php:S3649 has a "Resources" subsection with an unallowed name: "Articles"
Rule python:S3649 has a "Resources" subsection with an unallowed name: "Articles"
Rule javascript:S5696 has a "Resources" subsection with an unallowed name: "Articles"
```

These are legitimate and should be fixed:
- There are indeed 2 `Pitfalls` sections for the JAVA SE framework
- We have discussed that the allowed subsections for `Resources` are: `Documentation`, `Articles & Blog Posts`, `Conference Presentations`, `Standards`. Should we rename it to Articles & Blog Posts?

2023-02-27 16:42 UTC, ilia-kebets-sonarsource commented on docs/how_to_fix_it_subsection_names.adoc
> +* How does this work?
@arseniy-sonar done: https://github.com/SonarSource/rspec/pull/1587/commits/fd6d6680690fc65572f497f4a71baa1b193c2f40

2023-02-28 14:58 UTC, christophe-zurn-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +  if progressive_education_titles:
The `Resources` section is now optional

2023-02-28 14:59 UTC, christophe-zurn-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +ACCEPTED_PROGRESSIVE_EDUCATION_SECTION_NAMES: Final[list[str]] = parse_names('rspec-tools/rspec_tools/validation/names/progressive_education_section_names.adoc')
As discussed offline, for simplicity we could get rid of the `progressive` prefix and simply use `education` instead

2023-02-28 15:04 UTC, christophe-zurn-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +        raise RuleValidationError(f'Rule {rule_language.id} has unconventional header "{title}"')
This check could be done in all cases, even when we are in the new format

2023-02-28 17:16 UTC, christophe-zurn-sonarsource approved these changes
LGTM!

2023-02-28 17:16 UTC, christophe-zurn-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +    if missing_titles and missing_titles != OPTIONAL_EDUCATION_SECTION_NAMES:
As `OPTIONAL_EDUCATION_SECTION_NAMES` is a list, it might be more robust to check whether the difference between them is empty
```suggestion
    if difference(missing_titles, OPTIONAL_EDUCATION_SECTION_NAMES):
```

2023-03-01 14:41 UTC, arseniy-sonar requested changes
About the section title lists:
These lists are written in asciidoc to serve a double purpose and eliminate duplication that potentially leads to an inconsistency:
- the list is used in the documentation - docs/description.adoc
- the list is used in the validation script to make sure rules comply with what is written in the documentation.

To implement this strategy, you should use the same lists in the documentation ("Types of rule description"/"3. Progressive Education"). Given that now you have also predefined lists for nested section names, perhaps the format of a single list is not suitable anymore, and you can go for a nested list in the .adoc file as well, i.e., the list you have inlined the description.adoc now.

If you think it is more inconvenient than it is useful, let's discuss it.

BTW, the link to `section_names.adoc` in the `docs/description.adoc` is broken now.

2023-03-01 14:41 UTC, arseniy-sonar commented on rspec-tools/tests/resources/invalid-rules/S200/common/rule.adoc
> +== Resources
Looking at this file alone, it is hard to tell why this is an invalid rule. Is it missing the required sections, or mixes education/non-education sections? I would put a comment into the adoc to explain what's wrong about this rule.

2023-03-01 14:41 UTC, arseniy-sonar commented on rspec-tools/tests/resources/invalid-rules/S200/cpp/rule.adoc
> +=== Yolo
```suggestion
=== Yolo (invalid section)
```

2023-03-01 14:41 UTC, arseniy-sonar commented on rspec-tools/tests/resources/invalid-rules/S200/csharp/rule.adoc
> +=== Pitfalls
Again, I would be more explicit to show why this rule is invalid. Is it an unexpected section title?

2023-03-01 14:41 UTC, arseniy-sonar commented on rspec-tools/tests/resources/invalid-rules/S200/java/rule.adoc
> +=== Yolo
```suggestion
=== Yolo (invalid section name)
```

2023-03-01 14:41 UTC, arseniy-sonar commented on rspec-tools/tests/resources/invalid-rules/S200/javascript/rule.adoc
> +=== How to fix it in Express.js
If I assume correctly, the problem here is duplicate sections.
Would non-empty sections with different content but the same title still trigger the violation?
```suggestion
=== How to fix it in Express.js
This is one way to fix it in Express.js
=== How to fix it in Express.js
This is another way to fix it in Express.js.
Invalid rule because of the duplicate section
```

2023-03-01 14:41 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +def dfs(collector, node, level):
I believe you could use something like `node.find_all('h3')` instead of implementing your own DFS

2023-03-01 17:03 UTC, ilia-kebets-sonarsource commented on rspec-tools/tests/resources/invalid-rules/S200/javascript/rule.adoc
> +=== How to fix it in Express.js
The issue is that there are more than the allowed number of 6 frameworks here. Also, I deleted this file, as we actually use the one in S101.

2023-03-01 17:04 UTC, ilia-kebets-sonarsource commented on rspec-tools/tests/resources/invalid-rules/S200/javascript/rule.adoc
> +=== How to fix it in Express.js
I commented there though

2023-03-01 17:33 UTC, ilia-kebets-sonarsource commented on rspec-tools/tests/resources/invalid-rules/S200/javascript/rule.adoc
> +=== How to fix it in Express.js
https://github.com/SonarSource/rspec/pull/1587/commits/3db0dfbbb7c90a2fdfc07a03f136ea895dfcdfd0

2023-03-02 08:41 UTC, ilia-kebets-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +def dfs(collector, node, level):
https://github.com/SonarSource/rspec/pull/1587/commits/9d3d5d283ef5953d8cd20dfa039c25e375600787

2023-03-02 08:43 UTC, ilia-kebets-sonarsource commented on rspec-tools/tests/resources/invalid-rules/S200/common/rule.adoc
> +== Resources
https://github.com/SonarSource/rspec/commit/3db0dfbbb7c90a2fdfc07a03f136ea895dfcdfd0

2023-03-02 08:43 UTC, ilia-kebets-sonarsource commented on rspec-tools/tests/resources/invalid-rules/S200/csharp/rule.adoc
> +=== Pitfalls
https://github.com/SonarSource/rspec/pull/1587/commits/9fdbd668cb3c4e518503347cd32d5b8a2b8f8ff3

2023-03-02 10:21 UTC, arseniy-sonar requested changes
As discussed offline, let's leave fixing the section header levels to a follow-up PR.

Thank you for addressing all points. Only one is remaining that I didn't explain properly.
The purpose of the section lists in the adoc file is to have a single source of truth for the documentation of RSPEC and for the validation. Right now the numerous list files are not very usable as a documentation, and are duplicated in the docs/description.adoc section. I suggest collate these list files into one file with a nested list of allowed sections and include it both into documentation and into the validation script.

2023-03-02 11:02 UTC, closed without merging