S3900: Update rule description and message
SonarSource/rspec pull request #1597
Opened 2023-03-01 15:25 UTC by zsolt-kolbay-sonarsource

https://github.com/SonarSource/sonar-dotnet/issues/2643

2023-03-02 07:43 UTC, martin-strecker-sonarsource requested changes

2023-03-02 07:43 UTC, martin-strecker-sonarsource commented on rules/S3900/csharp/rule.adoc
Below, in the example:
* Beginning the *Noncompliant Code Example* section with a compliant example is confusing. Maybe we should put the `Foo` example last?
* Grammar: `// Compliant: other not being dereferenced` -> `// Compliant: "other" is not dereferenced`
* Simplify ``++ValidatedNotNullAttribute++`` 
* Consider adding an AttributeUsage attribute to the user-defined Attribute as it is good practice to do so `[AttributeUsage(AttributeTargets.Parameter, Inherited=false)]`

2023-03-02 07:43 UTC, martin-strecker-sonarsource commented on rules/S3900/csharp/rule.adoc
Have you discussed the exceptions already? I would add
* [ArgumentNullException.ThrowIfNull Method (System) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.argumentnullexception.throwifnull?view=net-7.0) (.Net 7+)
* [NotNullAttribute](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#postconditions-maybenull-and-notnull) (C#8)
* [ReSharper Code annotation attributes: NotNullAttribute](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#NotNullAttribute)

2023-03-02 07:43 UTC, martin-strecker-sonarsource commented on rules/S3900/csharp/rule.adoc
We should consider to provide a correct implementation for the Guard class that corresponds to 
https://github.com/dotnet/runtime/blob/6a218ab799e56d4ebaffda550de06a9a73a88b14/src/libraries/System.Private.CoreLib/src/System/ArgumentNullException.cs#L59
Downside is, that CallerArgumentExpression is .Net Core 3+ only.

I would also remove the `this` as the method isn't called as an extension method, and providing extension methods for `object` is not recommended.

```cs
public static void NotNull<T>([ValidatedNotNullAttribute] T value, [CallerArgumentExpression("value")] string name = "") where T : class`

Guard.NotNull(value);
```

2023-03-02 17:10 UTC, zsolt-kolbay-sonarsource commented on rules/S3900/csharp/rule.adoc
Thank you for the thorough review!
- I moved the `Foo()` compliant method to the Compliant section and addressed the grammar/formatting issues.
- I've added the `AttributeUsage` attribute.
- I've added a sample for `ArgumentNullException.ThrowIfNull()` to the Compliant section, and the Microsoft/Resharper annotations to the list of exceptions.
- `NotNull()` is no longer an extension method, and I've added the `CallerArgumentExpression` attribute to the second parameter.

2023-03-02 18:12 UTC, martin-strecker-sonarsource requested changes

2023-03-02 18:12 UTC, martin-strecker-sonarsource commented on rules/S3900/csharp/rule.adoc
> +Parameters marked with https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis[attributes for null-state static analysis] - `[NotNull]` or `[DisallowNull]` - a
I think `[DisallowNull]` is a pre-condition and does not fit here. It is only useful if applied to ref parameter as far as I can tell. See e.g. this [example](https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzguATEBqAPgAQCYBGAWACh8AGAAn2IDoARKCAcxgHs0oBjFBgGFOGAKYBBGBAA2ATxRQUAbgoUAxDACu06RGDTRNUVP2jVlAMx1CNQTQDeFGs5oB6VzQDaLFDOmcAdwA5bWkAXRoAWgA+GgAVAAtDACdRADMaAAcIZIgwUQRRZJowKDYEhBpgQy0dGgg0wuSAnIwUOCrNSsUaLkq/QNEMLNQUGlhe0KcXfCt8ABYaAFkACm9FAeDQsNSMzmAAK1FeBAB+Gk4ASgdplxdOGgBeSZ0VcjuAX1uab9m6RaWxBWl2+jned3uh2OZwuT16ogCFyhJ2BbwhLncsOetWkSjcHgAPJEaC1kjAxlA9uMxjjvndVrsLpc0S4vuQPkA==).

2023-03-02 18:12 UTC, martin-strecker-sonarsource commented on rules/S3900/csharp/rule.adoc
> +Parameters marked with https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis[attributes for null-state static analysis] - `[NotNull]` or `[DisallowNull]` - a
```suggestion
Arguments validated for `null` via helper methods should be annotated with the https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#postconditions-maybenull-and-notnull[`[NotNull]`] attribute.
```

2023-03-02 18:12 UTC, martin-strecker-sonarsource commented on rules/S3900/csharp/rule.adoc
> +Parameters marked with the `[NotNull]` https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#ItemNotNullAttribute[Resharper code annotation attribute] are ignored as wel
```suggestion
Parameters marked with the `[NotNull]` https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#ItemNotNullAttribute[Resharper code annotation attribute] are supported as well.
```

2023-03-02 18:12 UTC, martin-strecker-sonarsource commented on rules/S3900/csharp/rule.adoc
> +    public static void NotNull<T>([ValidatedNotNullAttribute] T value,  [CallerArgumentExpression("value")] string name) where T : class
```suggestion
    public static void NotNull<T>([ValidatedNotNullAttribute] T value,  [CallerArgumentExpression("value")] string name = "") where T : class
```

2023-03-02 18:12 UTC, martin-strecker-sonarsource commented on rules/S3900/csharp/rule.adoc
I think it would make sense to name the methods
* Foo
* Bar
* Baz
* Qux

in that order or something related to https://en.wikipedia.org/wiki/Metasyntactic_variable

2023-03-03 13:35 UTC, zsolt-kolbay-sonarsource commented on rules/S3900/csharp/rule.adoc
> +Parameters marked with https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis[attributes for null-state static analysis] - `[NotNull]` or `[DisallowNull]` - a
Changed it.

2023-03-03 13:35 UTC, zsolt-kolbay-sonarsource commented on rules/S3900/csharp/rule.adoc
> +Parameters marked with the `[NotNull]` https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#ItemNotNullAttribute[Resharper code annotation attribute] are ignored as wel
Done.

2023-03-06 08:38 UTC, martin-strecker-sonarsource requested changes

2023-03-06 08:38 UTC, martin-strecker-sonarsource commented on rules/S3900/csharp/rule.adoc
> +    public void Bar(MyOtherClass other)
The `Bar` in the compliant section is the one with the `protected` modifier. You exchange the code of the Bar and Baz methods.

2023-03-06 08:38 UTC, martin-strecker-sonarsource commented on rules/S3900/csharp/rule.adoc
>  ----
```suggestion
[source,csharp]
----
```

2023-03-06 08:38 UTC, martin-strecker-sonarsource commented on rules/S3900/csharp/rule.adoc
> +    public static void NotNull<T>([ValidatedNotNullAttribute] T value,  [CallerArgumentExpression("value")] string name = "") where T : class
```suggestion
    public static void NotNull<T>([ValidatedNotNullAttribute] T value, [CallerArgumentExpression("value")] string name = "") where T : class
```

2023-03-06 14:14 UTC, martin-strecker-sonarsource approved these changes
LGTM

2023-04-13 08:48 UTC, merged