add checks for education format (re-re-based)
SonarSource/rspec pull request #1607
Opened 2023-03-03 08:51 UTC by ilia-kebets-sonarsource

2023-03-03 16:02 UTC, arseniy-sonar requested changes
Thank you for converging the multiple lists of permitted sections into an (almost) single source of truth.
I think it can be improved further in two aspects:
1. "all_section_names.adoc" contains some of the sections from the "education_format_example.adoc", so this makes it harder to keep consistent (if I want to rename or add an education section, I need to remember to change it in these two files), and makes it less precise because now the education sections are allowed for non-education rules, which wasn't the intention, I believe. (BTW, why is it called '*_example"? Is it not the definitive list?).
To address this, I propose to keep two files - one for education, and one for non-education rules: "legacy_section_names.adoc", and "education_format_section_names.adoc", for example. One will be used for non-education rules, and will fail on education rule, and vice-versa. This should also reduce the total validation code for section names.
2. The handling of the "education_format_example.adoc" looks really narrow, and might break if we decide to add a new `== ` section, rename, or reorder the sections. the parsing code is tightly coupled with this particular document. I like how you collect the optional sections. I propose to not make any assumptions about the `== `-level sections, and transform the 2-level nested list into an array of `sections` as you do now + an map of arrays of subsections, i.e.:
`{"Resources" -> ["Articles", "Standards", ...], "How to fix it" -> ["Pitfalls", "Going extra mile"], ...}`
(you can skip the `{framework display name}` in the section name)

I understand that you will need special handling of the `How to fix it in ...` section, but at least all the remaining can be handled in a generic way.

2023-03-03 16:02 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +HOW_TO_FIX_IT_REGEX = re.compile(HOW_TO_FIX_IT)
Why do you use two ways to match this header?
`section.startswith(HOW_TO_FIX_IT)` and `HOW_TO_FIX_IT_REGEX.match(s)`

2023-03-06 16:39 UTC, arseniy-sonar requested changes
Looks good. Only one important issue remains: the asciidoctor built-in validation, see my inline comment

2023-03-06 16:39 UTC, arseniy-sonar commented on ci/validate_asciidoc.sh
> +      if asciidoctor -a rspecator-view -o /dev/null rules/*/*/tmp*.adoc; then
Is there a way to keep failing on other `asciidoctor` warnings?
Would it be possible to skip print the header-level skip warnings for thousands of rules during validation?
Finally, you can remove the `echo "== Description" > "$TMP_ADOC"` workaround on l.76 if you are disabling this check.

2023-03-06 16:39 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +      if HOW_TO_FIX_IT_REGEX.match(section):
```suggestion
      if section.starts_with(HOW_TO_FIX_IT):
```
This might be slightly faster, but more importantly it makes it more correlated with the body of the `if`

2023-03-06 16:39 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +        current_map[section] = set()
```suggestion
        section = HOW_TO_FIX_IT # overwrite previous instances of "How to fix it *" section specifications
      current_section_name = section
      current_map[section] = set()
```

2023-03-06 16:39 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +  return lst3
```suggestion
  return list(set(lst1).intersection(lst2))
```
In harmony with the `difference` function you have below

2023-03-06 16:39 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +        current_map[section] = set()
```suggestion
        section = HOW_TO_FIX_IT
      else:
        if section in current_map:
          raise RuleValidationError(f'Section {section} is mentioned more than once in the specification file')
      current_section_name = section
      current_map[section] = set()
```
If we don't overwrite its subsections, they are gonna accumulate and be duplicated. 
I think the correct way of handling this is to assert that the section wasn't mentioned before, except if it is a HOW_TO_FIX_IT subsection. See my suggestion there

2023-03-06 16:39 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +  education_titles = intersection(h2_titles, list(SECTIONS.keys()) + list(OPTIONAL_SECTIONS.keys()))
If you change the `intersection` second parameter type to a set, you can write this shorter:
```suggestion
  education_titles = intersection(h2_titles, SECTIONS.keys() + OPTIONAL_SECTIONS.keys())
```

2023-03-06 16:39 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +def validate_how_to_fix_it_framework(section_name, rule_language, framework_sections_seen):
```suggestion
  for section_name in how_to_fix_it_sections:
    validate_how_to_fix_it_framework(section_name, rule_language)

def validate_how_to_fix_it_framework(section_name, rule_language):
    framework_sections_seen = set()
```
Why do you keep a single set for all "How to fix it " sections?

2023-03-06 16:39 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +        subsections_seen.add(name)
```suggestion
        if name not in OPTIONAL_SECTIONS[optional_section]:
          raise RuleValidationError(f'Rule {rule_language.id} has a "{optional_section}" subsection with an unallowed name: "{name}"')
        if name in subsections_seen:
          raise RuleValidationError(f'Rule {rule_language.id} has duplicate "{optional_section}" subsections. There are 2 occurences of "{name}"')
        subsections_seen.add(name)
```
This code is duplicated in `validate_how_to_fix_it_subsections` and `validate_how_to_fix_it_framework`

2023-03-06 16:40 UTC, ilia-kebets-sonarsource commented on rspec-tools/tests/resources/invalid-rules/S200/scala/rule.adoc
> +=== Documentation
Yes, I'll add a comment

2023-03-06 16:41 UTC, ilia-kebets-sonarsource commented on rspec-tools/tests/resources/invalid-rules/S200/javascript/rule.adoc
> +== How to fix it in Razor
duplicate frameworks, will add a comment

2023-03-06 16:42 UTC, ilia-kebets-sonarsource commented on rspec-tools/tests/resources/invalid-rules/S101/javascript/rule.adoc
> +== How to fix it in Express.js
I believe the number gets triggered before in the implementation. I'll refactor the titles to trigger that only.

2023-03-06 16:44 UTC, ilia-kebets-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +        current_map[section] = set()
I've reworked this one now.

2023-03-06 16:49 UTC, ilia-kebets-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +        subsections_seen.add(name)
Yes, it has been refactored as `validate_subsections`

2023-03-06 16:50 UTC, ilia-kebets-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +  education_titles = intersection(h2_titles, list(SECTIONS.keys()) + list(OPTIONAL_SECTIONS.keys()))
I'm getting the following error:

```
>     education_titles = intersection(h2_titles, SECTIONS.keys() + OPTIONAL_SECTIONS.keys())
E     TypeError: unsupported operand type(s) for +: 'dict_keys' and 'dict_keys'
```

2023-03-06 16:53 UTC, ilia-kebets-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +def validate_how_to_fix_it_framework(section_name, rule_language, framework_sections_seen):
`validate_how_to_fix_it_framework` checks a single `How to fix it in...` section, so I must collect the framework names one level above.

2023-03-06 16:54 UTC, ilia-kebets-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +        current_map[section] = set()
I used sets instead of the initial lists to handle the duplicate subsections.

2023-03-06 16:59 UTC, ilia-kebets-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +        current_map[section] = set()
I believe that a check for the tooling itself is a bit overkill, no?

2023-03-06 17:52 UTC, ilia-kebets-sonarsource commented on ci/validate_asciidoc.sh
> +      if asciidoctor -a rspecator-view -o /dev/null rules/*/*/tmp*.adoc; then
> Is there a way to keep failing on other asciidoctor warnings?
not sure, but I've changed to fail on [errors](https://docs.asciidoctor.org/asciidoctor/latest/errors-and-warnings/#error) 
> Would it be possible to skip print the header-level skip warnings for thousands of rules during validation?
I guess with a regex on stdout?
> Finally, you can remove the echo "== Description" > "$TMP_ADOC" workaround on l.76 if you are disabling this check.
Since we're keeping errors, we still need this, right?

2023-03-07 07:51 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +  education_titles = intersection(h2_titles, list(SECTIONS.keys()) + list(OPTIONAL_SECTIONS.keys()))
Nevermind then, sorry. I thought `dict.keys()` returns a set, but it returns `dict_keys`

2023-03-07 08:25 UTC, arseniy-sonar requested changes
The validation code looks good, good job refactoring!
The only point remaining is the [spam of the warnings](https://cirrus-ci.com/task/5020001413890048?logs=asciidoc_tests#L86) coming from level-skipping of the code-example subsections. Even now, with few rules implementing this format these warning constitute 484 lines of the full 573-line long validation log. This makes the log hard to read, and it is important to see when some other rule error happens, because that has direct effect on the rule descriptions that are displayed to the clients.
It is not an option to send the asciidoctor output to /dev/null as it has other useful diagnostics.
What do you think can be done here?
Shall we raise the examples to the h3 level (the same level as the "What is the potential impact?" subsection)?
This would also allow RSPEC tooling to check the names of these sections, as it does it for the legacy format. And is an important point since, I think products might rely on the names of these sections, for example, to show examples side-by-side.

2023-03-07 08:25 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +    titles = collect_titles(resources_section, 3)
```suggestion
  top_level_section = descr.find('h2', string=section_regex)
  if top_level_section is not None:
    titles = collect_titles(top_level_section, 3)
```

2023-03-07 08:25 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +def validate_subsections_for_map(rule_language: LanguageSpecificRule, section_name: str, map, section_regex = None):
```suggestion
def validate_subsections_for_map(rule_language: LanguageSpecificRule, section_name: str, allowed_subsections: set[str], section_regex = None):
```
this makes it more explicit, and reduces the number of lookups to the `SECTIONS` map

2023-03-07 08:25 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +def validate_how_to_fix_it_framework(section_name, rule_language, framework_sections_seen):
I see now. I find this pretty hard to follow. Moreover, you are essentially passing validation of the "how to fix it" section name to the `validate_how_to_fix_it_framework` callee.
Since you already have the list of all "how to fix it in" sections: `how_to_fix_it_sections`, why not check duplication of section names in `validate_how_to_fix_it_sections_names`? For example:
```
  duplicate_names = [x for x in how_to_fix_it_sections if how_to_fix_it_sections.count(x) > 1] # O(n*n) is fine, given n <= 6
  if 0 < duplicate_names.len():
    raise RuleValidationError(f'Rule {rule_language.id} has duplicate "{HOW_TO_FIX_IT}" sections "{duplicate_names}"')
```

2023-03-07 08:37 UTC, ilia-kebets-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +def validate_subsections_for_map(rule_language: LanguageSpecificRule, section_name: str, map, section_regex = None):
done in e45c99c72

2023-03-07 08:38 UTC, ilia-kebets-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +    titles = collect_titles(resources_section, 3)
Thanks!

2023-03-07 08:41 UTC, arseniy-sonar commented on ci/validate_asciidoc.sh
> +      if asciidoctor -a rspecator-view -o /dev/null rules/*/*/tmp*.adoc; then
Right, I did not realise it was an error and warning-level

2023-03-07 09:33 UTC, ilia-kebets-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +def validate_how_to_fix_it_framework(section_name, rule_language, framework_sections_seen):
done

2023-03-07 15:41 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/description.py
> +SECTIONS = {
Just like in the doc, please, add a comment here warning the developer that they should change the list in the documentation if these maps are updated

2023-03-07 15:57 UTC, ilia-kebets-sonarsource commented on docs/description.adoc
> +Content of the section "_3. How to fix it_" (i.e. subsections 3.a, 3.b, 3.c and 3.d) may be repeated multiple times, as
I didn't touch this because it is heavily modified by the other PR: https://github.com/SonarSource/rspec/pull/1610/files

2023-03-07 15:58 UTC, ilia-kebets-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +SECTIONS = {
done https://github.com/SonarSource/rspec/pull/1607/commits/f01bbbb92b07348717aa21cf5b668dbadef7a6d1

2023-03-07 16:16 UTC, merged