SONARPY-1303 add metadata for python for S6001
SonarSource/rspec pull request #1672
Opened 2023-03-20 16:40 UTC by maksim-grebeniuk-sonarsource

2023-03-22 14:36 UTC, guillaume-dequenne-sonarsource requested changes
I think we need a Python-specific description for this rule.

2023-03-22 14:36 UTC, guillaume-dequenne-sonarsource commented on rules/S6001/description.adoc
> +When a back reference in a regex refers to a capturing group that hasn't been defined yet (or at all), it can never be matched. Named back references throw a ``++PatternSyntaxException++`` in that ca
I believe `PatternSyntaxException` is a Java exception, we shouldn't refer to it in the Python rule description. We should probably have a Python-specific `description.adoc` which describe the actual Python behavior.

2023-03-23 13:47 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM.

2023-03-23 13:53 UTC, maksim-grebeniuk-sonarsource commented on rules/S6001/python/rule.adoc
> +pattern = re.compile(r"\1(.)", re.DOTALL) # Noncompliant, group 1 is defined after the back reference
done

2023-03-23 13:57 UTC, merged