Modify rule S5950: Fix typos + rewording (CPP-4142)
SonarSource/rspec pull request #1674
Opened 2023-03-21 11:03 UTC by amelie-renard-sonarsource

2023-03-21 15:10 UTC, phil-nash-sonarsource commented on rules/S5950/cfamily/rule.adoc
> +`make_unique()`, on the other hand, doesn't impact performances.
Replace the two uses of "performances" with "performance"

2023-03-21 15:13 UTC, phil-nash-sonarsource commented on rules/S5950/cfamily/rule.adoc
> +`make_unique()`, on the other hand, doesn't impact performances.
"`make_shared()` still impacts performance" - relative to what?

2023-03-21 15:16 UTC, phil-nash-sonarsource requested changes
See inline comments

2023-03-21 15:51 UTC, amelie-renard-sonarsource commented on rules/S5950/cfamily/rule.adoc
> +`make_unique()`, on the other hand, doesn't impact performances.
Mmm, I misunderstood the paragraph. I've rewritten it, I hope it's clearer

2023-03-22 09:26 UTC, loic-joly-sonarsource reviewed
I'd be happy if a native speaker (yes, looking at you @phil-nash-sonarsource) could check my comments.

2023-03-22 09:26 UTC, loic-joly-sonarsource commented on rules/S5950/cfamily/rule.adoc
> +Note: This scenario can only happen before {cpp}17. From {cpp}17, the standard states that each argument needs to be thoroughly evaluated before evaluating the other arguments. So the explicit constr
I'm not sure, but this wording sounds slightly strange to me...
```suggestion
Note: This scenario can only happen before {cpp}17. Starting with {cpp}17, the standard states that each argument needs to be thoroughly evaluated before evaluating the other arguments. So the explicit construction of `unique_ptr` and `shared_ptr` become exception-safe.
```

2023-03-22 09:26 UTC, loic-joly-sonarsource commented on rules/S5950/cfamily/rule.adoc
> +Note: This scenario can only happen before {cpp}17. From {cpp}17, the standard states that each argument needs to be thoroughly evaluated before evaluating the other arguments. So the explicit constr
I'm not sure either about the word "thoroughly".
```suggestion
Note: This scenario can only happen before {cpp}17. From {cpp}17, the standard states that even though the order of evaluation of each argument is still unspecified, interleaving the evaluation of different arguments is no longer allowed. This makes the direct construction of `unique_ptr` and `shared_ptr` exception-safe.
```

2023-03-23 08:06 UTC, amelie-renard-sonarsource commented on rules/S5950/cfamily/rule.adoc
> +Note: This scenario can only happen before {cpp}17. From {cpp}17, the standard states that each argument needs to be thoroughly evaluated before evaluating the other arguments. So the explicit constr
I don't know about the first comment, but I like your second suggestion.

2023-03-23 08:18 UTC, philsquared commented on rules/S5950/cfamily/rule.adoc
> +Note: This scenario can only happen before {cpp}17. From {cpp}17, the standard states that each argument needs to be thoroughly evaluated before evaluating the other arguments. So the explicit constr
I think "From" was ok. "Starting with" is better. Or perhaps, "Since".

2023-03-23 08:19 UTC, philsquared commented on rules/S5950/cfamily/rule.adoc
> +Note: This scenario can only happen before {cpp}17. From {cpp}17, the standard states that each argument needs to be thoroughly evaluated before evaluating the other arguments. So the explicit constr
I agree that Loïc's second comment is a good improvement. LGTM. Ship it!

2023-03-23 08:56 UTC, philsquared commented on rules/S5950/cfamily/rule.adoc
That is the case I had in mind, yes. I think a mention in the rspec that this is a valid exception should be enough. I don't think it is that common, in practice.

2023-03-23 08:58 UTC, amelie-renard-sonarsource commented on rules/S5950/cfamily/rule.adoc
Okay, I'll add something about that

2023-03-31 15:46 UTC, phil-nash-sonarsource commented on rules/S5950/cfamily/rule.adoc
> +Note: Because `make_shared` performs only one allocation for both the object and the control block, the memory occupied by the object will be deallocated when no `shared_ptr` or `weak_ptr` points to
I think "never mind the weak ones" sounds a little too informal for this setting. How about something like, "independently of any `weak_ptr`s" ?

2023-03-31 15:47 UTC, phil-nash-sonarsource requested changes
Just one more minor change (inline) and this is good to go.

2023-04-03 06:13 UTC, amelie-renard-sonarsource commented on rules/S5950/cfamily/rule.adoc
> +Note: Because `make_shared` performs only one allocation for both the object and the control block, the memory occupied by the object will be deallocated when no `shared_ptr` or `weak_ptr` points to
Sounds good to me

2023-04-03 06:17 UTC, merged