Modify rule S6437: Change the noncompliant example (PLSQL-S2492)
SonarSource/rspec pull request #1775
Opened 2023-04-18 16:22 UTC by gregory-paidis-sonarsource

This is a fix for [this issue](https://discuss.sonarsource.com/t/parse-error-on-noncompliant-example-of-plsql-namingtypescheck/12627)

2023-04-19 08:42 UTC, csaba-sagi-sonarsource commented on rules/S2492/plsql/rule.adoc
>  BEGIN
Why didn't you address the "_Compliant Solution has unneeded {code}_" comment from Michal?

2023-04-19 08:42 UTC, csaba-sagi-sonarsource requested changes
I think we can improve the examples further.

2023-04-20 07:44 UTC, gregory-paidis-sonarsource commented on rules/S2492/plsql/rule.adoc
>  BEGIN
you are right, thanks for noticing it :)

2023-04-20 09:08 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2023-04-20 09:11 UTC, merged