Modify rule S6544: include cases where promises are not resolved or error handled
SonarSource/rspec pull request #1780
Opened 2023-04-19 15:37 UTC by ilia-kebets-sonarsource

2023-04-20 12:04 UTC, yassin-kammoun-sonarsource requested changes
It's getting difficult to understand what the rule is all about now. This is why I think we need to introduce subsections to structure a bit the rule description.

I would move the main description in the section "Why is this an issue" and rework it as follows:

_[start]_

Promises need to be resolved or awaited to perform the expected asynchronous task and return a value, if any. Otherwise, they are nothing else than a regular object.

### Unresolved promises

Forgetting to await a promise is a frequent mistake. There are places where it makes no sense to use a promise object as it is. This is likely a bug as the developer forgot to resolve it.

The rule forbids returning promises where another type is expected such as in:

* conditionals
* void returns
* spread operators

### Missing error handling

When a promise raises an exception but doesn't have proper error handling, the program's call stack will be inconsistent and difficult to understand. (would be nice to have an example with a misleading call stack or strack trace)

_[end]_

2023-04-20 13:18 UTC, ilia-kebets-sonarsource commented on rules/S6544/javascript/rule.adoc
> +This rule can be ignored for promises that you know will always resolve like timers.
Timers are an example, but there are indeed cases when people promisify event based code, which cannot reject.

2023-04-20 13:18 UTC, ilia-kebets-sonarsource commented on rules/S6544/javascript/rule.adoc
> +This rule can be ignored for promises that you know will always resolve like timers.
So it's not an implemented exception.

2023-04-20 13:21 UTC, ilia-kebets-sonarsource commented on rules/S6544/javascript/rule.adoc
> +Promises that aren't resolved will run at an unexpected time, when they do not contain error handling and they raise an exception, the associated call stack will be wrong.
hmm, I can improve this part. Indeed a promise will start when executed synchronously. But usually promisified code has some process.nextTick() or event-based logic which will run when your code gets on top of the event queue again.

2023-04-20 13:59 UTC, ilia-kebets-sonarsource commented on rules/S6544/javascript/rule.adoc
> +If you mistook the promise with its resolved value, await or resolve the promise so it gets resolved correctly, using an IIFE if necessary:
done

2023-04-20 14:21 UTC, ilia-kebets-sonarsource commented
@yassin-kammoun-sonarsource for the sections "Unresolved promises" and "Missing error handling", it is currently not allowed to have subsections for "why is this an issue", other than "potential impact", that's why I used underlines.

2023-04-20 14:28 UTC, yassin-kammoun-sonarsource approved these changes

2023-04-21 17:18 UTC, cynthiabethea approved these changes
added a few suggestions to consider

2023-04-21 17:18 UTC, cynthiabethea commented on rules/S6544/javascript/rule.adoc
> +If you mistook the promise with its resolved value, await or resolve the promise so it gets resolved correctly, using an "immediately invoked function expression" (IIFE) if necessary:
picky suggestion, I would reword this as:

If you mistakenly treated a promise as its resolved value, you can ensure it is properly resolved by using await or resolve on the promise. In some cases, you may need to use an "immediately invoked function expression" (IIFE).

2023-04-24 07:28 UTC, merged