Modify rule S3949: Remove CBDE from C#, add VB.NET
SonarSource/rspec pull request #1825
Opened 2023-05-01 12:06 UTC by pavel-mikula-sonarsource

https://github.com/SonarSource/sonar-dotnet/issues/7139

2023-05-02 12:35 UTC, Tim-Pohlmann requested changes

2023-05-02 12:35 UTC, Tim-Pohlmann commented on rules/S3949/csharp/rule.adoc
> +}
```suggestion
public long Transform(int value)
{
    if (value <= 0)
    {
        return value;
    }
    long number = int.MaxValue;
    return number + value;
}
```

2023-05-03 06:57 UTC, pavel-mikula-sonarsource commented on rules/S3949/csharp/rule.adoc
> +}
Oops, and it was missing on the VB version

2023-05-03 07:17 UTC, Tim-Pohlmann approved these changes
LGTM

2023-05-22 09:16 UTC, pavel-mikula-sonarsource commented
There are 2 new commits to review

2023-05-26 15:17 UTC, Tim-Pohlmann approved these changes
LGTM

2023-05-26 15:17 UTC, merged