Modify rule S1912: CPP-4028 Take namespace into consideration
SonarSource/rspec pull request #1828
Opened 2023-05-04 08:56 UTC by LoghinVladDev

2023-05-04 09:01 UTC, LoghinVladDev commented
To be merged together with https://github.com/SonarSource/sonar-cpp/pull/2736

2023-05-04 12:55 UTC, LoghinVladDev commented
@necto Please Review details of name lookup, I'm trying to think of a more direct explanation. Input appreciated
Also, would this not be a candidate for the new format? this 'name lookup' could be in the last level of the 'learning' process

2023-05-04 14:04 UTC, necto requested changes

2023-05-04 14:04 UTC, necto commented on rules/S1912/cfamily/rule.adoc
> +Consider the call ``a::b::f()``, and the following cases for the name specified to the list:
This does not say this isn't nested in a different namespace (i.e. your call in this context `namespace c {...; a::b::f();}` won't fit the bullet points below). Moreover, this might confuse users who have a call without full qualification, e.g. `namespace a { ...; using namespace b; ...; f(); }` should still adhere to the same rules described below.

I propose to focus on the function declaration here instead of the function call site. I.e., speak about `namespace a { namespace b { void f(); } }`.

2023-05-04 15:38 UTC, necto commented on rules/S1912/cfamily/rule.adoc
> +- If the function name is fully qualified (list contains ``::a::b::f``), only calls to the function ``f``, from the named scope ``b``, from the global named scope ``a`` will trigger an issue
I find the description in ASTMatcher easier to grasp. Something along the lines:
```suggestion
For example, `namespace a { namespace b { void f(); } }` can be matched with "f", "b::f", "a::b::f", "::a::b::f" (fully qualified name yielding most precise results).
```
Note, that this remark should be concise enough: it matters only when you configure the rule, so it shouldn't take too much space when a developer on your team wants to read about the meaning of the rule.

2023-05-04 15:42 UTC, necto commented on rules/S1912/cfamily/rule.adoc
> +A call will be matched differently depending on the presence of the scope resolution operator ``::`` in the function name from the configurable list.
```suggestion
Depending on the use of the scope resolution operator ``::`` in a function name in `nonReentrantFunctionList`, the rule might flag calls of functions declared in different name scopes.
```

2023-05-04 15:44 UTC, necto commented on rules/S1912/cfamily/rule.adoc
> +It is recommended to provide fully qualified names to the configurable list. This also applies to functions in the global scope.
```suggestion
It is recommended to provide fully qualified names to the configurable list (i.e., start each name with `::`), even for the functions in the global namespace.
```
To be clarified, but I think "global namespace" is more common term than "global name scope"

2023-05-05 07:27 UTC, LoghinVladDev commented on rules/S1912/cfamily/rule.adoc
> +It is recommended to provide fully qualified names to the configurable list. This also applies to functions in the global scope.
I think this is correct for C++. I though from the perspective of C programming. I assume people using POSIX non-reentrant functions would be in majority C programmers. 
Although the topic at hand only happens in C++, so, it would make sense to adopt full C++ terminology

2023-05-05 10:04 UTC, necto approved these changes

2023-05-05 10:04 UTC, necto commented on rules/S1912/cfamily/rule.adoc
> +
```suggestion
A call will be matched differently depending on the presence of the scope resolution operator ``::`` in the function name from the configurable list.
```

The second sentence clarifies the first one, so it would make sense for them to go into the same paragraph.

2023-05-05 11:31 UTC, merged