Create rule S4423: add language AzureResourceManager
SonarSource/rspec pull request #1835
Opened 2023-05-05 15:59 UTC by egon-okerman-sonarsource

[Specification ticket](https://sonarsource.atlassian.net/browse/SONARIAC-755)
[Implementation ticket](https://sonarsource.atlassian.net/browse/SONARIAC-781)
[RSPEC Preview](https://sonarsource.github.io/rspec/#/rspec/S4423/azureresourcemanager)

2023-05-09 08:13 UTC, mstachniuk requested changes
Please see my comments.

2023-05-09 08:13 UTC, mstachniuk commented on rules/S4423/azureresourcemanager/rule.adoc
> +      // ...
IMO we can skip those 2 lines and the same in compliant code examples

2023-05-09 08:13 UTC, mstachniuk commented on rules/S4423/azureresourcemanager/rule.adoc
> +
Please also add examples in Bicep format and comment them for now.

2023-05-09 08:13 UTC, mstachniuk commented on rules/S4423/azureresourcemanager/rule.adoc
> +      // ...
Also, we can skip those 2 lines and line 42, and the same in compliant code examples

2023-05-09 14:31 UTC, egon-okerman-sonarsource commented on rules/S4423/azureresourcemanager/rule.adoc
> +  "$schema": "<https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",>
Fixed but GH is a bit slow today

2023-05-09 14:34 UTC, egon-okerman-sonarsource commented on rules/S4423/azureresourcemanager/rule.adoc
> +
Bicep examples are kept in a separate branch: https://github.com/SonarSource/rspec/tree/rule/S4423/add-bicep. Do you think it is better to add it in comments here?

2023-05-09 14:35 UTC, egon-okerman-sonarsource commented on rules/S4423/azureresourcemanager/rule.adoc
> +      // ...
I added them to signify that there are some lines missing. There are some properties not set that are required.

Do you think it is worth adding those back, or would it just make the file too long?

2023-05-10 08:57 UTC, mstachniuk commented on rules/S4423/azureresourcemanager/rule.adoc
> +        "minimumTlsVersion": "TLS1_0" // Noncompliant
Comments in JSON are not allowed by syntax, please remove it

2023-05-11 15:14 UTC, merged