Modify rule S5000: LaYC format
SonarSource/rspec pull request #1909
Opened 2023-05-16 08:31 UTC by frederic-tingaud-sonarsource

2023-05-16 09:40 UTC, amelie-renard-sonarsource requested changes

2023-05-16 09:40 UTC, amelie-renard-sonarsource commented on rules/S5000/cfamily/rule.adoc
> +The function ``++memcmp++`` only returns meaningful results for objects of trivially copyable types that have no padding. This includes scalar types, arrays, and trivially copyable classes.
```suggestion
The function ``++memcmp++`` only returns meaningful results for objects of trivially copyable types without padding. This includes scalar types, arrays, and trivially copyable classes.
```

2023-05-16 09:40 UTC, amelie-renard-sonarsource commented on rules/S5000/cfamily/rule.adoc
> +`memcmp` compares the raw memory representation of two objects (what the standard calls their _object representation_). For objects that are not trivially copyable or that contain padding, two object
```suggestion
`memcmp` compares the raw memory representation of two objects (what the standard calls their _object representation_). When objects are not trivially copyable or contain padding, they could have different raw memory representations even though they store identical values. So the result of `memcmp` is not meaningful.
```

2023-05-16 09:40 UTC, amelie-renard-sonarsource commented on rules/S5000/cfamily/rule.adoc
>  class Shape { // Trivially copyable, but will contain padding after the bool on most architectures
Do you think we can make the first example more C oriented?

2023-05-16 09:40 UTC, amelie-renard-sonarsource commented on rules/S5000/cfamily/rule.adoc
> +* One or more of the following methods is trivial and the rest are deleted: copy /constructor, move constructor, copy assignment operator, and move assignment operator,
What is a trivial copy constructor? A trivial move constructor? A trivial destructor? etc...
I think this should also be explained, don't you think?

2023-05-16 15:15 UTC, frederic-tingaud-sonarsource commented on rules/S5000/cfamily/rule.adoc
> +* One or more of the following methods is trivial and the rest are deleted: copy /constructor, move constructor, copy assignment operator, and move assignment operator,
Added explanations.

2023-05-16 15:15 UTC, frederic-tingaud-sonarsource commented on rules/S5000/cfamily/rule.adoc
>  class Shape { // Trivially copyable, but will contain padding after the bool on most architectures
Done

2023-05-17 09:08 UTC, amelie-renard-sonarsource approved these changes
A typo and a small suggestion, otherwise looks good!

2023-05-17 09:08 UTC, amelie-renard-sonarsource commented on rules/S5000/cfamily/rule.adoc
> +https://en.cppreference.com/w/cpp/language/classes#Trivially_copyable_class[Detailed definition of what a trivially copyable class is].
```suggestion
https://en.cppreference.com/w/cpp/language/classes#Trivially_copyable_class[Definition of a trivially copyable class].
```

2023-05-17 11:31 UTC, merged