Modify rule S6535: Add diff view to code examples
SonarSource/rspec pull request #1924
Opened 2023-05-22 09:43 UTC by ilia-kebets-sonarsource

2023-05-22 11:37 UTC, vilchik-elena requested changes
Let's move most of introduction to the first section

2023-05-22 17:32 UTC, vilchik-elena requested changes

2023-05-22 17:32 UTC, vilchik-elena commented on rules/S6535/javascript/rule.adoc
> +In JavaScript, the ``++/++`` (backslash) character is used to escape special characters inside a string, a template literal, or a regular expression.
I am not sure why we need a new line for each sentence. It does not look very pretty. I would merge all of them into one paragraph

2023-05-22 17:32 UTC, vilchik-elena commented on rules/S6535/javascript/rule.adoc
>  const regex = /[[]/;
I think some link to the docs about which characters are special and could be escaped would not hurt

2023-05-22 17:32 UTC, vilchik-elena commented on rules/S6535/javascript/rule.adoc
>  const regex = /[\[]/;
could you add a comment here explaining why it's not compliant? `[` seems to be a special char in regex

2023-05-22 17:32 UTC, vilchik-elena commented on rules/S6535/javascript/rule.adoc
>  const octal = '\8';
and here :D

2023-05-22 17:32 UTC, vilchik-elena commented on rules/S6535/javascript/rule.adoc
>  Escaping is only meaningful for special characters.
I think this phrase can be dropped, it does not bring much

2023-05-22 17:32 UTC, vilchik-elena commented on rules/S6535/javascript/rule.adoc
> +Useless character escapes can safely be removed without changing the original behavior.
how about adding a mention that the developer should first make sure that the intention was to simply use the escaped char and that there is no hidden bug.

2023-05-23 11:29 UTC, ilia-kebets-sonarsource commented on rules/S6535/javascript/rule.adoc
>  const regex = /[[]/;
There is no exhaustive link, I have added 2.

2023-05-25 12:42 UTC, closed without merging