Modify rule S4663: Adapt to LaYC
SonarSource/rspec pull request #1926
Opened 2023-05-22 13:03 UTC by frederic-tingaud-sonarsource

2023-06-06 12:35 UTC, vilchik-elena requested changes
I suggest to add code examples for each language

2023-06-06 12:35 UTC, vilchik-elena commented on rules/S4663/rule.adoc
> +A meaningful comment should be added or the comment markers should be removed.
```suggestion
A meaningful text should be added to the comment or the comment markers should be removed.
```

2023-06-06 12:35 UTC, vilchik-elena commented on rules/S4663/rule.adoc
> +An empty multi-line comment doesn't help to improve the readability of the code and might indicate an oversight.
I think `doesn't help` sounds passive aggressive and also I am not sure why we are mentioning readability for this rule.
```suggestion
An empty multi-line comment might indicate an oversight.
```

2023-06-08 13:17 UTC, vilchik-elena commented on rules/S4663/common/code-example.adoc
> +[source,java]
why did you decide to put this fine in the subdir?

2023-06-08 14:04 UTC, vilchik-elena approved these changes

2023-06-08 15:00 UTC, frederic-tingaud-sonarsource commented on rules/S4663/common/code-example.adoc
> +[source,java]
I _felt_ like it would be better in that case, because the include::{variable}[] pattern can be a little confusing. The variable is declared in a subfolder, but interpreted by the include at root. So for example you are inside the java subfolder and your variable says `:example: java/code-example.adoc`. If somebody writes `:example: code-example.adoc` and there is a code-example.adoc at the root, we don't know if they wanted to include the common file and they succeeded or if they didn't understand they need to repeat the folder name. If the common file is also in a subfolder, there can be no doubt it's on purpose.

2023-06-08 15:03 UTC, merged