Modify rule S4144: Adapt to LaYC format
SonarSource/rspec pull request #1935
Opened 2023-05-23 13:22 UTC by frederic-tingaud-sonarsource

2023-05-23 13:23 UTC, frederic-tingaud-sonarsource commented
I don't understand this sentence in the description:
"Numerical and string literals are not taken into account". Does it mean that two methods with identical code except for a numerical value will be considered as identical?

2023-05-25 17:31 UTC, frederic-tingaud-sonarsource commented on rules/S4144/python/rule.adoc
> +Numerical and string literals are not taken into account.
@guillaume-dequenne-sonarsource do you understand this sentence? I moved it here, but I don't understand what it tries to say. IMO, we should reformulate it, remove it, or put some code example to make it clear.

2023-05-26 05:58 UTC, vilchik-elena requested changes

2023-05-26 05:58 UTC, vilchik-elena commented on rules/S4144/cfamily/rule.adoc
> +This rule raises an exception when two methods implemented inside a class definition share the same implementation.
```suggestion
This rule raises an issue when two methods implemented inside a class definition have the same implementation.
```

2023-05-26 05:58 UTC, vilchik-elena commented on rules/S4144/description.adoc
> -When two methods have the same implementation, either it was a mistake - something else was intended - or the duplication was intentional, but may be confusing to maintainers. In the latter case, one
I see that you moved this sentence to the end, but for "go" for example it's not done

2023-05-26 05:58 UTC, vilchik-elena commented on rules/S4144/python/rule.adoc
> +Numerical and string literals are not taken into account.
@frederic-tingaud-sonarsource it means that if 2 functions differ only by string literal value they are considered identical

2023-05-26 05:58 UTC, vilchik-elena commented on rules/S4144/apex/rule.adoc
> +[source,apex,diff-id=1,diff-type=compliant]
IMHO we should avoid 2 separate code blocks without any text between then.
What about `To avoid duplication one implementation can invoke the other.`

2023-05-26 05:58 UTC, vilchik-elena commented on rules/S4144/apex/rule.adoc
the root `exceptions.adoc` file which is included here, does it make sense? is it used a lot? I wonder if it's better to inline it

Also I am not sure what the content of that file means:

```
Methods that are not accessors (getters and setters), with fewer than 2 statements are ignored.
```

Are accessors always ignored? or never?

2023-05-26 12:06 UTC, frederic-tingaud-sonarsource commented on rules/S4144/description.adoc
> -When two methods have the same implementation, either it was a mistake - something else was intended - or the duplication was intentional, but may be confusing to maintainers. In the latter case, one
The sentence is not here in the other languages unless I missed something. And I wonder if it's because they don't ignore numerical and literal values.

2023-05-26 12:35 UTC, frederic-tingaud-sonarsource commented on rules/S4144/apex/rule.adoc
The file is used by the root rules.adoc and by PHP. I understand it as "getter and setter are never ignored, but it might be interesting to have the opinion of somebody from a squad that implemented this rule. Perhaps @leonardo-pilastri-sonarsource you can confirm?

2023-05-26 12:51 UTC, frederic-tingaud-sonarsource commented on rules/S4144/description.adoc
> -When two methods have the same implementation, either it was a mistake - something else was intended - or the duplication was intentional, but may be confusing to maintainers. In the latter case, one
Removing the sentence altogether because no language actually implements this.-

2023-05-26 13:53 UTC, leonardo-pilastri-sonarsource commented on rules/S4144/apex/rule.adoc
I did not work on the rule but by having a look at least at the way the Java check works, it looks like all methods with less than 2 statements are ignored, **except** for accessors (getters and setters are considered even if they are 1-liners). So I think the exception text is trying to say that all methods are evaluated, except for the ones that are not getters/setters **AND** are less than 2 lines (IMO not super clear by reading it). As for Apex I was told the biztech team actually use the language, maybe you can ping them?

2023-05-29 09:38 UTC, frederic-tingaud-sonarsource commented
Adding @sebastian-hungerecker-sonarsource to review the Ruby code example: The idea is to change the example so that it explains how one can refactor to remove duplication. I am not even convinced that this code compiles, let alone looks like good Ruby.

2023-05-30 10:56 UTC, sebastian-hungerecker-sonarsource commented on rules/S4144/ruby/rule.adoc
A couple of comments on the code:

* I don't understand the variable name `ray`. Does French use the same word for "ray" and "radius" by any chance? Anyway, I think "radius" is what's meant here.
* Ruby uses snake_case for method and variable names, not camelCase.
* Ruby does not use the `get_foo` / `set_foo` naming convention for getters and setters. Instead getters should just use the name of the variable and setters should use assignment syntax. So for an instance variable `@foo`, the getter should be named `foo` and the setter `foo=`.
* Conventionally, the parameter name of a setter should be the name of the variable being set.

With that in mind, the code should be:

```ruby
class Circle
  def initialize(radius)
    @radius = radius
  end

  def width=(width)
    self.diameter = width
  end

  def height=(height)
    self.diameter = height
  end

  def diameter=(diameter)  # Implementation is shared
    @radius = diameter / 2
    update_shape()
  end

  def update_shape()
    # ...
  end
end
```

2023-05-30 13:35 UTC, frederic-tingaud-sonarsource commented
Adding @guillaume-dequenne-sonarsource to review the Scala code example: The idea is to change the example so that it explains how one can refactor to remove duplication. I am not even convinced that this code compiles, let alone looks like good Scala.

2023-05-31 08:54 UTC, quentin-jaquier-sonarsource approved these changes

2023-05-31 08:54 UTC, quentin-jaquier-sonarsource commented on rules/S4144/scala/rule.adoc
> +  def updateShape() {...}
_nitpick_
```suggestion
  def updateShape() = {...}
```

2023-05-31 08:54 UTC, quentin-jaquier-sonarsource commented on rules/S4144/scala/rule.adoc
> +  def updateShape() {...}
_nitpick_
```suggestion
  def updateShape() = {...}
```

2023-05-31 08:54 UTC, quentin-jaquier-sonarsource commented on rules/S4144/scala/rule.adoc
> +class Circle(radius: Int) {
Fields are immutable by default in scala.
```suggestion
class Circle(var radius: Int) {
```

2023-05-31 08:54 UTC, quentin-jaquier-sonarsource commented on rules/S4144/scala/rule.adoc
> +class Circle(radius: Int) {
```suggestion
class Circle(var radius: Int) {
```

2023-05-31 08:54 UTC, quentin-jaquier-sonarsource commented on rules/S4144/scala/rule.adoc
>    }
_Optional:_ the previous code works fine, but I would say it is common practise to remove the block and directly go for:
```suggestion
  def setWidth(size: Int) = setDiameter(size)

  def setHeight(size: Int) = setDiameter(size)
```
(You could even go for `def setWidth = setDiameter`, but I don't think I would recommend this code...)

2023-05-31 09:11 UTC, sebastian-hungerecker-sonarsource commented on rules/S4144/scala/rule.adoc
>    }
I'd go with assignment syntax over `setFoo` (same as in Ruby):

```scala
def width_=(width: Int) {
  diameter = width
}

def diameter_=(diameter: Int) {
  radius = diameter / 2
  updateShape()
}
```

Also I don't think it's idiomatic to use `=` when there is no return value.

2023-05-31 09:29 UTC, quentin-jaquier-sonarsource commented on rules/S4144/scala/rule.adoc
>    }
Fair point, I guess my Scala skills are a bit rusty!

2023-06-05 15:23 UTC, vilchik-elena approved these changes

2023-06-05 15:24 UTC, merged