Modify rule S3981: Adapt to LaYC
SonarSource/rspec pull request #1937
Opened 2023-05-23 16:57 UTC by frederic-tingaud-sonarsource

2023-05-24 09:46 UTC, vilchik-elena requested changes

2023-05-24 09:46 UTC, vilchik-elena commented on rules/S3981/csharp/rule.adoc
> +if(collection.Count >= 0){...} // Noncompliant always true
I suggest to add some punctuation after `// Noncompliant`, colon or comma

2023-05-24 09:46 UTC, vilchik-elena commented on rules/S3981/csharp/rule.adoc
> +Either remove the redundant code if the current behavior is correct or fix the code to properly check for emptiness if it was the intent.
I don't think that there is ever the case when the current behavior is correct. In 99.999999% cases the comparison operator was chosen incorrectly.

2023-05-24 09:46 UTC, vilchik-elena commented on rules/S3981/csharp/rule.adoc
How about something like this (splitting true and false cases)

```
The size of a collection and the length of an array are always greater than or equal to zero. So testing that size or length is greater than or equal to zero doesn't make sense, since the result is always ``++true++``.
[source,csharp]
----
if(collection.Count >= 0){...} // Noncompliant, always true
if(array.Length >= 0){...} // Noncompliant, always true
----
In this example, the condition is always true, and probably `>` should have been used. 

Similarly testing that it is less than zero will always return ``++false++``.
[source,csharp]
----
if(enumerable.Count() < 0){...} // Noncompliant, always false
----

Most often the intent is to check the (non)emptiness of the collection or array, and ` > 0` or ` == 0` operations should be used.

```

2023-05-24 09:46 UTC, vilchik-elena commented on rules/S3981/kotlin/rule.adoc
> +if (myList.size >= 0) { // Noncompliant always true
I think it was nice and concise to use `{...}`
Still I wonder if it's better to comment ellipsis so that the code is valid (in that case multiline block will do better)

2023-05-24 17:37 UTC, frederic-tingaud-sonarsource commented on rules/S3981/csharp/rule.adoc
> +if(collection.Count >= 0){...} // Noncompliant always true
Done

2023-05-24 17:41 UTC, frederic-tingaud-sonarsource commented on rules/S3981/csharp/rule.adoc
Changed

2023-05-24 17:41 UTC, frederic-tingaud-sonarsource commented on rules/S3981/kotlin/rule.adoc
> +if (myList.size >= 0) { // Noncompliant always true
Reverted

2023-05-26 05:45 UTC, vilchik-elena approved these changes
LGTM, but I suggested removing the repetition

2023-05-26 05:45 UTC, vilchik-elena commented on rules/S3981/csharp/rule.adoc
> +The size of a collection and the length of an array are always greater than or equal to zero. So testing that a size or length is greater than or equal to zero doesn't make sense, since the result is
```suggestion
The size of a collection and the length of an array are always greater than or equal to zero. So testing that doesn't make sense, since the result is always ``++true++``.
```

2023-05-29 16:37 UTC, merged