Modify rule S4507: Adding support for web.config error handling parameters (XML)(APPSEC-700)
SonarSource/rspec pull request #1938
Opened 2023-05-24 07:40 UTC by gaetan-ferry-sonarsource

2023-05-25 14:38 UTC, pierre-loup-tristant-sonarsource requested changes
I have one change request. Please look at the comment I made.

2023-05-26 07:29 UTC, gaetan-ferry-sonarsource commented on rules/S4507/xml/rule.adoc
> +Applications should be released without any development feature activated. In general, it is also recommended to avoid hardcoding a development feature option in an application's configuration. Such
That's fair point, even if this is what I thought when speaking about "environment-specific configurations". It is apparently not that clear so I'll rework the paragraph taking your suggestion into account.

2023-05-26 15:02 UTC, pierre-loup-tristant-sonarsource approved these changes
LGTM

2023-07-04 16:37 UTC, alban-auzeill approved these changes

2023-07-04 16:38 UTC, merged