Modify rule S3973: LaYC Indenting if
SonarSource/rspec pull request #1947
Opened 2023-05-25 17:54 UTC by frederic-tingaud-sonarsource

2023-05-25 19:49 UTC, vilchik-elena requested changes

2023-05-25 19:49 UTC, vilchik-elena commented on rules/S3973/csharp/rule.adoc
> +DoTheOtherThing(); // Did we really intend to always call this function?
Avoid using "we"
```suggestion
DoTheOtherThing(); // Was the intend to call this function unconditionally?
```

2023-05-25 19:49 UTC, vilchik-elena commented on rules/S3973/csharp/rule.adoc
> +DoTheOtherThing(); // We clearly intended to always call this function.
```suggestion
DoTheOtherThing(); // A clear intent to call this function unconditionally.
```

2023-05-25 19:49 UTC, vilchik-elena commented on rules/S3973/description.adoc
> +In the absence of both curly braces and indentation, the intent of the original programmer is unclear and perhaps not actually what is executed. Additionally, such code is highly likely to be confusi
```suggestion
In the absence of both curly braces and indentation, the intent is unclear and perhaps not what is executed. Additionally, such code is likely to be confusing to maintainers.
```

2023-05-25 19:49 UTC, vilchik-elena commented on rules/S3973/description.adoc
> +In the absence of both curly braces and indentation, the intent of the original programmer is unclear and perhaps not actually what is executed. Additionally, such code is highly likely to be confusi
I suggest adding one more paragraph "This rule raises an issue, if ..."

2023-05-25 19:49 UTC, vilchik-elena commented on rules/S3973/tsql/rule.adoc
> +In the absence of both ``++BEGIN...END++`` block and indentation the intent of the original programmer is entirely unclear and perhaps not actually what is executed. Additionally, such code is highly
Same changes as for top-level, plus could you remove `entirely` from `entirely unclear`? I believe such words not what we want, sounds like victim blaming :)

2023-05-25 19:49 UTC, vilchik-elena commented on rules/S3973/description.adoc
> -In the absence of enclosing curly braces, the line immediately after a conditional is the one that is conditionally executed. By both convention and good practice, such lines are indented. In the abs
imho this old description (which you mostly used as it is) is a bit Captain Obvious

imagine you did this mistake and someone tells you all that. For sure there is nothing new you gonna learn

how about smth like 
```
For various reasons, it might happen that the conditionally executed line is not denoted by indentation. In that case, the intent of the code is not clear and will probably confuse maintainers.

The scenarios leading to this problem could be mistakenly denoted code like here.
---
if (condition) // Noncompliant
dosmthifCondition()

dosomethingelse() 
---

Or mistakenly removed the conditionally executed statement.
---
if (condition) // Noncompliant
//  dosmthifCondition()
dosomethingelse() 
---
```

2023-05-29 17:07 UTC, frederic-tingaud-sonarsource commented on rules/S3973/csharp/rule.adoc
> +DoTheOtherThing(); // Did we really intend to always call this function?
Done

2023-05-29 17:07 UTC, frederic-tingaud-sonarsource commented on rules/S3973/csharp/rule.adoc
> +DoTheOtherThing(); // We clearly intended to always call this function.
Done

2023-05-29 17:07 UTC, frederic-tingaud-sonarsource commented on rules/S3973/description.adoc
> +In the absence of both curly braces and indentation, the intent of the original programmer is unclear and perhaps not actually what is executed. Additionally, such code is highly likely to be confusi
Done

2023-05-29 17:11 UTC, frederic-tingaud-sonarsource commented on rules/S3973/description.adoc
> +In the absence of both curly braces and indentation, the intent of the original programmer is unclear and perhaps not actually what is executed. Additionally, such code is highly likely to be confusi
Done

2023-05-29 17:11 UTC, frederic-tingaud-sonarsource commented on rules/S3973/tsql/rule.adoc
> +In the absence of both ``++BEGIN...END++`` block and indentation the intent of the original programmer is entirely unclear and perhaps not actually what is executed. Additionally, such code is highly
Agreed, fixed

2023-05-29 17:11 UTC, frederic-tingaud-sonarsource commented on rules/S3973/description.adoc
> -In the absence of enclosing curly braces, the line immediately after a conditional is the one that is conditionally executed. By both convention and good practice, such lines are indented. In the abs
Done

2023-06-05 08:27 UTC, vilchik-elena approved these changes

2023-06-05 08:31 UTC, merged