Modify rule S3433: Migrate to new educational format
SonarSource/rspec pull request #1955
Opened 2023-05-29 12:58 UTC by cristian-ambrosini-sonarsource

Removing `swift` rule since it's not implemented yet.
I'll leave a comment in the rule as soon as this PR is merged.

2023-05-31 09:51 UTC, sebastien-marichal requested changes

2023-05-31 09:51 UTC, sebastien-marichal commented on rules/S3433/csharp/rule.adoc
> +=== Exceptions
As per [documentation](https://github.com/SonarSource/rspec/blob/master/docs/description.adoc#2-education-format), the `Exceptions` should be under the `Why is this an issue?` section.

2023-05-31 09:51 UTC, sebastien-marichal commented on rules/S3433/csharp/rule.adoc
> +public void MyIgnoredTestMethod()
Maybe not really important: an `async Task` compliant example could be nice.

2023-05-31 09:51 UTC, sebastien-marichal commented on rules/S3433/csharp/metadata.json
> +  "quickfix": "targeted"
Following my comment on the `async Task` test method, not sure if the quick fix is feasible as there are at least two possibilities in this case. 
If we are not required to cover all cases with the quick fix, you can ignore and resolve this comment.

2023-05-31 13:32 UTC, cristian-ambrosini-sonarsource commented on rules/S3433/csharp/rule.adoc
> +=== Exceptions
Yes, and it should be under the proper section, right? :worried:
Maybe what's confusing you is that we don't have a "How to fix it" section in this rule so the compliant/noncompliant examples are inside the "Why" section. Either that or I'm missing something, let me know

2023-05-31 13:51 UTC, cristian-ambrosini-sonarsource commented on rules/S3433/csharp/rule.adoc
> +public void MyIgnoredTestMethod()
Yeah that would be nice, my only concern is that having a 4/3 match on compliant/noncompliant examples can be confusing for users. WDYT?

2023-05-31 13:53 UTC, cristian-ambrosini-sonarsource commented on rules/S3433/csharp/metadata.json
> +  "quickfix": "targeted"
That's a good point, I'm assuming that `targeted` can result in either `partial` or `covered` once the quick fix is implemented so we should be fine.

2023-05-31 13:59 UTC, sebastien-marichal commented on rules/S3433/csharp/rule.adoc
> +public void MyIgnoredTestMethod()
I was thinking of replacing this compliant solution with the `async Task` one, keeping the 3/3 match.

2023-06-01 09:59 UTC, sebastien-marichal approved these changes
LGTM!

2023-06-01 10:17 UTC, merged