Modify rule S2699: Migrate to new educational format
SonarSource/rspec pull request #1956
Opened 2023-05-29 14:15 UTC by cristian-ambrosini-sonarsource

2023-05-30 16:00 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +public void TestGetFoo()
I agree on changing the name of the test method to match the name of the tested method. 
However, why removing the `_WhenSomething_ExpectsSomething`?
I would keep it and make it into a real scenario. E.g. (compliant solution):

```cs
[TestMethod]
public void ByScalar_WhenMatrixInvertibleAndScalarNonZero_ExpectsInvertibleResult()
{
    var matrix = new Matrix(1, 2, 1, 3);
    MatrixAssert.IsInvertible(matrix.ByScalar(3));
}
```

2023-05-31 08:32 UTC, cristian-ambrosini-sonarsource commented on rules/S2699/csharp/rule.adoc
> +The rule is targetting test methods that lack an assertion and consist solely of an action and optionally a setup. Such tests are designed to verify that the process runs without throwing an exceptio
I would not consider it an exception, it's more a FP. I'll try to improve a bit the first part, let me know what you think 👍

2023-05-31 13:34 UTC, antonioaversa requested changes
More changes related to code examples and frameworks

2023-05-31 13:34 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +    public static void Caclulator(int value) =>
`Caclulator` -> `Calculator`

Besides the name, the example doesn't compile (`StringCalculator` is not defined), and even if it was, the assertion method would not compile because it returns `void`, whereas the body is a boolean expression.

Moreover, `Calculator` isn't a typical name for an assertion method, which typically is something like `AssertX` or `BeX` as in `Should.BeX` etc. It also doesn't return a `bool`, but it raises exception when it fails, so that the test runner can report the test failure.

For this example to have value and not confuse the user, I think it should better capture a real scenario where users would use a custom assertion method, which is when `Assert.X` or `CollectionAssert.X` etc. are not enough.

2023-05-31 13:34 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +== Hot to fix it in MSTest
I think [this list](https://github.com/SonarSource/rspec/blob/master/docs/header_names/allowed_framework_names.adoc) should also be extended, with the list of testing frameworks for .NET.

2023-05-31 13:34 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +    Assert.AreEqual(0, actual);
Too many empty lines:

```cs
var stringCalculator = new StringCalculator();
var actual = stringCalculator.Add("0");
Assert.AreEqual(0, actual);
```

2023-05-31 13:34 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +public void Add_SingleNumber_ReturnsSameNumber()
`Add_Zero_ReturnsSameNumber`?

If you add a single (digit) number, you don't (always) get the same number.

2023-05-31 13:34 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +	Assert.That(0, Is.EqualTo(actual));
Indenting and empty lines

2023-05-31 13:34 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +    public void Add_SingleNumber_ReturnsSameNumber() => Validator.Caclulator(0); // Compliant
As in comment below, should the test be called `Add_Zero_ReturnsSameNumber`?

2023-05-31 13:34 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +[TestMethod]
The NUnit attribute is `Test`, defined in a `TestFixture`.
`TestMethod` is MSTest specific.
Check [here ](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-nunit)for some examples.

2023-05-31 13:34 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +[TestMethod]
xUnit uses `Fact` and `Theory`. `TestMethod` is MSTest specific.

Check [here](https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test) for examples.

2023-05-31 13:34 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +Such tests are only verifying that no exception is thrown, without providing any guarantees regarding the behavior of the code under test.
It would be better in my opinion, to have a single noncompliant example, shown after this first paragraph.
That way, users would understand right away what we are talking about.

It would also avoid having non-compliant blocks for each testing framework, which look very similar to each other. It also renders less useful the fourth-level sections under code examples.

2023-05-31 13:34 UTC, antonioaversa requested changes
More changes related to code examples and frameworks

2023-05-31 14:13 UTC, cristian-ambrosini-sonarsource commented on rules/S2699/csharp/rule.adoc
> +== Hot to fix it in MSTest
Good catch! I wonder why there are no tests that verify this (and thus what's the purpose of the list in the first place)

2023-05-31 14:16 UTC, cristian-ambrosini-sonarsource commented on rules/S2699/csharp/rule.adoc
> +[TestMethod]
Yeah that was my fault. I just changed the assertion invocation based on the framework and not the attributes, thanks for catching it!

2023-06-01 10:03 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +The rule is targetting test methods that lack an assertion and consist solely of an action and optionally a setup. Such tests are designed to verify that the process runs without throwing an exceptio
Good!

2023-06-06 08:04 UTC, cristian-ambrosini-sonarsource commented on rules/S2699/csharp/rule.adoc
> +Such tests are only verifying that no exception is thrown, without providing any guarantees regarding the behavior of the code under test.
You should see the diff visually, isn't it mandatory to have noncompliant/compliant pair inside a `Code Examples` subsection?

2023-06-06 09:26 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +== Hot to fix it in MSTest
I don't know exactly but I suspect it may just be for verification by the rspec tooling on CI, as I would infer from [here](https://github.com/SonarSource/rspec/blob/65008d6b56be390dd88703092d02473dda30ebdb/rspec-tools/tests/validation/test_description_validation.py#L93) and [here](https://github.com/SonarSource/rspec/blob/65008d6b56be390dd88703092d02473dda30ebdb/docs/description.adoc#L206).
Nothing user-facing on SQ or SC I think.

@arseniy-sonar : am I right?

2023-06-06 09:57 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +Such tests are only verifying that no exception is thrown, without providing any guarantees regarding the behavior of the code under test.
After discussion, adding an example in the why section after the first paragraph is enough for the user to grasp what we are talking about. No changes to How to fix sections are required.=

2023-06-06 10:02 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +	{
`{` should be vertically aligned to `public static void IsSameNumber(int value)`.

2023-06-06 10:03 UTC, necto commented on rules/S2699/csharp/rule.adoc
> +== Hot to fix it in MSTest
Yes. This list is maintained to make sure we use consistent spelling for the frameworks. If the framework used in the title of this section is missing from the list, it should fail the rule-description validation in the CI check. Let me know if that does not happen

2023-06-06 10:17 UTC, antonioaversa commented on rules/S2699/csharp/rule.adoc
> +[TestClass]
Alternative:
```cs
    [TestClass]
    public class CustomTestExample
    {
        [TestMethod]
        public void Add_SingleNumber_ReturnsSameNumber()
        {
            var stringCalculator = new StringCalculator();
            var actual = stringCalculator.Add("0");
            Validator.AssertCustomEquality(0, actual); // Compliant
        }
    }

    public static class Validator
    {
        [AssertionMethod]
        public static void AssertCustomEquality(int expected, int actual)
        {
            // ...
        }
    }
```

2023-06-06 10:17 UTC, antonioaversa approved these changes
LGTM
Open discussions to be addressed first.

2023-06-06 12:01 UTC, cristian-ambrosini-sonarsource commented on rules/S2699/csharp/rule.adoc
> +== Hot to fix it in MSTest
If I remember correctly the CI was green even tho those 3 test frameworks were missing from the list. I can do a quick test later to verify that

2023-06-06 12:22 UTC, merged