Modify rule S2190: LaYC format
SonarSource/rspec pull request #1962
Opened 2023-05-30 13:28 UTC by gregory-paidis-sonarsource

Also remove unused languages.

2023-05-31 09:19 UTC, vilchik-elena requested changes

2023-05-31 09:19 UTC, vilchik-elena commented on rules/S2190/csharp/rule.adoc
> +1. a method invoking itself
If you want to be so well-structured and split the possible cases in the list I would recommend putting a code example after each. That way reader will quickly grasp what you mean.

2023-05-31 09:19 UTC, vilchik-elena commented on rules/S2190/csharp/rule.adoc
> +The program will either be looping indefinitely or the stack will reach its limit and the program will crash due to a stack overflow error.
again, if the rule about recursion program will not be looping indefinitely.

2023-05-31 09:19 UTC, vilchik-elena commented on rules/S2190/csharp/rule.adoc
>  == Why is this an issue?
I believe this rule deserves a proper explanation of what is recursion and its base case
Mention kinds of recursion (direct and indirect), why recursion is good, and why dangerous.

2023-05-31 09:19 UTC, vilchik-elena commented on rules/S2190/csharp/rule.adoc
> +Non-termination occurs when control enters a loop that lacks an exit condition.
I am afraid the word "loop" might be confusing in the context of recursion

2023-05-31 09:19 UTC, vilchik-elena commented on rules/S2190/csharp/rule.adoc
> +1. self-invoking should happen under a condition that eventually evaluates to `false`
You should not assume that reader remembers the order of scenarios from another tab. This tab should be understandable on its own

2023-05-31 09:19 UTC, vilchik-elena commented on rules/S2190/csharp/rule.adoc
> +[source,csharp,diff-id=1,diff-type=compliant]
Similar here add a paragraph about the fix

2023-05-31 09:19 UTC, vilchik-elena commented on rules/S2190/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/iteration-statements#the-for-statement["for" statement]
I would add `the` like in the documentation 
`The "for" statement`

2023-05-31 10:02 UTC, gregory-paidis-sonarsource commented on rules/S2190/csharp/rule.adoc
> +3. `while` and `for` loops
So, the rule applies to both, because it checks endless execution via the CFG.
Do you think we should rename it to something like `Loops and recursions should not be infinite`?

2023-05-31 10:03 UTC, gregory-paidis-sonarsource commented on rules/S2190/csharp/rule.adoc
> +The program will either be looping indefinitely or the stack will reach its limit and the program will crash due to a stack overflow error.
Same as the title, if applies to loops as well.

2023-06-08 15:23 UTC, gregory-paidis-sonarsource commented on rules/S2190/csharp/rule.adoc
> +Non-termination occurs when control enters a loop that lacks an exit condition.
I rewrote it in a way that it starts talking about looping and then describes recursion as well, so it should be a bit more clear

2023-06-08 15:24 UTC, gregory-paidis-sonarsource commented on rules/S2190/csharp/rule.adoc
> +Non-termination occurs when control enters a loop that lacks an exit condition.
Removed non-termination from the entire text

2023-06-12 12:05 UTC, vilchik-elena commented on rules/S2190/csharp/rule.adoc
> +In this example, `Pow` will call `Pow` only if the exponent is greater than one, while passing `exponent-1` to the method, a smaller value than the one it received, `exponent`. This means that the re
I would drop this paragraph. You try to literally describe what is happening in the code, and you are not doing it very precise. E.g. `recursion will run `exponent-1` times`: not recursion, but method, and which value of exponent you imply in "`exponent-1` times"

The first sentence is too complicated

2023-06-12 12:05 UTC, vilchik-elena commented on rules/S2190/csharp/rule.adoc
> +In this example, `Foo` is invoking `Bar` conditionally, only if `n` is a positive number. Also, both `Foo` and `Bar` are decrementing the value of `n`, which means it will always decrease, until it r
This explanation is more confusing than helping. Do we need the both methods to decrement the value to avoid the loop?

2023-06-12 12:13 UTC, vilchik-elena commented on rules/S2190/csharp/rule.adoc
> +Here are some ways to achieve that:
I am not sure it's appropriate to say so, when each way corresponds to a different original problem

2023-06-13 12:39 UTC, gregory-paidis-sonarsource commented on rules/S2190/csharp/rule.adoc
> +Recursion can have a lot of benefits:
rewrote it as `some` instead of `a lot` :)

2023-06-13 12:39 UTC, gregory-paidis-sonarsource commented on rules/S2190/csharp/rule.adoc
> +In this example, `Pow` will call `Pow` only if the exponent is greater than one, while passing `exponent-1` to the method, a smaller value than the one it received, `exponent`. This means that the re
Dropped

2023-06-13 12:42 UTC, gregory-paidis-sonarsource commented on rules/S2190/csharp/rule.adoc
> +In this example, `Foo` is invoking `Bar` conditionally, only if `n` is a positive number. Also, both `Foo` and `Bar` are decrementing the value of `n`, which means it will always decrease, until it r
I refactored the examples to only have `n-1` inside `Foo`, and removed this sentence, as I do not believe it adds much value

2023-06-16 09:24 UTC, vilchik-elena approved these changes

2023-06-16 10:23 UTC, merged