Modify rule S3464: LaYC format
SonarSource/rspec pull request #1966
Opened 2023-05-30 16:13 UTC by antonioaversa

RSpec: https://sonarsource.github.io/rspec/#/rspec/S3464

2023-05-31 14:48 UTC, gregory-paidis-sonarsource requested changes
Looks very readable, left a couple of suggestions. Consider most stuff for VB as well, since it's very similar.

2023-05-31 14:48 UTC, gregory-paidis-sonarsource commented on rules/S3464/csharp/rule.adoc
> +static int NthFibonacciNumber(int n)
I think you can remove `static` to simplify the examples.
Applies to all code snippets.

2023-05-31 14:48 UTC, gregory-paidis-sonarsource commented on rules/S3464/csharp/rule.adoc
> +        return 1; // Base case => stop recurring
(Nitpick, optional)
The arrow seems like a lambda to me, maybe use a colon:

`Base case: ...`

Also, `recurring` feels slightly unnatural, maybe something like:

`(stop|exit) the recursive calls` or `(stop|exit) the recursion`

2023-05-31 14:48 UTC, gregory-paidis-sonarsource commented on rules/S3464/csharp/rule.adoc
> +class Box<T> : IComparable<Box<T>>
Do you need the CRTP _target_ to be generic? Is it semantically different than this, as far as the pattern is concerned:

```csharp
class Box: IComparable<Box> { }
```

I feel like if you try to convey CRTP, having one less generic makes it a bit more readable/understandable.

2023-05-31 14:48 UTC, gregory-paidis-sonarsource commented on rules/S3464/csharp/rule.adoc
> +With types, some invalid recursive definitions are catched by the compiler:
"catched" -> "caught"

2023-05-31 14:48 UTC, gregory-paidis-sonarsource commented on rules/S3464/csharp/rule.adoc
> +In more complex scenarios, however, the code will compile but execution will result into a `TypeLoadException` if you try to instantiate the class.
Either here or in "Resources" tab, you can add this:

- [TypeLoadException](https://learn.microsoft.com/en-us/dotnet/api/system.typeloadexception?view=net-7.0)

Some more suggestions:
- [Recursion - wiki](https://en.wikipedia.org/wiki/Recursion_(computer_science))
- [Clippert's "Curiouser and curiouser"](https://ericlippert.com/2011/02/02/curiouser-and-curiouser/)
- [Cleary's CRGP](https://blog.stephencleary.com/2022/09/modern-csharp-techniques-1-curiously-recurring-generic-pattern.html)

You can also add [wiki's CRTP](https://en.wikipedia.org/wiki/Curiously_recurring_template_pattern), but it's basically all about C++

2023-05-31 16:26 UTC, antonioaversa commented on rules/S3464/csharp/rule.adoc
> +class Box<T> : IComparable<Box<T>>
Yes, I don't think it is actually needed and it doesn't add value. Removed.

2023-05-31 16:27 UTC, antonioaversa commented on rules/S3464/csharp/rule.adoc
> +With types, some invalid recursive definitions are catched by the compiler:
Nice catch :-)

2023-06-01 08:36 UTC, gregory-paidis-sonarsource commented on rules/S3464/csharp/rule.adoc
> +In more complex scenarios, however, the code will compile but execution will result into a `TypeLoadException` if you try to instantiate the class.
Consider adding the link for `TypeLoadException` here as well, as we discussed.

2023-06-01 08:36 UTC, gregory-paidis-sonarsource requested changes
Some more minor changes suggested.

2023-06-01 11:26 UTC, antonioaversa commented on rules/S3464/csharp/rule.adoc
> +With types, some invalid recursive definitions are catched by the compiler:
whoops, fixed!

2023-06-01 15:49 UTC, gregory-paidis-sonarsource approved these changes
LGTM!

2023-06-01 15:49 UTC, merged