Modify rule S3443: LaYC format
SonarSource/rspec pull request #1971
Opened 2023-05-31 09:38 UTC by sebastien-marichal

2023-05-31 13:26 UTC, cristian-ambrosini-sonarsource requested changes
Looks good! I suggested a few changes

2023-05-31 13:26 UTC, cristian-ambrosini-sonarsource commented on rules/S3443/csharp/rule.adoc
> +Calling `GetType` on `System.Type` is considered compliant to get an instance of `System.RuntimeType`, like in the following example:
Educational: so if I understood correctly:
```cs
string str = string.Empty;

Type strType = str.GetType(); // Compliant (System.String)
Type strTypeType = strType.GetType(); // Noncompliant (System.RuntimeType)
typeof(Type).GetType(); // Compliant (System.RuntimeType)
```

So the exception of this rule is specifically the line `typeof(Type).GetType();` to allow one way to retrieve System.RuntimeType without raising the issue. Am I right?

2023-05-31 13:26 UTC, cristian-ambrosini-sonarsource commented on rules/S3443/csharp/rule.adoc
>  var runtimeType = intType.GetType(); // Noncompliant, always typeof(System.RuntimeType)
This first example is not fixed in the compliant example, right?
WDYT about a test like the following?

```cs
void ExamineSystemType(string str, Type type) 
{
    type.GetType(); // Noncompliant
    
    if (type.IsInstanceOfType(typeof(string))) // Noncompliant
    { /* ... */ }
}
```
and then the compliant version:
```cs
void ExamineSystemType(string str, Type type) 
{
    str.GetType(); // Noncompliant
    
    if (str.IsInstanceOfType(typeof(string))) // Noncompliant
    { /* ... */ }
}
```

2023-05-31 13:45 UTC, sebastien-marichal commented on rules/S3443/csharp/rule.adoc
> +Calling `GetType` on a variable of type `Type` will always return the `Type` representation of `System.Type` (aka. `typeof(System.Type)`). This also applies to passing a `Type` argument to `IsInstanc
I wanted to have a clearer sentence, I think the old version is not easy to understand for junior developers. And I agree, `type` is used too many times.

2023-06-01 07:22 UTC, cristian-ambrosini-sonarsource approved these changes
LGTM!

2023-06-01 07:23 UTC, merged