Modify rule S6232: CPP-3254 Well defined alternatives to union type-punning
SonarSource/rspec pull request #1976
Opened 2023-05-31 13:19 UTC by LoghinVladDev

Also using LaYC format for specialized examples

2023-06-05 04:33 UTC, necto requested changes

2023-06-05 04:33 UTC, necto commented on rules/S6232/cfamily/rule.adoc
> +* S6181 - replacing `std::memcpy` with `std::bit_cast++`.
Looks like you've unintentionally left the extra `++` remain
```suggestion
* S6181 - replacing `std::memcpy` with `std::bit_cast`.
```

2023-06-05 04:33 UTC, necto commented on rules/S6232/cfamily/metadata.json
> +  "title": "Well defined type-punning should be used instead of union type-punning",
"type-punning" is quite a heavy word to repeat in a single sentence.
What do you think of the following options?
```suggestion
  "title": "Well-defined alternative should be used instead of union type-punning",
```
```suggestion
  "title": "Well-defined type-punning method should be used instead of a union-based one",
```

2023-06-05 04:33 UTC, necto commented on rules/S6232/cfamily/rule.adoc
> +Despite being allowed in C, this operation has undefined behavior according to {cpp} standard and should be replaced by `std::memcpy` (or `std::bit_cast` in {cpp}20).
Perhaps it is worth mentioning that `memcpy` should not have any performance impact, and will likely be removed during compilation (to be verified)

2023-06-05 04:33 UTC, necto commented on rules/S6232/cfamily/rule.adoc
> +Solution until {cpp}20:
```suggestion
Solution before {cpp}20:
```

2023-06-05 04:33 UTC, necto commented on rules/S6232/cfamily/rule.adoc
> +Replace any "union type-punning" solution with a standard compliant solution.
```suggestion
Replace any "union type-punning" solution with a standard-compliant solution.
```

2023-06-05 04:33 UTC, necto commented on rules/S6232/cfamily/rule.adoc
> +The operation is performed by saving the value in the member with the source type and then reading the value of the target type.
```suggestion
The operation is performed by saving the value in the member of the source type and then reading the value from the member of the target type.
```

2023-06-05 04:36 UTC, necto commented
Also, I would seize the opportunity and marked the "quickfix" as "targeted" because it looks feasible for some cases (but I'm not suggesting implementing it in the current sprint!)

2023-06-05 04:50 UTC, necto commented on rules/S6232/cfamily/rule.adoc
>  == Resources
Perhaps, include the video Balazs mentioned in the ticket comment
Do you know other good resources on the subject?

2023-06-05 04:51 UTC, necto commented
It might be also worth adding the "What is the potential impact?" section citing one or two horrors of the non-conformance to the standard

2023-06-05 07:05 UTC, LoghinVladDev commented on rules/S6232/cfamily/rule.adoc
> +Despite being allowed in C, this operation has undefined behavior according to {cpp} standard and should be replaced by `std::memcpy` (or `std::bit_cast` in {cpp}20).
Clang/Apple Clang/GCC/MSVC optimizes it to no performance impact. It's good to mention that most modern compilers optimize it

2023-06-05 08:14 UTC, LoghinVladDev commented on rules/S6232/cfamily/rule.adoc
> +  std::uint32_t i;
Given that in 'what is the potential impact' I want to specify size difference between architectures, would it be worth to change this to also include a size assert before cpp 20, since bit cast does this implicitly

```diff
+ static_assert(sizeof(i) == sizeof(number), "Safe type-punning not possible on this architecture");
std::memcpy(&i, &number, sizeof(float));
```

2023-06-06 10:16 UTC, necto approved these changes
I couple of nits, and looking great otherwise!

Note that you use different spellings: "union-type punning" and "union type-punning". I propose (in the change suggestions below) to stick to the term "union-based type punning"

2023-06-06 10:16 UTC, necto commented on rules/S6232/cfamily/rule.adoc
> +Since union type-punning relies on reading the "inactive" member, code using it is undefined behavior.
```suggestion
Since union type-punning relies on reading the "inactive" member, code using it exercises undefined behavior.
```
Grammatically, "code" cannot be "behavior"

2023-06-06 10:16 UTC, necto commented on rules/S6232/cfamily/rule.adoc
> +Replace any "union type-punning" solution with a standard-compliant solution.
```suggestion
Replace any "union-based type punning" solution with a standard-compliant solution.
```

2023-06-06 18:28 UTC, merged