Modify rule S2368: LaYC format
SonarSource/rspec pull request #1981
Opened 2023-05-31 14:26 UTC by sebastien-marichal

2023-05-31 14:49 UTC, antonioaversa requested changes
A bit more education on what multidimensional and jagged arrays are, and some very minor cosmetic suggestions.

2023-06-01 11:59 UTC, sebastien-marichal commented on rules/S2368/why-dotnet.adoc
> +Using multidimensional and jagged arrays as function parameters in C# can be challenging for developers. When these methods are exposed to external users, it requires advanced knowledge of the langua
Having a paragraph about what is multi-dimensional and jagged array seems too much to be in the `why` in my opinion. For me, it should be added as documentation or article resources.

2023-06-01 15:49 UTC, sebastien-marichal commented on rules/S2368/why-dotnet.adoc
> +Using multidimensional and jagged arrays as function parameters in C# can be challenging for developers. When these methods are exposed to external users, it requires advanced knowledge of the langua
I improve the `why` section to include the code example. Didn't want to add a too complex example since we could lose junior devs. Hopefully, the one I added is good enough.
Happy to have your feedback on those.

2023-06-02 07:09 UTC, antonioaversa commented on rules/S2368/why-dotnet.adoc
> +Using multidimensional and jagged arrays as function parameters in C# can be challenging for developers. When these methods are exposed to external users, it requires advanced knowledge of the langua
I think it's good!

2023-06-02 07:35 UTC, antonioaversa requested changes
The why explanation is good! Some small remarks related to method visibility scope, orthography and cosmetic.

2023-06-02 07:35 UTC, antonioaversa commented on rules/S2368/csharp/exceptionCode.adoc
> +public class Program
Is the `public class Program` class necessary? 
The why section of the rule mentions "they are not publicly exposed".
If the rule also checks for type visibility, in addition to method visibility (effective visibility), then it makes sense to keep the class and clearly show its visibility, since it would have an effect on whether the rule would be reported or not. And maybe make a bit clearer what `publicly visible` means. 
If the rule only checks for method visibility, then I would remove the class and only show the method, with its visibility.

2023-06-02 07:35 UTC, antonioaversa commented on rules/S2368/csharp/rule.adoc
> +:unintuitiveCode: csharp/unintuitiveCode.adoc
I like the breakdown!

2023-06-02 07:35 UTC, antonioaversa commented on rules/S2368/vbnet/exceptionCode.adoc
> +Public Class Program
Same remark as in the C# example

2023-06-02 07:35 UTC, antonioaversa commented on rules/S2368/vbnet/exceptionCode.adoc
> +[source,vbnet,diff-id=1,diff-type=compliant]
Is this actually compliant with the same diff id as the intuitive and unintuitive examples?
You seem to have two compliant for one non-compliant: do you know what happens in the UI?

2023-06-02 07:35 UTC, antonioaversa commented on rules/S2368/vbnet/intuitiveCode.adoc
> +    Public Sub WriteMatrix(matrix As Matrix2x2) ' Compliant
In the "exception" example, `ByVal` was used, but here is not. 
I would align the two uses, and either make `ByVal` implicit in both or explicit in both.

My personal preference is to make implicit, because `ByVal` is the default anyway and doesn't add any valuable information in this context: the rule would trigger all the same if the parameter was `ByRef`. So I would remove it, so that the user would not wonder why it is there in the first place.

2023-06-02 07:35 UTC, antonioaversa commented on rules/S2368/why-dotnet.adoc
> +Using https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/multidimensional-arrays[multidimentsional] and https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/arrays/
multidimentsional -> multidimensional

I would also split this paragraph into three: one per period.

2023-06-02 07:36 UTC, antonioaversa commented
@sebastien-marichal The `validate_asciidoc` check is failing.

2023-06-02 07:42 UTC, sebastien-marichal commented on rules/S2368/csharp/rule.adoc
> +:unintuitiveCode: csharp/unintuitiveCode.adoc
Unfortunately, that's the reason why the `validate_asciidoc` check is falling 😞

2023-06-02 07:49 UTC, sebastien-marichal commented on rules/S2368/csharp/exceptionCode.adoc
> +public class Program
Nice catch, I will add a second example with a `private` or `internal` visibility for the class. Will check before if it is implemented that way.

2023-06-02 08:05 UTC, sebastien-marichal commented on rules/S2368/vbnet/exceptionCode.adoc
> +[source,vbnet,diff-id=1,diff-type=compliant]
Copy-paste mistake

2023-06-02 14:19 UTC, sebastien-marichal commented on rules/S2368/csharp/rule.adoc
> +:unintuitiveCode: csharp/unintuitiveCode.adoc
This will be fixed soon https://github.com/SonarSource/rspec/pull/2028! 🎉

2023-06-05 07:34 UTC, antonioaversa commented
@sebastien-marichal : the PR currently shows 38 commits - I think you may want to rebase on the current HEAD of `dotnet-layc`.

2023-06-05 07:58 UTC, frederic-tingaud-sonarsource commented
My bad. I rebased the branch to make sure the fix that landed on master was fixing this branch, I didn't realize it wasn't based on master.

2023-06-05 09:02 UTC, merged