Modify rule S3889: LAYC format
SonarSource/rspec pull request #1997
Opened 2023-06-01 11:58 UTC by gregory-paidis-sonarsource

2023-06-01 14:41 UTC, antonioaversa commented on rules/S3889/csharp/rule.adoc
>  include::../description.adoc[]
I think `description.adoc` should be renamed to `why-dotnet.adoc`, or `why.adoc` (as the rule only applies to csharp and vbnet, so there is no name conflict with other languages). I would call it `why-dotnet.adoc` though, for consistency.

2023-06-01 14:47 UTC, antonioaversa commented on rules/S3889/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/lock[lock statement]
Examples of resources shown [here](https://github.com/SonarSource/rspec/tree/a51217c6d91abfa5e1d77d0ae0843e3903adf2d0/rules/S5131/common/resources) capitalize the first letter, whereas the [styling guide for adoc](https://github.com/SonarSource/rspec/blob/master/docs/styling_guide.adoc#lists) prescribes not avoid capitalizing on list items.
In this case, I think that we don't have an introducing sentence terminated by `:`, and that the first letter for each element of the list should be capitalized, as in the examples.

2023-06-01 14:48 UTC, antonioaversa commented on rules/S3889/description.adoc
> +There are other synchronization mechanisms that are safer and should be used, such as:
suggestion: should be used instead

2023-06-01 14:51 UTC, antonioaversa commented on rules/S3889/metadata.json
> +  "title": "\"Thread.Resume\" and \"Thread.Suspend\" should be used",
"title": "\"Thread.Resume\" and \"Thread.Suspend\" should **not** be used",

2023-06-01 14:51 UTC, antonioaversa requested changes
Title to be fixed, the rest is minor

2023-06-02 09:19 UTC, gregory-paidis-sonarsource commented on rules/S3889/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/lock[lock statement]
I agree in general, but `lock` is written in lowercase, both in the documentation and while writing code. 
Based on that, do you still think it should be capitalized?

2023-06-02 09:20 UTC, gregory-paidis-sonarsource commented on rules/S3889/metadata.json
> +  "title": "\"Thread.Resume\" and \"Thread.Suspend\" should be used",
🤦‍♂️

2023-06-02 09:35 UTC, antonioaversa commented on rules/S3889/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/lock[lock statement]
No OK, makes sense.

2023-06-02 09:37 UTC, antonioaversa approved these changes
LGTM!

2023-06-02 09:37 UTC, merged