Modify rule S6534: Adapt to LaYC
SonarSource/rspec pull request #2003
Opened 2023-06-01 12:51 UTC by victor-diez-sonarsource

2023-06-01 15:21 UTC, yassin-kammoun-sonarsource commented on rules/S6534/javascript/rule.adoc
> +* 52 bits for the significand
Just asking but, is `sigificand` a popular term? I am more familiar with the term `mantissa`.

2023-06-01 15:21 UTC, yassin-kammoun-sonarsource commented on rules/S6534/javascript/rule.adoc
> +* 11 bits for the exponent (2^n^). Range is from -1022 to 1023
Is the extra hat in `2^n^` intentional?

2023-06-01 15:21 UTC, yassin-kammoun-sonarsource commented on rules/S6534/javascript/rule.adoc
> +* 11 bits for the exponent (2^n^). Range is from -1022 to 1023
There are more hats like this below.

2023-06-01 15:21 UTC, yassin-kammoun-sonarsource commented on rules/S6534/javascript/rule.adoc
> +Javascript provides the helper function `Number.isSafeInteger()` to test if a number is between the safe limits.
```suggestion
JavaScript provides the helper function `Number.isSafeInteger()` to test if a number is between the safe limits.
```

2023-06-01 15:21 UTC, yassin-kammoun-sonarsource commented on rules/S6534/javascript/rule.adoc
> +When you need to store a large number, use `BigInt`. `BigInt` and `Number` can be compared between them as usual, but pay attention that operations(`+` `pass:[*]` `-` `%` `pass:[**]`) between both ty
```suggestion
When you need to store a large number, use `BigInt`. `BigInt` and `Number` can be compared between them as usual, but pay attention that operations (`+` `pass:[*]` `-` `%` `pass:[**]`) between both types raise an error unless they are coerced to the same type, so you will have to adapt your code accordingly.
```

2023-06-05 09:18 UTC, victor-diez-sonarsource commented on rules/S6534/javascript/rule.adoc
> +* 52 bits for the significand
not sure which one is better, 

https://en.wikipedia.org/wiki/Significand

they seem to be synonyms

2023-06-05 09:19 UTC, victor-diez-sonarsource commented on rules/S6534/javascript/rule.adoc
> +* 11 bits for the exponent (2^n^). Range is from -1022 to 1023
as mentioned: https://docs.asciidoctor.org/asciidoc/latest/text/subscript-and-superscript/

2023-06-05 09:49 UTC, vilchik-elena requested changes

2023-06-05 09:49 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +* 11 bits for the exponent (2^n^). Range is from -1022 to 1023
`-1022 <= n <= 1023`

2023-06-05 09:49 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +Numbers in JavaScript are stored as double-precision 64-bit binary format IEEE 754. Like any other number encoding occupying a finite number of bits, it is unable to represent all numbers, as trying
Drop the last sentance

2023-06-05 09:49 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +* 52 bits for the significand
significand (or mantissa)

2023-06-05 09:49 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +`Number = (-1)^sign^ * (1 + significand) * 2 ^exponent^`
move to the previous line with text  and drop `Number =`

2023-06-05 09:49 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +Given this structure, there are some limits in both *magnitude* and *precision*.
drop `some`

2023-06-05 09:49 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> -== How to fix it
Keep this section

2023-06-07 14:46 UTC, vilchik-elena requested changes

2023-06-07 14:46 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +// When images can be added, uncomment the block
fyi this exact image will not be used, we will need to create our own copy of it

2023-06-07 14:46 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +JavaScript provides the helper function `Number.isSafeInteger()` to test if a number is between the safe limits.
does this function work both in precision and magnitute? If yes, could you mention that here?

2023-06-07 14:46 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +When you need to store a large number, use `BigInt`. `BigInt` and `Number` can be compared between them as usual, but pay attention that operations (`+` `pass:[*]` `-` `%` `pass:[**]`) between both t
```suggestion
When you need to store a large number, use `BigInt` values. `BigInt` and `number` can be compared between them as usual (`<`, `<=`, `>`, `>=`, `==` etc). But arithmetic operations (`+` `pass:[*]` `-` `%` `pass:[**]`) between both types raise a `TypeError`. To avoid that, values should be coerced to the same type.
```

2023-06-07 14:46 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +When you need to store a large number, use `BigInt`. `BigInt` and `Number` can be compared between them as usual, but pay attention that operations (`+` `pass:[*]` `-` `%` `pass:[**]`) between both t
How to create `BigInt`? 
How to coerce?

2023-06-07 14:46 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +This code snippet shows some cases where the value stored will be rounded.
I would drop this phrase, not sure what it brings

2023-06-07 14:46 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> -=== Code examples
This section should use all these titles

2023-06-07 14:46 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
>  == How to fix it
Here I would first speak about bigint and show noncompliant and compliant examples
Then speak about precisison and show noncompliant and compliant examples for it.

2023-06-07 14:46 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +import {Decimal} from 'decimal.js';
```suggestion
import { Decimal } from 'decimal.js';
```

2023-06-07 14:46 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#number_encoding[MDN Number encoding]
I suggest to put MDN at the end, so that it's clear it has nothing to do with the language feature.
```suggestion
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#number_encoding[Number encoding (MDN)]
```

WDYT?

2023-06-09 08:27 UTC, vilchik-elena requested changes

2023-06-09 08:27 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
>  * https://en.wikipedia.org/wiki/Double-precision_floating-point_format[Wikipedia Double-precision floating-point format]
```suggestion
* https://en.wikipedia.org/wiki/Double-precision_floating-point_format[Wikipedia - Double-precision floating-point format]
```

2023-06-09 08:27 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +Numbers in JavaScript are stored in double-precision 64-bit binary format IEEE 754. Like any other number encoding occupying a finite number of bits, it is unable to represent all numbers.
Can we add link to the format?

2023-06-09 08:27 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +Number.MAX_SAFE_INTEGER + 1 === Number.MAX_SAFE_INTEGER + 2;  //true
```suggestion
Number.MAX_SAFE_INTEGER + 1 === Number.MAX_SAFE_INTEGER + 2;  // true
```

2023-06-09 08:27 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +
```suggestion
=== Magnitude
```

2023-06-09 08:27 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +
```suggestion
Precision
```

2023-06-09 08:27 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +When you need to store a large number, use `BigInt`. `BigInt` and `Number` can be compared between them as usual, but pay attention that operations (`+` `pass:[*]` `-` `%` `pass:[**]`) between both t
```suggestion
When you need to store a large number, use `BigInt`. `BigInt` and `number` can be compared between them as usual, but pay attention that arithmetic operations (`+`, `pass:[*]`, `-`, `%`, `pass:[**]`) between both types raise an error unless they are converted to the same type. Use the `BigInt` and `Number` functions to convert between both types.
```

2023-06-09 08:27 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +Be careful converting values back and forth, however, as the precision of a BigInt value may be lost when it is coerced to a Number value.
```suggestion
Be careful converting values back and forth, however, as the precision of a `BigInt` value may be lost when it is coerced to a `number` value.
```

2023-06-09 08:27 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +When you need to store a large number, use `BigInt`. `BigInt` and `Number` can be compared between them as usual, but pay attention that operations (`+` `pass:[*]` `-` `%` `pass:[**]`) between both t
Why did you remove the mention of comparison?

2023-06-09 08:27 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
>  [source,javascript]
I think we need to split code samples as we did with description (magnitude vs precision) and use Noncompliant/Compliant samples

2023-06-09 08:27 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +When you need to store a large number, use `BigInt`. `BigInt` and `Number` can be compared between them as usual, but pay attention that operations (`+` `pass:[*]` `-` `%` `pass:[**]`) between both t
Why don't you mention `123n` syntax?

2023-06-09 08:27 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> -=== Code examples
ping

2023-06-09 08:27 UTC, vilchik-elena commented on rules/S6534/javascript/rule.adoc
> +myBigInt + 1n === myBigInt + 2n;  //false
```suggestion
myBigInt + 1n === myBigInt + 2n;  // false
```

2023-06-09 09:25 UTC, victor-diez-sonarsource commented on rules/S6534/javascript/rule.adoc
> +When you need to store a large number, use `BigInt`. `BigInt` and `Number` can be compared between them as usual, but pay attention that operations (`+` `pass:[*]` `-` `%` `pass:[**]`) between both t
I didn't remove the mention of the comparison. 
Also, 123n syntax is explained in first tab

2023-06-09 10:24 UTC, vilchik-elena approved these changes

2023-06-09 10:41 UTC, merged