Modify rule S6523: Adapt to LaYC
SonarSource/rspec pull request #2007
Opened 2023-06-01 13:38 UTC by victor-diez-sonarsource

2023-06-01 15:16 UTC, yassin-kammoun-sonarsource approved these changes
Minor suggestions, looks good otherwise.

2023-06-01 15:16 UTC, yassin-kammoun-sonarsource commented on rules/S6523/javascript/rule.adoc
> +const foo = [...bar?.baz]   //Noncompliant: TypeError: (intermediate value) is not iterable
```suggestion
new (foo?.bar)();           // Noncompliant: TypeError: (intermediate value) is not a constructor
const { foo } = bar?.baz;   // Noncompliant: TypeError: Cannot destructure property 'foo' of '(intermediate value)' as it is undefined.
const foo = [...bar?.baz]   // Noncompliant: TypeError: (intermediate value) is not iterable
```

2023-06-01 15:16 UTC, yassin-kammoun-sonarsource commented on rules/S6523/javascript/rule.adoc
> +In order to prevent runtime errors, you should provide fallbacks for when the optional chaining operator short circuits to `undefined`.
```suggestion
In order to prevent runtime errors, you should provide fallbacks for when the optional chaining operator short-circuits to `undefined`.
```

2023-06-06 08:01 UTC, vilchik-elena requested changes

2023-06-08 10:04 UTC, vilchik-elena requested changes

2023-06-08 10:04 UTC, vilchik-elena commented on rules/S6523/javascript/rule.adoc
>  == How to fix it
Conventionally, we need `Nocompliant ..`\`Compliant...` titles here. I agree it's ok without them, still I suggest to add them so that the noncompliant code is present on the second tab.

WDYT about such structure?

```
In order to prevent runtime errors, you should provide fallbacks for when the optional chaining operator short-circuits to `undefined`.

=== Code examples

==== Noncompliant code example
[source,javascript]
----
foo?.bar();
----

==== Compliant solution
* Using nullish coalescing operator `??`
[source,javascript]
----
foo?.bar();
----

* Using logical OR operator `||`
[source,javascript]
----
foo?.bar();
----

* ...
[source,javascript]
----
foo?.bar();
----


```

2023-06-08 13:50 UTC, victor-diez-sonarsource commented on rules/S6523/javascript/metadata.json
> +  "title": "Should not use optional chaining when returning undefined is forbidden",
I would argue that 'undefined' is also a defined value, defined as 'undefined' :P

2023-06-09 07:32 UTC, vilchik-elena requested changes
There is some check is failing on this PR

2023-06-09 09:15 UTC, vilchik-elena requested changes

2023-06-09 09:15 UTC, vilchik-elena commented on rules/S6523/javascript/rule.adoc
> +* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing[MDN - Nullish coalescing operator (??)]
where is doc for optional chaining?)

2023-06-09 09:27 UTC, victor-diez-sonarsource commented on rules/S6523/javascript/rule.adoc
> +* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing[MDN - Nullish coalescing operator (??)]
done :P

2023-06-09 10:35 UTC, vilchik-elena approved these changes

2023-06-09 10:42 UTC, merged