Modify rule S6522: Adapt to LaYC
SonarSource/rspec pull request #2009
Opened 2023-06-01 14:46 UTC by victor-diez-sonarsource

2023-06-01 15:14 UTC, yassin-kammoun-sonarsource approved these changes
Left minor suggestions, otherwise looks good to me.

2023-06-01 15:14 UTC, yassin-kammoun-sonarsource commented on rules/S6522/javascript/rule.adoc
> +Instead, use constants for `import` and `require`, so that their value is always the same in the scope where they are defined.
```suggestion
Instead, use constants for `import` and `require` statements, so that their value is always the same in the scope where they are defined.
```

2023-06-01 15:14 UTC, yassin-kammoun-sonarsource commented on rules/S6522/javascript/rule.adoc
> +[source,javascript]
Do we still need to use the noncompliant tag?

2023-06-01 15:14 UTC, yassin-kammoun-sonarsource commented on rules/S6522/javascript/rule.adoc
>  [source,javascript]
Should we use the compliant tag?

2023-06-05 10:05 UTC, vilchik-elena reviewed
Clarify the scope of the rule first

2023-06-06 12:04 UTC, victor-diez-sonarsource commented on rules/S6522/javascript/rule.adoc
> +[source,javascript]
yes now we need to add an explanation why it is non-compliant

2023-06-07 12:52 UTC, vilchik-elena approved these changes
LGTM! nice work!

2023-06-07 12:52 UTC, vilchik-elena commented on rules/S6522/javascript/rule.adoc
> +fs.readPath = fs.readFile; // fs.default now contains readPath
not sure I understand the comment. Could you elaborate?

2023-06-07 13:01 UTC, victor-diez-sonarsource commented on rules/S6522/javascript/rule.adoc
> +fs.readPath = fs.readFile; // fs.default now contains readPath
when doing a default import, the import variable will point to the exports.default, which is an object that can be modified externally. So this rule does not raise an issue because it's valid js, but that's why I mention: `Please be aware the mutated value can be observed by all other modules importing the same value.`

2023-06-07 13:02 UTC, victor-diez-sonarsource commented on rules/S6522/javascript/rule.adoc
> +fs.readPath = fs.readFile; // fs.default now contains readPath
probably it should say `Please be aware the mutated value can be observed by all other modules importing the same object.`

2023-06-08 07:55 UTC, vilchik-elena commented on rules/S6522/javascript/rule.adoc
> +fs.readPath = fs.readFile; // fs.default now contains readPath
check here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#default_import

the way you import is already default. 
I think you should replace import with `import * as fs from ...`

2023-06-08 07:55 UTC, vilchik-elena commented on rules/S6522/javascript/rule.adoc
> +fs.readPath = fs.readFile; // fs.default now contains readPath
@victor-diez-sonarsource and remove `Please` from that phrase

2023-06-08 09:04 UTC, vilchik-elena requested changes
As discussed please group the cases by the type of imported object (sealed vs live binding)

2023-06-09 07:34 UTC, vilchik-elena approved these changes

2023-06-09 07:34 UTC, merged