Modify S5542: Migrate it to the Learn-As-You-Code mode
SonarSource/rspec pull request #2011
Opened 2023-06-01 15:08 UTC by loris-s-sonarsource

2023-06-07 08:45 UTC, loris-s-sonarsource commented on rules/S5542/rationale.adoc
> +2. The strength of an encryption is usually measured by the effort required to crack it within a reasonable time frame.
```suggestion
2. The strength of an encryption algorithm is usually measured by the effort required to crack it within a reasonable time frame.

```

2023-06-07 08:49 UTC, loris-s-sonarsource commented on rules/S5542/vbnet/how-to-fix-it/dotnet.adoc
> +[source,csharp,diff-id=1,diff-type=noncompliant]
```suggestion
[source,vbnet,diff-id=1,diff-type=noncompliant]
```

2023-06-07 08:49 UTC, loris-s-sonarsource commented on rules/S5542/vbnet/how-to-fix-it/dotnet.adoc
> +[source,csharp,diff-id=2,diff-type=noncompliant]
```suggestion
[source,vbnet,diff-id=2,diff-type=noncompliant]
```

2023-06-07 08:49 UTC, loris-s-sonarsource commented on rules/S5542/vbnet/how-to-fix-it/dotnet.adoc
> +[source,csharp,diff-id=1,diff-type=compliant]
```suggestion
[source,vbnet,diff-id=1,diff-type=compliant]
```

2023-06-07 08:49 UTC, loris-s-sonarsource commented on rules/S5542/vbnet/how-to-fix-it/dotnet.adoc
> +[source,csharp]
```suggestion
[source,vbnet]
```

2023-06-07 08:49 UTC, loris-s-sonarsource commented on rules/S5542/vbnet/how-to-fix-it/dotnet.adoc
> +[source,csharp,diff-id=2,diff-type=compliant]
```suggestion
[source,vbnet,diff-id=2,diff-type=compliant]
```

2023-06-07 08:56 UTC, loris-s-sonarsource commented on rules/S5542/common/resources/articles.adoc
> +
```suggestion

* https://learn.microsoft.com/en-us/dotnet/standard/security/vulnerabilities-cbc-mode[Microsoft, Timing vulnerabilities with CBC-mode symmetric decryption using padding]
```

2023-06-12 11:33 UTC, hendrik-buchwald-sonarsource requested changes
See the comments for details.

2023-06-12 11:33 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/java/how-to-fix-it/java-cryptographic-extension.adoc
> +Cipher.getInstance("AES/CBC/PKCS5Padding"); // Noncompliant
Same comment as above about wrapping it in a function.

2023-06-12 11:33 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/rationale.adoc
> +* Confidentiality, privacy, and intellectual property protection.
```suggestion
* Confidentiality, privacy, and intellectual property protection

```

As per style guide, I would write those points without a dot at the end (since it is just a listing but not full sentences).

2023-06-12 11:33 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/rationale.adoc
> +1. No encryption is absolutely unbreakable.
```suggestion
1. No encryption is unbreakable.

```

I feel like this sounds a little bit better without the "absolutely" and conveys the same message.

2023-06-12 11:33 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/rationale.adoc
> +important to choose encryption algorithms that are considered the strongest by
```suggestion
important to choose encryption algorithms that are considered strong and secure

```

It does not necessarily have to be the strongest algorithm. More security usually also means more computation power required.

2023-06-12 11:33 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/rationale.adoc
> +For AES, the weakest "modes" are CBC (Cipher Block Chaining) and ECB
```suggestion
For AES, the weakest modes are CBC (Cipher Block Chaining) and ECB

```

It is called mode, I don't think quotes are necessary.

2023-06-12 11:33 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/summary.adoc
> +This vulnerability exposes encrypted data to an unnecessarily large number of
```suggestion
This vulnerability exposes encrypted data to a number of
```

"unnecessarily large" feels imprecise as there only has to be one successful attack.

2023-06-12 15:50 UTC, loris-s-sonarsource reviewed
post-review auto-review

2023-06-12 15:50 UTC, loris-s-sonarsource commented on rules/S5542/java/how-to-fix-it/java-cryptographic-extension.adoc
> +Cipher.getInstance("AES/CBC/PKCS5Padding"); // Noncompliant
```suggestion
import javax.crypto.Cipher;
import java.security.NoSuchAlgorithmException;
import javax.crypto.NoSuchPaddingException;

public static void main(String[] args) {
    try {
        Cipher.getInstance("AES/CBC/PKCS5Padding"); // Noncompliant
    } catch(NoSuchAlgorithmException|NoSuchPaddingException e) {
        // ...
    }
}
```

2023-06-12 15:50 UTC, loris-s-sonarsource commented on rules/S5542/java/how-to-fix-it/java-cryptographic-extension.adoc
> +Cipher.getInstance("RSA/None/NoPadding"); // Noncompliant
```suggestion
import javax.crypto.Cipher;
import java.security.NoSuchAlgorithmException;
import javax.crypto.NoSuchPaddingException;

public static void main(String[] args) {
    try {
        Cipher.getInstance("RSA/None/NoPadding"); // Noncompliant
    } catch(NoSuchAlgorithmException|NoSuchPaddingException e) {
        // ...
    }
}
```

2023-06-12 15:50 UTC, loris-s-sonarsource commented on rules/S5542/java/how-to-fix-it/java-cryptographic-extension.adoc
> +Cipher.getInstance("AES/GCM/NoPadding");
```suggestion
import javax.crypto.Cipher;
import java.security.NoSuchAlgorithmException;
import javax.crypto.NoSuchPaddingException;

public static void main(String[] args) {
    try {
        Cipher.getInstance("AES/GCM/NoPadding");
    } catch(NoSuchAlgorithmException|NoSuchPaddingException e) {
        // ...
    }
}
```

2023-06-12 15:50 UTC, loris-s-sonarsource commented on rules/S5542/java/how-to-fix-it/java-cryptographic-extension.adoc
> +Cipher.getInstance("RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING");
```suggestion
import javax.crypto.Cipher;
import java.security.NoSuchAlgorithmException;
import javax.crypto.NoSuchPaddingException;

public static void main(String[] args) {
    try {
        Cipher.getInstance("RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING");
    } catch(NoSuchAlgorithmException|NoSuchPaddingException e) {
        // ...
    }
}
```

2023-06-12 15:50 UTC, loris-s-sonarsource commented on rules/S5542/javascript/how-to-fix-it/node-js.adoc
> +crypto.createCipheriv("AES-128-CBC", key, iv);
```suggestion
crypto.createCipheriv("AES-128-CBC", key, iv); // Noncompliant
```

2023-06-12 15:50 UTC, loris-s-sonarsource commented on rules/S5542/kotlin/how-to-fix-it/java-cryptographic-extension.adoc
> +Cipher.getInstance("AES/CBC/PKCS5Padding"); // Noncompliant
```suggestion
import javax.crypto.Cipher
import javax.crypto.NoSuchPaddingException
import java.security.NoSuchAlgorithmException

fun main(args: Array<String>) {
    try {
        val aes = Cipher.getInstance("AES/CBC/PKCS5Padding"); // Noncompliant
    } catch (e: NoSuchAlgorithmException) {
        // ...
    } catch (e: NoSuchPaddingException) {
        // ...
    }
}
```

2023-06-12 15:50 UTC, loris-s-sonarsource commented on rules/S5542/kotlin/how-to-fix-it/java-cryptographic-extension.adoc
> +Cipher.getInstance("RSA/None/NoPadding"); // Noncompliant
```suggestion
import javax.crypto.Cipher
import javax.crypto.NoSuchPaddingException
import java.security.NoSuchAlgorithmException

fun main(args: Array<String>) {
    try {
        val rsa = Cipher.getInstance("RSA/None/NoPadding"); // Noncompliant
    } catch (e: NoSuchAlgorithmException) {
        // ...
    } catch (e: NoSuchPaddingException) {
        // ...
    }
}
```

2023-06-12 15:50 UTC, loris-s-sonarsource commented on rules/S5542/kotlin/how-to-fix-it/java-cryptographic-extension.adoc
> +[source,java,diff-id=2,diff-type=noncompliant]
```suggestion
[source,kotlin,diff-id=2,diff-type=noncompliant]
```

2023-06-12 15:50 UTC, loris-s-sonarsource commented on rules/S5542/kotlin/how-to-fix-it/java-cryptographic-extension.adoc
> +[source,java,diff-id=1,diff-type=compliant]
```suggestion
[source,kotlin,diff-id=1,diff-type=compliant]
```

2023-06-12 15:50 UTC, loris-s-sonarsource commented on rules/S5542/kotlin/how-to-fix-it/java-cryptographic-extension.adoc
> +----
```suggestion
[source,kotlin,diff-id=2,diff-type=compliant]
----
import javax.crypto.Cipher
import javax.crypto.NoSuchPaddingException
import java.security.NoSuchAlgorithmException

fun main(args: Array<String>) {
    try {
        val rsa = Cipher.getInstance("RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING");
    } catch (e: NoSuchAlgorithmException) {
        // ...
    } catch (e: NoSuchPaddingException) {
        // ...
    }
}
----
```

2023-06-12 15:52 UTC, loris-s-sonarsource commented on rules/S5542/cfamily/how-to-fix-it/openssl.adoc
> +For the RSA assymmetric cypher, use the Optimal asymmetric encryption padding (OAEP):
```suggestion
include::../../common/fix/rsa-compliant-example.adoc[]
```

2023-06-12 15:52 UTC, loris-s-sonarsource commented on rules/S5542/cfamily/how-to-fix-it/openssl.adoc
> +RSA_public_decrypt(flen, from, to, key, RSA_SSLV23_PADDING); // Noncompliant
```suggestion
void encrypt() {
  RSA_public_decrypt(flen, from, to, key, RSA_SSLV23_PADDING); // Noncompliant
}
```

2023-06-12 16:05 UTC, loris-s-sonarsource commented on rules/S5542/rationale.adoc
> +
```suggestion
```

2023-06-13 10:23 UTC, loris-s-sonarsource reviewed
self-review

2023-06-13 10:23 UTC, loris-s-sonarsource commented on rules/S5542/cfamily/rule.adoc
> +
```suggestion
```

2023-06-13 10:23 UTC, loris-s-sonarsource commented on rules/S5542/csharp/rule.adoc
> +
```suggestion
```

2023-06-13 10:23 UTC, loris-s-sonarsource commented on rules/S5542/java/rule.adoc
```suggestion
```

2023-06-13 10:23 UTC, loris-s-sonarsource commented on rules/S5542/javascript/rule.adoc
> +
```suggestion
```

2023-06-13 10:23 UTC, loris-s-sonarsource commented on rules/S5542/kotlin/rule.adoc
```suggestion
```

2023-06-13 10:23 UTC, loris-s-sonarsource commented on rules/S5542/php/rule.adoc
> +
```suggestion
```

2023-06-13 10:23 UTC, loris-s-sonarsource commented on rules/S5542/python/rule.adoc
> +
```suggestion
```

2023-06-13 10:23 UTC, loris-s-sonarsource commented on rules/S5542/vbnet/rule.adoc
> +
```suggestion
```

2023-06-13 12:14 UTC, loris-s-sonarsource commented on rules/S5542/php/rule.adoc
> +dd
```suggestion
```

2023-06-13 14:24 UTC, loris-s-sonarsource commented on rules/S5542/rationale.adoc
> +the cryptography community.
```suggestion
by the cryptography community.
```

2023-06-14 13:45 UTC, hendrik-buchwald-sonarsource requested changes
Looks pretty good already but I spotted some small stuff to change.

2023-06-14 13:45 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/csharp/how-to-fix-it/dotnet.adoc
> +== How to fix it in .Net
```suggestion
== How to fix it in .NET
```

In `allowed_framework_names.adoc` we use the uppercase name, so I think it makes sense to stick to that.

2023-06-14 13:45 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/vbnet/how-to-fix-it/dotnet.adoc
> +== How to fix it in .Net
```suggestion
== How to fix it in .NET
```

In `allowed_framework_names.adoc` we use the uppercase name, so I think it makes sense to stick to that.

2023-06-14 13:45 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/cfamily/how-to-fix-it/botan.adoc
> +void encrypt {
```suggestion
void encrypt() {
```

2023-06-14 13:45 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/cfamily/how-to-fix-it/cryptopp.adoc
> +voic encrypt {
```suggestion
voic encrypt() {
```

2023-06-14 13:45 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/cfamily/how-to-fix-it/openssl.adoc
> +[source,cpp,diff-id=1,diff-type=noncompliant]
```suggestion
[source,cpp,diff-id=1,diff-type=compliant]
```

2023-06-14 13:45 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/cfamily/how-to-fix-it/openssl.adoc
> +[source,cpp,diff-id=2,diff-type=noncompliant]
```suggestion
[source,cpp,diff-id=2,diff-type=compliant]
```

2023-06-14 13:45 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/csharp/how-to-fix-it/dotnet.adoc
> +BouncyCastle can also be used:
What's the reason to also include BouncyCastle here?

2023-06-14 13:45 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/impact.adoc
> +====  Theft of sensitive data
```suggestion
==== Theft of sensitive data
```

2023-06-14 13:45 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/impact.adoc
> +====  Additional attack surface
```suggestion
==== Additional attack surface
```

2023-06-14 13:45 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/vbnet/how-to-fix-it/dotnet.adoc
> +
```suggestion
```

2023-06-14 13:45 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/vbnet/how-to-fix-it/dotnet.adoc
> +BouncyCastle can also be used:
Same question as above.

2023-06-16 08:15 UTC, loris-s-sonarsource commented on rules/S5542/csharp/how-to-fix-it/dotnet.adoc
> +BouncyCastle can also be used:
Only because it was in the original rspec. Unfortunately, [the analyzer's code](https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/src/SonarAnalyzer.Common/Rules/EncryptionAlgorithmsShouldBeSecureBase.cs) does not check bouncycastle code :/ 

Do you think it's overkill here?

2023-06-16 08:15 UTC, loris-s-sonarsource commented on rules/S5542/vbnet/how-to-fix-it/dotnet.adoc
> +BouncyCastle can also be used:
Yeah also same reason, it was there. From the RSPEC Jira entry and its review it looks like it was added without challenging the fact that there was no noncompliant sample, n ow that I look at it

2023-06-16 08:18 UTC, loris-s-sonarsource commented on rules/S5542/php/how-to-fix-it/openssl.adoc
> +== How to fix it in Mcrypt
```suggestion
== How to fix it in OpenSSL
```

2023-06-16 08:20 UTC, loris-s-sonarsource commented on rules/S5542/cfamily/rule.adoc
> +
yes, that's because it does not exist

2023-06-19 09:53 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/csharp/how-to-fix-it/dotnet.adoc
> +BouncyCastle can also be used:
Ah, I see. I would move it to its own file, as it is not part of the .NET core.

2023-06-19 09:57 UTC, hendrik-buchwald-sonarsource commented on rules/S5542/vbnet/how-to-fix-it/dotnet.adoc
> +BouncyCastle can also be used:
Okay, then as said in the other post, I think we should remove it.

2023-06-20 07:14 UTC, hendrik-buchwald-sonarsource approved these changes
LGTM!

2023-06-20 08:15 UTC, loris-s-sonarsource commented on rules/S5542/python/how-to-fix-it/pyca.adoc
> +== How to fix it in Pyca
```suggestion
== How to fix it in pyca
```

2023-06-20 08:27 UTC, merged