S2925: Add c# and vbnet specifications
SonarSource/rspec pull request #2016
Opened 2023-06-01 15:48 UTC by gregory-paidis-sonarsource

2023-06-01 16:19 UTC, antonioaversa requested changes
Title to be fixed for java, comments section to be shared and other more cosmetic remarks.

2023-06-01 16:19 UTC, antonioaversa commented on rules/S2925/csharp/rule.adoc
> +* It can be cancelled and continued, which gives more flexibility and control in the timing of your code.
What about having `asynchronous`, `precise`, `cancelled and continued` in bold?

2023-06-01 16:19 UTC, antonioaversa commented on rules/S2925/csharp/rule.adoc
> +Another scenario is when some data might need to be mocked using https://github.com/moq/moq4[Moq], and a delay needs to be introduced.
Another scenario where `Thread.Sleep` may appear is when some data might need to be mocked using https://github.com/moq/moq4[Moq] or a similar framework, and a delay needs to be introduced.

If I understand well, this is not just about Moq right? It can be any mocking library I guess, such as https://www.telerik.com/products/mocking.aspx.

2023-06-01 16:19 UTC, antonioaversa commented on rules/S2925/csharp/rule.adoc
> +An alternative is to use `ReturnsAsync` and pass the delay amount there:
`delay amount` -> `amount of time to delay` or `time to delay`

2023-06-01 16:19 UTC, antonioaversa commented on rules/S2925/csharp/rule.adoc
> +Remove this use of "Thread.sleep()".
sleep with capital S

2023-06-01 16:19 UTC, antonioaversa commented on rules/S2925/java/metadata.json
> +}
The title is with small s in java and capital s in dotnet, so I guess title has to be overridden either here or for both csharp and vbnet.

2023-06-02 08:27 UTC, gregory-paidis-sonarsource commented on rules/S2925/csharp/rule.adoc
> +* It is more precise than `Thread.Sleep`.
I meant that it has better precision in milliseconds.
I will clarify with "more precise in timing the delay", if that's fine with you.

2023-06-02 08:32 UTC, gregory-paidis-sonarsource commented on rules/S2925/csharp/rule.adoc
> +An alternative is to use `ReturnsAsync` and pass the delay amount there:
made it more specific

2023-06-02 08:33 UTC, gregory-paidis-sonarsource commented on rules/S2925/java/metadata.json
> +}
overriden in java, for brevity

2023-06-02 09:17 UTC, antonioaversa commented on rules/S2925/vbnet/rule.adoc
> +== Why is this an issue?
There are some differences between the csharp version and the vbnet one:
- `It is **asynchronous**: This means that the thread will not be blocked, but instead will be reused by other operations` vs `It is **asynchronous**: The thread will not be blocked, but instead will be reused by other operations`
- `Another scenario is when some data might need to be mocked and a delay needs to be introduced.
One example of this is when using https://github.com/moq/moq4[Moq].` vs `Another scenario is when some data might need to be mocked using https://github.com/moq/moq4[Moq], and a delay needs to be introduced.`
- [Optional and only personal preference] the non-compliant version of the code in csharp goes to new line at every `.`, whereas the vb.net doesn't. I think non inlining in VB.NET is more cumbersome, since you need to prepend each line with `_`. Still, I would align the style used in VB.NET to the one used in the C# version.
- [Optional and only personal preference] there is an empty line in the compliant version in C#, which is not there in VB.NET

2023-06-02 09:17 UTC, antonioaversa commented on rules/S2925/csharp/rule.adoc
> +* It is asynchronous. This means that the thread will not be blocked, but instead will be reused by other operations.
First words are still capitalized

2023-06-02 09:18 UTC, antonioaversa approved these changes
LGTM! Two conversations still open and to be checked, before merging.

2023-06-02 09:28 UTC, antonioaversa commented on rules/S2925/csharp/rule.adoc
> +* It is asynchronous. This means that the thread will not be blocked, but instead will be reused by other operations.
Makes sense as it is the start of a sentence.

2023-06-05 12:01 UTC, pavel-mikula-sonarsource commented on rules/S2925/csharp/rule.adoc
> +endif::env-github,rspecator-view[]
This ugly (hard to maintain) `ifdef` section can be extracted into `rspecator.adoc` or `rspecator-dotnet.adoc` in the root

2023-06-05 12:02 UTC, pavel-mikula-sonarsource commented on rules/S2925/resources-dotnet.adoc
> +* https://www.telerik.com/products/mocking.aspx[Telerik mocking library]
I'm not sure why the Telerik is here, when the rule doesn't speak about it.

2023-06-05 12:04 UTC, pavel-mikula-sonarsource commented on rules/S2925/vbnet/rule.adoc
> +
Same below

2023-06-05 12:05 UTC, pavel-mikula-sonarsource commented on rules/S2925/vbnet/rule.adoc
> +    Dim userService = New Mock(Of UserService)()
```suggestion
    Dim UserService As New Mock(Of UserService)
```

2023-06-05 12:06 UTC, pavel-mikula-sonarsource commented on rules/S2925/vbnet/rule.adoc
> +    userService.Setup(Function(m) m.GetUserById(42)).Returns(
```suggestion
    UserService.Setup(Function(X) X.GetUserById(42)).Returns(
```

2023-06-05 12:07 UTC, pavel-mikula-sonarsource commented on rules/S2925/vbnet/rule.adoc
> +Public Sub UserService_Test()
Same nitpicks as above

2023-06-05 12:11 UTC, pavel-mikula-sonarsource commented on rules/S2925/vbnet/rule.adoc
> +== Why is this an issue?
The inline version is fine. Leave it as it is.

`_` is not used in VB except some extreme cases.
The VB formatting would be like this with auto line continuation
```
        UserService.
            Setup(Function(m) m.GetUserById(42)).
            ReturnsAsync(expected, TimeSpan.FromMilliseconds(500))
```

2023-06-05 12:11 UTC, pavel-mikula-sonarsource approved these changes
LGTM, left some nitpicks above

2023-06-06 12:52 UTC, merged