Modify rule S5547: LaYC format
SonarSource/rspec pull request #2023
Opened 2023-06-02 12:27 UTC by hendrik-buchwald-sonarsource

2023-06-07 08:53 UTC, loris-s-sonarsource requested changes
- Multiple pretty medium requests
- imports are missing in multiple code samples

2023-06-07 08:53 UTC, loris-s-sonarsource commented on rules/S5547/kotlin/how-to-fix-it/java-cryptographic-extension.adoc
> +fun main(args: Array<String>) {
Same suggestion to get rid of the function

2023-06-07 08:53 UTC, loris-s-sonarsource commented on rules/S5547/php/how-to-fix-it/openssl.adoc
> +https://www.php.net/manual/en/book.sodium.php[Sodium] instead.
```suggestion
```

2023-06-07 08:53 UTC, loris-s-sonarsource commented on rules/S5547/php/rule.adoc
> +include::how-to-fix-it/mcrypt.adoc[]
Suggestion to add a newline in between includes to avoid black magic errors

2023-06-07 08:53 UTC, loris-s-sonarsource commented on rules/S5547/vbnet/how-to-fix-it/system-security-cryptography.adoc
> +[source,csharp,diff-id=1,diff-type=noncompliant]
```suggestion
[source,vbnet,diff-id=1,diff-type=noncompliant]
```

2023-06-07 08:53 UTC, loris-s-sonarsource commented on rules/S5547/vbnet/how-to-fix-it/bouncy-castle.adoc
> +[source,csharp,diff-id=1,diff-type=noncompliant]
```suggestion
[source,vbnet,diff-id=1,diff-type=noncompliant]
```

2023-06-07 08:53 UTC, loris-s-sonarsource commented on rules/S5547/vbnet/how-to-fix-it/system-security-cryptography.adoc
> +[source,csharp,diff-id=1,diff-type=compliant]
```suggestion
[source,vbnet,diff-id=1,diff-type=compliant]
```

2023-06-07 16:02 UTC, hendrik-buchwald-sonarsource commented on rules/S5547/common/resources/docs.adoc
> +* https://botan.randombit.net/handbook/[Botan] - Handbook
True, I agree. It would not be very valuable.

I think it would be good to also have docs for the other languages but I am not going to add them in this PR to not make the scope of the changes too big.

2023-06-07 16:04 UTC, hendrik-buchwald-sonarsource commented on rules/S5547/common/fix/strong-cryptography.adoc
> +It is highly recommended to use an algorithm that is currently considered secure
Okay, why not, I have added it.

2023-06-07 16:08 UTC, hendrik-buchwald-sonarsource commented on rules/S5547/summary.adoc
> +might be recoverable without prior knowledge of the key.
I think `unnecessarily large number` is a bit too imprecise. There might just be a single possible attack and that might be enough.

2023-06-07 16:20 UTC, hendrik-buchwald-sonarsource commented on rules/S5547/rationale.adoc
> +be able to decrypt an encrypted message to access its content.
I like your version better than mine. The only sentence I would disagree with is the following:

> it is important to choose encryption algorithms that are considered the strongest by
the cryptography community.

I think it is important to use an algorithm that is considered strong, not necessarily the strongest though. Stronger usually also means it requires more computational power, so it might not be a good idea to use _the strongest_ if the additional security does not realistically make any difference.

2023-06-07 16:24 UTC, hendrik-buchwald-sonarsource commented on rules/S5547/rationale.adoc
> +be able to decrypt an encrypted message to access its content.
I have added a slightly modified version now.

2023-06-08 09:54 UTC, loris-s-sonarsource requested changes
A very few changes left! 🦾

2023-06-08 09:54 UTC, loris-s-sonarsource commented on rules/S5547/kotlin/rule.adoc
> -* https://owasp.org/www-project-mobile-top-10/2016-risks/m5-insufficient-cryptography[OWASP Mobile Top 10 2016 Category M5] - Insufficient Cryptography
Minor: Just noticed that these were not in the standards.adoc file

2023-06-08 09:54 UTC, loris-s-sonarsource commented on rules/S5547/csharp/how-to-fix-it/dot-net.adoc
> +----
```suggestion
----
using System.Security.Cryptography;

```

2023-06-08 09:54 UTC, loris-s-sonarsource commented on rules/S5547/csharp/how-to-fix-it/dot-net.adoc
> +----
```suggestion
----
using System.Security.Cryptography;

```

2023-06-08 09:54 UTC, loris-s-sonarsource commented on rules/S5547/csharp/how-to-fix-it/bouncy-castle.adoc
> +----
```suggestion
----
using Org.BouncyCastle.Crypto.Engines;
using Org.BouncyCastle.Crypto.Parameters;

```

2023-06-08 09:54 UTC, loris-s-sonarsource commented on rules/S5547/csharp/how-to-fix-it/bouncy-castle.adoc
> +----
```suggestion
----
using Org.BouncyCastle.Crypto.Engines;
using Org.BouncyCastle.Crypto.Parameters;

```

2023-06-08 09:54 UTC, loris-s-sonarsource commented on rules/S5547/java/how-to-fix-it/java-cryptographic-extension.adoc
> +public static void main(String[] args) {
About the try catches: Ok, it adds value because thanks to that users won't trigger the exception rule

About the method: We have multiple code samples in other languages with no method declaration so they are not consistent, unfortunately.

If we keep the method declaration here, let's declare it in the other code samples, at least in the languages where adding it out of a method would pose a problem.

2023-06-08 09:54 UTC, loris-s-sonarsource commented on rules/S5547/vbnet/how-to-fix-it/bouncy-castle.adoc
> +----
```suggestion
----
Imports Org.BouncyCastle.Crypto.Engines
Imports Org.BouncyCastle.Crypto.Parameters

```

2023-06-08 09:54 UTC, loris-s-sonarsource commented on rules/S5547/vbnet/how-to-fix-it/bouncy-castle.adoc
> +----
```suggestion
----
```suggestion
Imports Org.BouncyCastle.Crypto.Engines
Imports Org.BouncyCastle.Crypto.Parameters

```
```

2023-06-08 09:54 UTC, loris-s-sonarsource commented on rules/S5547/vbnet/how-to-fix-it/dot-net.adoc
> +----
```suggestion
----
Imports System.Security.Cryptography

```

2023-06-08 09:54 UTC, loris-s-sonarsource commented on rules/S5547/vbnet/how-to-fix-it/dot-net.adoc
> +----
```suggestion
----
Imports System.Security.Cryptography

```

2023-06-09 14:14 UTC, hendrik-buchwald-sonarsource commented on rules/S5547/java/how-to-fix-it/java-cryptographic-extension.adoc
> +public static void main(String[] args) {
Good point. I think it should be changed for cfamily and csharp. It does not need to be changed for javascript and python since there the import can be on the same level as the code.

2023-06-12 12:53 UTC, loris-s-sonarsource commented on rules/S5547/vbnet/how-to-fix-it/dot-net.adoc
> +Dim SimpleDES As New DESCryptoServiceProvider() ' Noncompliant
```suggestion
Public Sub Encrypt()
    Dim SimpleDES As New DESCryptoServiceProvider() ' Noncompliant
End Sub
```

2023-06-12 12:53 UTC, loris-s-sonarsource commented on rules/S5547/vbnet/how-to-fix-it/dot-net.adoc
> +Dim AES128ECB = Aes.Create()
```suggestion
Public Sub Encrypt()
    Dim AES128ECB = Aes.Create()
End Sub
```

2023-06-12 13:05 UTC, hendrik-buchwald-sonarsource commented
@loris-s-sonarsource yea, I did not add them because I did not want to distract from what the rule is about. It is not relevant for this rule how the IV is specified. And if I add it I have to make sure that it is secure, in case people copy it. So in the end, I think it is best to leave key and IV away here.

2023-06-12 13:58 UTC, merged