Sonar-dotnet: Migrate multiple rules to LaYC level 2
SonarSource/rspec pull request #2033
Opened 2023-06-02 15:02 UTC by gregory-paidis-sonarsource

2023-06-06 16:03 UTC, antonioaversa approved these changes
LGTM

2023-06-07 07:18 UTC, cristian-ambrosini-sonarsource requested changes
Some changes before merging

2023-06-07 07:18 UTC, cristian-ambrosini-sonarsource commented on rules/S2857/comments-and-links.adoc
> +Alternatively, we can just make an exception for ``++,++`` and consider the comma like a space ?
` ``++ ` can be written as `

2023-06-07 07:18 UTC, cristian-ambrosini-sonarsource commented on rules/S2857/comments-and-links.adoc
> +* we raise issues only if the previous string ends with an alphanumeric character or ``++*++`` or ``++@++`` and the next one starts with an alphanumeric character (if we have non-alphanumeric charact
` ``++ ` can be written as `

2023-06-07 07:34 UTC, sebastien-marichal requested changes
I mainly looked for grammar mistakes.
Didn't look at all the files yet

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2187/csharp/rule.adoc
> +Using a base class that contains one or more test cases, to provide generic test cases is also consider a compliant scenario.
```suggestion
Using a base class that contains one or more test cases, to provide generic test cases is also considered a compliant scenario.
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2187/csharp/rule.adoc
> +*This particular exception scenario is only applies to the MSTest test framework.*
```suggestion
*This particular exception scenario only applies to the MSTest test framework.*
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2178/resources-dotnet.adoc
> +* https://learn.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/operators-and-expressions/logical-and-bitwise-operators[Logical and Bitwise Operators in Visual Basic]
We have both languages (C# & VB.NET) in a shared adoc file

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2187/csharp/rule.adoc
> +More informations here:
```suggestion
More information here:
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2187/csharp/rule.adoc
> +More informations here:
```suggestion
More information here:
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2222/csharp/rule.adoc
> +    lock(obj) // Compliant: the lock will be release at the end of the lock block
```suggestion
    lock(obj) // Compliant: the lock will be released at the end of the lock block
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2222/csharp/rule.adoc
> +    lockObj.EnterReadLock(); // Compliant: the lock will be release in the finally block
```suggestion
    lockObj.EnterReadLock(); // Compliant: the lock will be released in the finally block
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2222/vbnet/rule.adoc
> +        SyncLock obj ' Compliant: the lock will be release at the end of the SyncLock block
```suggestion
        SyncLock obj ' Compliant: the lock will be released at the end of the SyncLock block
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2222/vbnet/rule.adoc
> +        lockObj.EnterReadLock() ' Compliant: the lock will be release in the finally block
```suggestion
        lockObj.EnterReadLock() ' Compliant: the lock will be released in the finally block
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2223/csharp/rule.adoc
> +Unlike instance fields, that can only be accessed by code having a hold on the instance, `static` fields can be accessed by any code having visibility of the field and its type.
```suggestion
Unlike instance fields, which can only be accessed by code having a hold on the instance, `static` fields can be accessed by any code having visibility of the field and its type.
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2275/csharp/rule.adoc
> +* the format string is not a `const`.
Nitpick: For formatting reasons, we could add a `+` in the next blank line to align the code example with the bullet point.
```
* the format string is not a `const`.
+
[source,csharp]
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2306/csharp/rule.adoc
> +https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords[Keywords], on the other hand, are always reserved, and therefore are not valid variable names.
```suggestion
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords[Keywords], on the other hand, are always reserved and therefore are not valid variable names. 
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2346/csharp/rule.adoc
> +Consistent use of `None` in flags enumerations indicates that all flag values are cleared. The value 0 should not be used to indicate any other state, since there is no way to check that the bit `0`
```suggestion
Consistent use of `None` in flag enumerations indicates that all flag values are cleared. The value 0 should not be used to indicate any other state since there is no way to check that the bit `0` is set.
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2346/vbnet/rule.adoc
> +Consistent use of `None` in flags enumerations indicates that all flag values are cleared. The value 0 should not be used to indicate any other state, since there is no way to check that the bit `0`
```suggestion
Consistent use of `None` in flag enumerations indicates that all flag values are cleared. The value 0 should not be used to indicate any other state since there is no way to check that the bit `0` is set.
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2368/csharp/intuitive-code.adoc
> +    public void WriteMatrix(Matrix2x2 matrix) // Compliant
```suggestion
    public void WriteMatrix(Matrix2x2 matrix) // Compliant: data type is explicit
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2368/csharp/unintuitive-code.adoc
> +    public void WriteMatrix(int[][] matrix) // Noncompliant
```suggestion
    public void WriteMatrix(int[][] matrix) // Noncompliant: data type is implicit
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2368/vbnet/exception-code.adoc
> +    Private Sub UpdateMatrix(matrix As Integer()()) ' Compliant
```suggestion
    Private Sub UpdateMatrix(matrix As Integer()()) ' Compliant: method is private
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2368/vbnet/intuitive-code.adoc
> +    Public Sub WriteMatrix(matrix As Matrix2x2) ' Compliant
```suggestion
    Public Sub WriteMatrix(matrix As Matrix2x2) ' Compliant: data type is explicit
```

2023-06-07 07:34 UTC, sebastien-marichal commented on rules/S2368/vbnet/unintuitive-code.adoc
> +    Public Sub WriteMatrix(matrix As Integer()()) ' Noncompliant
```suggestion
    Public Sub WriteMatrix(matrix As Integer()()) ' Noncompliant: data type is implicit
```

2023-06-07 08:34 UTC, sebastien-marichal requested changes
Finish reviewing all files.

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S2699/csharp/rule.adoc
> +Those tests increase the coverage without enforcing anything on convered code, resulting in a false sense of security.
```suggestion
Those tests increase the coverage without enforcing anything on the covered code, resulting in a false sense of security.
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S2857/csharp/rule.adoc
> +        "FROM Person as p" +    // Noncompliant: concatenation results in "p.zipFROM"
```suggestion
        "FROM Person as p" +    // Noncompliant: concatenation results in "p.PhoneNumberFROM"
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S2930/csharp/rule.adoc
> +Here is the list of predefined factory method tracked by this rule:
```suggestion
Here is the list of predefined factory methods tracked by this rule:
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S2953/csharp/rule.adoc
> +The decision would be based on whether the instance can have unmanaged resources which have to be dealt with, upon destruction or ealier in the lifetime of the object.
```suggestion
The decision would be based on whether the instance can have unmanaged resources which have to be dealt with, upon destruction or earlier in the lifetime of the object.
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S2953/csharp/rule.adoc
> +The https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern[Dispose pattern] can help making the determination.
```suggestion
The https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern[Dispose pattern] can help to take the decision.
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S2970/csharp/rule.adoc
> +NFluent offers a syntax for assertions, and it's important to follow `Check.That()` with an assertion method to complete the assertion.
```suggestion
`NFluent` offers a syntax for assertions, and it's important to follow `Check.That()` with an assertion method to complete the assertion.
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S3060/csharp/rule.adoc
> +* Make the method https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/virtual[virtual], if it is not already. That will allow derive classes to perform https://en.wikipedia.or
```suggestion
* Make the method https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/virtual[virtual], if it is not already. That will allow derived classes to perform https://en.wikipedia.org/wiki/Method_overriding[method overriding].
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S3060/csharp/rule.adoc
> +* Move the code at the right level of the type hierarchy.
```suggestion
* Move the code to the right level of the type hierarchy.
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S3060/csharp/rule.adoc
> +When simple method polymorphism is not enough, for example because multiple sections of the parent method should be reused, the https://en.wikipedia.org/wiki/Template_method_pattern[Template method p
```suggestion
When simple method polymorphism is not enough, for example, because multiple sections of the parent method should be reused, the https://en.wikipedia.org/wiki/Template_method_pattern[Template method pattern] might help.
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S3427/csharp/rule.adoc
> +  public static void Print(int number, string delimiter = "\n") { } // Noncompliant, default parameter value is hidden by overload
```suggestion
  public static void Print(int number, string delimiter = "\n") { } // Noncompliant: default parameter value is hidden by overload
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S3433/csharp/rule.adoc
> +However, non-`public` methods are not considered as tests and will not be executed, regardless of whether they have a test attribute.
```suggestion
However, non-`public` methods are not considered test methods and will not be executed, regardless of whether they have a test attribute.
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S3443/csharp/rule.adoc
> +Calling `GetType` on a `Type` variable will always return the `System.Type` representation, which is equivalent to `typeof(System.Type)`. This also applies to passing a `Type` argument to `IsInstance
```suggestion
Calling `GetType` on a `Type` variable will always return the `System.Type` representation, which is equivalent to `typeof(System.Type)`. This also applies to passing a `Type` argument to `IsInstanceOfType` which always returns `false`.
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S3443/csharp/rule.adoc
> +Make sure the usage of `GetType` or `IsInstanceOfType` is invoked with correct variable or argument type.
```suggestion
Make sure the usage of `GetType` or `IsInstanceOfType` is invoked with the correct variable or argument type.
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S3464/csharp/rule.adoc
> +For example the implementation of the generator for the n-th value of the Fibonacci sequence comes naturally from its mathematical definition, when recursion is used:
```suggestion
For example, the implementation of the generator for the n-th value of the Fibonacci sequence comes naturally from its mathematical definition, when recursion is used:
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S3464/vbnet/rule.adoc
> +For example the implementation of the generator for the n-th value of the https://en.wikipedia.org/wiki/Fibonacci_sequence[Fibonacci sequence] comes naturally from its mathematical definition, when r
```suggestion
For example, the implementation of the generator for the n-th value of the https://en.wikipedia.org/wiki/Fibonacci_sequence[Fibonacci sequence] comes naturally from its mathematical definition, when recursion is used:
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S3875/csharp/rule.adoc
> +* Classes that implement `IComparable<T>` or `IEquatable<T>` most probably behave as a value-type objects and so are ignored.
```suggestion
* Classes that implement `IComparable<T>` or `IEquatable<T>` most probably behave as value-type objects and so are ignored.
```

2023-06-07 08:34 UTC, sebastien-marichal commented on rules/S4159/why.adoc
> +In this model objects are required to conform a specific structure, so that they can be used by the https://learn.microsoft.com/en-us/dotnet/framework/mef/[Managed Extensibility Framework (MEF)].
```suggestion
In this model, objects are required to conform to a specific structure, so that they can be used by the https://learn.microsoft.com/en-us/dotnet/framework/mef/[Managed Extensibility Framework (MEF)].
```

2023-06-07 09:33 UTC, cristian-ambrosini-sonarsource approved these changes
LGTM!

2023-06-07 09:35 UTC, sebastien-marichal approved these changes

2023-06-07 09:43 UTC, sebastien-marichal commented on rules/S2187/csharp/rule.adoc
> +Using a base class that contains one or more test cases, to provide generic test cases is also consider a compliant scenario.
Fix in #2090

2023-06-07 09:43 UTC, sebastien-marichal commented on rules/S2187/csharp/rule.adoc
> +*This particular exception scenario is only applies to the MSTest test framework.*
Fix in #2090

2023-06-07 09:43 UTC, sebastien-marichal commented on rules/S2187/csharp/rule.adoc
> +More informations here:
Fix in #2090

2023-06-07 09:44 UTC, sebastien-marichal commented on rules/S2187/csharp/rule.adoc
> +More informations here:
Fix in #2090

2023-06-07 09:44 UTC, sebastien-marichal commented on rules/S2222/vbnet/rule.adoc
> +        SyncLock obj ' Compliant: the lock will be release at the end of the SyncLock block
Fix in #2090

2023-06-07 09:44 UTC, sebastien-marichal commented on rules/S2222/vbnet/rule.adoc
> +        lockObj.EnterReadLock() ' Compliant: the lock will be release in the finally block
Fix in #2090

2023-06-07 09:44 UTC, sebastien-marichal commented on rules/S2223/csharp/rule.adoc
> +Unlike instance fields, that can only be accessed by code having a hold on the instance, `static` fields can be accessed by any code having visibility of the field and its type.
Fix in #2090

2023-06-07 09:44 UTC, sebastien-marichal commented on rules/S2223/csharp/rule.adoc
> +Another typical scenario of use of non-private mutable `static` field is the following:
Fix in #2090

2023-06-07 09:44 UTC, sebastien-marichal commented on rules/S2275/csharp/rule.adoc
> +* the format string is not a `const`.
Fix in #2090

2023-06-07 09:44 UTC, sebastien-marichal commented on rules/S2306/csharp/rule.adoc
> +https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords[Keywords], on the other hand, are always reserved, and therefore are not valid variable names.
Fix in #2090

2023-06-07 09:45 UTC, sebastien-marichal commented on rules/S2346/csharp/rule.adoc
> +Consistent use of `None` in flags enumerations indicates that all flag values are cleared. The value 0 should not be used to indicate any other state, since there is no way to check that the bit `0`
Fix in #2090

2023-06-07 09:45 UTC, sebastien-marichal commented on rules/S2346/vbnet/rule.adoc
> +Consistent use of `None` in flags enumerations indicates that all flag values are cleared. The value 0 should not be used to indicate any other state, since there is no way to check that the bit `0`
Fix in #2090

2023-06-07 09:45 UTC, sebastien-marichal commented on rules/S2368/csharp/exception-code.adoc
> +    public void UpdateMatrix(int[][] matrix) // Compliant, class is internal
Fix in #2090

2023-06-07 09:45 UTC, sebastien-marichal commented on rules/S2368/csharp/exception-code.adoc
> +    private void UpdateMatrix(int[][] matrix) // Compliant
Fix in #2090

2023-06-07 09:45 UTC, sebastien-marichal commented on rules/S2368/csharp/intuitive-code.adoc
> +    public void WriteMatrix(Matrix2x2 matrix) // Compliant
Fix in #2090

2023-06-07 09:45 UTC, sebastien-marichal commented on rules/S2368/csharp/unintuitive-code.adoc
> +    public void WriteMatrix(int[][] matrix) // Noncompliant
Fix in #2090

2023-06-07 09:45 UTC, sebastien-marichal commented on rules/S2368/vbnet/intuitive-code.adoc
> +    Public Sub WriteMatrix(matrix As Matrix2x2) ' Compliant
Fix in #2090

2023-06-07 09:45 UTC, sebastien-marichal commented on rules/S2368/vbnet/unintuitive-code.adoc
> +    Public Sub WriteMatrix(matrix As Integer()()) ' Noncompliant
Fix in #2090

2023-06-07 09:45 UTC, sebastien-marichal commented on rules/S2437/csharp/rule.adoc
> +Specifically, using `& -1` with any value always results the original value.
Fix in #2090

2023-06-07 09:45 UTC, sebastien-marichal commented on rules/S2437/vbnet/rule.adoc
> +Specifically, using `And -1` with any value always results the original value.
Fix in #2090

2023-06-07 09:46 UTC, sebastien-marichal commented on rules/S2857/csharp/rule.adoc
> +        "FROM Person as p" +    // Noncompliant: concatenation results in "p.zipFROM"
Fix in #2090

2023-06-07 09:46 UTC, sebastien-marichal commented on rules/S2930/csharp/rule.adoc
> +Here is the list of predefined factory method tracked by this rule:
Fix in #2090

2023-06-07 09:46 UTC, sebastien-marichal commented on rules/S2953/csharp/rule.adoc
> +The decision would be based on whether the instance can have unmanaged resources which have to be dealt with, upon destruction or ealier in the lifetime of the object.
Fix in #2090

2023-06-07 09:46 UTC, sebastien-marichal commented on rules/S2953/csharp/rule.adoc
> +The https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern[Dispose pattern] can help making the determination.
Fix in #2090

2023-06-07 09:46 UTC, sebastien-marichal commented on rules/S2970/csharp/rule.adoc
> +Fluent Assertions provides an interface for writing assertions, and it is important to ensure that `Should()` is properly used in conjunction with an assertion method.
Fix in #2090

2023-06-07 09:46 UTC, sebastien-marichal commented on rules/S2970/csharp/rule.adoc
> +NFluent offers a syntax for assertions, and it's important to follow `Check.That()` with an assertion method to complete the assertion.
Fix in #2090

2023-06-07 09:46 UTC, sebastien-marichal commented on rules/S3060/csharp/rule.adoc
> +* Make the method https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/virtual[virtual], if it is not already. That will allow derive classes to perform https://en.wikipedia.or
Fix in #2090

2023-06-07 09:46 UTC, sebastien-marichal commented on rules/S3060/csharp/rule.adoc
> +* Move the code at the right level of the type hierarchy.
Fix in #2090

2023-06-07 09:46 UTC, sebastien-marichal commented on rules/S3060/csharp/rule.adoc
> +When simple method polymorphism is not enough, for example because multiple sections of the parent method should be reused, the https://en.wikipedia.org/wiki/Template_method_pattern[Template method p
Fix in #2090

2023-06-07 09:47 UTC, sebastien-marichal commented on rules/S3427/csharp/rule.adoc
> +  public static void Print(int number, string delimiter = "\n") { } // Noncompliant, default parameter value is hidden by overload
Fix in #2090

2023-06-07 09:47 UTC, sebastien-marichal commented on rules/S3433/csharp/rule.adoc
> +However, non-`public` methods are not considered as tests and will not be executed, regardless of whether they have a test attribute.
Fix in #2090

2023-06-07 09:47 UTC, sebastien-marichal commented on rules/S3443/csharp/rule.adoc
> +Calling `GetType` on a `Type` variable will always return the `System.Type` representation, which is equivalent to `typeof(System.Type)`. This also applies to passing a `Type` argument to `IsInstance
Fix in #2090

2023-06-07 09:47 UTC, sebastien-marichal commented on rules/S3443/csharp/rule.adoc
> +Make sure the usage of `GetType` or `IsInstanceOfType` is invoked with correct variable or argument type.
Fix in #2090

2023-06-07 09:47 UTC, sebastien-marichal commented on rules/S3464/csharp/rule.adoc
> +For example the implementation of the generator for the n-th value of the Fibonacci sequence comes naturally from its mathematical definition, when recursion is used:
Fix in #2090

2023-06-07 09:47 UTC, sebastien-marichal commented on rules/S3464/vbnet/rule.adoc
> +For example the implementation of the generator for the n-th value of the https://en.wikipedia.org/wiki/Fibonacci_sequence[Fibonacci sequence] comes naturally from its mathematical definition, when r
Fix in #2090

2023-06-07 09:47 UTC, sebastien-marichal commented on rules/S3875/csharp/rule.adoc
> +* Classes that implement `IComparable<T>` or `IEquatable<T>` most probably behave as a value-type objects and so are ignored.
Fix in #2090

2023-06-07 09:47 UTC, sebastien-marichal commented on rules/S4159/why.adoc
> +In this model objects are required to conform a specific structure, so that they can be used by the https://learn.microsoft.com/en-us/dotnet/framework/mef/[Managed Extensibility Framework (MEF)].
Fix in #2090

2023-06-07 10:01 UTC, merged