Modify rule S2346: LaYC format
SonarSource/rspec pull request #2045
Opened 2023-06-05 12:28 UTC by antonioaversa

Adapts the [rule](https://sonarsource.github.io/rspec/#/rspec/S2346) to LaYC format level 2, for dotnet languages (csharp, vbnet).

2023-06-05 13:36 UTC, sebastien-marichal commented on rules/S2346/csharp/rule.adoc
> +var someDays = Days.Wednesday | Days.Weekend;                    // 0b01100100
I would include this line in the next example as, to me, it is not as relevant in this example as it could be in the next one.

While reading documentation or tutorials, I will sometimes skip to the example that seems to be the most relevant one which could be the next one, then some context will be missing.

2023-06-05 13:41 UTC, sebastien-marichal commented on rules/S2346/resources.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators[Bitwise and shift operators (C# reference)]
I think we should separate resources when we language specific links.

2023-06-05 15:06 UTC, antonioaversa commented on rules/S2346/resources.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators[Bitwise and shift operators (C# reference)]
I think there has been the opposite recommendation in a previous PR.
I will ask the question on Slack.

2023-06-06 06:57 UTC, antonioaversa commented on rules/S2346/resources.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators[Bitwise and shift operators (C# reference)]
As discussed on Slack: separating resources when lang-specific content is present, from now on.

2023-06-06 08:18 UTC, sebastien-marichal requested changes
One last small change. Otherwise all good!

2023-06-06 08:18 UTC, sebastien-marichal commented on rules/S2346/csharp/rule.adoc
>  ifdef::env-github,rspecator-view[]
You can extract this `ifdef/endif` section to a dedicated `rspecator.adoc` file and include it in both languages.

2023-06-06 11:48 UTC, merged