Modify rule S2222: LaYC format
SonarSource/rspec pull request #2046
Opened 2023-06-05 13:31 UTC by sebastien-marichal

2023-06-05 13:50 UTC, sebastien-marichal commented on rules/S2222/why-dotnet.adoc
> +=== Exceptions
This is a bit overkill, might remove it.
@gregory-paidis-sonarsource WDYT?

2023-06-05 15:55 UTC, gregory-paidis-sonarsource requested changes
Looks good, left a couple suggestions

2023-06-05 15:55 UTC, gregory-paidis-sonarsource commented on rules/S2222/why-dotnet.adoc
> +* `SpinLock`
I think it would be nice if you linked all of these (Monitor, Mutex, etc)

2023-06-06 11:41 UTC, sebastien-marichal commented on rules/S2222/csharp/rule.adoc
> +{
The logic is identical, but since the solution is mentioned in the `How to fix it` section, I will keep it. I think it is better to show multiple solutions to an issue.

For instance, I don't think I would have thought of the `try-finally` solution to release a lock object before reading this rule.

2023-06-06 14:02 UTC, gregory-paidis-sonarsource approved these changes
LGTM!

2023-06-06 14:02 UTC, merged