Modify rule S3923: LaYC identical branches
SonarSource/rspec pull request #2049
Opened 2023-06-05 13:50 UTC by frederic-tingaud-sonarsource

2023-06-05 14:51 UTC, amelie-renard-sonarsource requested changes

2023-06-05 14:51 UTC, amelie-renard-sonarsource commented on rules/S3923/abap/rule.adoc
> +Having all branches in a `CASE` or `IF` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `CASE`/`
```suggestion
Having all branches in a `CASE` or `IF` chain with the same implementation is odd. Either a copy-paste error was made, and something different should be executed, or there shouldn't be a `CASE`/`IF` chain.
```
To be less harsh?
(+Grammarly)
(and same comment for the other languages)

2023-06-05 14:51 UTC, amelie-renard-sonarsource commented on rules/S3923/abap/rule.adoc
>  [source,abap]
Could you find a sentence to introduce this code?
(and same comment for the other languages)

2023-06-05 14:51 UTC, amelie-renard-sonarsource commented on rules/S3923/plsql/rule.adoc
> +Having all branches in a `CASE` or `IF`/`ELSIF` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a
```suggestion
Having all branches in a `CASE` or `IF`/`ELSIF` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `CASE` or `IF`/`ELSIF` chain at all.
```

2023-06-05 14:51 UTC, amelie-renard-sonarsource commented on rules/S3923/ruby/rule.adoc
> +Having all branches in a `case` or `if` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `case`/`
```suggestion
Having all branches in a `case` or `if` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `case` or `if` chain at all.
```

2023-06-05 14:51 UTC, amelie-renard-sonarsource commented on rules/S3923/scala/rule.adoc
> +Having all branches in a `match` or `if` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `match`
```suggestion
Having all branches in a `match` or `if` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `match` or `if` chain at all.
```

2023-06-05 14:51 UTC, amelie-renard-sonarsource commented on rules/S3923/tsql/rule.adoc
> +Having all branches in a `CASE`, `IF` or `IIF` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `
```suggestion
Having all branches in a `CASE`, `IF` or `IIF` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `CASE`, `IF`, or `IIF` chain at all.
```

2023-06-05 14:51 UTC, amelie-renard-sonarsource commented on rules/S3923/tsql/rule.adoc
> +This rule does not apply to `IF`/`CASE` chains without `ELSE` clauses.
```suggestion
This rule does not apply to `IF` or `CASE` chains without `ELSE` clauses.
```

2023-06-05 14:51 UTC, amelie-renard-sonarsource commented on rules/S3923/vbnet/rule.adoc
> +Having all branches in a `Select Case` or `If` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `
```suggestion
Having all branches in a `Select Case` or `If` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `Select Case` or `If` chain at all.
```

2023-06-06 14:19 UTC, frederic-tingaud-sonarsource commented on rules/S3923/abap/rule.adoc
>  [source,abap]
done

2023-06-06 14:44 UTC, amelie-renard-sonarsource requested changes

2023-06-06 14:44 UTC, amelie-renard-sonarsource commented on rules/S3923/kotlin/rule.adoc
> +Having all branches in a `when` or `if` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `when`/`
This needs also to be updated

2023-06-06 14:44 UTC, amelie-renard-sonarsource commented on rules/S3923/plsql/rule.adoc
> +Having all branches in a `CASE` or `IF`/`ELSIF` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a
This needs also to be updated

2023-06-06 14:44 UTC, amelie-renard-sonarsource commented on rules/S3923/python/rule.adoc
> +Having the same implementation in every branch of an `if` chain is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be an `if` chain at all.
This needs also to be updated

2023-06-06 14:44 UTC, amelie-renard-sonarsource commented on rules/S3923/ruby/rule.adoc
> +Having all branches in a `case` or `if` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `case` o
This needs also to be updated

2023-06-06 14:44 UTC, amelie-renard-sonarsource commented on rules/S3923/scala/rule.adoc
> +Having all branches in a `match` or `if` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `match`
This needs also to be updated

2023-06-06 14:44 UTC, amelie-renard-sonarsource commented on rules/S3923/tsql/rule.adoc
> +Having all branches in a `CASE`, `IF` or `IIF` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `
This needs also to be updated

2023-06-06 17:33 UTC, frederic-tingaud-sonarsource commented on rules/S3923/abap/rule.adoc
> +Having all branches in a `CASE` or `IF` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `CASE`/`
done

2023-06-06 17:46 UTC, frederic-tingaud-sonarsource commented on rules/S3923/kotlin/rule.adoc
> +Having all branches in a `when` or `if` chain with the same implementation is an error. Either a copy-paste error was made and something different should be executed, or there shouldn't be a `when`/`
Fixed for all, sorry for the noise

2023-06-08 09:04 UTC, amelie-renard-sonarsource approved these changes

2023-06-08 15:06 UTC, merged