Modify rule S2055(Java): Update rule according to the LayC
SonarSource/rspec pull request #2084
Opened 2023-06-06 15:42 UTC by alban-auzeill

2023-06-07 09:20 UTC, leveretka requested changes

2023-06-07 09:20 UTC, leveretka commented on rules/S2055/java/rule.adoc
>  == Why is this an issue?
I think in this section you still haven't explained, why this is an issue. I think it's worth mentioning, what happens if you don't follow this rule. Like that there will be an exception at runtime.

2023-06-07 09:20 UTC, leveretka commented on rules/S2055/java/rule.adoc
> +non-serializable objects, it calls the implicit or explicit no-argument constructor.
I find this section more confusing than the previous description if you don't know what it is about. How about:

"Serializable classes can have non-serializable ancestors, and to initialize fields inherited from such ancestor the no-argument constructor will be invoked. If there's no implicit or explicit no-argument constructor, the error occurs at runtime".

2023-06-08 18:11 UTC, alban-auzeill commented on rules/S2055/java/rule.adoc
> +non-serializable objects, it calls the implicit or explicit no-argument constructor.
@leveretka I have reworked the rule and updated the above screen capture.

2023-06-12 07:38 UTC, leveretka approved these changes
LGTM!

2023-06-12 08:40 UTC, merged