Modify rule S2365: Migrate to new educational format
SonarSource/rspec pull request #2085
Opened 2023-06-06 15:49 UTC by gregory-paidis-sonarsource

https://sonarsource.github.io/rspec/#/rspec/S2365/csharp

2023-06-07 10:56 UTC, csaba-sagi-sonarsource commented on rules/S2365/vbnet/rule.adoc
> +Module SomeModule
NITPICK:
The C# and VB.NET examples are not the same. Here we have a module, while for C# the property is not nested inside a class.

2023-06-07 10:59 UTC, csaba-sagi-sonarsource commented on rules/S2365/vbnet/rule.adoc
> +Most developers expect https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/properties[property] access to be as efficient as https://learn.microsoft.com/en-us/dotnet/visual-basic
Just thinking out loud:
This is why I am not sure it is a good idea to put the links here. We have duplicated the whole text because of the language-specific links + anyway, the links will be in the resources part (some more duplication) + if the links break we will need to fix it in more places (higher maintenance) + do we really need a link here for it? Advanced users will not click them because they know what it is while people with less experience should anyway look at all the resources in the documentation part.

2023-06-07 11:00 UTC, csaba-sagi-sonarsource commented on rules/S2365/rspecator-dotnet.adoc
If I understand it correctly, there is nothing dotnet specific in this file, we can name it just rspecator and if ever a third language comes it can also include it.

2023-06-08 07:37 UTC, gregory-paidis-sonarsource commented on rules/S2365/vbnet/rule.adoc
> +Most developers expect https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/properties[property] access to be as efficient as https://learn.microsoft.com/en-us/dotnet/visual-basic
That's a good point, I removed the links and moved it to `why-dotnet.adoc`

2023-06-08 09:35 UTC, csaba-sagi-sonarsource commented on rules/S2365/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/api/system.array.clone[Array.Clone]
This should also be part of why-dotnet.adoc

2023-06-08 09:37 UTC, csaba-sagi-sonarsource commented on rules/S2365/vbnet/rule.adoc
> +[source,vbnet,diff-id=1,diff-type=noncompliant]
The code snippets are still different, could you please make them identical for c# and vb.net?

2023-06-08 09:38 UTC, csaba-sagi-sonarsource requested changes
I left two small notes, please address. After that it is good to go!

2023-06-08 14:46 UTC, merged