Modify rule S3218: LaYC format
SonarSource/rspec pull request #2089
Opened 2023-06-07 08:49 UTC by cristian-ambrosini-sonarsource

2023-06-07 11:28 UTC, csaba-sagi-sonarsource commented on rules/S3218/csharp/rule.adoc
> +Naming the members of an inner class the same as the static members of its enclosing class is possible but generally considered a bad practice. That's because maintainers may be confused about which
Do we need the `and all references to it should be updated accordingly` part? I mean if one does not update it, the project will not build.

2023-06-07 11:30 UTC, csaba-sagi-sonarsource commented on rules/S3218/csharp/rule.adoc
> +[source,csharp,diff-id=1,diff-type=noncompliant]
The previous state contained 3 examples, where the second was showcasing why the problem exists. I think we lost this educational information by removing it.
I suggest going back to the previous state with 3 snippets.

2023-06-07 11:36 UTC, csaba-sagi-sonarsource commented on rules/S3218/csharp/rule.adoc
> +Naming the members of an inner class the same as the static members of its enclosing class is possible but generally considered a bad practice. That's because maintainers may be confused about which
Thinking out loud, should we do the changes for java too? As the rule was completely common before?

2023-06-07 13:05 UTC, cristian-ambrosini-sonarsource commented on rules/S3218/csharp/rule.adoc
>  ifdef::env-github,rspecator-view[]
Umm.. I think I didn't merge rspecator anywhere except where we had both csharp and vbnet (using `rspecator-dotnet`). That's a good point, I will change it in this PR, but I'm afraid we should go through the rules already merged to check this change. This might also be scripted, it seems common for every rules/languages

2023-06-07 13:13 UTC, cristian-ambrosini-sonarsource commented on rules/S3218/csharp/rule.adoc
> +[source,csharp,diff-id=1,diff-type=noncompliant]
I kept the first two examples, removing the last one because it was redundant with the second snippet. I think it's pretty straightforward and we haven't lost any information. What do you think it's missing?

2023-06-07 13:14 UTC, cristian-ambrosini-sonarsource commented on rules/S3218/csharp/rule.adoc
> +Naming the members of an inner class the same as the static members of its enclosing class is possible but generally considered a bad practice. That's because maintainers may be confused about which
Yep I thought the same; let's see what the team thinks about that (see Slack conversation)

2023-06-07 15:21 UTC, cristian-ambrosini-sonarsource commented on rules/S3218/csharp/rule.adoc
> +Naming the members of an inner class the same as the static members of its enclosing class is possible but generally considered a bad practice. That's because maintainers may be confused about which
The why is now shared with Java.
Using "_inner class_" wording should be valid for each of those languages.
In CSharp _nested_ would be more specific but in Java it means a different thing:
Nested classes are divided into two categories: `non-static` and `static`. `Non-static` nested classes are called **inner classes**. Nested classes that are declared static are called static **nested classes**. Given what the rule is targetting we should be good with a common description using the _inner_ terminology.

2023-06-08 10:46 UTC, csaba-sagi-sonarsource commented on rules/S3218/csharp/rule.adoc
> +[source,csharp,diff-id=1,diff-type=noncompliant]
What I am afraid is that based on these samples, people will only rename the member and from that point the functionality will change as it will return the outer and not the inner. Maybe indeed the intent was to return the inner one. That is why I liked the 3 snippet example that we had.

2023-06-08 10:47 UTC, csaba-sagi-sonarsource commented on rules/S3218/java/rule.adoc
> +[source,text]
And also I would not change the snippets for java at all. Let them do that part. That way we improved the rule in a non invasive way.

2023-06-08 10:47 UTC, csaba-sagi-sonarsource requested changes
One more round of comments.

2023-06-08 14:36 UTC, csaba-sagi-sonarsource commented on rules/S3218/java/rule.adoc
> +[source,text]
You cannot have diff-id=1,diff-type=compliant for two snippets, it will not work like that.
https://sonarsource.slack.com/archives/C04P0SB2KJP/p1686150697710199
Please fix it.

2023-06-08 14:36 UTC, csaba-sagi-sonarsource requested changes
One last round. I promise!

2023-06-09 09:04 UTC, csaba-sagi-sonarsource commented on rules/S3218/rspecator.adoc
> +include::./message.adoc[]
NITPICK:
The message and the comments and links can be embedded directly and the files removed.

2023-06-09 09:33 UTC, merged