Modify rule S1163: LaYC format
SonarSource/rspec pull request #2091
Opened 2023-06-07 12:31 UTC by cristian-ambrosini-sonarsource

2023-06-09 10:06 UTC, antonioaversa commented
@cristian-ambrosini-sonarsource : labels to be applied, for all relevant languages

2023-06-09 11:52 UTC, antonioaversa requested changes

2023-06-09 13:37 UTC, cristian-ambrosini-sonarsource commented on rules/S1163/rspecator.adoc
> +include::./message.adoc[]
I decided to embed directly the content in the rspecator

2023-06-09 13:38 UTC, cristian-ambrosini-sonarsource commented on rules/S1163/rspecator.adoc
> +include::./comments-and-links.adoc[]
I decided to embed directly the content in the rspecator

2023-06-12 07:22 UTC, antonioaversa approved these changes
LGTM!

2023-06-12 07:23 UTC, merged