Modify rule S1186: LaYC format
SonarSource/rspec pull request #2095
Opened 2023-06-07 13:26 UTC by sebastien-marichal

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone

2023-06-07 15:11 UTC, antonioaversa approved these changes
LGTM
Some minor suggestions

2023-06-07 15:11 UTC, antonioaversa commented on rules/S1186/vb6/notsupported-code.adoc
> +Raising an error specifying the method is not yet implemented provides the initial intention to add an implementation in the future.
There are actually "methods" in VB6, but they are procedures within files which are instantiated with special syntax.

The examples actually show procedures:
- sub procedures
- function procedures
- property procedures

[Reference](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/aa242125(v=vs.60))
[Reference](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/aa262302(v=vs.60)#using-object-variables)

2023-06-07 15:11 UTC, antonioaversa approved these changes
LGTM
Some minor suggestions

2023-06-07 15:33 UTC, sebastien-marichal commented on rules/S1186/comments-and-links.adoc
> +=== on 07 June 2023, 14:45:00 Sebastien Marichal wrote:
Removed it since, there is ticket for the languages

2023-06-07 15:45 UTC, sebastien-marichal commented on rules/S1186/why-dotnet.adoc
> +Such methods must be avoided and removed.
I had the same thought, and since there was already an `Exception` section, I figured I should try to treat those scenarios as compliant solutions rather than exceptions.

2023-06-07 15:54 UTC, sebastien-marichal commented on rules/S1186/vb6/rule.adoc
> +:operationName: procedure
@antonioaversa this is my attempt to have `procedure` in the description instead of `method`.
WDYT?

2023-06-08 14:42 UTC, antonioaversa requested changes
Mostly suggestion on sentence structure and passive sentences.

2023-06-08 14:42 UTC, antonioaversa commented on rules/S1186/csharp/notsupported-code.adoc
> +By throwing the https://learn.microsoft.com/en-us/dotnet/api/system.notsupportedexception[`NotSupportedException`], it makes clear the initial intention not to implement it in the future.
Active form:
`You can make clear the initial intention not to implement the method in the future by throwing...`

2023-06-08 14:42 UTC, antonioaversa commented on rules/S1186/why-dotnet.adoc
> +However, there are some cases where a {operationName} needs to be empty without logic. In those cases, it is essential to minimize confusion and enhance clarity.
without logic -> without any logic.
However, I would just remove it: if the method is empty, it is also without any logic in it.

2023-06-08 14:42 UTC, antonioaversa commented on rules/S1186/why-dotnet.adoc
> +* The {operationName} implementation will never be done.
This is more a personal opinion, it's optional and more a suggestion for the future: I would try to use less the verb "do", when a verb (to implement) for the object (implementation) exists:
```
The {operationName} will never be implemented.
``` 
It looks simpler and more direct to me.

2023-06-08 15:36 UTC, sebastien-marichal commented on rules/S1186/csharp/rule.adoc
> +* empty `virtual` methods as the implementation might not be required in the base class
I think `MustOverride` should be removed then, from my understanding it is the same as `abstract`.

2023-06-09 11:57 UTC, antonioaversa commented on rules/S1186/comments-and-links.adoc
> +=== on 07 June 2023, 14:45:00 Sebastien Marichal wrote:
If by "tickets" you mean "labels": they are only visible in the PR, not on the UI of RSPEC.
If you open the RSPEC and you don't see a tab for language X, despite the rule being implementable for language X, you may wonder if the empty implementation was removed by mistake, because the person migrating to the new format hasn't found the right JIRA issue or hasn't looked into the right JIRA project while searching for an upcoming implementation of the rule for language X.
So I would re-add the message.

2023-06-09 12:39 UTC, antonioaversa approved these changes
LGTM!
Non blocking remark: https://github.com/SonarSource/rspec/pull/2095#discussion_r1224211331

2023-06-09 12:51 UTC, sebastien-marichal commented on rules/S1186/comments-and-links.adoc
> +=== on 07 June 2023, 14:45:00 Sebastien Marichal wrote:
I found open implementation tickets in Jira, which is why I revert those changes.

2023-06-09 12:51 UTC, merged