Modify S4423: Migrate it to the Learn-As-You-Code
SonarSource/rspec pull request #2097
Opened 2023-06-07 13:49 UTC by loris-s-sonarsource

2023-06-09 15:29 UTC, loris-s-sonarsource commented on rules/S4423/common/fix/fix.adoc
> +
when encrypting data, remember that secrets should not be stored in code.

2023-06-14 08:19 UTC, loris-s-sonarsource commented on rules/S4423/rationale.adoc
> +https://datatracker.ietf.org/doc/html/rfc8996[March 2021].
```suggestion
When these unsecured protocols are used, it is best practice to expect a breach:
that a user or organization with malicious intent will perform mathematical
attacks on this data after obtaining it by other means.
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource requested changes
See the comments for details.

Many of the rules include a common highlighting and message file. For the messages, it can make sense in some cases, but the highlighting information is usually very language-specific. So I would recommend not having a common highlighting file but instead, keeping language-specific files for the languages that had this information before in the rule.adoc. If there are no highlighting information, just remove that section for the language. Makes more sense than having highlighting information that do not apply.

For the message, I would include a local message.adoc if it exists (and migrate the custom message information from the rule.adoc to such a language-specific file) and otherwise include the common message.adoc.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/azureresourcemanager/how-to-fix-it/azure-mysql.adoc
> +== How to fix it in Azure MySQL
I am not convinced if it makes sense to have "Azure" as part of the framework name since Azure Resource Manager is Azure-only.

I am also not convinced that "MySQL" is a good name since this rule is also about PostgreSQL and MariaDB.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/azureresourcemanager/how-to-fix-it/azure-storage-account.adoc
> +== How to fix it in Azure Storage Accounts
Same thing regarding "Azure" and Azure Resource Manager.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/azureresourcemanager/how-to-fix-it/azure-mysql.adoc
> +[source,json,diff-id=1,diff-type=noncompliant]
```suggestion
[source,json,diff-id=1,diff-type=compliant]
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/azureresourcemanager/how-to-fix-it/azure-storage-account.adoc
> +[source,json,diff-id=1,diff-type=noncompliant]
```suggestion
[source,json,diff-id=1,diff-type=compliant]
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/azureresourcemanager/rule.adoc
> +include::../highlighting.adoc[]
I don't think a shared highlighting file makes sense here.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/cloudformation/rule.adoc
> +include::../highlighting.adoc[]
I don't think a shared highlighting file makes sense here.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/csharp/how-to-fix-it/dotnet.adoc
> +== How to fix it in .Net
```suggestion
== How to fix it in .NET
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/vbnet/how-to-fix-it/dotnet.adoc
> +== How to fix it in .Net
```suggestion
== How to fix it in .NET
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/cloudformation/how-to-fix-it/api-gateway.adoc
> +== How to fix it in AWS API Gateways
```suggestion
== How to fix it in API Gateway
```

Cloudformation is AWS specific, so I don't think AWS should be part of the framework name. Since it is a name, I would write singular here.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/cloudformation/how-to-fix-it/opensearch.adoc
> +== How to fix it in AWS OpenSearch
```suggestion
== How to fix it in OpenSearch
```

Cloudformation is AWS specific, so I don't think AWS should be part of the framework name.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/cloudformation/how-to-fix-it/opensearch.adoc
> +[source,cloudformation,diff-id=1,diff-type=noncompliant]
```suggestion
[source,cloudformation,diff-id=1,diff-type=compliant]
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/cloudformation/rule.adoc
> +include::../message.adoc[]
The shared messages do not contain the right information. I think this should stay language specific.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/csharp/how-to-fix-it/dotnet.adoc
> +algorithm: TLSv1.0.
```suggestion
These samples use TLSv1.0 as the default TLS algorithm, which is cryptographically weak.
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/docker/how-to-fix-it/curl.adoc
> +== How to fix it in Curl
```suggestion
== How to fix it in cURL
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/java/how-to-fix-it/okhttp.adoc
> +          .tlsVersions(TlsVersion.TLS_1_1)                // Noncompliant
That seems like a rather unconventional indentation for the comment here (aligning it to the level of the constructor).

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/java/rule.adoc
> +include::../common/resources/standards.adoc[]
Might need a newline here, not sure.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/javascript/how-to-fix-it/aws-api-gateway.adoc
> +[source,javascript,diff-id=1,diff-type=noncompliant]
```suggestion
[source,javascript,diff-id=1,diff-type=compliant]
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/javascript/how-to-fix-it/aws-open-search.adoc
> +== How to fix it in AWS OpenSearch
I think "CDK" or "AWS CDK" would fit the definition of framework here better than "OpenSearch".

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/kotlin/how-to-fix-it/okhttp.adoc
> +
```suggestion
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/kotlin/how-to-fix-it/okhttp.adoc
> +          .tlsVersions(TlsVersion.TLS_1_1)                // Noncompliant
I also find this indentation unconventional.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/kotlin/rule.adoc
> +include::../common/resources/standards.adoc[]
Might need a newline here.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/php/how-to-fix-it/core.adoc
> +[source,php,diff-id=1,diff-type=noncompliant]
```suggestion
[source,php,diff-id=1,diff-type=compliant]
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/python/how-to-fix-it/aws-api-gateway.adoc
> +[source,python,diff-id=1,diff-type=noncompliant]
```suggestion
[source,python,diff-id=1,diff-type=compliant]
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/python/how-to-fix-it/aws-api-gateway.adoc
> +== How to fix it in AWS API Gateways
Same thing as for Javascript, I think the framework should rather be "CDK" or "AWS CDK". Defining a class of a library as the framework is too detailed in my opinion.

It would be still very  clear, even if API Gateway and OpenSearch are in the same tab.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/python/how-to-fix-it/aws-api-gateway.adoc
> +
```suggestion
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/python/how-to-fix-it/aws-open-search.adoc
> +
```suggestion
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/python/how-to-fix-it/aws-open-search.adoc
> +[source,python,diff-id=1,diff-type=noncompliant]
```suggestion
[source,python,diff-id=1,diff-type=compliant]
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/python/how-to-fix-it/openssl.adoc
> +[source,python,diff-id=1,diff-type=noncompliant]
```suggestion
[source,python,diff-id=1,diff-type=compliant]
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/python/how-to-fix-it/ssl.adoc
> +[source,python,diff-id=1,diff-type=noncompliant]
```suggestion
[source,python,diff-id=1,diff-type=compliant]
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/python/rule.adoc
> +include::../message.adoc[]
The shared messages do not contain the right information. I think this should stay language specific.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/rationale.adoc
> +Encryption algorithms are essential for protecting sensitive information and
This file is the same (or very similar) as the file in the other PR that I already reviewed. It would be great if you could apply the same things here, so I don't have to write everything twice. For example, the dots at the end of the list entries.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/summary.adoc
> +This vulnerability exposes encrypted data to an unnecessarily large number of
As mentioned in the other PR, I think "unnecessarily large" is not very precise, as it would be already enough if it exposes the data to one attack.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/terraform/how-to-fix-it/aws-api-gateway.adoc
> +== How to fix it in AWS API Gateways
```suggestion
== How to fix it in AWS API Gateway
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/terraform/how-to-fix-it/gcp-lb.adoc
> +[source,terraform,diff-id=1,diff-type=noncompliant]
```suggestion
[source,terraform,diff-id=1,diff-type=compliant]
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/terraform/rule.adoc
> +include::../highlighting.adoc[]
Same comment as before, I don't think the shared highlighting file makes sense here.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/cfamily/how-to-fix-it/curl.adoc
> +== How to fix it in Curl
```suggestion
== How to fix it in cURL 
```

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/cfamily/how-to-fix-it/curl.adoc
> +cryptographical algorithms (TLSv1.0 and LTSv1.1).
As per styling guide, I think it would be nice to incorporate TLSv1.0 and LTSv1.1 directly into the sentence instead of having them in parentheses. There was a similar sentence before where I left an example.

2023-06-14 14:59 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/docker/how-to-fix-it/curl.adoc
> +
The Docker samples have no code rationale, unlike the other languages.

2023-06-16 16:51 UTC, loris-s-sonarsource commented on rules/S4423/cloudformation/how-to-fix-it/api-gateway.adoc
> +== How to fix it in AWS API Gateways
```suggestion
== How to fix it in API Gateways
```

2023-06-19 14:19 UTC, loris-s-sonarsource commented on rules/S4423/azureresourcemanager/rule.adoc
> +include::../message.adoc[]
```suggestion
=== Message
* If `minimumTlsVersion`/`minimalTlsVersion` is specified but has the wrong value
** Change this code to disable support of older TLS versions.
* If `minimumTlsVersion`/`minimalTlsVersion` is not specified at all
** Set `minimumTlsVersion`/`minimalTlsVersion` to disable support of older TLS versions.

=== Highlighting
* Highlight `minimumTlsVersion`/`minimalTlsVersion` if it is specified but has the wrong value
* Highlight resource if `minimumTlsVersion`/`minimalTlsVersion` is not specified at all
```

2023-06-19 14:19 UTC, loris-s-sonarsource commented on rules/S4423/cloudformation/rule.adoc
```suggestion

=== Message

For `AWS::Elasticsearch::Domain` and `AWS::OpenSearchService::Domain`:

* If `TLSSecurityPolicy` is specified but has the wrong value
** Change this code to disable support of older TLS versions.
* If `DomainEndpointOptions` is specified but does not contain `TLSSecurityPolicy`
** Set "TLSSecurityPolicy" to disable support of older TLS versions.
* If `DomainEndpointOptions` is not specified at all
** Set "DomainEndpointOptions.TLSSecurityPolicy" to disable support of older TLS versions.

For `AWS::ApiGateway::DomainName`:

 * If `SecurityPolicy` is specified but has the wrong value
** Change this code to disable support of older TLS versions.
 * If `SecurityPolicy` is not specified at all
 ** Set "SecurityPolicy" to disable support of older TLS versions.

For `AWS::ApiGatewayV2::DomainName`:

 * If `SecurityPolicy` is specified but has the wrong value
 ** Change this code to disable support of older TLS versions.
 * If `DomainNameConfigurations` exists but `SecurityPolicy` is not specified
** Set "SecurityPolicy" to disable support of older TLS versions.
 * If `DomainNameConfigurations` does not exist
** Set "DomainNameConfigurations.SecurityPolicy" to disable support of older TLS versions.


=== Highlighting


For `AWS::Elasticsearch::Domain` and `AWS::OpenSearchService::Domain`:

* Highlight `TLSSecurityPolicy` if it is specified but has the wrong value
* Highlight `DomainEndpointOptions` if it is specified but does not contain `TLSSecurityPolicy`
* Highlight resource if `DomainEndpointOptions` is not specified at all

For `AWS::ApiGateway::DomainName`:

 * Highlight `SecurityPolicy` if it is specified but has the wrong value
 * Highlight resource if `SecurityPolicy` is not specified at all

For `AWS::ApiGatewayV2::DomainName`:

 * Highlight `SecurityPolicy` if it is specified but has the wrong value
 * Highlight `DomainNameConfigurations` if it exists but `SecurityPolicy` is not specified
 * Highlight resource if `DomainNameConfigurations` does not exist

```

2023-06-19 14:19 UTC, loris-s-sonarsource commented on rules/S4423/docker/rule.adoc
> +include::../message.adoc[]
```suggestion
=== Message

Change this code to enforce TLS 1.2 or above.
```

2023-06-19 14:19 UTC, loris-s-sonarsource commented on rules/S4423/javascript/rule.adoc
> +include::../message.adoc[]
```suggestion
=== Message

==== OpenSSL and ssl modules

Change this code to use a stronger protocol.

==== AWS APIGateway

Change this code to enforce TLS 1.2 or above.

==== AWS OpenSearch / Elasticsearch

Omitting "tlsSecurityPolicy" enables a deprecated version of TLS. Set it to
enforce TLS 1.2 or above.

```

2023-06-19 14:19 UTC, loris-s-sonarsource commented on rules/S4423/python/rule.adoc
```suggestion
=== Message

==== OpenSSL and ssl modules

When the system default is used:

> Change this code to explicitly enforce TLSv1.2 or above.

In all other cases:

> Change this code to enforce TLS 1.2 or above.

==== AWS APIGateway

Change this code to enforce TLS 1.2 or above.

==== AWS OpenSearch / Elasticsearch

Omitting "tls_security_policy" enables a deprecated version of TLS. Set it to enforce TLS 1.2 or above.
Change this code to enforce TLS 1.2 or above.

```

2023-06-19 14:19 UTC, loris-s-sonarsource commented on rules/S4423/terraform/rule.adoc
> +include::../message.adoc[]
```suggestion
=== Message

==== AWS

For `aws_elasticsearch_domain`:

* If `tls_security_policy` is specified but has the wrong value
** Change this code to disable support of older TLS versions.
* If `domain_endpoint_options` is specified but does not contain `tls_security_policy`
** Set "tls_security_policy" to disable support of older TLS versions.
* If resource if `domain_endpoint_options` is not specified at all
** Set "domain_endpoint_options.tls_security_policy" to disable support of older TLS versions.

For `aws_api_gateway_domain_name`:

* If `security_policy` is specified but has the wrong value
** Change this code to disable support of older TLS versions.
* If resource if `security_policy` is not specified at all
** Set "security_policy" to disable support of older TLS versions.

For `aws_apigatewayv2_domain_name`:

* If `security_policy` is specified but has the wrong value
** Change this code to disable support of older TLS versions.
* If `domain_name_configuration` is specified but does not contain `security_policy`
** Set "security_policy" to disable support of older TLS versions.
* If resource if `domain_name_configuration` is not specified at all
** Set "domain_name_configuration.security_policy" to disable support of older TLS versions.

==== GCP

For `google_compute_ssl_policy`:

* If `min_tls_version` is specified but has the wrong value
** Change this code to disable support of older TLS versions.

* If `min_tls_version` is not specified at all
** Set "min_tls_version" to disable support of older TLS versions.


=== Highlighting

==== AWS

For `aws_elasticsearch_domain`:

* Highlight `tls_security_policy` if it is specified but has the wrong value
* Highlight `domain_endpoint_options` if it is specified but does not contain `tls_security_policy`
* Highlight resource if `domain_endpoint_options` is not specified at all

For `aws_api_gateway_domain_name`:

* Highlight `security_policy` if it is specified but has the wrong value
* Highlight resource if `security_policy` is not specified at all

For `aws_apigatewayv2_domain_name`:

* Highlight `security_policy` if it is specified but has the wrong value
* Highlight `domain_name_configuration` if it is specified but does not contain `security_policy`
* Highlight resource if `domain_name_configuration` is not specified at all

==== GCP

For `google_compute_ssl_policy`:

* Highlight `min_tls_version` if it is specified but has the wrong value
* Highlight resource if `min_tls_version` is not specified at all

```

2023-06-19 14:21 UTC, loris-s-sonarsource commented on rules/S4423/rationale.adoc
> +the cryptography community.
```suggestion
Encryption algorithms are essential for protecting sensitive information and
ensuring secure communications in a variety of domains. They are used for
several important reasons:

* Confidentiality, privacy, and intellectual property protection
* Security during transmission or on storage devices
* Data integrity, general trust, and authentication

When selecting encryption algorithms, tools, or combinations, you should also
consider two things:

1. No encryption is unbreakable.
2. The strength of an encryption algorithm is usually measured by the effort required to crack it within a reasonable time frame.
For these reasons, as soon as cryptography is included in a project, it is
important to choose encryption algorithms that are considered strong and secure
by the cryptography community.
```

2023-06-19 14:21 UTC, loris-s-sonarsource commented on rules/S4423/rationale.adoc
> +* TLS versions 1.0 and 1.1.
```suggestion
* SSL versions 1.0, 2.0 and 3.0
* TLS versions 1.0 and 1.1
```

2023-06-19 14:22 UTC, loris-s-sonarsource commented on rules/S4423/summary.adoc
> +attacks whose goal is to recover the plaintext.
```suggestion
This vulnerability exposes encrypted data to a number of
attacks whose goal is to recover the plaintext.
```

2023-06-19 15:42 UTC, loris-s-sonarsource commented on rules/S4423/python/how-to-fix-it/aws-api-gateway.adoc
> +== How to fix it in AWS API Gateways
```suggestion
== How to fix it in AWS CDK
```

2023-06-19 15:42 UTC, loris-s-sonarsource commented on rules/S4423/python/how-to-fix-it/aws-api-gateway.adoc
> +----
```suggestion
----

By default, AWS's OpenSearch service `CfnDomains` enables TLS 1.0, a weak
cryptographic algorithm.

[source,python,diff-id=1,diff-type=noncompliant]
----
from aws_cdk.aws_opensearchservice import CfnDomain, EngineVersion

class ExampleStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        CfnDomain(self, "example",
            version=EngineVersion.OPENSEARCH_1_3
        ) # Noncompliant
----
```

2023-06-19 15:42 UTC, loris-s-sonarsource commented on rules/S4423/python/how-to-fix-it/aws-api-gateway.adoc
> +
```suggestion

[source,python,diff-id=1,diff-type=compliant]
----
from aws_cdk.aws_opensearchservice import CfnDomain, EngineVersion
class ExampleStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)
        CfnDomain(self, "example",
            version=EngineVersion.OPENSEARCH_1_3
            domain_endpoint_options=CfnDomain.DomainEndpointOptionsProperty(
                tls_security_policy="Policy-Min-TLS-1-2-2019-07"
            )
        )
----
```

2023-06-19 15:42 UTC, loris-s-sonarsource commented on rules/S4423/rationale.adoc
> +2. The strength of an encryption algorithm is usually measured by the effort required to crack it within a reasonable time frame.
```suggestion
2. The strength of an encryption algorithm is usually measured by the effort required to crack it within a reasonable time frame.

```

2023-06-19 15:42 UTC, loris-s-sonarsource commented on docs/header_names/allowed_framework_names.adoc
> +* API Gateways
```suggestion
* API Gateway
```

2023-06-19 15:42 UTC, loris-s-sonarsource commented on docs/header_names/allowed_framework_names.adoc
> +* AWS API Gateways
```suggestion
* AWS API Gateway
```

2023-06-19 15:42 UTC, loris-s-sonarsource commented on rules/S4423/kotlin/how-to-fix-it/java-cryptographic-extension.adoc
> +
```suggestion
```

2023-06-19 15:42 UTC, loris-s-sonarsource commented on rules/S4423/javascript/how-to-fix-it/aws-open-search.adoc
> +
```suggestion

[source,javascript,diff-id=1,diff-type=compliant]
----
import { aws_apigateway as agw } from 'aws-cdk-lib';
new agw.DomainName(this, 'Example', {
    certificate: certificate,
    domainName: domainName,
    securityPolicy: agw.SecurityPolicy.TLS_1_2,
});
----
```

2023-06-19 15:43 UTC, loris-s-sonarsource commented on docs/header_names/allowed_framework_names.adoc
> +* AWS OpenSearch
```suggestion
* AWS OpenSearch
// CDK
* AWS CDK
```

2023-06-19 15:44 UTC, loris-s-sonarsource commented on rules/S4423/rationale.adoc
> +Encryption algorithms are essential for protecting sensitive information and
done

2023-06-19 15:46 UTC, loris-s-sonarsource commented on rules/S4423/javascript/how-to-fix-it/aws-open-search.adoc
> +[source,javascript,diff-id=1,diff-type=noncompliant]
```suggestion
[source,javascript,diff-id=2,diff-type=noncompliant]
```

2023-06-19 15:46 UTC, loris-s-sonarsource commented on rules/S4423/javascript/how-to-fix-it/aws-open-search.adoc
> +[source,javascript,diff-id=1,diff-type=compliant]
```suggestion
[source,javascript,diff-id=2,diff-type=compliant]
```

2023-06-19 15:46 UTC, loris-s-sonarsource commented on rules/S4423/python/how-to-fix-it/aws-api-gateway.adoc
> +[source,python,diff-id=1,diff-type=noncompliant]
```suggestion
[source,python,diff-id=2,diff-type=noncompliant]
```

2023-06-19 15:46 UTC, loris-s-sonarsource commented on rules/S4423/python/how-to-fix-it/aws-api-gateway.adoc
> +[source,python,diff-id=1,diff-type=compliant]
```suggestion
[source,python,diff-id=2,diff-type=compliant]
```

2023-06-19 15:47 UTC, loris-s-sonarsource commented on rules/S4423/python/how-to-fix-it/aws-api-gateway.adoc
> +[source,python,diff-id=1,diff-type=compliant]
```suggestion
[source,python,diff-id=2,diff-type=compliant]
```

2023-06-20 07:19 UTC, hendrik-buchwald-sonarsource requested changes
`validate_asciidoc` is still failing.

2023-06-20 09:12 UTC, hendrik-buchwald-sonarsource requested changes
I missed something before that was changed in the other PR.

2023-06-20 09:12 UTC, hendrik-buchwald-sonarsource commented on rules/S4423/impact.adoc
> +After retrieving encrypted data and performing mathematical attacks on it on a
In the other PR you applied some feedback to this text (like the mathematical attacks), it would be good to apply it here as well.

2023-06-20 10:11 UTC, loris-s-sonarsource commented on rules/S4423/impact.adoc
> +infrastructure.
```suggestion
=== What is the potential impact?
After retrieving encrypted data and performing cryptographic attacks on it on a
given timeframe, attackers can recover the plaintext that encryption was
supposed to protect.

Depending on the recovered data, the impact may vary.

Below are some real-world scenarios that illustrate the potential impact of an
attacker exploiting the vulnerability.

==== Additional attack surface
By modifying the plaintext of the encrypted message, an attacker may be able to
trigger additional vulnerabilities in the code. An attacker can further exploit
a system to obtain more information. +
Encrypted values are often considered trustworthy because it would not be
possible for a third party to modify them under normal circumstances.

==== Breach of confidentiality and privacy
When encrypted data contains personal or sensitive information, its retrieval
by an attacker can lead to privacy violations, identity theft, financial loss,
reputational damage, or unauthorized access to confidential systems.

In this scenario, the company, its employees, users, and partners could be
seriously affected.

The impact is twofold, as data breaches and exposure of encrypted data can
undermine trust in the organization, as customers, clients and stakeholders may
lose confidence in the organization's ability to protect their sensitive data.

==== Legal and compliance issues
In many industries and locations, there are legal and compliance requirements
to protect sensitive data. If encrypted data is compromised and the plaintext
can be recovered, companies face legal consequences, penalties, or violations
of privacy laws.
```

2023-06-20 15:03 UTC, hendrik-buchwald-sonarsource approved these changes
LGTM! A small typo left in the comments.

2023-06-20 15:36 UTC, merged