Modify rule S3451: LaYC format
SonarSource/rspec pull request #2104
Opened 2023-06-07 15:46 UTC by antonioaversa

Description:
Adapts the [rule](https://sonarsource.github.io/rspec/#/rspec/S3451) to LaYC format level 2, for csharp.

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone

2023-06-08 08:51 UTC, cristian-ambrosini-sonarsource requested changes
Looks good! Left a couple of suggestions

2023-06-08 08:51 UTC, cristian-ambrosini-sonarsource commented on rules/S3451/csharp/rule.adoc
> +The https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.defaultvalueattribute[DefaultValue] attribute from the `System.ComponentModel` namespace, is sometimes used to declare a member'
```suggestion
The https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.defaultvalueattribute[DefaultValue] attribute from the `System.ComponentModel` namespace, is sometimes used to declare a member's default value. This can be used for instance by the reset feature of a visual designer or by a code generator.
```

2023-06-09 07:21 UTC, antonioaversa commented on rules/S3451/csharp/rule.adoc
> +The use of `[DefaultValue]` with `[Optional]` has no more effect than `[Optional]` alone. That's because `[DefaultValue]` doesn't actually do anything; it merely indicates the intent for the value.
I agree, I have restructured the section to have a first paragraph which is more to the point.

2023-06-09 12:36 UTC, cristian-ambrosini-sonarsource approved these changes
LGTM!

2023-06-09 12:36 UTC, cristian-ambrosini-sonarsource commented on rules/S3451/csharp/rule.adoc
> +https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.defaultvalueattribute[DefaultValue] does not make the compiler set the default value, as its name may seems to suggest. What you pro
Isn't it `its name may seem to suggest`?
Otherwise you can also skip it entirely, wdyt
```suggestion
https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.defaultvalueattribute[DefaultValue] does not make the compiler set the default value, as its name may suggest. What you probably wanted to use is https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.defaultparametervalueattribute[DefaultParameterValue]. 
```

2023-06-12 07:25 UTC, merged