Modify rule S927: LaYC format
SonarSource/rspec pull request #2114
Opened 2023-06-08 12:46 UTC by sebastien-marichal

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone

2023-06-08 14:47 UTC, cristian-ambrosini-sonarsource requested changes
Good! I left a couple of comments

2023-06-08 14:47 UTC, cristian-ambrosini-sonarsource commented on rules/S927/csharp/metadata.json
>  {
Are there any open tickets in order to implement this rule for:
- Cfamily
- Java
- Javascript
? If not you can remove all of them

2023-06-08 14:47 UTC, cristian-ambrosini-sonarsource commented on rules/S927/csharp/rule.adoc
>  I've changed the sample code.
You can create a common `rspecator.adoc` file for both vbnet and csharp

2023-06-08 14:47 UTC, cristian-ambrosini-sonarsource commented on rules/S927/vbnet/rule.adoc
> +To avoid any ambiguity in the code, parameters' names should match the initial declaration, whether its initial declaration is from an interface or a base class.
Educational: aren't partial methods a thing also in vbnet?

2023-06-08 14:57 UTC, sebastien-marichal commented on rules/S927/vbnet/rule.adoc
> +To avoid any ambiguity in the code, parameters' names should match the initial declaration, whether its initial declaration is from an interface or a base class.
I missed that will update it accordingly, thanks!

2023-06-09 09:00 UTC, cristian-ambrosini-sonarsource requested changes
Last round

2023-06-09 14:17 UTC, merged