modify_S2639_layc
SonarSource/rspec pull request #2122
Opened 2023-06-09 08:19 UTC by cynthiabethea

Made some updates to rule text for Java, Javascript, and the general description for the other languages.

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone

2023-06-09 11:59 UTC, vilchik-elena requested changes
The top level description is not used anywhere, currently it holds only super-java-specific content. I suggest to drop the top level description

2023-06-09 11:59 UTC, vilchik-elena commented on rules/S2639/javascript/rule.adoc
> +It is likely the regular expression does not work as you intended. It's good practice to avoid using empty character classes in regular expressions, as they do not serve any useful purpose in pattern
This is a bug-detection rule, so I think saying `good practice` is not appropriate

2023-06-09 11:59 UTC, vilchik-elena commented on rules/S2639/java/rule.adoc
>  == Why is this an issue?
Remove `=== Noncompliant code example`

2023-06-09 11:59 UTC, vilchik-elena commented on rules/S2639/javascript/rule.adoc
>  === Noncompliant code example
Drop this title

2023-06-12 15:51 UTC, cynthiabethea commented on rules/S2639/rule.adoc
@vilchik-elena  I noticed this rule is on the list Fred posted, this adoc file refers to languages it was never implemented in, so I am skipping any more changes to this file and just do the changes to the Java/Javascript versions of the rules

2023-06-13 13:47 UTC, vilchik-elena requested changes
Looks good for JS (just one typo).
I suggest reverting Java as clearly more work is required to clarify all the cases. (or you can open a separate PR and pass it to JVM squad to finish)

2023-06-13 13:47 UTC, vilchik-elena commented on rules/S2639/java/rule.adoc
> +``|`` is the OR operator.  When you use ``|`` as a stand-alone, it matches the space between characters. To use it as a literal character in a regular expression, it needs to be escaped with a backsl
```suggestion
* ``|`` is the OR operator.  When you use ``|`` as a stand-alone, it matches the space between characters. To use it as a literal character in a regular expression, it needs to be escaped with a backslash ``\|``.
```

2023-06-13 13:47 UTC, vilchik-elena commented on rules/S2639/java/rule.adoc
>  String clean4 = str.replaceFirst(".",""); // Noncompliant;
```suggestion
String clean2 = str.replaceFirst(".",""); // Noncompliant;
```

2023-06-13 13:47 UTC, vilchik-elena commented on rules/S2639/java/rule.adoc
>  String clean5 = str.replaceFirst("|","_"); // Noncompliant;
```suggestion
String clean = str.replaceAll("|","_"); // Noncompliant; yields _/_F_i_l_e_|_N_a_m_e_._t_x_t_
String clean2 = str.replaceFirst("|","_"); // Noncompliant; 
```

2023-06-13 13:47 UTC, vilchik-elena commented on rules/S2639/java/rule.adoc
> +* When you use ``.`` in ``replaceAll`` it matches _everything_.
```suggestion
When you use ``.`` in ``replaceAll`` it matches _everything_.
```

2023-06-13 13:47 UTC, vilchik-elena commented on rules/S2639/java/rule.adoc
> +* When you use ``.`` in ``replaceAll`` it matches _everything_.
`replaceAll` just an example in fact, there are many other functions that take regex as parameter.

2023-06-13 13:47 UTC, vilchik-elena commented on rules/S2639/javascript/rule.adoc
> +- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions[MDN web docs: Regular exporessions]
```suggestion
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions[MDN web docs: Regular expressions]
```

2023-06-13 13:47 UTC, vilchik-elena commented on rules/S2639/java/rule.adoc
>  String clean6 = str.replaceFirst(File.separator,""); // Noncompliant;
```suggestion
String clean = str.replaceAll(File.separator, ""); // Noncompliant; exception on Windows
String clean2 = str.replaceFirst(File.separator, ""); // Noncompliant;
```

2023-06-13 13:47 UTC, vilchik-elena commented on rules/S2639/java/rule.adoc
> +When you use ``File.separator``, it matches the platform-specific file path delimiter. On Windows, this will be taken as an escape character.
I am not sure what "escape character" is. Are you?

2023-06-14 12:18 UTC, vilchik-elena approved these changes

2023-06-14 12:18 UTC, vilchik-elena commented
@cynthiabethea could you fix the PR title and merge?

2023-06-15 14:56 UTC, merged