Modify rule S107: LaYC format
SonarSource/rspec pull request #2130
Opened 2023-06-09 11:34 UTC by amelie-renard-sonarsource

2023-06-12 12:54 UTC, hendrik-buchwald-sonarsource reviewed
As requested, some comments about PHP.

2023-06-12 12:54 UTC, hendrik-buchwald-sonarsource commented on rules/S107/php/split-example.adoc
> +[source,cpp]
```suggestion
[source,php]
```

2023-06-12 12:54 UTC, hendrik-buchwald-sonarsource commented on rules/S107/php/noncompliant.adoc
> +{
```suggestion
function setCoordinates($x1, $y1, $z1, $x2, $y2, $z2) { // Noncompliant
```

Not required but this keeps it in the same style.

2023-06-12 12:54 UTC, hendrik-buchwald-sonarsource commented on rules/S107/php/struct-example.adoc
> +function setCoordinates($p1, $p2) {
```suggestion
function setCoordinates(Point $p1, Point $p2) {
```

This way it is clear that the arguments represent an object of that type.

2023-06-12 12:54 UTC, hendrik-buchwald-sonarsource commented on rules/S107/php/struct-example.adoc
> +}
```suggestion
class Point
{
    // In geometry, Point is a logical structure to group data
    public function __construct(
        public int $x,
        public int $y,
        public int $z
    ) {}
}
```

The code is correct but not recommendable. I have included a short PHP 8 version.

2023-06-12 12:54 UTC, hendrik-buchwald-sonarsource commented on rules/S107/php/split-example.adoc
> +function setOrigin($x, $y, $z) {
```suggestion
function setOrigin(int $x, int $y, int $z) {
```

Not required but in my opinion we should lead with good example in the samples.

2023-06-12 12:54 UTC, hendrik-buchwald-sonarsource commented on rules/S107/php/split-example.adoc
> +function setSize($width, $height, $depth) {
```suggestion
function setSize(int $width, int $height, float $depth) {
```

Not required but in my opinion we should lead with good example in the samples.

2023-06-12 12:56 UTC, hendrik-buchwald-sonarsource reviewed
As requested, some comments about PHP.

2023-06-12 13:04 UTC, amelie-renard-sonarsource commented
Perfect, thanks @hendrik-buchwald-sonarsource !

2023-06-12 14:59 UTC, guillaume-dequenne-sonarsource reviewed
Left a few comments related to the Python version of the rule.

2023-06-12 14:59 UTC, guillaume-dequenne-sonarsource commented on rules/S107/python/rule.adoc
> +def setCoordinates(x1, y1, z1, x2, y2, z2): # Noncompliant
It would be better to use snake case to respect Python conventions (`set_coordinates`)

2023-06-12 14:59 UTC, guillaume-dequenne-sonarsource commented on rules/S107/python/rule.adoc
> +def setSize(width, height, depth):
Same here.

2023-06-12 14:59 UTC, guillaume-dequenne-sonarsource commented on rules/S107/python/rule.adoc
> +def setCoordinates(p1, p2):
Same here.
Also, I assume `p1` and `p2` are meant to be `Point` objects? In which case you can type hint them accordingly, to make the example clearer: 
```
def set_coordinates(p1: Point, p2: Point): 
  ...
```

2023-06-12 14:59 UTC, guillaume-dequenne-sonarsource commented on rules/S107/python/rule.adoc
> +This rule raises an issue when a function, a method, or a lambda has more parameters than the given number.
This sentence seems odd (not only for Python): the given number of what?
I understand we're referring to the rule property `max_parameter` that can vary depending on the language, but it's not very clear in isolation.

2023-06-13 06:47 UTC, amelie-renard-sonarsource commented on rules/S107/python/rule.adoc
> +def setCoordinates(p1, p2):
Yes, it's correct. Fixed, thanks!

2023-06-13 06:47 UTC, amelie-renard-sonarsource commented on rules/S107/python/rule.adoc
> +This rule raises an issue when a function, a method, or a lambda has more parameters than the given number.
Thanks for the feedback. I have changed the end of the sentence, is it clearer now?

2023-06-13 09:23 UTC, dorian-burihabwa-sonarsource commented on rules/S107/go/split-example.adoc
> +void setOrigin(x int, y int, z int) {
```suggestion
func setOrigin(x int, y int, z int) {
```

2023-06-13 09:23 UTC, dorian-burihabwa-sonarsource commented on rules/S107/go/split-example.adoc
> +void setSize(width int, height int, depth int) {
```suggestion
func setSize(width int, height int, depth int) {
```

2023-06-13 09:39 UTC, sebastian-hungerecker-sonarsource requested changes

2023-06-13 09:39 UTC, sebastian-hungerecker-sonarsource commented on rules/S107/ruby/noncompliant.adoc
> +def setCoordinates(x1, y1, z1, x2, y2, z2) # Noncompliant
Ruby uses snake_case, not camelCase. Also setters would usually be defined using the `=` operator, not the `set_` prefix, so `def coordinates=`, not `def set_coordinates`, but that doesn't really work when there's more than one argument.

2023-06-13 09:39 UTC, sebastian-hungerecker-sonarsource commented on rules/S107/ruby/split-example.adoc
> +def setOrigin(int x, int y, int z)
Given my earlier point about the `set_` prefix, I'd rename these to `move` and `resize`.

Also Ruby doesn't have parameter types (which I'm sure you know, but added in this example out of habit).

2023-06-13 09:39 UTC, sebastian-hungerecker-sonarsource commented on rules/S107/ruby/struct-example.adoc
> +Struct.new("Point", :x, :y, :z) # In geometry, Point is a logical structure to group data
This should be `Point = Struct.new(:x, :y, :z)`

2023-06-13 09:39 UTC, sebastian-hungerecker-sonarsource commented on rules/S107/ruby/struct-example.adoc
> +def setCoordinates(p1, p2)
I'd be inclined to want to change this to `def coordinates=(points)` where `points` is expected to be an array of two points, but that may make the example unclear. Plus putting the arguments into an array kinda circumvents this rule, so we probably shouldn't do that in the examples.

Maybe we can use an example that's not about setters?

2023-06-13 10:03 UTC, sebastian-hungerecker-sonarsource commented on rules/S107/ruby/struct-example.adoc
> +def setCoordinates(p1, p2)
Maybe instead of a setter, we can define the constructor? Something like this:

Noncompliant:

```ruby
class Cube
  def initialize(x1, y1, z1, x2, y2, z2) # Noncompliant
    # ...
  end
end
```

Compliant:

```ruby
Point = Struct.new(:x, :y, :z)

class Cube
  def initialize(p1, p2) # Compliant
    # ...
  end
end
```

Though in that case, I guess we'd have to drop the example with `move` and `resize` because it wouldn't really be good practice to remove the constructor and instead require the user to call two methods to initialize the object instead of having a constructor.

2023-06-13 11:47 UTC, dorian-burihabwa-sonarsource requested changes
Thank you for the great work,  I reviewed the examples for Apex, Go, Kotlin, Java and Scala (I saw that Ruby was commented on as I was reviewing so I did not cover these samples).

The examples are pretty good but some might be tweaked to follow conventions (eg: implicit or explicit function types) or language versions.

Ping me if you want another review on the same languages

2023-06-13 11:47 UTC, dorian-burihabwa-sonarsource commented on rules/S107/scala/struct-example.adoc
> +end Point
Because most of our examples use Scala2, I would suggest this version
```suggestion
class Point(var x: Int, var y: Int, var z: Int) { // In geometry, Point is a logical structure to group data
}

```

2023-06-14 11:56 UTC, vilchik-elena approved these changes

2023-06-14 11:56 UTC, vilchik-elena commented on rules/S107/javascript/noncompliant.adoc
> +void setCoordinates(int x1, int y1, int z1, int x2, int y2, int z2) { // Noncompliant
```suggestion
function setCoordinates(x1, y1, z1, x2, y2, z2) { // Noncompliant
```

2023-06-14 11:56 UTC, vilchik-elena commented on rules/S107/javascript/split-example.adoc
> +}
```suggestion
function setOrigin(x, y, z) {
   // ...
}

function setSize(width, height, depth) {
   // ...
}
```

2023-06-14 11:56 UTC, vilchik-elena commented on rules/S107/javascript/struct-example.adoc
> +}
```suggestion
// In geometry, Point is a logical structure to group data
let point1 = { x: x1, y: y1, z: z1};
let point2 = { x: x1, y: y1, z: z1};
setCoordinates(point1, point2);

function setCoordinates(p1, p2) {
   // ...
}
```

2023-06-15 14:25 UTC, sebastian-hungerecker-sonarsource approved these changes
LGTM for Ruby.

2023-06-15 15:01 UTC, martin-strecker-sonarsource commented on rules/S107/csharp/rule.adoc
> +Methods with a long parameter list are difficult to use, as maintainers must figure out the role of each parameter and keep track of their position.
Consider making "function" an attribute and use it in rules/S107/rule.adoc:
`{function}s with a long parameter list are difficult to use, as maintainers must figure out the role of each parameter and keep track of their position.`

You could then define it here `:function: method` and reuse the existing documents as you do with most of the other rules.

Hint: We had some discussion in our squad to create a common dictionary for all languages for such cases (concepts and keywords that have different names/casing but refer to the same thing). This would allow us to resolve such minor differences.

You can find the discussion here: https://sonarsource.slack.com/archives/C059FQ512EA/p1686562366420019

One major problem with this is also affecting you here: You need two variables because you need the capitalized and the lowercase variant as asciidoc does not have any built-in functions to solve this.

2023-06-16 07:33 UTC, amelie-renard-sonarsource commented on rules/S107/csharp/rule.adoc
> +Methods with a long parameter list are difficult to use, as maintainers must figure out the role of each parameter and keep track of their position.
Thanks, @martin-strecker-sonarsource for your insight. TBH, I hesitated to introduce these two variables (one upper case, one lower case). So I thought I'd wait for the rules to be approved before deciding.
But indeed, I'll add them.

The common dictionary is a nice idea!

2023-06-16 07:39 UTC, martin-strecker-sonarsource commented on rules/S107/csharp/rule.adoc
> +Methods with a long parameter list are difficult to use, as maintainers must figure out the role of each parameter and keep track of their position.
Rewording the sentence might be another option.

2023-06-16 07:41 UTC, martin-strecker-sonarsource commented on rules/S107/apex/rule.adoc
> +:struct-example: apex/struct-example.adoc
You may consider shortening the definition to the only part that ever changes:
```suggestion
:language: apex
```

2023-06-16 07:51 UTC, amelie-renard-sonarsource commented on rules/S107/apex/rule.adoc
> +:struct-example: apex/struct-example.adoc
Indeed, I didn't think of that. Thanks!

2023-06-16 08:44 UTC, martin-strecker-sonarsource commented on rules/S107/plsql/rule.adoc
>  With the default threshold of 10:
```suggestion
With a customized threshold of 5 (the default is 10):
```

Noncompliant
```sql
SET SERVEROUTPUT ON

CREATE PROCEDURE storeCube( -- Noncompliant, too many parameters
  x1 PLS_INTEGER,
  y1 PLS_INTEGER,
  z1 PLS_INTEGER,
  x2 PLS_INTEGER,
  y2 PLS_INTEGER,
  z2 PLS_INTEGER)
BEGIN
  -- store the qube values
END;
/
BEGIN
  storeCube(0, 0, 0, 1, 1, 1);
END;
/

DROP PROCEDURE storeCube;
```

Split
```sql
SET SERVEROUTPUT ON

CREATE PROCEDURE storeVector(
  x PLS_INTEGER,
  y PLS_INTEGER,
  z PLS_INTEGER)
BEGIN
  -- store the vectors values
END;
/
BEGIN
storeVector(0, 0, 0);
storeVector(1, 1, 1);
END;
/

DROP PROCEDURE storeVector;
```
struct
```sql
SET SERVEROUTPUT ON

CREATE TYPE point AS OBJECT(
  x PLS_INTEGER,
  y PLS_INTEGER,
  z PLS_INTEGER);

CREATE PROCEDURE storeQube(
  p1 point,
  p2 point)
BEGIN
END;
/
BEGIN
storeQube(point(0, 0, 0), point(1, 1, 1))
END;
/

DROP PROCEDURE storeQube;
DROP TYPE point;
```

2023-06-16 08:59 UTC, martin-strecker-sonarsource commented on rules/S107/vb6/rule.adoc
> +* Find a better data structure for the parameters that group data in a way that makes sense for the specific application domain
=== Noncompliant code example

```vb6
Public Sub SetCoordinates(ByVal x1 As Integer, ByVal y1 As Integer, ByVal z1 As Integer, ByVal x2 As Integer, ByVal y2 As Integer, ByVal z2 As Integer) ' Noncompliant
  ' ...
End Sub
```

=== Compliant solution

Split

```vb6
Public Sub SetOrigin(ByVal x As Integer, ByVal y As Integer, ByVal z As Integer)
  ' ...
End Sub

Public Sub SetSize(ByVal width As Integer, ByVal height As Integer, ByVal depth As Integer)
  ' ...
End Sub
```

struct
```vb6
Public Type Point
    X As Integer
    Y As Integer
    Z As Integer
End Type

Public Sub SetCoordinates(p1 As Point, p2 As Point)
  ' ...
End Sub
```

2023-06-16 10:00 UTC, amelie-renard-sonarsource commented on rules/S107/vb6/rule.adoc
> +* Find a better data structure for the parameters that group data in a way that makes sense for the specific application domain
Thanks!

2023-06-16 10:07 UTC, amelie-renard-sonarsource commented on rules/S107/plsql/rule.adoc
>  With the default threshold of 10:
Thanks!

2023-06-16 15:20 UTC, frederic-tingaud-sonarsource requested changes

2023-06-16 15:20 UTC, frederic-tingaud-sonarsource commented on rules/S107/cfamily/rule.adoc
:upper_function: Function

:function: function

2023-06-16 15:20 UTC, frederic-tingaud-sonarsource commented on rules/S107/plsql/rule.adoc
> +include::struct-example.adoc[]
It's not necessary to have these as includes, they could be inlined. But it's not a big deal, if you prefer like that I'm ok with it.

2023-06-26 10:14 UTC, amelie-renard-sonarsource commented on rules/S107/scala/noncompliant.adoc
> +ifdef::env-github,rspecator-view[]
Indeed, removed

2023-08-10 13:46 UTC, frederic-tingaud-sonarsource approved these changes

2023-08-10 13:51 UTC, amelie-renard-sonarsource commented on rules/S107/vbnet/rule.adoc
> +        MyBase.New(Param1) ' Compliant by exception
Fixed in https://github.com/SonarSource/rspec/pull/2130/commits/5368290adb82c87176ced10c7639c244d7ff1a34

2023-08-10 14:19 UTC, dorian-burihabwa-sonarsource approved these changes
LGTM 👍🏿 Checked for Apex, Go, Java, Kotlin, Ruby, and Scala.

I left a suggestion on the ruby non-compliant example that contains some extra blank lines

2023-08-10 14:19 UTC, dorian-burihabwa-sonarsource commented on rules/S107/ruby/noncompliant.adoc
> +
I guess we can remove the extra blank lines
```suggestion
```

2023-08-10 14:54 UTC, merged