Modify rule S108: LaYC format
SonarSource/rspec pull request #2133
Opened 2023-06-09 12:44 UTC by amelie-renard-sonarsource

2023-06-13 10:04 UTC, frederic-tingaud-sonarsource requested changes

2023-06-13 10:04 UTC, frederic-tingaud-sonarsource commented on rules/S108/exceptions.adoc
> +A code block is not empty when it contains a comment.
```suggestion
A code block is not considered empty when it contains a comment.
```
I think the "considered" word is important to keep because from an AST point of view, it _is_ empty.

2023-06-13 10:04 UTC, frederic-tingaud-sonarsource commented on rules/S108/noncompliant.adoc
>  [source,text]
```suggestion
[source,java]
```

2023-06-13 10:04 UTC, frederic-tingaud-sonarsource commented on rules/S108/description.adoc
> +Removing or filling the empty code blocks takes away ambiguity.
```suggestion
Removing or filling the empty code blocks takes away ambiguity and will generally result in a simpler and less surprising code.
```

2023-06-13 11:43 UTC, amelie-renard-sonarsource commented on rules/S108/description.adoc
> +Removing or filling the empty code blocks takes away ambiguity.
Modified

2023-06-13 11:43 UTC, amelie-renard-sonarsource commented on rules/S108/noncompliant.adoc
>  [source,text]
Fixed

2023-06-13 11:44 UTC, amelie-renard-sonarsource commented on rules/S108/exceptions.adoc
> +A code block is not empty when it contains a comment.
I rewrote it differently. WDYT?

2023-06-13 14:19 UTC, frederic-tingaud-sonarsource commented on rules/S108/exceptions.adoc
> +A code block is not empty when it contains a comment.
Great, thanks!

2023-06-13 14:24 UTC, frederic-tingaud-sonarsource requested changes
Just one remaining point where I don't completely agree.

2023-06-13 14:24 UTC, frederic-tingaud-sonarsource commented on rules/S108/description.adoc
> +An empty code block is confusing and surprising for maintainers as it may indicate missing code.
Not a fan of this wording, because it implies that it's because code might be missing that it is surprising, while the two are independent.
```cpp
for (int i = 0; i < 10; doSomething(), ++i) {}
```
has no missing code but is super surprising.

2023-06-15 17:03 UTC, frederic-tingaud-sonarsource approved these changes

2023-06-15 17:03 UTC, merged