Modify rule S4635: Improve code example
SonarSource/rspec pull request #2143
Opened 2023-06-09 15:37 UTC by sebastien-marichal

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone

2023-06-09 16:51 UTC, zsolt-kolbay-sonarsource approved these changes
~~LGTM~~

2023-06-09 17:31 UTC, zsolt-kolbay-sonarsource requested changes
I'd add a short description on how to handle negative values (when the character/string cannot be found in the string).

2023-06-09 17:31 UTC, zsolt-kolbay-sonarsource commented on rules/S4635/csharp/rule.adoc
>  Using these methods gives the same result while avoiding the creation of additional `string` objects.
This will not have the same result in every scenario as the non-compliant version of the code.
If the character/string cannot be found in the string, then `IndexOf` will return -1. I've seen several code bases, where the return value of `IndexOf` was compared to -1 instead of checking whether it's smaller than 0. Consider the following code:
```
if (str.SubString(42).IndexOf('X') == -1)
{
   ...
}
```
Replacing this with 
```
if (str.IndexOf('X', 42) - 42 == -1)
{
   ...
}
```
will yield a different outcome if `'X'` is not found.
I think it's worth adding this as a note to the description.

2023-06-12 09:16 UTC, zsolt-kolbay-sonarsource reviewed
I will not be able to follow up on my change request this week, so I change the status and leave it up to you if you want to change it.

2023-06-12 11:20 UTC, martin-strecker-sonarsource requested changes

2023-06-12 11:20 UTC, martin-strecker-sonarsource commented on rules/S4635/csharp/rule.adoc
> +As mentioned in the `String.IndexOf` documentation, when the value to seek within the string is not found, `String.IndexOf` will return the `-1`.
I don't understand the problem. The code can be rewritten as follows:
```cs
if (str.IndexOf(char1, startIndex) == -1)
```
Consider removing the pitfall section.

2023-06-12 11:26 UTC, martin-strecker-sonarsource commented
I also think the title is a bit confusing as well:

❓ **String offset-based methods should be preferred for finding substrings from offsets**

What about something like:

❗  **The startString parameter should be preferred for seeking strings from offsets**

2023-06-12 11:29 UTC, martin-strecker-sonarsource commented on rules/S4635/csharp/rule.adoc
> +To mitigate the creation of new objects while searching for characters within a substring, it is possible to use the overload of the mentioned methods that accept an offset as the second parameter. H
The parameter is always called `startIndex` so we could use the name to refer to it instead of the position
```suggestion
To mitigate the creation of new objects while searching for characters within a substring, it is possible to use the overload of the mentioned methods with a `startIndex` parameter. Here is an example:
```

2023-06-12 13:43 UTC, sebastien-marichal commented on rules/S4635/csharp/rule.adoc
> +As mentioned in the `String.IndexOf` documentation, when the value to seek within the string is not found, `String.IndexOf` will return the `-1`.
I think the section is still relevant with your version of the fix.
The rule's compliant solution suggests subtracting `startIndex` from the result of `IndexOf`.
```cs
str.IndexOf(char1, startIndex) - startIndex
```

I think, if not careful enough, devs might apply the fix and end up with code like this:

```cs
if (str.IndexOf(char1, startIndex) - startIndex == -1)
{
   // ...
}
```

Which will change the behavior of the application. It will, in most cases if not all, evaluate to `false`.

2023-06-12 13:52 UTC, sebastien-marichal commented
> I also think the title is a bit confusing as well:
> 
> ❓ **String offset-based methods should be preferred for finding substrings from offsets**
> 
> What about something like:
> 
> ❗ **The startString parameter should be preferred for seeking strings from offsets**

I agree the title could be better. I must admit, your suggestion is not totally clear to me. Maybe we can find something better.

2023-06-12 15:24 UTC, martin-strecker-sonarsource commented
> your suggestion is not totally clear to me

I had a typo in it. It should read  "The 'startIndex' parameter should be preferred for seeking strings from offsets."

Which part of it?

The rule is highlighting the `IndexOf()` invocation, so it should be clear what "startIndex parameter" refers to. Maybe we can change it to "startIndex parameter of the IndexOf method" but this is a bit imprecise because there are IndexOf, IndexOfAny, LastIndexOf, and LastIndexOfAny.

2023-06-12 15:25 UTC, martin-strecker-sonarsource commented on rules/S4635/csharp/metadata.json
> +    "quickfix": "infeasible"
It is possible to provide a quick fix for this case.

2023-06-12 15:53 UTC, sebastien-marichal commented on rules/S4635/csharp/metadata.json
> +    "title": "Seeking characters from a substring should be avoided",
@martin-strecker-sonarsource This is my try to improve the title. From my understanding, this rule is looking of useless object creation when seeking character. I think this fits well.

I dropped the `startIndex` info since I don't know where to put it and I am not sure if really relevant.

2023-06-12 16:56 UTC, martin-strecker-sonarsource requested changes
Title is fine. We still need to do something about the example/pitfall.

2023-06-13 10:25 UTC, sebastien-marichal commented on rules/S4635/csharp/rule.adoc
> +As mentioned in the `String.IndexOf` documentation, when the value to seek within the string is not found, `String.IndexOf` will return the `-1`.
I have removed the `Pitfalls` section and updated the examples to be more realistic.
I believe now, it should be more clear.

2023-06-13 10:40 UTC, martin-strecker-sonarsource approved these changes
LGTM. Some minor grammar issues are still to be resolved.

2023-06-13 10:40 UTC, martin-strecker-sonarsource commented on rules/S4635/csharp/rule.adoc
> +To mitigate the creation of new objects while searching for characters within a substring, it is possible to use the overload of the mentioned methods with a `startIndex` parameter. Here is an exampl
There are many overloads with a `startIndex` parameter per method group. "Here is an example:" doesn't fit any more as you show the compliant solution.
```suggestion
To mitigate the creation of new objects while searching for characters within a substring, it is possible to use an overload of the mentioned methods with a `startIndex` parameter:
```

2023-06-13 10:40 UTC, martin-strecker-sonarsource commented on rules/S4635/csharp/rule.adoc
> +if (str.IndexOf(char1, startIndex) == -1)           // Compliant: no new instance of string created
```suggestion
if (str.IndexOf(char1, startIndex) == -1)           // Compliant: no new instance of string is created
```

2023-06-13 14:01 UTC, merged