Modify rule S110: LaYC format
SonarSource/rspec pull request #2146
Opened 2023-06-12 06:58 UTC by amelie-renard-sonarsource

2023-06-12 17:32 UTC, frederic-tingaud-sonarsource requested changes

2023-06-12 17:32 UTC, frederic-tingaud-sonarsource commented on rules/S110/rule.adoc
> +But abusing this concept by creating a deep inheritance tree can lead to very complex and unmaintainable source code. Most of the time, too deep of an inheritance tree is due to lousy object-oriented
For me, "lousy" is a very badly connoted word.
```suggestion
But abusing this concept by creating a deep inheritance tree can lead to complex and unmaintainable source code. Most of the time, an inheritance tree becoming too deep is the symptom of systematic use of "inheritance" when other approaches like "composition" would be better suited.
```

2023-06-12 17:32 UTC, frederic-tingaud-sonarsource commented on rules/S110/php/rule.adoc
> +This rule raises an issue when the inheritance tree, starting from `Object`, has a greater depth than is allowed.
Does `Object` exist in PHP?

2023-06-12 17:32 UTC, frederic-tingaud-sonarsource commented on rules/S110/java/rule.adoc
>  * ``++java.fwk.**++`` same as above, but including sub-packages.
```suggestion
* ``++java.fwk.**++``: same as above, but including sub-packages.
```

2023-06-13 06:51 UTC, amelie-renard-sonarsource commented on rules/S110/java/rule.adoc
>  * ``++java.fwk.**++`` same as above, but including sub-packages.
Fixed

2023-06-13 07:37 UTC, amelie-renard-sonarsource commented on rules/S110/php/rule.adoc
> +This rule raises an issue when the inheritance tree, starting from `Object`, has a greater depth than is allowed.
Apparently not, removed

2023-06-13 07:39 UTC, amelie-renard-sonarsource commented on rules/S110/rule.adoc
> +But abusing this concept by creating a deep inheritance tree can lead to very complex and unmaintainable source code. Most of the time, too deep of an inheritance tree is due to lousy object-oriented
Better, thanks!

2023-06-13 14:28 UTC, frederic-tingaud-sonarsource approved these changes

2023-06-13 14:32 UTC, merged