Modify rule S3445: LaYC format
SonarSource/rspec pull request #2151
Opened 2023-06-12 13:55 UTC by costin-zaharia-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-13 10:21 UTC, sebastien-marichal requested changes
Left some suggestions, to summarize:
- focus more on the rethrow mechanism in the description
- reconsider the exception example
- merge `how to` section in the `why` section

Open to discussing it if needed.

2023-06-13 10:21 UTC, sebastien-marichal commented on rules/S3445/csharp/rule.adoc
> +In the software development context, an expression is a value or anything that executes and ends up being a value. The expression shall be implicitly convertible to `System.Exception`, and the result
I would expect more details about the rethrown mechanism and how the stack is preserved in those cases.

I think the explanations are going too far.

2023-06-13 10:21 UTC, sebastien-marichal commented on rules/S3445/csharp/rule.adoc
> +  throw new Exception("Additional information", exception);
This code example is throwing a brand-new `exception`, I would not consider it an exception per se.
However, it is a good and interesting addition.

2023-06-13 10:21 UTC, sebastien-marichal commented on rules/S3445/csharp/rule.adoc
> +== How to fix it
The code example from the `why` and `How to fix it` sections are the same.
I think the `How to fix it` section could be merged into the `why`

2023-06-13 14:09 UTC, costin-zaharia-sonarsource commented on rules/S3445/csharp/rule.adoc
> +In the software development context, an expression is a value or anything that executes and ends up being a value. The expression shall be implicitly convertible to `System.Exception`, and the result
> I would expect more details about the rethrown mechanism and how the stack is preserved in those cases.

Do you mean updating the next section (Without specifying an expression)? I've added "preserving the stack trace." to make this obvious.

> I think the explanations are going too far.

I've tried to explain all the concepts involved:
- what is an expression
- how it's evaluated and how the throw works when the expression is specified
- how the stack trace is cleared and what that means "losing the list of method calls between.."

What do you think it's superflu? the null handling?

2023-06-13 14:21 UTC, costin-zaharia-sonarsource commented on rules/S3445/csharp/rule.adoc
> +== How to fix it
My understanding is that it's perfectly fine to have snippets from the `Why` section replicated in `How to fix it` and that we should not expect the users to have the context from the other tab.

I think that for this rule, having two separate sections helps. The first one explains what the problem is and what's the result of using both approaches, while the second section has a short and clear explanation, straight to the point, while providing code examples with the compliant and noncompliant snippets.

I think that mixing the description of how the `throw` works and the rule expectations will cause more confusion and make the topic harder to understand.

2023-06-13 15:37 UTC, sebastien-marichal commented on rules/S3445/csharp/rule.adoc
> +== How to fix it
It is not always very clear to me, to be honest.
You convince me, this rule might be too complex to skip the `How to fix it` section.

2023-06-13 15:38 UTC, sebastien-marichal requested changes
I added more details to my previous comment.

2023-06-14 07:47 UTC, costin-zaharia-sonarsource commented on rules/S3445/csharp/rule.adoc
> +In this case, the https://en.wikipedia.org/wiki/Stack_trace[stack trace], will be cleared, losing the list of method calls between the original method that threw the exception and the current method.
I've linked the stack trace but I would not go into more details about what a stack trace because the resto of the sentence indirectly explains that: "losing the list of method calls between the original method that threw the exception and the current method"

2023-06-14 09:27 UTC, sebastien-marichal approved these changes
LGTM!
Left some comments that do not need another review round.

2023-06-14 09:27 UTC, sebastien-marichal commented on rules/S3445/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/api/system.exception?view=net-7.0#re-throwing-an-exception[Re-throwing an exception]
```suggestion
* https://learn.microsoft.com/en-us/dotnet/api/system.exception#re-throwing-an-exception[Re-throwing an exception]
```

2023-06-14 09:27 UTC, sebastien-marichal commented on rules/S3445/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/statements#13106-the-throw-statement[The throw statement]
You can also add here the link to the stack trace wiki page

2023-06-14 13:00 UTC, merged