Modify rule S4586: LaYC format
SonarSource/rspec pull request #2155
Opened 2023-06-12 16:47 UTC by martin-strecker-sonarsource

Update rule content and descriptions to LaYC format.
https://sonarsource.github.io/rspec/#/rspec/S4586

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-13 13:41 UTC, csaba-sagi-sonarsource commented on rules/S4586/csharp/rule.adoc
>  == Why is this an issue?
The Why is this an issue section is the same for C# and VB.net. Please extract it into a file called why-dotnet.adoc and link it, to remove duplication.

2023-06-13 13:42 UTC, csaba-sagi-sonarsource requested changes
I left two small comments. Also, it might have not been shared with you that we took a decision to take the clean-as-you code approach and update the quickfix field for each rule we migrate to lake, so please evaluate if a quickfix is possible or not and update the field accordingly.

2023-06-14 12:01 UTC, csaba-sagi-sonarsource commented on rules/S4586/csharp/rule.adoc
>  == Why is this an issue?
I really don't have a strong opinion. Some people are using it and Pavel also suggested to use it in this exact case.

2023-06-14 12:05 UTC, csaba-sagi-sonarsource approved these changes
I am approving the PR, The unresolved conversation is optional in my opinion.
If you wish apply it, otherwise feel free to merge as is.

2023-06-15 10:12 UTC, martin-strecker-sonarsource commented
Re-requested a review because of https://github.com/SonarSource/rspec/pull/2155#discussion_r1230766502

2023-06-15 10:28 UTC, csaba-sagi-sonarsource commented on rules/S4586/csharp/rule.adoc
>  == Why is this an issue?
If we ever plan to introduce a dictionary for the keywords, I think this state is a better one to move forwards, otherwise, I am not sure we will revisit the rule ever to add the variables/attributes.
I don't have a strong opinion so I will let you decide and merge the rule in whichever state you wish.

2023-06-15 10:28 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2023-06-15 13:08 UTC, merged