Modify S4426: Learn-As-You-Code Migration
SonarSource/rspec pull request #2166
Opened 2023-06-13 09:58 UTC by loris-s-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-15 16:40 UTC, loris-s-sonarsource commented on rules/S4426/common/fix/fix.adoc
> +ECDH, or ECMQV. Keys generated with EC algorithms are mentioned directly in
```suggestion
ECDH, or ECMQV. The length of keys generated with EC algorithms are mentioned directly in
```

2023-06-19 14:00 UTC, hendrik-buchwald-sonarsource commented on rules/S4426/impact.adoc
> +After retrieving encrypted data and performing mathematical attacks on it on a
I am unsure if "mathematical attacks" is a good description. Maybe "exhaustion attack"? https://www.staff.uni-mainz.de/pommeren/Cryptology/Classic/1_Monoalph/exhaust.html

2023-06-19 14:25 UTC, loris-s-sonarsource commented on rules/S4426/common/fix/fix.adoc
> +possible to use higher key sizes that provide an even higher level of security.
I have to admit that when I wrote that I felt some kind of imprecision

2023-06-19 15:14 UTC, loris-s-sonarsource commented on rules/S4426/kotlin/how-to-fix-it/java-cryptographic-extension.adoc
> +        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("RSA");
```suggestion
        val keyPairGenerator = KeyPairGenerator.getInstance("RSA");
```

2023-06-19 15:14 UTC, loris-s-sonarsource commented on rules/S4426/kotlin/how-to-fix-it/java-cryptographic-extension.adoc
> +        KeyGenerator keyGenerator = KeyGenerator.getInstance("AES");
```suggestion
        val keyGenerator = KeyGenerator.getInstance("AES");
```

2023-06-19 15:16 UTC, loris-s-sonarsource commented on rules/S4426/java/rule.adoc
> +* https://wiki.sei.cmu.edu/confluence/x/hDdGBQ[CERT, MSC61-J.] - Do not use insecure or weak cryptographic algorithms
```suggestion
```

2023-06-19 15:18 UTC, loris-s-sonarsource commented on rules/S4426/python/rule.adoc
> +include::../message.adoc[]
```suggestion
i=== Message

Use a key length of at least 'xxx' bits

Use a public key exponent of at least 65537
```

2023-06-20 07:31 UTC, hendrik-buchwald-sonarsource requested changes
`validate_asciidoc` is still failing, otherwise it looks good.

2023-06-20 10:08 UTC, merged