Modify rule S4275: LaYC format
SonarSource/rspec pull request #2168
Opened 2023-06-13 11:40 UTC by martin-strecker-sonarsource

Update rule content and descriptions to LaYC format.
[S4275: Getters and setters should access the expected fields](https://sonarsource.github.io/rspec/#/rspec/S4275)

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-13 12:31 UTC, gregory-paidis-sonarsource requested changes
Looks good, left some minor suggestions

2023-06-13 12:31 UTC, gregory-paidis-sonarsource commented on rules/S4275/csharp/rule.adoc
> +Properties provide a way to enforce encapsulation by providing accessors that give controlled access to `private` fields. However, in classes with multiple fields, it is not unusual that cut and past
You can link [encapsulation](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)), some junior devs might not know it.

2023-06-13 12:31 UTC, gregory-paidis-sonarsource commented on rules/S4275/csharp/rule.adoc
> +Properties provide a way to enforce encapsulation by providing accessors that give controlled access to `private` fields. However, in classes with multiple fields, it is not unusual that cut and past
why does it say `cut` and paste instead of `copy` and paste? 🤔 
Technically, `cut and paste` will not result in this issue.

2023-06-13 12:31 UTC, gregory-paidis-sonarsource commented on rules/S4275/vbnet/metadata.json
> +    "title": "Property procedures should access the expected fields"
you need to change the `quickfix` field as well, both for c# and vb.net in `metadata.json`.

(I think it should be `infeasible` for this rule)

2023-06-13 12:31 UTC, gregory-paidis-sonarsource commented on rules/S4275/vbnet/rule.adoc
> +Properties provide a way to enforce encapsulation by providing property procedures that give controlled access to `Private` fields. However, in classes with multiple fields, it is not unusual that cu
Same as C#:

- Link encapsulation
- cut -> copy

2023-06-14 09:23 UTC, antonioaversa commented on rules/S4275/csharp/rule.adoc
> +Properties provide a way to enforce encapsulation by providing accessors that give controlled access to `private` fields. However, in classes with multiple fields, it is not unusual that cut and past
A small code example would also help. 
Especially because all code examples for this rule are now in the How to fix tab.

2023-06-14 10:35 UTC, martin-strecker-sonarsource commented on rules/S4275/csharp/rule.adoc
> +Properties provide a way to enforce encapsulation by providing accessors that give controlled access to `private` fields. However, in classes with multiple fields, it is not unusual that cut and past
I added an example, but I'm not certain it works: https://github.com/SonarSource/sonar-dotnet/issues/7420

2023-06-14 10:37 UTC, martin-strecker-sonarsource commented on rules/S4275/vbnet/metadata.json
> +    "title": "Property procedures should access the expected fields"
It is possible. The rule makes sure that there is a fitting field, so we could replace the tokens.

2023-06-14 10:39 UTC, martin-strecker-sonarsource commented on rules/S4275/csharp/rule.adoc
> +    public int Y => x; // Noncompliant: The returned field should be 'y'
May not work:
https://github.com/SonarSource/sonar-dotnet/issues/7420
The implementation works on the symbol-level in most parts, so it should be fine, but it is not covered by tests.

2023-06-14 11:12 UTC, martin-strecker-sonarsource commented
@gregory-paidis-sonarsource There are directories, where the rule.adoc isn't adapted for
* cfammily
* java
* php
* swift

Are we supposed to delete these directories? The rule.adoc looks like so
```adoc
include::../rule.adoc[]
ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../message.adoc[]

include::../highlighting.adoc[]

endif::env-github,rspecator-view[]
```

If we delete it, where should it be documented?

2023-06-14 11:57 UTC, gregory-paidis-sonarsource commented
> Are we supposed to delete these directories? 

@martin-strecker-sonarsource  I think you are fine ignoring them. Take a look if they are included in [this gigantic PR](https://github.com/SonarSource/rspec/pull/2145) for the languages you wanted. If they are, don't do anything about them :)

2023-06-14 11:58 UTC, gregory-paidis-sonarsource approved these changes
LGTM, take a look at the comment for the removal of unused languages. If nothing is needed, merge at will.

2023-06-14 12:59 UTC, merged