Modify rule S2291: LAYC format
SonarSource/rspec pull request #2169
Opened 2023-06-13 12:10 UTC by gregory-paidis-sonarsource

2023-06-14 07:48 UTC, martin-strecker-sonarsource requested changes
I'm a bit concerned about the section about the "checked" and "unchecked" language feaure.

2023-06-14 07:48 UTC, martin-strecker-sonarsource commented on rules/S2291/csharp/metadata.json
> +  "quickfix": "infeasible"
targeted: The fix is to remove the `unchecked` block.

2023-06-14 07:48 UTC, martin-strecker-sonarsource commented on rules/S2291/csharp/rule.adoc
> +The checked and unchecked https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/checked-and-unchecked[statements] and https://learn.microsoft.com/en-us/dotnet/csharp/language-
This is a nice explanation but I would move the

> Enumerable.Sum() always executes addition in a `checked` context

paragraph to the beginning and move this part into a subsection like `=== Background` or the `How does it work` section in `How to fix it`.

2023-06-14 07:48 UTC, martin-strecker-sonarsource commented on rules/S2291/csharp/rule.adoc
> +unchecked(a = a + 1); // a+1 overflows, results in 0
```suggestion
unchecked(a = a + 1); // a + 1 overflows, results in 0
```

2023-06-14 07:48 UTC, martin-strecker-sonarsource commented on rules/S2291/csharp/rule.adoc
> +* When `checked` is specified, an https://learn.microsoft.com/en-us/dotnet/api/system.overflowexception[OverflowException] is thrown for a run-time overflow, and https://learn.microsoft.com/en-us/dot
I don't think, we need to talk about compile time errors in our rules. In the case of this rule, there is no compile time error possible.
```suggestion
* When `checked` is specified, an https://learn.microsoft.com/en-us/dotnet/api/system.overflowexception[OverflowException] is thrown instead.
```

2023-06-14 07:48 UTC, martin-strecker-sonarsource commented on rules/S2291/csharp/rule.adoc
> +checked(b + 1) // compile-time: Compiler Error CS0220
The examples and explanations are almost identical to what is written in https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/checked-and-unchecked Do we really need this section? This is more like an explanation of a language feature than an education about a code smell / bug. I think we usually assume the user knows the language and link to "Learn Microsoft" as you already did. My personal opinion is, that the link is enough already. What do you think?

2023-06-14 07:48 UTC, martin-strecker-sonarsource commented on rules/S2291/csharp/rule.adoc
> +https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.sum[Enumerable.Sum()] always executes addition in a `checked` context, so an OverflowException will be thrown if the value exceeds
It would be good to back that claim with a source (unfortunately we can not use footnotes 😢 ). You can either cite the exception section:
> [OverflowException](https://learn.microsoft.com/en-us/dotnet/api/system.overflowexception?view=net-7.0)
The sum is larger than [Int32.MaxValue](https://learn.microsoft.com/en-us/dotnet/api/system.int32.maxvalue?view=net-7.0).

or the source code

https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System.Core/System/Linq/Enumerable.cs#L1408-L1415

This link should go into the Resources section.

2023-06-14 07:48 UTC, martin-strecker-sonarsource commented on rules/S2291/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0220?f1url=%3FappId%3Droslyn%26k%3Dk(CS0220)[Compiler Error CS0220]
Not needed.
```suggestion
```

2023-06-14 07:48 UTC, martin-strecker-sonarsource commented on rules/S2291/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/api/system.overflowexception[OverflowException Class]
```suggestion
* https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.sum[`Enumerable.Sum` Method]
* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/checked-and-unchecked[`checked` and `unchecked` statements]
* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#12819-the-checked-and-unchecked-operators[`checked` and `unchecked` operators]
* https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/[Exceptions and Exception Handling]
* https://learn.microsoft.com/en-us/dotnet/api/system.overflowexception[`OverflowException` Class]
```

2023-06-14 14:26 UTC, gregory-paidis-sonarsource commented on rules/S2291/csharp/rule.adoc
> +checked(b + 1) // compile-time: Compiler Error CS0220
Yes, what you say makes sense. I still struggle to find the balance of how explanatory I should be. Dropped the entire section.

2023-06-14 15:29 UTC, martin-strecker-sonarsource approved these changes
LGTM. One minor suggestion, though.

2023-06-14 15:29 UTC, martin-strecker-sonarsource commented on rules/S2291/csharp/rule.adoc
> +https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.sum[Enumerable.Sum()] always executes addition in a `checked` context, so an https://learn.microsoft.com/en-us/dotnet/api/system.ov
```suggestion
https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.sum[`Enumerable.Sum()`] always executes addition in a `checked` context, so an https://learn.microsoft.com/en-us/dotnet/api/system.overflowexception[OverflowException] will be thrown if the value exceeds `MaxValue`, even if an `unchecked` context was specified. Therefore, using this method inside an `unchecked` context will only make the code more confusing, since the behavior will still be `checked`.
```

2023-06-15 07:34 UTC, martin-strecker-sonarsource commented on rules/S2291/csharp/rule.adoc
> +https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.sum[Enumerable.Sum()] always executes addition in a `checked` context, so an https://learn.microsoft.com/en-us/dotnet/api/system.ov
I don't know: https://sonarsource.slack.com/archives/C04P0SB2KJP/p1686642571396659 There is a meeting today with the documentation team where I will bring this up as well.

2023-06-15 08:20 UTC, merged