Modify rule S4830: LaYC format
SonarSource/rspec pull request #2176
Opened 2023-06-13 15:17 UTC by hendrik-buchwald-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [x] logical errors and incorrect information
- [x] information gaps and missing content
- [x] text style and tone
- [x] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-16 16:49 UTC, loris-s-sonarsource requested changes
In general, I recommend adding a small web request to add a little realism and show the user that this impacts web requests. 


I mentioned it in the .Net samples and in general, adding them could add compliant code samples and show more colorfully to the user that they shouldn't do that, thanks to the diff views. It is only done on Docker and JS for now.

To follow what's written in the impact sections (which LGTM ! ✅ very nice), we could make requests to "bank.example.com". This could have even more impact.

2023-06-16 16:49 UTC, loris-s-sonarsource commented on rules/S4830/common/fix/validation.adoc
> +necessary certificates to your trust store.
This looks like "extra mile" or "pitfalls" materials no ? Since the fix is only to activate validation

2023-06-16 16:49 UTC, loris-s-sonarsource commented on rules/S4830/csharp/how-to-fix-it/dot-net.adoc
> +}
WDYT of adding a little more? And then adding the benign code as compliant ? 

```suggestion
using System.Net;
using System.Net.Http;

public static void connect()
{
    ServicePointManager.ServerCertificateValidationCallback +=
	 (sender, certificate, chain, errors) => {
	     return true; // Noncompliant
    };

    HttpClient httpClient = new HttpClient();
    HttpResponseMessage response = httpClient.GetAsync("https://example.com").Result;
}
```

2023-06-16 16:49 UTC, loris-s-sonarsource commented on rules/S4830/csharp/how-to-fix-it/dot-net.adoc
> +include::../../common/fix/code-rationale.adoc[]
because it's a global change. I suggest adding:

"In the following example, the callback change impacts the entirety of HTTP requests made by the application.",

2023-06-16 16:49 UTC, loris-s-sonarsource commented on rules/S4830/javascript/how-to-fix-it/node-js.adoc
> +  rejectUnauthorized: false // Secondary location
```suggestion
  rejectUnauthorized: false
```

I don't think the users understand this comment or care. However the code rationale should indicate that the problem comes from this line

2023-06-16 16:49 UTC, loris-s-sonarsource commented on rules/S4830/php/how-to-fix-it/curl.adoc
> +curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false); // Noncompliant
Here I suggest adding the initialization of $curl and optionally a request made

2023-06-16 16:49 UTC, loris-s-sonarsource commented on rules/S4830/python/how-to-fix-it/openssl.adoc
> +ctx1 = SSL.Context(SSL.TLSv1_2_METHOD) # Noncompliant: by default certificate validation is not done
```suggestion
ctx1 = SSL.Context(SSL.TLSv1_2_METHOD) # Noncompliant:
```

I think this part belongs in the code rationale instead

2023-06-16 16:49 UTC, loris-s-sonarsource commented on rules/S4830/python/how-to-fix-it/ssl.adoc
> +ctx1 = ssl._create_unverified_context() # Noncompliant: by default certificate validation is not done
```suggestion
ctx1 = ssl._create_unverified_context() # Noncompliant
```

Same train of thought, I think it belongs in the code rationale instead.

And I have mixed feelings about adding multiple functions.  But I'm not sure so I'm not suggesting anything

2023-06-16 16:49 UTC, loris-s-sonarsource commented on rules/S4830/python/how-to-fix-it/ssl.adoc
> +[source,python,diff-id=1,diff-type=noncompliant]
```suggestion
[source,python,diff-id=1,diff-type=compliant]
```

2023-06-16 16:49 UTC, loris-s-sonarsource commented on rules/S4830/vbnet/how-to-fix-it/dot-net.adoc
> +Imports System.Net
Same suggestion as .Net Here

2023-06-16 16:49 UTC, loris-s-sonarsource commented on rules/S4830/docker/how-to-fix-it/common.adoc
> +== How to fix it
It's actually Curl instead of common right ?
```suggestion
== How to fix it in cURL
```

2023-06-19 14:25 UTC, hendrik-buchwald-sonarsource commented on docs/header_names/allowed_framework_names.adoc
> +* SSL
True, fixed.

2023-06-19 14:53 UTC, hendrik-buchwald-sonarsource commented on rules/S4830/common/fix/validation.adoc
> +appropriately.
True, it repeats itself. I have pushed a new version. It is very similar to your suggestion but also contains a transition to the subsections.

2023-06-19 14:57 UTC, hendrik-buchwald-sonarsource commented on rules/S4830/common/fix/validation.adoc
> +necessary certificates to your trust store.
I don't think it fits the pitfalls. It could fit the extra mile. On the other hand, it could be also considered part of the fix. After all, there was a reason somebody disabled certificate validation. So if they simply reenable it, that probably does not solve their problem.

2023-06-19 15:05 UTC, hendrik-buchwald-sonarsource commented on rules/S4830/docker/how-to-fix-it/common.adoc
> +== How to fix it
I am not convinced it makes sense to have a code sample for every command that the rule supports. curl is in this case also representing other commands like wget, thus I made this a common fix for now.

2023-06-19 15:52 UTC, loris-s-sonarsource commented on rules/S4830/common/fix/validation.adoc
> +necessary certificates to your trust store.
Oh, I see the point. Sounds good

2023-06-19 16:06 UTC, loris-s-sonarsource commented on rules/S4830/vbnet/how-to-fix-it/dot-net.adoc
> +Imports System.Net
It looks like it could look like this (I added both compliant and non compliant in the same snippet and took the current compliant from rspec:

``` vbnet
Imports System
Imports System.Linq
Imports System.Net
Imports System.Net.Security
				
Public Module Example
	Public Sub Main()
		Dim Development As Boolean = True
		Dim ValidCerts As String() = {"cert-example-1", "cert-example-2"}
		
		ServicePointManager.ServerCertificateValidationCallback = Function(sender, certificate, chain, errors) True ' Noncompliant
			
		ServicePointManager.ServerCertificateValidationCallback =
		Function(sender, certificate, chain, errors)
			If Development Then Return True ' For development, trust all certificates
			Return Errors = SslPolicyErrors.None AndAlso ValidCerts.Contains(certificate.GetCertHashString()) ' Compliant: trust only some certificates
		End Function
				
		Dim request As System.Net.HttpWebRequest = System.Net.HttpWebRequest.Create(New System.Uri("https://example.com"))
		request.Method = System.Net.WebRequestMethods.Http.Get
		Dim response As System.Net.HttpWebResponse = request.GetResponse()
		response.Close()
	End Sub
End Module
```

2023-06-19 16:08 UTC, loris-s-sonarsource commented on rules/S4830/vbnet/how-to-fix-it/dot-net.adoc
> +Imports System.Net
It looks like it could work, depending on the web. config file, out of scope here. In dotnetfiddle it looks like the webconfig file is configured to be safe so it does not work.

I think we can assume that users running into this rule will have it enabled and it will work for them

2023-06-19 16:09 UTC, loris-s-sonarsource commented on rules/S4830/docker/how-to-fix-it/common.adoc
> +== How to fix it
got it

2023-06-20 08:25 UTC, hendrik-buchwald-sonarsource commented on rules/S4830/vbnet/how-to-fix-it/dot-net.adoc
> +Imports System.Net
Okay, thanks!

2023-06-20 08:25 UTC, hendrik-buchwald-sonarsource commented on rules/S4830/cfamily/how-to-fix-it/botan.adoc
> +include::../../common/fix/code-rationale.adoc[]
Done. I hope it works :sweat_smile:

2023-06-20 09:07 UTC, loris-s-sonarsource requested changes
Minor Changes, else LGTM

2023-06-20 09:07 UTC, loris-s-sonarsource commented on rules/S4830/javascript/how-to-fix-it/node-js.adoc
> +  rejectUnauthorized: false
just to avoid unnecessary diff colors:
```suggestion
  rejectUnauthorized: false,
  secureProtocol: 'TLSv1_2_method'
```

2023-06-20 09:07 UTC, loris-s-sonarsource commented on rules/S4830/javascript/how-to-fix-it/node-js.adoc
> +});
```suggestion
const tls = require('node:tls');

let options = {
    secureProtocol: 'TLSv1_2_method'
};

let socket = tls.connect(443, "www.example.com", options, () => {
  process.stdin.pipe(socket);
  process.stdin.resume();
});
```

2023-06-20 09:07 UTC, loris-s-sonarsource commented on rules/S4830/javascript/how-to-fix-it/node-js.adoc
> +    rejectUnauthorized: false
```suggestion
    rejectUnauthorized: false,
    secureProtocol: 'TLSv1_2_method'
```

2023-06-20 09:07 UTC, loris-s-sonarsource commented on rules/S4830/javascript/how-to-fix-it/request.adoc
> +  rejectUnauthorized: false // Noncompliant
```suggestion
  rejectUnauthorized: false, // Noncompliant
  secureProtocol: 'TLSv1_2_method'
```

2023-06-20 10:09 UTC, loris-s-sonarsource approved these changes
LGTM

2023-06-20 11:26 UTC, merged