Modify Rule S2737: LaYC catch rethrow
SonarSource/rspec pull request #2193
Opened 2023-06-14 14:20 UTC by frederic-tingaud-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-15 12:11 UTC, amelie-renard-sonarsource requested changes

2023-06-16 14:32 UTC, frederic-tingaud-sonarsource commented on rules/S2737/java/code-example.adoc
> +public String readFile(File f) {
Not only is it too long, I don't think the fix we propose is good java because of try-with-resources.
I pinged the Java squad about it.

2023-06-16 14:32 UTC, frederic-tingaud-sonarsource commented on rules/S2737/vbnet/rule.adoc
Not sure "correctly" is super explicit. What do you think about this instead?

2023-06-16 15:02 UTC, amelie-renard-sonarsource commented on rules/S2737/vbnet/rule.adoc
Sounds good!

2023-06-16 15:03 UTC, amelie-renard-sonarsource approved these changes
(modulo the code example for Java)

2023-06-16 15:33 UTC, dorian-burihabwa-sonarsource commented on rules/S2737/java/code-example.adoc
> +}
How about this for a shorter example?
```suggestion
String firstLine;
try (FileReader fileReader = new FileReader(fileName);
      BufferedReader bufferedReader = new BufferedReader(fileReader)) {      
  firstLine = bufferedReader.readLine());
}
catch (IOException e) {  // Noncompliant
  throw e;
}
```

2023-06-16 17:10 UTC, frederic-tingaud-sonarsource commented on rules/S2737/java/code-example.adoc
> +}
@dorian-burihabwa-sonarsource: the problem if we keep a FileReader is that we can't show that the whole try should be removed. 
I guess we can still write
```java
String firstLine;
try (FileReader fileReader = new FileReader(fileName);
      BufferedReader bufferedReader = new BufferedReader(fileReader)) {      
  firstLine = bufferedReader.readLine());
}
```
but it has a bit more impact than the other languages.

2023-06-20 09:56 UTC, dorian-burihabwa-sonarsource commented on rules/S2737/java/code-example.adoc
> +public String readFile(File f) {
How about removing all resource opening logic like it is done in the other languages?
```java
public String readFile(File f) {
  String content;
  try {
    content = loadFromDisk(f);
  } catch (IOException e) {
    throw e;
  }
  return content;
}

```

2023-06-20 13:57 UTC, dorian-burihabwa-sonarsource requested changes
Reviewed the Java examples.

Sorry, I forgot to include the throwing clause in the method signature I originally suggested

2023-06-20 13:57 UTC, dorian-burihabwa-sonarsource commented on rules/S2737/java/compliant.adoc
> +public String readFile(File f) {
I guess we want to wash our hands off the exception handling here
```suggestion
public String readFile(File f) throws IOException {
```

2023-06-20 13:57 UTC, dorian-burihabwa-sonarsource commented on rules/S2737/java/code-example.adoc
> +public String readFile(File f) {
```suggestion
public String readFile(File f) throws IOException {
```

2023-06-20 14:00 UTC, frederic-tingaud-sonarsource commented on rules/S2737/java/compliant.adoc
> +public String readFile(File f) {
```suggestion
public String readFile(File f) throws IOException {
```

2023-06-22 12:04 UTC, merged