Modify rule S2589: LaYC format
SonarSource/rspec pull request #2195
Opened 2023-06-14 14:51 UTC by sebastien-marichal

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-14 16:37 UTC, martin-strecker-sonarsource requested changes

2023-06-14 16:37 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +When an operand of a https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#1224-boolean-expressions[boolean expression] does not influence the result i
I would not link to the C# spec. The spec is hard to read and for language enthusiasts only (You are free to keep the link, if you can explain to me what the `true` operator is, where it originates from, how it is used, how it relates to conditional and/or, and why it shouldn't be used anymore 🤯 ).

It can be shortened and made more precise like so:
```suggestion
An operand of a boolean expression that never changes the result of the expression can be removed.
```
While technically correct, I also think that it is confusing. Maybe you can mix it with the original message or keep the original message.

> If a boolean expression doesn’t change the evaluation of the condition, then it is entirely unnecessary, and can be removed. If it is gratuitous because it does not match the programmer’s intent, then it’s a bug and the expression should be fixed.

2023-06-14 16:37 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +[source,csharp,diff-id=1,diff-type=noncompliant]
Shouldn't this go into the `How to fix` section?

A minimal example for this section for illustration could be
```cs
if (true)
{
}
```
(I hope this raises the issue).

2023-06-14 16:37 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> -    if (a) // Noncompliant
Why was this example removed?

2023-06-14 16:37 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +    if (b && a)     // Noncompliant: "a" is always "true", only "b" will change the expression result
```suggestion
    if (b && a)     // Noncompliant: "a" is always "true" and can be removed
```

2023-06-14 16:37 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +    if (c || !a)    // Noncompliant: "!a" is always "false"
```suggestion
    if (c || !a)    // Noncompliant: "!a" is always "false" and can be removed
```

2023-06-14 16:37 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +Since one of the operands is unnecessary to the condition, the condition should be updated.
```suggestion
Since one of the operands is unnecessary to the conditions, the conditions should be updated.
```

2023-06-14 16:37 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#1218-conditional-operator[Conditional expression with the conditional operator in C#]
Don't link the spec. Use the Average Joe documentation instead
```suggestion
* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators#conditional-logical-and-operator-[Conditional logical AND operator &&]
* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators#conditional-logical-or-operator-[Conditional logical OR operator ||]
```

2023-06-14 16:37 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#1218-conditional-operator[Conditional expression with the conditional operator in C#]
Add the https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator link

2023-06-14 16:37 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +    var v2 = s ?? d;        // Noncompliant: "d" is always null and the produced value is always equal to s.
s is undefined

2023-06-14 16:37 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +    var v1 = d ?? "value";  // Noncompliant: "d" is always null
```suggestion
    var v1 = d ?? "value";  // Noncompliant: "d" is always null and v1 is always "value". 
```

2023-06-14 16:37 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +    var v2 = s ?? d;        // Noncompliant: "d" is always null and the produced value is always equal to s.
```suggestion
    var v2 = s ?? d;        // Noncompliant: "d" is always null and v2 is always equal to s.
```

2023-06-15 08:39 UTC, sebastien-marichal commented on rules/S2589/csharp/rule.adoc
> +When an operand of a https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions#1224-boolean-expressions[boolean expression] does not influence the result i
I believe mentioning the operand is important as `boolean expression` could be interpreted as the whole condition expression.

I will try to come up with something less confusing.

2023-06-15 08:47 UTC, sebastien-marichal commented on rules/S2589/csharp/rule.adoc
> -    if (a) // Noncompliant
The given compliant solution was to use a method within the condition. But another compliant solution could be to remove entirely the `if`.
I can add it back and remove the whole `if` as a better compliant example. Since it was my opinion I preferred to remove it.
WDYT?

2023-06-15 08:56 UTC, sebastien-marichal commented on rules/S2589/csharp/rule.adoc
> +[source,csharp,diff-id=1,diff-type=noncompliant]
Doesn't have to be in the `How to fix` section if not too complete, it is our call.
Since we try to have "blog-post" like description, I tend to have most of the content of the rules in the `why` section.

2023-06-15 11:54 UTC, sebastien-marichal commented on rules/S2589/csharp/rule.adoc
> +[source,csharp,diff-id=1,diff-type=noncompliant]
> ```cs
> if (true)
> {
> }
> ```

It does not raise, it has the same exception as [S2583](https://sonarsource.github.io/rspec/#/rspec/S2583/csharp). I will add the same exception section as S2583.

2023-06-15 12:04 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/metadata.json
> +  "title": "Boolean expressions should not be unnecessary"
> not necessary; with no reasonable cause

[Cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/gratuitous)

Seems very fitting to me

> not be unnecessary

is a double negative. "Boolean expressions should not be redundant" seems preferable to me. 

Gratuitous is used quite some times in different places.
https://github.com/search?q=repo%3ASonarSource%2Frspec%20gratuitous&type=code

But redundant is used much more often.
https://github.com/search?q=repo%3ASonarSource%2Frspec+redundant&type=code

I would keep it for the moment and add an issue to replace "gratuitous" with "redundant" after we have confirmation from the docs team (#guild-education).

2023-06-15 12:07 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +[source,csharp,diff-id=1,diff-type=noncompliant]
Fair enough, but you have two/three different kinds of examples and two different kinds of fixes (removal vs. correction). This should go into "how to fix", IMO.

2023-06-15 12:20 UTC, sebastien-marichal commented on rules/S2589/csharp/metadata.json
> +  "title": "Boolean expressions should not be unnecessary"
What about `Boolean expressions should be essential`?
I like the fact there is no negation anymore but I am not sure about "essential".

2023-06-15 12:30 UTC, martin-strecker-sonarsource requested changes

2023-06-15 12:30 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +An operand of a boolean expression that never changes the result of the expression might not match the programmer's intent and leads to unexpected behavior and potential bugs.
Looks good to me.
```suggestion
An operand of a boolean expression that never changes the result of the expression might not match the programmer's intent and can lead to unexpected behavior and potential bugs.
```

2023-06-15 12:30 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/metadata.json
> +  "title": "Boolean expressions should not be unnecessary"
> essential

I don't think this works. Let's stick with gracious for the moment and raise the issue in #guild-eduction

2023-06-15 12:30 UTC, martin-strecker-sonarsource commented on rules/S2589/metadata.json
> +  "title": "Boolean expressions should not be unnecessary",
It's probably better to not touch the title as it affects all languages. It's not worth it at the moment. If we want to get rid of gratuitous, we should do so in all rules at once. Just to be clear: I had to look up gratuitous as well. For me, it violates our guidelines:

> Try to use simple English and avoid slang. Assume users have high school-level English, equivalent to CEFR levels B1/B2, at best.

So we need confirmation and then remove it everywhere. That is done best in a dedicated PR.

2023-06-15 15:59 UTC, martin-strecker-sonarsource approved these changes
Some minor suggestions. All are optional.

2023-06-15 15:59 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +* to update the unnecessary operand
NIT: When viewed on GitHub, the bullet points do not show up. A new line is needed:
```suggestion

* to update the unnecessary operand
```

2023-06-15 15:59 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> ++
```suggestion
The unnecessary operand is removed:
```

2023-06-15 15:59 UTC, martin-strecker-sonarsource commented on rules/S2589/csharp/rule.adoc
> +[source,csharp,diff-type=compliant]
Let's give it a try.
```suggestion
[source,csharp,diff-id=1,diff-type=compliant]
```

2023-06-16 06:53 UTC, sebastien-marichal commented on rules/S2589/csharp/rule.adoc
> +[source,csharp,diff-type=compliant]
Unfortunately, it does not work 😞 
The main issue is what changed lines to display on the noncompliant example.
I let the `diff-type` if, at some point, this will be possible.

2023-06-16 07:28 UTC, merged