Modify rule S2583: LaYC format
SonarSource/rspec pull request #2196
Opened 2023-06-14 15:20 UTC by martin-strecker-sonarsource

[S2583](https://sonarsource.github.io/rspec/#/rspec/S2583/csharp)

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-14 15:23 UTC, martin-strecker-sonarsource commented on rules/S2583/metadata.json
> +  "quickfix": "partial"
The `d ?? "value"` case can be fixed.

2023-06-15 09:55 UTC, sebastien-marichal requested changes

2023-06-15 09:55 UTC, sebastien-marichal commented on rules/S2583/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator[Microsoft Learn] - ?? and ??= operators - the null-coalescing operators
```suggestion
* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators#conditional-logical-and-operator-[Microsoft Learn - Conditional logical AND operator &&]
* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators#conditional-logical-or-operator-[Microsoft Learn - Conditional logical OR operator ||]
* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator[Microsoft Learn - ?? and ??= operators - the null-coalescing operators]
```

2023-06-15 09:55 UTC, sebastien-marichal commented on rules/S2583/description.adoc
> +Conditional expressions which are always `true` or `false` can lead to dead code. Such code is always buggy and should never be used in production.
I would explain what "dead code" is; the user might not be familiar with this term. Also, we could add more details about its impact on an application
A link to the [wiki page](https://en.wikipedia.org/wiki/Dead_code) could be added.
Or maybe, we could change the term to [unreachable code](https://en.wikipedia.org/wiki/Unreachable_code), which is more precise for this rule (based on Wikipedia's definition).

2023-06-15 09:55 UTC, sebastien-marichal commented on rules/S2583/description.adoc
> +Conditional expressions which are always `true` or `false` can lead to dead code. Such code is always buggy and should never be used in production.
I don't agree with this statement or the term `buggy` is not appropriate here.

```suggestion
Conditional expressions which are always `true` or `false` can lead to dead code. Such code should never be used in production.
```

2023-06-15 09:55 UTC, sebastien-marichal commented on rules/S2583/metadata.json
> +  "quickfix": "partial"
The quickfix update should be in `csharp/metadata.json`, not sure we can take this decision for all squads.

2023-06-15 13:48 UTC, martin-strecker-sonarsource commented on rules/S2583/description.adoc
> +Conditional expressions which are always `true` or `false` can lead to dead code. Such code is always buggy and should never be used in production.
I agree. I changed it now and I'm asking myself what "Such code should never be used in production." is conveying as information to the user? I would say this sentence needs clarification (what is production code) and is also confusing: Why is it okay to do it in non-production code, like test code? What about removing that part as well?

2023-06-15 14:51 UTC, sebastien-marichal requested changes
Only left is to add more details in the description, IMO.

2023-06-15 14:51 UTC, sebastien-marichal commented on rules/S2583/description.adoc
> +Conditional expressions which are always `true` or `false` can lead to dead code. Such code is always buggy and should never be used in production.
We should remove it, I agree, it does not make sense.
We could replace this part with a small paragraph about the impact with an example such as unreachable code with a `Dispose` call or some other critical statement.

2023-06-16 10:27 UTC, merged