Handle variables *inside* an include
SonarSource/rspec pull request #2229
Opened 2023-06-16 17:23 UTC by frederic-tingaud-sonarsource

The point of this branch is the change in validate_asciidoc.sh. The rest is taken from another PR and should not be reviewed.

2023-06-20 13:24 UTC, necto requested changes
I did not run it, it seems like it should work, and I see you've successfully tested it on the S107 commit.
I presume that you'll merge the functional change independently of the rule modification.

P.S. Perhaps on 7th iteration, you'll reimplement asciidoctor in bash

2023-06-20 13:24 UTC, necto commented on ci/replace_variables_in_path.sh
> +AFTER=$(echo "$2" | sed -r "s/include::(.*)\{(.*)\}(.*)\[\]/\3/")
These three are the same regular expression. Let's make it obvious by aligning them
```suggestion
BEFORE=$(echo "$2" | sed -r "s/include::(.*)\{(.*)\}(.*)\[\]/\1/")
VAR=$(echo "$2"    | sed -r "s/include::(.*)\{(.*)\}(.*)\[\]/\2/")
AFTER=$(echo "$2"  | sed -r "s/include::(.*)\{(.*)\}(.*)\[\]/\3/")
```

2023-06-20 14:17 UTC, marco-antognini-sonarsource reviewed
Some minor suggestions.

I notice that if `a.adoc` includes `b.adoc` and `b.adoc` includes `a.adoc` there won't be an error. Handling this could be quite hard though, and probably it won't happen in practice. So I'm not requesting fixing it. Maybe just add a comment about this limitation?

2023-06-20 14:17 UTC, marco-antognini-sonarsource commented on ci/replace_variables_in_path.sh
> +#!/bin/bash
Can you add a comment explaining what are the input $1 and $2 and what this does? I think I got it (substitute the variable in the path with its actual value read from another file) but future readers may not. :)

2023-06-20 14:17 UTC, marco-antognini-sonarsource commented on ci/replace_variables_in_path.sh
> +BEFORE=$(echo "$2" | sed -r "s/include::(.*)\{(.*)\}(.*)\[\]/\1/")
This will not work if there is more than one variable. The grep command in the main script will however match (`grep -Eh "include::.*\{"`).

Not sure how this should be handled. I'd suggest keeping it simple and emit an error.

2023-06-20 14:17 UTC, marco-antognini-sonarsource commented on ci/validate_asciidoc.sh
>      orphans=$(comm -1 -3 <(sort -u included) <(sort -u created))
I'm not familiar with `comm` but shouldn't there be only one argument, namely `-3`?

2023-06-21 10:48 UTC, frederic-tingaud-sonarsource commented on ci/replace_variables_in_path.sh
> +AFTER=$(echo "$2" | sed -r "s/include::(.*)\{(.*)\}(.*)\[\]/\3/")
done

2023-06-21 10:48 UTC, frederic-tingaud-sonarsource commented on ci/validate_asciidoc.sh
> +    find "$dir" -name "*.adoc" -execdir sh -c 'grep -Eh ":\w+:\s+[A-Za-z0-9\/-]+" "$1" | sed -r "s/:(\w+):\s+([A-Za-z0-9\/-]+)/\1\t\2/"' shell {} \; > vars
Great, thanks!

2023-06-21 10:48 UTC, frederic-tingaud-sonarsource commented on ci/replace_variables_in_path.sh
> +BEFORE=$(echo "$2" | sed -r "s/include::(.*)\{(.*)\}(.*)\[\]/\1/")
Added a check for that

2023-06-21 10:48 UTC, frederic-tingaud-sonarsource commented on ci/replace_variables_in_path.sh
> +#!/bin/bash
done

2023-06-21 10:48 UTC, frederic-tingaud-sonarsource commented on ci/replace_variables_in_path.sh
> +set -uo pipefail
fixed

2023-06-21 10:50 UTC, frederic-tingaud-sonarsource commented on ci/validate_asciidoc.sh
>      orphans=$(comm -1 -3 <(sort -u included) <(sort -u created))
the `-1` and `-3` are actually minuses to remove these columns from the result.

2023-06-21 12:05 UTC, marco-antognini-sonarsource commented on ci/validate_asciidoc.sh
>      orphans=$(comm -1 -3 <(sort -u included) <(sort -u created))
Right, I misread the man page!

2023-06-21 12:09 UTC, marco-antognini-sonarsource approved these changes
Thanks for the update. I guess now the first commit can be removed. :-)

2023-06-22 09:44 UTC, necto approved these changes

2023-06-22 09:45 UTC, merged