Modify rule S2755: LaYC format
SonarSource/rspec pull request #2245
Opened 2023-06-20 10:04 UTC by hendrik-buchwald-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-20 14:25 UTC, hendrik-buchwald-sonarsource commented on rules/S2755/java/how-to-fix-it/java-se.adoc
> +// To be compliant, completely disable DOCTYPE declaration:
I know that this structure is not perfect since we try not to convey important information through comments anymore. But in this case, I would keep it like this for now. If I would move every possibility to its own code block, it would get really messy (and code diff would not work anymore).

2023-06-21 08:58 UTC, loris-s-sonarsource requested changes
Some comments

2023-06-21 08:58 UTC, loris-s-sonarsource commented on rules/S2755/java/how-to-fix-it/java-se.adoc
> +// To be compliant, completely disable DOCTYPE declaration:
Unfortunately, this is really hard to read. 

To improve the situation, I suggest:

* Getting rid of non compliant examples. They have no value to users getting this error
* Making multiple sections (illustrated below)
* Getting the setExpandEntityReferences code to an extra-mile section, also the bug has been fixed and can be removed.
* For this one I think we should omit imports and illustrative functions


``` 
// extra-mile
==== Disable entity Expansion
Specifically for 'DocumentBuilderFactory', it is possible to disable the entity
extension. Note, however, that this does not prevent the retrieval of external
entities.

[source, java]
----
factory.setExpandEntityReferences(false);
----
```

Suggestion for the whole compliant code:

```
Protection from XXE can be done in several different ways. Choose one depending
on how the affected parser object is used in your code.

**1.** The first way is to completely disable DOCTYPE declarations:

[source, java]
----
// Applicable to:
// - DocumentBuilderFactory 
// - SAXParserFactory 
// - SchemaFactory
factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);

// For XMLInputFactory:
factory.setProperty(XMLInputFactory.SUPPORT_DTD, false);
----

**2.** Disable external entity declarations completely:

[source, java]
----
// Applicable to:
// - DocumentBuilderFactory 
// - SAXParserFactory 
factory.setFeature("http://xml.org/sax/features/external-general-entities", false);
factory.setFeature("http://xml.org/sax/features/external-parameter-entities", false);

// For XMLInputFactory:
factory.setProperty(XMLInputFactory.IS_SUPPORTING_EXTERNAL_ENTITIES, Boolean.FALSE);
----

**3.** Prohibit the use of all protocols by external entities:

[source, java]
----
// `setAttribute` variant, applicable to:
// - DocumentBuilderFactory 
// - TransformerFactory 
factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");

// `setProperty` variant, Applicable to:
// - XMLInputFactory 
// - SchemaFactory 
factory.setProperty(XMLConstants.ACCESS_EXTERNAL_DTD, "");
factory.setProperty(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");

// For SAXParserFactory, the prohibition is done on child objects:
SAXParser parser = factory.newSAXParser();
parser.setProperty(XMLConstants.ACCESS_EXTERNAL_DTD, "");
parser.setProperty(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
----
```

2023-06-21 08:58 UTC, loris-s-sonarsource commented on rules/S2755/java/how-to-fix-it/jdom2.adoc
> +SAXBuilder builder = new SAXBuilder(); // Noncompliant
It is lacking imports and function. Here is a sample:

```
import org.jdom2.input.SAXBuilder;

public class Program
{
    public static void main(String[] args) {
		SAXBuilder builder = new SAXBuilder(); // Noncompliant
	}
}
```

2023-06-21 08:58 UTC, loris-s-sonarsource commented on rules/S2755/javascript/how-to-fix-it/libxmljs.adoc
> +                       );
```suggestion
libxmljs.parseXmlString(xml, {
    noblanks: true,
    noent: true, // Noncompliant
    nocdata: true
});
```

2023-06-21 08:58 UTC, loris-s-sonarsource commented on rules/S2755/python/how-to-fix-it/lxml.adoc
> +----
missing the import:

```
from lxml import etree
```

2023-06-21 08:58 UTC, loris-s-sonarsource commented on rules/S2755/python/how-to-fix-it/std.adoc
> +----
```suggestion
----
import xml.sax
```

2023-06-21 08:58 UTC, loris-s-sonarsource commented on rules/S2755/python/rule.adoc
> -message: 'This function loads the XML code and triggers the vulnerability.'
Note: I checked and this is not the message that's actually sent back to users

2023-06-21 11:50 UTC, hendrik-buchwald-sonarsource commented on rules/S2755/common/fix/code-rationale.adoc
> +processing enabled and as a result are vulnerable to XXE attacks in case that
True, I did not notice how complicated the sentence got :laughing:

2023-06-21 12:35 UTC, hendrik-buchwald-sonarsource commented on rules/S2755/impact.adoc
> +
Agreed, forgot about that.

2023-06-21 12:39 UTC, hendrik-buchwald-sonarsource commented on rules/S2755/python/rule.adoc
> -message: 'This function loads the XML code and triggers the vulnerability.'
Okay :+1: Yes, I think it will be the case for many rules that the actual messages do not match what is specified here in RSPEC. It is not a perfect system.

2023-06-21 15:12 UTC, hendrik-buchwald-sonarsource commented on rules/S2755/rationale.adoc
> +
I have removed the impact from here. I would also rather not add the suggestion as I feel this applies to every vulnerability and is not really helpful here for the developer trying to fix the bug.

2023-06-21 15:23 UTC, hendrik-buchwald-sonarsource commented on rules/S2755/java/how-to-fix-it/java-se.adoc
> +// To be compliant, completely disable DOCTYPE declaration:
True, I also did not think that the compliant samples were providing value. I just left them in, so that I could use the diff feature. But I like the new approach, makes it more readable.

2023-06-21 15:40 UTC, hendrik-buchwald-sonarsource commented on rules/S2755/common/fix/xxe.adoc
> +
I don't think this is the right approach in this case and not what I meant. Some libraries provide the functionality to specify which entities can be expanded. I would have liked to also add code samples for that but it would extend past the scope of the sprint.

I will add a sentence to clarify what I mean.

2023-06-22 08:45 UTC, loris-s-sonarsource approved these changes
LGTM ! Minor suggestions

2023-06-22 08:45 UTC, loris-s-sonarsource commented on rules/S2755/cfamily/how-to-fix-it/libxml2.adoc
> +  XercesDOMParser *DOMparser = new XercesDOMParser();
```suggestion
```

2023-06-22 08:45 UTC, loris-s-sonarsource commented on rules/S2755/cfamily/how-to-fix-it/xerces.adoc
> +By default, XercesDOMParser is safe.
```suggestion
By default, `XercesDOMParser` is safe.
```

2023-06-22 08:45 UTC, loris-s-sonarsource commented on rules/S2755/csharp/how-to-fix-it/dot-net.adoc
> +XmlDocument is safe by default since .NET Framework 4.5.2. For older versions,
```suggestion
`XmlDocument` is safe by default since .NET Framework 4.5.2. For older versions,
```

2023-06-22 08:45 UTC, loris-s-sonarsource commented on rules/S2755/csharp/how-to-fix-it/dot-net.adoc
> +set XmlResolver explicitly to `null`.
```suggestion
set `XmlResolver` explicitly to `null`.
```

2023-06-22 08:45 UTC, loris-s-sonarsource commented on rules/S2755/java/how-to-fix-it/java-se.adoc
> +**1.** The first way is to completely disable DOCTYPE declarations:
```suggestion
**1.** The first way is to completely disable `DOCTYPE` declarations:
```

2023-06-22 08:45 UTC, loris-s-sonarsource commented on rules/S2755/java/how-to-fix-it/jdom2.adoc
> +  builder.setProperty(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
```suggestion
    SAXBuilder builder = new SAXBuilder(); 
    builder.setProperty(XMLConstants.ACCESS_EXTERNAL_DTD, "");
    builder.setProperty(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
```

2023-06-22 08:45 UTC, loris-s-sonarsource commented on rules/S2755/javascript/how-to-fix-it/libxmljs.adoc
> +`readFileSync` is safe by default.
```suggestion
`parseXmlString` is safe by default.
```

2023-06-22 08:45 UTC, loris-s-sonarsource commented on rules/S2755/php/how-to-fix-it/core.adoc
> +External entity substitution is disabled by default.
```suggestion
External entity substitution is disabled by default in `simplexml_load_string()` and `DOMDocument::open()`.
```

2023-06-22 08:45 UTC, loris-s-sonarsource commented on rules/S2755/php/how-to-fix-it/core.adoc
> +External entity substitution is disabled by default.
```suggestion
```

2023-06-22 08:45 UTC, loris-s-sonarsource commented on rules/S2755/python/how-to-fix-it/std.adoc
> +import xml.sax
```suggestion
import xml.sax

```

2023-06-22 08:45 UTC, loris-s-sonarsource commented on rules/S2755/python/how-to-fix-it/std.adoc
> +parser = xml.sax.make_parser()
```suggestion
import xml.sax

parser = xml.sax.make_parser()
```

2023-06-22 09:25 UTC, merged