Modify Rule S6468: LaYC format
SonarSource/rspec pull request #2246
Opened 2023-06-20 12:02 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-22 13:16 UTC, guillaume-dequenne-sonarsource commented on rules/S6468/python/rule.adoc
> +Group exceptions should only be caught with ``++except++`.
There is an extra backtick ` here.

2023-06-22 13:22 UTC, guillaume-dequenne-sonarsource reviewed
Looks good! I left a small suggestion as I feel we could enrich this rule description a bit.

2023-06-22 13:22 UTC, guillaume-dequenne-sonarsource commented on rules/S6468/python/rule.adoc
> +Python 3.11 introduced ``++except*++`` and ``++ExceptionGroup++`` which allows to handle and raise multiple unrelated exceptions simultaneously.
To be honest, I'm not so familiar with the `except*` syntax.
I feel like this will be the case for many users and that maybe we could take the opportunity to briefly explain how `except*` is intended to be used.
Maybe even one of the code examples could show this (though this may get a bit too much).

2023-06-23 07:15 UTC, joke1196 commented on rules/S6468/python/rule.adoc
> +Python 3.11 introduced ``++except*++`` and ``++ExceptionGroup++`` which allows to handle and raise multiple unrelated exceptions simultaneously.
Great thank you. I have added a small example to show the usage of except* and ExceptionGroup, I think it makes more sens and help understanding the issue raised

2023-06-26 10:00 UTC, guillaume-dequenne-sonarsource requested changes
Suggesting some minor changes.
Great example to explain what `except*` and `ExceptionGroup` are for.

2023-06-26 10:20 UTC, joke1196 commented on rules/S6468/python/rule.adoc
> +In the example below we gather multiple exceptions in a group which is then handled by a single expect block:
Yes thank you! I will rephrase it as well to remove the allow.

2023-06-26 15:16 UTC, guillaume-dequenne-sonarsource approved these changes
Looks good, left two very minor comments.

2023-06-26 15:16 UTC, guillaume-dequenne-sonarsource commented on rules/S6468/python/rule.adoc
> +In the example below, we gather multiple exceptions in a group which is then handled by a single expect block:
I think a comma before the "which" is still needed.

2023-06-26 15:16 UTC, guillaume-dequenne-sonarsource commented on rules/S6468/python/rule.adoc
> +except* ExceptionGroup:  # Noncompliant: Type error
It would probably be better to write the exception name verbatim: "TypeError".

2023-06-27 08:44 UTC, joke1196 commented on rules/S6468/python/rule.adoc
> +In the example below, we gather multiple exceptions in a group which is then handled by a single expect block:
I am having a hard telling if it is or not a restrictive clause. Still, there is an issue with the subject so I revamped the phrase a bit, removing the `which` altogether. I think it works better also with the second example.

2023-06-29 13:36 UTC, jean-jimbo-sonarsource approved these changes

2023-06-30 07:11 UTC, merged