Modify rule S6481: Adapt to LaYC
SonarSource/rspec pull request #2254
Opened 2023-06-20 15:06 UTC by victor-diez-sonarsource

2023-06-22 14:53 UTC, vilchik-elena requested changes
The rule has a double negation, how about simplifying it?

2023-06-22 14:53 UTC, vilchik-elena commented on rules/S6481/javascript/rule.adoc
>  Providing values like an object to a React `Context` will provoke additional re-renders as
`like an object`? very scientific :D Could we be more precise?

2023-06-22 14:53 UTC, vilchik-elena commented on rules/S6481/javascript/rule.adoc
>  React doesn't know the object is the same.
```suggestion
React doesn't know the value is the same.
```

2023-06-22 14:53 UTC, vilchik-elena commented on rules/S6481/javascript/rule.adoc
> +This can significantly impact performance since the whole component tree will be re-rendered each time.
Is it intentional to have these 2 sentences in one paragraph? IMHO I would split and move the first one to the previous paragraph as before.

2023-06-22 14:53 UTC, vilchik-elena commented on rules/S6481/javascript/rule.adoc
> +Wrapping the value in a `useMemo` hook will avoid additional render passes.
```suggestion
To avoid additional render passes wrap the value in a `useMemo` hook.
```

2023-06-22 14:53 UTC, vilchik-elena commented on rules/S6481/javascript/rule.adoc
>  [source,javascript]
add compliant comment

2023-06-28 07:40 UTC, vilchik-elena requested changes

2023-06-28 07:40 UTC, vilchik-elena commented on rules/S6481/javascript/rule.adoc
> +Because each Javascript object carries its identity, object or function expressions get a new identity every run. These should not be used as Context `value` because React will always consider they h
What is `every run` in the first sentence?

2023-06-28 07:40 UTC, vilchik-elena commented on rules/S6481/javascript/rule.adoc
> +  const foo = useMemo(() => ({foo: 'bar'}), []); { /* Compliant: value is cached by useMemo */ }
rename variable so that property and variable name are not the same

2023-06-28 07:40 UTC, vilchik-elena commented on rules/S6481/javascript/rule.adoc
>      <SomeContext.Provider value={foo}>
I would better have compliant comment here (while leaving `/* value is cached by useMemo */ ` where it's now)

2023-06-28 07:40 UTC, vilchik-elena commented on rules/S6481/javascript/rule.adoc
> +  const foo = useMemo(() => ({foo: 'bar'}), []); { /* Compliant: value is cached by useMemo */ }
why comment is in the curly braces?

2023-06-28 07:40 UTC, vilchik-elena commented on rules/S6481/javascript/rule.adoc
> +    <SomeContext.Provider value={{foo: 'bar'}}> { /* Noncompliant: value is an object expression */ }
```suggestion
    <SomeContext.Provider value={{foo: 'bar'}}> { /* Noncompliant: value is an object literal */ }
```

2023-06-28 08:59 UTC, victor-diez-sonarsource commented on rules/S6481/javascript/rule.adoc
> +Because each Javascript object carries its identity, object or function expressions get a new identity every run. These should not be used as Context `value` because React will always consider they h
every execution of the expression? don't know how to put it more clear

2023-06-28 09:01 UTC, victor-diez-sonarsource commented on rules/S6481/javascript/rule.adoc
> +  const foo = useMemo(() => ({foo: 'bar'}), []); { /* Compliant: value is cached by useMemo */ }
typo

2023-06-28 11:53 UTC, vilchik-elena approved these changes

2023-06-28 11:54 UTC, vilchik-elena approved these changes

2023-06-28 11:55 UTC, merged