Modify rule S5714: LaYC format
SonarSource/rspec pull request #2262
Opened 2023-06-21 12:38 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-22 15:53 UTC, guillaume-dequenne-sonarsource commented on rules/S5714/python/rule.adoc
>  The only two possible types for an ``++except++``'s expression are a class deriving from ``++BaseException++``, or a tuple composed of such classes (or an old style class if you are using python 2, b
`python` should be capitalized here.
I'm not sure whether we should rephrase the Python 2 bit as well, knowing it's less and less common to use Python 2.

2023-06-22 15:54 UTC, guillaume-dequenne-sonarsource commented on rules/S5714/python/rule.adoc
> +Instead use a tuple of the exceptions that should be caught in the ``++except++`` block.
We should have an `How to fix it` section here.

2023-06-23 12:17 UTC, joke1196 commented on rules/S5714/python/rule.adoc
>  The only two possible types for an ``++except++``'s expression are a class deriving from ``++BaseException++``, or a tuple composed of such classes (or an old style class if you are using python 2, b
I have moved it to a note as it it not as important in order to understand the rule.

2023-06-23 15:50 UTC, guillaume-dequenne-sonarsource commented on rules/S5714/python/rule.adoc
> +The result of a boolean expression of exceptions is a single exception class, thus using a boolean expression in an ``++except++`` block will result in catching only one kind of exception.
Here, maybe a code snippet would make things clearer.

2023-06-23 15:52 UTC, guillaume-dequenne-sonarsource commented on rules/S5714/python/rule.adoc
> +Instead of using a boolean expression in a ``++except++`` block, try using a tuple of the exceptions that should be caught.
I think phrasing the recommendation as `Make sure to...` rather than `Try...` sounds a bit stronger and confident. Which is probably what we want, given this is an obvious bug.
I'd also probably focus on what should be done rather than what should not be done (i.e not starting with the "instead" clause).

2023-06-26 07:34 UTC, joke1196 commented on rules/S5714/python/rule.adoc
> +The result of a boolean expression of exceptions is a single exception class, thus using a boolean expression in an ``++except++`` block will result in catching only one kind of exception.
I have added a small example, tell me if you think this is not enough

2023-06-26 09:08 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM.

2023-06-30 07:39 UTC, jean-jimbo-sonarsource commented on rules/S5714/python/rule.adoc
> +*Note*: __In Python 2 it is possible to raise exception from and old-style class which do not derive from ``++BaseException++``.__
Fix grammar:
*Note*: __In Python 2 it is possible to raise an exception from an old-style class that does not derive from ``++BaseException++``.__

2023-06-30 07:40 UTC, jean-jimbo-sonarsource requested changes
added a grammar fix

2023-07-04 09:09 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-07-04 09:11 UTC, merged