Modify rule S5722: LaYC format
SonarSource/rspec pull request #2263
Opened 2023-06-21 14:04 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-23 09:31 UTC, guillaume-dequenne-sonarsource commented on rules/S5722/python/rule.adoc
> -=== Noncompliant code example
Here is missing a `How to fix it` section.

2023-06-23 12:38 UTC, joke1196 commented on rules/S5722/python/rule.adoc
> -=== Noncompliant code example
I moved the code example to the how to fix section. I think it is ok like that but we could still move it back if needed as the examples are quite concise as well.

2023-06-23 15:48 UTC, guillaume-dequenne-sonarsource requested changes
Left some suggestons.

2023-06-23 15:48 UTC, guillaume-dequenne-sonarsource commented on rules/S5722/python/rule.adoc
> +Each special methods have a specific number of parameters, the Python interpreter will call these methods with those parameters. Every call to a special method will throw a ``++TypeError++`` if it is
I think `Each special method expects a specific number of parameters.` (with singular and full stop) sounds a bit better.
I'd also rephrase `Every call to a special method will throw a ``++TypeError++`` if it is defined with an incorrect number of parameters.`
to
`Calls to a special method will throw a ``++TypeError++`` if it is defined with an incorrect number of parameters.`

2023-06-23 15:48 UTC, guillaume-dequenne-sonarsource commented on rules/S5722/python/rule.adoc
> +Try using the same signature defined in the Python documentation for each special methods.
I'd say `Make sure to use the same signature as defined in the Python documentation for each special methods`.

2023-06-23 15:48 UTC, guillaume-dequenne-sonarsource commented on rules/S5722/python/rule.adoc
> +Python allows developers to customize how code is interpreted by defining special methods (also called magic methods). For example, it is possible to override how the multiplication operator (``++a *
Here there is an uncapitalized `python`.

2023-06-26 09:06 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM.

2023-06-30 07:41 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-06-30 08:35 UTC, merged