Modify rule S5724: LaYC format
SonarSource/rspec pull request #2264
Opened 2023-06-21 14:28 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-23 08:50 UTC, guillaume-dequenne-sonarsource commented on rules/S5724/python/rule.adoc
> -=== Noncompliant code example
I think we're missing the `How to fix it` section here.

2023-06-23 08:56 UTC, guillaume-dequenne-sonarsource commented on rules/S5724/python/rule.adoc
>  Property getter, setter and deleter methods are called by the python interpreter with a specific number or arguments:
`python` should be capitalized here.
Probably we could have a small explanation on the `@property` and `x.setter` decorators and what they do.

I'm also unsure how conventional/Pythonic it is to have getters and setters being defined as `get_x`, `set_x`, etc... Maybe we can mention that it is a conventional way to define getters and setters and that the contract of these methods should therefore be predictable (I assume that no `TypeError` would be thrown if I were to create my custom setter that takes multiple values at once - but it might be a weird API).

2023-06-23 09:30 UTC, guillaume-dequenne-sonarsource commented on rules/S5724/python/rule.adoc
> +Adding any other parameter, or removing these mandatory parameters will throw a TypeError exception at runtime.
Referring to this as the `TypeError` may not be thrown for a custom-defined getter/setter.

2023-06-23 13:29 UTC, joke1196 commented on rules/S5724/python/rule.adoc
>  Property getter, setter and deleter methods are called by the python interpreter with a specific number or arguments:
It's true if you don't use the `property` method or decorator you can use x.get_x with any number of parameters, just like any normal method. I think the rule makes sense really if we want to have a property accessor and mutator in order to use `x.x = 1` or `del x.x`.

2023-06-23 13:34 UTC, guillaume-dequenne-sonarsource commented on rules/S5724/python/rule.adoc
>  Property getter, setter and deleter methods are called by the python interpreter with a specific number or arguments:
Oh right, I missed the `foo = property(get_foo, set_foo, del_foo, "'foo' property.") ` of the `class B` example and was afraid the rule was simply reporting on method names...
My bad!

2023-06-26 07:23 UTC, joke1196 commented on rules/S5724/python/rule.adoc
> +Creating property accessor and mutator is quite common in Object-Oriented Programming. Python provides two main ways of implementing getters, setters and deleters; either with the ``++@property++`` d
Yes good catch thank you

2023-06-26 09:00 UTC, guillaume-dequenne-sonarsource requested changes
Looks good overall, I'm wondering if we can make the example a bit more explicit and the wording a bit better though.

2023-06-26 09:49 UTC, joke1196 commented on rules/S5724/python/rule.adoc
> +----
Yes good call. It make sense. I have added the comments not sure if it is understantable with the methods under a decorator.

2023-06-26 09:51 UTC, joke1196 commented on rules/S5724/python/rule.adoc
> +This code example allows for such programs:
Ok so I tried something in the mean time without the `allow`. Hopefully it makes it easier to understand.

2023-06-26 15:27 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM.
Left a minor comment on grammar.

2023-06-30 07:46 UTC, jean-jimbo-sonarsource approved these changes
Thorough.

2023-06-30 08:35 UTC, merged