Modify S5527: Learn-As-You-Code migration
SonarSource/rspec pull request #2269
Opened 2023-06-21 15:56 UTC by loris-s-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-26 13:56 UTC, hendrik-buchwald-sonarsource requested changes
See the comments for details.

2023-06-26 13:56 UTC, hendrik-buchwald-sonarsource commented on rules/S5527/python/how-to-fix-it/std.adoc
> +`_create_unverified_context` or `_create_stdlib_context` is used. It is
Just a note, I wouldn't actually change this for now: those examples already confused me in another rule. Since the methods start with underscores, those seem to be functions that should not be called directly outside of the module.

2023-06-26 13:56 UTC, hendrik-buchwald-sonarsource commented on rules/S5527/python/how-to-fix-it/std.adoc
> +example = ssl.create_default_context()
The text above says that `_create_default_https_context` should be called. Though, if `create_default_context` is actually secure that seems like the better approach to me since the method does not start with an underscore.

2023-06-26 13:56 UTC, hendrik-buchwald-sonarsource commented on rules/S5527/rationale.adoc
> +authentifying `example.com`, serve it using a totally different hostname, and
```suggestion
authentifying `example.com`, serve it using a different hostname, and
```

It could be totally different but it does not have to be totally different. It could also be slightly different. So I just wouldn't mention that part.

2023-06-26 13:56 UTC, hendrik-buchwald-sonarsource commented on rules/S5527/rationale.adoc
> +authentifying `example.com`, serve it using a totally different hostname, and
I don't think `authentifying` is a common word. I am not saying it is wrong (e.g. there is [this](https://en.wiktionary.org/wiki/authentifying)) but if you search for [it](https://www.google.com/search?channel=fs&client=ubuntu&q=%22authentifying%22),  you don't find many "serious" sites. So to keep the text easy, I would recommend a different word.

2023-06-26 13:56 UTC, hendrik-buchwald-sonarsource commented on rules/S5527/rationale.adoc
> +To do so, an attacker would create, buy, or steal a correct certificate
```suggestion
To do so, an attacker would obtain a valid certificate
```

Buying a certificate would probably still include creating it. How about:

2023-06-27 13:13 UTC, loris-s-sonarsource reviewed
acting upon the review

2023-06-27 13:13 UTC, loris-s-sonarsource commented on rules/S5527/java/how-to-fix-it/java-ee.adoc
> +import javax.mail.PasswordAuthentication;
Yes, I removed the last part to avoid hardcoding a password

2023-06-27 13:13 UTC, loris-s-sonarsource commented on rules/S5527/java/how-to-fix-it/java-se.adoc
> +== How to fix it in Java SE
I wondered the same, and actually javax is not necessarily equal to java ee (it means java extension). In that case, https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/HttpsURLConnection.html is actually noted as Java SE in the docs

2023-06-27 13:13 UTC, loris-s-sonarsource commented on rules/S5527/kotlin/how-to-fix-it/ok-http.adoc
> +      override fun verify(hostname: String?, session: SSLSession?): Boolean { // Noncompliant
Yes, wondered the same and it's actually "verify", the function name, that is highlighted in SQ

2023-06-28 12:04 UTC, hendrik-buchwald-sonarsource requested changes
I think there is still a bit of work to do in the fix section.

2023-06-28 12:04 UTC, hendrik-buchwald-sonarsource commented on rules/S5527/common/fix/validation.adoc
> +* Set the correct host name in the `/etc/hosts` file.
I don't think the readers would understand what they are supposed to do here and it is probably not even necessary. Since you suggest using a self-signed certificate, they can just use localhost.

2023-06-28 13:05 UTC, loris-s-sonarsource reviewed
post-review changes

2023-06-28 13:05 UTC, loris-s-sonarsource commented on rules/S5527/common/fix/validation.adoc
> +* Set the correct host name in the `/etc/hosts` file.
```suggestion
* If the hostname is not `localhost`, set the correct host name in the `/etc/hosts` file.
```

2023-06-28 13:05 UTC, loris-s-sonarsource commented on rules/S5527/common/fix/validation.adoc
> +* Set the correct host name in the `/etc/hosts` file.
I just changed it. Do you think it still make sense or would you still delete it ?

2023-06-28 13:06 UTC, loris-s-sonarsource commented on rules/S5527/java/how-to-fix-it/apache-commons-email.adoc
> +==== Compliant code example
```suggestion
==== Compliant solution
```

2023-06-28 13:06 UTC, loris-s-sonarsource commented on rules/S5527/java/how-to-fix-it/java-ee.adoc
> +==== Compliant code example
```suggestion
==== Compliant solution
```

2023-06-28 13:06 UTC, loris-s-sonarsource commented on rules/S5527/java/how-to-fix-it/java-se.adoc
> +==== Compliant code example
```suggestion
==== Compliant solution
```

2023-06-28 13:06 UTC, loris-s-sonarsource commented on rules/S5527/kotlin/how-to-fix-it/ok-http.adoc
> +==== Compliant code example
```suggestion
==== Compliant solution
```

2023-06-28 13:11 UTC, loris-s-sonarsource commented on rules/S5527/common/fix/validation.adoc
> +* If the hostname is not `localhost`, set the correct host name in the `/etc/hosts` file.
```suggestion
* If the hostname is not `localhost`, set the correct host name in the `/etc/hosts` file.

```

2023-06-28 13:11 UTC, loris-s-sonarsource commented on rules/S5527/common/fix/validation.adoc
> +* If the hostname is not `localhost`, set the correct host name in the `/etc/hosts` file.
```suggestion
* If the hostname is not `localhost`, add the hostname in the `/etc/hosts` file.
```

2023-06-28 13:15 UTC, loris-s-sonarsource commented on rules/S5527/common/fix/validation.adoc
> +sections.
```suggestion
recommended to first re-enable the default validation and fix the root cause: the validity of the certificate.
```

2023-06-28 13:16 UTC, loris-s-sonarsource commented on rules/S5527/common/fix/validation.adoc
> +is no other choice, try following this solution:
```suggestion
as this creates unnecessary dependencies and can lead to reliability issues.

Therefore, the first solution is to change the remote host's certificate to
match its identity. If the remote host is not under your control, consider replicating its
service to a server whose certificate you can change yourself.

In case the contacted host is located on a development machine, and if there
is no other choice, try following this solution:
```

2023-06-28 13:30 UTC, hendrik-buchwald-sonarsource approved these changes
LGTM :+1:  The tests are failing though.

2023-06-28 15:11 UTC, merged