Modify rule S5659: LaYC format
SonarSource/rspec pull request #2272
Opened 2023-06-22 08:30 UTC by hendrik-buchwald-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-22 15:21 UTC, hendrik-buchwald-sonarsource commented on docs/header_names/allowed_framework_names.adoc
> +* Java JWT
These are 2 different libraries.

2023-06-26 12:05 UTC, loris-s-sonarsource requested changes
GutenTag!

2023-06-26 12:05 UTC, loris-s-sonarsource commented on rules/S5659/python/how-to-fix-it/python-jwt.adoc
> +to verify the signature of the token.
Here, I am also divided about the value of adding this sentence. It's hard to tell, but combining the fact we have only two lines and the text that I suggest in the .Net comment, this could be removed

2023-06-26 12:05 UTC, loris-s-sonarsource commented on rules/S5659/python/how-to-fix-it/python-jwt.adoc
> +jwt.verify_jwt(token, key, algo)
I suggest actually adding a recommended algorithm there

2023-06-26 12:05 UTC, loris-s-sonarsource commented on rules/S5659/vbnet/how-to-fix-it/jwt-net.adoc
> +When using `Decode`, make sure to explicitly set `verify` to `true`.
Same comments as in C# here, just commenting to have an anchor

2023-06-26 12:28 UTC, hendrik-buchwald-sonarsource commented on docs/header_names/allowed_framework_names.adoc
> -* OpenSSL
It is twice in the file.

2023-06-26 12:32 UTC, hendrik-buchwald-sonarsource commented on rules/S5659/common/extra-mile/key-rotation.adoc
> +may be compromised. Therefore, it is a good practice to periodically rotate your
No, this is a bit of general advice on how to be even more secure when using JWT tokens.

2023-06-26 12:35 UTC, hendrik-buchwald-sonarsource commented on rules/S5659/common/extra-mile/key-storage.adoc
> +Ensure that your secret keys are stored securely. They should not be hard-coded
Yea, I also think it makes sense here. It fits the "extra mile" section quite nicely. Without this, I wouldn't be surprised if some people just hard-code the key to sign in their application.

2023-06-26 14:26 UTC, hendrik-buchwald-sonarsource commented on rules/S5659/comments-and-links.adoc
> -* Compliant Code: \https://github.com/we45/Vulnerable-Flask-App/blob/752ee16087c0bfb79073f68802d907569a1f0df7/app/app.py#L86
I can delete it but all checks are green.

2023-06-27 07:23 UTC, hendrik-buchwald-sonarsource commented on rules/S5659/common/extra-mile/key-rotation.adoc
> +secret keys. By doing so, you limit the amount of time that an attacker can
The secret can't be revoked and directly next to this text is the section about key storage, so I don't want to duplicate that part. So I could write "rotate your keys, i.e. change it" but do you really think that is necessary? Rotate is a pretty normal English word.

2023-06-28 12:18 UTC, loris-s-sonarsource approved these changes
LGTM, 1 minor change

2023-06-28 12:18 UTC, loris-s-sonarsource commented on rules/S5659/common/fix/decode.adoc
> +verification might be unintentionally skipped or bypassed.
Oohh nice ! We could even get to the next mile and give examples, but that might be too much haha

2023-06-28 12:18 UTC, loris-s-sonarsource commented on rules/S5659/javascript/how-to-fix-it/jsonwebtoken.adoc
> +const jwt = require('jsonwebtoken');
```suggestion
```

2023-06-28 14:26 UTC, merged