Modify S5756: LaYC format
SonarSource/rspec pull request #2279
Opened 2023-06-23 12:05 UTC by guillaume-dequenne-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-26 08:41 UTC, joke1196 requested changes
Looks good, I have just added a small comment

2023-06-26 14:10 UTC, guillaume-dequenne-sonarsource commented on rules/S5756/python/rule.adoc
> +In order to be callable, a Python class should implement the {link-with-uscores1}[``++__call__++``] method.
I added a small sentence saying that and moved the code example to the first tab, hopefully that should help.

2023-06-26 14:42 UTC, joke1196 approved these changes
LGTM!

2023-06-30 07:06 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-06-30 07:13 UTC, merged