Modify S5632: LaYC format
SonarSource/rspec pull request #2281
Opened 2023-06-23 12:42 UTC by guillaume-dequenne-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-26 14:49 UTC, joke1196 requested changes

2023-06-26 14:49 UTC, joke1196 commented on rules/S5632/python/rule.adoc
> +Attempting to raise an object which does not derive from BaseException will raise a ``++TypeError++``.
BaseException here could be highlighted I think.

2023-06-26 14:52 UTC, joke1196 commented
LGTM! Just added a small formatting comment.

2023-06-26 14:56 UTC, guillaume-dequenne-sonarsource commented on rules/S5632/python/rule.adoc
> +Attempting to raise an object which does not derive from BaseException will raise a ``++TypeError++``.
Good catch, thanks.

2023-06-28 09:09 UTC, joke1196 approved these changes
LGTM!

2023-06-30 07:02 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-06-30 07:13 UTC, merged