Modify S5905: LaYC format
SonarSource/rspec pull request #2284
Opened 2023-06-23 15:34 UTC by guillaume-dequenne-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-26 07:49 UTC, joke1196 commented on rules/S5905/python/rule.adoc
> +The ``++assert++`` statement does not take parentheses around its parameters. Calling ``++assert(x, y)++`` will test if the tuple ``++(x, y)++`` is True, which is always the case.
Small suggestion: we could maybe say why a nonempty tuple is truthy all the time.

2023-06-26 08:43 UTC, joke1196 requested changes
Looks good to me. Just added a small suggestion.

2023-06-26 14:51 UTC, joke1196 approved these changes
LGTM! I like the added explanation

2023-06-26 16:33 UTC, jean-jimbo-sonarsource commented on rules/S5905/python/rule.adoc
> +When tested for truthiness, a sequence or collection will evaluate to `False` if it's empty (its ``++__len__++`` method returns 0) and to `True` if it contains at least one element.
We should use "if it is empty", rather than the contracted "if it's empty"

2023-06-29 13:21 UTC, jean-jimbo-sonarsource approved these changes
NLGTM

2023-06-30 07:14 UTC, merged