Modify Rule S3363: Add VB.NET description
SonarSource/rspec pull request #2285
Opened 2023-06-23 15:41 UTC by zsolt-kolbay-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-04 18:00 UTC, cristian-ambrosini-sonarsource commented on rules/S3363/vbnet/rule.adoc
> +include::../introduction-dotnet.adoc[]
As discussed via Slack, I suggest moving the list from the `Introduction` to the `Why is this an issue` section, it looks a bit weird visually

2023-07-04 18:03 UTC, cristian-ambrosini-sonarsource requested changes

2023-07-04 18:03 UTC, cristian-ambrosini-sonarsource commented on rules/S3363/csharp/rule.adoc
> -
Opinion: I think this empty line separates a bit the Key highlighting what the rule is focusing on

2023-07-04 18:03 UTC, cristian-ambrosini-sonarsource commented on rules/S3363/csharp/rule.adoc
> +    [Key]
Why? It should work even without the attribute

2023-07-05 12:20 UTC, zsolt-kolbay-sonarsource commented on rules/S3363/csharp/rule.adoc
> +    [Key]
I renamed the property to `PersonIdentifier`. Now it requires the `[Key]` attribute.

2023-07-05 12:23 UTC, cristian-ambrosini-sonarsource approved these changes
LGTM

2023-07-05 13:35 UTC, csaba-sagi-sonarsource approved these changes
LGTM!

2023-07-05 14:54 UTC, merged