Modify rule S5708: LaYC format
SonarSource/rspec pull request #2287
Opened 2023-06-26 13:08 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-27 07:36 UTC, guillaume-dequenne-sonarsource commented on rules/S5708/python/rule.adoc
> +When creating a custom Exception class, note that it should inherit from `Exception`, not `BaseException`. `Exception` allows people to catch all exceptions except the ones explicitly asking the inte
This sentence was also in the description of S5632 (and I changed it slightly). I think it would be better to stay consistent here as well.

2023-06-28 07:56 UTC, joke1196 commented on rules/S5708/python/rule.adoc
> +When creating a custom Exception class, note that it should inherit from `Exception`, not `BaseException`. `Exception` allows people to catch all exceptions except the ones explicitly asking the inte
Yes, thank you, I have reused the sentence from S5632.

2023-06-28 10:08 UTC, guillaume-dequenne-sonarsource requested changes
Looks good overall, left some suggestion for further improvement.

2023-06-28 10:08 UTC, guillaume-dequenne-sonarsource commented on rules/S5708/python/rule.adoc
> +*Note*: __In Python 2 it is possible to raise old-style classes, which do not inherit from BaseException.__
Should we say to raise, to catch, or both here (to raise and catch)?
Also I feel like the note about `BaseException` vs `Exception` might be more relevant here than the one about Python 2. Wdyt? (I think this is also how it was done for S5632).

2023-06-28 10:08 UTC, guillaume-dequenne-sonarsource commented on rules/S5708/python/rule.adoc
> +This rule raises an issue when the expression used in an `except` statement is not a class deriving from `BaseException` nor a tuple of such classes.
I'm not sure about the grammar, but isn't neither/nor more correct? (vs not/nor)

2023-06-28 10:08 UTC, guillaume-dequenne-sonarsource commented on rules/S5708/python/rule.adoc
>  [source,python]
I'm wondering if we could make the example better and use the diff view?
Maybe by clearly separating the case where we catch an invalid custom exception from the one where we catch a list of exception?
I feel we could drop the case where we have a tuple of random objects, as well as the one with the set. I don't feel they add so much value. Wdyt?

Also, if the resulting example is small, maybe we can consider keeping everything in one tab here as well.

2023-06-28 11:15 UTC, joke1196 commented on rules/S5708/python/rule.adoc
>  [source,python]
Yes, I think it fits nicely in one tab with the more concise example.

2023-06-28 11:20 UTC, joke1196 commented on rules/S5708/python/rule.adoc
> +This rule raises an issue when the expression used in an `except` statement is not a class deriving from `BaseException` nor a tuple of such classes.
Apparently, both are possible, but not/nor does not seems to be the default way :).

2023-06-28 11:24 UTC, joke1196 commented on rules/S5708/python/rule.adoc
> +*Note*: __In Python 2 it is possible to raise old-style classes, which do not inherit from BaseException.__
Yes, I have reworked the layout a bit and moved up the `BaseException` vs `Exception`, higher up in the description, and left the Python 2 note lower in the page as it is less relevant.

2023-06-28 12:49 UTC, guillaume-dequenne-sonarsource approved these changes
Left a final comment.
Looks good otherwise!

2023-06-28 12:49 UTC, guillaume-dequenne-sonarsource commented on rules/S5708/python/rule.adoc
> +except [TypeError, ValueError]:  # Noncompliant: lists or sets are not accepted.
Sorry, I realize I could have commented on this before, but I find the word "accepted" a bit odd in this context.
I also don't think we should mention set at all since we got rid of the example anyway (it seems too specific).

Maybe saying "Noncompliant: list of exceptions (only tuples are valid)", with or without the parenthesised bit, would be a bit clearer.

2023-06-29 12:52 UTC, jean-jimbo-sonarsource commented on rules/S5708/python/rule.adoc
> +To fix this issue, make sure the expression used in an `expect` statement is an exception which derives from `BaseException`/`Exception` or a tuple of such exceptions.
Change expect to except

2023-06-29 12:52 UTC, jean-jimbo-sonarsource requested changes
Found typo (expect vs except)

2023-06-30 06:37 UTC, jean-jimbo-sonarsource commented on rules/S5708/python/rule.adoc
> +In Python 3, attempting to catch in an `except` statement an object which does not derive from `BaseException` will raise a `TypeError`.
This sentence can be less complex when the words are reordered. I suggest "Attempting to catch an object that does not derive from `BaseException` in Python 3's `except` statement, will raise a TypeError" or similar.

2023-06-30 06:37 UTC, jean-jimbo-sonarsource requested changes
Left a rewording comment

2023-06-30 07:35 UTC, joke1196 commented on rules/S5708/python/rule.adoc
> +In Python 3, attempting to catch in an `except` statement an object which does not derive from `BaseException` will raise a `TypeError`.
I have tried something in between. Tell me what you think.

2023-07-03 06:48 UTC, jean-jimbo-sonarsource approved these changes

2023-07-03 07:01 UTC, merged