Modify rule S1206: LaYC format
SonarSource/rspec pull request #2290
Opened 2023-06-26 14:57 UTC by gregory-paidis-sonarsource

2023-06-26 14:59 UTC, gregory-paidis-sonarsource commented on rules/S1206/java/rule.adoc
> -include::../description.adoc[]
Description, noncompliant and compliant were used only here, so I inlined them.

2023-06-27 09:02 UTC, mary-georgiou-sonarsource requested changes

2023-06-27 09:02 UTC, mary-georgiou-sonarsource commented on rules/S1206/java/rule.adoc
> +If two objects are equal according to the ``++equals(Object)++`` method, then calling the ``++hashCode++`` method on each of the two objects must produce the same integer result.
I guess java part is out of scope right? I'm not reviewing this?

2023-06-27 09:02 UTC, mary-georgiou-sonarsource commented on rules/S1206/csharp/rule.adoc
> +When you want to use `Equals` and `GetHashCode`, either override both of them, or simply inherit them.
```suggestion
When you override `Equals` then you have to override also `GetHashCode`. You have to override both of them, or simply inherit them.
```

2023-06-27 10:15 UTC, gregory-paidis-sonarsource commented on rules/S1206/java/rule.adoc
> +If two objects are equal according to the ``++equals(Object)++`` method, then calling the ``++hashCode++`` method on each of the two objects must produce the same integer result.
you could look that everything looks correct, I just moved stuff around.

2023-06-27 10:16 UTC, gregory-paidis-sonarsource commented on rules/S1206/csharp/rule.adoc
> +ifdef::env-github,rspecator-view,env-vscode[]
By using this flag, you can render this part locally in vscode. It works like an environment variable, useful for development, no impact in the product.

2023-06-27 12:31 UTC, mary-georgiou-sonarsource commented on rules/S1206/csharp/rule.adoc
> +ifdef::env-github,rspecator-view,env-vscode[]
Cool thanks - I'll use it too.

2023-06-27 12:35 UTC, mary-georgiou-sonarsource approved these changes
LGTM

2023-06-27 12:35 UTC, merged