Modify rule S3456: LaYC format
SonarSource/rspec pull request #2291
Opened 2023-06-26 15:01 UTC by mary-georgiou-sonarsource

2023-06-26 15:28 UTC, mary-georgiou-sonarsource commented
@Tim-Pohlmann  this rule has a quickfix - so no need to review.

2023-06-28 09:04 UTC, Tim-Pohlmann requested changes
I suggest a rewrite to make it easier to understand.

2023-06-28 09:04 UTC, Tim-Pohlmann commented on rules/S3456/csharp/rule.adoc
> +The `String` and the utf-8 literals types offer an indexer property that allows you to treat them as an array of chars directly without the need to call `ToCharArray`.
I think this would be easier to understand if you flip it around:
1. Strings have an indexer and an enumerator that treat them as char-arrays.
2. Therefore, calls to `ToCharArray` can sometimes be omitted.
3. Not omitting the calls makes the code harder to read and can hurt performance.
4. The same applies to `Span<byte>.ToArray()`.

2023-06-28 09:04 UTC, Tim-Pohlmann commented on rules/S3456/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/api/system.string.tochararray[String.ToCharArray Method]
Sort by relevance:
```suggestion
* https://learn.microsoft.com/en-us/dotnet/api/system.string.tochararray[String.ToCharArray Method]
* https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#accessing-individual-characters[Accessing individual characters]
* https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/utf8-string-literals[UTF-8 Strings literals]
```

2023-06-28 11:42 UTC, Tim-Pohlmann approved these changes
LGTM! Just some minor adjustments.

2023-06-28 11:42 UTC, Tim-Pohlmann commented on rules/S3456/csharp/rule.adoc
> +The `string` type offers an indexer property that allows you to treat it as a `char array, therefore, if you just need to access a specific character or iterate over all of them, the `ToCharArray` ca
Much better! Just some minor improvements:
```suggestion
The `string` type offers an indexer property that allows you to treat it as a `char` array. Therefore, if you just need to access a specific character or iterate over all of them, the `ToCharArray` call should be omitted. For these cases, not omitting makes the code harder to read and less performant as `ToCharArray` copies the characters from the `string` object into a new Unicode character array.
```

2023-06-28 11:42 UTC, Tim-Pohlmann commented on rules/S3456/csharp/rule.adoc
> +Same principle applies to https://devblogs.microsoft.com/dotnet/csharp-11-preview-updates/#utf-8-string-literals[utf-8 literals types] (`ReadOnlySpan<byte>`, `Span<byte>`).
```suggestion
The same principle applies to https://devblogs.microsoft.com/dotnet/csharp-11-preview-updates/#utf-8-string-literals[utf-8 literals types] (`ReadOnlySpan<byte>`, `Span<byte>`) and the https://learn.microsoft.com/en-us/dotnet/api/system.span-1.toarray?view=net-7.0[`ToArray`] method.
```

2023-06-28 12:02 UTC, merged