Modify rule S2259: LaYC format
SonarSource/rspec pull request #2294
Opened 2023-06-26 15:47 UTC by sebastien-marichal

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-27 11:56 UTC, martin-strecker-sonarsource requested changes

2023-06-27 11:56 UTC, martin-strecker-sonarsource commented on rules/S2259/csharp/exceptionCode1.adoc
> +    public static string ToUpper(this string value)
"ToUpper" is a bad example. It is shadowed by the instance method ToUpper and is therefore never called. Use something easy like "RemoveVowels" instead :
```
return Regex.Replace(value, "[aeoui]*","", RegexOptions.IgnoreCase);
```
See [sharplab.io](https://sharplab.io/#v2:C4LgTgrgdgPgAgJgIwFgBQcAMACOSB0AIgJYCGA5lAPYDOwxAxjfgMJUAmApgIJSkA2ATxrEaAbnRZcBACqcAHsHwAlTuQj9SYAKLyADmE40RVKOPSSAzNIBsuBNhbYA3umzvsbjwG04AdhAAOSpgQI1+AEkAM2DQ8IAKPgBbTioo+IA3AQhOAEpc7ABdL3c4azw7PEwAfmxVJKoMzgA1KgB3Tn4aeOAAC1FpGuws/hzckpcJj2xiKOxM7M5sAF5l7Chw8bRp6ddtnYP/dfCJfYOAXymPI9VyBRVOPU0GTgXRzgAabAAib1JUiDEQoAKm+H2+YLqagUAHk9PRTMwIpQqIYWKQaHlTtNLmdPHjEAgJnsDqUkABOeLfXjATRQegMbAwl6kKDfB4NJqtDpdeL5bGkvCU+LxKrVXIbfj8XIcxotdqdbr8ia485AA)

2023-06-27 11:56 UTC, martin-strecker-sonarsource commented on rules/S2259/csharp/rule.adoc
> +    var o = GetValue();
How is o guaranteed to be not null in this case? Use `var o = new object();` instead.

2023-06-27 11:56 UTC, martin-strecker-sonarsource commented on rules/S2259/csharp/rule.adoc
> +    Console.WriteLine(input.ToString()); // Noncompliant: 'input' might be null
We only raise, if there is a code path indicating that `input` might be null:
```cs
if (input is null)
{
  // do something
}
// We learned from the if that input might be null
input.ToString(); // Noncompliant

2023-06-27 11:56 UTC, martin-strecker-sonarsource commented on rules/S2259/dotnet-why.adoc
> +There is some scenario to which this rule won't raise:
```suggestion
In the following cases, the rule does not raise:
```

2023-06-27 11:56 UTC, martin-strecker-sonarsource commented on rules/S2259/dotnet-why.adoc
> +* value has been previously validated by creating a `ValidatedNotNull` or `NotNull` attribute and used on method parameter
```suggestion
* value has been validated by a helper method annotated with a `ValidatedNotNull` attribute
```

2023-06-27 11:56 UTC, martin-strecker-sonarsource commented on rules/S2259/dotnet-why.adoc
> +* value has been previously validated by creating a `ValidatedNotNull` or `NotNull` attribute and used on method parameter
There are more options on how to suppress the warning:
These attributes are available in .Net core only but can be redefined in custom code and will be recognized by us:
* [NotNullAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullattribute?view=net-7.0) same behavior as ValidatedNotNull
* NotNullWhen [see](https://github.com/SonarSource/sonar-dotnet/blob/8fc3b67ae9e293bf0ed77f68aa4de9fdfe3294ab/analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.NetCore.cs#L92) same behavior as described in the [docs](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullwhenattribute?view=net-7.0) 
* DoesNotReturn [see](https://github.com/SonarSource/sonar-dotnet/blob/8fc3b67ae9e293bf0ed77f68aa4de9fdfe3294ab/analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs#L209) and [TerminatesProgram](https://github.com/SonarSource/sonar-dotnet/blob/8fc3b67ae9e293bf0ed77f68aa4de9fdfe3294ab/analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.cs#L212C40-L212C40) Same behavior as described in the [docs](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.doesnotreturnattribute?view=net-7.0) and [here](https://blog.jetbrains.com/dotnet/2012/08/15/contract-annotations-in-resharper-7/)
* [DoesNotReturnIfAttribute](https://github.com/SonarSource/sonar-dotnet/blob/8fc3b67ae9e293bf0ed77f68aa4de9fdfe3294ab/analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs#L1687) behaves like described in the [docs](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.doesnotreturnifattribute?view=net-7.0)

* Debug.Assert: [see](https://github.com/SonarSource/sonar-dotnet/blob/8fc3b67ae9e293bf0ed77f68aa4de9fdfe3294ab/analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.cs#L375)

We also support the bang operator:

* Bang operator [see](https://github.com/SonarSource/sonar-dotnet/blob/8fc3b67ae9e293bf0ed77f68aa4de9fdfe3294ab/analyzers/tests/SonarAnalyzer.UnitTest/TestCases/SymbolicExecution/Roslyn/NullPointerDereference.CSharp8.Nullable.cs#L20)

2023-06-29 06:30 UTC, martin-strecker-sonarsource commented on rules/S2259/dotnet-why.adoc
> +* value has been previously validated by creating a `ValidatedNotNull` or `NotNull` attribute and used on method parameter
The test case comment is wrong. That is a TP as `o1` is known to be null at that point.

2023-06-29 07:02 UTC, martin-strecker-sonarsource requested changes

2023-06-29 07:02 UTC, martin-strecker-sonarsource commented on rules/S2259/why-dotnet.adoc
> +* code is unreachable
I think this causes errors in the ascii doc validation as it requires a newline around the includes:
> ERROR: These adoc files contain an include that is stuck to other content.
This may result in broken tags and other display issues.
Make sure there is an empty line before and after each include

 Given that we have a lot of exceptions, I would suggest using headings instead of the bullet list to resolve this.

2023-06-29 13:41 UTC, martin-strecker-sonarsource requested changes
I made some suggestions to make the examples a bit more concise. Feel free to apply the changes.

2023-06-29 13:41 UTC, martin-strecker-sonarsource commented on rules/S2259/csharp/exception-code-extension-method.adoc
> +    public static string? RemoveVowels(this string? value)
```suggestion
    public static string RemoveVowels(this string value)
```

2023-06-29 13:41 UTC, martin-strecker-sonarsource commented on rules/S2259/csharp/exception-code-analysis-attr.adoc
> +        }
I find this if quite confusing. You have another example with unreachable code later. I don't see the need to repeat unreachable code here. The `return value.ToUpper();` is enough.
```suggestion
```

2023-06-29 13:41 UTC, martin-strecker-sonarsource commented on rules/S2259/csharp/exception-code-extension-method.adoc
> +using System.Diagnostics.CodeAnalysis;
```suggestion
```

2023-06-29 13:41 UTC, martin-strecker-sonarsource commented on rules/S2259/csharp/exception-code-extension-method.adoc
> +        Console.WriteLine("Atlantic Ocean".RemoveVowels());
```suggestion
```

2023-06-29 13:41 UTC, martin-strecker-sonarsource commented on rules/S2259/vbnet/exception-code-analysis-attr.adoc
> +        End If
```suggestion
```

2023-06-29 13:41 UTC, martin-strecker-sonarsource commented on rules/S2259/vbnet/exception-code-extension-method.adoc
> +        Console.WriteLine(StrValue.RemoveVowels())
```suggestion
```

2023-06-29 13:41 UTC, martin-strecker-sonarsource commented on rules/S2259/vbnet/rule.adoc
> +:noncompliantCode: vbnet/noncompliant-code.adoc
You can get rid of all the variables by instead defining `:language: vbnet` (and `:language: csharp` respectively).

2023-06-29 13:41 UTC, martin-strecker-sonarsource commented on rules/S2259/csharp/exception-code-rider-attr.adoc
> +    public void TerminatesProgram() { }
What do you think about adding an `Environment.FailFast("A catastrophic failure has occurred.");` call?

https://learn.microsoft.com/en-us/dotnet/api/system.environment.failfast?view=net-7.0

I'm not sure if it is a good idea but it would show what the method is supposed to do. (Same would apply to VB).

2023-06-29 14:58 UTC, sebastien-marichal commented on rules/S2259/csharp/exception-code-rider-attr.adoc
> +    public void TerminatesProgram() { }
I think this is a good idea as you mention to exactly show what the method does.

2023-06-29 14:58 UTC, sebastien-marichal commented on rules/S2259/vbnet/rule.adoc
> +:noncompliantCode: vbnet/noncompliant-code.adoc
Nice idea, although I don't know if it will pass the validation.
I tried we will see.

2023-06-29 15:02 UTC, sebastien-marichal commented on rules/S2259/vbnet/rule.adoc
> +:noncompliantCode: vbnet/noncompliant-code.adoc
It worked!

2023-07-03 07:44 UTC, martin-strecker-sonarsource requested changes

2023-07-03 07:44 UTC, martin-strecker-sonarsource commented on rules/S2259/csharp/rule.adoc
> +Values marked with the https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving[null forgiving operator]
```suggestion
Expressions marked with the https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving[null forgiving operator]
```

2023-07-03 07:44 UTC, martin-strecker-sonarsource commented on rules/S2259/csharp/rule.adoc
> +    o!.ToString();    // Compliant: the null forgiving operator suppresses the nullable warning
```suggestion
    o!.ToString();    // Compliant: the null forgiving operator suppresses the null reference warning
```

2023-07-03 07:44 UTC, martin-strecker-sonarsource commented on rules/S2259/rule.adoc
> -== Why is this an issue?
Is this file really unused or do we need to copy it to the cfamilly folder?

2023-07-03 07:44 UTC, martin-strecker-sonarsource commented on rules/S2259/vbnet/noncompliant-code.adoc
> +    Console.WriteLine(Input.ToString()) ' Noncompliant: 'Input' might be Nothing
```suggestion
    Console.WriteLine(Input.ToString) ' Noncompliant: 'Input' might be Nothing
```

2023-07-03 07:44 UTC, martin-strecker-sonarsource commented on rules/S2259/why-dotnet.adoc
> +Unreachable is by definition not executed, thus `{null-keyword}` values will never be accessed.
```suggestion
Unreachable code is not executed, thus `{null-keyword}` values will never be accessed.
```

2023-07-03 07:44 UTC, martin-strecker-sonarsource commented on rules/S2259/why-dotnet.adoc
> +https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis[Nullable analysis attributes] provides more accurate semantic information when performing static analys
```suggestion
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis[Nullable analysis attributes] enable the developer to annotate methods with information about the null-state of its arguments. Thus, potential `{null-keyword}` values validated by one of the following attributes will not raise:
```

2023-07-03 07:44 UTC, martin-strecker-sonarsource commented on rules/S2259/why-dotnet.adoc
> +When values are validated to not be `{null-keyword}` with https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.assert[Debug.Assert] it is safe to access it.
```suggestion
A value validated with https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.assert[Debug.Assert] to not be `{null-keyword}`  is safe to access.
```

2023-07-03 07:44 UTC, martin-strecker-sonarsource commented on rules/S2259/why-dotnet.adoc
> +* https://learn.microsoft.com/en-us/dotnet/api/microsoft.validatednotnullattribute[ValidatedNotNullAttribute]
```suggestion
* https://learn.microsoft.com/en-us/dotnet/api/microsoft.validatednotnullattribute[ValidatedNotNullAttribute] (The attribute is interpreted the same as the https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullattribute[NotNullAttribute])
```

2023-07-03 07:44 UTC, martin-strecker-sonarsource commented on rules/S2259/csharp/exception-code-analysis-attr.adoc
> +public sealed class NotNullAttribute : Attribute { }
```suggestion
public sealed class NotNullAttribute : Attribute { } // The alternative name 'ValidatedNotNullAttribute' is also supported
```

2023-07-03 07:44 UTC, martin-strecker-sonarsource commented on rules/S2259/why-dotnet.adoc
> ++
```suggestion
```

2023-07-03 07:44 UTC, martin-strecker-sonarsource commented on rules/S2259/vbnet/exception-code-rider-attr.adoc
> +    Public Sub TerminatesProgram()
```suggestion
    Public Sub TerminateProgram()
```

2023-07-03 07:44 UTC, martin-strecker-sonarsource commented on rules/S2259/vbnet/exception-code-rider-attr.adoc
> +        TerminatesProgram()
```suggestion
        TerminateProgram()
```

2023-07-03 08:29 UTC, sebastien-marichal commented on rules/S2259/rule.adoc
> -== Why is this an issue?
It was not included at all, cfamily `rule.adoc` is almost the same but better (it includes the right cpp attribute for code snippets for instance).

2023-07-03 08:45 UTC, sebastien-marichal commented on rules/S2259/why-dotnet.adoc
> ++
It is intended to have the Rider example at the same indentation level as the bullet point.
The current example is about the `TerminatesProgramAttribute`, that's why.
I am also OK to have it at the root level as a single example for the whole Rider section if you think that's OK.

2023-07-03 15:13 UTC, martin-strecker-sonarsource approved these changes
There are two unresolved comments above. Otherwise LGTM.

2023-07-03 15:26 UTC, merged