Modify S2734: LaYC format
SonarSource/rspec pull request #2297
Opened 2023-06-27 10:01 UTC by guillaume-dequenne-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-28 09:24 UTC, joke1196 commented on rules/S2734/python/rule.adoc
> +To fix this issue, make sure that the ``++__init__++`` method does not return anything.
I think this sentence is a bit confusing because of the sentence: `The __init__ method is required to return None.`  Maybe we could rephrase the previous sentence something like:  A ``++TypeError++`` will be raised if the ``++__init__++`` method either yields or returns any expression other than ``++None++``. While returning None will not raise an error, it is considered a bad practice. Removing the return statement altogether is preferred. 

Than  it makes more sense with the __init__ method should not have a return statement

2023-06-28 09:28 UTC, joke1196 requested changes
Looks good! Not sure if changes are needed, but I left a small comment for some potential clarification.

2023-06-28 14:14 UTC, joke1196 commented on rules/S2734/python/rule.adoc
>  == Why is this an issue?
I noticed the description is missing.

2023-06-28 14:17 UTC, joke1196 requested changes
Looks good like this! I think it works well with this wording. I have just added a comment as I only notice now the description is missing, sorry about that.

2023-06-28 14:20 UTC, guillaume-dequenne-sonarsource commented on rules/S2734/python/rule.adoc
>  == Why is this an issue?
Good catch, thanks!

2023-06-28 14:28 UTC, joke1196 approved these changes
LGTM!

2023-06-29 07:02 UTC, joke1196 approved these changes
LGTM!

2023-06-29 12:41 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-06-30 07:16 UTC, merged