Modify rule S2201: LaYC format
SonarSource/rspec pull request #2301
Opened 2023-06-27 11:51 UTC by mary-georgiou-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-27 12:44 UTC, gregory-paidis-sonarsource requested changes
The rewrite is very good! Requested some extra links to documentation, and a few parsing fixes.

2023-06-27 12:44 UTC, gregory-paidis-sonarsource commented on rules/S2201/csharp/rule.adoc
> +* LINQ methods,
You need a new line before starting a list. If you look at the [highlighted point](https://github.com/SonarSource/rspec/blob/97f15451cae5ad38710ac5f48055fded1c871136/rules/S2201/csharp/rule.adoc#:~:text=methods%20are%20ignored%3A), it is rendered as a one-liner. 

Fix:

```
blabla
              <- empty line
* one
* two
* three
```

2023-06-27 12:44 UTC, gregory-paidis-sonarsource commented on rules/S2201/csharp/rule.adoc
> +* `[Pure]` methods,
I would suggest to link the following in this list:

- [LINQ](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/)
- [Pure](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.contracts.pureattribute)
- [built-in types](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/built-in-types)
- [Immutable collections](https://learn.microsoft.com/en-us/archive/msdn-magazine/2017/march/net-framework-immutable-collections)

(and the same as well at the resources->documentation)

2023-06-27 12:44 UTC, gregory-paidis-sonarsource commented on rules/S2201/csharp/rule.adoc
> -* although ``++string.Intern++`` has a side effect, ignoring its return value is still suspicious as it is the only reference ensured to point to the intern pool.
Link `string.Intern` please

2023-06-27 12:44 UTC, gregory-paidis-sonarsource commented on rules/S2201/csharp/rule.adoc
> +Such code should be rewritten as a loop because `Enumerable.All<TSource>` method should be used to determine if all elements satisfy a condition and not to change their state.
I would also link `Enumerable.All` here

2023-06-27 12:44 UTC, gregory-paidis-sonarsource commented on rules/S2201/csharp/rule.adoc
> +foreach( var x in data)
Very nitpicky: empty space before `var`

2023-06-27 12:44 UTC, gregory-paidis-sonarsource commented on rules/S2201/csharp/rule.adoc
> -This rule doesn't report issues on method calls with ``++out++`` or ``++ref++`` arguments.
I would also link `out` and `ref` here, since it's not something most juniors might use

2023-06-27 12:44 UTC, gregory-paidis-sonarsource commented on rules/S2201/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.contracts.pureattribute[PureAttribute documentation]
I am not sure if we have a guideline for this, but when linking stuff on this section, we usually name them the same as the documentation it points to, so for example this one would be `PureAttribute Class`. Personally I like this, since it's a no-brainer when you are adding links.

I will leave this as optional, since I am not sure if it's enforced.

2023-06-27 12:44 UTC, gregory-paidis-sonarsource commented on rules/S2201/csharp/rule.adoc
> -This rule doesn't report issues on method calls with ``++out++`` or ``++ref++`` arguments.
(same in Documentation)

2023-06-27 12:46 UTC, mary-georgiou-sonarsource commented on rules/S2201/csharp/rule.adoc
> +* `[Pure]` methods,
Good idea! thanks.

2023-06-27 12:52 UTC, mary-georgiou-sonarsource commented on rules/S2201/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.contracts.pureattribute[PureAttribute documentation]
sounds good to me.

2023-06-27 13:49 UTC, gregory-paidis-sonarsource requested changes
Looks good, 2 minor changes requested

2023-06-27 13:49 UTC, gregory-paidis-sonarsource commented on rules/S2201/csharp/rule.adoc
> +foreach(var x in data)
nitpick: add a space after `foreach`

(did not see it before, sorry)

2023-06-27 13:49 UTC, gregory-paidis-sonarsource commented on rules/S2201/csharp/rule.adoc
> +* https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/[LINQ],
unnecessary comma `,` at the end of `LINQ`

2023-06-28 07:35 UTC, gregory-paidis-sonarsource approved these changes
LGTM!

2023-06-28 07:35 UTC, merged