Modify rule S3862: LaYC format
SonarSource/rspec pull request #2304
Opened 2023-06-27 12:38 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-28 14:57 UTC, guillaume-dequenne-sonarsource requested changes
I think the explanation how the iterator works is quite nice.
I left some comments for small improvements I think we could do.

2023-06-28 14:57 UTC, guillaume-dequenne-sonarsource commented on rules/S3862/python/rule.adoc
> +`for-in` loops, https://docs.python.org/3/whatsnew/3.3.html#pep-380-syntax-for-delegating-to-a-subgenerator[`yield from`] and iterable unpacking only work with https://docs.python.org/3/glossary.html
Should we replace "semantic" with "protocol" to be a bit more precise?

2023-06-28 14:57 UTC, guillaume-dequenne-sonarsource commented on rules/S3862/python/rule.adoc
> +[source,python]
This should be above the separator line (it currently appears in the code snippet).

2023-06-28 14:57 UTC, guillaume-dequenne-sonarsource commented on rules/S3862/python/rule.adoc
> +`for-in` loops, https://docs.python.org/3/whatsnew/3.3.html#pep-380-syntax-for-delegating-to-a-subgenerator[`yield from`] and iterable unpacking only work with https://docs.python.org/3/glossary.html
I have the feeling this section does a great job at explaining how an iterator actually works, but doesn't really answer the question "Why is this an issue?".

I believe a simple sentence explaining which kind of exception would be thrown if trying to iterate from a non iterable object would do the trick.

2023-06-28 14:57 UTC, guillaume-dequenne-sonarsource commented on rules/S3862/python/rule.adoc
> +=== Code examples
I have the feeling these examples do too much and are a bit noisy overall.
Maybe we could consider only keeping the `for ... in` example for the non-async case. And maybe we could have 2 different snippets clearly separated to tackle the `async` case.
Not sure what would be best.

2023-06-29 07:14 UTC, joke1196 commented on rules/S3862/python/rule.adoc
> +[source,python]
Yes, thank you!

2023-06-29 07:46 UTC, joke1196 commented on rules/S3862/python/rule.adoc
> +=== Code examples
I think it is nice having an example of unpacking and yield as well. I will reduce the number of examples for unpacking, it would be cleaner. Tell me if it is still too noisy. I also tried a few different layouts. Not sure I can have multiple Noncompliant code examples sections so I just split the examples with a bit of text.

2023-06-29 07:48 UTC, joke1196 commented on rules/S3862/python/rule.adoc
> +`for-in` loops, https://docs.python.org/3/whatsnew/3.3.html#pep-380-syntax-for-delegating-to-a-subgenerator[`yield from`] and iterable unpacking only work with https://docs.python.org/3/glossary.html
Yes, you are right!  I also added a small sentence for the async iterator part.

2023-06-29 07:51 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-06-29 10:08 UTC, guillaume-dequenne-sonarsource approved these changes
I left one last suggestion regarding grammar.

I still think the Noncompliant/Compliant code examples are a bit noisy, but I don't see an obvious way to improve it without losing information.
So I think it's good as it is. LGTM

2023-06-29 10:08 UTC, guillaume-dequenne-sonarsource commented on rules/S3862/python/rule.adoc
> +Note also that iterating over an https://docs.python.org/3/glossary.html#term-asynchronous-iterable[asynchronous iterable], i.e. an object having the ``++__aiter__++`` method, requires the use of htt
I feel like the comma is unneeded in the sentence "Failing to provide the `async` keyword will result in a `TypeError` stating the object is not iterable."

2023-06-29 10:19 UTC, merged