Modify rule S1716: LaYC format
SonarSource/rspec pull request #2305
Opened 2023-06-27 13:39 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-27 13:42 UTC, joke1196 commented
Not 100% sure, about the added example but I wanted to show a valid way of using `break` and `continue`. Not only how not to use it. WDYT?

2023-06-28 12:38 UTC, guillaume-dequenne-sonarsource requested changes
I'm kind of unsure about the added examples as well. I left some suggestions.

2023-06-28 12:38 UTC, guillaume-dequenne-sonarsource commented on rules/S1716/python/rule.adoc
> +        continue
Taking this snippet in isolation, the `continue` is redundant. I'm not sure it's the best example to give, because of that.

2023-06-28 12:38 UTC, guillaume-dequenne-sonarsource commented on rules/S1716/python/rule.adoc
> +Python will raise a `SyntaxError` when `break` or `continue` are used outside of `for` or `while` loops.
After this, maybe we can say something about how `sys.exit()` can be used instead, since it's in our compliant code example.
I'm not really sure it's such a great recommendation to begin with, though, but I don't have an alternative to suggest.

2023-06-28 13:14 UTC, joke1196 commented on rules/S1716/python/rule.adoc
> +`break` and `continue` are control flow statements used inside of loops to break out of the loop or continue with the iteration of the loop respectively.
I split the sentence in two. I think it works better that way.

2023-06-28 15:03 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM.

2023-06-29 07:52 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-06-29 08:16 UTC, merged