[APPSEC-801] Migrate S4433 to LaYC format.
SonarSource/rspec pull request #2307
Opened 2023-06-27 13:51 UTC by gaetan-ferry-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-28 08:11 UTC, gaetan-ferry-sonarsource commented
That was on purpose. Considering this section is optional and that the explanation would probably look like "Here the code does not use anonymous authentication" I chose not to add it. I open to be challenged here.

2023-06-29 08:17 UTC, hendrik-buchwald-sonarsource requested changes
Okay, good point. The fix is so simple in this case ("use a password") that it does not need a text about that.

All in all it looks very nice already. I left some comments. Also, can you remove the "Compliant" comments from the samples? It was done sometimes in old rules but we are not supposed to have compliant comments anymore.

2023-06-29 08:17 UTC, hendrik-buchwald-sonarsource commented on rules/S4433/common/impact.adoc
> +Typically, an attacker might get access to user accounts lists that he can use
```suggestion
Typically, an attacker might get access to user account lists that he can use
```

2023-06-29 08:17 UTC, hendrik-buchwald-sonarsource commented on rules/S4433/common/impact.adoc
> +European RGPD law.
```suggestion
European GDPR law.
```

RGPD is the French name for it.

2023-06-29 09:11 UTC, gaetan-ferry-sonarsource commented on rules/S4433/common/impact.adoc
> +European RGPD law.
oopsy, french guy spotted

2023-06-29 13:26 UTC, hendrik-buchwald-sonarsource approved these changes
LGTM!

2023-06-29 14:45 UTC, merged