Modify rule S5553: CPP-4409 new cases + LayC
SonarSource/rspec pull request #2315
Opened 2023-06-28 10:03 UTC by necto

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-28 13:10 UTC, tomasz-kaminski-sonarsource requested changes
Looks good, a lot of informative content here. I have added few comments and general questions on shape.

2023-06-28 13:10 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +=== What is the potential impact?
I was wondering about describing potential impact of the undefined behavior. This one sounds ok, but I wonder what value it adds.

2023-06-28 13:10 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +In many cases the access works and succeeds at writing or reading a value.
I would rewrite that in a way that would suggest that in many cases in works by accident, but not simply working,

2023-06-28 13:10 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +References and pointers to temporary objects become dangling after these objects are destroyed.
Can we actually put a text before Why this is an issue, I tought that there are simply tabs, and this text should be part of Why this is an issue.

2023-06-28 13:10 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +  for (auto score : stats.getPlayerScores()) { // Compliant
I would mention if with an initializer here as most popural option.

2023-06-28 13:10 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +  auto s = std::make_unique<std::string>("string");
This example seem very questionable in isolation, as you can just declare string that you will later use. I think we should not place code with smells in complain solutions.
Maybe to present the point use shared_ptr and store shared_ptr<std::String const> in MyStrRef?

2023-06-28 13:55 UTC, necto commented on rules/S5553/cfamily/rule.adoc
> +- https://en.cppreference.com/w/cpp/language/lifetime[Lifetime]
Apparently we have used links to cppreference in S5502, S1912, S5798, S5800, S5417, S5524, S3229, S5403, S2815, S5000.
We only mentioned an abseil reference in S5995
I think the cpprefenrece is a reliable resource, well regarded by the C++ community.
abseil is maybe less so, but still on the trustworthy side.
What would be the problem in using these reources?

2023-06-28 13:57 UTC, necto commented on rules/S5553/cfamily/rule.adoc
> +=== What is the potential impact?
Perhaps, we should have a common shared section explaining why UB is bad, cited from many rules that detect UB.
However, I think it is worth a quick paragraph emphasizing the practical impact rather than theoretical "there be dragons" scare tale.
Otherwise, the users might thing, well it might a UB, but my grandfather did it, my father did it, and I did it for 10 years, so why would I care?

2023-06-28 14:24 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +=== What is the potential impact?
Ok, good point. I will also include that section in my rule.

2023-06-28 14:24 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +References and pointers to temporary objects become dangling after these objects are destroyed.
Great, thanks for pointing this out.

2023-06-28 14:30 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +- https://en.cppreference.com/w/cpp/language/lifetime[Lifetime]
We are endorsing these sources as the company if we link them, and that has marketing consequences. This is not related to the quality of the blogs, but Abseil is clearly connected to Google. And I am not sure if the company, in general, wants to make such references. We may ask Amelie about it.

2023-06-28 14:53 UTC, necto commented on rules/S5553/cfamily/rule.adoc
> +In many cases the access works and succeeds at writing or reading a value.
added "by accident". Did you have in mind something more than that?

2023-06-28 15:06 UTC, necto commented on rules/S5553/cfamily/rule.adoc
> +  auto s = std::make_unique<std::string>("string");
I am not entirely sure what you suggested, is ac019745e close?

2023-06-28 15:16 UTC, necto commented on rules/S5553/cfamily/rule.adoc
> +  for (auto score : stats.getPlayerScores()) { // Compliant
I gues you meant `for` with an initializer. Done in 6ce3edaef

2023-06-29 09:34 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +- https://en.cppreference.com/w/cpp/language/lifetime[Lifetime]
Thanks for clarying with the docs.

2023-06-29 09:40 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +The interface of `Wrapper::getOr` from the example above is dangerous,
I am still concerned that going the extra mile presents solutions that still have the same issues. What would think about starting the paragraph, with `Note that the interface using `std::string_view` still mostly are prone to the same problems, however, they avoid the performance impact on std::string creation.

2023-06-29 09:41 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +  auto s = std::make_unique<std::string>("string");
Yes, thanks. This looks like things that are actually used in code.

2023-06-29 09:42 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +  for (auto score : stats.getPlayerScores()) { // Compliant
Yes, thanks.

2023-06-29 13:55 UTC, necto commented on rules/S5553/cfamily/rule.adoc
> +The interface of `Wrapper::getOr` from the example above is dangerous,
added

2023-06-30 06:03 UTC, tomasz-kaminski-sonarsource approved these changes

2023-06-30 06:07 UTC, tomasz-kaminski-sonarsource approved these changes

2023-06-30 11:16 UTC, merged