Modify rule S2319: LaYC format
SonarSource/rspec pull request #2317
Opened 2023-06-28 12:43 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-28 14:17 UTC, guillaume-dequenne-sonarsource approved these changes
Left minor comments.
Also, I see that the legacy key `PreIncrementDecrement ` is replaced with `S2319` when running rule-api.
Not sure what we should do about that, but I think it is generally disruptive to change rule keys, so we should make sure what should be the correct behavior here before merging.

2023-06-28 14:17 UTC, guillaume-dequenne-sonarsource commented on rules/S2319/python/rule.adoc
> +++x # Noncompliant: pre and post increment operators do not exist.
I'd probably add "in Python." (I know it's obvious), just because the sentence seems a bit odd without it.

2023-06-28 14:17 UTC, guillaume-dequenne-sonarsource commented on rules/S2319/python/rule.adoc
> +This rule raises an issue when an increment or decrement operator is used.
I guess we could say "a non-existing increment or decrement operator" or mention pre/post explicitly, so that there cannot be a confusion with `+=`.

2023-06-29 12:49 UTC, jean-jimbo-sonarsource commented on rules/S2319/python/rule.adoc
> +This rule raises an issue when an increment or decrement operator is used.
I like the idea of adding pre/post, "non-existing" isn't a typical enough phrase to use here.

2023-06-29 12:49 UTC, jean-jimbo-sonarsource requested changes
Added some comments

2023-07-03 06:50 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-07-04 08:41 UTC, merged