Modify S5807: LaYC format
SonarSource/rspec pull request #2320
Opened 2023-06-28 13:48 UTC by guillaume-dequenne-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-29 09:30 UTC, joke1196 commented on rules/S5807/python/rule.adoc
> +
I find this sentence a bit confusing, especially with the repetition of `imported`. Maybe we could just add a small example to illustrate it better. Something like `fileX.py` as the `from moduleY import *` statement and in `moduleY/__init__.py` we would have the ``++__all__++`` list. What do you think?

2023-06-29 09:32 UTC, joke1196 requested changes
LGTM! I have just added a small comment about a potential example we could add. Tell me what you think.

2023-06-29 13:33 UTC, guillaume-dequenne-sonarsource commented on rules/S5807/python/rule.adoc
> +
I added an example, please let me know what you think.

2023-06-29 13:55 UTC, joke1196 approved these changes
LGTM. I think the example is quite nice!

2023-06-30 06:59 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-07-03 07:02 UTC, merged