Modify rule S5712: LaYC format
SonarSource/rspec pull request #2325
Opened 2023-06-29 10:07 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-29 15:17 UTC, guillaume-dequenne-sonarsource requested changes
Looks good overall.
Left a small comment on grammar and some minor suggestions.

2023-06-29 15:17 UTC, guillaume-dequenne-sonarsource commented on rules/S5712/python/rule.adoc
> +This rule raises an issue when some special methods raises `NotImplementedError` instead of returning `NotImplemented`.
This should probably read "when a special method raises" (or "when some special methods raise")

2023-06-29 15:17 UTC, guillaume-dequenne-sonarsource commented on rules/S5712/python/rule.adoc
> +In Python, special methods corresponding to numeric operators, rich comparison operators and the ``++__length_hint__++`` method should return ``++NotImplemented++`` when the operation is not supporte
I'm not sure whether `__length_hint__ ` is the most obvious example to give. In fact, I didn't even know this existed.

2023-06-29 15:17 UTC, guillaume-dequenne-sonarsource commented on rules/S5712/python/rule.adoc
>  class MyClass:
Next to the "# Noncompliant" (can't point to that specific line as it wasn't changed), we could have something like:
`# Noncompliant: the exception will be propagated`

2023-06-30 10:02 UTC, joke1196 commented on rules/S5712/python/rule.adoc
> +This rule raises an issue when some special methods raises `NotImplementedError` instead of returning `NotImplemented`.
I think the singular is more appropriate as we will raise an issue for each special methods.

2023-06-30 11:35 UTC, joke1196 commented on rules/S5712/python/rule.adoc
> +In Python, special methods corresponding to numeric operators, rich comparison operators and the ``++__length_hint__++`` method should return ``++NotImplemented++`` when the operation is not supporte
I think this is more like a pitfall as __length_hint__ is the only non-numeric and non-comparison special method, also the behavior is different than the other special methods. I will move it to the appropriate section.

2023-06-30 15:50 UTC, guillaume-dequenne-sonarsource commented on rules/S5712/python/rule.adoc
> +The ``++__length_hint__++`` special method also requires to return a `NotImplemented`. Its behaviour differs from the other methods, because when this special method returns `NotImplemented` the call
I believe we should consistently use American English, so we should use "behavior".
I'd suggest rewriting:
"..., because when it returns `NotImplemented`, a default value will be returned. See https://peps.python.org/pep-0424/[PEP 424] for more information."

2023-07-04 09:08 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM

2023-07-04 09:44 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-07-04 11:41 UTC, merged