Modify rule S5713: LaYC format
SonarSource/rspec pull request #2327
Opened 2023-06-29 12:02 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-29 15:20 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM

2023-06-30 06:25 UTC, jean-jimbo-sonarsource commented on rules/S5713/python/rule.adoc
> +Repeating an exception class in a single `except` statement will not fail but it does not have any effect. This is surely not what the developer intended. Either the exception class is not the one wh
I don't think we need the sentence "This is surely not what the developer intended."
It is enough to say that the code has no effect and is therefore should be removed.

2023-06-30 06:25 UTC, jean-jimbo-sonarsource requested changes
Left a comment

2023-07-03 06:46 UTC, jean-jimbo-sonarsource approved these changes

2023-07-03 06:57 UTC, merged