Modify rule S3005: LaYC format
SonarSource/rspec pull request #2330
Opened 2023-06-29 12:23 UTC by mary-georgiou-sonarsource

2023-06-29 12:31 UTC, sebastien-marichal requested changes
Left minor comments.

2023-06-29 12:31 UTC, sebastien-marichal commented on rules/S3005/csharp/rule.adoc
> +* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/api/system.threading.threadlocal-1[ThreadLocal<T> Class]
```suggestion
=== Documentation

* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/api/system.threadstaticattribute[ThreadStaticAttribute Class]
* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/api/system.threading.threadlocal-1[ThreadLocal<T> Class]
```

2023-06-29 12:31 UTC, sebastien-marichal commented on rules/S3005/csharp/rule.adoc
> +== How to fix it
Educational: Could this rule be a candidate for a single `Why is this an issue`?

This rule seems to be quite short to me at least for its description part.

2023-06-30 07:39 UTC, mary-georgiou-sonarsource commented on rules/S3005/csharp/rule.adoc
> +== How to fix it
Yes - I think so. 
Indeed - I will remove the `How to fix it`.

2023-06-30 12:23 UTC, sebastien-marichal requested changes
I kind of changed my opinion about having everything in the same section 🙊 
We can discuss it.

2023-06-30 12:23 UTC, sebastien-marichal commented on rules/S3005/csharp/rule.adoc
> +== How to fix it
I am now, not really convinced anymore this rule should be on one page.
I worked on [S2252](https://github.com/SonarSource/rspec/pull/2340) which I rewrite to have only a `Why is this an issue?` section.

The code examples in this rule are a bit complex since it provides 2 solutions.

If you prefer to keep the structure within a single section (which is fine for me), I would like to suggest integrating the code example in the description as it would be in a blog post. And get ride of the structure `Code examples` and `Noncompliant code example` / `Compliant solution`

2023-06-30 13:45 UTC, sebastien-marichal approved these changes
LGTM!

2023-06-30 13:49 UTC, merged