Modify rule S2053: LaYC format
SonarSource/rspec pull request #2335
Opened 2023-06-29 13:43 UTC by hendrik-buchwald-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-03 08:50 UTC, gaetan-ferry-sonarsource requested changes
LGTM in general. I add some suggestions that you might want to include or not.

2023-07-03 08:50 UTC, gaetan-ferry-sonarsource commented on rules/S2053/common/resources/standards.adoc
>  * https://www.sans.org/top25-software-errors/#cat3[SANS Top 25] - Porous Defenses
I think this does not follow the new reference format guidelines: https://github.com/SonarSource/rspec/blob/master/docs/link_formatting.adoc
Also, the Porous Defenses link does not point to anything that seems related to me. I would remove it.
```suggestion
* https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[OWASP]  Top 10:2021 A02:2021 - Cryptographic Failures
* https://www.owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure[OWASP]  - Top 10 2017 - A03:2017 - Sensitive Data Exposure
* https://cwe.mitre.org/data/definitions/759[CWE] - CWE-759: Use of a One-Way Hash without a Salt
* https://cwe.mitre.org/data/definitions/760[CWE] - CWE-760: Use of a One-Way Hash with a Predictable Salt
```

2023-07-03 08:50 UTC, gaetan-ferry-sonarsource commented on rules/S2053/python/how-to-fix-it/std.adoc
> +salt = crypt.mksalt(crypt.METHOD_SHA256)
```suggestion
import crypt

salt = crypt.mksalt(crypt.METHOD_SHA256)
```

2023-07-03 08:50 UTC, gaetan-ferry-sonarsource commented on rules/S2053/php/how-to-fix-it/core.adoc
> +
It might make sense to add a line here to explain how the salt is generated in that case.

```suggestion
Here, the compliant code example ensures the salt is random and has a sufficient length by calling the `random_bytes` function with a length parameter set to 16. This one internally uses a cryptographically secure pseudo random number generator.
```

2023-07-03 08:50 UTC, gaetan-ferry-sonarsource commented on rules/S2053/kotlin/how-to-fix-it/java-se.adoc
> +
It might make sense to add a line here to explain how the salt is generated in that case.

```suggestion
Here, the compliant code example ensures the salt is random and has a sufficient length by calling the `nextBytes` method from the `SecureRandom` class with a salt buffer of 16 bytes. This class implements a cryptographically secure pseudo-random number generator.
```

2023-07-03 08:50 UTC, gaetan-ferry-sonarsource commented on rules/S2053/java/how-to-fix-it/java-se.adoc
> +
It might make sense to add a line here to explain how the salt is generated in that case.

```suggestion
Here, the compliant code example ensures the salt is random and has a sufficient length by calling the `nextBytes` method from the `SecureRandom` class with a salt buffer of 16 bytes. This class implements a cryptographically secure pseudo-random number generator.
```

2023-07-06 06:15 UTC, hendrik-buchwald-sonarsource commented on rules/S2053/rationale.adoc
> +the process for potential attackers to decipher passwords. Thus, the emphasis on
True, good point.

2023-07-06 06:35 UTC, hendrik-buchwald-sonarsource commented on rules/S2053/impact.adoc
> +task significantly easier and faster.
I will skip this since the sprint is already so late. Maybe next time.

2023-07-06 06:53 UTC, hendrik-buchwald-sonarsource commented on rules/S2053/common/fix/salt.adoc
> +by industry standards.
I agree. I don't remember anymore where I read this or if I simply copied it from the initial RSPEC documentation. [NIST](https://pages.nist.gov/800-63-3/sp800-63b.html) seems to recommend at least 32 bits. Other than that, I find a lot of stuff where people say that 128-bit is the industry standard but no references to actual standards.

Since the implementation looks for 128 bits and it seems to be the consensus everywhere that 128 bits is better, I would suggest just leaving it at that for now.

2023-07-06 07:28 UTC, gaetan-ferry-sonarsource approved these changes
LGTM

2023-07-06 08:32 UTC, merged