Modify rule S2252: LaYC format
SonarSource/rspec pull request #2340
Opened 2023-06-30 08:35 UTC by sebastien-marichal

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-30 08:49 UTC, dorian-burihabwa-sonarsource approved these changes
LGTM (reviewed for Java)

2023-06-30 08:50 UTC, alban-auzeill approved these changes
Approved the change about Java

2023-06-30 13:14 UTC, Tim-Pohlmann requested changes
For this rule, it makes sense to split it into "Why is this an issue?" and "How to fix it".

2023-06-30 13:14 UTC, Tim-Pohlmann commented on rules/S2252/why.adoc
> +A {for-link}[`{for-keyword}`] loop is a fundamental programming construct used to execute a block of code repeatedly. However, if the loop's condition is false before the first iteration, the loop wi
Grammarly has some ideas to rewrite this. I do not think it is strictly better. Please judge for yourself which version you like best.
```suggestion
A {for-link}[`{for-keyword}`] loop is a fundamental programming construct used to execute a block of code repeatedly. However, the loop will never run if the loop's condition is false before the first iteration.
```

2023-06-30 13:14 UTC, Tim-Pohlmann commented on rules/S2252/csharp/rule.adoc
> +* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/iteration-statements#the-for-statement[The `for` statement]
Keep it dry.
```suggestion
* Microsoft Learn - {for-link}[The `for` statement]
```

2023-06-30 13:14 UTC, Tim-Pohlmann commented on rules/S2252/vbnet/compliant-code.adoc
> +[source,vbneté,diff-id=1,diff-type=compliant]
`vbneté` :D

2023-06-30 13:14 UTC, Tim-Pohlmann commented on rules/S2252/vbnet/compliant-code.adoc
> +For i As Integer = 0 To 0 Step 1 ' Compliant: the condition is true at least once, the loop will execute
This is the same loop as in the Noncompliant example.

2023-06-30 13:14 UTC, Tim-Pohlmann commented on rules/S2252/vbnet/rule.adoc
> +* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/for-next-statement[For...Next Statement (Visual Basic)]
```suggestion
* Microsoft Learn - {for-link}[For...Next Statement (Visual Basic)]
```

2023-06-30 13:50 UTC, sebastien-marichal commented on rules/S2252/why.adoc
> +A {for-link}[`{for-keyword}`] loop is a fundamental programming construct used to execute a block of code repeatedly. However, if the loop's condition is false before the first iteration, the loop wi
I would like to keep this order, there is the cause and then the consequence.

2023-06-30 14:15 UTC, Tim-Pohlmann commented on rules/S2252/why.adoc
> +include::{language}/compliant-code.adoc[]
My concern here is that John Cliffton said that "How to fix it" might become the primary tab. If that happens, I would rather have it short and concise and move the "Why?" part to the next tab.

2023-06-30 14:40 UTC, sebastien-marichal commented on rules/S2252/why.adoc
> +This bug has the potential to cause unexpected outcomes such as data loss and data corruption.
I think we should add at least a small sentence on the possible outcomes of this issue. I will try to come up with something less vague.

2023-06-30 15:42 UTC, sebastien-marichal commented on rules/S2252/why.adoc
> +include::{language}/compliant-code.adoc[]
As discussed, I will keep the single `why` section for this rule.

2023-07-03 12:45 UTC, mary-georgiou-sonarsource approved these changes
LGTM

2023-07-03 12:45 UTC, merged