Modify rule S3466: LayC format
SonarSource/rspec pull request #2343
Opened 2023-06-30 11:42 UTC by Tim-Pohlmann

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-30 13:03 UTC, gregory-paidis-sonarsource requested changes
Looks good, left two minor suggestions

2023-06-30 13:03 UTC, gregory-paidis-sonarsource commented on rules/S3466/internals.adoc
> +ifdef::env-github,rspecator-view,env-vscode[]
I think you should name this `rspecator.adoc` to be consistent with most other rspecs

2023-06-30 13:03 UTC, gregory-paidis-sonarsource commented on rules/S3466/description.adoc
> +When default parameter values are not passed to base method calls, the value passed in by the caller is ignored. This can cause the function to behave differently than expected, leading to errors and
I think default is a bit misdirecting, since when the user passes their arguments, they are not default anymore.
Maybe use `optional` and link to [this page](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments#optional-arguments)

2023-06-30 13:20 UTC, Tim-Pohlmann commented on rules/S3466/internals.adoc
> +ifdef::env-github,rspecator-view,env-vscode[]
I was not aware. Thank you. What a weird word.

2023-06-30 13:29 UTC, Tim-Pohlmann commented on rules/S3466/description.adoc
> +When default parameter values are not passed to base method calls, the value passed in by the caller is ignored. This can cause the function to behave differently than expected, leading to errors and
Very good suggestion, thank you.

2023-07-03 12:07 UTC, gregory-paidis-sonarsource approved these changes
LGMT!

2023-07-03 12:07 UTC, merged