Modify rule S4428: LaYC format
SonarSource/rspec pull request #2346
Opened 2023-06-30 13:47 UTC by mary-georgiou-sonarsource

2023-07-03 16:07 UTC, martin-strecker-sonarsource requested changes
Some formatting issues and I got some help from my friend GPT with the wording.

2023-07-03 16:07 UTC, martin-strecker-sonarsource commented on rules/S4428/description.adoc
> +However, as we are talking about an export, you should not forget to also annotate your class with the https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.composition.exportattribute[`
```suggestion
For the https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.composition.partcreationpolicyattribute[`PartCreationPolicyAttribute`] to be meaningful in the context of an export, it is necessary to also annotate the class with the https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.composition.exportattribute[`ExportAttribute`].
```

2023-07-03 16:07 UTC, martin-strecker-sonarsource commented on rules/S4428/resources.adoc
> +* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/framework/mef/[Managed Extensibility * Framework (MEF)]
```suggestion
* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/framework/mef/[Managed Extensibility Framework (MEF)]
```

2023-07-03 16:07 UTC, martin-strecker-sonarsource commented on rules/S4428/resources.adoc
> +* Stefan Henneken - https://stefanhenneken.net/2019/03/06/mef-part-3-life-cycle-management-and-monitoring/[MEF Part 3 – Life cycle management and monitoring]
The linked pages look broken in Island browser (Missing images, code snippets are misaligned). Did you check with other browsers?

2023-07-03 16:07 UTC, martin-strecker-sonarsource commented on rules/S4428/resources.adoc
> +* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.composition.partcreationpolicyattribute[PartCreationPolicyAttribute Class]
Consider adding a link to https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.composition.creationpolicy

2023-07-04 08:45 UTC, mary-georgiou-sonarsource commented on rules/S4428/resources.adoc
> +* Stefan Henneken - https://stefanhenneken.net/2019/03/06/mef-part-3-life-cycle-management-and-monitoring/[MEF Part 3 – Life cycle management and monitoring]
Yes - they work with Chrome normally - it's island the issue.
Is this a reason to remove them? (not showing well in all browsers?)
I found them pretty useful.

2023-07-04 11:24 UTC, martin-strecker-sonarsource approved these changes
LGTM. Just some optional fine-tuning suggestions.

2023-07-04 11:24 UTC, martin-strecker-sonarsource commented on rules/S4428/description.adoc
> +For the https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.composition.partcreationpolicyattribute[`PartCreationPolicyAttribute`] to be meaningful in the context of an export, it is n
necessary is repeated twice. I would suggest using a synonym.
```suggestion
For the https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.composition.partcreationpolicyattribute[`PartCreationPolicyAttribute`] to be meaningful in the context of an export, it is required to also annotate the class with the https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.composition.exportattribute[`ExportAttribute`].
```

2023-07-04 11:24 UTC, martin-strecker-sonarsource commented on rules/S4428/csharp/rule.adoc
>  [PartCreationPolicy(CreationPolicy.Any)] // Noncompliant
Consider adding a `using System.ComponentModel.Composition;`

2023-07-04 11:24 UTC, martin-strecker-sonarsource commented on rules/S4428/vbnet/rule.adoc
>  <PartCreationPolicy(CreationPolicy.Any)> ' Noncompliant
Same here: consider adding an `Imports System.ComponentModel.Composition`

2023-07-04 11:39 UTC, merged