Modify rule S2995: LaYC format
SonarSource/rspec pull request #2347
Opened 2023-06-30 13:51 UTC by sebastien-marichal

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-06-30 14:57 UTC, sebastien-marichal commented on rules/S2995/csharp/metadata.json
> +  "quickfix": "targeted"
Not sure if we can make it, I might update it later.

2023-07-03 06:28 UTC, mary-georgiou-sonarsource requested changes

2023-07-03 06:28 UTC, mary-georgiou-sonarsource commented on rules/S2995/csharp/rule.adoc
```suggestion
In C#, the https://learn.microsoft.com/en-us/dotnet/api/system.object.referenceequals[`Object.ReferenceEquals`] method is used to compare two https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/reference-types[reference type] variables. If you use this method to compare two https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-types[value types], such as `int`, `float`, or `bool` you will not get the expected results because value type variables contain an instance of the type and not a reference to it.
```

2023-07-03 06:28 UTC, mary-georgiou-sonarsource commented on rules/S2995/csharp/rule.adoc
> +Thus, value types variables can't have the same reference and using `Object.ReferenceEquals` to compare them will always return `false` even if the compared variables have the same value.
```suggestion
Due to value type variables containing directly an instance of the type, they can't have the same reference, and using `Object.ReferenceEquals` to compare them will always return `false` even if the compared variables have the same value.
```

2023-07-03 06:28 UTC, mary-georgiou-sonarsource commented on rules/S2995/csharp/rule.adoc
> +    if (Object.ReferenceEquals(struct1, struct2)) // Noncompliant: this will be always false
```suggestion
    if (Object.ReferenceEquals(struct1, struct2)) // Noncompliant: this is always false
```

2023-07-03 06:28 UTC, mary-georgiou-sonarsource commented on rules/S2995/csharp/rule.adoc
> +    if (struct1.Equals(struct2)) // Compliant: value are compared
If I remember correctly in case it's not a default struct one should define the equality by overloading the comparison operators.

Might be better to give a more complete example in this case + add a sentence in "how to fix it?" WDTY?

See here: https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type#struct-example

Also please add this link to the resources - I think it's pretty useful.

2023-07-03 09:16 UTC, sebastien-marichal commented on rules/S2995/csharp/rule.adoc
> +    if (struct1.Equals(struct2)) // Compliant: value are compared
I updated the code examples to be more clear regarding value equality for structs.

2023-07-03 12:57 UTC, mary-georgiou-sonarsource approved these changes
LGTM

2023-07-03 13:09 UTC, merged