Modify rule S4624: Adapt to LaYC
SonarSource/rspec pull request #2399
Opened 2023-07-05 10:38 UTC by yassin-kammoun-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-05 14:06 UTC, victor-diez-sonarsource requested changes
Can you please mention this exception? https://github.com/SonarSource/eslint-plugin-sonarjs/issues/319

2023-07-05 14:06 UTC, victor-diez-sonarsource commented on rules/S4624/javascript/rule.adoc
> +Template literals are a convenient way to include variables or expressions within a string by using the backtick ``++(`)++`` character. They allow you to embed placeholders ``++`${expression}`++`` in
```suggestion
Template literals are delimited with the backtick ``++(`)++`` character. They are a convenient way to include variables or expressions within a string using placeholders ``++`${expression}`++`` in the string and evaluate them dynamically.
```

2023-07-05 14:06 UTC, victor-diez-sonarsource commented on rules/S4624/javascript/rule.adoc
> +Template literals are a convenient way to include variables or expressions within a string by using the backtick ``++(`)++`` character. They allow you to embed placeholders ``++`${expression}`++`` in
in the first phrase seems you imply that you can use the backtick to include variables. I would separate the backtick syntax from the placeholder one.

2023-07-06 07:43 UTC, victor-diez-sonarsource approved these changes
Please add also the reason for the exception. Originally requested in https://discuss.sonarsource.com/t/fp-in-ts-sonarcloud-analysis-detecting-nested-template-literal-for-styled-emotion-components/9574/4

From Greg: 

> And indeed this issue is quite painful when working with styled components. It’s quite common to nest template literal in this case.

2023-07-06 10:13 UTC, yassin-kammoun-sonarsource commented
> Please add also the reason for the exception. Originally requested in https://discuss.sonarsource.com/t/fp-in-ts-sonarcloud-analysis-detecting-nested-template-literal-for-styled-emotion-components/9574/4
> 
> From Greg:
> 
> > And indeed this issue is quite painful when working with styled components. It’s quite common to nest template literal in this case.

I preferred to provide a general explanation of why it's okay to have nested templates spanning multiple lines rather than a specific one about styled emotion components.

2023-07-06 10:27 UTC, merged