Modify rule S3504: Adapt to LaYC
SonarSource/rspec pull request #2421
Opened 2023-07-06 13:36 UTC by yassin-kammoun-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-06 13:47 UTC, victor-diez-sonarsource requested changes
I think there is space in this rule to explain more concepts. 

When talking about var: https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

Let and const: non-hoisted but you face the [temporal dead zone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz)

Probably explain a little bit about js [scopes](https://developer.mozilla.org/en-US/docs/Glossary/Scope)

2023-07-07 11:33 UTC, yassin-kammoun-sonarsource commented
@victor-diez-sonarsource Is it better now ?

2023-07-07 11:48 UTC, victor-diez-sonarsource approved these changes
excellent, thanks! :)

just a small typo with a comma

2023-07-07 11:48 UTC, victor-diez-sonarsource commented on rules/S3504/javascript/rule.adoc
> +Unlike ``++let++`` and ``++const++``, variables declared with ``++var++`` are subject to "hoisting," which means that they are moved to the top of their scope during the compilation phase, even if th
```suggestion
Unlike ``++let++`` and ``++const++``, variables declared with ``++var++`` are subject to "hoisting", which means that they are moved to the top of their scope during the compilation phase, even if the actual declaration is placed lower in the code.
```

2023-07-07 11:50 UTC, yassin-kammoun-sonarsource commented on rules/S3504/javascript/rule.adoc
> +Unlike ``++let++`` and ``++const++``, variables declared with ``++var++`` are subject to "hoisting," which means that they are moved to the top of their scope during the compilation phase, even if th
👍

2023-07-07 11:58 UTC, merged