Create a shared_content folder at root
SonarSource/rspec pull request #2441
Opened 2023-07-11 08:41 UTC by frederic-tingaud-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-19 06:39 UTC, tomasz-kaminski-sonarsource requested changes

2023-07-19 06:39 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +include::../../../shared_content/cfamily/dangling_reference_impact.adoc[]
I would prefer if that would not be relative. Does asciidoctor has any notion of `include` dirs?
I think we are already doing some transformation of the includes, so we could replace `shared_content/...` with dedicated path. This has additional benefit of people being unable to use `shared_content` inside the rule.

2023-07-19 06:39 UTC, tomasz-kaminski-sonarsource commented on ci/validate_asciidoc.sh
> +    # There should be no cross inclusion between rules
Isn't this subset of safe mode?

2023-07-19 07:55 UTC, frederic-tingaud-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +include::../../../shared_content/cfamily/dangling_reference_impact.adoc[]
Sadly asciidoctor doesn't have include directories. That would have helped a lot. I thought about having a magic attribute to simplify the includes. The problem is that at the moment we have no custom behavior for includes and breaking that would break some workflows (GitHub previews, VSCode preview and so on). We discussed it with @necto and decided that the benefit was not good enough compared to what we would lose. But I'm open to rediscussing it because these paths are indeed ugly.
I don't understand your last point about forbidding people to use `shared_content` inside the rule. Are there places where you don't want people to access `shared_content`?

2023-07-19 07:56 UTC, frederic-tingaud-sonarsource commented on ci/validate_asciidoc.sh
> +    # There should be no cross inclusion between rules
We currently build with unsafe mode. I don't know exactly why, but that is good for us because otherwise the `shared_content` folder couldn't be included.

2023-07-19 08:11 UTC, tomasz-kaminski-sonarsource commented on rules/S5553/cfamily/rule.adoc
> +include::../../../shared_content/cfamily/dangling_reference_impact.adoc[]
Ok. The script could have special handling for shared folders, but all other normal tools will break because of that. Makes sense.

2023-07-19 11:15 UTC, tomasz-kaminski-sonarsource commented on ci/validate_asciidoc.sh
> +    cross_references=$(grep -Eh "S[0-9]{3,}" included | grep -v ${dir})
I think we should check all `includes` that does not contain `shared_content` directory here. Not only rule includes.

2023-07-19 11:15 UTC, tomasz-kaminski-sonarsource commented on ci/validate_asciidoc.sh
> +    cross_references=$(grep -Eh "S[0-9]{3,}" included | grep -v ${dir})
If of course this is not already breaking something.

2023-07-19 11:31 UTC, necto approved these changes
I would also mention this capability in https://github.com/SonarSource/rspec/blob/master/docs/description.adoc
And the "shared_content" folder in
https://github.com/SonarSource/rspec#rules-directory-structure

2023-07-19 11:31 UTC, necto commented on ci/validate_asciidoc.sh
> +    cross_references=$(grep -Eh "S[0-9]{3,}" included | grep -v ${dir})
Agreed

2023-07-20 08:27 UTC, tomasz-kaminski-sonarsource approved these changes

2023-07-20 10:17 UTC, merged