Modify rule S3039: Improve S3039 to comply to LayC
SonarSource/rspec pull request #2447
Opened 2023-07-11 09:53 UTC by johann-beleites-sonarsource

2023-07-11 13:28 UTC, johann-beleites-sonarsource commented
Before:
https://next.sonarqube.com/sonarqube/coding_rules?q=s3039&open=java%3AS3039
After:
![image](https://github.com/SonarSource/rspec/assets/63855942/c5612170-46e2-4069-8f7e-808055f77329)
![image](https://github.com/SonarSource/rspec/assets/63855942/b29b522c-fe5f-4cb7-b11e-c127d4680ab3)

2023-07-13 17:44 UTC, alban-auzeill requested changes

2023-07-13 17:44 UTC, alban-auzeill commented on rules/S3039/java/rule.adoc
> +This rule raises an issue when a negative literal or `String::length` is passed as an argument to the `String::substring`, `String::charAt`, and related methods.
It depends, for `charAt ` the rule raises when `index > length() -1` and for  `substring` when `index > length()`
```suggestion
This rule raises an issue when a negative literal or a too-large index is passed as an argument to the `String::substring`, `String::charAt`, and related methods.
```

2023-07-13 17:44 UTC, alban-auzeill commented on rules/S3039/java/rule.adoc
> +Use non-negative indexes that are strictly smaller than the length of the string in question.
```suggestion
Use non-negative indexes that are smaller than or equal to the length of the string in question with `String::substring` and strictly smaller with `String::charAt`.
```

2023-07-13 17:44 UTC, alban-auzeill commented on rules/S3039/java/rule.adoc
> +char ch = speech.charAt(speech.length());                    // Noncompliant, speech.length() is out of bounds
`substring(0, speech.length())` is a valid compliant.
`substring(speech.length - 1, 0)` is not supported by the rule, only `substring(speech.length(), 0)`
```suggestion
String substr1 = speech.substring(-1, speech.length()); // Noncompliant, -1 is out of bounds
String substr2 = speech.substring(speech.length(), 0);     // Noncompliant, the beginIndex must be smaller than or equal to the endIndex
char ch = speech.charAt(speech.length());                    // Noncompliant, speech.length() is out of bounds
```

2023-07-13 17:44 UTC, alban-auzeill commented on rules/S3039/java/rule.adoc
> +char ch = speech.charAt(speech.length() - 1);                   // Compliant, speech.length() - 1 is in bounds.
```suggestion
String substr1 = speech;                                       // Compliant, no string operation used
String substr2 = new StringBuilder(speech).reverse().toString(); // Compliant, the string can be reversed using StringBuilder::reverse()
char ch = speech.charAt(speech.length() - 1);                   // Compliant, speech.length() - 1 is in bounds.
```

2023-07-14 12:32 UTC, alban-auzeill approved these changes

2023-07-14 12:38 UTC, merged