Modify rule S6427: LaYC format
SonarSource/rspec pull request #2449
Opened 2023-07-11 11:20 UTC by amelie-renard-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-11 12:34 UTC, marco-antognini-sonarsource requested changes
I think it would be worth mentioning `emplace`. There is also a wording issue: `opt.value() = x` is well-defined even if `opt` is empty (`std::bad_optional_access`).

2023-07-11 12:34 UTC, marco-antognini-sonarsource commented on rules/S6427/cfamily/rule.adoc
> +      *val = 314; // Noncompliant, it is undefined behavior if the optional is empty
```suggestion
      *val = 314; // Noncompliant; the behavior is undefined if the optional is empty.
```

2023-07-11 12:34 UTC, marco-antognini-sonarsource commented on rules/S6427/cfamily/rule.adoc
> +      val.value() = 42; // Noncompliant, it will throw if the optional is empty
```suggestion
      val.value() = 42; // Noncompliant; it will throw if the optional is empty.
```

2023-07-11 12:34 UTC, marco-antognini-sonarsource commented on rules/S6427/cfamily/rule.adoc
> +The class `std::optional` stores an optional value: a `std::optional<T>` can either contain a value of type `T` or be empty.
I feel this sentence is very repetitive. Maybe something like this:
```suggestion
The class `std::optional<T>` is either in an empty state or it stores an value of type `T`.
```

2023-07-11 12:34 UTC, marco-antognini-sonarsource commented on rules/S6427/cfamily/rule.adoc
> +One way to access the value of a non-empty optional is the `operator*`, making an optional look like a pointer. However, the similarity ends there: an optional object models an object, not a pointer.
> Assigning a value to [...] the result of the function value() is undefined behavior if the optional has no value.

Technically, this is well defined: `.value()` will throw and the assignement will never happen.

The connection with the pointer semantics works relatively well, I think, when using `*` or `->` to access the value: it is undefined on `nullptr` and it is undefined on `nullopt`.

The connection with pointers stops when `.value()` is involved: there is simply no counterpart for pointers.

> the preferred way [...] is to assign it directly

This could be more explicit and refer to the `operator=` of the optional, or its `emplace` function -- the later is also interesting when the move or copy operation is expensive or forbidden.

2023-07-13 06:55 UTC, amelie-renard-sonarsource commented on rules/S6427/cfamily/rule.adoc
> +The class `std::optional` stores an optional value: a `std::optional<T>` can either contain a value of type `T` or be empty.
Modified, let me know what you think

2023-07-13 10:19 UTC, amelie-renard-sonarsource commented on rules/S6427/cfamily/rule.adoc
> +One way to access the value of a non-empty optional is the `operator*`, making an optional look like a pointer. However, the similarity ends there: an optional object models an object, not a pointer.
Updated in https://github.com/SonarSource/rspec/pull/2449/commits/3533d1f1e18dbf179e7b464c7cc93208cdd7321d

2023-07-17 06:45 UTC, marco-antognini-sonarsource reviewed
Looks much better already, a couple of smaller nits and I think it's ready.

2023-07-17 06:45 UTC, marco-antognini-sonarsource commented on rules/S6427/cfamily/rule.adoc
> +The class `std::optional` stores an optional value: a `std::optional<T>` can either contain a value of type `T` or be empty.
Much better! 👍

2023-07-17 06:45 UTC, marco-antognini-sonarsource commented on rules/S6427/cfamily/rule.adoc
> +One way to access the value of a non-empty optional is the `operator*`, making an optional look like a pointer. However, the similarity ends there: an optional object models an object, not a pointer.
Technically, just calling `operator*` on an empty optional is UB. This suggestion removes the notion of "assignment" since it's already past the point of UB. I tried to keep it short but maybe there's a better alternative.

```suggestion
One way to access the value of a non-empty optional is the `operator*`, making an optional look like a pointer. However, the similarity ends there: an optional object models an object, not a pointer. Furthermore, dereferencing an empty optional is undefined behavior.
```

2023-07-17 06:45 UTC, marco-antognini-sonarsource commented on rules/S6427/cfamily/rule.adoc
> +* assign the value directly with the `operator=`: e.g. `std::optional<int> opt = 3;`
Nit: the example may give the impression we need a new variable.

```suggestion
* assign the value directly with the `operator=`: e.g. `myOptionalInteger = 3;`
```

2023-07-17 06:45 UTC, marco-antognini-sonarsource commented on rules/S6427/cfamily/rule.adoc
> +The rule raises an issue when the `operator=` or the `value()` function initializes an optional.
```suggestion
The rule raises an issue when the `operator*` or the `value()` function are used to assign a new value to an optional.
```

2023-07-17 10:44 UTC, amelie-renard-sonarsource commented on rules/S6427/cfamily/rule.adoc
> +One way to access the value of a non-empty optional is the `operator*`, making an optional look like a pointer. However, the similarity ends there: an optional object models an object, not a pointer.
I have rewritten this paragraph a bit in https://github.com/SonarSource/rspec/pull/2449/commits/ebf7f7963022f73f824203a3f1359f9f29c452f7
WDYT?

2023-07-17 12:02 UTC, marco-antognini-sonarsource approved these changes
LGTM

2023-07-17 12:04 UTC, merged