Create rule S6658: Special methods should have an expected return type
SonarSource/rspec pull request #2450
Opened 2023-07-11 11:54 UTC by maksim-grebeniuk-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-13 09:38 UTC, guillaume-dequenne-sonarsource requested changes
Looking good, left a few comments.

2023-07-13 09:38 UTC, guillaume-dequenne-sonarsource commented on rules/S6658/python/rule.adoc
> +This rule raises an issue when a special method is defined with an unexpected number of parameters.
This should be updated:
`This rule raises an issue when a special method returns an object of an unexpected type.`

2023-07-13 09:38 UTC, guillaume-dequenne-sonarsource commented on rules/S6658/python/rule.adoc
> +Each special method expects a specific return type. The Python interpreter will call these methods. Calls to a special method will throw a ``++TypeError++`` if it there is returning value with incorr
I'd probably complete:
`The Python interpreter will call these methods when performing the operation they're associated with.`
And I'd rephrase:
`Calls to a special method will throw a ``++TypeError++`` if its return type is incorrect.`

2023-07-13 09:38 UTC, guillaume-dequenne-sonarsource commented on rules/S6658/python/rule.adoc
> +Make sure to return value with correct type defined in the Python documentation for each special methods.
I'd rephrase:
`Make sure to return a value of the same type as defined in the Python documentation for each special method.`

2023-07-13 09:38 UTC, guillaume-dequenne-sonarsource commented on rules/S6658/python/rule.adoc
> +        return 0 # Noncompliant: incorrect return type. Boolean value expected.
I'd say: `# Noncompliant: returned value should be of type bool.` to consistently used the exact type name.

2023-07-13 09:38 UTC, guillaume-dequenne-sonarsource commented on rules/S6658/python/rule.adoc
> +* https://docs.python.org/3/library/copy.html[Copy module] - Documentation of ``++__copy__++`` and ``++__deepcopy__++``
We should make the links consistent with the new format (Python Documentation - ...)

2023-07-13 09:38 UTC, guillaume-dequenne-sonarsource commented on rules/S6658/python/rule.adoc
> +* Make sure this method returns a value of type XXX.
I guess we can even say `Return a value of type XXX here.` to be even more direct in the issue message.

2023-07-13 09:38 UTC, guillaume-dequenne-sonarsource commented on rules/S6658/python/rule.adoc
> +=== Methods to be checked:
Probably we can add these methods to the `Why is this an issue part`, saying that an issue will be raised when one of the following method doesn't return the indicated type. 
That would probably make easier for people to understand when they can expect an issue (since all special methods are not listed here).

2023-07-17 14:11 UTC, guillaume-dequenne-sonarsource requested changes
Left a few comments.

2023-07-17 14:11 UTC, guillaume-dequenne-sonarsource commented on rules/S6658/python/rule.adoc
> +The Python interpreter will call these methods when performing the operation they're associated with. Each special method expects a specific return type. The Python interpreter will call these method
It probably doesn't make sense to repeat `The Python interpreter will call these methods.` in the second part of the explanation.

2023-07-20 08:39 UTC, anton-haubner-sonarsource commented on rules/S6658/python/rule.adoc
> +Python allows developers to customize how code is interpreted by defining special methods (also called magic methods). For example, it is possible to define the objects own truthiness or falsiness by
Minor issue: Typo: "iverriding" instead of "overriding".

2023-07-24 11:44 UTC, anton-haubner-sonarsource commented on rules/S6658/python/rule.adoc
> +
Since the spec also mentions `__getnewargs__` and `__getnewargs_ex__`, maybe we should also point to their documentation at https://docs.python.org/3/library/pickle.html#pickling-class-instances

2023-08-02 12:20 UTC, closed without merging