Modify rule S4634: Adapt to LaYC
SonarSource/rspec pull request #2452
Opened 2023-07-11 13:03 UTC by yassin-kammoun-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-11 13:23 UTC, victor-diez-sonarsource requested changes

2023-07-11 13:23 UTC, victor-diez-sonarsource commented on rules/S4634/javascript/rule.adoc
> +When a promise only needs to "resolve" or "reject", it's more efficient and readable to use the methods specially created for such use cases: ``++Promise.resolve()++`` and ``++Promise.reject()++``.
Not sure about the reasoning. I would rather start with a short explanation are Promises. And then continue with: 

Avoid converting a non-promise value to a promise with the Promise constructor if the resolved value is already known. If you have a value that is not a promise and does not depend on an asynchronous operation, but you want to use it in a promise chain, you can use Promise.resolve() to convert it to a promise. Similarly, use Promise.reject...

2023-07-12 07:28 UTC, yassin-kammoun-sonarsource commented on rules/S4634/javascript/rule.adoc
> +When a promise only needs to "resolve" or "reject", it's more efficient and readable to use the methods specially created for such use cases: ``++Promise.resolve()++`` and ``++Promise.reject()++``.
Probably too much explanation of what a promise is. Let me know if I should cut branches here and there.

2023-07-12 07:34 UTC, victor-diez-sonarsource commented on rules/S4634/javascript/rule.adoc
> +When a promise only needs to "resolve" or "reject", it's more efficient and readable to use the methods specially created for such use cases: ``++Promise.resolve()++`` and ``++Promise.reject()++``.
no need, I would say that this rule is a perfect candidate to add a 'how to fix' tab. I would just add a noncompliant snippet in the general explanation and put all alternatives you mention under the new 'how to fix it?' title

2023-07-12 07:39 UTC, victor-diez-sonarsource commented on rules/S4634/javascript/rule.adoc
> +    return Promise.resolve(fetchDataFromServer());
this example is redundant as `fetchDataFromServer()` looks like a promise already.  probably can be rewritten as:

```js
function fetchData() {
  if (cache) {
    return Promise.resolve(cache);
  } else {
  if (shouldFetchData()) {
    return fetchDataFromServer()
        .then(data => {
            cache = data;
            return data;
        })
  } else {
    return Promise.reject(new Error('Data fetch is not required'));
  }
}
```

2023-07-12 07:43 UTC, yassin-kammoun-sonarsource commented on rules/S4634/javascript/rule.adoc
> +    return Promise.resolve(fetchDataFromServer());
👍

2023-07-12 07:43 UTC, yassin-kammoun-sonarsource commented on rules/S4634/javascript/rule.adoc
> +When a promise only needs to "resolve" or "reject", it's more efficient and readable to use the methods specially created for such use cases: ``++Promise.resolve()++`` and ``++Promise.reject()++``.
👍

2023-07-12 07:48 UTC, victor-diez-sonarsource commented on rules/S4634/javascript/rule.adoc
> +  .then(processedData => Promise.resolve(processedData)) // Intermediate step with resolved value
no need for `Promise.resolve()` here neiter, thenables can resolve with values. Probably another good reference:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

The usecase in promise chains for Promise.resolve() is when you want to initiate the promise chain with something which is not a promise.

```js
const data = cache ? cache : fetchData();

return Promise.resolve(data) // data may be a Promise or not, we need to wrap it
    .then(data => {
        return sanitizeData(data);
    })

```

2023-07-12 07:51 UTC, yassin-kammoun-sonarsource commented on rules/S4634/javascript/rule.adoc
> +  .then(processedData => Promise.resolve(processedData)) // Intermediate step with resolved value
👍

2023-07-12 07:57 UTC, yassin-kammoun-sonarsource commented on rules/S4634/javascript/rule.adoc
> +    return Promise.resolve(fetchDataFromServer());
👍

2023-07-12 07:57 UTC, yassin-kammoun-sonarsource commented on rules/S4634/javascript/rule.adoc
> +  .then(processedData => Promise.resolve(processedData)) // Intermediate step with resolved value
👍

2023-07-12 08:42 UTC, victor-diez-sonarsource commented
Last thing, I think we are actually the 'why is this an issue?' reason. We are defining promises and Promise.resolve(), but we are missing why we should not use the constructor for non-async values

2023-07-12 08:43 UTC, victor-diez-sonarsource requested changes
Last thing, I think we are actually the 'why is this an issue?' reason. We are defining promises and Promise.resolve(), but we are missing why we should not use the constructor for non-async values

2023-07-12 08:59 UTC, victor-diez-sonarsource approved these changes

2023-07-12 09:05 UTC, merged