Modify rule S6491: LaYC format
SonarSource/rspec pull request #2453
Opened 2023-07-11 14:03 UTC by marco-antognini-sonarsource

Keep the whole description in "Why is this an issue" because reading it once should be enough. Also, aimed for conciseness.

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-14 07:05 UTC, amelie-renard-sonarsource requested changes
I thought you wanted to start with an easy one ;)

2023-07-14 07:05 UTC, amelie-renard-sonarsource commented on rules/S6491/cfamily/rule.adoc
I am not sure about not filling in the "How can I fix it" tab. Don't you think the user would need this information every time (s)he sees the issue message?
I think I would, but that may be because I'm not familiar with `std::format`...

2023-07-17 11:13 UTC, marco-antognini-sonarsource reviewed
It _looked_ easy at first 🙃 
Thanks for the great feedback.

2023-07-17 11:13 UTC, marco-antognini-sonarsource commented on rules/S6491/cfamily/rule.adoc
Initially, I thought "since the fix is trivial, we don't need it". But, while the fix is only about changing a character or two, it is not always trivial. So now I agree with you.

I added the "how to fix it" section with some more examples. Let me know what you think of it.

2023-07-18 07:37 UTC, amelie-renard-sonarsource requested changes
I like this new version, good work!
Some suggestions to rewrite sentences a bit (with the help of Island AI :) )

2023-07-18 07:37 UTC, amelie-renard-sonarsource commented on rules/S6491/cfamily/rule.adoc
> +  For example, `std::format("{:05}", num)` adds enough `0` before `num` to align it to the right to reach a width of 5.
The first bullet point describes the outcome of the custom character option while the second bullet point describes how to enable the numeric padding. I did not find it explicit enough so I have asked Island AI to help with that :)
```suggestion
* Numeric padding with `0`: this option is available for most arithmetic types and is enabled by adding `0` before the width specifier. +
  For example, `std::format("{:05}", num)` adds enough `0` before `num` to align it to the right and reach a width of 5.
```

2023-07-18 07:37 UTC, amelie-renard-sonarsource commented on rules/S6491/cfamily/rule.adoc
> +// Noncompliant: the use of character padding results in "00-10"
To make the two comments more consistent
```suggestion
// Noncompliant: character padding results in "00-10"
```

2023-07-18 07:37 UTC, amelie-renard-sonarsource commented on rules/S6491/cfamily/rule.adoc
> +// Compliant: use numeric padding to produce "-0010"
For consistency
```suggestion
// Compliant: numeric padding results in "-0010"
```

2023-07-18 07:37 UTC, amelie-renard-sonarsource commented on rules/S6491/cfamily/rule.adoc
> +The following example illustrates the difference in padding behaviors when a sign specifier (such as `{plus}`) and the alternative form (`#`) are used to format the floating-point variable `num`.
I like the ideas of the sentences but I find them a bit hard to follow within the logic of the rule. WDYT about (with the help of Island AI):
```suggestion
This example shows how custom character padding and numeric padding differ when formatting a floating-point variable `num`. It uses a sign specifier (`{plus}`) and the alternative form (`#`).

As a side note, numeric padding also works with other specifiers to change the type representation, set the precision, apply locale-specific formatting, etc.
```

2023-07-18 07:37 UTC, amelie-renard-sonarsource commented on rules/S6491/cfamily/rule.adoc
> +  return std::format("{:0>+#5", num); // Custom character padding with "0"
```suggestion
  return std::format("{:0>+#5", num); // Noncompliant: custom character padding with "0"
```

2023-07-18 07:37 UTC, amelie-renard-sonarsource commented on rules/S6491/cfamily/rule.adoc
> +Here are some examples of outputs for these two code snippets:
```suggestion
Here are examples of outputs for the two code snippets:
```

2023-07-18 10:13 UTC, marco-antognini-sonarsource commented
@amelie-renard-sonarsource Thanks for the great suggestions! I should try this AI :-)
Before asking for another review, I'll consider [this other point](https://github.com/SonarSource/rspec/pull/2503/files#r1266557731) (link external resources) from #2503.

2023-07-20 07:18 UTC, amelie-renard-sonarsource approved these changes

2023-07-20 07:19 UTC, merged