Create rule S6658: Function call arguments should be passed in proper order
SonarSource/rspec pull request #2462
Opened 2023-07-12 11:35 UTC by maksim-grebeniuk-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-12 12:40 UTC, guillaume-dequenne-sonarsource requested changes
Left some minor comments.

2023-07-12 12:40 UTC, guillaume-dequenne-sonarsource commented on rules/S5686/python/rule.adoc
> +When the names of parameters in a function/method call match the names of the method arguments, it contributes to clearer, more readable code. However, when the names match, but are passed in a diffe
I think the format for the high level description is more: "This rule raises an issue when..."
Maybe something like:
`This rule raises an issue when the arguments passed to a function call match the names of its parameters but are passed in a different order.`

I still think the original sentence makes sense and could be moved to the `Why is this an issue` section.

2023-07-12 12:40 UTC, guillaume-dequenne-sonarsource commented on rules/S5686/python/rule.adoc
> +Python functions typically expect arguments to be provided in a specific order to ensure the correct execution of the function. When arguments are passed in a different order, the function may receiv
This bit is okay, but it assumes the parameters are in the wrong order.
Maybe the code is just confusing because the naming itself is not consistent.
Not sure whether we should, and how to mention this. Happy to discuss.

2023-07-12 12:40 UTC, guillaume-dequenne-sonarsource commented on rules/S5686/python/rule.adoc
> +Make sure that function call arguments in correct order
Rephrase to:
`Make sure that function call arguments are in the correct order.`

2023-07-12 12:40 UTC, guillaume-dequenne-sonarsource commented on rules/S5686/python/rule.adoc
> +* https://docs.python.org/3/tutorial/controlflow.html#defining-functions[Defining functions] - Python function understanding
I believe the standard way of adding links to documentation should be something like:

`* Python Documentation - https://docs.python.org/3/tutorial/controlflow.html#defining-functions[Defining functions]`

2023-07-13 07:47 UTC, guillaume-dequenne-sonarsource commented on rules/S5686/python/rule.adoc
> +Make sure that function call arguments are in the correct order.
Sorry, after a re-read, this still sounds a bit off to me.
What about:
`Make sure that the arguments of this call are in the correct order.`?

I left out "function" because nothing prevents this rule from raising on methods as well.

2023-07-13 11:53 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM.

2025-03-06 08:44 UTC, maksim-grebeniuk-sonarsource commented
Not actual

2025-03-06 08:44 UTC, closed without merging