Modify rule S6490: LaYC format
SonarSource/rspec pull request #2503
Opened 2023-07-17 13:06 UTC by marco-antognini-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-18 06:21 UTC, amelie-renard-sonarsource requested changes

2023-07-18 06:21 UTC, amelie-renard-sonarsource commented on rules/S6490/cfamily/rule.adoc
>  == Why is this an issue?
The rule raises an issue when the user specifies a width or a precision that is not an integer. It seems like a rookie mistake from somebody who did not understand what options he set or what these options do.
So, IMO, we should add an explanation here about these options (maybe based on what is described here: https://en.cppreference.com/w/cpp/utility/format/formatter#Standard_format_specification)
(BTW, I would add this link to the resources section)

2023-07-18 10:11 UTC, marco-antognini-sonarsource commented on rules/S6490/cfamily/rule.adoc
>  == Why is this an issue?
Thanks, that's a good point. I'll try to improve this.

Re. the resource section: Initially, I didn't want to add it because I felt the page miss one big introductory explanation (or a link to it): where should I write these specifiers? The page for [`std::format`](https://en.cppreference.com/w/cpp/utility/format/format) introduces the syntax `{ arg-id (optional) : format-spec }`. Maybe a good solution is to link both pages... I'll see what I can come up with, and we may apply the same in #2453.

2023-07-18 13:29 UTC, marco-antognini-sonarsource commented on rules/S6490/cfamily/rule.adoc
>  == Why is this an issue?
I reworked the rule description, any feedback is appreciated.

2023-07-18 13:31 UTC, marco-antognini-sonarsource commented on rules/S6490/cfamily/rule.adoc
> +  https://en.cppreference.com/w/cpp/utility/format/formatter#Standard_format_specification[standard format specification]
I wasn't sure if I should put it on two lines... Happy to add this one to #2453 (with any adjustments).

2023-07-18 14:09 UTC, amelie-renard-sonarsource commented on rules/S6490/cfamily/rule.adoc
> +  https://en.cppreference.com/w/cpp/utility/format/formatter#Standard_format_specification[standard format specification]
I would put it on two lines as it is what we usually do:
```suggestion
* {cpp} reference -
  https://en.cppreference.com/w/cpp/utility/format/format[`std::format`]
* https://en.cppreference.com/w/cpp/utility/format/formatter#Standard_format_specification[standard format specification]
```

2023-07-21 13:38 UTC, amelie-renard-sonarsource requested changes

2023-07-21 13:38 UTC, amelie-renard-sonarsource commented on rules/S6490/cfamily/rule.adoc
>  == Why is this an issue?
I think the content is good, it gives the user all the necessary information.
However, I would rewrite it a little to make it easier to follow. I have written some suggestions, to give you an idea of what I have in mind.

2023-07-21 13:38 UTC, amelie-renard-sonarsource commented on rules/S6490/cfamily/rule.adoc
> +void example(std::string_view s, double d, int maxLen) {
I would use the second tab here:
```suggestion
== How to fix it

The rule raises an issue when the width or precision specifier is not an integer.

=== Code examples

==== Noncompliant code example
[source,cpp]
----
void example(std::string_view s, double d, int maxLen) {
// ...
```

2023-07-21 13:38 UTC, amelie-renard-sonarsource commented on rules/S6490/cfamily/rule.adoc
> +In the following example, the padding character is `_`, the alignment is to the right (`>`), the width specifier is `10`, and the precision specifier is `.2` with a fixed decimal notation (`f`).
The paragraph contains a lot of useful information, but I don't think it's easy to follow are we are in the middle of understanding how the static and dynamic notations work

2023-07-21 13:38 UTC, amelie-renard-sonarsource commented on rules/S6490/cfamily/rule.adoc
> +With `std::format` and the related formatting functions,
I would start by explaining the format string:
```suggestion
The `std::format` function and related formatting functions allow you to control how a value is displayed as text, including its width and precision.

For example, you can modify the number `3.14159` to have a minimum width of `10` and a precision of `2` using the format string "{:_>10.2f}".
[source,cpp]
----
std::format("{:_>10.2f}", 3.14159)
----

The format string uses:

* `_` as the padding character
* `>` to align the value to the right
* `10` to specify the width
* `.2` to specify the precision
* `f` to indicate fixed decimal notation

The resulting string is `+"______3.14"+`.
```

2023-07-21 13:38 UTC, amelie-renard-sonarsource commented on rules/S6490/cfamily/rule.adoc
> +Its width and precision can be specified in two ways:
And then I would mention the two possible notations:
```suggestion
The width and the precision can be specified in two different ways:

* Statically, by embedding the desired values in the format specification, as in the previous example.
* Dynamically, by referring to complementary function arguments using `{}` or `{arg-id}`. +
With dynamic notation, the previous example becomes:
+
[source,cpp]
----
std::format("{0:_>{1}.{2}f}", 3.14159, 10, 2)
----
```

2023-07-24 13:38 UTC, amelie-renard-sonarsource approved these changes
LGTM :D
Good job!

2023-07-24 15:01 UTC, merged