Modify rule S6459: LaYC format
SonarSource/rspec pull request #2505
Opened 2023-07-17 13:55 UTC by michael-jabbour-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-18 12:53 UTC, amelie-renard-sonarsource requested changes
Nice work! I think the content you added will be helpful for the user.

2023-07-18 12:53 UTC, amelie-renard-sonarsource commented on rules/S6459/cfamily/rule.adoc
> +template <std::copy_constructible T> void func(T&& t);  // Overload #1.
I like the idea of illustrating that standard-provided constraints do not work well with forwarding references. Still, I think one example is enough for the user to understand the point.

2023-07-18 12:53 UTC, amelie-renard-sonarsource commented on rules/S6459/cfamily/rule.adoc
> +    func(s);
I would avoid writing "no surprise" as it may make the user feel stupid if it is not obvious.
```suggestion
    // Call with an rvalue argument:
    func(std::string{""}); // Calls #1: T is 'std::string', which satisfies 'std::copyable'.
    
    // Call with an lvalue argument:
    std::string s{""};
    func(s);  // Calls #2: T is a reference type ('std::string&') which never satisfies 'std::copyable'.
```

2023-07-18 12:53 UTC, amelie-renard-sonarsource commented on rules/S6459/cfamily/rule.adoc
> +naive attempt may silently fail for one or the other.
I am not fond of the word "naive". What about:
```suggestion
Even if it is possible to write `SomeConcept` in a way that works for both plain types and references, it is not straightforward and requires a dedicated effort.
```

2023-07-18 16:31 UTC, michael-jabbour-sonarsource commented on rules/S6459/cfamily/rule.adoc
> +----
Looks much better. Fixed in 67dd3536861f6a0ddf1bcb2b31f4cb89f75665a6. :smile:

2023-07-18 16:32 UTC, michael-jabbour-sonarsource commented on rules/S6459/cfamily/rule.adoc
> +a certain constraint).
Good point, I slightly changed the suggested wording, and addressed that in 273878771dda02ba5bc937bf3dd56322315b4a06.

2023-07-18 16:33 UTC, michael-jabbour-sonarsource commented on rules/S6459/cfamily/rule.adoc
>  _Type-constraints_ provide a terse way to express constraints on the type deduced for a given template parameter or auto placeholder.
Agreed, changed in 54f20a8c259c1aca8fed58b1e56cbd7fcb243d3a.

2023-07-18 16:34 UTC, michael-jabbour-sonarsource commented on rules/S6459/cfamily/rule.adoc
> +template <std::copy_constructible T> void func(T&& t);  // Overload #1.
You are right, I removed the second example in 7268c96e7f34b5aeecad638646b025ffbaba2bea.

2023-07-20 07:57 UTC, amelie-renard-sonarsource requested changes
Some nitpicks, looks good already!

2023-07-20 07:57 UTC, amelie-renard-sonarsource commented on rules/S6459/cfamily/rule.adoc
> + * CPP reference - https://en.cppreference.com/w/cpp/language/reference#Forwarding_references[Forwarding references]
What about adding a link to the c++ constraints and concepts page?
```suggestion
 * CPP reference - https://en.cppreference.com/w/cpp/language/reference#Forwarding_references[Forwarding references]
 * CPP reference - https://en.cppreference.com/w/cpp/language/constraints[Constraints and concepts]
```

2023-07-20 07:57 UTC, amelie-renard-sonarsource commented on rules/S6459/cfamily/rule.adoc
> +    func(s);  // Calls #2: T is a reference type ('std::string&') and therefore doesn't satisfy 'std::copyable'.
```suggestion
    func(s);  // Calls #2: T is a reference type ('std::string&') and therefore does not satisfy 'std::copyable'.
```

2023-07-20 07:57 UTC, amelie-renard-sonarsource commented on rules/S6459/cfamily/rule.adoc
> +auto func(std::copy_constructible auto&& arg)
I would add the "noncompliant" comment to highlight that the same block contains two different examples:
```suggestion
auto func(std::copy_constructible auto&& arg) // Noncompliant
```

2023-07-20 07:57 UTC, amelie-renard-sonarsource commented on rules/S6459/cfamily/rule.adoc
> +auto func2(T&& arg)
```suggestion
auto func2(T&& arg) //  Noncompliant
```

2023-07-20 07:57 UTC, amelie-renard-sonarsource commented on rules/S6459/cfamily/rule.adoc
> +are designed to handle forwarding reference parameters and will not raise issues for this rule.
We usually phrase it the following way:
```suggestion
The rule does not raise an issue for the `std::ranges::range` concept and its refinements (like `std::ranges::forward_range`, `std::ranges::bidirectional_range`) which are designed to handle forwarding reference parameters.
```
i.e.: 
the rule raises issues or not 
vs 
the behavior raises issues or not

But your sentence is correct, so I let you choose what you prefer :)

2023-07-20 16:39 UTC, michael-jabbour-sonarsource commented on rules/S6459/cfamily/rule.adoc
> + * CPP reference - https://en.cppreference.com/w/cpp/language/reference#Forwarding_references[Forwarding references]
Good point

2023-07-21 07:08 UTC, amelie-renard-sonarsource commented
I would keep the backticks: see the example in the [docs](https://github.com/SonarSource/rspec/blob/master/docs/link_formatting.adoc)
Maybe indeed some of our rules don't follow this guideline, but they should :)

2023-07-21 11:18 UTC, michael-jabbour-sonarsource commented
> I would keep the backticks: see the example in the [docs](https://github.com/SonarSource/rspec/blob/master/docs/link_formatting.adoc) Maybe indeed some of our rules don't follow this guideline, but they should :)

True, thanks for pointing that out.

2023-07-21 12:03 UTC, amelie-renard-sonarsource approved these changes

2023-07-21 12:04 UTC, merged