Modify rule S3416: add C# and VB.NET
SonarSource/rspec pull request #2528
Opened 2023-07-18 14:08 UTC by antonioaversa

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-19 12:53 UTC, csaba-sagi-sonarsource commented on rules/S3416/rule-dotnet.adoc
> +- the non-generic version of `ILoggerFactory.CreateLogger`, taking a string as its input parameter, is used
Here you say it does not raise for taking a string as its input parameter, however you have examples that state that
` _logger = loggerFactory.CreateLogger(typeof(AnotherType).FullName);` is noncompliant.
I either misunderstand something or it is contradictory.
+ what about nameof(AnotherType)? I guess that should also raise.

2023-07-19 12:55 UTC, csaba-sagi-sonarsource commented on rules/S3416/vbnet/how.adoc
> +== How to fix it in Microsoft Extensions Logging
Btw I know we have this hot to fix in framework stuff, but I am not entirely sure we should use it here.
Yes, we will cover different logging frameworks, but the rule is quite straight forward about what you are messing up and the fix is the same in all of them. Just that the method is called differently.
IMHO I would simplify the rule as much as possible.

2023-07-19 12:56 UTC, csaba-sagi-sonarsource requested changes
I left a clarification question about the string parameter there, and also another question to think about it. The second one is completely optional, it is just my opinion.

2023-07-19 13:33 UTC, csaba-sagi-sonarsource commented on rules/S3416/rule-dotnet.adoc
> +- the non-generic version of `ILoggerFactory.CreateLogger`, taking a string as its input parameter, is used
Yes, I agree with you for both that it should raise and also that the bullet points should be a bit more clear. 
For me, the first one is the more confusing, since it says the issue will ignore the overloads taking a string as an argument but in some cases, it does not. However, both the `typeof` and `nameof` variants depend on a Type, but at the end of the day, they are strings.

2023-07-19 14:34 UTC, antonioaversa commented on rules/S3416/vbnet/how.adoc
> +== How to fix it in Microsoft Extensions Logging
As discussed, I have removed all logging framework-specific examples, made more generic one-fit-all examples, and simplified the How to fix section.

2023-07-20 07:24 UTC, csaba-sagi-sonarsource commented on rules/S3416/rule-dotnet.adoc
> +The rule doesn't raise issues when custom handling of logging names is in place, and the logger name is not derived from a `Type`.
What about nested private classes?
Is it OK in that case to use the type of the enclosing class?

2023-07-20 07:26 UTC, csaba-sagi-sonarsource commented on rules/S3416/vbnet/why-code-example.adoc
> +        _logger = loggerFactory.CreateLogger(Of AnotherType)()   ' Noncompliant
Not a very strong opinion but I don't like when the names start with a special char. And I am not sure how many of our rules have examples where the names start with an underscore.

2023-07-20 07:27 UTC, csaba-sagi-sonarsource requested changes
I left a couple of comments + I think it would be great to add a list of frameworks that we target in the rule.

2023-07-20 09:02 UTC, antonioaversa commented on rules/S3416/vbnet/why-code-example.adoc
> +        _logger = loggerFactory.CreateLogger(Of AnotherType)()   ' Noncompliant
That's a long debate :-)

All examples from Microsoft Learn, at least the ones for logging that are mentioned in the resources, follow this convention for private fields. 
Coming from Java, I always appreciated how this convention helps with constructor assignments, which have always been a bit cumbersome to me in Java, due to Java not following the convention: `this.logger = logger;`. 
But there are also people that say that the demonstrative pronoun `this` is actually more readable.

In school, I have was taught to limit the use of `this` and `that`, as they are "sloppy" and assume reader location.
And that's where my aversion to `this` probably comes from :-)

I would also mention that the underscore has the advantage of not creating casing problems in case-insensitive languages such as VB.NET, when you have both a property `Logger` and a variable or an input parameter of a method, `logger`. But that's not so relevant I think.

Either way, I have changed, because my little grammatical idiosyncrasies should stay with me only :-)

2023-07-20 09:15 UTC, antonioaversa commented
> I left a couple of comments + I think it would be great to add a list of frameworks that we target in the rule.

List of supported frameworks added.

2023-07-20 11:33 UTC, csaba-sagi-sonarsource commented on rules/S3416/rule-dotnet.adoc
> +The rule doesn't raise issues when custom handling of logging names is in place, and the logger name is not derived from a `Type`.
I was just wondering if one would actually want to do that, but yeah, it is configurable on the outer class too. So all is good!

2024-03-14 13:22 UTC, merged