Modify S6303: Add more risks
SonarSource/rspec pull request #2556
Opened 2023-07-19 15:19 UTC by loris-s-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [x] logical errors and incorrect information
- [x] information gaps and missing content
- [x] text style and tone
- [x] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-19 15:20 UTC, loris-s-sonarsource commented on rules/S6303/description.adoc
> +* Denial of services and security bypasses
```suggestion
* a malicious insider working at the cloud provider gains physical access to the storage device.
* unknown attackers penetrate the cloud provider's logical infrastructure and systems.

After a successful intrusion, the underlying applications are exposed to:

* Theft of intellectual property and/or personal data
* Extortion
* Denial of services and security bypasses
```

2023-07-20 07:19 UTC, hendrik-buchwald-sonarsource requested changes
Some small feedback in the comments.

Not related to your PR but maybe you can update it as well:
> Using unencrypted RDS DB resources exposes data to unauthorized access to the
underlying storage.

I don't think that sentence is very nice, it sounds odd.

2023-07-20 07:19 UTC, hendrik-buchwald-sonarsource commented on rules/S6303/description.adoc
> +* a malicious insider working at the cloud provider gains physical access to the storage device.
These entries I would write upper-case since they are full sentences and end with dots.

2023-07-20 07:19 UTC, hendrik-buchwald-sonarsource commented on rules/S6303/description.adoc
> +* Theft of intellectual property and/or personal data
These entries I would write lower-case since they are just an enumeration (https://github.com/SonarSource/rspec/blob/master/docs/styling_guide.adoc#lists).

2023-07-20 07:19 UTC, hendrik-buchwald-sonarsource commented on rules/S6303/description.adoc
> +* Denial of services and security bypasses
It is not obvious to me how DOS is related to an unencrypted database.

2023-07-20 13:22 UTC, hendrik-buchwald-sonarsource approved these changes
LGTM

2023-07-20 14:09 UTC, merged