Modify rule S2228: reworked rule description for LayC format [SONARJAVA-4490]
SonarSource/rspec pull request #2561
Opened 2023-07-19 16:38 UTC by kaufco

2023-07-20 14:14 UTC, dorian-burihabwa-sonarsource approved these changes
LGTM 👍🏿 I left a few suggestions on formatting and `@Override` annotations

2023-07-20 14:14 UTC, dorian-burihabwa-sonarsource commented on rules/S2229/java/rule.adoc
> +Transactional methods have a propagation type, an optional parameter for the `@Transaction` annotation. It states the requirements about the transactional context in which the method can be called an
Let's split these 2 sentences on their individual lines
```suggestion
Transactional methods have a propagation type, an optional parameter for the `@Transaction` annotation.
It states the requirements about the transactional context in which the method can be called and how it creates, appends, or suspends an ongoing transaction.
```

2023-07-20 14:14 UTC, dorian-burihabwa-sonarsource commented on rules/S2229/java/rule.adoc
> +@Override
Is the `@Override` annotation useful to understand the problem here?
```suggestion
```

2023-07-20 14:14 UTC, dorian-burihabwa-sonarsource commented on rules/S2229/java/rule.adoc
> +@Override
```suggestion
```

2023-07-21 10:14 UTC, kaufco commented on rules/S2229/java/rule.adoc
> +Transactional methods have a propagation type, an optional parameter for the `@Transaction` annotation. It states the requirements about the transactional context in which the method can be called an
Fixed.

2023-07-21 10:15 UTC, kaufco commented on rules/S2229/java/rule.adoc
> +@Override
Fixed.

2023-07-21 10:15 UTC, kaufco commented on rules/S2229/java/rule.adoc
> +@Override
Fixed.

2023-07-21 12:58 UTC, dorian-burihabwa-sonarsource requested changes

2023-07-21 12:58 UTC, dorian-burihabwa-sonarsource commented on rules/S2229/java/rule.adoc
> +However, if a transactional method is called from another method in the same class, the `this` argument is used as the receiver instance instead of an injected proxy object, which bypasses the wrappe
```suggestion
However, if a transactional method is called from another method in the same class, the `this` argument is used as the receiver instance instead of the injected proxy object, which bypasses the wrapper code.
```

2023-07-21 13:10 UTC, dorian-burihabwa-sonarsource approved these changes

2023-07-21 16:09 UTC, closed without merging