Modify rule S836: Adapt to LaYC
SonarSource/rspec pull request #2596
Opened 2023-07-21 07:48 UTC by tomasz-kaminski-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-21 15:09 UTC, necto requested changes

2023-07-21 15:09 UTC, necto commented on rules/S836/cfamily/rule.adoc
>  [source,cpp]
Why did you change the language to `cpp`?

2023-07-21 15:09 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +  return a; // Complaint
```suggestion
  return a; // Compliant
```
Please find&replace it in other places too

2023-07-21 15:09 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +}(); // invoke lambda just (immediately)  after creation
```suggestion
}(); // invoke the lambda immediately (right after creation)
```

2023-07-21 15:09 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +auto [px, py. pz] = [&] {
```suggestion
auto [px, py, pz] = [&] {
```

2023-07-21 15:09 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +    return std::make_tuple(0, 0, 1.0);
```suggestion
    return std::make_tuple(1, 0, 0);
  } else if (y_dir) {
    return std::make_tuple(0, 1, 0);
  } else {
    assert(z_dir);
    return std::make_tuple(0, 0, 1);
```
To make it compile, and avoid the hairy `0., 1.0, 0.`

2023-07-21 15:09 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +* S2107 detect fields being left uninitialized after invocation of constructor
```suggestion
* S2107 detects fields being left uninitialized after the invocation of a constructor
```

2023-07-21 15:29 UTC, tomasz-kaminski-sonarsource commented
Do you think that adding Pitfall paragraph, that just initializing the value to zero is not always the right solution? Like changing an uninitialized pointer to a null pointer.

2023-07-21 15:37 UTC, tomasz-kaminski-sonarsource commented on rules/S836/cfamily/rule.adoc
> +them does not have defined behavior. For example:
Good suggestion.

2023-07-21 15:39 UTC, tomasz-kaminski-sonarsource commented on rules/S836/cfamily/rule.adoc
> +program to behave non-deterministically at runtime.
If you ship it user, crashing it worse. But I understand this depends, and should not be in rule.

2023-07-21 15:40 UTC, tomasz-kaminski-sonarsource commented on rules/S836/cfamily/rule.adoc
> +program to behave non-deterministically at runtime.
I just removed it and have:
> Using garbage values will cause the program to behave
non-deterministically at runtime.

2023-07-21 15:42 UTC, tomasz-kaminski-sonarsource commented on rules/S836/cfamily/rule.adoc
> +is used as a gadget for extracting information from the instance
I believe that in vulnerability reasearch world, the exploit word is avoided. And they refers to gadget. I will change it to "that uses this defect" if that is ok with you/

2023-07-21 15:44 UTC, tomasz-kaminski-sonarsource commented on rules/S836/cfamily/rule.adoc
>  [source,cpp]
Accident, I was having all examples marked as `cpp` in first place.

2023-07-21 15:56 UTC, necto commented on rules/S836/cfamily/rule.adoc
>  * https://cwe.mitre.org/data/definitions/457[MITRE, CWE-457] - Use of Uninitialized Variable
The link should be applied to the document, leaving the standard (source) as plain text

2023-07-21 15:58 UTC, tomasz-kaminski-sonarsource commented on rules/S836/cfamily/rule.adoc
>  * https://cwe.mitre.org/data/definitions/457[MITRE, CWE-457] - Use of Uninitialized Variable
Could you elaborate. I used that exact spelling in other rule.

2023-07-21 16:01 UTC, tomasz-kaminski-sonarsource commented on rules/S836/cfamily/rule.adoc
>  * https://cwe.mitre.org/data/definitions/457[MITRE, CWE-457] - Use of Uninitialized Variable
OK, I checked the link formatting doc, and I think got it correct now.

2023-07-21 16:04 UTC, necto commented on rules/S836/cfamily/rule.adoc
>  * https://cwe.mitre.org/data/definitions/457[MITRE, CWE-457] - Use of Uninitialized Variable
I think it should be:
source - https://link[document]
```
* MITRE - https://cwe.mitre.org/data/definitions/457[CWE-457 Use of Uninitialized Variable]
```
But I can be wrong

2023-07-24 07:27 UTC, tomasz-kaminski-sonarsource commented on rules/S836/cfamily/rule.adoc
>  * https://cwe.mitre.org/data/definitions/457[MITRE, CWE-457] - Use of Uninitialized Variable
I used the first form. Grep in RSPEC shows only the old forms.

2023-07-24 08:41 UTC, tomasz-kaminski-sonarsource commented on rules/S836/cfamily/rule.adoc
>  * https://cwe.mitre.org/data/definitions/457[MITRE, CWE-457] - Use of Uninitialized Variable
I have checked with Best Practices, and we should just CWE as source:
https://github.com/SonarSource/rspec/blob/master/docs/link_formatting.adoc

2023-07-24 09:35 UTC, necto approved these changes

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +non-deterministically at runtime.
```suggestion
nondeterministically at runtime.
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +void initialized() {
```suggestion
int initialized() {
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +void uses() {
```suggestion
int uses() {
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +  return p.x; // Non-complaint: reading an uninitialized variable
```suggestion
  return p.x; // Non-compliant: reading an uninitialized variable
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +  return a; // Complaint
```suggestion
  return a; // Compliant
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +  return a; // Complaint
```suggestion
  return a; // Compliant
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +  return a; // Complaint
```suggestion
  return a; // Compliant
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +the member will remain uninitialized. And reading
```suggestion
the member will remain uninitialized  (See also S2107). And reading
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +object has a defined value even if no initializer is specified.
I would lean towards the standard section title "Exceptions", and  clarify it inside the section:

```suggestion
=== Exceptions

This rule does not flag the variables with static storage duration, meaning:
global, static, and thread-local variables.

All the variables with static storage duration are zero-initialized before the initializer is evaluated.
As a consequence, any variable or member of such an object has a defined value even if no initializer is specified.
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +the object is used by mistake. Generally, such problems can be addressed by:
This is quite subjective, so feel free to discard it.

I notice that you use quite a lot of passive voice.
In general, it hinders comprehension and leads to more complex sentences.
It is also against [our guidelines](https://github.com/SonarSource/rspec/blob/master/docs/tone_guide.adoc#guidelines).

In most places in this rule description, however, it makes sense. Indeed, it is clearer to say "constructor is called" or "variable is initialized", rather than "C++ abstract machine skips the constructor call", or "initializes a variable".

But here, I think you could improve the readability by using active voice:
```suggestion
the object is used by mistake. Generally, you can address such problems by:
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +Initializing variable in all code paths:
```suggestion
Initializing variable on all code paths:
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +=== Going the extra mile
I think it is worth mentioning that in this case you can often make your variable `const`. And also that using `const` variables makes you more disciplined about your initialization.

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +the structure may break assumptions of retirement handling code. Or more commonly,
```suggestion
is not handled correctly. For example, setting an `age` field of an `Employee`
structure may break assumptions of retirement handling code. Or more commonly,
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +setting a pointer to `NULL`, will turn dereference of an uninitialized value
```suggestion
setting a pointer to `NULL` will turn dereference of an uninitialized value
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +into a null pointer dereference.
With no `-` both adjectives apply to the "dereference", i.e., it is equivalent to "pointer null dereference"
```suggestion
into a null-pointer dereference.
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +to the compute value:
```suggestion
to compute the value:
```

2023-07-24 09:35 UTC, necto commented on rules/S836/cfamily/rule.adoc
> +- C++ reference - https://en.cppreference.com/w/cpp/language/storage_duration[Storage class specifiers]
Not sure if this makes any difference. for consistency
```suggestion
* C++ reference - https://en.cppreference.com/w/cpp/language/storage_duration[Storage class specifiers]
```

2023-07-24 10:04 UTC, tomasz-kaminski-sonarsource commented on rules/S836/cfamily/rule.adoc
> +the object is used by mistake. Generally, such problems can be addressed by:
Good suggestion. Applied.

2023-07-24 10:07 UTC, tomasz-kaminski-sonarsource commented on rules/S836/cfamily/rule.adoc
> +=== Going the extra mile
Making variable `const` prevents moving them, or (if I recall correctly) prevents named return initialization. I agree that using const when possible is better, but I think it is not necessary if you want to avoid uninitialized variables.

2023-07-24 10:43 UTC, merged