Modify rule S5720: LaYC format
SonarSource/rspec pull request #2609
Opened 2023-07-24 09:07 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-24 09:43 UTC, maksim-grebeniuk-sonarsource approved these changes
LGTM

2023-07-24 11:40 UTC, guillaume-dequenne-sonarsource requested changes
Looks good, minor comments.

2023-07-24 11:40 UTC, guillaume-dequenne-sonarsource commented on rules/S5720/python/rule.adoc
> +For example, with "ignoredDecorators" set to "abstractmethod".
Does it make sense to use `abstractmethod` here as an example?

As far as I know, the parameter is mostly there for custom decorators we may not have knowledge about and which might make the rule irrelevant. I don't think that's the case with `abstractmethod` though?

Maybe we could use a made-up name that makes things blurrier and understandable why we wouldn't want to raise (like custom static method or something)?

2023-07-24 11:51 UTC, joke1196 commented on rules/S5720/python/rule.adoc
> +You can also disable raising issues on methods decorated with a specific decorators. These decorators can be added to this rule's "ignoredDecorators" parameter.
Yes sure I think it is clearer with the `prevent raising` bit. Thanks

2023-07-24 11:54 UTC, joke1196 commented on rules/S5720/python/rule.adoc
> +For example, with "ignoredDecorators" set to "abstractmethod".
Yes, you are right, it makes sense to use a custom decorator.

2023-07-25 07:52 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM

2023-08-07 11:33 UTC, jean-jimbo-sonarsource commented on rules/S5720/python/rule.adoc
> +Naming the first parameter something different than "self" is not recommended as it could lead to confusion. It might indicate that the "self" parameter was forgotten, in which case calling the metho
Please mod to "...something different from "self"..."

2023-08-07 11:36 UTC, jean-jimbo-sonarsource commented on rules/S5720/python/rule.adoc
> +This rule may be parametrized to prevent raising issues on methods decorated with specific decorators. These decorators can be added to this rule's `ignoredDecorators` parameter.
spelling: "parameterized"

2023-08-07 11:37 UTC, jean-jimbo-sonarsource commented on rules/S5720/python/rule.adoc
> +Make sure to have a "self" parameter on instance methods and annotate static method with the `@staticmethod` decorator.
"...and annotate static methods..."

2023-08-07 11:37 UTC, jean-jimbo-sonarsource reviewed
Left a few spelling/grammar comments

2023-08-07 13:18 UTC, jean-jimbo-sonarsource approved these changes

2023-08-08 09:03 UTC, merged