Modify rule S5890: LaYC format
SonarSource/rspec pull request #2613
Opened 2023-07-24 12:26 UTC by maksim-grebeniuk-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-24 14:44 UTC, joke1196 requested changes
I added a few comments. I may not have understood properly each point so don't hesitate to correct me, especially for the last two points of the list.

2023-07-24 14:44 UTC, joke1196 commented on rules/S5890/python/rule.adoc
> +* *False sense of correctness:* Type hints can provide a sense of confidence that the code is handling specific types, but if the assigned values don't adhere to those hints, it can create a false se
I am not sure about this point. It feels like adding type hints makes the code less good as it gives a false sense of correctness, which I don't agree with. 
Also, I am not sure I get the last part of this sentence, because having type hints will allow static type checker to catch these issues. If I understand correctly; this last part is saying that having a correct type assigned will help the type check to catch an error, but there are no errors.
I feel this point goes against adding type hints, more than applying the correct type. Maybe I didn't fully understand what you meant.

2023-07-24 14:44 UTC, joke1196 commented on rules/S5890/python/rule.adoc
>  Type hints can be used to communicate the intended type of a given variable. These are not enforced at runtime and not respecting them might not necessarily lead to runtime errors.
Maybe we could merge this part with the first sentence of the description as they say something similar.

2023-07-24 14:44 UTC, joke1196 commented on rules/S5890/python/rule.adoc
> +This rule raises an issue when assigned value type is not compatible with typehint of assigning variable.
Small typo, I think it should be: when an assigned value type is not compatible with the type hint of the assigning variable.

2023-07-24 14:44 UTC, joke1196 commented on rules/S5890/python/rule.adoc
> +Assign to variable value of type same as type hint type or update the type hint.
Maybe we could have a bit less repetition of the word `type` something like: Assign to the variable a value of the type proposed by the type hint or update the type hint.

2023-07-26 14:53 UTC, joke1196 commented on rules/S5890/python/rule.adoc
> +This rule raises an issue when assigned value type is not compatible with the type hint of assigning variable.
Still think we are missing some articles here: when `an` assigned value type is not compatible with the type hint of `the` assigning variable.

2023-07-26 14:59 UTC, joke1196 requested changes
Looks good! Small comments on some grammar issues.

2023-07-26 14:59 UTC, joke1196 commented on rules/S5890/python/rule.adoc
> +Assign to variable value compatible with the type hint or change it.
Here as well small grammar issues: missing articles. Assign to `a` variable `a` value compatible with `its` type hint. After re-reading it I would maybe drop the `change it` only because I have the feeling it would push people to maybe drop the type hint to fix the issue or maybe go for `Any`, not 100% sure on this one I let you decide.

2023-07-27 12:08 UTC, joke1196 commented on rules/S5890/python/rule.adoc
> +Assign the variable to the value compatible with or change the type hint.
I am not sure we can say it that way I think we need a repetition of `type hint` in the end, but I will let @jean-jimbo-sonarsource  have a go at it.

2023-07-27 12:08 UTC, joke1196 approved these changes
LGTM. One thing I was not sure about so I will ask for Jean's review.

2023-08-03 07:11 UTC, jean-jimbo-sonarsource commented on rules/S5890/python/rule.adoc
> +Assign the variable to the value compatible with or change the type hint.
"Assign the variable to the value compatible with or change the type hint." sounds incomplete. I don't see any harm in clarifying by being more verbose. 
For example: "Assign the variable to the value compatible with the type hint or change the type hint to be compatible with the variable's type."

2023-08-03 07:11 UTC, jean-jimbo-sonarsource requested changes
I have made a suggestion, but would like an extra pair of eyes on it. It may not disambiguate the sentence enough.

2023-08-04 10:49 UTC, jean-jimbo-sonarsource approved these changes

2023-08-04 15:16 UTC, merged