Modify rule S5781: LaYC format
SonarSource/rspec pull request #2615
Opened 2023-07-24 13:48 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-24 14:20 UTC, maksim-grebeniuk-sonarsource reviewed
LGTM

2023-07-24 15:48 UTC, guillaume-dequenne-sonarsource requested changes
Looks good, minor comments

2023-07-24 15:48 UTC, guillaume-dequenne-sonarsource commented on rules/S5781/rule.adoc
> +only the last occurence of the duplicated value will remain.
We probably want to add something to explain why this might happen and why this is bad:
* maybe the duplication comes from a copy paste that didn't get replaced (an actual value is missing from the set)
* maybe it's just a simple duplication, in which case it's just confusing/difficult to maintain code

As far as I know we don't raise on function calls, so we wouldn't detect any actual redundant computation (as we're not sure 2 identical calls would lead to identical results), so I wouldn't mention that, but it's also a legitimate potential impact.

2023-07-25 09:17 UTC, joke1196 commented on rules/S5781/rule.adoc
> +only the last occurence of the duplicated value will remain.
Yes, that's right, I have added more details on why this is an issue.

2023-07-25 09:17 UTC, joke1196 commented on rules/S5781/rule.adoc
> +The duplicated values should be either modified or removed.
I see what you mean. I have reworked this part a bit.

2023-07-25 15:14 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM

2023-08-03 07:13 UTC, jean-jimbo-sonarsource commented on rules/S5781/rule.adoc
> +By definition a set cannot hold multiple times the same value.
"By definition, a set cannot hold the same value multiple times." is clearer

2023-08-03 07:15 UTC, jean-jimbo-sonarsource approved these changes
Left one comment

2023-08-03 07:54 UTC, merged