Modify rule S1232: Expand and comply with LaYC format
SonarSource/rspec pull request #2621
Opened 2023-07-24 15:09 UTC by necto

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-24 15:28 UTC, necto commented on rules/S1232/cfamily/rule.adoc
> +* S5025 - recomments to avoid manual memory management
```suggestion
* S5025 recommends to avoid manual memory management
```

2023-07-24 15:31 UTC, tomasz-kaminski-sonarsource commented on rules/S1232/cfamily/rule.adoc
> +Use the same form to deallocate objects as used to allocate them to avoid segmentation faults and memory leaks.
Form does not connect with anything for me. Maybe follow the title, and same "Use matching way of deallocation object.

2023-07-24 15:40 UTC, tomasz-kaminski-sonarsource requested changes

2023-07-24 15:50 UTC, tomasz-kaminski-sonarsource commented on rules/S1232/cfamily/rule.adoc
> +auto _pString1 = std::make_unique<std::string>();
Maybe also have example were you declared variable directlyy.
std::string _pString1;
std::vector<std::string> _pString2(100);

2023-07-25 08:54 UTC, necto commented on rules/S1232/cfamily/rule.adoc
> +[source,cpp,diff-id=1,diff-type=noncompliant]
As discussed over Zoom, this rule is C++-only, also There isn't much choice in C, you can only `free()` memory.

2023-07-25 09:45 UTC, necto commented on rules/S1232/cfamily/rule.adoc
> +auto _pString1 = std::make_unique<std::string>();
done ffcb4082bf

2023-07-25 09:46 UTC, necto commented on rules/S1232/cfamily/rule.adoc
> +  might still invoke later the destructor on the freed memory causing a segmentation fault.
rephrased

2023-07-25 09:53 UTC, necto commented on rules/S1232/cfamily/rule.adoc
> +Use the same form to deallocate objects as used to allocate them to avoid segmentation faults and memory leaks.
rephrased

2023-07-25 09:53 UTC, necto commented on rules/S1232/cfamily/rule.adoc
> +Specifically, arrays should be deleted with `+delete []+` and objects should be deleted with `delete`.
Added a table

2023-07-25 09:54 UTC, necto commented on rules/S1232/cfamily/rule.adoc
> +Similarly, the memory allocated with `new` cannot be released using `free()` instead of `delete`.
I added a section for this. I'll fill it later

2023-07-25 10:01 UTC, tomasz-kaminski-sonarsource commented on rules/S1232/cfamily/rule.adoc
> +  will lead to a destructor invocation on an "object" that was never constructed
This is not true, if you do code like that:
```
void* p = ::operator new(sizeof(T));
T* o = new(p) T();
delete p;
```
Is rule raising the issue for such examples? I would be surprised, because this pattern is pretty common. And if we do, it means that we have some additional parts of `M23_360` ready.

2023-07-25 10:04 UTC, tomasz-kaminski-sonarsource commented on rules/S1232/cfamily/rule.adoc
> +=== Why does the rule apply to `::operator new(std::size_t count)`?
I think for this seciton, I would focus more on answering:
```suggestion
=== Why the issue is raised even if calling destructor has no effect?
```

And having example:
```
TrivialClass* p = static_cast<TrivialClass*>(malloc(sizeof(TrivialClass));
delete[] p; // no destructor is called.
```

2023-07-25 10:10 UTC, tomasz-kaminski-sonarsource commented on rules/S1232/cfamily/rule.adoc
> +=== Why does the rule apply to `::operator new(std::size_t count)`?
And maybe:
```
int* p = malloc(10 * sizeof(int));
delete[] p; // expect array coookie
```

2023-07-25 10:25 UTC, tomasz-kaminski-sonarsource commented on rules/S1232/cfamily/rule.adoc
> +=== Standards
Add link to RAII https://en.cppreference.com/w/cpp/language/raii

2023-07-26 08:08 UTC, necto commented on rules/S1232/cfamily/rule.adoc
> +=== Standards
added

2023-07-26 08:50 UTC, necto commented on rules/S1232/cfamily/rule.adoc
> +  will lead to a destructor invocation on an "object" that was never constructed
Removed.
The issue is not raised for these cases, see https://github.com/SonarSource/sonar-cpp/pull/2909

2023-07-26 09:01 UTC, necto commented on rules/S1232/cfamily/rule.adoc
> +=== Why does the rule apply to `::operator new(std::size_t count)`?
Added

2023-07-28 08:52 UTC, tomasz-kaminski-sonarsource approved these changes

2023-07-28 08:53 UTC, merged