Modify rule S3520: Convert to LaYC format
SonarSource/rspec pull request #2623
Opened 2023-07-25 00:49 UTC by LoghinVladDev

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-25 12:22 UTC, necto requested changes

2023-07-25 12:22 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Releasing the same pointer twice is undefined behavior and will usually crash the program.
```suggestion
Releasing the same memory location twice leads to undefined behavior and can often crash the program.
```
"releasing the same pointer" is not correct, as you are not releasing the pointer per see.
If you take it as "releasing the memory pointed to by the same pointer" it is also not correct, because if I change the pointer in the meantime, it is fine to call `free` on it again.

2023-07-25 12:22 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +The effects of a "double-free" heavily depend on how the program's memory management data structures are implemented.
Is the "data structures" detail important to describe the impact?
I feel omitting it unburdens the object of the sentence
```suggestion
The effects of a "double-free" heavily depend on how the program's memory management is implemented.
```

2023-07-25 12:22 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +This can lead to a buffer overflow vulnerability.
How?

2023-07-25 12:22 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +As a result, a second call can be optimized out, leading to hard-to-identify bugs.
In this circumstance, how skipping this second call can lead to a hard-to-identify bug?

2023-07-25 12:22 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Any access to that memory past its lifetime end, including another `delete`, is undefined behavior.
Is it UB in C?

In any case, I would start by saying that UBs are bad regardless. And then only went into the details of particular misbehavior observed in the field

2023-07-25 12:22 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +- Attempt to release any allocated memory in the function it was allocated in.
> Do. Or do not. There is no try. (C)

Seriously, this bullet point was prepended by "best practice". It is already in the context of "try your best to follow this, but you can't be required to do so"

```suggestion
- To release any allocated memory in the function it was allocated in.
```

2023-07-25 12:22 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Besides just ensuring that every release happens once, the following best practices can also be used:
Except for the "set to null", I would move the rest of this list into the "Going the extra mile" subsection.

2023-07-25 12:22 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +==== Noncompliant code example
Looks like the obvious fix of "remove one of the `free` calls" is missing

2023-07-25 12:22 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +In {cpp}:
Let's have one non-compliant example per "Noncompliant code example" subsection. This will make it easier to find which noncompliant code snippet a "Compliant solution" corresponds to.

You can repeat "Noncompliant code example" and "Compliant solution" multiple times.

2023-07-25 12:24 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +{cpp}, using smart pointers:
Yes. Although, I am not sure about the diff view. and I think you don't need to use "Noncompliant code example" / "Compliant solution" sections

2023-07-25 12:39 UTC, LoghinVladDev commented on rules/S3520/cfamily/rule.adoc
> +Any access to that memory past its lifetime end, including another `delete`, is undefined behavior.
Calling `free` twice with the same parameter is UB in both C and CPP.
CPP does not define double delete as UB directly, but it does define the lifetime of heap-allocated memory.

2023-07-25 13:13 UTC, LoghinVladDev commented on rules/S3520/cfamily/rule.adoc
> +==== Noncompliant code example
Added as comment in examples, to keep repetitions low and diffs available

2023-07-31 15:25 UTC, necto requested changes

2023-07-31 15:25 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Although this does not mean it is guaranteed, it can lead to worse issues.
I do not understand this sentence: what is `it` in the first and the second parts?

2023-07-31 15:25 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Any access to that memory past its lifetime end, including another `delete`, is undefined behavior.
Right now the paragraph speaks only about C++ standard.
Can you rephrase it to include C as well? (potentially in another bullet point)

2023-07-31 15:25 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +    // Additionally, this call to free here can be removed since another will happen later
"Additionally" suggests that you can do both: set it to null and remove the `free`. But doing so will introduce a memory leak.
```suggestion
    // Alternatively, the call to free here can be removed since another will happen later
```

2023-07-31 15:25 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +    // Additionally, this call to delete here can be removed since another will happen later
"Additionally" suggests that you can do both: set it to null and remove the `delete`. But doing so will introduce a memory leak.
```suggestion
    // Alternatively, the invocation of delete here can be removed since another will happen later
```

2023-07-31 15:25 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +    // Additionally, this call to free here can be removed since another will happen later
Personally, I feel that "remove call to free" is the primary fix, and setting to null is kind of a hack. It is also mentioned first in the list of fixes above.
However, presently this fix is hidden in a comment. I would add at least one example that just removes the call to `free` or invocation of `delete`.
BTW, it would work better with the diff highlighting, because at the moment our products highlight on the line-level granularity and not token-level

2023-08-03 00:51 UTC, LoghinVladDev commented on rules/S3520/cfamily/rule.adoc
> +Although this does not mean it is guaranteed, it can lead to worse issues.
Rephrased, together with the next comment about memory lifetime in C.
Moved UB descriptions to "why is this an issue"
Described impact of UB more clearly in "what is the potential impact"

2023-08-03 05:28 UTC, necto requested changes

2023-08-03 05:28 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +- Demonstrative Example 2 on CWE - https://cwe.mitre.org/data/definitions/415[415 Double Free] presents a set of circumstances where a crash does not occur.
The citation style from "Resources" section does not work when used inside of a sentence
```suggestion
- Demonstrative Example 2 on https://cwe.mitre.org/data/definitions/415[CWE-415] presents a set of circumstances where a crash does not occur.
```

2023-08-03 05:28 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Both the C and {cpp} standards describe it as such.
The article use here is inconsistent
```suggestion
Both C and {cpp} standards describe it as such.
```
Or
```suggestion
Both the C and the {cpp} standards describe it as such.
```

2023-08-03 05:28 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Due to this, there is no guarantee that a crash will happen on a "double-free".
What do you mean by 
> crash will happen on a "double-free"
?
Is it that there is no guarantee the crash will happen at all, or that it will happen immediately when you call the second `free`?

2023-08-03 05:28 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Using `delete` or `free(...)` releases the reservation on a memory location, making it immediately available for another purpose.
Here is a[ "convention" I made up yesterday](https://docs.google.com/document/d/1hEN48Qqh4UcOjdslhNAtzRQyhU247Mk7MYr1YIuWHtM/edit#heading=h.6ujwyp74oeqh): 
> cite function names without parentheses

I am not claiming this is objectively better per se. It is better to be consistent across rule descriptions, though.
"free" without parentheses is used in S3946, S3529, S1232, S1262, S984. With parentheses only in this rule.

Also you have it in the next paragraph

Feel free to challenge this convention. So far no one did.

```suggestion
Using `delete` or `free` releases the reservation on a memory location, making it immediately available for another purpose.
```

2023-08-03 05:28 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +This can lead to a buffer overflow vulnerability.
if two calls to malloc return the same pointer, it can also lead to attacker accessing directly the secret buffer without any overflow

2023-08-03 05:28 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +{cpp}-11 introduced smart pointers.
```suggestion
{cpp}11 introduced smart pointers.
```

2023-08-03 05:28 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +This includes the issue of "double-free".
Stylistic, to avoid overusing of "this/these"
```suggestion
Using these instead of manual memory management can mitigate most dynamic memory management issues
including "double-free".
```

2023-08-03 05:28 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +  // delete not called by std::unique_ptr destructor.
```suggestion
  // delete not called by std::unique_ptr destructor if the branch above was taken.
```

2023-08-03 09:59 UTC, LoghinVladDev commented on rules/S3520/cfamily/rule.adoc
> +Due to this, there is no guarantee that a crash will happen on a "double-free".
Both apply, a crash immediately and a crash at all, since there must be unpredictable scenarios

2023-08-03 10:00 UTC, LoghinVladDev commented on rules/S3520/cfamily/rule.adoc
> +This can lead to a buffer overflow vulnerability.
Will add it, need to look up the name, but I believe it was "read-what-where"

2023-08-03 10:11 UTC, LoghinVladDev commented
In the [review comment](https://github.com/SonarSource/rspec/pull/2629#pullrequestreview-1560663191) for S3529, you stated a good point about the "Going the extra mile" section. 

While not applicable in the exact same format, the info is useful. I will do a minor modification to at least specify RAII firsthand, before going into smart pointers, since it uses the idiom.

It would be really cool to have something of the sort of "general best practices", since:
- As an example, this rule, S3529, and other memory allocation rules will mention smart pointers/RAII in the "going the extra mile"
- Best practices could also refer back to the rules that they cover. "Using the RAII idiom" would refer to both memory allocation, and, for example, resource acquisition (files, locks, etc.)

Just randomly throwing it here, but I see it as a potential great initiative:
- Cross squad collab. effort - best practices
- Either done on blog posts/generic rules?

Would this be possible/feasible? I would open a discuss thread for this, please advise.

2023-08-03 14:35 UTC, LoghinVladDev commented
Have a look if the pitfalls section is too long.
It is yet incomplete.

shared content will be removed from commit once merge with master is done

2023-08-04 07:02 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Due to this, there is no guarantee that a crash will happen on a "double-free".
What is the point of this sentence?
Why would the reader care if there is a guarantee of a crash?

2023-08-04 07:42 UTC, necto requested changes
Please, also update the quick fix status in the metadata

2023-08-04 07:42 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Besides just ensuring that every release happens once, the following best practices can also be used:
1. unnecessary passive voice in "practices can be used"
2. the best practices are specifically meant to ensure every release happens once, so you can reformulate this sentence:
```suggestion
To ensure that every release happens once, you can follow these best practices:
```

2023-08-04 07:42 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Any raw pointers of references to memory held by _RAII_ objects may still lead to a "double-free".
I am not sure where this section will be placed, and whether it will follow directly the "going the extra mile" section. Because of that, I think it is better to avoid coupling:
```suggestion
However, any raw pointers of references to memory held by _RAII_ objects may still lead to a "double-free".
```

2023-08-04 07:42 UTC, necto commented on rules/S3520/cfamily/rule.adoc
>  }
I think this explanation is too detailed. Remember this is already a tangent (pitfalls) of a tangent (going the extra mile). At this point it should be enough to mention the pitfall (i.e., the non-compliant and compliant code snippets + 2 lines explanation of why) and point to an article that can provide more details.

2023-08-04 07:42 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Similar to `std::unique_ptr`, a "double-free" can occur from an erroneous initialization.
```suggestion
Similar to `std::shared_ptr`, a "double-free" can occur from an erroneous initialization.
```

2023-08-04 07:42 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +  std::shared_ptr<std::string> p2(p1.get()); /// Noncompliant: Intended: std::shared_ptr<string> p2(p1);
What is the purpose of the third `/` in the `/// ...` comments?

2023-08-04 07:42 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +                                             /// If intention was to create another pointer - std::unqiue_ptr<std::string> p2(*p1);
I don't think you need to explain the possible intention and the reasoning in the head of a user. This is not didactic material, but a self-help rule description. The intended reader of this example is not going for the reason why this example is here in the first place.

2023-08-04 07:42 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +                                             /// Possibly intended code: std::unique_ptr<std::string> p4(p3.release());
Again, I don't think this adds any value to the reader trying to get the pitfalls of using smart pointers, given the compliant example below

2023-08-04 07:42 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Passing this pointer to a call that could release the memory could cause a "double-free", amongst other problems.
I suggest the following reformulating, addressing the readability issues:
1. "could release the memory could cause" - the repetition of "could" while grammatically correct, didn't parse for me the first time
2. "amongst other problems" is too vague and makes me think "what other problems?" "why are they not mentioned explicitly?", while I don't think you want the reader thinking about this. I can think only of the problems with "use-after-free". Let me know if you had in mind others.

```suggestion
Passing this pointer to a function that might release it can lead to a "double-free" and "use-after-free".
```

2023-08-04 07:42 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Both C and {cpp} standards describe it as such.
As an option; to make it shorter without losing information, and arguably with no loss of readability. Feel free to disregard it.
```suggestion
The danger of a "double-free" comes directly from the fact that it is undefined behavior (in both C and {cpp}).
```

2023-08-04 07:42 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Ideally, the release should be independent of any additional conditions.
Given this is already a recommendation, no need for the qualifier
```suggestion
The release should be independent of any additional conditions.
```

2023-08-04 07:42 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Remove the unnecessary invocation of `delete`:
Since this applies only to the first snippet in the "Compliant solution", it is better placed in that section

2023-08-04 07:42 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Set the pointer to `nullptr` after any invocation of `delete`:
If it is really "after **any** `delete`", the "compliant solution" does not follow this advice, because it does not nullify `p` at the end of the function
```suggestion
Set the pointer to `nullptr` after invoking `delete`:
```

2023-08-04 11:33 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +include::../../../shared_content/cfamily/memory_raii_extra_mile.adoc
```suggestion
include::../../../shared_content/cfamily/memory_raii_extra_mile.adoc[]
```

2023-08-04 11:55 UTC, LoghinVladDev commented on rules/S3520/cfamily/rule.adoc
> +  std::shared_ptr<std::string> p2(p1.get()); /// Noncompliant: Intended: std::shared_ptr<string> p2(p1);
None, habbit. Will remove

2023-08-04 12:03 UTC, LoghinVladDev commented on rules/S3520/cfamily/rule.adoc
> +                                             /// If intention was to create another pointer - std::unqiue_ptr<std::string> p2(*p1);
Intention was to exemplify how can one reach that pitfall. Regardless, with more attentiveness, they can also be understood from the compliant/noncompliant, and from the now reduced expl.

So yeah, reduced the explanation, confirm if it is better as succint.

2023-08-04 12:47 UTC, LoghinVladDev commented on rules/S3520/cfamily/rule.adoc
> +Due to this, there is no guarantee that a crash will happen on a "double-free".
For a while I assumed a double free is a guaranteed crash, and I'm pretty sure a number of cpp users assume the same.
Having that crash guarantee allows a certain group of people go with "I'll investigate if it's a crash". While in this case, I'm trying to emphasise that - just because in most cases it does, you might have a special scenario where it does not crash, and you should investigate regardless.

2023-08-04 12:58 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Due to this, there is no guarantee that a crash will happen on a "double-free".
I see, thanks for the explanation

2023-08-04 13:24 UTC, necto requested changes

2023-08-04 13:24 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +Due to this, there is no guarantee that a crash will happen on a "double-free" when the resource is released or at all until the end of the program's execution.
It is not clear what "this" refers to here (I guess an artifact of rewriting)
```suggestion
Note that there is no guarantee that a crash will happen on a "double-free" when the resource is released or at all until the end of the program's execution.
```

2023-08-04 13:24 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +  std::unique_ptr<std::string> p2(p1.get()); // Noncompliant: Since the copy constructor of std::unique_ptr is deleted, an user might attempt this.
Same as with the shared_ptr
```suggestion
  std::unique_ptr<std::string> p2(p1.get()); // Noncompliant: both p1 and p2 own the pointer now.
```

2023-08-04 13:24 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +  std::unique_ptr<std::string> p4(p3.get()); // Noncompliant: The intention was to transfer ownership, “double-free” will happen.
```suggestion
  std::unique_ptr<std::string> p4(p3.get()); // Noncompliant: both p3 and p4 own the pointer now.
```

2023-08-04 13:24 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +To avoid this, only use copy/move construction and the `std::make_*` family of functions on initialization.
Is there another function from std::make_* that is applicable here?
```suggestion
To avoid this, only use copy/move construction for sharing ownership or the `std::make_shared` for initialization.
```

2023-08-04 13:24 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +This can lead to a sensitive data exposure vulnerability or a buffer overflow vulnerability.
```suggestion
This can lead to a sensitive-data-exposure vulnerability or a buffer-overflow vulnerability.
```

2023-08-04 13:56 UTC, LoghinVladDev commented on rules/S3520/cfamily/rule.adoc
> +Extra care must be taken when passing the memory address contained in a RAII object.
I was really oscillating between the two

2023-08-04 13:57 UTC, LoghinVladDev commented on rules/S3520/cfamily/rule.adoc
> +* {cpp} reference - https://en.cppreference.com/w/cpp/memory/shared_ptr[std::shared_ptr]
Okay, assumed as they're also referenced in std::unique/shared_ptr pages

2023-08-04 14:09 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +* {cpp} reference - https://en.cppreference.com/w/cpp/memory/shared_ptr[std::shared_ptr]
True, so maybe the links will be redundant. your call

2023-08-04 15:02 UTC, necto commented on rules/S3520/cfamily/rule.adoc
> +However, keeping a raw pointer or reference to memory held by _RAII_ objects may still lead to a "double-free".
Sorry, my previous suggestion was incomplete (and Grammarly didn't help :( )
```suggestion
However, keeping a raw pointer or a reference to memory held by _RAII_ objects may still lead to a "double-free".
```

2023-08-04 15:16 UTC, LoghinVladDev commented
> That was a long one, but we've done it!

Not expecting memory issues to be quick, glad to be able to dive into it

2023-08-04 15:19 UTC, merged