Modify S5886: LaYC format
SonarSource/rspec pull request #2625
Opened 2023-07-25 07:31 UTC by guillaume-dequenne-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-25 10:17 UTC, joke1196 requested changes
LGTM. I have just added small comments nothing major so feel free to ignore them. I really like this rule's description it is super clear!

2023-07-25 10:17 UTC, joke1196 commented on rules/S5886/python/rule.adoc
> +* Python documentation https://docs.python.org/3/library/typing.html[Support for type hints]
Small thing but a `-` is missing between the name and the link

2023-07-25 10:17 UTC, joke1196 commented on rules/S5886/python/rule.adoc
> +To fix this issue, make sure that the returned values of your function are compatible with its type hint.
Feel free to ignore this one, but I would rather go with `returned value ... is compatible`. I feel it is weird that a function could return multiple types.

2023-07-26 07:36 UTC, joke1196 commented on rules/S5886/python/rule.adoc
> +* PEP 544 https://peps.python.org/pep-0544/[Protocols: Structural subtyping (static duck typing)]
Sorry to be super annoying here but a `-` is still missing

2023-07-26 07:37 UTC, joke1196 approved these changes
LGTM. I still added a micro comment for a missing `-`.

2023-07-26 09:45 UTC, guillaume-dequenne-sonarsource commented on rules/S5886/python/rule.adoc
> +* PEP 544 https://peps.python.org/pep-0544/[Protocols: Structural subtyping (static duck typing)]
No worries, that's my bad! Thanks!

2023-07-26 13:10 UTC, maksim-grebeniuk-sonarsource commented on rules/S5886/python/rule.adoc
> +class Bucket:  # Note: no base classes
maybe it is better to move it to compliant/noncompliant samples? Showing how it could looks like in correct way

2023-07-26 13:11 UTC, maksim-grebeniuk-sonarsource approved these changes
LGTM, just left a minor suggestion. Feel free to ignore it.

2023-08-03 08:01 UTC, jean-jimbo-sonarsource approved these changes

2023-08-03 08:58 UTC, guillaume-dequenne-sonarsource commented on rules/S5886/python/rule.adoc
> +class Bucket:  # Note: no base classes
The intention was to keep the compliant/noncompliant examples as simple as possible and to have this slightly more complex case as a standalone example.

2023-08-03 08:58 UTC, merged