Default Queue encryption is now SSE-SQS
SonarSource/rspec pull request #2626
Opened 2023-07-25 08:38 UTC by sebastien-andrivet-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-25 08:55 UTC, hendrik-buchwald-sonarsource commented
Hey, I got an email about this because I was watching the ticket (since I created it). I didn't look at the actual changes but I noticed that the metadata of the PR needs to be slightly adjusted. Mainly, the title of the PR and it needs a label. Thanks!

You can find the details in the readme: https://github.com/SonarSource/rspec#to-modify-an-existing-rule

2023-07-25 14:29 UTC, egon-okerman-sonarsource requested changes
One small error should be fixed, the rest looks good.

2023-07-25 14:29 UTC, egon-okerman-sonarsource commented on rules/S6330/terraform/rule.adoc
> +  sqs_managed_sse_enabled = true # Sensitive, encryption disabled
I think there is a typo here

2023-07-25 14:36 UTC, sebastien-andrivet-sonarsource commented on rules/S6330/terraform/rule.adoc
> +  sqs_managed_sse_enabled = true # Sensitive, encryption disabled
Yes, you're right.

2023-07-25 15:02 UTC, egon-okerman-sonarsource approved these changes
LGTM, let's hold off on merging for now until this fix gets implemented.

2024-05-23 12:23 UTC, petertrr commented
I removed the `iac` label as it has been merged separately

2024-09-02 10:03 UTC, egon-okerman-sonarsource commented
This has been implemented in both IAC and Python for a while now, merging it.

2024-09-02 10:03 UTC, merged