Modify rule S5780: LaYC format
SonarSource/rspec pull request #2632
Opened 2023-07-25 12:14 UTC by maksim-grebeniuk-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-27 12:35 UTC, joke1196 requested changes
LGTM, just a small comments on the example.

2023-07-27 12:35 UTC, joke1196 commented on rules/S5780/rule.adoc
> +    {a1: 1, a2: 2, a1: 3}  # Noncompliant: Change or remove duplicates of this key.
I found `this key` is not super clear here, maybe we could go with `Change or remove the duplicated key`

2023-07-28 07:08 UTC, joke1196 commented on rules/S5780/rule.adoc
> +{"one": 1, "two": 2, "one": 3}  # Noncompliant: the key "one" has duplicate.
Small grammar issue. it would be either `the key "one" has a duplicate`, or I would think it would be better with `the key "one" is duplicated`

2023-07-28 07:08 UTC, joke1196 commented on rules/S5780/rule.adoc
> +    {a1: 1, a2: 2, a1: 3}  # Noncompliant: the key a1 has duplicate.
Same grammar issue, the key a1 is duplicated

2023-07-28 07:09 UTC, joke1196 requested changes
LGTM. Just two small grammar issues. Otherwise looks good!

2023-07-28 07:48 UTC, joke1196 approved these changes
LGTM!

2023-08-07 11:07 UTC, jean-jimbo-sonarsource commented on rules/S5780/rule.adoc
> +By definition a dictionary cannot hold multiple times the same key.
Please amend to: "By definition, a dictionary cannot hold the same key multiple times."

2023-08-07 11:12 UTC, jean-jimbo-sonarsource commented on rules/S5780/rule.adoc
> +When instantiating a dictionary literal with the same key repeated multiple times,
When instantiating a dictionary literal, if a key is repeated, only the last occurrence of the key will be retained. T

2023-08-07 11:15 UTC, jean-jimbo-sonarsource commented on rules/S5780/rule.adoc
> +Creating a dictionary with redundant elements is prone to errors and confusion. A duplicated key in a dictionary literal should be either:
This can also be rephrased to: "This can lead to errors and confusion, as it is not clear which value belongs to which key. This can be remedied by either:"

2023-08-07 11:18 UTC, jean-jimbo-sonarsource commented on rules/S5780/rule.adoc
> +* modified, as it was mistakenly put in the dictionary instead an actual key which would lead to bugs and errors further in the program.
"replacing the duplicated key with the correct key"

2023-08-07 11:20 UTC, jean-jimbo-sonarsource commented on rules/S5780/rule.adoc
> +* removed, as it was a simple duplication, making the code confusing and difficult to maintain.
"removing the duplicated key to make the code more concise and easier to maintain"

2023-08-07 11:20 UTC, jean-jimbo-sonarsource requested changes
Added a few rephrasings.

2023-08-08 07:07 UTC, merged