Modify rule S6214: Convert to LaYC format
SonarSource/rspec pull request #2633
Opened 2023-07-25 12:22 UTC by LoghinVladDev

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-25 12:34 UTC, necto requested changes

2023-07-25 12:34 UTC, necto commented on rules/S6214/cfamily/rule.adoc
> +Compare integers safely using `std::cmp_*` functions to avoid any unexpected results.
```suggestion
Compare integers of mixed signedness safely using `std::cmp_*` functions to avoid any unexpected results.
```

2023-07-25 12:34 UTC, necto commented on rules/S6214/cfamily/rule.adoc
> +The conversion preserves the two's-complement bit pattern of the signed value that often corresponds to a large unsigned result.
Is this guaranteed to be two's-compliment?

2023-07-25 12:34 UTC, necto commented on rules/S6214/cfamily/rule.adoc
> +Integer comparisons are usually used in creating branch conditions.
```suggestion
Integer comparisons are often used in branch conditions.
```

2023-07-25 12:34 UTC, necto commented on rules/S6214/cfamily/rule.adoc
>  [source,cpp]
I think the diff view here will be helpful

2023-07-25 12:34 UTC, necto commented on rules/S6214/cfamily/rule.adoc
> +* S6183 - a version of this rule that triggers when signed and unsigned variables are compared.
```suggestion
* S6183 - a version of this rule that triggers when any signed and unsigned variables are compared.
```

2023-07-25 12:34 UTC, necto commented on rules/S6214/cfamily/rule.adoc
```suggestion

=== Related rules

```

2023-07-25 13:15 UTC, LoghinVladDev commented on rules/S6214/cfamily/rule.adoc
> +The conversion preserves the two's-complement bit pattern of the signed value that often corresponds to a large unsigned result.
Yes, part of the cpp20 standard, and the rule is aimed "since-cpp20"

2023-08-02 14:35 UTC, necto requested changes
A minor fix, and could you, please, update the "quickfix" metadata field?
This needs a second thought, but it looks like it is feasible to always provide a quick fix for this rule

2023-08-02 14:35 UTC, necto commented on rules/S6214/cfamily/rule.adoc
> +The conversion preserves the two's-complement bit pattern of the signed value that often corresponds to a large unsigned result.
To avoid confusing the reader, I would qualify this statement with "Since C++20, ...". No need to specify what happens in other standards since the rule is applicable only starting from C++20

2023-08-02 15:07 UTC, necto commented
Additionally, I think it is useful to mention the danger of entering an infinite loop in the "Pitfalls" section

2023-08-03 05:07 UTC, necto requested changes

2023-08-03 05:07 UTC, necto commented on rules/S6214/cfamily/rule.adoc
>  ----
In the compliant solution you have two more examples:
```
bool fun(int x, std::vector<int> const& v) {
  return std::cmp_less(x, v.size()); // Compliant
}
std::vector<int> v = foo();
if (0 < v.size() && v.size() < 100) { // Compliant, even though v.size() returns an unsigned integer
}
```
It would be instructive to also show their noncompliant version

2023-08-04 09:47 UTC, necto approved these changes

2023-08-04 09:47 UTC, necto commented on rules/S6214/cfamily/rule.adoc
> +Since {cpp}20, the conversion preserves the two's-complement bit pattern of the signed value that often corresponds to a large unsigned result.
Depending on your definition of large, but given the sign bit, the negative number converted to unsigned will occupy the largest half of the unsigned range, i.e., will always be bigger than any number representable in the signed type of the same width, and that sounds pretty large to me
```suggestion
Since {cpp}20, the conversion preserves the two's-complement bit pattern of the signed value that always corresponds to a large unsigned result.
```

2023-08-04 09:47 UTC, necto commented on rules/S6214/cfamily/rule.adoc
>  == Resources
Perhaps you can also point to the documentation of the cmp_* functions https://en.cppreference.com/w/cpp/utility/intcmp

2023-08-04 11:53 UTC, merged