Modify rule S5797: LaYC format
SonarSource/rspec pull request #2634
Opened 2023-07-25 12:24 UTC by maksim-grebeniuk-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-26 14:04 UTC, joke1196 commented on rules/S5797/rule.adoc
the  level 3 documentation title is missing

2023-07-26 14:06 UTC, joke1196 commented on rules/S5797/rule.adoc
> +[source,text,diff-id=1,diff-type=noncompliant]
As discussed we can go with the `python` source type

2023-07-26 14:20 UTC, joke1196 requested changes
Looks good! Only a few issues with the examples they deserve a bit more love I think.

2023-07-26 14:20 UTC, joke1196 commented on rules/S5797/rule.adoc
>      param = (1,)
I do not think the examples really convey what the rule is supposed to do. Maybe we can simplify those to properly use constants instead of function objects, which would be more in line with the description. 
And small issue: the example refers to a `var` variable that does not exist. 
Maybe for this one, I would drop the fancy parametrization of the function and really have a small but concrete example.  Also, I don't think the last line of the example is syntactically correct (I would guess a `if` is missing).

2023-07-27 09:59 UTC, joke1196 approved these changes
LGTM

2023-07-28 14:02 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-08-04 14:43 UTC, merged