Modify rule S2107: Expand and adjust for LaYC
SonarSource/rspec pull request #2647
Opened 2023-07-26 07:45 UTC by necto

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-28 12:10 UTC, tomasz-kaminski-sonarsource requested changes
I think this rule would be good place to explain some details on how defaulted trivial constructor works, and we should expand on it in Why this is an issue.

2023-07-28 12:10 UTC, tomasz-kaminski-sonarsource commented on rules/S2107/cfamily/rule.adoc
> +all member variables of a type with an implicit or explicit constructor will be automatically initialized.
I struggling to understand this sentence. I think we should focus on the default constructor in the first place.
However, if the class has a trivial default constructor, such a class will not be initialized. For example:
```
struct Trivial {
  int x;
  int y;
};

struct Container {
  Container() { /* no initialization of t */ }
  Trivial t;
};
````

2023-07-28 12:10 UTC, tomasz-kaminski-sonarsource commented on rules/S2107/cfamily/rule.adoc
> +(this is its raison d'être after all).
I would remove this reference to language I do not recognize. It may be only understandable to people exposed to french.

2023-07-28 12:10 UTC, tomasz-kaminski-sonarsource commented on rules/S2107/cfamily/rule.adoc
> +the variable will be left uninitialized.
I think we should extend this section, to have code samples with classes and an explanation of which members are not initialized. This rule seems like the place where we should put this deduction.

2023-07-28 12:10 UTC, tomasz-kaminski-sonarsource commented on rules/S2107/cfamily/rule.adoc
>  See S3230 for more details about this order.
One this rule is in related rules I am not sure if we should keep the reference.

2023-07-28 12:10 UTC, tomasz-kaminski-sonarsource commented on rules/S2107/cfamily/rule.adoc
> +Aggregate classes do not initialize most of their data members
I would mention in this section, that using `x{}` or `x()` (in class initializers) will value initialize all aggregate members.

2023-07-28 12:10 UTC, tomasz-kaminski-sonarsource commented on rules/S2107/cfamily/rule.adoc
> +- in a delegate class,
What is a delegate class? This term does not link the bell for me.

2023-07-31 12:47 UTC, necto commented on rules/S2107/cfamily/rule.adoc
> +(this is its raison d'être after all).
It is a relatively common [English idiom](https://en.wikipedia.org/wiki/Raison_d%27%C3%AAtre#:~:text=Raison%20d'%C3%AAtre%20%2F%CB%8Cr,or%20%22reason%20to%20be%22.), but it is certainly not part of a "simple English". removed

2023-07-31 12:51 UTC, necto commented on rules/S2107/cfamily/rule.adoc
>  See S3230 for more details about this order.
I am divided on this one. On one hand, it is duplication, to have the reference both here in the context, and in the Resources section. On another hand, here the reference is most relevant, so it helps both to put the reference in context and to explain the order mentioned here; and the reference is good to mention in the Resources section because that's the first place you would look at when searching for related rules.

It does not seem like too much duplication, though, so if you have no preference, I would leave both references in.

2023-07-31 13:11 UTC, necto commented on rules/S2107/cfamily/rule.adoc
> +- in a delegate class,
expanded

2023-07-31 15:02 UTC, necto commented on rules/S2107/cfamily/rule.adoc
> +the variable will be left uninitialized.
I added a few examples. Additionally, the Noncompliant code example section covers some. Do you think any cases are still missing?

2023-07-31 15:05 UTC, necto commented
@tomasz-kaminski-sonarsource 
I added some C++ reference links for the initialization subject. Do you know of a good article/blog post that would introduce the subject?

2023-08-01 08:55 UTC, tomasz-kaminski-sonarsource requested changes
This looks a lot better now, however, I still get some confusion from the first sentence of the introduction section. Added some suggestion to reworking why this is an issue introduction.

2023-08-01 08:55 UTC, tomasz-kaminski-sonarsource commented on rules/S2107/cfamily/rule.adoc
> +or of non-trivial type with a default constructor will be automatically initialized.
When I read this sentence, I get a lot of question about what is trying to convey, for example:
* What is the trivial type? There are trivial operations, like cosntruyctor destructors, not trivial type
* What are explicit constructors (does it mean `explicit` keyword). Maybe it is written by user?
```
struct A {
   A() = default;
   int x;
   int y;  
};
```

The examples that are below helps a lot, and I think that maybe just dropping the sentence may be good idea. And starting from the `Trivial types` section, but also would remove Trivial there.

As more concrete suggestions:
* Add a small sentence, before why this is an issue, including a description that when the class type has a constructor, it is expected that it will initialize all members. This rule raises the issue if some members are left initialized.
* Start why this is an issue, with the example of no constructor.

2023-08-01 08:55 UTC, tomasz-kaminski-sonarsource commented on rules/S2107/cfamily/rule.adoc
> +- in a member of the class of a dats member
Would this rewrite say the same say thing? If so I will found it cleaner.
```suggestion
- in the constructor of member type, if it is a class
```

2023-08-01 08:57 UTC, tomasz-kaminski-sonarsource commented on rules/S2107/cfamily/rule.adoc
> +the variable will be left uninitialized.
I think that examples already cover most of the cases I can think of. Good job on that.

2023-08-01 09:00 UTC, tomasz-kaminski-sonarsource commented on rules/S2107/cfamily/rule.adoc
>  See S3230 for more details about this order.
I see your point now. This makes sense. However, I think that just saying S3230 may be confusing for user, as it does not immediately scream this is rule id. I think saying "See rule S3230 for more details about this order" would be fine.

2023-08-02 05:31 UTC, necto commented on rules/S2107/cfamily/rule.adoc
>  See S3230 for more details about this order.
I added "rule"

2023-08-02 09:53 UTC, necto commented on rules/S2107/cfamily/rule.adoc
> +or of non-trivial type with a default constructor will be automatically initialized.
Rewritten as discussed over zoom

2023-08-02 09:55 UTC, necto commented on rules/S2107/cfamily/rule.adoc
> +- in a member of the class of a dats member
"keep value in the constructor of member type, if it is a class" does not make sense to me, as you can't "keep value in constructor"
But you can put the value into one of the fields of the class of a data member, that's what I meant.
I've rewritten it, see if that is understandable now

2023-08-02 12:07 UTC, tomasz-kaminski-sonarsource commented on rules/S2107/cfamily/rule.adoc
> +or of non-trivial type with a default constructor will be automatically initialized.
Looks a lot better now. Thanks!

2023-08-02 14:32 UTC, tomasz-kaminski-sonarsource approved these changes
Some very minor suggestions, but otherwise look good.

2023-08-02 14:32 UTC, tomasz-kaminski-sonarsource commented on rules/S2107/cfamily/rule.adoc
> +This leads to garbage being printed in benign-looking code like this:
Maybe we should say, this leads to undefined behavior in following bening-looking code. In C++ this is UB.
And comment on the court. // Undefined behavior,

2023-08-02 14:44 UTC, necto commented on rules/S2107/cfamily/rule.adoc
> +This leads to garbage being printed in benign-looking code like this:
rewritten

2023-08-02 14:45 UTC, tomasz-kaminski-sonarsource commented
For the blog, I couldn't think any out of top of my head.

2023-08-02 14:52 UTC, merged