Modify Rule S5795: LaYC Format
SonarSource/rspec pull request #2648
Opened 2023-07-26 08:58 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-26 11:02 UTC, guillaume-dequenne-sonarsource requested changes
This is undoubtedly a tricky rule and having a clear description for it is not easy.

I think there is still some room to make it a bit more palatable though. Left some suggestions, happy to discuss them in more detail.

2023-07-26 11:02 UTC, guillaume-dequenne-sonarsource commented on rules/S5795/python/rule.adoc
> +Note however that interned strings don't necessarily have the same identity as string literals.
I think the concept of interned strings and why this works in this case should be explained a bit more.

2023-07-27 09:42 UTC, joke1196 commented on rules/S5795/python/rule.adoc
> +The CPython interpreter caches certain builtin values for integers, bytes, floats, strings, frozensets and tuples.
I tried to rework a bit the description to make it more intelligible. Adding short examples makes it a bit more breathable I think.

2023-07-27 13:07 UTC, guillaume-dequenne-sonarsource requested changes
This is a pretty solid improvement, thanks!
I left some comments for further improvement suggestions.
Happy to discuss them in more details.

2023-07-27 13:07 UTC, guillaume-dequenne-sonarsource commented on rules/S5795/python/rule.adoc
> +a reference to the interned string should be kept.
Rather than "are not immortal", what about "may be garbage collected"? (I assume this is what you mean?)
Also, the "it" in "to benefit from it" is not clear, shouldn't it be "them"? Although I guess you don't benefit from the strings themselves, but from their caching mechanism.

2023-07-27 13:07 UTC, guillaume-dequenne-sonarsource commented on rules/S5795/python/rule.adoc
> +() is tuple() # Noncompliant: the empty tuple object is cached this line will return True.
What about:
`# Noncompliant: This will return True only because the CPython interpreter caches the empty tuple`

2023-07-27 13:23 UTC, joke1196 commented on rules/S5795/python/rule.adoc
> +The CPython interpreter caches certain builtin values for integers, bytes, floats, strings, frozensets and tuples. When a value is cached all its references are pointing to the same object in memory;
Sure make sense for the builtin vs built-in!

2023-07-27 13:24 UTC, joke1196 commented on rules/S5795/python/rule.adoc
> +The following example illustrates this caching mechanism:
Yes that is correct it should be two paragraphs

2023-07-27 13:32 UTC, joke1196 commented on rules/S5795/python/rule.adoc
> +to bugs as the behaviour changes depending on the value.
I went for behaviour in some other rules, I will go through them again to change it!

2023-07-28 07:03 UTC, joke1196 commented on rules/S5795/python/rule.adoc
> +to bugs as the behaviour changes depending on the value.
Oh I see it now, yes! Still, I'll check the other non-approved PR for this.

2023-07-28 12:45 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM, nice work on this tricky rule!

2023-08-03 08:20 UTC, jean-jimbo-sonarsource approved these changes
Really like this one.

2023-08-03 11:46 UTC, merged