Modify S5717: LaYC format
SonarSource/rspec pull request #2659
Opened 2023-07-26 11:42 UTC by guillaume-dequenne-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-27 11:55 UTC, joke1196 commented on rules/S5717/python/rule.adoc
>  In the following example, the parameter "param" has ``++list()++`` as a default value. This list is created only once and then reused in every call. Thus when it appends ``++'a'++`` to this list, the
I find the last sentence is bit confusing. `Thus when __it__ appends` feels a bit strange, as I was notit referred to the `This list` of the previous sentence instead of the `call`. Maybe we could go with something like: Thus when appending `a` in the body of the function, its next call will have `[a]` as a default value. Does it make sense?

2023-07-27 11:56 UTC, joke1196 commented on rules/S5717/python/rule.adoc
> +For the same reason, it is also a bad idea to store mutable default value in another object (ex: as an attribute). Multiple instances will then share the same value and modifying one objet will modif
Super optional, maybe we could add a small example here to better illustrate the attribute part?

2023-07-27 11:57 UTC, joke1196 approved these changes
LGTM. I have just added some small comments, but they could be ignored, I'll let you decide.

2023-07-27 13:38 UTC, maksim-grebeniuk-sonarsource approved these changes
LGTM

2023-08-07 10:46 UTC, jean-jimbo-sonarsource commented on rules/S5717/python/rule.adoc
> +For the same reason, it is also a bad idea to store mutable default value in another object (ex: as an attribute). Multiple instances will then share the same value and modifying one objet will modif
A few grammar/spelling issues here. Please change to "For the same reason, it is also a bad idea to store mutable default values in another object (ex: as an attribute). Multiple instances will then share the same value and modifying one object will modify all of them.



"

2023-08-07 10:49 UTC, jean-jimbo-sonarsource commented on rules/S5717/python/rule.adoc
>  * a default value is either modified in the function or assigned to anything else than a variable and it has one of the following types:
This can be improved with:
"a default value is either modified in the function or assigned to anything other than a variable and it has one of the following types:"

2023-08-07 10:50 UTC, jean-jimbo-sonarsource requested changes
Left some comments on grammar/spelling

2023-08-07 15:39 UTC, guillaume-dequenne-sonarsource commented on rules/S5717/python/rule.adoc
> +For the same reason, it is also a bad idea to store mutable default value in another object (ex: as an attribute). Multiple instances will then share the same value and modifying one objet will modif
I must admit I was hesitant to even keep that part, so if you're okay, I'll leave it as it is.

2023-08-08 05:55 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-08-08 07:05 UTC, merged