Modify rule S5754: LaYC format
SonarSource/rspec pull request #2662
Opened 2023-07-26 12:21 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-26 12:54 UTC, guillaume-dequenne-sonarsource requested changes
Looks good!
Minor typos/rewording suggestions.

2023-07-26 12:54 UTC, guillaume-dequenne-sonarsource commented on rules/S5754/python/rule.adoc
> +This rule raises an issue when a bare ``++except:++``, an ``++except BaseException++`` or an ``++except SystemExit++`` block don't re-raise the exception caught.
Shouldn't it be singular (doesn't) instead of don't?

2023-07-26 12:54 UTC, guillaume-dequenne-sonarsource commented on rules/S5754/python/rule.adoc
> +It is possible to catch this exception in order perform, for example, clean-up tasks but it should be raised again to allow the interpreter to exit as expected. Not re-raising such exception could le
missing "to"; in order to perform.
Also maybe we could remove the "but" and make it a separate sentence for readability: It should, however, be raised again to allow the interpreter to exit as expected.

2023-07-26 12:54 UTC, guillaume-dequenne-sonarsource commented on rules/S5754/python/rule.adoc
> +Both statements will catch every exceptions, including `SystemExit`. It is recommended to catch instead a more specific exception, or if it is not possible, the exception should be raised again.
Here also I'd suggest splitting the sentences instead of using "or".

2023-07-26 12:54 UTC, guillaume-dequenne-sonarsource commented on rules/S5754/python/rule.adoc
> +Re-raise `SystemExit` exceptions, `BaseException` exceptions and exceptions caught in a bare `except` statement.
I'd suggest not repeating `exceptions` and reword to:
Re-raise `SystemExit`, `BaseException` and any exception caught in a bare `except` clause.

2023-07-28 12:25 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM

2023-07-28 13:28 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-08-04 13:20 UTC, maksim-grebeniuk-sonarsource approved these changes

2023-08-04 14:50 UTC, merged