Modify rule S5706: LaYC format
SonarSource/rspec pull request #2665
Opened 2023-07-26 12:52 UTC by maksim-grebeniuk-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-27 12:29 UTC, joke1196 requested changes
Looks good. Added small comments, for the examples and maybe a bit more info in the description.

2023-07-27 12:29 UTC, joke1196 commented on rules/S5706/python/rule.adoc
>  The ``++__exit__++`` method can filter passed-in exceptions by simply returning True or False.
Maybe we could be a bit more context on what is the issue. Like maybe a bit of detail about the `__exit__` method, just so that we can understand better what is meant with the `filter passed-in exception`.  WDYT?

2023-07-27 12:29 UTC, joke1196 commented on rules/S5706/python/rule.adoc
> +
Maybe we could add a bit of detail on why each case is Noncompliant.

2023-07-28 07:33 UTC, joke1196 commented on rules/S5706/python/rule.adoc
> +The ``++__exit__++`` is the method of a statement context manager which is called on exit the runtime context related to this object.
I am not sure I understand properly this part, I think a few words are missing. At the moment it is a bit abstract maybe we could make it more concrete. I would suggest something like: The magic methods `__enter__` and `__exit__` allows you to implement objects which can be used as the expression of a `with` statement. 
```
with MyContextManager() as c :
   #do something with c
```
This statement can be rewritten as a `try...finally` and an explicit call to the `__enter__` and `__exit__` methods.

```
c = MyContextManager()
c.__enter__()
try:
   #do something with c
finally:
  c.__exit__()
```
Then maybe we could say a few words about the role of the exit method with the happy path. We can then introduce the exception path this way will tie nicely with the next paragraph.

2023-07-28 07:34 UTC, joke1196 commented on rules/S5706/python/rule.adoc
>  The ``++__exit__++`` method can filter passed-in exceptions by simply returning True or False.
I guess the paragraph on line 18 could be merged with the paragraph starting at line 12, as they say basically the same thing.

2023-07-28 07:38 UTC, joke1196 requested changes
Looks good, I like the details on the examples. I left a suggestion for the description in order to make it a bit more concrete, with some examples. The goal would be to show why/when you would use the `__exit__` method, so it makes it easier to show why you should not re-raise the exception

2023-08-04 14:46 UTC, guillaume-dequenne-sonarsource requested changes
I left a few grammar/styling comments.
I'm also under the impression that we could have a dedicated "How to fix it" section here, given that the code snippet is a bit long.
Wdyt @jean-jimbo-sonarsource ?

2023-08-04 14:46 UTC, guillaume-dequenne-sonarsource commented on rules/S5706/python/rule.adoc
> +Methods ``++__enter__++`` and ``++__exit__++`` allows you to implement objects which can be used as the expression of a ``++with++`` statement.
`allow` since it's plural.
I'd suggest "make it possible to implement" as a more neutral alternative.
I'd end with ":" as the snippet that follows directly completes this.

2023-08-04 14:46 UTC, guillaume-dequenne-sonarsource commented on rules/S5706/python/rule.adoc
In this case I think the resulting tab is quite long and we should probably have a dedicated "How to fix it" section.

2023-08-04 14:46 UTC, guillaume-dequenne-sonarsource commented on rules/S5706/python/rule.adoc
> +----
The indentation on this snippet is missing.

2023-08-04 14:46 UTC, guillaume-dequenne-sonarsource commented on rules/S5706/python/rule.adoc
> +   #do something with c
You probably can use ellipsis to have syntactically correct code:
```
with MyContextManager() as c :
   ... # do something with c
```

2023-08-04 14:46 UTC, guillaume-dequenne-sonarsource commented on rules/S5706/python/rule.adoc
> +This statement can be rewritten as a ``++try...finally++`` and an explicit call to the ``++__enter__++`` and ``++__exit__++`` methods.
If you change it on the previous line, I'd also end this one with ":"

2023-08-04 14:46 UTC, guillaume-dequenne-sonarsource commented on rules/S5706/python/rule.adoc
> +        raise exc_value # Noncompliant: __exit__() methods should not reraise the passed-in exception; this is the caller’s responsibility.
I'd suggest rewording "passed-in" to "provided".
(note that this is in multiple places in the examples but I'll just leave this one comment to not bloat things).

2023-08-04 14:46 UTC, guillaume-dequenne-sonarsource commented on rules/S5706/python/rule.adoc
> +The ``++__exit__++`` is the method of a statement context manager which is called on exit the runtime context related to this object.
Grammar fix:
...which is called when exiting the runtime context

2023-08-04 14:46 UTC, guillaume-dequenne-sonarsource commented on rules/S5706/python/rule.adoc
> +If an exception is supplied, and the method wishes to suppress the exception (i.e., prevent it from being propagated), it should return a true value. Otherwise, the exception will be processed normal
I feel the wording is a bit off ("the method wishes" sounds like the method is a living thing).
What about:
"If an exception is supplied as an argument, its propagation can be suppressed by having the method return a truthy value. Otherwise, the exception will be processed normally upon exit from the method."

2023-08-04 15:43 UTC, jean-jimbo-sonarsource commented on rules/S5706/python/rule.adoc
> +Methods ``++__enter__++`` and ``++__exit__++`` allows you to implement objects which can be used as the expression of a ``++with++`` statement.
Sie note: I'm not sure we've been consistent with the use of colons before we show code snippets. I think we should always have them.

2023-08-07 10:39 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-08-07 14:53 UTC, guillaume-dequenne-sonarsource approved these changes
Looks good, left a last comment.

2023-08-07 14:53 UTC, guillaume-dequenne-sonarsource commented on rules/S5706/python/rule.adoc
> +== How to fix it
Here we should have a small explanation of what is needed to fix the issue, before the code snippets.
Something like the following should be enough:
To fix this issue, make sure to avoid raising the exception provided to an ``++__exit__++`` method.

2023-08-08 09:10 UTC, merged