Modify rule S1542: LaYC format
SonarSource/rspec pull request #2667
Opened 2023-07-26 13:03 UTC by maksim-grebeniuk-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-28 13:44 UTC, guillaume-dequenne-sonarsource requested changes
Some minor suggestions.

2023-07-28 13:44 UTC, guillaume-dequenne-sonarsource commented on rules/S1542/python/rule.adoc
> +This rule raises an issue when function name doesn't respect the naming convention.
when function name => when a function name

2023-07-28 13:44 UTC, guillaume-dequenne-sonarsource commented on rules/S1542/python/rule.adoc
> +According to PEP8 function names should be in all lowercase letters, multiple words should be separated by underscores. This convention is known as "snake_case." For example: ``++calculate_area++``,
Slight rewording suggestion:
According to PEP8, function names should be lowercase, with words separated by underscores as necessary to improve readability. This convention...

2023-07-28 13:44 UTC, guillaume-dequenne-sonarsource commented on rules/S1542/python/rule.adoc
> +=== How to fix it
How to fix it should be a 2nd level title `==`. That said, I think we shouldn't have it at all here, as the rule description is so small (let's keep everything in one single tab).

2023-07-28 13:44 UTC, guillaume-dequenne-sonarsource commented on rules/S1542/python/rule.adoc
> +Respect the naming convention for the function (by default it is the snake case as recommended by PEP8).
If we remove the header, then we can rephrase this:
To fix this, respect the naming convention for the function. The default naming convention is snake case, as recommended by PEP8. Other naming conventions can be defined through the `format` rule parameter.

2023-08-02 12:39 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM.

2023-08-03 08:24 UTC, jean-jimbo-sonarsource commented on rules/S1542/python/rule.adoc
>  include::../description.adoc[]
what's going on here?

2023-08-03 08:25 UTC, jean-jimbo-sonarsource requested changes
please see my note

2023-08-03 09:06 UTC, guillaume-dequenne-sonarsource commented on rules/S1542/python/rule.adoc
>  include::../description.adoc[]
This is supposed to include a common description for multiple languages. Is it not working?
To test it, you can clone the project and open a preview of the page in VSCode or IntelliJ, it should resolve these include statements.
Alternatively, to test it in the SQ UI, you can run `rule-api` to generate the actual html in the `sonar-python` project, then build the analyzer, include the jar into a local SonarQube and run it. It's a bit more involved to do it the first time, but makes reviewing a bit easier afterwards, as you can really make sure everything displays properly.

2023-08-03 09:10 UTC, maksim-grebeniuk-sonarsource commented on rules/S1542/python/rule.adoc
>  include::../description.adoc[]
You can also use the IntelliJ [AsciiDoc](https://plugins.jetbrains.com/plugin/7391-asciidoc) plugin as well.

2023-08-04 11:48 UTC, jean-jimbo-sonarsource commented on rules/S1542/python/rule.adoc
>  include::../description.adoc[]
Ahh thanks, I got it working now

2023-08-04 13:35 UTC, merged