Modify S5806: LaYC format
SonarSource/rspec pull request #2673
Opened 2023-07-26 13:46 UTC by guillaume-dequenne-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-27 12:04 UTC, joke1196 commented on rules/S5806/python/rule.adoc
> +It is sometimes acceptable to shadow a builtin to improve the readability of a public API or to support multiple versions of a library. In these cases the value is higher than the maintainability cos
I would maybe use `benefits are greater than`  instead of `value is higher than`. Not 100% sure though, so happy to leave it as is.

2023-07-27 12:05 UTC, joke1196 approved these changes
LGTM. Just added a small potential change on the wording, feel free to ignore.

2023-07-27 13:42 UTC, maksim-grebeniuk-sonarsource requested changes
Looks good, just left the formatting comment

2023-07-27 13:42 UTC, maksim-grebeniuk-sonarsource commented on rules/S5806/python/rule.adoc
Should the `=== Code examples` section header here be here?

2023-08-07 10:21 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-08-07 12:45 UTC, merged