Run include and cross-references validation on all files
SonarSource/rspec pull request #2685
Opened 2023-07-27 09:52 UTC by marco-antognini-sonarsource

The previous validation code was taking about 3 minutes when running on
all rules, which is the case when modifying anything outside rules/,
including shared_content/.

The runtime was marginal when only the content specific to one rule was
modified, e.g. only rules/S100/cfamily/rule.adoc is modified.

The new validation code always takes about 30 seconds on the CI. This is
a slight increase for small PR but a large reduction for PR affecting
the whole system.

Furthermore, the new approach validates includes and cross-references
properly. An issue is now raised when:
 * The last include to shared_content/lang/foo.adoc is removed.
 * A shared_content doc includes a file from another rule, e.g.
   rules/S100/lang/rule.adoc includes shared_content/lang/foo.adoc,
   which includes rules/S200/bar.adoc.

This is achieved with proper Asciidoc extensions written in Ruby.
See https://docs.asciidoctor.org/asciidoctor/latest/extensions/

---

Requires:
 - [ ] #2684

2023-07-31 15:59 UTC, necto requested changes
I think it is worth the common-case time increase because it is not on a critical path: some other tasks take longer anyway, e.g., `tooling_test`, `validate_links`.
I agree with you that this is a more natural and flexible way to add validation checks, and I am looking forward to how it can be extended for more sophisticated and specialized checks.

Have you tried running it on CI with some failures it detects (smoke tests)?
I'd be curious to see the CI logs if any

2023-07-31 15:59 UTC, necto commented on ci/validate_asciidoc.sh
>  #  * The include:: should have an empty line before and after them.
I wonder if this one would be easier to validate from the Ruby extension

2023-07-31 15:59 UTC, necto commented on ci/validate_asciidoc.sh
>  #  * Asciidoc files are free or errors and warnings.
This looks like like a property that could be also validated when you run asciidoctor with a custom plugin. Any reason, you keep a separate asciidoctor run for this?

2023-07-31 15:59 UTC, necto commented on ci/validate_asciidoc.sh
> +  echo "List of errors:"
for consistency with the above
```suggestion
  echo 'List of errors:'
```

2023-08-02 06:11 UTC, marco-antognini-sonarsource reviewed
Thanks for the review

2023-08-02 06:11 UTC, marco-antognini-sonarsource commented on ci/custom-asciidoctor
Binary executables usually don't have any extension, like the official `asciidoctor`.

2023-08-02 06:11 UTC, marco-antognini-sonarsource commented on ci/validate_asciidoc.sh
>  #  * The include:: should have an empty line before and after them.
Sadly, it is not: the API is not designed to read the source surrounding the include.

2023-08-02 06:11 UTC, marco-antognini-sonarsource commented on ci/validate_asciidoc.sh
>  #  * Asciidoc files are free or errors and warnings.
Maybe it's _possible_, but not easy not maintainable AFAICT: we'd need to hack into the logging system somehow. It would be easier to fix https://github.com/asciidoctor/asciidoctor/issues/3414.

Also, we need a run with `rspectator-view` and one without it. The first is currently only executed if the second did not fail. We'd need to redesign this and how the plugins are enabled in the custom-asciidoctor (e.g., we don't want them when rspecatator view is disabled).

2023-08-02 06:42 UTC, marco-antognini-sonarsource commented
> Have you tried running it on CI with some failures it detects (smoke tests)? I'd be curious to see the CI logs if any

I tested locally during development and at one point on the CI. I can't find the run again -- too many squashed commits to go through. Here are fresh runs:

* [this one](https://cirrus-ci.com/task/5497328451190784?logs=asciidoc_tests#L86) shows how it fails when there are unused files.

* [this other one](https://cirrus-ci.com/task/6335321147703296?logs=asciidoc_tests#L94) shows how it fails with bad cross refs.

(The good thing is, in rewriting the test I noticed a small issue with the impl. Fixed in 6ace02f.)

2023-08-02 06:57 UTC, necto commented on ci/custom-asciidoctor
Did you mean just "executable"?
The official `asciidoctor` is a text executable.

This is a matter of taste. To me, the common well-known executables have no extension, and that distinguished them from the custom scripts like this one

2023-08-02 07:00 UTC, necto approved these changes
LGTM

2023-08-02 07:21 UTC, marco-antognini-sonarsource commented on ci/custom-asciidoctor
yes

2023-08-02 07:21 UTC, merged