Create rule S5852[javascript]: Using slow regular expressions is security-sensitive
SonarSource/rspec pull request #269
Opened 2021-08-18 07:12 UTC by yassin-kammoun-sonarsource

2021-08-18 08:53 UTC, vilchik-elena requested changes

2021-08-18 08:53 UTC, vilchik-elena commented on rules/S5852/javascript/rule.adoc
> +== Ask Yourself Whether
it seems to be the same as for java so we can just use `../ask-yourself.adoc`

2021-08-18 08:53 UTC, vilchik-elena commented on rules/S5852/javascript/rule.adoc
> +In all of the following cases, catastrophic backtracking can only happen if the problematic part of the regex is followed by a pattern that can fail, causing the backtracking to actually happen.
why did you remove sentence `Note that when performing a full match...`? it makes sense for JS. Just replace example method call

2021-08-18 08:53 UTC, vilchik-elena commented on rules/S5852/javascript/rule.adoc
> +Possessive quantifiers do not keep backtracking positions, thus can be used, if possible, to avoid performance issues. Unfortunately, they are not supported in JavaScript, but one can still mimick th
did you find some source recommending that?

2021-08-18 08:53 UTC, vilchik-elena commented on rules/S5852/javascript/rule.adoc
> +/((?=(a+))\2)+$/.test(
looks scary :) can't we just use `/a+$/` in this example?

2021-08-18 08:53 UTC, vilchik-elena commented on rules/S5852/javascript/rule.adoc
> +Most of the regular expression engines use ``++backtracking++`` to try all possible execution paths of the regular expression when evaluating an input, in some cases it can cause performance issues,
how about using simple syntax for inlined code in `.adoc`?

2021-08-18 08:53 UTC, vilchik-elena commented on rules/S5852/javascript/rule.adoc
> +* Refactor ``++nested quantifiers++`` to limit the number of way the inner group can be matched by the outer quantifier, for instance this nested quantifier situation ``++(ba+)+++`` doesn't cause per
I don't get why we use code formatting for terms and keywords (like `nested quantifiers` here). How about using bold or italic?
 Why `nested quantifiers` is at all highlighted? Does not sound like any particular term

2021-08-18 08:53 UTC, vilchik-elena commented on rules/S5852/javascript/rule.adoc
> +* Use an alternative non-backtracking regex implementations such as Google's https://github.com/google/re2[RE2] or https://github.com/uhop/node-re2/[node-re2].
are those available for JS?

2021-08-18 08:53 UTC, vilchik-elena commented on rules/S5852/javascript/rule.adoc
> +* When using ``++String.prototype.match()++``, it is often possible to make the regex infallible by making all the parts that could fail optional, which will prevent backtracking. Of course this mean
`str.match(regex)` is `null` if match is not found

2021-08-18 10:58 UTC, yassin-kammoun-sonarsource commented on rules/S5852/javascript/rule.adoc
> +Possessive quantifiers do not keep backtracking positions, thus can be used, if possible, to avoid performance issues. Unfortunately, they are not supported in JavaScript, but one can still mimick th
Yes, here is the article describing how to prevent backtracking: https://javascript.info/regexp-catastrophic-backtracking#preventing-backtracking

2021-08-18 10:59 UTC, yassin-kammoun-sonarsource commented on rules/S5852/javascript/rule.adoc
> +/((?=(a+))\2)+$/.test(
Of course `/a+$/` is simpler, and yes`/((?=(a+))\2)+$/` looks scary, but the point here is to show how to prevent backtracking.

2021-08-18 11:20 UTC, yassin-kammoun-sonarsource commented on rules/S5852/javascript/rule.adoc
> +* Use an alternative non-backtracking regex implementations such as Google's https://github.com/google/re2[RE2] or https://github.com/uhop/node-re2/[node-re2].
For node.js applications only.

2021-08-18 11:25 UTC, yassin-kammoun-sonarsource commented on rules/S5852/javascript/rule.adoc
> +* When using ``++String.prototype.match()++``, it is often possible to make the regex infallible by making all the parts that could fail optional, which will prevent backtracking. Of course this mean
I will improve the example because I guess it's not clear enough.

2021-08-18 13:06 UTC, vilchik-elena commented on rules/S5852/javascript/rule.adoc
> +* When using `+String.prototype.match()+`, it is often possible to make the regex infallible by making all the parts that could fail optional, which will prevent backtracking. Of course this means th
I would use `!==`

2021-08-18 13:07 UTC, vilchik-elena approved these changes

2021-08-23 14:27 UTC, vilchik-elena commented on rules/S5852/javascript/rule.adoc
> +This rule determines the runtime complexity of a regular expression and informs you of the complexity if it is not linear.
`This rule determines the runtime complexity of a regular expression and informs you if the complexity is not linear.` - I am not sure we will be able to report the complexity

2021-08-24 07:36 UTC, yassin-kammoun-sonarsource commented on rules/S5852/javascript/rule.adoc
> +This rule determines the runtime complexity of a regular expression and informs you of the complexity if it is not linear.
Then, what about: `This rules reports on quantifiers causing super-linear worst-case time complexity.` ?

2021-09-03 09:53 UTC, vilchik-elena commented on rules/S5852/javascript/rule.adoc
> +In all of the following cases, catastrophic backtracking can only happen if the problematic part of the regex is followed by a pattern that can fail, causing the backtracking to actually happen.
I think I was wrong, `String.prototype.match` is also partial match

2021-09-03 10:03 UTC, yassin-kammoun-sonarsource reviewed
lgtm

2021-09-03 10:15 UTC, merged