Modify rule S2318: LaYC format
SonarSource/rspec pull request #2690
Opened 2023-07-27 13:19 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-27 13:45 UTC, maksim-grebeniuk-sonarsource commented on rules/S2318/python/rule.adoc
> +
Should 'How to fix it' header be here?

2023-07-27 13:45 UTC, maksim-grebeniuk-sonarsource requested changes
Looks good, just left formatting question comment

2023-07-27 13:48 UTC, joke1196 commented on rules/S2318/python/rule.adoc
> +
No so if the rule is quite short we do not need to split it in two tabs. I think it makes sense in this one to keep everything in the main tab as it is a one-liner. You can check [here](https://github.com/SonarSource/rspec/blob/master/docs/description.adoc) to see which sections are optional or not.

2023-07-28 11:59 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM, minor comment, feel free to ignore.

2023-07-28 11:59 UTC, guillaume-dequenne-sonarsource commented on rules/S2318/python/rule.adoc
> +The operators ``++<>++`` and ``++!=++`` are equivalent, but since Python 2.7 the ``++<>++`` form is considered obsolete and is removed in newer version of Python.
When has it been removed?
If it's been removed in Python 3, I'd just say "and has been removed in Python 3."
That way we don't imply this is a super recent development 😄

2023-08-03 14:03 UTC, maksim-grebeniuk-sonarsource approved these changes
LGTM

2023-08-07 10:17 UTC, jean-jimbo-sonarsource commented on rules/S2318/python/rule.adoc
> +The operators ``++<>++`` and ``++!=++`` are equivalent, but since Python 2.7 the ``++<>++`` form is considered obsolete and has been removed in Python 3.
We can phrase this better:

"The <> and != operators are equivalent. However, the <> operator is considered obsolete in Python 2.7 and has been removed from Python 3. Therefore, it is recommended to use != instead."

2023-08-07 10:17 UTC, jean-jimbo-sonarsource approved these changes
Left a rephrase comment

2023-08-07 13:14 UTC, jean-jimbo-sonarsource approved these changes

2023-08-07 13:16 UTC, merged