Modify rule S4023: LayC and improve rule description
SonarSource/rspec pull request #2691
Opened 2023-07-27 13:30 UTC by martin-strecker-sonarsource

see also https://github.com/SonarSource/sonar-dotnet/issues/7633#issuecomment-1653156163

2023-07-31 09:14 UTC, cristian-ambrosini-sonarsource requested changes
Left a few suggestions

2023-07-31 09:14 UTC, cristian-ambrosini-sonarsource commented on rules/S4023/csharp/rule.adoc
> +}
That's a good sample, just a thought: I would simplify it a bit and avoid all the JSON serialization configuration, I think it's not a relevant topic for this rule and might add complexity for the reader.

2023-07-31 09:14 UTC, cristian-ambrosini-sonarsource commented on rules/S4023/csharp/rule.adoc
> +[source,csharp,diff-id=2,diff-type=noncompliant]
It's a bit confusing to have one solution in the "Why section" and another solution in the "How to fix it".
I would keep both examples in this section, each under their appropriate bullet point.
- Add members to the interface:
[Noncompliant/Compliant snippet]
- Replace the usage as a marker interface with custom attributes
[Noncompliant/Compliant snippet]

2023-07-31 11:48 UTC, martin-strecker-sonarsource commented on rules/S4023/csharp/rule.adoc
> +}
If I remove that part, the `includeFields` variable is mysterious to the reader: What is this used for? By assigning it to `JsonSerializerOptions.IncludeFields` it is obvious to the reader and he can look it up to learn more about it. I think it is essential to the understanding of the `Serialize` method purpose.

2023-07-31 13:04 UTC, cristian-ambrosini-sonarsource requested changes

2023-07-31 13:04 UTC, cristian-ambrosini-sonarsource commented on rules/S4023/csharp/rule.adoc
> +Interfaces describe functionality that an implementing class has to provide. An empty interface doesn't add any such functional requirements and is as such useless.
```suggestion
Empty interfaces should be avoided as they do not provide any functional requirements for implementing classes.
```

2023-07-31 13:04 UTC, cristian-ambrosini-sonarsource commented on rules/S4023/csharp/rule.adoc
> +public interface IAggregate: IComparable, IFormattable { } // Compliant
The first snippet has a `// Compliant` comment, the second an extended `// Compliant: explanation` and the third none. IMO we can improve a bit the consistency

2023-08-01 10:23 UTC, cristian-ambrosini-sonarsource approved these changes
LGTM!

2023-08-01 16:23 UTC, merged

2023-08-02 07:38 UTC, bart-vmware commented on rules/S4023/csharp/rule.adoc
> +        // Take decisions based on the presents of the marker
~presents~ presence

2023-08-02 07:38 UTC, bart-vmware commented on rules/S4023/csharp/rule.adoc
> +        // Take decisions based on the presents of the marker
~presents~ presence

2023-08-02 07:53 UTC, martin-strecker-sonarsource commented on rules/S4023/csharp/rule.adoc
> +        // Take decisions based on the presents of the marker
Thank you! #2755