Modify rule S1048,S3654: LaYC format
SonarSource/rspec pull request #2698
Opened 2023-07-28 10:20 UTC by marco-antognini-sonarsource

I moved and edited the content for S3654. It may be easier to review this commit by commit. Those commits that move content around did not modify it.

Github cannot display the final result but VSCode can. I also checked it looked fine by running `gradle rule -Prule=SXXX -Pbranch=mb/S1048-S3654` in our CFamily plugin.

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-31 09:58 UTC, necto reviewed
This is the first time I see the use of `docdir` (and I learned about it) and the "ping-pong" include, including the file from a shared folder that would include a file back from your folder.

I expect this to be surprising for others, and it might work poorly with some non-fully-asciidoc-compliant tools and scripts (as you've discovered with our bash validation script, which should be fixed of course).
For example, it breaks the GitHub built-in viewer, as it replaces includes with links rather than doing the textual inclusion.

In this particular case, "exception_in_destructor.adoc" represent sharing of three things:
1. the document structure
2. the "Why is this an issue?" section
3. the "External coding guidelines" section

Do you think the complexity of the include organization is worth the amount of code reuse?

An alternative I see is to duplicate the structure (already duplicated across all LaYC-ready rules),
and include only the "Why is this an issue?" section into S3654 and S1048 specifications.
For the "External coding guidelines", as it is rather small, it sounds equally fine to duplicate it or to include it.

2023-07-31 11:03 UTC, marco-antognini-sonarsource commented
> I expect this to be surprising for others, and it might work poorly with some non-fully-asciidoc-compliant tools and scripts (as you've discovered with our bash validation script, which should be fixed of course).
> For example, it breaks the GitHub built-in viewer, as it replaces includes with links rather than doing the textual inclusion.

I don't see an issue here. Let me explain.

First, it's a standard variable. As such, the surprise should be limited to reading the doc. This also means official tools should support it. If they don't, it's a bug on their side.

The fact our validation script did not handle it is a bug on our side. Also, our validation script has [some known & documented limitations with variables](https://github.com/SonarSource/rspec/blob/a7c717ca7559e297edcb704873f233f33ded3ceb/ci/replace_variables_in_path.sh#L17).

Regarding GitHub built-in viewer, regular includes are already not enabled ([a random example](https://github.com/SonarSource/rspec/blob/a7c717ca7559e297edcb704873f233f33ded3ceb/rules/S1134/rule.adoc#L11)). So this changes nothing.

2023-07-31 11:41 UTC, necto commented
> Regarding GitHub built-in viewer, regular includes are already not enabled ([a random example](https://github.com/SonarSource/rspec/blob/a7c717ca7559e297edcb704873f233f33ded3ceb/rules/S1134/rule.adoc#L11)). So this changes nothing.

The regular includes are "enabled" through the clickable links. While it is less convenient than the proper support for includes, it still allows you to see what the included file adds to the document by clicking on the link.
This breaks, however, once you add variables into the mix, as your link above demonstrates.

> This also means official tools should support it. If they don't, it's a bug on their side.

You can call it a bug, they might call it "partial support". In the end, it is we who will bear the consequences of using a less common feature. That's why to me it is still a downside to using it.

2023-08-02 06:53 UTC, marco-antognini-sonarsource commented
> This breaks, however, once you add variables into the mix, as your link above demonstrates.

My point exactly: GitHub preview is already not suited to (re)view RSPEC.

> You can call it a bug, they might call it "partial support". In the end, it is we who will bear the consequences of using a less common feature. That's why to me it is still a downside to using it.

I feel this argument is moot because we only use official tools (I don't even know of an unofficial asciidoc tool), and it works.

---

I'd rather we take this feature under a different lens: is it helping in writing rule descriptions? It is probably a bit subjective, but I feel the current PR shows it is valuable: two rules have the same structure, and the `docdir` variable helps not duplicate the structure in addition to the content.

2023-08-02 09:16 UTC, necto commented
> is it helping in writing rule descriptions?

Indeed it seems subjective, as for me both variants seem equally usable, modulo the additional tool-reliance of the approach taken in this PR.

Let's agree to disagree.

2023-08-02 13:08 UTC, amelie-renard-sonarsource requested changes
Good work, very thorough!
Small comments, mainly about CCT

2023-08-02 13:08 UTC, amelie-renard-sonarsource commented on shared_content/cfamily/exception_in_destructor.adoc
> +In all cases, `std::terminate` results in an implementation-defined, abrupt, and unclean program termination.
This is about "what is the potential impact?", the software quality involved being reliability.
I am not sure it is useful to put it with a distinct subtitle, but I would still put it at the end of the text, after the example.

2023-08-03 10:16 UTC, marco-antognini-sonarsource reviewed
Thanks for the feedback.

2023-08-03 11:38 UTC, amelie-renard-sonarsource commented on shared_content/cfamily/exception_in_destructor.adoc
> +Throwing an exception from a destructor may result in a call to `std::terminate`.
Works for me!

2023-08-03 11:39 UTC, amelie-renard-sonarsource commented on shared_content/cfamily/exception_in_destructor.adoc
> +In all cases, `std::terminate` results in an implementation-defined, abrupt, and unclean program termination.
Indeed, the subtitle works well, specially with the additional content

2023-08-03 11:48 UTC, amelie-renard-sonarsource commented on shared_content/cfamily/exception_in_destructor.adoc
> +However, even a destructor declared as `noexcept(false)` calls `std::terminate` when it throws during stack unwinding.
Okay, fine with me.
It may be interesting to link one blog post about this if there is one reliable and well-documented.

2023-08-03 12:58 UTC, amelie-renard-sonarsource requested changes
One small comment, otherwise LGTM

2023-08-03 14:06 UTC, marco-antognini-sonarsource commented on shared_content/cfamily/exception_in_destructor.adoc
> +However, even a destructor declared as `noexcept(false)` calls `std::terminate` when it throws during stack unwinding.
The best I could find is http://www.gotw.ca/gotw/047.htm, but it's outdated -- like all the others I've found -- and focuses on why `std::uncaught_exception()` isn't enough, for which we have [S6015](https://sonarsource.github.io/rspec/#/rspec/S6015/cfamily).

Maybe we should cover this in more depth in S6015 when rewriting it... not 100% sure yet.

2023-08-04 07:37 UTC, amelie-renard-sonarsource commented on shared_content/cfamily/exception_in_destructor.adoc
> +However, even a destructor declared as `noexcept(false)` calls `std::terminate` when it throws during stack unwinding.
Ok, nevermind then :)

2023-08-04 07:37 UTC, amelie-renard-sonarsource approved these changes

2023-08-04 07:38 UTC, merged