Modify rule S4999,S5000: LaYC format
SonarSource/rspec pull request #2712
Opened 2023-07-31 08:51 UTC by marco-antognini-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-14 12:03 UTC, alejandro-alvarez-sonarsource requested changes

2023-09-14 12:03 UTC, alejandro-alvarez-sonarsource commented on rules/S5000/cfamily/rule.adoc
> +* S4999 - "memcpy", "memmove", and "memset" should only be called with pointers to trivially copyable types
```suggestion
* S4999 - `memcpy`, `memmove`, and `memset` should only be called with pointers to trivially copyable types
```

2023-09-14 12:03 UTC, alejandro-alvarez-sonarsource commented on shared_content/cfamily/trivially_copyable_types.adoc
> +_Note: a default implementation, either explicit (with `= default`) or implicit (if the special member function is omitted), is considered trivial._
```suggestion
_Note: a default implementation is always considered trivial, both when it is explicit (with `= default`) or implicit (if the special member function is omitted)._
```

2023-09-14 12:50 UTC, marco-antognini-sonarsource commented on rules/S4999/cfamily/rule.adoc
> +* S5000 - "memcmp" should only be called with pointers to trivially copyable types with no padding
I agree it's not great but the [policy](https://github.com/SonarSource/rspec/blob/master/docs/link_formatting.adoc) is to use the title verbatim, so with regular quotes `"`.

2023-09-14 12:52 UTC, marco-antognini-sonarsource reviewed
Thanks for the nice suggestions!

2023-09-18 11:32 UTC, alejandro-alvarez-sonarsource approved these changes

2023-09-19 06:14 UTC, merged