Modify rule S3925: Adopt exception description to the new behavior
SonarSource/rspec pull request #2713
Opened 2023-07-31 10:44 UTC by martin-strecker-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-07-31 12:56 UTC, cristian-ambrosini-sonarsource requested changes

2023-07-31 12:56 UTC, cristian-ambrosini-sonarsource commented on rules/S3925/csharp/rule.adoc
> +This rule only raises an issue on classes that indicate that they are interested in serialization (see the _Exceptions_ section). That is to reduce noise because a https://learn.microsoft.com/en-us/d
id this chained link sentence on purpose? :satisfied: 
I propose to have the text followed by a brief bullet-point list to increase the readability, or a list within brackets (System.Exception, Regex...).

2023-07-31 12:56 UTC, cristian-ambrosini-sonarsource commented on rules/S3925/csharp/rule.adoc
> +  1. Having a `[Serializable]` attribute applied
Information: do you know if the nested bullet point list is displayed correctly? I wonder if it needs an empty line before this

2023-07-31 12:56 UTC, cristian-ambrosini-sonarsource commented on rules/S3925/csharp/rule.adoc
> +public class SerializationOptIn_Interface: ISerilalizable                                      // 2.
```suggestion
public class SerializationOptIn_Interface : ISerilalizable                                      // 2.
```

2023-08-01 09:48 UTC, martin-strecker-sonarsource commented on rules/S3925/csharp/rule.adoc
> +This rule only raises an issue on classes that indicate that they are interested in serialization (see the _Exceptions_ section). That is to reduce noise because a https://learn.microsoft.com/en-us/d
The list is not complete and has more full illustration purposes. It is a bit unusual but does the job. If I do a bullet list, it will have to end with `* and more`. I don't think that this aspect is important enough to warrant such a big paragraph, but I wouldn't mind changing it. What do you think?

2023-08-01 09:54 UTC, martin-strecker-sonarsource commented on rules/S3925/csharp/rule.adoc
> +  1. Having a `[Serializable]` attribute applied
According to the documentation, it is possible and a newline is optional:
https://docs.asciidoctor.org/asciidoc/latest/lists/ordered/#nested-ordered-list

2023-08-01 10:19 UTC, cristian-ambrosini-sonarsource commented on rules/S3925/csharp/rule.adoc
> +This rule only raises an issue on classes that indicate that they are interested in serialization (see the _Exceptions_ section). That is to reduce noise because a https://learn.microsoft.com/en-us/d
I think for this kind of stuff it's better to ask @cynthiabethea.
Can you please give us your opinion on this sentence? :pray:

2023-08-01 10:21 UTC, cristian-ambrosini-sonarsource approved these changes
LGTM, please wait until we have an answer from Cynthia before merging 👍

2023-08-02 15:58 UTC, cynthiabethea commented on rules/S3925/csharp/rule.adoc
> +This rule only raises an issue on classes that indicate that they are interested in serialization (see the _Exceptions_ section). That is to reduce noise because a https://learn.microsoft.com/en-us/d
My concern is, I don't think it's clear that each word is a distinct link. I would assume it's taking me to a page with a list of such classes. 

What about doing list as part of a setence.

That is to reduce noise because a lot of classes in the base class library are implementing ISerializable, including the following classes: System.Exception, Regex...

So it takes up less space than a bulleted list

2023-08-03 11:53 UTC, cristian-ambrosini-sonarsource approved these changes
I prefer this one a lot. LGTM!

2023-08-03 13:41 UTC, merged