Modify rule S5912: LaYC format
SonarSource/rspec pull request #2714
Opened 2023-07-31 12:03 UTC by marco-antognini-sonarsource

Given the nature of the bug is easy to understand, I didn't feel it was worth explicitly mentioning this is makes the application unreliable. Let me know if you disagree.

## Review

A dedicated reviewer checked the rule description successfully for:

- [x] logical errors and incorrect information
- [x] information gaps and missing content
- [x] text style and tone
- [x] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-04 12:26 UTC, amelie-renard-sonarsource requested changes
I agree that there is no need to talk more about the software qualities, as it is simple.

2023-08-04 12:26 UTC, amelie-renard-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +It is usually a good idea to design a base class so that slicing cannot happen: it can be abstract or non-copiable.
How about putting it into "Going the extra mile"?
And also mention what to do when you do the slicing on purpose (like what is explained in C++ Core Guidelines)

2023-08-04 12:26 UTC, amelie-renard-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +In the noncompliant example above, the `stream` gets sliced when calling `writeAll`, and its `buffer` may be lost or written out-of-sequence.
I would remove this sentence and update the "Noncompliant" comment above (as in my suggestion)

2023-08-04 12:26 UTC, amelie-renard-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +  writeAll(stream, data); // Noncompliant: stream is sliced.
```suggestion
  writeAll(stream, data); // Noncompliant: stream is sliced, and its buffer may be lost or written out-of-sequence
```

2023-08-04 12:26 UTC, amelie-renard-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +To prevent this from happening, the base class can be made non-copyable.
```suggestion
To prevent slicing from happening, the base class can be made non-copyable.
```

2023-08-04 12:26 UTC, amelie-renard-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +The same strategy is applied for `std::ostream` and co.
I would put this last sentence when we explain to the user that slicing can be prevented by making a class non-copyable or abstract (so in the description of "How to fix it" or "Going the extra mile"

2023-08-04 12:26 UTC, amelie-renard-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +This code defect is usually the consequence of not using polymorphism correctly.
I am uncomfortable with this sentence: for me, it's more a problem of (for example) passing by copy instead of reference. The general polymorphism architecture may be correct.
When I read incorrect uses of polymorphism, I think more about not using inheritance, redefining functions instead of overriding etc.
Does that make sense?

2023-08-10 13:44 UTC, marco-antognini-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +  std::string description;
I feel that only one field makes the example less obvious why we are using inheritance to reuse definitions.

Maybe keeping two would be a good compromise, WDYT?

```suggestion
  int uuid;
  std::string manufacturer;
```

2023-08-10 13:44 UTC, marco-antognini-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +This code defect is usually the consequence of not using polymorphism correctly.
It totally does. I'll think about how to improve this. Thanks.

2023-08-10 13:44 UTC, marco-antognini-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +In the noncompliant example above, the `stream` gets sliced when calling `writeAll`, and its `buffer` may be lost or written out-of-sequence.
Makes sense indeed. It would be closer to the defect and easier to understand/follow.

2023-08-10 13:44 UTC, marco-antognini-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +In the noncompliant example above, the `stream` gets sliced when calling `writeAll`, and its `buffer` may be lost or written out-of-sequence.
```suggestion
```

2023-08-10 13:44 UTC, marco-antognini-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/efbc482f0d10555c6a8827906af71430a3023bd2/CppCoreGuidelines.md#es63-dont-slice[ES.63 Don't slice]
The revision you suggest to use is 4 years old. Mine is only a month old. Ideally, we should update all links, but it requires manually verifying that the anchors are valid.

2023-08-10 14:35 UTC, marco-antognini-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +The same strategy is applied for `std::ostream` and co.
Makes sense. I moved it to How to fix it, and rephrased it a bit.

2023-08-10 14:35 UTC, marco-antognini-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +It is usually a good idea to design a base class so that slicing cannot happen: it can be abstract or non-copiable.
I thought a bit about this one.

I feel the "non-copyable" part should be part of the main "how to fix it" -- it's also used in an example below. I tried to move it to "going the extra mile" section but it felt strange when reading the description.

I do agree on the "slicing on purpose", it belongs there.

2023-08-10 14:35 UTC, marco-antognini-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +This code defect is usually the consequence of not using polymorphism correctly.
I rephrased a bit this part of the description. Let me know if it's better or can be further improved.

2023-08-11 06:43 UTC, amelie-renard-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +  std::string description;
Yes, I'm fine with that

2023-08-11 06:47 UTC, amelie-renard-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/efbc482f0d10555c6a8827906af71430a3023bd2/CppCoreGuidelines.md#es63-dont-slice[ES.63 Don't slice]
We had discussions about it and chose to keep the links consistent with one another (see ticket [CPP-4080](https://sonarsource.atlassian.net/browse/CPP-4080)). Here the two versions are identical so we can keep the consistency

2023-08-11 06:49 UTC, amelie-renard-sonarsource approved these changes
I really like this new version, good work!

2023-08-11 06:58 UTC, marco-antognini-sonarsource commented on rules/S5912/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/efbc482f0d10555c6a8827906af71430a3023bd2/CppCoreGuidelines.md#es63-dont-slice[ES.63 Don't slice]
Fair. I recorded my thoughts on the ticket. I'll apply the suggestion for consistency and we can revisit when the ticket is worked on.

2023-08-11 07:03 UTC, merged