Modify rule S1913: LaYC format
SonarSource/rspec pull request #2747
Opened 2023-07-31 14:22 UTC by marco-antognini-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-02 09:22 UTC, amelie-renard-sonarsource requested changes

2023-08-02 09:22 UTC, amelie-renard-sonarsource commented on rules/S1913/cfamily/rule.adoc
> +In other words, its value does not depend on `e` nor has any side effects.
"nor has any side effects": I find this information necessary and think we should emphasize it more.
The way I see it is that the user likely made a mistake because:
- sizeof(sizeof()) always returns the same result and does not depend on `e`
- sizeof does not evaluate the expression, which means that there is no side effect

I would separate these two things to make the second one more explicit than it currently is. WDYT?

2023-08-02 10:02 UTC, marco-antognini-sonarsource commented on rules/S1913/cfamily/rule.adoc
> +In other words, its value does not depend on `e` nor has any side effects.
Great idea. I rephased the description in bdd67d6213. Let me know what you think.

2023-08-02 11:19 UTC, amelie-renard-sonarsource commented on rules/S1913/cfamily/rule.adoc
> +This means that `sizeof(sizeof(e))` is equivalent to `sizeof(size_t)`.
What about:
```suggestion
Given an expression `e` of type `T`, `sizeof(e)` returns the size in bytes of `T`. The `sizeof` function does not evaluate the expression `e`, and the result of `sizeof(e)` is of type `size_t`. Therefore, `sizeof(sizeof(e))` is equivalent to `sizeof(size_t)`.
```

2023-08-02 11:23 UTC, amelie-renard-sonarsource commented on rules/S1913/cfamily/rule.adoc
> +In other words:
And then, I would keep:
```suggestion
In other words, `sizeof(sizeof(e))` always returns the same result and does not depend on `e`, which is unlikely what was expected.
```

2023-08-02 11:24 UTC, amelie-renard-sonarsource commented on rules/S1913/cfamily/rule.adoc
> +In other words, its value does not depend on `e` nor has any side effects.
I find the result better but still a bit hard to follow. I wrote down suggestions, let me know what you think.

2023-08-02 12:36 UTC, marco-antognini-sonarsource commented on rules/S1913/cfamily/rule.adoc
> +This means that `sizeof(sizeof(e))` is equivalent to `sizeof(size_t)`.
Thanks for the suggestion.

Pedantic nit: `sizeof` is an operator, not a function. Although the difference does not really matter here, I've adapted your suggestion.

I also changed it slightly in 8771cba278 to have one statement/fact per sentence. I've also put more emphasis on the "no side effect" parts.

2023-08-03 07:17 UTC, amelie-renard-sonarsource approved these changes
Small suggestion, otherwise LGTM

2023-08-03 07:17 UTC, amelie-renard-sonarsource commented on rules/S1913/cfamily/rule.adoc
> +The `sizeof` operator results in a value of `size_t`.
I am not used to this wording, so it seems strange to me.
What about:
```suggestion
The `sizeof` operator results in a value of type `size_t`.
```
Or
```suggestion
The return type of the `sizeof` operator is `size_t`.
```

2023-08-03 09:18 UTC, merged