Modify rule S5314: Expand and adjust for LaYC
SonarSource/rspec pull request #2748
Opened 2023-07-31 15:32 UTC by balazs-benics-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-01 08:03 UTC, tomasz-kaminski-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +Concurrent accesses to shared resources are guarded by synchronization
I think you should include an example code illustrating deadlock here. I.e. Two mutexes trying to be locked.
In general, I think having some code samples, explaining what we are talking about, in why this is an issues helps.

2023-08-01 08:13 UTC, tomasz-kaminski-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +Usually, blocking operations are separated from the critical section along
This sounds like a statement of the fact, and not an instruction, guide how to fix it. I think it should say something like, that  usually code can be changed to move such operation out of critical section.

2023-08-01 08:28 UTC, tomasz-kaminski-sonarsource requested changes
Looks good. However, I think we need some more code examples, and adjust how to fix it.

2023-08-01 08:28 UTC, tomasz-kaminski-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +#include <unistd.h>  // sleep()
This rule applies for C, but examples are only for cpp. I would check what rule detect, and add examples for C here, and to lit, if they are not present.

2023-08-01 08:28 UTC, tomasz-kaminski-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +Time-Of-Check-To-Time-Of-Use (TOCTOU) bugs.
Code example, if possible would be great.

2023-08-01 09:03 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +#include <unistd.h>  // sleep()
The rule fires for C++ as well.
Here is the non-compliant example on CompilerExplorer: https://godbolt.org/z/r1Ee6j7cq
I added a C example as well, using `pthreads`, which also passes: https://godbolt.org/z/5Gc76M8vY

2023-08-01 09:07 UTC, tomasz-kaminski-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +#include <unistd.h>  // sleep()
If we add such example for rspec, we should make sure that we actually detect them. What we have done up to this point is to create an sonar-cpp PR, that contains both updated rspec and additional lit tests.

2023-08-01 09:34 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +Time-Of-Check-To-Time-Of-Use (TOCTOU) bugs.
Added, however, it ended up quite complicated.
And I also decided to mention the ABA problem.

2023-08-01 09:34 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +#include <unistd.h>  // sleep()
I'll add these tests in a separate PR to the sonar-cpp.

2023-08-01 09:41 UTC, tomasz-kaminski-sonarsource requested changes

2023-08-01 09:41 UTC, tomasz-kaminski-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +[source,c]
You can have second diff mark.

2023-08-01 09:41 UTC, tomasz-kaminski-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +  do_expensive_work(value);
Would add `uncomplaint` marker here.

2023-08-01 09:41 UTC, tomasz-kaminski-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +[source,cpp]
I know that I requested it, but I am not sure about this example. It is long, and I do not think add much. So maybe remove it.

2023-08-01 09:41 UTC, tomasz-kaminski-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +#include <mutex>
This one is great.

2023-08-01 09:41 UTC, tomasz-kaminski-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +int input;
Would declare some classes for that. Even as `class Input { ... }`.

2023-08-01 09:51 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +  do_expensive_work(value);
Do you mean "non-compliant"?

2023-08-01 09:52 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +[source,cpp]
Reverted!

2023-08-01 09:58 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +int input;
I'm not sure I share this opinion.
To me, the example is already convoluted and bloated.
By using a custom UDT here, I would need to have a "default" input basically a sentinel, which is currently represented by `-1`.
As well as an equality operator to check if the input has changed or not.
Additionally, if I have a class, it might be actually a better design to encapsulate the mutex in the object itself, depending on the scenario.

Given all this, I'd prefer not to have a class here.

2023-08-01 09:59 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +  do_expensive_work(value);
I decided not to put `non-compliant` in this example, as we cannot see a blocking call, thus we won't diagnose it either.
I'd rather keep the `non-compliant` comments for coding patterns for which we raise an issue.

2023-08-01 10:00 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +[source,c]
I've heard that only the first diff will be displayed, thus it's not advised to have multiple diff markers.

2023-08-01 10:26 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +Time-Of-Check-To-Time-Of-Use (TOCTOU) bugs.
I split the ABA problem from the example, and mentioned after the example.

2023-08-01 10:52 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +#include <unistd.h>  // sleep()
Here is the PR: https://github.com/SonarSource/sonar-cpp/pull/2916

2023-08-01 10:52 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +[source,c]
I added the diff markers.

2023-08-01 11:04 UTC, tomasz-kaminski-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +  do_expensive_work(value);
I would change this example then to something we can actually detect. We may otherwise put false expectation on the user. Same would apply to pitfall.

2023-08-01 12:22 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +  do_expensive_work(value);
I'm not exactly sure how to achieve that. Given how limited this rule is. I actually mentioned this in the spreadsheet.
Look at [here](https://github.com/SonarSource/llvm-project/blob/v16/clang/lib/StaticAnalyzer/Checkers/BlockInCriticalSectionChecker.cpp#L96), how the list of "blocking" functions is defined.
```C++
bool BlockInCriticalSectionChecker::isBlockingFunction(const CallEvent &Call) const {
  return matchesAny(Call, SleepFn, GetcFn, FgetsFn, ReadFn, RecvFn);
}
```
I don't really want to put a `sleep()` there as I don't think would be representative.
Calling `getc`, `fgets`, `read`, and `recv` is also quite inappropriate in this context. They you at least need some setup code to get a file-descriptor to do anything.

And in general, the rule won't be able to catch all of these issues. So, I had a mindset to rather educate the user with a sensible, but not too concrete example.

2023-08-01 13:15 UTC, balazs-benics-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +  do_expensive_work(value);
Fixed. Have a look.

2023-08-01 13:21 UTC, tomasz-kaminski-sonarsource approved these changes

2023-08-02 08:06 UTC, tomasz-kaminski-sonarsource commented on rules/S5314/cfamily/rule.adoc
> +Note that in the example, it might not be always correct to commit the result even if the `input` didn't change since we last checked. It could be that it was changed, but it was restored as we are c
The `in example` for me sugget above example code. I would just drop it.
```suggestion
Note that, it might not be always correct to commit the result even if the `input` didn't change since we last checked. It could be that it was changed, but it was restored as we are checking it again. This is commonly known as the ABA problem, where `A` and `B` refers to the values of the resource.
```

2023-08-02 08:07 UTC, tomasz-kaminski-sonarsource commented
Just single edit, and you can merge it.

2023-08-02 15:22 UTC, merged