Modify rule S5486: Expand and adjust for LaYC
SonarSource/rspec pull request #2751
Opened 2023-08-01 13:20 UTC by balazs-benics-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-01 13:45 UTC, tomasz-kaminski-sonarsource requested changes

2023-08-01 13:45 UTC, tomasz-kaminski-sonarsource commented on rules/S5486/cfamily/rule.adoc
> +"pthread_mutex_t" should not be consecutively locked or unlocked twice
This for me suggest that this rule works only if two locks are placed one after the another. Which is not the case.

2023-08-01 13:45 UTC, tomasz-kaminski-sonarsource commented on rules/S5486/cfamily/rule.adoc
> +* _non recursive mutexes_ are targeted by this rule.
I think to make that statement, you should explain what recursive on non-recursive mutexes are. 
I think I would suggest going with a description, starting with explaining critical section, and how mutexes are used to create it.

For example, something like, to be reworded
1. When a program run multiple threads, multiple threads may at the same time access (concurrently) the same data or other resources. Such concurrent access needs to be avoided...., and here come mutext.
2. Then how mutexes are used to create critical section (with code examples).
3. The go into locking.


In general, when writing rspec, I would think what kind of programmer would actually read 
"why this is an issue?" section. Somoene who understands concepts like recursive mutext, will not bother to checking why locking twice is an problem.

2023-08-02 07:52 UTC, balazs-benics-sonarsource commented on rules/S5486/cfamily/rule.adoc
> +* _non recursive mutexes_ are targeted by this rule.
I think it makes sense. Have a look at how I incorporated this suggestion.

2023-08-02 08:11 UTC, tomasz-kaminski-sonarsource commented on rules/S5486/cfamily/rule.adoc
> +"pthread_mutex_t" should not be consecutively locked or unlocked twice
I think all synonyms of consecutively will have the same issues. Maybe something like more descriptive:
> locked twice, without being unlocked in between, or unlocked twice, without being locked in between.

2023-08-02 08:34 UTC, tomasz-kaminski-sonarsource approved these changes
This looks good to me. I would recommend having a second pair of eyes to check it.

2023-08-02 14:10 UTC, necto requested changes

2023-08-02 14:10 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +Unlocking a _released_ mutex is _undefined behavior_.
In other rules, we add a sentence about what is _undefined behavior_ really about. like

> This means the compiler is not bound by the language standard anymore and your program has no meaning assigned to it.

e.g. [S3529](https://github.com/SonarSource/rspec/blob/cfb0d089bbf1141761208c5908d80486489b3620/rules/S3529/cfamily/rule.adoc#what-is-the-potential-impact)

And add possible concrete consequences if any. Concrete examples of undefined behavior have more impact on the reader

2023-08-02 14:10 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +  pthread_mutex_unlock(&m2);
Didn't you write above that it should be in reverse order? This might be confusing

2023-08-02 14:10 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +  pthread_mutex_lock(&m1);
```suggestion
  pthread_mutex_lock(&m1); // Noncompliant: m1 is already locked
```

2023-08-02 14:10 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +  pthread_mutex_unlock(&m1);
```suggestion
  pthread_mutex_unlock(&m1); // Noncompliant: m1 is already unlocked
```

2023-08-02 14:10 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +  pthread_mutex_lock(&m2);
```suggestion
  pthread_mutex_lock(&m2); // Compliant: m1 is locked, but m2 is not
```

2023-08-02 14:10 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +  callback(); // If locks mutex 'm', then we have a deadlock.
```suggestion
  callback(); // If tries to lock mutex 'm', then we have a deadlock.
```

2023-08-02 14:10 UTC, necto commented on rules/S5486/cfamily/rule.adoc
>  == Resources
Please format the links according to https://github.com/SonarSource/rspec/blob/master/docs/link_formatting.adoc

2023-08-02 15:31 UTC, necto commented on rules/S5486/cfamily/rule.adoc
>  == Resources
I was primarily referring to the hyperlink being on the title, and not the source. Here is an [example](https://github.com/SonarSource/rspec/blob/a6984ff38766deefba7a7fe7fb38ce27ab22814f/rules/S1232/cfamily/rule.adoc#resources)

`grep` is not effective at the moment because most of our rules follow an outdated format.

For CWE, we do not need to mention MITRE, just CWE as a source, and the naked number as the subject title prefix, see [this example](https://github.com/SonarSource/rspec/pull/2596/files#diff-399a5f611cc941a3a4072b888d23eeba6341ccf6fc42e0850c2435d3f321f73fR273)

2023-08-02 15:34 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +frequently referred to as a _lock_.
That's fine. I can only suggest a shorter expression
```suggestion
Such mutual exclusion is generally achieved by using a _mutex_, also known as _"lock"_.
```
But I just wanted to make sure the "which is ... referred to" is indeed applied to the "mutex" and the "action of achieving mutual exclusion".

2023-08-02 15:37 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> -=== on 6 Nov 2019, 23:32:48 Loïc Joly wrote:
"is related to XXXX" is an artifact of the migration. I agree that it is better placed in the metadata, but that's an improvement for another day

2023-08-02 15:51 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +Unlocking a _released_ mutex is _undefined behavior_.
I do not know any specifics, so I would just add the sentence cited above (as the reader might not know what "undefined behavior" means and hos bad it is)

2023-08-02 15:54 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +  callback(); // If locks mutex 'm', then we have a deadlock.
since `m` is already locked, `callback` cannot lock it. It can call `lock` which will block until it can lock the mutex (which will never happen). I call that "try to lock" because it will try, but it can't succeed, and it is the trying that leads to deadlock

2023-08-03 05:59 UTC, balazs-benics-sonarsource commented on rules/S5486/cfamily/rule.adoc
> +  callback(); // If locks mutex 'm', then we have a deadlock.
Indeed, I thought I can abbreviate things and I meant by "locks" here that it "calls lock".
I feel it's bikeshedding, but whatever.

2023-08-03 06:04 UTC, balazs-benics-sonarsource commented on rules/S5486/cfamily/rule.adoc
>  == Resources
Thanks for the clarification. Now it makes sense.

2023-08-03 06:05 UTC, balazs-benics-sonarsource commented
I start to get lost in the review. Did I address everything?

2023-08-03 06:52 UTC, balazs-benics-sonarsource commented
I reworded the state transitions paragraph to be more "declarative".
I experimented with using tables, but I couldn't figure out how to make it pretty.
A major problem was: how to give labels to the "state" and "action" dimensions in a nice way.

I considered representing the result of the combination in the cell for a given row (state) and column (action).
In the end, I ended up having a pattern matching-like construct, that I believe is still pretty good.

2023-08-03 10:26 UTC, necto requested changes
> I start to get lost in the review. Did I address everything?

I believe you have not addressed [this thread](https://github.com/SonarSource/rspec/pull/2751#discussion_r1281946570)
> - To me, this together with the code snippet belongs to "going the extra mile". You've fixed your double lock as the rule told you, now if you want your code to be better and less prone to such an error, read on about "critical sections" and why to make them small
> - On second thought, I agree with you. It should be in the "extra mile" section.

Personally, to avoid getting lost, I usually abstain from commenting on threads without making sure to address them. For example, "I'll come back to that", is nice communication, but then it puts your comment as the last in the thread. And that is what I rely on when I am looking for the threads I have not addressed: they are the ones that do not end with my own comment.

> I ended up having a pattern matching-like construct, that I believe is still pretty good.

I find it also a nice and concise enough, no need for a table

Another overall comment, subjectively I feel you are overusing _emphasis_. Also sometimes you use it instead of double quotes `"`, but not always.

2023-08-03 10:26 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +A consequence of this blocking behavior is why calling ``lock`` on a _mutex_ that is already _acquired_ by our thread will result in _deadlock_ because it would block until the _mutex_ becomes _avail
This sentence is too long, it overflows my reading buffer

2023-08-03 10:26 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +. _released_ + ``unlock()`` => _undefined behavior_
This is much more clear, thanks!

Since the case you are describing in (*) corresponds to "acquired + lock" (it was acquired by another thread before it had a chance to finish lock), I would move the (*) to the third line "acquired + lock", in this case, it will block and wait.
in the (*) you can note that if no one releases the mutex during this waiting, it is called a "deadlock".

So, if the mutex was locked by a different thread, it is fine, the thread that locked it will likely unlock it eventually.
However, if the mutex was locked by this same thread, it has no one to rescue it.

2023-08-03 10:26 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +"pthread_mutex_t" should not be locked when already locked, or unlocked when already unlocked
```suggestion
"pthread_mutex_t" should not be locked when already locked, or unlocked when already unlocked.
```

2023-08-03 10:26 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +Data structures are designed to maintain their invariants in member-function calls while modifying their internal representation.
This still sounds odd to me, because you usually can't maintain an invariant while modifying internal representation. That's why member-functions are necessary: to maintain invariant between the calls, and encapsulate the code where the invariant is broken. How about dropping the second part here:
```suggestion
Data structures are designed to maintain their invariants between member-function calls.
```

2023-08-03 11:11 UTC, balazs-benics-sonarsource commented on rules/S5486/cfamily/rule.adoc
> +Consequently, _critical sections_ are supposed to be as small as possible.
Move to the "extra mile" section, as-is.

2023-08-03 11:25 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +A consequence of this blocking behavior is why calling ``lock`` on a _mutex_ that is already _acquired_ by our thread will result in _deadlock_ because it would block until the _mutex_ becomes _avail
Or maybe it is malformed:
"A consequence of ... is why calling ... because it would ..., which will ..." - something is amiss.

2023-08-03 13:42 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +These are the possible transitions when calling ``lock`` or ``unlock`` on a _mutex_ in a given state:
Here is my summary of your description of the mental model for dealing with mutexes.
With this preamble, the table below looks correct to me.
Let me know if this summary matches your thinking.
```suggestion
A _mutex_ has two states: _released_ - which is the initial state, or _acquired_.
You can abstract away the concurrent thread sharing the mutex and think of it as owned by the current thread:
it never spontaneously changes between acquired and released.
In this view, these are the possible transitions when calling ``lock`` or ``unlock`` on a _mutex_ in a given state:
```

2023-08-03 13:56 UTC, balazs-benics-sonarsource reviewed
Fixed everything, except rewriting the state transitions.

2023-08-03 13:56 UTC, balazs-benics-sonarsource commented on rules/S5486/cfamily/rule.adoc
> +A consequence of this blocking behavior is why calling ``lock`` on a _mutex_ that is already _acquired_ by our thread will result in _deadlock_ because it would block until the _mutex_ becomes _avail
I think I addressed this one. Let me know if you like it.

2023-08-03 14:04 UTC, balazs-benics-sonarsource commented
@arseniy-sonar Sorry about the spurious review request about 5 minutes ago.
I didn't know you already wrote your suggestion to the "transition" section.
I liked it.

Now, it's in the final from.

2023-08-03 14:44 UTC, necto requested changes

2023-08-03 14:44 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +You can abstract away the concurrent thread sharing the mutex and think of it as owned by the current thread.
Is there any value in restricting the number of concurrent threads? If not, just use plural
```suggestion
You can abstract away the concurrent threads sharing the mutex and think of it as owned by the current thread.
```

2023-08-03 14:44 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +If a thread attempts to lock a mutex it has already acquired, it will _deadlock_ because it would need to release it to lock it again.
It is confusing to put into the footnote for the first row the situation describing the third row.

What do you think of
- having two footnotes - for first and third rows, or
- adding it as a standalone sentence in a separate pararaph?

2023-08-03 14:44 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +They need to _lock_ the _mutex_ to gain _safe_ exclusive access to the resource and _unlock_ it after they are done mutating or reading it.
It looks like the "punchline" of this section - "why this is an issue" - is the end of the footnote `(*)`, and then it is followed by a generic statement of why mutexes are useful.
Yet, this paragraph is (more) relevant where you introduce the mutex states.

If you agree that this is an issue, I propose to rearrange the paragraphs:
1. two states of the mutex
2. use of mutexes for protection of resource access
3. mental model of mutex state evolution
4. table of state transitions
5. footnote
6. > If a thread attempts to lock a mutex it has already acquired, it will _deadlock_ because it would need to release it to lock it again.

2023-08-03 14:44 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +  pthread_mutex_lock(&m1); // Noncompliant: m1 is already locked
Other than the rule summary and title (which are identical), this is the first time you use "locked". In the "Why this is an issue" you've used the term "acquired" instead. Should we speak about "acquired" instead of locked here as well?
Or perhaps, use "locked" everywhere, and maybe mention that it is also called "acquired"?

2023-08-03 16:03 UTC, tomasz-kaminski-sonarsource commented on rules/S5486/cfamily/rule.adoc
> +=== External coding guidelines
I think this should be the standards section.

2023-08-04 07:24 UTC, balazs-benics-sonarsource reviewed
Resolved the review comments.

2023-08-04 07:24 UTC, balazs-benics-sonarsource commented on rules/S5486/cfamily/rule.adoc
> +  pthread_mutex_lock(&m1); // Noncompliant: m1 is already locked
Added the sentence "These two states are frequently called _unlocked_ and _locked_ as well." after introducing the term "acquired" to clarify this.
Also now using "acquired" and "released" in the "Noncompliant" comments.

2023-08-04 07:24 UTC, balazs-benics-sonarsource commented on rules/S5486/cfamily/rule.adoc
> +=== External coding guidelines
I followed what is present in S836, where CWE was part of the "External coding guidelines" section.
I've moved my CWE to the "Standards" section, as suggested. Thanks.

Speaking of sibling sections, does the order matter?
For example, I mention "Standards" and then, "Related rules" and then "Documentation".
While in the rspec reference they are mentioned in this order:
> Resources (optional)
>  - Documentation   <---
>  - Articles & blog posts
>  - Conference presentations
>  - Standards   <---
>  - External coding guidelines
>  - Benchmarks
>  - Related rules   <---

2023-08-04 07:24 UTC, balazs-benics-sonarsource commented on rules/S5486/cfamily/rule.adoc
> +They need to _lock_ the _mutex_ to gain _safe_ exclusive access to the resource and _unlock_ it after they are done mutating or reading it.
I agree that the paragraph "To effectively protect..." is at a weird place.

It took me a while to understand that all you want is to move the paragraph "To effectively protect..." in between the "A _mutex_ has two states:..." and "You can abstract away the concurrent threads...".

I've moved the paragraph.

2023-08-04 08:46 UTC, tomasz-kaminski-sonarsource approved these changes
This looks great! The section on the data races, critical section, and mutexes is spot on for me, it explains the concepts in a simple manner.

2023-08-04 09:38 UTC, necto approved these changes
Agree, the rule is really solid now

2023-08-04 09:38 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +"pthread_mutex_t" should not be locked when already locked, or unlocked when already unlocked.
I believe we use double quotes for code only in the title and the messages. In the rule description you can enjoy the proper formatting
```suggestion
`pthread_mutex_t` should not be locked when already locked, or unlocked when already unlocked.
```

2023-08-04 09:38 UTC, necto commented on rules/S5486/cfamily/rule.adoc
> +If a thread attempts to lock a mutex it has already acquired, it will _deadlock_ because it would need to release it to lock it again.
Looks good

2023-08-04 10:26 UTC, merged