Modify rule S5272: Expand and adjust for LaYC
SonarSource/rspec pull request #2752
Opened 2023-08-01 13:21 UTC by pdschbrt

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-02 12:11 UTC, necto requested changes

2023-08-02 12:11 UTC, necto commented on rules/S5272/cfamily/rule.adoc
You gave one way to deal with the problem. To increase the rule value, you can provide other ways to fix it. Here are some ideas:
- copy instead of move
- take a regular (lvalue) reference instead of move-constructing another object (although, be careful not to suggest creating a dangling reference)
- remove the use
- remove the move, and use the same object instead of it's "move-constructed" successor

Also, another example of non-compliant code could use a move constructor, and yet another, could pass `std::move(x)` to a function taking an rvalue reference and use it after the call.

As you can only use diff view on a pair of code snippets, it might be more comprehensible if for different non-compliant  examples, you give different compliant solutions

2023-08-02 12:24 UTC, pdschbrt commented
Thanks for your feedback, @necto 

I'll try to address your points.

I was also thinking of discussing the move-assignement operator, but then thought that the description could become too lengthy. But I'll try to give it a shot. We should be able to make it shorter by putting the `DynamicIntArray` implementation in the _Why is this an issue?_ section and then referring back to it.

2023-08-03 06:30 UTC, pdschbrt commented on rules/S5272/cfamily/rule.adoc
> +Relying on an object that has been moved-from may lead to undefined behavior.
There are a few selected STL types such as `std::unique_ptr` for which the moved-from state is fully specified. I mention that later in the `Exceptions` section.

2023-08-03 07:22 UTC, pdschbrt commented on rules/S5272/cfamily/rule.adoc
> +"Stealing" resources (e.g. memory) from another object is oftentimes much more efficient than making a copy and destroying the original, and can frequently be implemented by reassigning a few pointer
I've added another brief paragraph that comments on the assignment operators. It's also picked up once more in the example.

2023-08-03 07:23 UTC, pdschbrt commented on rules/S5272/cfamily/rule.adoc
> +class DynamicIntArray {
This is now factored out.

2023-08-03 07:24 UTC, pdschbrt commented on rules/S5272/cfamily/rule.adoc
I've tried to address these points in additional code examples.

2023-08-03 07:25 UTC, pdschbrt commented
I've addressed all of your comments. Please give it another shot, @necto.

Thanks!

2023-08-03 11:42 UTC, necto commented on rules/S5272/cfamily/rule.adoc
> +Relying on an object that has been moved-from may lead to undefined behavior.
I see. How about making it a little stronger, like
```suggestion
Relying on an object that has been moved-from leads to undefined behavior in most cases.
```
Because I imagine, even though `std::unique_ptr` moved-from state is well specified, it is not relied upon often

2023-08-03 12:27 UTC, necto requested changes
Note that you don't need to use the heavy \`\`++`` syntax if the simple \`\` works.
Please update the "quickfix" status also

2023-08-03 12:27 UTC, necto commented on rules/S5272/cfamily/rule.adoc
> +  array_user(a);
This fails to compile

2023-08-03 12:27 UTC, necto commented on rules/S5272/cfamily/rule.adoc
> +The ``++DynamicIntArray++`` type defined in the following manages a resource, i.e., memory, and shall serve as an example that showcases how move operations "steal" another objects resources and how
```suggestion
The ``++DynamicIntArray++`` type defined in the following manages a resource, i.e., memory, and shall serve as an example that showcases how move operations "steal" another object's resources and how they differ from making copies.
```

2023-08-03 12:27 UTC, necto commented on rules/S5272/cfamily/rule.adoc
> +  // Constructor
IMO, it is obvious that this is a constructor
```suggestion
```

2023-08-03 12:27 UTC, necto commented on rules/S5272/cfamily/rule.adoc
> +  // Destructor
IMO, it is obvious that this is a destructor
```suggestion
```

2023-08-03 12:27 UTC, necto commented on rules/S5272/cfamily/rule.adoc
> +[source,cpp,diff-id=1,diff-type=compliant]
You cannot reuse same `diff-id` more or less than in 2 code snippets. This is a limitation, so in the alternative fix proposal you have to abstain from using diff view
```suggestion
[source,cpp]
```

2023-08-03 12:27 UTC, necto commented on rules/S5272/cfamily/rule.adoc
> +[source,cpp,diff-id=1,diff-type=compliant]
```suggestion
[source,cpp]
```

2023-08-03 12:27 UTC, necto commented on rules/S5272/cfamily/rule.adoc
> +[source,cpp,diff-id=1,diff-type=compliant]
```suggestion
[source,cpp]
```

2023-08-03 13:24 UTC, pdschbrt commented on rules/S5272/cfamily/rule.adoc
> +The ``++DynamicIntArray++`` type defined in the following manages a resource, i.e., memory, and shall serve as an example that showcases how move operations "steal" another objects resources and how
That is a good idea---sold!

2023-08-03 13:51 UTC, pdschbrt commented
Just addressed the next round of feedback, @necto.

2023-08-03 14:59 UTC, necto commented on rules/S5272/cfamily/rule.adoc
> +* Use the object _before_ moving it
```suggestion
* Use the object _only before_ moving it
```

2023-08-03 14:59 UTC, necto commented on rules/S5272/cfamily/rule.adoc
> +#include <memory>
Wasn't the whole point of hoisting the definition of `DynamicIntArray` into the section above to shorten these examples?
I presume you've inserted it here to make the code compile, but that is not a requirement. I think it is fine if the code compiles when you concatenate the code snippet with the definition of `DynamicIntArray` and a (non)compliant example

2023-08-03 14:59 UTC, necto commented on rules/S5272/cfamily/rule.adoc
> +  array_user(a);
I see that you added a shortened definition of `DynamicIntArray`, but that wasn't the only reason why this fails to compile. The other reason is more important: you can't pass an lvalue to `array_user` that takes an rvalue reference. So you have to fix this example differently. For example, create a temporary copy `array_user(DynamicArray{a})`.

2023-08-04 06:25 UTC, pdschbrt commented on rules/S5272/cfamily/rule.adoc
> +#include <memory>
I've reverted the change(s).

2023-08-04 06:26 UTC, pdschbrt commented
I've just addressed your comments, @necto.

2023-08-04 09:19 UTC, necto approved these changes

2023-08-04 09:40 UTC, merged