Modify rule S3699: LaYC format
SonarSource/rspec pull request #2759
Opened 2023-08-02 12:25 UTC by maksim-grebeniuk-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-02 12:47 UTC, guillaume-dequenne-sonarsource requested changes
Looks good, minor suggestion on the top level description.

2023-08-02 12:47 UTC, guillaume-dequenne-sonarsource commented on rules/S3699/javascript/rule.adoc
> +This rule raises an issue when a function call results are used however the function does not return anything.
Reword suggestion:
This rule raises an issue when a function call result is used, even though the function does not return anything.

2023-08-04 09:50 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM

2023-08-04 10:57 UTC, jean-jimbo-sonarsource approved these changes
LGTM

2023-08-04 10:58 UTC, merged