Modify rule S2092: Add Go language
SonarSource/rspec pull request #2760
Opened 2023-08-02 13:03 UTC by sebastien-andrivet-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-03 13:54 UTC, egon-okerman-sonarsource requested changes
There are still some changes necessary before the PR can be approved. Please go over them and let me know if you disagree with anything I mentioned.

2023-08-03 13:54 UTC, egon-okerman-sonarsource commented on rules/S2092/go/rule.adoc
> +}
This text is already pretty long, it is best to limit the examples here to one per framework.

The goal of the examples here is not to be complete, but to demonstrate to users how this issue should be fixed. For example, the fixes for `handler1` and `handler2` are the same, so there is little value in showing it twice. We expect highlighting and issue messages if the sensitive issue is slightly different from the example.

2023-08-03 13:54 UTC, egon-okerman-sonarsource commented on rules/S2092/go/rule.adoc
> +	ctrl.Ctx.SetSecureCookie("secret", "name3", "value3", 200, "/", "example.com", false, false) // Sensitive
Same here, try to stick to one sensitive line and one fix. We count on our users to be smart enough if the API is the same for their issue.

2023-08-03 13:54 UTC, egon-okerman-sonarsource commented on rules/S2092/go/rule.adoc
> +	http.SetCookie(w, &cookie) // Sensitive, Secure is false by default
```suggestion
	http.SetCookie(w, &cookie) // Sensitive: Secure is false by default
```
Nitpick: for consistency, colon is recommended for RSPEC (see #guild-education on Slack, not in the docs yet unfortunately.)

2023-08-03 14:27 UTC, sebastien-andrivet-sonarsource commented on rules/S2092/go/rule.adoc
> +Beego
I think it should be:

```
For https://pkg.go.dev/github.com/beego/beego[Beego]:
```

since it is AsciiDoc, isn't it?

2023-08-03 14:29 UTC, egon-okerman-sonarsource commented on rules/S2092/go/rule.adoc
> +Beego
You are right, I've altered the suggestion.

2023-08-03 14:29 UTC, sebastien-andrivet-sonarsource commented on rules/S2092/go/rule.adoc
> +	http.SetCookie(w, &cookie) // Sensitive, Secure is false by default
Yes, this is the line to be highlighted since when a cookie is created, it is always with Secure = false.

2023-08-03 14:38 UTC, egon-okerman-sonarsource commented on rules/S2092/go/rule.adoc
> +	http.SetCookie(w, &cookie) // Sensitive, Secure is false by default
Well, in this case, I would say it is inconsistent with the Fiber example, where the constructor is highlighted instead.

2023-08-04 07:35 UTC, egon-okerman-sonarsource requested changes
Some more small changes are necessary, after that should be fine to merge 👍

2023-08-04 07:35 UTC, egon-okerman-sonarsource commented on rules/S2092/go/rule.adoc
>    cookie.Secure = true // Compliant
In RSPEC, we don't include the `// Compliant` comment, so remove them here and in examples below.

2023-08-04 07:35 UTC, egon-okerman-sonarsource commented on rules/S2092/go/rule.adoc
> +  c.SetCookie("name", "value", 200, "/", "example.com", true, false) // Sensitive
```suggestion
  c.SetCookie("name", "value", 200, "/", "example.com", true, false)
```
This can also be removed

2023-08-04 08:50 UTC, egon-okerman-sonarsource approved these changes
LGTM!

2025-01-28 10:16 UTC, merged