Modify rule S3403: LaYC format
SonarSource/rspec pull request #2765
Opened 2023-08-02 14:34 UTC by maksim-grebeniuk-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-02 16:55 UTC, guillaume-dequenne-sonarsource requested changes
Looks good, minor change request.

2023-08-02 16:55 UTC, guillaume-dequenne-sonarsource commented on rules/S3403/python/rule.adoc
> +Operators https://docs.python.org/3/reference/expressions.html#is-not[``++is++``] and https://docs.python.org/3/reference/expressions.html#is-not[``++is not++``] check if their operands point to the
`is` will return False, and `is not` will return True, right?
I think we should reverse the `True` and `False` in the sentence to be consistent.

2023-08-04 06:34 UTC, guillaume-dequenne-sonarsource approved these changes
LGTM.

2023-08-04 10:43 UTC, jean-jimbo-sonarsource commented on rules/S3403/python/rule.adoc
> -Operators https://docs.python.org/3/reference/expressions.html#is-not[``++is++``] and https://docs.python.org/3/reference/expressions.html#is-not[``++is not++``] check if their operands point to the
" Such comparisons can only be bugs." sounds like a filler - it's not actually giving useful information. I'd suggest discarding it as the reasoning has already been given and it is an issue/bug.

2023-08-04 10:43 UTC, jean-jimbo-sonarsource approved these changes
Added a small feedback

2023-08-04 14:46 UTC, merged