Modify rule S1265: LaYC format
SonarSource/rspec pull request #2776
Opened 2023-08-03 10:14 UTC by amelie-renard-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [x] logical errors and incorrect information
- [x] information gaps and missing content
- [x] text style and tone
- [x] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-03 12:03 UTC, marco-antognini-sonarsource requested changes

2023-08-03 12:03 UTC, marco-antognini-sonarsource commented on rules/S1265/cfamily/rule.adoc
Your rewrite is already an improvement.
But the implementation is wrong (CPP-2429) for the same reason the description is lacking precision: there are many possible `operator new` and `operator delete`, and each should have the corresponding one.

To be fair, neither the C++ CG nor CERT articles describe what the corresponding operator is, and this is not trivial. C++ reference is a bit better in that area, but the wording is not easy to follow because the elements are on different pages. See https://en.cppreference.com/w/cpp/language/delete and https://en.cppreference.com/w/cpp/memory/new/operator_delete for example.

There are essentially two things I would improve in the description:
 * Why is it an issue to rely on the default new/delete when one of them is defined? You give a hint (the program will not do it correctly). Being more explicit would dissipate misunderstanding in this complex topic. E.g., if the impl of `new` uses `malloc`, the `free` must be used in `delete`; if `new` draw memory from a preallocated buffer, `delete` should not call `free`, ...
 * Which `delete` overload corresponds to a given `new` overload?

---

I wonder if we should put this on hold until the FPs are fixed (CPP-2429).
WDYT?

2023-08-03 13:27 UTC, amelie-renard-sonarsource commented on rules/S1265/cfamily/rule.adoc
If I understand correctly, the rule does not raise FP but has FN when the new operator and the delete operator it finds do not correspond. Or as soon as one new operator and one delete operator are defined.
I don't think this should prevent the rule from being improved. It would help the user to define the new or delete operator missing correctly.
I'll work on it (it seems so easy... 😅 )

2023-08-03 14:10 UTC, tomasz-kaminski-sonarsource commented
I think it may be worth to link the updated symbolic-execution rule as related to this one: https://sonarsource.github.io/rspec/#/rspec/S1232. Or take same inspiration from it.

2023-08-10 07:56 UTC, marco-antognini-sonarsource approved these changes
Looks good, I have a couple of small points. No need for another round unless you want to.

2023-08-10 07:56 UTC, marco-antognini-sonarsource commented on rules/S1265/cfamily/rule.adoc
> +If the `operator delete` is not overridden alongside the `operator new`, the program will call its default implementation. And this latter may not be suitable for the custom memory allocation strateg
While grammatically correct, I found "this latter" hard to read for some reason.
A simple suggestion, but feel free to dismiss it.
```suggestion
If the `operator delete` is not overridden alongside the `operator new`, the program will call its default implementation and may not be suitable for the custom memory allocation strategy used by the overridden `operator new`.
```

2023-08-10 07:56 UTC, marco-antognini-sonarsource commented on rules/S1265/cfamily/rule.adoc
> +For instance, if the `operator new` draws memory from a preallocated buffer instead of allocating memory, the `operator delete` should not call the `free` function to release the memory. On the contr
I think "on the contrary" does not 100% fit here. What about "reciprocally"?

```suggestion
For instance, if the `operator new` draws memory from a preallocated buffer instead of allocating memory, the `operator delete` should not call the `free` function to release the memory. Reciprocally, if the `operator new` allocate memory with `malloc`, the `operator delete` must call `free`.
```

2023-08-10 07:56 UTC, marco-antognini-sonarsource commented on rules/S1265/cfamily/rule.adoc
> +Deallocating memory that was not allocated results in undefined behavior.
The first sentence is "positive" (this should be done), while the second is "negative" (don't do that). This makes it slightly hard to follow.

Given we are talking about the defect, I wonder if we should prefer the negative style.

Also, small nit in the second sentence: in a way, all memory is allocated in some way (heap, stack, buffer, ...). What matters is the two new/delete match.

I tried to make a suggestion to address these points.

```suggestion
Overriding only one of the two operators may result in your program consuming more and more memory over time, eventually leading to a crash. 

Deallocating memory that was not allocated with the corresponding strategy results in undefined behavior.
```

2023-08-10 07:56 UTC, marco-antognini-sonarsource commented on rules/S1265/cfamily/rule.adoc
> +    return 0;
Function is void.

```suggestion
```

2023-08-10 07:56 UTC, marco-antognini-sonarsource commented on rules/S1265/cfamily/rule.adoc
> +    return 0;
```suggestion
```

2023-08-10 07:56 UTC, marco-antognini-sonarsource commented on rules/S1265/cfamily/rule.adoc
> +        return p;
The operators new below are not standard compliant because they should throw on failure.

This should fix the issue:
```suggestion
        if (!p) {
            throw std::bad_alloc();
        }
        return p;
```

2023-08-10 07:56 UTC, marco-antognini-sonarsource commented on rules/S1265/cfamily/rule.adoc
Thanks, looks much better already! Let's leave the second point to CPP-2429.

2023-08-10 08:09 UTC, amelie-renard-sonarsource commented on rules/S1265/cfamily/rule.adoc
> +Deallocating memory that was not allocated results in undefined behavior.
Good point, thanks!

2023-08-10 08:11 UTC, amelie-renard-sonarsource commented on rules/S1265/cfamily/rule.adoc
> +If the `operator delete` is not overridden alongside the `operator new`, the program will call its default implementation. And this latter may not be suitable for the custom memory allocation strateg
```suggestion
If the `operator delete` is not overridden alongside the `operator new`, the program will call its default implementation, which may not be suitable for the custom memory allocation strategy used by the overridden `operator new`.
```

2023-08-10 08:17 UTC, merged