Modify rule S5485: Expand and adjust for LaYC
SonarSource/rspec pull request #2779
Opened 2023-08-03 11:49 UTC by pdschbrt

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-03 11:52 UTC, tomasz-kaminski-sonarsource commented
I think that the current rule title "Appropriate arguments should be passed to stream functions" (in metadata file), does not meet LaYC standards.

2023-08-03 13:31 UTC, tomasz-kaminski-sonarsource requested changes

2023-08-03 13:31 UTC, tomasz-kaminski-sonarsource commented on rules/S5485/cfamily/rule.adoc
> +These functions require appropriate parameters.
I think that it would be nicer, to formulate it, as this functions put restrictions on the values of the parameters, and have bulled list of the restrictions.
If they are not all, for example `ftell` with not opened file is probably also bad, I would say including, but not limited to.

2023-08-03 13:31 UTC, tomasz-kaminski-sonarsource commented on rules/S5485/cfamily/rule.adoc
> +Besides the aforementioned availability issues of the application, any attempts to dereference a ``++NULL++`` pointer made by the C library functions can, in rare circumstances, also results in secur
I would sync this null pointer dereference with the other rule, for consistency.

2023-08-04 06:18 UTC, pdschbrt commented
Hey @tomasz-kaminski-sonarsource, I've addressed your comments and harmonized this rule with the very similar rule that we worked on. Let me know what you think.

2023-08-04 06:54 UTC, tomasz-kaminski-sonarsource requested changes
Looks good. Just few small suggestions.

2023-08-04 06:54 UTC, tomasz-kaminski-sonarsource commented on rules/S5485/cfamily/metadata.json
> +  "title": "Sufficiently restricted arguments should be passed to stream functions",
I think I like appropariate here more, after rereading. I know this was my suggestion, but this sound akward.

2023-08-04 06:54 UTC, tomasz-kaminski-sonarsource commented on rules/S5485/cfamily/rule.adoc
> +Passing insufficiently restricted arguments to standard C library functions for handling I/O streams results in undefined behavior.
Same here.

2023-08-04 06:54 UTC, tomasz-kaminski-sonarsource commented on rules/S5485/cfamily/rule.adoc
> +These functions put certain restrictions on the values of their parameters, which are listed in the following:
I think there are more restriction placed. I believe FILE must be actually correct file handle. So I would say something that this is subset of restrictions.

2023-08-04 06:54 UTC, tomasz-kaminski-sonarsource commented on rules/S5485/cfamily/rule.adoc
> +  FILE *f = fopen("example_file.txt", "r");
I would just add comment here, saying:
```
// may be null if fopen operation failed
```
Then I would just remove the description of code from above.

2023-08-04 06:59 UTC, tomasz-kaminski-sonarsource commented on rules/S5485/cfamily/metadata.json
> +  "title": "Sufficiently restricted arguments should be passed to stream functions",
Could you try to consult with best practies team on this tree "Appropariate" rule titles? They feel as not matching guidelines for me, but I think that very subjective.
If you change this one, I would suggest adjusting previous rule in this PR>

2023-08-04 07:00 UTC, pdschbrt commented on rules/S5485/cfamily/rule.adoc
> +These functions put certain restrictions on the values of their parameters, which are listed in the following:
True. Let me try to rephrase this slightly.

2023-08-04 07:02 UTC, tomasz-kaminski-sonarsource commented on rules/S5485/cfamily/metadata.json
> +  "title": "Sufficiently restricted arguments should be passed to stream functions",
There is style guide on titles here: https://docs.sonarsource.com/sonarqube/latest/extension-guide/adding-coding-rules/#coding-rule-guidelines

2023-08-04 07:05 UTC, pdschbrt commented
How about this?

2023-08-04 07:08 UTC, pdschbrt commented on rules/S5485/cfamily/metadata.json
> +  "title": "Sufficiently restricted arguments should be passed to stream functions",
Sure. We, in fact, have a whole bunch of rules that are concerned with `appropriate` parameters. I'll double-check with best practices 👍🏻

2023-08-04 11:49 UTC, tomasz-kaminski-sonarsource commented on rules/S5485/cfamily/rule.adoc
> +These functions put certain restrictions on the values of their parameters, which are listed in the following:
Looks good.

2023-08-04 11:50 UTC, tomasz-kaminski-sonarsource commented on rules/S5485/cfamily/metadata.json
> +  "title": "Sufficiently restricted arguments should be passed to stream functions",
I like the only valid approach. Much better that appropariate.

2023-08-04 11:53 UTC, tomasz-kaminski-sonarsource approved these changes
Looks good to me now.

2023-08-04 11:54 UTC, pdschbrt commented
Excellent. Thanks for your thorough review.

2023-08-04 11:54 UTC, merged