SONARJAVA-4495 Update S2175 in line with LayC.
SonarSource/rspec pull request #2813
Opened 2023-08-07 13:26 UTC by johann-beleites-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-07 14:28 UTC, leonardo-pilastri-sonarsource requested changes
Just some line breaks adjustment to facilitate visualizing future changes, and more compact code examples, everything else looks good!

2023-08-07 14:28 UTC, leonardo-pilastri-sonarsource commented on rules/S2175/java/rule.adoc
> +of type `java.lang.Object` and will compare said argument with objects already in the collection.
```suggestion
The `java.util.Collection` type and its subtypes provide methods to access and modify collections such as `Collection.remove(Object o)` and `Collection.contains(Object o)`.
Some of these methods accept arguments of type `java.lang.Object` and will compare said argument with objects already in the collection.
```

2023-08-07 14:28 UTC, leonardo-pilastri-sonarsource commented on rules/S2175/java/rule.adoc
> +can be indicative of a design issue.
```suggestion
If the actual type of the argument is unrelated to the type of object contained in the collection, these methods will always return `false`, `null`, or `-1`.
This behavior is most likely unintended and can be indicative of a design issue.
```

2023-08-07 14:28 UTC, leonardo-pilastri-sonarsource commented on rules/S2175/java/rule.adoc
> +unrelated to the type used for the collection declaration:
```suggestion
This rule raises an issue when the type of the argument provided to one of the following methods is unrelated to the type used for the collection declaration:
```

2023-08-07 14:28 UTC, leonardo-pilastri-sonarsource commented on rules/S2175/java/rule.adoc
> +argument of which the type is compatible with the list content's type.
```suggestion
Ask yourself what the purpose of this method call is.
Check whether the provided argument and collection are correct in this context and for the desired purpose.
Remove unnecessary calls and otherwise provide an argument of which type is compatible with the list content's type.
```

2023-08-07 14:28 UTC, leonardo-pilastri-sonarsource commented on rules/S2175/java/rule.adoc
> +----
It was mentioned in the document produced by the .NET squad that multiple code blocks might have issues rendering, and if possible we should prefer squashing code example into one `noncompliant` block and one `compliant` block. Something like:

```
[source,java,diff-id=1,diff-type=noncompliant]
----
void removeFromMap(Map<Integer, Object> map, String strKey) {
  map.remove(strKey); // Noncompliant, this call will remove nothing and always return 'null' because 'map' is handling only Integer keys and String cannot be cast to Integer.
}

void ifContains(List<String> list, Integer integer) {
  if (list.contains(integer)) { // Noncompliant; always false as the list only contains Strings, not integers.
    // ...
  }
}
----

==== Compliant solution
[source,java,diff-id=1,diff-type=compliant]
----
void removeFromMap(Map<Integer, Object> map, String strKey) {
  map.remove(Integer.parseInt(strKey)); // Compliant, strKey is parsed into an Integer before trying to remove it from the map.
}

void ifContains(List<String> list, Integer integer) {
  if (list.contains(integer.toString())) { // Compliant, 'integer' is converted to a String before checking if the list contains it.
    // ...
  }
}
----
```

2023-08-08 11:57 UTC, johann-beleites-sonarsource commented on rules/S2175/java/rule.adoc
> +----
Oh really? Didn't know that, thanks. Sounds like a bug that should be fixed on product side as well.

2023-08-08 13:42 UTC, leonardo-pilastri-sonarsource approved these changes
Looks good!

2023-08-08 15:31 UTC, merged

2023-08-08 15:37 UTC, necto commented
@johann-beleites-sonarsource, for the future PRs, please make sure 
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

@leonardo-pilastri-sonarsource, I'll appreciate if you can also watch out for the violation of the guidelines in the PRs you review