Modify rule S2272: reworked rule description for LaYC format
SonarSource/rspec pull request #2872
Opened 2023-08-14 12:46 UTC by kaufco

2023-08-14 14:26 UTC, irina-batinic-sonarsource requested changes

2023-08-14 14:26 UTC, irina-batinic-sonarsource commented on rules/S2272/java/rule.adoc
Usually, if we add a `How to fix it` section, we add some text here.
IMO, for this particular case, we can skip it.

2023-08-14 14:26 UTC, irina-batinic-sonarsource commented on rules/S2272/java/rule.adoc
>  ----
If I remember correctly, the code in noncompliant and compliant sections should compile.
Let's remove `...`

2023-08-14 14:26 UTC, irina-batinic-sonarsource commented on rules/S2272/java/rule.adoc
>  [source,java,diff-id=1,diff-type=compliant]
Same here. Let's remove `...`

2023-08-14 14:26 UTC, irina-batinic-sonarsource commented on rules/S2272/java/rule.adoc
> +* https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html#next--[Java SE 8 API Specification: Iterator]
Let's reference the latest Java version: https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/Iterator.html#next()

2023-08-15 11:16 UTC, kaufco commented on rules/S2272/java/rule.adoc
>  ----
Fixed.

2023-08-15 11:16 UTC, kaufco commented on rules/S2272/java/rule.adoc
Fixed.

2023-08-15 11:16 UTC, kaufco commented on rules/S2272/java/rule.adoc
>  [source,java,diff-id=1,diff-type=compliant]
Fixed.

2023-08-15 11:16 UTC, kaufco commented on rules/S2272/java/rule.adoc
> +* https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html#next--[Java SE 8 API Specification: Iterator]
Resolved (not fixed).

2023-08-15 12:12 UTC, irina-batinic-sonarsource commented on rules/S2272/java/rule.adoc
> +* https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html#next--[Java SE 8 API Specification: Iterator]
I can't entirely agree it is resolved.
As was explained in [this slack thread](https://sonarsource.slack.com/archives/C04P0SB2KJP/p1692031949269499?thread_ts=1692028946.548869&cid=C04P0SB2KJP) let's go with the lowest supported version.

2023-08-15 15:18 UTC, irina-batinic-sonarsource approved these changes

2023-08-15 15:20 UTC, merged