Modify rule S5488: Expand and adjust for LaYC
SonarSource/rspec pull request #2914
Opened 2023-08-21 11:34 UTC by pdschbrt

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-21 13:17 UTC, tomasz-kaminski-sonarsource requested changes
Looks good.

2023-08-21 13:17 UTC, tomasz-kaminski-sonarsource commented on rules/S5488/cfamily/rule.adoc
> +The behavior for some of those UNIX/POSIX functions is unspecified, i.e., implementation-defined, if one passes incorrectly constrained parameters.
Unspecified is not the same as implementation defined. Unspecified means that each execution could produce different results, even with the same arguments, while implementation defined need to be document. Maybe say `is not defined` instead of referring to world, that is world of power.

2023-08-22 06:52 UTC, pdschbrt commented on rules/S5488/cfamily/rule.adoc
> +The behavior for some of those UNIX/POSIX functions is unspecified, i.e., implementation-defined, if one passes incorrectly constrained parameters.
I rephrased it a bit to avoid the term `unspecified`.

2023-08-22 07:12 UTC, tomasz-kaminski-sonarsource requested changes
Looks really good. Please prepare PR for the sonar-cpp.

2023-08-22 08:04 UTC, merged