Modify rule S5308: Expand and adjust for LaYC
SonarSource/rspec pull request #2916
Opened 2023-08-21 14:35 UTC by pdschbrt

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-21 15:01 UTC, tomasz-kaminski-sonarsource requested changes
This looks really nice. I have added some suggestion how to rewrite the example from how to use correctly, to one that illustrates potential impact.

2023-08-21 15:01 UTC, tomasz-kaminski-sonarsource commented on rules/S5308/cfamily/rule.adoc
> +A brief example on how ``++setuid++`` can be used and how to correctly check its return value is given in what follows:
This seems to be useful, but it does not match why this is an issue. The code as far I understand, contains no issue. I think that is really nice example, and maybe we could rework it to show, how you create or remove file with root privileges if set_uid failed. I would put that in separate section, after what is potential impact.

2023-08-22 07:03 UTC, pdschbrt commented on rules/S5308/cfamily/rule.adoc
> +A brief example on how ``++setuid++`` can be used and how to correctly check its return value is given in what follows:
I agree that we should put the example into a separate section; currently, it's not in the right place.

The code deliberately does not contain an issue. Since this is really security-critical stuff, I didn't want to show the user a broken example. There are enough bad examples on StackOverflow and on the internet in general.

I'll put it in a separate section and try to modify it slightly to showcase what could go wrong without correct error handling, however, I'll try to refrain from making it like really bad.

2023-08-22 07:39 UTC, pdschbrt commented on rules/S5308/cfamily/rule.adoc
> +A brief example on how ``++setuid++`` can be used and how to correctly check its return value is given in what follows:
It's now updated. Please check the most recent version.

2023-08-22 08:38 UTC, tomasz-kaminski-sonarsource approved these changes
Good read. Made me late to the standup.

2023-08-22 08:51 UTC, pdschbrt commented
Excellent. Thanks!

2023-08-22 08:54 UTC, merged