Modify rule S3588: Expand and adjust for LaYC
SonarSource/rspec pull request #2933
Opened 2023-08-23 07:08 UTC by pdschbrt

Removed code example which contains a FN. A corresponding Jira ticket has been created at https://sonarsource.atlassian.net/browse/CPP-4655

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-23 07:29 UTC, tomasz-kaminski-sonarsource requested changes
Could you rebase this on master, so I would see actual diff?

2023-08-23 07:33 UTC, tomasz-kaminski-sonarsource requested changes
I think we should mention RAII in going extra mile in this section when representing file as object in C++ would remove the closing and avoid double closing. similarly what we have to use after free or double free.

2023-08-23 08:46 UTC, pdschbrt commented
Please give it another read.

2023-08-23 09:46 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +Using {cpp}'s _RAII_ idiom can mitigate these "double-close" issues.
I think I would add example of such class here. It should be that hard. We have some shared entry for RAII idiom, and maybe you could include it here.

2023-08-23 11:58 UTC, pdschbrt commented on rules/S3588/cfamily/rule.adoc
> +Using {cpp}'s _RAII_ idiom can mitigate these "double-close" issues.
I've sketched an exemplary class that manages a variable of type `FILE *`.

I've also seen the shared description for RAII but felt that it does not quite match the situation and hence chose not to include it. Instead, I've added a few lines on RAII that match this rule's context.

2023-08-23 12:29 UTC, tomasz-kaminski-sonarsource requested changes
Looks a lot as the think I was looking for. Just few comments.

2023-08-23 13:26 UTC, pdschbrt commented
The problem with returning the pointer using `handle()` is that some madman could then pass that pointer to `fclose`, again. I wish to eliminate misuse with such a wrapper class.

I've cleaned-up the code a bit, which should do the trick.

2023-08-23 13:26 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +  size_t fread(void *ptr, size_t size, size_t nmemb); // Forward to C's `fread`.
I would add `handle()` method to extract `FILE*`, so it show that you do not need to wrap every API to gets the benefits.

2023-08-23 13:28 UTC, pdschbrt commented on rules/S3588/cfamily/rule.adoc
> +  size_t fread(void *ptr, size_t size, size_t nmemb); // Forward to C's `fread`.
I've got a concern with that. See my comment above.

2023-08-23 15:06 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +  size_t fread(void *ptr, size_t size, size_t nmemb); // Forward to C's `fread`.
Yes, but it is same for `unique_ptr`, you can call explicit delete. You are protecting against `Machieveli`, and making user believe that you need wrap everything. I would add a comment, that they could also wrap each call.

2023-08-24 06:32 UTC, pdschbrt commented on rules/S3588/cfamily/rule.adoc
> +  size_t fread(void *ptr, size_t size, size_t nmemb); // Forward to C's `fread`.
Fair enough. I've updated the class accordingly. It should be less distracting now.

2023-08-24 06:38 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +  size_t fread(void *ptr, size_t size, size_t nmemb); // Forward to C's `fread`.
I would still add a comment at the end mention that providing a functions that wrap underlying call may be better. But this is sufficient to address double free. Or something, like:
> With the above design it is still possible double close file handle, by calling passing `f.handle()` to function that closes stream (for example `close(f.handle())`. But this design reduces the risk of such occurrence, but eliminating risk of manual closing.

Maybe we should also add `release()` function, that will return handle, but disamr file by setting internal one to nullptr.

2023-08-24 06:44 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +      exit(1);
We should throw something here. Or just make file empty.

2023-08-24 06:45 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +  size_t fread(void *ptr, size_t size, size_t nmemb); // Forward to C's `fread`.
OK. I would skip release, but rename this class to `ScopedFile` or would add move constructor and operator bool.

2023-08-24 07:51 UTC, pdschbrt commented
Slowly getting there. Let me know what you think.

2023-08-24 07:55 UTC, tomasz-kaminski-sonarsource requested changes

2023-08-24 07:55 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +    f = fopen(path.c_str(), modes.c_str());
Use ctor initializer.

2023-08-24 07:55 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +    if (!f) {
Just call close inside, and add a comment regarding termination,.

2023-08-24 07:55 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +    int status = fclose(std::exchange(f, nullptr));
You should not close nullptr. So this need a check if f is not null.

2023-08-24 07:55 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +    // Close the currently managed file and "steal" the other's file.
I would put that inside if and reverse condition.

2023-08-24 07:55 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +  File(File &&other) { f = std::exchange(other.f, nullptr); }
Again, use ctor initializer.

2023-08-24 07:57 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +    if (status == EOF) {
Why not use if with intialier, of just inline call of close into condition:
```
if (close(f) == EOF) {
  throw....;
}
```

2023-08-24 08:09 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +      perror("fclose() failed");
I would throw here, and let destructor terminate or hitting noexcept.

2023-08-24 08:09 UTC, tomasz-kaminski-sonarsource commented on rules/S3588/cfamily/rule.adoc
> +      perror("fclose() failed");
Just comment, that destructor will terminate in case of exceptions.

2023-08-24 08:36 UTC, pdschbrt commented on rules/S3588/cfamily/rule.adoc
> +      perror("fclose() failed");
Done.

2023-08-24 08:46 UTC, tomasz-kaminski-sonarsource approved these changes

2023-08-24 08:47 UTC, merged