Modify rule S2259: Expand and adjust for LaYC
SonarSource/rspec pull request #2939
Opened 2023-08-23 12:40 UTC by tomasz-kaminski-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-23 14:45 UTC, pdschbrt requested changes
Looks good. I only pointed out some minor places that could be rephrased.

I'll give it another read, once you've addressed my comments 👍🏻

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +Such a pointer does not point to an object or valid memory, and as a consequence dereferencing or accessing the memory pointed by such a pointer has undefined behavior.
```suggestion
A null pointer does neither point to an object nor to valid memory, and as a consequence dereferencing or accessing the memory pointed by such a pointer is undefined behavior.
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +  return *ptr; // Noncompliant, deference of null pointer
```suggestion
  return *ptr; // Noncompliant, deference of null pointer
```
```suggestion
  return *ptr; // Noncompliant: deference of a null pointer
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +In addition to using an `*` operator, accessing a member of the structure (using `->`) or element of an array (using `[]`) leads to dereference of the pointer,
```suggestion
In addition to using the `*` operator, accessing a member of a structure (using `->`) or an element of an array (using `[]`) also leads to dereference of the pointer,
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +  return ptr[2]; // Noncompliant, subscript of null pointer
```suggestion
  return ptr[2]; // Noncompliant: subscript operator used on null pointer
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +Finally, invoking a function pointer that points to null, dereferences the pointer and results in undefined behavior.
```suggestion
Finally, invoking a function pointer that holds a null value, dereferences the pointer and too results in undefined behavior.
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +  void (*func)(int) = NULL; // func is pointer to function
```suggestion
  void (*func)(int) = NULL; // func is a pointer to a function
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +  func(10); // Noncompliant, invocation of null function pointer
```suggestion
  func(10); // Noncompliant, invocation of null function pointer 
```
```suggestion
  func(10); // Noncompliant: invocation of a null function pointer 
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +The behavior of a program that deferences a null pointer results in undefined behavior,
```suggestion
The behavior of a program that deferences a null pointer results in undefined behavior.
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +In such case the compiler no longer needs to adhere to the language standard,
```suggestion
In that case, the compiler no longer needs to adhere to the language standard
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +In practice dereference of null pointer may lead to program crashes, or the application may appear to execute correctly while losing data or producing incorrect results.
```suggestion
In practice, dereferencing a null pointer may lead to program crashes, or the application may appear to execute correctly while losing data or producing incorrect results.
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +if (p1 == NULL && *p1 == '\t') { // Noncompliant, p1 will be dereferenced IFF it is null
```suggestion
if (p1 == NULL && *p1 == '\t') { // Noncompliant: p1 will be dereferenced IFF it is null
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
>  if (p1 != NULL && *p1 == '\t') { // Compliant, *p1 cannot be evaluated when p1 is NULL
```suggestion
if (p1 != NULL && *p1 == '\t') { // Compliant: *p1 cannot be evaluated if p1 is NULL
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +p2[2] = '\t'; // Noncompliant; potential null-dereference
```suggestion
p2[2] = '\t'; // Noncompliant; potential null-dereference
```
```suggestion
p2[2] = '\t'; // Noncompliant: potential null-dereference
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +  p2[2] = '\t'; // Compliant
```suggestion
  p2[2] = '\t'; // Compliant: p2 is known to be non-null
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +In {cpp}, it is preferred to use reference parameter (`Type const&` or `Type&`), or passing object by value (`Type`),
```suggestion
In {cpp}, it is preferred to use reference parameters (`Type const&` or `Type&`), or pass objects by value (`Type`),
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +instead of a pointer (`Type const*` or `Type*`), when the argument is expected to never be null.
```suggestion
instead of a pointer (`Type const*` or `Type*`), if the argument is expected to never be null.
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +* S3807 detects calling a C library function that requires valid pointer, with a null pointer an argument
```suggestion
* S3807 detects calls to C library functions that require valid, non-null pointers with null pointer arguments
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +* S2637 detects passing of null pointer as an argument for a parameter that is annotated with `nonnull`
```suggestion
* S2637 detects uses of null pointers as arguments for parameters that are annotated with `nonnull`
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S3807/cfamily/rule.adoc
> +* S2259 detects dereferences of null pointer
```suggestion
* S2259 detects dereferences of null pointer
```
```suggestion
* S2259 detects dereferences of null pointers
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S3807/cfamily/rule.adoc
> +* S2637 detects passing of null pointer as argument for parameter that is annotated with `nonnull`
```suggestion
* S2637 detects uses of null pointers as arguments for parameters that are annotated with `nonnull`
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +Dereferencing a null pointer results in the undefined behavior.
```suggestion
Dereferencing a null pointer results in undefined behavior.
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +A pointer to null, known also as a null pointer, is created by initializing a pointer object to `0`, `NULL`, or in the case of C++ `nullptr`.
```suggestion
A pointer to null, also known as a null pointer, is created by initializing a pointer object to `0`, `NULL`, or in case of C++ `nullptr`.
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +  return ptr->x; // Noncompliant, member access on a null pointer
```suggestion
  return ptr->x; // Noncompliant, member access on a null pointer
```
```suggestion
  return ptr->x; // Noncompliant: member access on a null pointer
```

2023-08-23 14:45 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +== Hot to fix it
```suggestion
== How to fix it
```

2023-08-24 06:26 UTC, tomasz-kaminski-sonarsource commented
I think I have addressed every comment.

2023-08-24 06:38 UTC, pdschbrt requested changes
Two minor things, then we're good.

2023-08-24 06:38 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +and cause undefined behavior if performed on a pointer to null.
```suggestion
and causes undefined behavior if performed on a pointer to null.
```

2023-08-24 06:38 UTC, pdschbrt commented on rules/S2259/cfamily/rule.adoc
> +The behavior of a program that deferences a null pointer results in undefined behavior,
How about just starting this paragraph with `The behavior of a program that dereferences a null pointer is undefined.`?
This also flows very well with what follows.

2023-08-24 07:07 UTC, pdschbrt approved these changes
Looks good. That's a nice overview of null pointer dereferences.

2023-08-24 07:32 UTC, merged