Modify rule S6317: Update to LayC format (APPSEC-968)
SonarSource/rspec pull request #2949
Opened 2023-08-23 14:44 UTC by egon-okerman-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-25 15:03 UTC, sebastien-andrivet-sonarsource requested changes

2023-08-25 15:03 UTC, sebastien-andrivet-sonarsource commented on rules/S6317/common/fix/least-privilege.adoc
> +When creating IAM policies, it is important to adhere to the principle of least privilege. This means that any user or role should only be granted enough permissions to perform the tasks that they ar
It is a detail, but I am not sure when we put an empty line after the subsection, and when we do not. This does not look consistent but maybe it has no impact on what the users see.

2023-08-25 15:03 UTC, sebastien-andrivet-sonarsource commented on rules/S6317/terraform/how-to-fix-it/aws-iam.adoc
> +[source,terraform]
The diff attributes are missing

2023-08-25 15:09 UTC, egon-okerman-sonarsource commented on rules/S6317/metadata.json
>      "impacts": {
I don't think Conventional is the best attribute here, but then again I do not know which one would fit better.

@hendrik-buchwald-sonarsource do you have any thoughts on this?

2023-08-25 15:48 UTC, hendrik-buchwald-sonarsource commented on rules/S6317/metadata.json
>      "impacts": {
Based on the [decision tree](https://xtranet-sonarsource.atlassian.net/wiki/spaces/PM/pages/2869067851/LaYC+Classifying+Rules), I think it is conventional. It is not a perfect fit but I don't think we should overthink it for now.

2023-08-30 08:50 UTC, sebastien-andrivet-sonarsource approved these changes
LGTM, but should probably be rebased on master because of a dead link.

2023-08-30 09:56 UTC, merged