Modify rule S2095: Expand and adjust for LaYC
SonarSource/rspec pull request #2964
Opened 2023-08-24 13:21 UTC by pdschbrt

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-24 14:26 UTC, tomasz-kaminski-sonarsource commented on rules/S2095/cfamily/rule.adoc
You should extrac you example of the `File` RAII, wrapping it will match `fopen` to `fclose`.

2023-08-24 14:30 UTC, tomasz-kaminski-sonarsource commented on rules/S2095/cfamily/rule.adoc
This also bundles operation together (construction and destruction) so make sure that `close` is matched with `fclose`. See rule about `malloc`/`delete` mismatch.

2023-08-25 07:08 UTC, tomasz-kaminski-sonarsource requested changes

2023-08-25 07:08 UTC, tomasz-kaminski-sonarsource commented on rules/S2095/cfamily/rule.adoc
> +This could lock up not just the program in question, but potentially everything that runs on the machine.
I think this is just shortland for the whole next section so I would remove this sentence:
```suggestion
```

2023-08-25 07:08 UTC, tomasz-kaminski-sonarsource commented on rules/S2095/cfamily/rule.adoc
> +=== Going the extra mile
This section goes after examples

2023-08-25 07:08 UTC, tomasz-kaminski-sonarsource commented on rules/S2095/cfamily/rule.adoc
> +* Java SE Tutorial - https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html[Try With Resources]
What this link does here?

2023-08-25 07:11 UTC, pdschbrt commented on rules/S2095/cfamily/rule.adoc
> +* Java SE Tutorial - https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html[Try With Resources]
Will be removed, yes.

2023-08-25 07:28 UTC, pdschbrt commented on rules/S2095/cfamily/rule.adoc
> +=== Going the extra mile
`Going the extra mile` is a subsection of  `How to fix it` according to the LaYC format description. This should be fine.

2023-08-25 07:28 UTC, pdschbrt commented on rules/S2095/cfamily/rule.adoc
> +=== Going the extra mile
Sorry, I now understand your point. Will move it ;-)

2023-08-25 08:04 UTC, tomasz-kaminski-sonarsource commented on rules/S2095/cfamily/rule.adoc
> +With the design shown above, it is no longer possible to have an unmatched call to ``++fopen++``.
It is possible if you call release. So I will say something, that this design will bey default close file that where opened, and closing it requires extra effort.

2023-08-25 09:01 UTC, pdschbrt commented on rules/S2095/cfamily/rule.adoc
> +With the design shown above, it is no longer possible to have an unmatched call to ``++fopen++``.
I've updated this now. It now matches the type of description we have for `S3588` 👍🏻

2023-08-25 09:34 UTC, tomasz-kaminski-sonarsource approved these changes

2023-08-25 09:40 UTC, merged