Modify rule S5876: Update to LayC format (APPSEC-969)
SonarSource/rspec pull request #2967
Opened 2023-08-24 15:05 UTC by sebastien-andrivet-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-25 14:09 UTC, egon-okerman-sonarsource requested changes
The text is good overall, but I think some adjustments could make it even better. A lot of it is subjective though, so feel free to discuss it in the comments I made.

2023-08-25 14:09 UTC, egon-okerman-sonarsource commented on rules/S5876/common/fix/new-session.adoc
> +3. To protect against session fixation attacks, session fixation protection mechanisms come into play during the authentication process. When a user successfully authenticates, the session fixation p
```suggestion
3. To protect against session fixation attacks, session fixation protection mechanisms come into play during the authentication process. When a user successfully authenticates, this mechanism generates a new session identifier for the user's session.
```
A bit less repetition

2023-08-25 15:17 UTC, sebastien-andrivet-sonarsource commented on rules/S5876/java/rule.adoc
> +https://docs.spring.io/spring-security/reference/5.6-SNAPSHOT/servlet/authentication/session-management.html#ns-session-fixation[Session Fixation Attack Protection]
I have replaced this version-specific link with the non-version-specific one (i.e. latest version).

2023-08-29 15:57 UTC, egon-okerman-sonarsource approved these changes
LGTM 👍

2023-08-30 07:09 UTC, merged