Modify rule S3590: LaYC format
SonarSource/rspec pull request #2968
Opened 2023-08-25 05:52 UTC by LoghinVladDev

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-08-25 08:53 UTC, pdschbrt requested changes
Found a few minor things, but nothing major.

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +* Program executable code - function pointers.
```suggestion
* Executable program code - function pointers.
```

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +
We also need the `What is the potential impact` section in between.

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +This rule raises an issue when trying to release pointers to non-heap memory, such as:
Please try to rephrase this a bit. I wouldn't explicitly mention that the "rule raises" since the rule has already been raised if a developer reads this. (The following list is really nice, it's just about the phrasing.)

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +Remove any calls to `free` or `delete` that release non-heap memory.
```suggestion
Remove any calls to `free` or `delete` that aim at releasing non-heap memory.
```

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +As a best practice, do not use the same pointer variable to point to heap memory and any other type of memory at different points in the program.
Please provide a more elaborate description of what you mean here and also give a code example, and then put it in the `Going the extra mile` subsection that follows the `Code examples` subsection.

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +  delete &number; // Noncompliant, memory allocated on the stack.
```suggestion
  delete &number; // Noncompliant: memory is stack-allocated.
```

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +  free(name); // Noncompliant, memory allocated on the stack.
```suggestion
  free(name); // Noncompliant: memory is stack-allocated.
```

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +  // ...
At a comment at the end of this function like `Compliant: stack memory is automatically released once the variables go out of scope` or something along those lines.

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +int get10() {
```suggestion
int getValue() {
```

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +  free((void*) &get10); // Noncompliant, memory part of program executable code.
```suggestion
  free((void*) &getValue); // Noncompliant: memory is part of executable code.
```

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +int get10() {
Adjust accordingly and also at some sort of `Compliant:` comment.

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +  free(&x); // Noncompliant, memory part of program data.
```suggestion
  free(&x); // Noncompliant: memory part of the program's data.
```

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +  free(&S::data); // Noncompliant, memory part of program data.
```suggestion
  free(&S::data); // Noncompliant: memory part of the program's data.
```

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +void fun() {
Add a `Compliant:` comment and state that global data does not need to be manually freed.

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +  free((void*)&limit); // Noncompliant, memory part of read-only program data.
```suggestion
  free((void*)&limit); // Noncompliant: memory part of program's read-only data.
```

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +  free(name); // Noncompliant, memory part of read-only program data.
```suggestion
  free(name); // Noncompliant: memory part of read-only program data.
```

2023-08-25 08:53 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +  free(name); // Noncompliant, memory part of read-only program data.
`Name` is a stack variable here.

2023-08-25 09:01 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +As a best practice, do not use the same pointer variable to point to heap memory and any other type of memory at different points in the program.
I was thinking this is a bit of a stretch, but I have seen this happen, I'm sure it makes sense to us but I will add an example to be thorough

2023-08-25 09:03 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +  free(name); // Noncompliant, memory part of read-only program data.
while it is a stack variable, the string data is supposed to be located in `.rodata` in most implementations, I believe.
I will check on godbolt

2023-08-25 09:09 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +
Was oscillating with this one:
* While yes, I believe that UB impact >> crash impact, I did not find any documented case of UB that does not act as a crash in the case of non-owned memory free, so most of the times the user will encounter a crash.
* While not stated in the rule, at least a sentence in the "...potential impact" specifying crashes is a good thing to add.

TL;DR will add a short section -> almost all UB in this case is a crash.

2023-08-25 09:11 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +  free(name); // Noncompliant, memory part of read-only program data.
You're right, of course. The actual string is likely part of the program's `.rodata`.

2023-08-25 09:27 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +As a best practice, do not use the same pointer variable to point to heap memory and any other type of memory at different points in the program.
Edit: I cannot decide whether this is a 'pitfall' or a 'going the extra mile'. Will add it to 'going...' for now, tell me after the re-review if it fits better in 'pitfalls'

2023-08-25 09:59 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +  // ...
I would use something a bit more generic, since the example also contains `alloca`

2023-08-25 10:02 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +int get10() {
Added

2023-08-25 10:02 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +void fun() {
Added

2023-08-25 10:03 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +This rule raises an issue when trying to release pointers to non-heap memory, such as:
Reprashed

2023-08-25 10:04 UTC, LoghinVladDev commented
Added a 'small' "Going the extra mile" section.
Do tell if it should be reduced.

2023-08-25 10:07 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +Freeing stack memory usually happens if the origin of the memory held by a pointer is mixed.
Used "origin of the memory held by a pointer is mixed." since I want to avoid "origin of the memory pointed at by a pointer". Please indicate if you see a better way to phrase this

2023-08-25 11:28 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +
Please also align with the definition of UB that we now use in many rules. You can find an example in the description of rule `S3588`, for instance.
```
When a program comprises undefined behavior, the compiler no longer needs to adhere to the language standard, and the program has no meaning assigned to it.
The application might just crash, but in the worst case, the application may appear to execute correctly, while losing data or producing incorrect results.
```
This should be part of the `What is the potential impact` section.

2023-08-25 11:29 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +  // ...
Sounds good to me, too.

2023-08-25 11:50 UTC, pdschbrt requested changes
Some additional remarks.

2023-08-25 11:50 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +The following non-heap memory types should not be released:
```suggestion
The following non-heap memory types may not be released:
```
Makes it a bit stronger than `should` in this context.

2023-08-25 11:50 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +Freeing stack memory usually happens if the origin of the memory held by a pointer is mixed.
How about simplifying this a bit like in:
```suggestion
The accidental release of non-heap memory usually occurs in practice if the same pointer variable is used to once reference heap and once non-heap memory.
This may lead to confusion and should be avoided.
```

2023-08-25 11:50 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +This can happen
```suggestion

```

2023-08-25 11:50 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +To avoid this, follow these best practices:
```suggestion
These best practices help to avoid accidentally releasing non-heap memory:
```

2023-08-25 11:50 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +* If accessing different memory types, different pointers should be used.
```suggestion
* If accessing different memory types, use different pointer variables.
```

2023-08-25 11:50 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +* When passing non-heap memory address to a function, ensure that the function does not attempt to release the memory.
```suggestion
* When passing non-heap memory addresses to functions, ensure that the functions do not attempt to release the memory.
```

2023-08-25 11:50 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +  useAndClear(usedString); // If length < 31, the unsafe memory will free memory located on the stack.
`useAndClear` is not defined here.

2023-08-25 11:50 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +Noncompliant code example
I would either make these subsections of this very section or use short sentences to briefly explain what the respective code snippet shows. For instance,
```
The following piece of code shows a situation in which the same pointer variable is used to hold a stack or heap address, which leads to a situation in which heap memory is accidentally released.
```
I would prefer the later option, but leave the decision up to you.

2023-08-25 12:28 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +The following non-heap memory types should not be released:
I believe `must` is the intention, and I will go with that. The following ... `may` not ....; for me, implies the possibility that it might not happen

2023-08-25 12:28 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +This can happen
Whoops

2023-08-25 12:35 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +
Then should we start putting this into a new `shared_content/cfamily/potential_impact_undefined_behavior.adoc`?

2023-08-25 12:36 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +The following non-heap memory types should not be released:
In this context "may" means "disallowed". But I'm fine with "must", too.

2023-08-25 12:38 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +
Ideally, yes. However, many rules have slightly adjusted this baseline explanation of UB. So in practice, we cannot really share this.

2023-08-25 12:40 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +The following non-heap memory types should not be released:
Actually yes, you are correct, re-read and agree

2023-08-25 12:46 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +Noncompliant code example
Strongly agree with describing more in detail, tracks better to comments (and edit those a bit)

2023-08-25 12:57 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +  useAndClear(usedString); // If length < 31, the unsafe memory will free memory located on the stack.
addressed

2023-08-25 14:52 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +
I truly believe github should include some "10 lines above/10 lines below" for the suggestions as well, I stared a bit at the suggestion :laughing:. 

Regardless, is this not repeating the same stated concept at line 6 - "Attempting to release any other type of memory is _undefined behavior_?

2023-08-25 14:53 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +  // Compliant: program code will be released at the end of the program's execution.
Didn't think of that, that's a great suggestion

2023-08-25 14:57 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +
That's fine. For most, if not all, of the other rules, we also give a very quick repetition/summary of what goes wrong "IF ..." as an introduction, and then elaborate on what that means for the program and explain the consequences.

2023-08-25 15:01 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +
I truly want to be able to have in-rule links, and have line 6 UB be a link to "potential impact" UB, so we don't have to second guess clarity, since I'm really 50-50 repeats like these, and I balanced the scales with your opinion

2023-08-25 15:02 UTC, LoghinVladDev commented
Apologies for the occasional "leftovers", and thanks for observing them! Was fighting with SQ and getting an informer to display for the longest time today. I'll give it another read since it's past the demo

2023-08-28 08:08 UTC, pdschbrt requested changes
Almost done.

2023-08-28 08:08 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
> +Noncompliant code example
Did you already address this, @LoghinVladDev?
If I'm not mistaken, you elaborated on the code comments. In that case, use the appropriate number of `=` to make the `Noncompliant code example` and `Compliant solution` (sub)section headers.

2023-08-28 08:08 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
Do we have some materials concerning undefined behavior, for instance, that we could link here?

2023-08-28 10:08 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +Noncompliant code example
Oh, I completely missed this, as in, the `==== Compliant ....` formatting you were referring to.

I did not add the `====` since Noncompliant/compliant appears only in How to fix it as subheaders, not in the Going the extra mile section.

I will check if `====` is allowed (if CI formatting check passes)

2023-08-28 10:09 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
No materials of UB caused by stack free found, only crashes.

2023-08-28 11:16 UTC, LoghinVladDev commented on rules/S3590/cfamily/rule.adoc
> +Noncompliant code example
Update: yep, CI tooling fails with ==== inside Going the Extra Mile

2023-08-28 12:10 UTC, pdschbrt commented on rules/S3590/cfamily/rule.adoc
Ok. Leaving this blank should be fine, then.

2023-08-28 12:12 UTC, pdschbrt approved these changes
Looks good now.

2023-08-28 12:27 UTC, LoghinVladDev commented
Merged together with https://github.com/SonarSource/sonar-cpp/pull/2991

2023-08-28 12:50 UTC, merged