APPSEC-1083: S6382 Fixed incorrect ARM examples
SonarSource/rspec pull request #3056
Opened 2023-09-13 07:09 UTC by daniel-teuchert-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-13 13:53 UTC, loris-s-sonarsource requested changes
Things look good, however please remove all the "Compliant" comments 👍

2023-09-13 13:53 UTC, loris-s-sonarsource commented on rules/S6382/azureresourcemanager/rule.adoc
> +      clientCertEnabled: true // Compliant
```suggestion
      clientCertEnabled: true
```

no, we do not add the "compliant" comments haha

2023-09-13 13:53 UTC, loris-s-sonarsource commented on rules/S6382/azureresourcemanager/rule.adoc
> +    clientCertEnabled: true // Compliant
```suggestion
    clientCertEnabled: true
```

2023-09-13 13:53 UTC, loris-s-sonarsource commented on rules/S6382/azureresourcemanager/rule.adoc
> +      authenticationType: 'ClientCertificate' // Compliant
```suggestion
      authenticationType: 'ClientCertificate'
```

2023-09-13 13:53 UTC, loris-s-sonarsource commented on rules/S6382/azureresourcemanager/rule.adoc
> +    clientCertificates: [ // Compliant
```suggestion
    clientCertificates: [
```

2023-09-13 13:53 UTC, loris-s-sonarsource commented on rules/S6382/azureresourcemanager/rule.adoc
> +      certificates: [ // Compliant
```suggestion
      certificates: [
```

2023-09-13 15:12 UTC, loris-s-sonarsource requested changes
I didn't notice them, but sometimes it is written "Sensitive", even in the code samples. Sorry for not noticing earlier, please remove them

2023-09-14 07:10 UTC, daniel-teuchert-sonarsource commented
> I didn't notice them, but sometimes it is written "Sensitive", even in the code samples. Sorry for not noticing earlier, please remove them

What do you mean? I think this is compliant with the general guidelines to mark sensitive code in hotspots with a comment.
See: https://xtranet-sonarsource.atlassian.net/wiki/spaces/LANG/pages/2808479903/General+Guidelines#Highlight-the-sensitive-line-in-non-compliant-samples-(Readability%2C-Consistency)

2023-09-14 07:44 UTC, loris-s-sonarsource commented
@daniel-teuchert-sonarsource I meant in the compliant code samples. Sensitive should be added in the noncompliant ones, but not the compliant ones

2023-09-14 08:02 UTC, daniel-teuchert-sonarsource commented
> @daniel-teuchert-sonarsource I meant in the compliant code samples. Sensitive should be added in the noncompliant ones, but not the compliant ones

oops good catch!

2023-09-14 09:40 UTC, loris-s-sonarsource approved these changes
LGTM!

2023-09-14 09:41 UTC, merged