Modify rule S6581: Add message and highlighting, remove `apk` in favor of `apt`
SonarSource/rspec pull request #3071
Opened 2023-09-14 08:34 UTC by petertrr

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-14 12:00 UTC, mstachniuk requested changes
Please adjust small comments to be compatible with LaYC format.

2023-09-14 14:22 UTC, petertrr commented on rules/S6584/docker/rule.adoc
> +RUN apt install ca-certificates
I didn't want to put it at the first line as it would imply that this is somewhat preferred over `apt-get` . Even though when called from non-interactive runtimes, apt would log `WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`

2023-09-14 14:24 UTC, petertrr commented on rules/S6584/docker/rule.adoc
>  == How to fix it
https://github.com/SonarSource/rspec/blob/master/docs/description.adoc still has `How to fix it` :thinking:

2023-09-15 13:18 UTC, mstachniuk approved these changes
LGTM if all checks are good

2023-09-15 13:21 UTC, merged