Modify S6337: Validation
SonarSource/rspec pull request #3085
Opened 2023-09-14 15:20 UTC by loris-s-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-15 08:33 UTC, daniel-teuchert-sonarsource requested changes
Please check my question regarding the suspicious_activities_terminiation.

2023-09-15 08:33 UTC, daniel-teuchert-sonarsource commented on rules/S6337/secrets/rule.adoc
> +include::../../../shared_content/secrets/impact/suspicious_activities_termination.adoc[]
The suspicious_activities_termination.adoc only mentions the abuse via emails. Does this fit this secret?

2023-09-15 13:23 UTC, loris-s-sonarsource commented on rules/S6337/secrets/rule.adoc
> +include::../../../shared_content/secrets/impact/suspicious_activities_termination.adoc[]
I also added the phishing and malware distribution, I think ti's pretty equivalent to AWS and GCP

2023-09-18 15:01 UTC, loris-s-sonarsource commented on rules/S6337/secrets/rule.adoc
> +include::../../../shared_content/secrets/impact/suspicious_activities_termination.adoc[]
Ah right, no it's not

2023-09-18 15:01 UTC, loris-s-sonarsource commented on rules/S6337/secrets/rule.adoc
> +include::../../../shared_content/secrets/impact/suspicious_activities_termination.adoc[]
```suggestion
include::../../../shared_content/secrets/impact/financial_loss.adoc[]
```

2023-09-18 15:19 UTC, daniel-teuchert-sonarsource approved these changes
LGTM!

2023-09-18 15:43 UTC, merged