Modify rule S5135: Clarify safe loader
SonarSource/rspec pull request #3089
Opened 2023-09-15 14:32 UTC by hendrik-buchwald-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-18 17:21 UTC, jamie-anderson-sonarsource requested changes

2023-09-18 17:21 UTC, jamie-anderson-sonarsource commented on rules/S5135/python/how-to-fix-it/yaml.adoc
> +are considered insecure, as they may allow to deserialize objects.
Just a small phrasing suggestion:
```suggestion
are considered insecure, as they may allow deserialization of objects.
```

2023-09-19 07:06 UTC, pierre-loup-tristant-sonarsource approved these changes

2025-02-27 13:03 UTC, hendrik-buchwald-sonarsource commented
Closed as requested by @nils-werner-sonarsource .

2025-02-27 13:03 UTC, closed without merging