Modify rule S6759: Restrict the scope to functional components
SonarSource/rspec pull request #3102
Opened 2023-09-19 13:17 UTC by yassin-kammoun-sonarsource

I am removing the JavaScript part of the initial RSPEC about Flow.js. Although we do support Flow.js to some extent, we limit ourselves to parsing its specific syntax. However, we don't have rule implementations that visit AST node types specific to Flow.js.

2023-09-19 15:43 UTC, alexander-kamushkin-sonarsource requested changes

2023-09-19 15:43 UTC, alexander-kamushkin-sonarsource commented on rules/S6759/javascript/rule.adoc
> +  return <div>Hello {this.props.name}</div>;
```suggestion
  return <div>Hello {props.name}</div>;
```

2023-09-19 15:43 UTC, alexander-kamushkin-sonarsource commented on rules/S6759/javascript/rule.adoc
> +  return <div>Hello {this.props.name}</div>;
```suggestion
  return <div>Hello {props.name}</div>;
```

2023-09-19 15:43 UTC, alexander-kamushkin-sonarsource commented on rules/S6759/javascript/rule.adoc
> +  return <div>Hello {this.props.name}</div>;
```suggestion
  return <div>Hello {props.name}</div>;
```

2023-09-20 07:02 UTC, yassin-kammoun-sonarsource commented on rules/S6759/javascript/rule.adoc
> +  return <div>Hello {this.props.name}</div>;
Thank you so much for catching this and the rest!

2023-09-20 07:28 UTC, alexander-kamushkin-sonarsource approved these changes

2023-09-20 09:22 UTC, merged