Modify rule S3457: LaYC on printf errors
SonarSource/rspec pull request #3106
Opened 2023-09-19 17:19 UTC by frederic-tingaud-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-21 09:42 UTC, amelie-renard-sonarsource requested changes

2023-09-21 09:42 UTC, amelie-renard-sonarsource commented on rules/S3457/cfamily/rule.adoc
> +Starting with C++20, std::format should be preferred, as it is more readable and validated at compile-time, making it more secure. S6494 covers that.
```suggestion
Starting with C++20, `std::format` should be preferred, as it is more readable and validated at compile-time, making it more secure. S6494 covers that.
```

2023-09-21 09:42 UTC, amelie-renard-sonarsource commented on rules/S3457/cfamily/rule.adoc
>  == Resources
I would add a link to std::format, e.g. https://en.cppreference.com/w/cpp/utility/format/format (not very user-friendly, but we'll add the blog post when we have one about std::format)

2023-09-21 09:42 UTC, amelie-renard-sonarsource commented on rules/S3457/cfamily/rule.adoc
> +Because `printf` format strings are interpreted at runtime, rather than validated by the compiler, they can contain errors that result in the wrong string being created. This rule statically validate
```suggestion
Because `printf` format strings are interpreted at runtime rather than validated by the compiler, they can contain errors that result in the wrong string being created. This rule statically validates the correlation of `printf` format strings and their arguments.
```

2023-09-21 09:42 UTC, amelie-renard-sonarsource commented on rules/S3457/cfamily/rule.adoc
>  This rule will only work if the format string is provided as a string literal.
The exception sentence does not look like an exception but a limitation.
I would either remove the exception paragraph (and include its content in the description) or reword the sentence "This rule does not raise issues when ..."
(I prefer the first option as it really looks like a technical limitation)

2023-09-21 09:42 UTC, amelie-renard-sonarsource commented on rules/S3457/cfamily/rule.adoc
>  printf("%0-f", 1.2); // Noncompliant; flag "0" is ignored because of "-"
```suggestion
printf("%d", 1, 2); // Noncompliant: the second argument "2" is unused
printf("%0-f", 1.2); // Noncompliant: flag "0" is ignored because of "-"
```
see https://sonarsource.slack.com/archives/C04P0SB2KJP/p1686055543993659
(could not find anything in the docs though)

2023-09-21 09:42 UTC, amelie-renard-sonarsource commented on rules/S3457/cfamily/rule.adoc
> +The related rule S2275 is about errors that will create undefined behavior, while this rule is about errors that produce an unexpected string.
Nitpick, but I would begin the sentence with the current rule as it is the one that interests more the user:
```suggestion
This rule is about errors that produce an unexpected string. For errors that will create undefined behavior, see the related rule S2275.
```

2023-09-21 16:08 UTC, frederic-tingaud-sonarsource commented on rules/S3457/cfamily/rule.adoc
>  This rule will only work if the format string is provided as a string literal.
Very true. I like this exception/limitation dichotomy.

2023-09-22 07:05 UTC, amelie-renard-sonarsource approved these changes

2023-09-22 07:05 UTC, merged