Modify rule S5276: LaYC - narrowing conversions
SonarSource/rspec pull request #3108
Opened 2023-09-20 10:09 UTC by frederic-tingaud-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-21 10:23 UTC, amelie-renard-sonarsource requested changes
Nitpicks.
Good idea to add examples in the description, it is far more user-friendly

2023-09-21 10:23 UTC, amelie-renard-sonarsource commented on rules/S5276/cfamily/rule.adoc
> +d += static_cast<double>(f()); // Compliant: clear
```suggestion
d += static_cast<double>(f()); // Compliant: the intent is clear
```

2023-09-21 10:23 UTC, amelie-renard-sonarsource commented on rules/S5276/cfamily/rule.adoc
> +Narrowing conversions should be fixed by either using a destination type that can represent all the source values or by using an explicit conversion:
What about putting the examples and this sentence in the "how to fix it" tab?
I would also add the diff highlighting to the examples

2023-09-21 15:49 UTC, frederic-tingaud-sonarsource commented on rules/S5276/cfamily/rule.adoc
> +Narrowing conversions should be fixed by either using a destination type that can represent all the source values or by using an explicit conversion:
Agreed for the diff, I added it.

Looking at the result of adding a "How to fix it", I have the feeling it is not more readable, so I reverted that.

2023-09-22 06:44 UTC, amelie-renard-sonarsource commented on rules/S5276/cfamily/rule.adoc
> +Narrowing conversions should be fixed by either using a destination type that can represent all the source values or by using an explicit conversion:
Ok

2023-09-22 06:45 UTC, amelie-renard-sonarsource approved these changes

2023-09-22 06:45 UTC, merged