Modify rule S1659: LaYC - one decl per line
SonarSource/rspec pull request #3109
Opened 2023-09-20 12:33 UTC by frederic-tingaud-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-21 10:03 UTC, amelie-renard-sonarsource requested changes

2023-09-21 10:03 UTC, amelie-renard-sonarsource commented on rules/S1659/cfamily/rule.adoc
> +References, pointers and assignments quickly make the behavior confusing for maintainers.
It is not clear by reading these lines when an issue is raised (and so how to fix the issue)
Given the example, I would say we raise an issue when at least a pointer, a reference, or an assignment exists in the declaration?

2023-09-21 16:02 UTC, frederic-tingaud-sonarsource commented on rules/S1659/cfamily/rule.adoc
> +References, pointers and assignments quickly make the behavior confusing for maintainers.
No, it triggers on all non-single declarators. I rewrote it a bit. Is it clearer that way?

2023-09-22 06:50 UTC, amelie-renard-sonarsource commented on rules/S1659/cfamily/rule.adoc
> +References, pointers and assignments quickly make the behavior confusing for maintainers.
Yes, crystal clear, thanks!

2023-09-22 06:50 UTC, amelie-renard-sonarsource approved these changes

2023-09-22 06:51 UTC, merged