Modify rule S2637: Expand and adjust for LaYC
SonarSource/rspec pull request #3145
Opened 2023-09-25 11:35 UTC by pdschbrt

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-26 10:23 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +Setting a value marked as ``++nonnull++`` to null (i.e., ``++NULL++``, ``++0++`` or ``++nullptr++``) is hence likely to cause null pointer dereferences at runtime.
```suggestion
Setting a value marked as ``++nonnull++`` to null (i.e., ``++NULL++``, ``++0++`` or ``++nullptr++``) is hence likely to cause null-pointer dereferences at runtime.
```

2023-09-26 11:06 UTC, necto requested changes
In "Going the extra mile" you can also recommend applying the attribute to your code to propagate the property as far as possible.

2023-09-26 11:06 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +  p = nullptr; // Noncompliant: `p` is marked "nonnull" but is set to null
To avoid confusion, I would move the declaration of `p` out of the parameter list
```suggestion
void foo() {
  __attribute__((nonnull)) int *p = bar();
  p = nullptr; // Noncompliant: `p` is marked "nonnull" but is set to null
```

2023-09-26 11:06 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +Besides affecting the application’s availability, null pointer dereferences may lead to code execution, in rare circumstances. If null is equivalent to the 0x0 memory address that can be accessed by
Have you heard of specific examples of this?

2023-09-26 11:06 UTC, necto commented on rules/S2637/cfamily/rule.adoc
>  == Why is this an issue?
Can you summarize in 1-2 sentences why it is an issue, i.e., what's wrong with it?

2023-09-26 14:01 UTC, pdschbrt commented on rules/S2637/cfamily/rule.adoc
> +Besides affecting the application’s availability, null pointer dereferences may lead to code execution, in rare circumstances. If null is equivalent to the 0x0 memory address that can be accessed by
Yes, there is a CWE or CERT-related article about that. I can look it up, in case you're interested.

This is only relevant for special platforms on which `0x0` is actually a valid memory address, and not for our everyday architectures. However, I thought it might be good to mention it here since it serves as a reminder not to make too many assumptions.

2023-09-26 14:06 UTC, pdschbrt commented on rules/S2637/cfamily/rule.adoc
> +  p = nullptr; // Noncompliant: `p` is marked "nonnull" but is set to null
As far as I know, the 'nonnull' attribute only applies to functions, methods, and parameters, so we need to keep it part of the parameter list.

2023-09-26 14:10 UTC, pdschbrt commented on rules/S2637/cfamily/rule.adoc
>  == Why is this an issue?
Done.

2023-09-26 14:17 UTC, pdschbrt commented
> In "Going the extra mile" you can also recommend applying the attribute to your code to propagate the property as far as possible.

Since one cannot apply the attribute to local pointer variables, I don't think this recommendation applies. We also don't wish to promote the idea of using the "nonnull" attribute blindly all over the place.

2023-09-27 10:25 UTC, necto requested changes
> Since one cannot apply the attribute to local pointer variables, I don't think this recommendation applies. We also don't wish to promote the idea of using the "nonnull" attribute blindly all over the place.

I meant, not to apply it blindly, but propagate it to the parameter declarations of the function that passes its parameters to a function taking `nonnull` arguments.

Also, I think it is worth mentioning that this `nonnull` attribute is a non-standard (either C or C++) GNU extension.

Please add a link to the GNU documentation of this attribute:
https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-nonnull-function-attribute
and 
https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-returns_005fnonnull-function-attribute

2023-09-27 10:25 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +Pointers marked as "nonnull" may not be set to null, since they are typically not null-check before use.
```suggestion
Pointers marked as "nonnull" may not be set to null, since they are typically not null-checked before use.
```

2023-09-27 10:25 UTC, necto commented on rules/S2637/cfamily/rule.adoc
>  == Why is this an issue?
Can you, please, point me to it?

2023-09-27 10:25 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +These values are typically _not_ null-checked before use.
I would also mention, that the compiler applies optimizations based on this attribute, and might, for example, *remove* a null-check if the parameter is declared as `nonnull` (even in the code outside of the function with the attribute)

2023-09-27 10:25 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +Setting a value marked as ``++nonnull++`` to null (i.e., ``++NULL++``, ``++0++`` or ``++nullptr++``) is hence likely to cause null-pointer dereferences at runtime.
Usually there can't be more than one null-pointer dereference before the application crashes
```suggestion
Setting a value marked as ``++nonnull++`` to null (i.e., ``++NULL++``, ``++0++`` or ``++nullptr++``) is hence likely to cause null-pointer a dereference.
```

2023-09-27 10:25 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +== What is the potential impact?
This section deals only with the impact of a null-pointer dereference. However, I believe the rule checks a violation of a contract with the compiler.
As the compiler applies optimizations based on this attribute, there may be no null-pointer dereference but other scary things if the developer does not respect the attribute.
For example, if `arg` is declared `nonnull`, the compiler might completely remove the code after the loop, leading to a file-descriptor leak:
```
void f(__attribute__((nonnull)) Node* arg) {
  while(arg) {
    arg = arg->next;
  }
  fclose(file);
}
```

2023-09-27 10:25 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +Ensure not to pass null values when non-null arguments are expected.
This is the most common fix (as the attribute will likely be in a library function).
However, sometimes it is more appropriate to remove the attribute.

2023-09-27 10:25 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +A commonly used attribute is ``++nonnull++`` which can be used to mark a function's return value and parameters as shown in the following:
In the following example, I expect to see the canonical use of `nonnull`, but I see immediately a broken use.
I suggest first showing how `nonnull` is expected to be used and then adding this code snippet demonstrating how it can be broken.

2023-09-27 10:25 UTC, necto commented on shared_content/cfamily/reference_over_nonnull_pointer.adoc
> +In {cpp}, it is preferred to use reference parameters (Type const& or Type&), or pass objects by value (Type), instead of a pointer (Type const* or Type*), if the argument is expected to never be nul
You can link [C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-inout) here or in the "Resources" section:

- F.17: For "in-out" parameters, pass by reference to non-const
- F.16: For "in" parameters, pass cheaply-copied types by value and others by reference to const

2023-09-27 12:11 UTC, pdschbrt commented on rules/S2637/cfamily/rule.adoc
> +These values are typically _not_ null-checked before use.
Good point.

2023-09-27 13:18 UTC, pdschbrt commented on shared_content/cfamily/reference_over_nonnull_pointer.adoc
> +In {cpp}, it is preferred to use reference parameters (Type const& or Type&), or pass objects by value (Type), instead of a pointer (Type const* or Type*), if the argument is expected to never be nul
Oh yes. That's always a good resource.

2023-09-27 13:22 UTC, pdschbrt commented on rules/S2637/cfamily/rule.adoc
> +Pointers marked as "nonnull" may not be set to null, since they are typically not null-checked before use.
@necto here is the extended sentence. I'm not sure why github swallowed it somehow.

2023-09-27 13:24 UTC, pdschbrt commented on rules/S2637/cfamily/rule.adoc
>  == Why is this an issue?
I've commented on that line further down the conversation. I'm not sure why github swallowed this change.

2023-09-27 16:02 UTC, necto commented on shared_content/cfamily/reference_over_nonnull_pointer.adoc
> +For more details refer to {cpp} Code Guidelines https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md[F.16: For "in" parameters, pass cheaply-copied types by value and others b
I think this part is better left for the "Resources" section. That means it cannot be in the same shared file, unfortunately, but you can create another shared_content file with the pointers, and include them into Resources of both S2637 and S2259. I leave it to your judgement if that will yield more readable rules.

2023-09-28 07:15 UTC, pdschbrt commented on rules/S2637/cfamily/rule.adoc
> +This especially holds for library functions such as the C standard library, for instance, which frequently requires `nonnull` pointer parameters.
We could speak of GCC's implementation of the C standard library. But we shouldn't get lost in the details. Let's make it an easier read.

2023-09-28 07:24 UTC, pdschbrt commented on shared_content/cfamily/reference_over_nonnull_pointer.adoc
> +For more details refer to {cpp} Code Guidelines https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md[F.16: For "in" parameters, pass cheaply-copied types by value and others b
I've duplicated them for now to avoid creating yet another shared file.

2023-09-28 14:45 UTC, necto requested changes

2023-09-28 14:45 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +== Resources
It is surprisingto have half of the "Resources" section here and half in the "see.adoc". I would put it either all here inline of rule.adoc, or all in the "see.adoc" (which can be renamed to "resources.adoc").
Granted, the "../see.adoc" is shared with Java, so you can either duplicate these 3 links there (btw, it should not be directly under "Resources", but in a subsection), or call the file "Standards" and include the entire "Standards" section there

2023-09-28 14:45 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md[F.17: For "in-out" parameters, pass by reference to non-const]
I'd say these are "External coding guidelines" rather than "Standards"

2023-09-28 14:45 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md[F.16: For "in" parameters, pass cheaply-copied types by value and others by reference to const]
Please add these two links also to S2259, IMO they are as relevant there

2023-09-28 14:45 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +Note that the `nonnull` attribute is a GNU extension (cf. https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-nonnull-function-attribute[nonnull] and https://gcc.gnu.org/onlinedo
I did not see "cf." before. According to [wiki](https://en.wikipedia.org/wiki/Cf.) it is used to invite the reader to compare the written with the external reference. IMO, this is not an entirely accurate use here: you are pointing to the documentation of the attributes, how can one compare it with the statement "`nonnull` attribute is a GNU extension"?
So I would either remove "cf." or replaced it with, IMHO, more appropriate "see" (which is also more commonly used).
```suggestion
Note that the `nonnull` attribute is a GNU extension (https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-nonnull-function-attribute[nonnull] and https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-returns_005fnonnull-function-attribute[returns_nonnull]) which many compiler vendors have implemented.
```
or
```suggestion
Note that the `nonnull` attribute is a GNU extension (see https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-nonnull-function-attribute[nonnull] and https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-returns_005fnonnull-function-attribute[returns_nonnull]) which many compiler vendors have implemented.
```

2023-10-04 06:56 UTC, pdschbrt commented on rules/S2637/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md[F.17: For "in-out" parameters, pass by reference to non-const]
Yes, that's indeed a much better place for these two links.

2023-10-04 06:57 UTC, pdschbrt commented on rules/S2637/cfamily/rule.adoc
> +== Resources
This becomes obsolete when addressing the next point.

2023-10-04 06:59 UTC, pdschbrt commented on rules/S2637/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md[F.16: For "in" parameters, pass cheaply-copied types by value and others by reference to const]
They are already there, but I'll move them to an `External coding guidelines` section.

2023-10-04 07:01 UTC, pdschbrt commented on rules/S2637/cfamily/rule.adoc
> +Note that the `nonnull` attribute is a GNU extension (cf. https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-nonnull-function-attribute[nonnull] and https://gcc.gnu.org/onlinedo
I'm fine with using "see" instead. Will change that.

2023-10-04 07:43 UTC, necto requested changes

2023-10-04 07:43 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +
Note that this subtitle is now missing in the Java rule.
I propose to put it directly into the see.adoc (which would be more appropriately named "standards.adoc")

2023-10-04 07:43 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +Setting a value marked as `nonnull` to null (i.e., `NULL`, `0` or `nullptr`) is hence likely to cause a null-pointer dereference.
You are using two phrases to, as I understand it, refer to the same thing: "adhere to the attribute" = "honor the attribute".
I think this is not necessary and detrimental in technical writing because it implies there is a subtle difference where there's none

2023-10-04 07:43 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +Compilers may even apply optimizations based on this attribute and might, for instance, _remove_ an explicit null-check if the parameter is declared as `nonnull`---even in code outside of the functio
triple-dash strikes again (— = ` -- ` - surrounded by spaces)
```suggestion
Compilers may even apply optimizations based on this attribute and might, for instance, _remove_ an explicit null-check if the parameter is declared as `nonnull` -- even in code outside of the function with the attribute.
```
Also, it is convenient to break long sentences into multiple lines at the point of natural pauses (punctuation). For example:
```suggestion
Compilers may even apply optimizations based on this attribute and might,
for instance, _remove_ an explicit null-check if the parameter is declared as `nonnull` --
even in code outside of the function with the attribute.
```

2023-10-04 07:43 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +Besides affecting the application's availability, null pointer dereferences may lead to malicious code execution, in rare circumstances.
```suggestion
Besides affecting the application's availability, null-pointer dereferences may lead to malicious code execution, in rare circumstances.
```

2023-10-04 07:43 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +* S2259 detects null pointer dereferences
```suggestion
* S2259 detects null-pointer dereferences
```

2023-10-04 07:43 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +If null is equivalent to the 0x0 memory address that can be accessed by privileged code, writing, and reading memory is possible, which compromises the integrity and confidentiality of the applicatio
Do you have a reference for this kind of exploit?
I find it hard to believe

2023-10-04 07:43 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +  Node *next;
```suggestion
  Node *next; // NULL for a tail node.
```

2023-10-04 07:43 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +This especially holds for library functions, which frequently require `nonnull` pointer parameters.
In the "Why this is an issue" you also mentioned another fault "assigning null to a nonnull pointer", and it is listed in the code examples. Should you also mention it here (note that it is different from "passing null values to non-null arguments")?

2023-10-04 07:43 UTC, necto commented on shared_content/cfamily/reference_over_nonnull_pointer.adoc
> +In {cpp}, it is preferred to use reference parameters (Type const& or Type&), or pass objects by value (Type), instead of a pointer (Type const* or Type*), if the argument is expected to never be nul
```suggestion
In {cpp}, it is preferred to use reference parameters (`Type const&` or `Type&`), or pass objects by value (`Type`), instead of a pointer (`Type const*` or `Type*`), if the argument is expected to never be null.
```

2023-10-04 08:57 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +In particular, the compiler does not enforce that values marked as `nonnull` are indeed non-null at runtime; it is the developers' responsibility to adhere the attribute.
```suggestion
In particular, the compiler does not enforce that values marked as `nonnull` are indeed non-null at runtime; it is the developers' responsibility to adhere to the attribute.
```

2023-10-04 09:36 UTC, pdschbrt commented on rules/S2637/cfamily/rule.adoc
> +If null is equivalent to the 0x0 memory address that can be accessed by privileged code, writing, and reading memory is possible, which compromises the integrity and confidentiality of the applicatio
You can find more info on that at https://wiki.sei.cmu.edu/confluence/display/c/EXP34-C.+Do+not+dereference+null+pointers or https://cwe.mitre.org/data/definitions/476

These two links are referenced in the "Resources --> Standards" section.

2023-10-04 10:00 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +This especially holds for library functions, which frequently require `nonnull` pointer parameters.
Sorry for going back and forth on it, and thank you for reconciling me with myself :D

2023-10-04 10:02 UTC, necto commented on rules/S2637/cfamily/rule.adoc
> +If null is equivalent to the 0x0 memory address that can be accessed by privileged code, writing, and reading memory is possible, which compromises the integrity and confidentiality of the applicatio
Nice! thank you, I've learned something new

2023-10-04 10:02 UTC, necto approved these changes
Nicely done!

2023-10-04 11:02 UTC, merged