Modify rule S3518: Expand and adjust for LaYC
SonarSource/rspec pull request #3147
Opened 2023-09-25 12:36 UTC by pdschbrt

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-26 10:13 UTC, necto requested changes
Note that in most cases single "`" ticks are enough to highlight a snippet as code. Reach out to heavier double-tick "``" and the `++` when the symbols in the snippet would break the formatting.
e.g.,
```
``++/++`` = `/`
```

Overall, I think your example `unsafe_division` is good but too advanced for the introduction. I would put it into "Going the extra mile", where you also note that you do not need to guard every division with a check for 0 divisor.
IMO, the primary motivating example should be the actual bug that exercises division by zero, not merely fails to protect against it.

2023-09-26 10:13 UTC, necto commented on rules/S3518/cfamily/rule.adoc
> +  return a / b;
```suggestion
  return a / b; // Noncompliant: While the above check correctly prevents signed integer overflows,
                // it fails to prevent divide-by-zero errors. If `b` is equal to `0`, the application
                // emits undefined behavior.
```
It probably does not matter now, but I would still put the "Noncompliant" marker on the line with the bug, or immediately before it. The reason is a potential later use by automated tools as a specification of a TP, like we do with the Julient benchmark.

2023-09-26 10:13 UTC, necto commented on rules/S3518/cfamily/rule.adoc
> +Furthermore, when using signed integer division and the dividend is the minimum value for the signed integer type and the divisor is equal to ``++-1++`` an overflow is provoked due to two's complemen
This sounds unrelated to the div-by-0 rule. Is it also detected by our rule implementation?

2023-09-26 10:13 UTC, necto commented on rules/S3518/cfamily/rule.adoc
> +std::optional<int> unsafe_division(int a, int b) {
This is odd name of the function. To me it looks rather like `safe_division`. Did you try to highlight that it misses the `/0`? The compliant snipped should be called `safe` then, but that would introduce irrelevant diff in the diff-view, so I would call it `safe_division` from the beginning.

2023-09-26 10:13 UTC, necto commented on rules/S3518/cfamily/rule.adoc
> +}
Add a caller code that exercises this div-by-0 possibility. Otherwise, our analyzer will not report, and admittedly, not every division must be checked against a `0` divisor because often it is known to be non-zero and the check introduces only a branch overhead.
Should be something non-obvious like
```
int foo(int a, int b) {
  if (b == 0) {
    a = 1;
  }
  return unsafe_division(a, b);
}
```
An alternative fix also should also be in the caller code, to avoid suggesting that you must check for 0 before *every* division.

2023-09-26 14:43 UTC, pdschbrt commented on rules/S3518/cfamily/rule.adoc
> +  return a / b;
That makes a lot of sense. I'll adjust it accordingly.

2023-09-26 14:45 UTC, pdschbrt commented on rules/S3518/cfamily/rule.adoc
> +std::optional<int> unsafe_division(int a, int b) {
I'll restructure this slightly and also rename it.

2023-09-26 15:01 UTC, pdschbrt commented on rules/S3518/cfamily/rule.adoc
> +}
That's a good suggestion. I've added this alternative.

2023-09-26 15:06 UTC, pdschbrt commented on rules/S3518/cfamily/rule.adoc
> +Furthermore, when using signed integer division and the dividend is the minimum value for the signed integer type and the divisor is equal to ``++-1++`` an overflow is provoked due to two's complemen
I don't think it's implemented by this rule, unfortunately.

I've added this remark as div-by-`-1` is equally dangerous, but oftentimes overlooked. The materials I did go through also all mention that risk, including the relevant CERT pages. I strongly feel that this belongs here.

2023-09-27 10:38 UTC, necto requested changes

2023-09-27 10:38 UTC, necto commented on rules/S3518/cfamily/rule.adoc
> +Furthermore, when using signed integer division and the dividend is the minimum value for the signed integer type and the divisor is equal to `-1` an overflow is provoked due to two's complement repr
This sentence now does not correspond to the code snippet.
I would put this, together with the code that correctly implements both checks (one of your compliant examples) into the "Going the extra mile" section.

I wonder if it is worth drawing the reader's attention to the integer-overflow issue before that

2023-09-27 10:42 UTC, necto commented
You can also link [C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md):

> ES.105: Don't divide by integer zero

BTW, they also mention another possible fix: replace integer division with a floating-point division, where the operation is defined. I think it makes sense to add here too

2023-09-27 14:13 UTC, pdschbrt commented on rules/S3518/cfamily/rule.adoc
> +Furthermore, when using signed integer division and the dividend is the minimum value for the signed integer type and the divisor is equal to `-1` an overflow is provoked due to two's complement repr
I've tried to move the detailed description on overflows to `Going the extra mile` section and I think that makes it a good read.

2023-09-27 14:14 UTC, pdschbrt commented
> You can also link [C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md):
> 
> > ES.105: Don't divide by integer zero
> 
> BTW, they also mention another possible fix: replace integer division with a floating-point division, where the operation is defined. I think it makes sense to add here too

Yes, indeed. I've added a description for this alternative fix.

2023-09-28 15:01 UTC, necto approved these changes

2023-10-04 07:16 UTC, merged