Update C++ rules
SonarSource/rspec pull request #3148
Opened 2023-09-25 13:08 UTC by amelie-renard-sonarsource

2023-09-25 15:31 UTC, marco-antognini-sonarsource requested changes
A few nits, I'll review the remaining 4 rules tomorrow.

2023-09-25 15:31 UTC, marco-antognini-sonarsource commented on rules/S5502/cfamily/rule.adoc
> +If you have several resource allocations in one statement, and the first succeeds while the second fails and throws an exception, the first allocated resource can leak. The classical mitigation for t
I don't understand this part: "you may not have the time to do this". Maybe this is clearer?
```suggestion
If you have several resource allocations in one statement, and the first succeeds while the second fails and throws an exception, the first allocated resource can leak. The classical mitigation for this issue is to use an RAII (_Resource Acquisition Is Initialization_) manager to wrap the raw resource. Yet, this solution may not be sufficient since the execution order is not specified.
```

2023-09-25 15:31 UTC, marco-antognini-sonarsource commented on rules/S5502/cfamily/rule.adoc
> +It is possible to write code that contains several allocations and will still behave correctly (it has even been made easier in {cpp}17, where the evaluation order has been made more strict). However
Present tense is better IMO. 
```suggestion
It is possible to write code that contains several allocations and still behaves correctly. {cpp}17 made this even easier since the evaluation order rules are more strict. However, it requires expert-level knowledge of the language. It is simpler and more future-proof to simply avoid using several allocations in a single statement.
```

2023-09-25 15:31 UTC, marco-antognini-sonarsource commented on rules/S5502/cfamily/rule.adoc
>  === Noncompliant code example
Here too, I find the `using` statement more of a distraction.

2023-09-25 15:31 UTC, marco-antognini-sonarsource commented on rules/S5502/cfamily/rule.adoc
> +It is possible to write code that contains several allocations and will still behave correctly (it has even been made easier in {cpp}17, where the evaluation order has been made more strict). However
Here we say "better not to have the problem in the first place" but in the example, we don't put this forward at all. I wonder if we should suggest an alternative for explicitness that removes the problem altogether. WDYT?

2023-09-25 15:31 UTC, marco-antognini-sonarsource commented on rules/S5502/cfamily/rule.adoc
>  == Resources
Above, the comment "Compliant: no resource in the same expression statement" is puzzling. I think it should say "no two resources are allocated in the same expression statement" but this may be overcomplicated...

2023-09-26 07:10 UTC, marco-antognini-sonarsource reviewed
Nits on the remaining four rules, feel free to pick what you think makes sense.

2023-09-26 07:10 UTC, marco-antognini-sonarsource commented on rules/S5955/cfamily/rule.adoc
>  * Resources are not retained longer than necessary
```suggestion
* It improves readability. The scope of the variable is clearly defined.
* It reduces the number of mistakes. The variable can't be accidentally misused outside of the loop.
* Resources are not retained longer than necessary.
```

2023-09-26 07:10 UTC, marco-antognini-sonarsource commented on rules/S5955/cfamily/rule.adoc
>  using namespace std;
Same comment as before about the using statement. Up to you.

2023-09-26 07:10 UTC, marco-antognini-sonarsource commented on rules/S6367/cfamily/rule.adoc
>  ----
```suggestion
[source,cpp]
----
```

2023-09-26 07:10 UTC, marco-antognini-sonarsource commented on rules/S6367/cfamily/rule.adoc
> +Moreover, access to `thread-local` variables defined inside the coroutine may read uninitialized memory.
```suggestion
Moreover, access to `thread_local` variables defined inside the coroutine may read uninitialized memory.
```

2023-09-26 08:07 UTC, amelie-renard-sonarsource commented on rules/S5951/cfamily/rule.adoc
> +[source,cpp]
Indeed, added

2023-09-26 08:11 UTC, amelie-renard-sonarsource commented on rules/S5506/cfamily/rule.adoc
>  === Noncompliant code example
Indeed. Added in https://github.com/SonarSource/rspec/pull/3148/commits/4f06279ef933f8d5f56cec79d5b60544e0e0eb46

2023-09-26 08:23 UTC, amelie-renard-sonarsource commented on rules/S4998/cfamily/rule.adoc
>  using namespace std;
I agree: fixed in https://github.com/SonarSource/rspec/pull/3148/commits/0f6d0494ef2fcc4e92f539c90ea8855c8146a3f4

2023-09-28 08:25 UTC, amelie-renard-sonarsource commented on rules/S5502/cfamily/rule.adoc
>  === Noncompliant code example
Fixed in https://github.com/SonarSource/rspec/pull/3148/commits/6e24e4e4b2eea2d50fa66721cbfb0ede62a6c993

2023-09-28 08:26 UTC, amelie-renard-sonarsource commented on rules/S5502/cfamily/rule.adoc
> +It is possible to write code that contains several allocations and will still behave correctly (it has even been made easier in {cpp}17, where the evaluation order has been made more strict). However
I added a more straightforward solution: https://github.com/SonarSource/rspec/pull/3148/commits/6e24e4e4b2eea2d50fa66721cbfb0ede62a6c993
WDYT?

2023-09-28 08:26 UTC, amelie-renard-sonarsource commented on rules/S5502/cfamily/rule.adoc
>  == Resources
Modified in https://github.com/SonarSource/rspec/pull/3148/commits/6e24e4e4b2eea2d50fa66721cbfb0ede62a6c993. Sounds clearer?

2023-09-28 08:51 UTC, marco-antognini-sonarsource commented on rules/S5502/cfamily/rule.adoc
> +It is possible to write code that contains several allocations and will still behave correctly (it has even been made easier in {cpp}17, where the evaluation order has been made more strict). However
Looks good!

2023-09-28 08:52 UTC, marco-antognini-sonarsource commented on rules/S5502/cfamily/rule.adoc
>  == Resources
Perfect

2023-09-28 08:57 UTC, amelie-renard-sonarsource commented on rules/S3624/cfamily/rule.adoc
>  Those operations work together, and letting the compiler automatically generate some of them, but not all, means that when one of those functions is called, the integrity of the resource will probabl
I (ChatGPT) rewrote the paragraph in https://github.com/SonarSource/rspec/pull/3148/commits/d5e64ae02928588aadece338ca8e7271a9338a9b. WDYT?

2023-09-28 11:33 UTC, marco-antognini-sonarsource commented on rules/S3624/cfamily/rule.adoc
>  Those operations work together, and letting the compiler automatically generate some of them, but not all, means that when one of those functions is called, the integrity of the resource will probabl
LGTM 👍

2023-09-28 12:48 UTC, amelie-renard-sonarsource commented on rules/S5951/cfamily/rule.adoc
>  {cpp}11 introduced reference qualifiers for member functions. This feature provides a better approach to forbid calling unintended functions:
As discussed, I reverted the changes in https://github.com/SonarSource/rspec/pull/3148/commits/ee967bdd53afa8a95187647d4a9263db66b917f7

2023-09-28 12:48 UTC, amelie-renard-sonarsource commented on rules/S5951/cfamily/rule.adoc
>  if (x1 + x2 = x3) { // Compiler will complain since const object cannot be assigned. Should be "x1 + x2 == x3"
As discussed, I reverted the changes in https://github.com/SonarSource/rspec/pull/3148/commits/ee967bdd53afa8a95187647d4a9263db66b917f7

2023-09-28 12:48 UTC, amelie-renard-sonarsource commented on rules/S5951/cfamily/rule.adoc
> +struct X {
As discussed, I reverted the changes in https://github.com/SonarSource/rspec/pull/3148/commits/ee967bdd53afa8a95187647d4a9263db66b917f7

2023-09-28 13:18 UTC, marco-antognini-sonarsource approved these changes
LGTM, thanks!

2023-09-28 14:48 UTC, merged