Modify rule S1854: Expand and adjust for LaYC
SonarSource/rspec pull request #3150
Opened 2023-09-25 14:14 UTC by pdschbrt

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-25 14:15 UTC, pdschbrt commented
Hey @necto 

I'm not yet happy with the updated rule description. I'm especially unhappy with `What is the potential impact?` section---any feedback is highly appreciated.

Cheers

2023-09-26 09:42 UTC, necto requested changes
I think it is important to mention the side effects of the RHS. (In the "Pitfalls" section?)
For example, here the `fwrite` call is probably made for its side effect:
```
size_t written = fwrite(str, sizeof(*str), strlen(str), fd);
```

I would also mention the `(void)` trick to ignore the `[[nodiscard]]` return values:
```
[[nodiscard]] int f();

void g() {
  (void)f();
}
```

2023-09-26 09:42 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +Assigning a value to a local variable that is not read by any subsequent instruction is called a _dead store_.
In the first paragraph, I would summarize in 1 or 2 sentences *why* this is an issue.
Something like "The only utility of assigning a value to a variable is to use this value later in the code. If it is never used, there is no need for the assignment. The presence of a useless assignment indicates misaligned intentions and is most likely an error". But preferably shorter.

2023-09-26 09:42 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +The following code snippet depicts a dead store.
IMO, this snippet contains too much code irrelevant to the issue.
I would limit it to ~5 lines. I would also add multiple snippets:
- assignment
  - the variable is never mentioned again
  - the variable is immediately overwritten
- increment (that you have)
- initialization

Perhaps most of them should be moved to the "noncompliant example"s

2023-09-26 09:42 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +Assigning a value to a local variable that is not read by any subsequent instruction is called a _dead store_.
Your sentence after the snippet does the job well:

> Computing or retrieving a value only to then immediately overwrite it or throw it away indicates serious logic errors in the code.

2023-09-26 09:42 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +  factorial(n);
Does our rule detect this too?

2023-09-26 09:42 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +}
Given that `factorial` is not the point of the example, I would choose a shorter function, e.g. 
```
long twice(long n) {
  return n*2;
}
```

2023-09-26 11:07 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +
It looks like you are missing a bunch of "Noncompliant code example" headers

2023-09-27 07:03 UTC, pdschbrt commented
> I think it is important to mention the side effects of the RHS. (In the "Pitfalls" section?) For example, here the `fwrite` call is probably made for its side effect:
> 
> ```
> size_t written = fwrite(str, sizeof(*str), strlen(str), fd);
> ```
> 
> I would also mention the `(void)` trick to ignore the `[[nodiscard]]` return values:
> 
> ```
> [[nodiscard]] int f();
> 
> void g() {
>   (void)f();
> }
> ```

Sold! Thanks for the suggestions.

2023-09-27 07:18 UTC, pdschbrt commented on rules/S1854/cfamily/rule.adoc
> +  factorial(n);
Sadly, it doesn't. I've simplified this example.

2023-09-27 07:19 UTC, pdschbrt commented on rules/S1854/cfamily/rule.adoc
> +}
I've removed the function altogether since our rule does not try to reason about side effects.

2023-09-27 07:19 UTC, pdschbrt commented on rules/S1854/cfamily/rule.adoc
> +
Ups, yes I do.

2023-09-27 15:47 UTC, necto requested changes
Looks pretty solid. Only minor nits left

2023-09-27 15:47 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +  // Compliant: no more dead stores and superfluous code
```suggestion
  // Compliant: no more dead stores and superfluous code
  // Assuming call to buz() had no important side effects
```

2023-09-27 15:47 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +  int x = 0;
```suggestion
  int x = 0; // Noncompliant: dead store, next line overwrites x
```

2023-09-27 15:47 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +When removing unused values and superfluous code, make sure that the right-hand side of a given assignment has no side effects that update the program's state.
This is either a tautology or it is not complete: if you consider files on disk and the network packets as part of program state, than any side effect update program's state. If you don't, you should still consider these side effects even though they do not update program's state
```suggestion
When removing unused values and superfluous code, make sure that the right-hand side of a given assignment has no side effects.
```

2023-09-27 15:47 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +  size_t n_items = fwrite(str, sizeof(char), strlen(str), stdout); // Noncompliant: `n_items` is never read, but the call has side effects
this line is long.
I am not sure whether you can place the `Noncompliant` comment on the previous one, but you certainly can put the explanation in a separate comment on another line.

2023-09-27 15:47 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +* S3516 ensures that function returns are not invariant
IMO, "function returns" as a noun, while grammatically correct, is pretty surprising and "function returns are" makes most readers stumble
```suggestion
* S3516 ensures that a function returns non-invariant
```

2023-09-28 07:39 UTC, pdschbrt commented on rules/S1854/cfamily/rule.adoc
> +* S3516 ensures that function returns are not invariant
Fair point.

2023-09-28 12:21 UTC, necto approved these changes
LGTM! See the minor nits in line comments

2023-09-28 12:21 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +The following code snippet depicts a dead store.
```suggestion
The following code snippet depicts a few dead stores.
```

2023-09-28 12:21 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +Therefore, unused values and superfluous code should be removed to prevent logic errors.
The second sentence does not really follow from the first (which does not mention logic errors, and even seem to argue otherwise).
```suggestion
Even if the unnecessary operations do not do any harm in terms of the program's correctness, they are--at best--a waste of computing resources.
In most cases, the operations have their intended use but it is not expressed in the code correctly.
Therefore, unused values and superfluous code should be removed to prevent logic errors.
```
Or something similar.

2023-09-28 12:21 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +  int x = 0;
Does the rule flag zero-initialization?
if it does, this marker is missing:
```suggestion
  int x = 0; // Noncompliant: dead store
```

2023-09-28 12:21 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +Still, values that are never read such as `n_items` indicate code smells that should be mitigated.
```suggestion
Still, values that are never read such as `n` indicate code smells that should be mitigated.
```

2023-09-28 12:21 UTC, necto commented on rules/S1854/cfamily/rule.adoc
> +A function that is marked `nodiscard` or that returns an enumeration or class declared `nodiscard` by value which is used in a discarded-value expression encourages the compiler to issue a warning.
This sentence is pretty complex.
I propose removing some information from it, given it is already pretty remote to the topic of the rule:
```suggestion
A function that is marked `nodiscard`  whose return value is ignored encourages the compiler to issue a warning.
```
Otherwise, please simplify / break it down into simpler sentences

2023-09-28 13:16 UTC, pdschbrt commented on rules/S1854/cfamily/rule.adoc
> +  int x = 0;
I just checked, it doesn't.

2023-09-28 13:25 UTC, merged