Modify rule S3519: Expand and adjust for LaYC
SonarSource/rspec pull request #3160
Opened 2023-09-26 13:49 UTC by pdschbrt

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-27 11:52 UTC, balazs-benics-sonarsource requested changes
Pretty good, I'd say.

2023-09-27 11:52 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +Ensure that memory access are within the bounds of the allocated array or buffer.
Shouldn't thins be plural?: memory accesses
Have you checked the text with Grammarly?

2023-09-27 11:52 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +}
Unfortunately, due to loop unrolling (4), we don't detect this: https://godbolt.org/z/ezMs5jhcc
I'd recommend reworking this example.

It's also not a good practice to hardcode the length of the string at the array declaration.

2023-09-27 11:52 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +=== Going the extra mile
Before the extra mile, I think it worths mentioning that one needs to be careful for zero terminating buffers whenever needed as this can be a problem (pitfall) in this context.

2023-09-27 11:52 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +To mitigate this risk, developers must carefully manage array and buffer sizes (, use secure coding practices, and employ techniques like input validation and bounds checking).
I think we should improve the chunking of this sentence by splitting it. This way we can express the same without using parens and colons.

2023-09-27 11:52 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +Instead, the `std::array` type should be used to manage stack-based arrays, and the `std::vector` type should be used if a heap-based array is desired.
Do we use the term "stack-based" anywhere else?
I think the accurate term is "automatic storage duration", but I guess yours is still more accessible for the reader.

2023-09-27 11:52 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +Besides always carrying their respective sizes, i.e., number of elements, `std::array` and `std::vector` implement many useful member functions such as `begin()` and `end()`, allowing one to safely a
```suggestion
Besides always carrying their respective sizes, i.e., the number of elements, `std::array` and `std::vector` implement many useful member functions such as `begin()` and `end()`, allowing one to safely and conveniently process them using algorithms from the {cpp}'s `<algorithm>` header, for instance.
```

2023-09-27 11:52 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +void buz(std::string const &s) {
global: I think the example names should reflect their content.

2023-09-27 11:52 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +* CWE - https://cwe.mitre.org/data/definitions/788[788 Access of Memory Location After End of Buffer]
In some entries you have the `.html` suffix, for others don't.
Please harmonize them.

2023-09-27 11:52 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +* CppCon 2018 - https://www.youtube.com/watch?v=0S0QgQd75Sw&ab_channel=CppCon[Software Vulnerabilities in C and C++]
This link appears to be dead to me.

2023-09-27 14:32 UTC, pdschbrt commented on rules/S3519/cfamily/rule.adoc
> +}
Yes, I've changed the code snippets in question to the C programming language.

2023-09-27 14:41 UTC, pdschbrt commented on rules/S3519/cfamily/rule.adoc
> +}
I'll give it a shot and rework it a bit.

2023-09-27 14:42 UTC, pdschbrt commented on rules/S3519/cfamily/rule.adoc
> +=== Going the extra mile
Let me add a `Pitfalls` section here.

2023-09-28 06:59 UTC, pdschbrt commented on rules/S3519/cfamily/rule.adoc
> +Instead, the `std::array` type should be used to manage stack-based arrays, and the `std::vector` type should be used if a heap-based array is desired.
Yes, I think "stack-based" is easier to swallow here. Especially, since we talk about "heap-based" arrays in the next half of the sentence.

2023-09-28 07:02 UTC, pdschbrt commented on rules/S3519/cfamily/rule.adoc
> +void buz(std::string const &s) {
I agree, but I guess that is off the table as this is not consistently handled in the rules that have been rewritten so far, unfortunately. From what I've seen I believe it's quite the contrary :-(

2023-09-28 07:04 UTC, pdschbrt commented on rules/S3519/cfamily/rule.adoc
> +* CppCon 2018 - https://www.youtube.com/watch?v=0S0QgQd75Sw&ab_channel=CppCon[Software Vulnerabilities in C and C++]
Oh, thanks for pointing that out. It was alive a few days ago. YouTube is strange sometimes 😄

2023-09-28 07:06 UTC, pdschbrt commented on rules/S3519/cfamily/rule.adoc
> +* CppCon 2018 - https://www.youtube.com/watch?v=0S0QgQd75Sw&ab_channel=CppCon[Software Vulnerabilities in C and C++]
That's crazy. The link is alive. It's only dead if you try to access the video using the Island browser. When using ordinary Chrome, it's all fine.

2023-09-28 07:11 UTC, pdschbrt commented on rules/S3519/cfamily/rule.adoc
> +Besides always carrying their respective sizes, i.e., number of elements, `std::array` and `std::vector` implement many useful member functions such as `begin()` and `end()`, allowing one to safely a
This should be fine and more of a flow without the "the" as "i.e." refers to "sizes".

2023-09-28 15:05 UTC, necto commented on rules/S3519/cfamily/rule.adoc
> +* CppCon 2018 - https://www.youtube.com/watch?v=0S0QgQd75Sw&ab_channel=CppCon[Software Vulnerabilities in C and C++]
Perhaps something to report to IT?

2023-09-28 15:50 UTC, necto requested changes
Note @balazs-benics-sonarsource comments in the bottom of "rules/S3519/cfamily/rule.adoc". I think there are a few things that you can draw from them

2023-09-28 15:50 UTC, necto commented on rules/S3519/cfamily/rule.adoc
> +Not only do these faulty accesses constitute undefined behavior, but they frequently introduce security vulnerabilities and open up the program to buffer overflow attacks, too.
This sounds like tautology
```suggestion
Not only do these faulty accesses constitute undefined behavior, but they frequently introduce security vulnerabilities, too.
```

2023-09-28 15:50 UTC, necto commented on rules/S3519/cfamily/rule.adoc
> +In case a user of the program can control the contents of a buffer, for instance, a malicious attacker can the buffer overflow to overwrite critical data, execute arbitrary code, or gain unauthorized
```suggestion
In case a user of the program can control the contents of a buffer, for instance, a malicious attacker can use the buffer overflow to overwrite critical data, leak secret or private information, execute arbitrary code, or gain unauthorized access to the system.
```

2023-09-28 15:50 UTC, necto commented on rules/S3519/cfamily/rule.adoc
> +  strncpy(buf1, str, strlen(str));
This is also far from best practice: if I accidentally add some characters to `str`, I'll overrun `buf1`. I think you should change both non-compliant and compliant examples to allocate `buf1` based on `strlen(str)`

2023-09-28 15:50 UTC, necto commented on rules/S3519/cfamily/rule.adoc
> +    printf("%d\n", array[i]);
Since this is a "**non**compliant" example, why not take the opportunity?
```suggestion
  for (size_t i = 0; i <= 8; ++i) { // Noncompliant: index is between 0 and 7
    printf("%d\n", array[i]); // Noncompliant: index reaches 8 - beyond the last element of the array
```

2023-09-28 15:50 UTC, necto commented on rules/S3519/cfamily/rule.adoc
> +    printf("%d\n", array[i]);
```suggestion
  for (size_t i = 0; i < 8; ++i) {
    printf("%d\n", array[i]); // Compliant: index is between 0 and 7
```

2023-09-28 15:50 UTC, necto commented on rules/S3519/cfamily/rule.adoc
> +However, the heap-allocated memory buffer for holding the copy is too small since `strlen` calculates the length of its input string but exclude the "invisible" terminating null byte ('\0').
```suggestion
However, the heap-allocated memory buffer for holding the copy is too small since `strlen` calculates the length of its input string but exclude the "invisible" terminating null byte (`'\0'`).
```

2023-09-28 15:50 UTC, necto commented on rules/S3519/cfamily/rule.adoc
> +[source,c]
I would use the diff-view here too, even though it is outside of "how to fix it", I think it can still be displayed in some products, and in the worst case, diff won't be highlighted

2023-09-28 15:50 UTC, necto commented on rules/S3519/cfamily/rule.adoc
> +  }
```suggestion
```
It is not always a good idea to check the `malloc` return value for null...

In any case, it is not the focus of this rule, and you already omitted it from other examples, so I would omit it here too, for brevity

2023-09-28 15:50 UTC, necto commented on rules/S3519/cfamily/rule.adoc
> +The `std::string` type should be used to manage buffers, since it guarantees safe buffer manipulations.
```suggestion
The `std::string` type should be used to manage buffers since it facilitates safe buffer manipulations.
```
you can still access string out-of-bounds

2023-09-28 15:50 UTC, necto commented on rules/S3519/cfamily/rule.adoc
>  == Resources
S5945 - for the discussion about replacing arrays with C++ wrappers
Maybe also S1851 that deprecates pointers

2023-09-28 15:50 UTC, necto commented on rules/S3519/cfamily/rule.adoc
>  == Resources
Also S5782 - overflow in POSIX functions. BTW, I think some of your examples actually belong to S5782 (e.g., overrun in `printf`)

2023-10-03 08:12 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +    printf("%d\n", array[i]);
Because we cannot detect that case. It would require us to loop more than 4 times to reach the OOB access.
I asked for this refactoring [here](https://github.com/SonarSource/rspec/pull/3160#discussion_r1338471315).

2023-10-03 08:12 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +=== Going the extra mile
Excellent addition! I love it.

2023-10-04 14:05 UTC, pdschbrt commented on rules/S3519/cfamily/rule.adoc
>  == Resources
I've added them to the "Related rules" section.

2023-10-04 14:22 UTC, pdschbrt commented on rules/S3519/cfamily/rule.adoc
> +  strncpy(buf1, str, strlen(str));
I addressed that issue.

2023-10-04 14:40 UTC, pdschbrt commented on rules/S3519/cfamily/rule.adoc
> +  }
I'm usually in favor of brevity, too. However, I feel the need to correctly handle a "failing" `malloc` in this example. Since both, this rule and our examples target low-level C code, we should highlight that many things can go sideways pretty quickly due to the very basic nature of APIs and functionalities provided by the C standard library---making them rather inconvenient to use at times. Unhandled allocation failures are often overlooked, but when manually handling buffers in C you need to get everything exactly right. The `make_str_copy` function should depict a function that is more on the realistic side.

There is only one other example that uses `malloc` which I would adjust to also have it handled correctly, if you don't mind.

2023-10-04 15:46 UTC, necto commented on rules/S3519/cfamily/rule.adoc
> +  }
I think it might not be a good idea because it is rare that you can do anything useful when your system is out of memory, but these frequent error checks still clutter the code. My reasoning was similar to [this SQ question](https://stackoverflow.com/questions/2248995/is-there-a-need-to-check-for-null-after-allocating-memory-when-kernel-uses-over), and [this answer](https://stackoverflow.com/a/49993528). I do not insist here, as the only downside is the code readability, and this rule deals with the safety so probably should err on the safe side

2023-10-05 07:00 UTC, pdschbrt commented
> Note @balazs-benics-sonarsource comments in the bottom of "rules/S3519/cfamily/rule.adoc". I think there are a few things that you can draw from them

Yes, I've extended the "Going the extra mile" section and incorporated some code examples, too 👍🏻

2023-10-05 11:22 UTC, balazs-benics-sonarsource reviewed
I've looked at the diff since the last review, and I think it's good.
I only had one remark.

2023-10-05 11:22 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +* Stack Protection - https://developers.redhat.com/articles/2022/06/02/use-compiler-flags-stack-protection-gcc-and-clang#:~:text=Stack%20canary&text=A%20modification%20indicates%20the%20detection,%2D
```suggestion
* Stack Protection - https://developers.redhat.com/articles/2022/06/02/use-compiler-flags-stack-protection-gcc-and-clang[Use compiler flags for stack protection in GCC and Clang]
```

Stuff after the `?` or `#` in URLs are usually optional.

2023-10-05 11:22 UTC, balazs-benics-sonarsource commented on rules/S3519/cfamily/rule.adoc
> +Various modern C and C++ compilers allow one to automatically instrument a program during compilation using so-called _sanitizers_.
```suggestion
Various modern C and {cpp} compilers allow one to automatically instrument a program during compilation using so-called _sanitizers_.
```

2023-10-05 12:57 UTC, balazs-benics-sonarsource approved these changes

2023-10-05 13:59 UTC, merged