Modify rule S946: Expand and adjust for LaYC
SonarSource/rspec pull request #3163
Opened 2023-09-27 11:50 UTC by pdschbrt

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-09-27 16:19 UTC, frederic-tingaud-sonarsource commented on rules/S946/cfamily/rule.adoc
> +Assigning the address of an automatic object to another object that outlives it is dangerous since the address is invalidated after the first object has ceased to exist.
An explanation of what an "automatic object" is could be useful here.

2023-09-28 07:42 UTC, pdschbrt commented on rules/S946/cfamily/rule.adoc
> +Assigning the address of an automatic object to another object that outlives it is dangerous since the address is invalidated after the first object has ceased to exist.
That's a good point. I'll try to craft a brief description.

2023-09-28 09:33 UTC, frederic-tingaud-sonarsource reviewed
So far, the code samples are in C.
In a sense, I guess many users who will trigger these problems are C developers. On the other hand, we usually do C++ samples and this kind of samples can be an occasion to nudge old-school C++ developers toward more modern code.
So I would vote for C++ and more modern samples, but you can choose to follow this vote or not.

2023-09-28 09:33 UTC, frederic-tingaud-sonarsource commented on rules/S946/cfamily/rule.adoc
> +  for (size_t i = 0; i < sizeof(buffer) / sizeof(buffer[0]); ++i) {
```suggestion
  for (char &c: buffer) {
```
or
```suggestion
  std::fill(std::begin(buffer), std::end(buffer), 42);
```

2023-09-28 10:00 UTC, pdschbrt commented
I agree with you: The rule is quite on the `C` side of life and I didn't want to overdo it in terms of making it `C++`.

2023-09-28 12:25 UTC, frederic-tingaud-sonarsource reviewed
Most of these are mere suggestions. Feel free to ignore them.

2023-09-28 12:25 UTC, frederic-tingaud-sonarsource commented on rules/S946/cfamily/metadata.json
I find the title a bit wordy and it also doesn't apply well to returning the address of a local variable.
What about
"The address of an automatic object should not be persisted after its lifetime"
or
"The address of an automatic object should not be persisted after the object ceases to exist"?

2023-09-28 12:25 UTC, frederic-tingaud-sonarsource commented on rules/S946/cfamily/rule.adoc
> +If the address of an automatic object is assigned to another automatic object of larger scope, a static or extern object, or if it is returned from a function (using `return` or an output parameter),
Just a suggestion:
```suggestion
If the address of an automatic object is assigned to another automatic object of larger scope, a static or extern object, or if it is returned from a function (using `return` or an output parameter), then there will be a point where the address will point to an object that ceased to exist.
```

2023-09-28 12:25 UTC, frederic-tingaud-sonarsource commented on rules/S946/cfamily/rule.adoc
> +Assigning the address of an automatic object to another object that outlives it is dangerous since the address is invalidated after the first object has ceased to exist.
```suggestion
Persisting the address of an automatic object after it ceases to exist is dangerous because any attempt to dereference it would result in undefined behavior.
```
I think what makes this description harder to read is the fact that many sentences have two different "object" in them that need to be fully qualified each time to make sense.

2023-09-28 12:25 UTC, frederic-tingaud-sonarsource commented on rules/S946/cfamily/rule.adoc
> +Persisting addresses of objects with automatic storage using objects that outlive them is dangerous as it may create invalid addresses.
```suggestion
Persisting addresses of objects with automatic storage past their lifetime is dangerous as it may create invalid addresses.
```

2023-09-28 12:25 UTC, frederic-tingaud-sonarsource commented on rules/S946/cfamily/rule.adoc
> +Do not persist addresses of objects with automatic storage using objects that outlive them.
This sentence only repeats what the title says. Summing up the below solutions might be more useful:

```suggestion
There are multiple approaches to avoid persisting addresses of object with automatic storage after their lifetime ended:

* Make a full copy of the object instead of using an address.
* Allocate the address on the heap and deallocate it once done.
* Create the automatic object in a larger scope where it outlives all storages of its address.
* Reduce the scope of objects that store the address of the original automatic object.
```

2023-10-03 07:38 UTC, balazs-benics-sonarsource commented on rules/S946/cfamily/rule.adoc
> +Assigning the address of an automatic object to another object that outlives it is dangerous since the address is invalidated after the first object has ceased to exist.
+1, but I would recommend avoiding the term "dereference" as we can also have dangling references.
Have you considered the term "access"? See https://godbolt.org/z/43c3esze1

2023-10-03 07:38 UTC, balazs-benics-sonarsource commented on rules/S946/cfamily/rule.adoc
> +The storage for an automatic object, e.g. a local variable, is allocated at the beginning of the enclosing code block and is deallocated at the end.
```suggestion
The storage for an automatic object, e.g. a local variable, is allocated at the beginning of the enclosing code block and is deallocated at the end.
This is commonly referred to as "allocated on the stack".
```
I think it's useful to make a connection to the common name of this so that the user could connect this to other resources.

2023-10-03 07:38 UTC, balazs-benics-sonarsource commented on rules/S946/cfamily/rule.adoc
> +In that case, the address becomes invalid and attempts to dereference the invalid address result in undefined behavior.
```suggestion
In that case, the address becomes invalid, and attempts to access it is undefined behavior.
```

2023-10-03 07:38 UTC, balazs-benics-sonarsource commented on rules/S946/cfamily/rule.adoc
> +}
It's unfortunate, but we don't detect escapes through out parameters.
And I was surprised that we don't raise S6655 for `ptr`. Then I realized that we would need to read or write (in short: access) the dangling pointer `ptr` to make use raise the issue.

I'd recommend raising a ticket for the out parameter and reworking the example.

2023-10-03 07:38 UTC, balazs-benics-sonarsource commented on rules/S946/cfamily/rule.adoc
> +}
It's unfortunate, but due to loop unrolling of known bounds limitations, see CPP-3607, we won't analyze anything after the loop statement, thus we never reach the return where we could raise this issue.

2023-10-05 07:12 UTC, pdschbrt commented on rules/S946/cfamily/metadata.json
Thanks for these suggestions. The title was indeed quite long.

I slightly modified your first suggestion and ended up with "The address of an automatic object should not be persisted beyond the object's lifetime" which sounds good to me.

2023-10-05 07:34 UTC, pdschbrt commented on rules/S946/cfamily/rule.adoc
> +}
Interesting. I'll create a ticket for that and introduce lit tests in the corresponding `sonar-cpp` pull request that links to the ticket -- that's how Tomek and I handled such situations previously.

2023-10-05 07:59 UTC, pdschbrt commented on rules/S946/cfamily/rule.adoc
> +}
At least we already have a ticket for that. I'll rework that code a bit, since we are not really interested in analyzing loops here.

2023-10-05 08:03 UTC, pdschbrt commented on rules/S946/cfamily/rule.adoc
> +}
cf. https://sonarsource.atlassian.net/browse/CPP-4734

2023-10-05 09:13 UTC, pdschbrt commented
I wonder if we should add a "Going the extra mile" section and suggest using C++ alternatives (if possible) to avoid these situations in the first place.

Then, on the other hand, that would be also quite a stretch since this rule is about persisting addresses of automatic variables.

Let me know if you are happy with the current state or if we should add something, @frederic-tingaud-sonarsource, @balazs-benics-sonarsource.

2023-10-05 09:30 UTC, balazs-benics-sonarsource requested changes
2 minor remarks left.

2023-10-05 09:30 UTC, balazs-benics-sonarsource commented on rules/S946/cfamily/rule.adoc
> +* CERT - https://wiki.sei.cmu.edu/confluence/display/c/MSC00-C.+Compile+cleanly+at+high+warning+levels[MSC00-C. Compile cleanly at high warning levels]
For these CERT links, sometimes its's a short link, sometimes a long link.
Please consolidate this and use the format that is used across different rules.

2023-10-05 09:30 UTC, balazs-benics-sonarsource commented on rules/S946/cfamily/rule.adoc
> +* Allocate the object on the heap and deallocate it once done.
Depending on the book, it's sometimes called "heap", and othertimes called "free-store".
I believe the Scott Meyers and Bjarne books differ on this taxonomy. Maybe it's better to xref these.
```suggestion
* Allocate the object on the heap (free-store) and deallocate it once done.
```

I found a paper actually using the "free-store" terminology: https://wg21.link/P1950.

2023-10-05 09:38 UTC, pdschbrt commented on rules/S946/cfamily/rule.adoc
> +* CERT - https://wiki.sei.cmu.edu/confluence/display/c/MSC00-C.+Compile+cleanly+at+high+warning+levels[MSC00-C. Compile cleanly at high warning levels]
Thanks for pointing this out. By majority vote (using `grep`) we now use short links 😁

2023-10-05 11:08 UTC, balazs-benics-sonarsource approved these changes
I'm good. Check Fred's comments and resolve them and merge this if they don't contradict.

2023-10-05 12:04 UTC, merged