Add CI task to validate file extension
SonarSource/rspec pull request #3196
Opened 2023-10-03 14:53 UTC by cristian-ambrosini-sonarsource

2023-10-05 15:53 UTC, gregory-paidis-sonarsource commented on ci/validate_file_extensions.sh
> +    echo $CSVB_FILES
This will print only the first element of the array. You need to either:
- Loop over them and print them with `for thingy in `${CSVB_FILES[@]}"`
- Use an oneliner like `printf '%s\n' "${CSVB_FILES[@]}"`

2023-10-05 15:55 UTC, gregory-paidis-sonarsource approved these changes
LGTM, please take care of the one comment I left.

2023-10-06 09:12 UTC, necto approved these changes

2023-10-06 09:12 UTC, necto commented on ci/validate_file_extensions.sh
I think this file deserves a comment similar to your PR comment.
It looks weird out of context: What is special about .cs and .vb files?

2023-10-06 14:23 UTC, sebastien-marichal requested changes
We almost forgot about Blazor / Razor files 😱

2023-10-06 14:23 UTC, sebastien-marichal commented on ci/validate_file_extensions.sh
> +CSVB_FILES=($(find "${RULES_DIR}" -type f -name "*.cs" -o -name "*.vb"))
Can you add `.razor` & `.cshtml` as well?

2023-10-06 15:13 UTC, cristian-ambrosini-sonarsource commented on ci/validate_file_extensions.sh
> +CSVB_FILES=($(find "${RULES_DIR}" -type f -name "*.cs" -o -name "*.vb"))
Good catch! I'll add them right away

2023-10-06 15:19 UTC, sebastien-marichal approved these changes
LGTM!

2023-10-09 08:37 UTC, merged