Check links embeded in adocs files
SonarSource/rspec pull request #32
Opened 2021-02-05 15:07 UTC by tomverin

2021-02-05 15:17 UTC, nicolas-harraudeau-sonarsource commented on checklinks.py
> +      print(f"Nothing there: {url}")
Could you print the actual status? 400, 401, 403 and 404 status codes have completely different meanings. Last time I worked with URLs, the answer I was getting was different if I did it from curl or a browser. Knowing what the exact status code is will help us understand if the problem comes from the script or if the URL is really broken.

2021-02-05 15:20 UTC, nicolas-harraudeau-sonarsource commented on checklinks.py
> +      print(f"Ok: {url}")
Just a side-note: this should be only printed in "debug" or "info" mode. We don't have to do it right now but we should start using loggers pretty soon or we will have a hard time finding errors in the logs.

2021-02-05 15:34 UTC, tomverin commented on checklinks.py
> +      print(f"Nothing there: {url}")
sure will do

2021-02-05 15:35 UTC, tomverin commented on checklinks.py
> +      print(f"Ok: {url}")
good point, I'll integrate a logger next

2021-02-05 19:27 UTC, nicolas-harraudeau-sonarsource requested changes
It works. I just suggested a few improvements to avoid testing multiple times the same links and not using a global variable.

2021-02-08 09:30 UTC, tomverin commented on checklinks.py
> +  exit(1)
Can't find all html files since they don't already exist, they are created on the fly by the asciidoc validation process, when a file is valid, I can then test html urls against it

2021-02-12 13:46 UTC, nicolas-harraudeau-sonarsource requested changes

2021-02-12 13:46 UTC, nicolas-harraudeau-sonarsource commented on rspec-tools/rspec_tools/cli.py
> +  '''Validate rules.'''
I think we can remove this command. It was only there as an example. I can do it later if you prefer.

2021-02-12 13:46 UTC, nicolas-harraudeau-sonarsource commented on rspec-tools/tests/links/test_links.py
> +  assert len(urls) == 1
This wouldn't detect a bug where the function adds the wrong key or value to the dict. You can simply do:
```
assert urls == {'https://www.google.com/404': 'tests/links/404/404.html'}

2021-02-12 13:46 UTC, nicolas-harraudeau-sonarsource commented on rspec-tools/tests/links/test_links.py
> +  assert checklinks.live_url("https://www.google.com")
This test could break if google is down. Yes it happens rarely but we should avoid depending on external services ;)

You can mock `urlopen` and make it return whatever code you want, or even raise exceptions.
In our case it would look something like:

```python
from unittest.mock import patch

def test_url():
  url = 'https://www.mytestwebsite42.com';
  with patch('urllib.request.urlopen') as mock_urlopen:
    mock_urlopen.return_value.code = 200
    assert checklinks.live_url(url)
    mock_urlopen.assert_called_once()
    assert mock_urlopen.call_args[0][0].full_url == url
```
Same for every other test.

2021-02-12 13:53 UTC, tomverin commented on rspec-tools/rspec_tools/checklinks.py
> +      return url
iteration of the code lead me there, and I did not see any better, looks much more clear with returning False indeed

2021-02-12 13:56 UTC, tomverin commented on rspec-tools/rspec_tools/checklinks.py
> +      errors.append(result)
Indeed

2021-02-12 14:15 UTC, tomverin commented on rspec-tools/tests/links/test_links.py
> +  assert len(urls) == 1
done

2021-02-12 14:15 UTC, tomverin commented on rspec-tools/rspec_tools/cli.py
> +  '''Validate rules.'''
Done

2021-02-12 14:16 UTC, tomverin commented on rspec-tools/rspec_tools/checklinks.py
> +      return url
Done

2021-02-12 14:18 UTC, merged