Modify S1192: Migrate to LayC
SonarSource/rspec pull request #3234
Opened 2023-10-10 09:31 UTC by leonardo-pilastri-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-10 11:45 UTC, victor-diez-sonarsource requested changes

2023-10-10 11:45 UTC, victor-diez-sonarsource commented on rules/S1192/javascript/rule.adoc
> +To prevent generating some false-positives, literals having less than 3 characters are excluded as well as literals matching `/^\w*$/`.
```suggestion
To prevent generating some false-positives, literals having less than 10 characters are excluded as well as literals matching `/^\w*$/`.
```

2023-10-10 11:45 UTC, victor-diez-sonarsource commented on rules/S1192/javascript/rule.adoc
> +    prepare("action1");  // Noncompliant - "action1" is duplicated 3 times
```suggestion
    prepare("action_to_launch");  // Noncompliant - "action1" is duplicated 3 times
```
use some string with more than 10 characters, `action1` has only 7 and would not be picked up by the rule.

2023-10-10 15:08 UTC, rudy-regazzoni-sonarsource requested changes
Nice work! I believe that a few adjustments are needed, please see my comments.

2023-10-11 09:23 UTC, rudy-regazzoni-sonarsource approved these changes
LGTM! Just there is also a missing diff-id/diff-type on following language examples that I would also like to be fixed, but other than that all is good 👍 

- apex
- cobol
- go
- kotlin
- php
- plsql
- rpg
- ruby
- scala
- swift
- tsql
- vbnet

2023-10-11 09:41 UTC, merged