Modify S112: Migrate to LaYC
SonarSource/rspec pull request #3242
Opened 2023-10-10 14:21 UTC by guillaume-dequenne-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-11 14:24 UTC, frederic-tingaud-sonarsource requested changes
That's a great improvement overall!

2023-10-11 14:35 UTC, guillaume-dequenne-sonarsource commented on rules/S112/cfamily/rule.adoc
> +At best, this makes the code hard to understand and maintain. At worst, legitimate exceptions may be unintentionally silenced and errors may be hidden. For instance, if an exception such as `std::bad
For other languages, I tried to give an example of a problem that could occur when catching generic exceptions without re-throwing them (or handling them, really), but due to lack of familiarity with C++ I added this example that I didn't fully understand to be honest. Is there such a case you could recommend adding for C++?

Otherwise I'm happy to remove the example completely as suggested.

2023-10-11 14:37 UTC, zsolt-kolbay-sonarsource requested changes
Added review for C# and VB.NET

2023-10-11 14:37 UTC, zsolt-kolbay-sonarsource commented on rules/S112/csharp/rule.adoc
> +This rule raises an issue when a generic exception (such as `Exception`, `SystemException`, `ApplicationException`, `IndexOutOfRangeException`, `NullReferenceException`, `OutOfMemoryException` or `Ex
The rule isn't only about generic exceptions, it's about two categories of exceptions:
1. The exception is too generic, meaning that the type (and name) of the exception class doesn't provide any information. All we know is something bad happened. Such class is the [System.Exception](https://learn.microsoft.com/en-us/dotnet/api/system.exception) class (not the same as [System.SystemException](https://learn.microsoft.com/en-us/dotnet/api/system.systemexception)).
These classes should be used to create custom exception types and use those when throwing.
2. The exception is thrown by the runtime and should not be thrown manually by the developer. Such exception is the [System.NullReferenceException](https://learn.microsoft.com/en-us/dotnet/api/system.nullreferenceexception) or [System.OutOfMemoryException](https://learn.microsoft.com/en-us/dotnet/api/system.outofmemoryexception). These exceptions aren't generic, in fact, they are quite specific.
These exceptions should not be used as base classes and should not be thrown. Many of them indicate serious errors, such that the application might not be able to recover from.

I'd change the title to `General or reserved exceptions should not be thrown`. Then group the exceptions two these two groups in the description:
1. General exceptions:
- System.ApplicationException
- System.Exception
- System.SystemException
2. Reserved exceptions (or runtime exceptions):
- System.ExecutionEngineException
- System.IndexOutOfRangeException
- System.NullReferenceException
- System.OutOfMemoryException

This is the case for C# and VB.NET, I don't know if the rule behaves the same way for other languages. But for these two languages, it's not just about general exceptions.

2023-10-11 15:30 UTC, guillaume-dequenne-sonarsource commented on rules/S112/csharp/rule.adoc
> +This rule raises an issue when a generic exception (such as `Exception`, `SystemException`, `ApplicationException`, `IndexOutOfRangeException`, `NullReferenceException`, `OutOfMemoryException` or `Ex
As far as I understand, this rule is only about the first use case you mention for all other languages (e.g, in Java the rule would raise an issue for throwing `Exception`, but not for throwing `OutOfMemoryError`).

My gut feeling is that the second use case should probably be a different rule altogether (which would make sense to have in Java as well - I couldn't find if it already exists, but they have [S1194](https://sonarsource.github.io/rspec/#/rspec/S1194) that is related). To me, these two use cases are slightly different in the reason why they are an issue as well as their potential impact (as you highlighted), and I'm afraid merging them in a single rule might be a bit confusing from a LaYC perspective.

I know splitting a rule in 2 can't be done as easily as updating a rule description, so for now I believe it's best that I update the description to match the current implementation, but I'd encourage considering to split the use cases in 2 distinct rules to make things clearer and more consistent.

2023-10-11 15:44 UTC, guillaume-dequenne-sonarsource commented on rules/S112/cfamily/rule.adoc
> +When working with a generic type of exception, the only way to distinguish between multiple exceptions is to check their message, which is error-prone and difficult to maintain.
I agree this sentence is a bit weaker than the following paragraph. I'm not 100% sure that moving the sentence is an improvement though.

I could imagine something like this:

"
From a consumer perspective, it is generally a best practice to only catch exceptions you intend to handle. Other exceptions should ideally not be caught and let to propagate up the stack trace so that they can be dealt with appropriately. When a generic exception is thrown, it forces consumers to catch exceptions they do not intend to handle, which they then have to re-throw. Besides, when working with a generic type of exception, the only way to distinguish between multiple exceptions is to check their message, which is error-prone and difficult to maintain.

At best, this makes the code hard to understand and maintain. At worst, legitimate exceptions may be unintentionally silenced and errors may be hidden. For instance, if an exception such as `std::bad_alloc` is caught and not re-thrown, it will prevent the program from terminating gracefully.
"

Though I'm a bit annoyed by the repetition of "error-prone / difficult to maintain / hard to understand and maintain", as well as by the "wall of text" effect that could result of the loss of spacing.

Wdyt? I don't mind changing to that if you think it's more compelling this way - or I can ideate some more to formulate this a bit better.

2023-10-12 10:02 UTC, frederic-tingaud-sonarsource commented on rules/S112/cfamily/rule.adoc
> +When working with a generic type of exception, the only way to distinguish between multiple exceptions is to check their message, which is error-prone and difficult to maintain.
I like it more. Perhaps to avoid the repetition of "difficult to maintain" we could go with:
```
From a consumer perspective, it is generally a best practice to only catch exceptions you intend to handle. Other exceptions should ideally not be caught and let propagate up the stack trace so that they can be dealt with appropriately. When a generic exception is thrown, it forces consumers to catch exceptions they do not intend to handle, which they then have to re-throw.

Besides, when working with a generic type of exception, the only way to distinguish between multiple exceptions is to check their message, which is error-prone and difficult to maintain. Legitimate exceptions may be unintentionally silenced and errors may be hidden.

For instance, ...
```
WDYT?

2023-10-12 10:06 UTC, frederic-tingaud-sonarsource commented on rules/S112/cfamily/rule.adoc
> +At best, this makes the code hard to understand and maintain. At worst, legitimate exceptions may be unintentionally silenced and errors may be hidden. For instance, if an exception such as `std::bad
For instance, in the following code, the fact that `checkState` throws a generic exception leads us to catch a permission error that shouldn't have been caught:

```cpp
void openFile(File& file) {
  if (!has_permissions(file)) {
    throw std::invalid_argument("Couldn't open file");
  }
  // ...
}

void checkState(File const& file) {
  if (!file.is_valid()) {
    throw std::exception();  // Noncompliant
  }
  // ...
}

void test(File file) {
  try {
    openFile(file);
    checkState(false);
    closeFile(file);
  } catch (std::exception& s) {
    // If we don't have the correct permissions to open, the
    // invalid_argument exception will be caught and we will try closing a
    // file that was never opened
    closeFile(file);
  }
}
```

2023-10-12 15:27 UTC, guillaume-dequenne-sonarsource commented on rules/S112/cfamily/rule.adoc
>  == Resources
Thanks! I was so focused on the main part of the rule that I forgot to check the links format.

2023-10-12 15:28 UTC, guillaume-dequenne-sonarsource commented on rules/S112/cfamily/rule.adoc
> +When working with a generic type of exception, the only way to distinguish between multiple exceptions is to check their message, which is error-prone and difficult to maintain.
Thanks, that reads much better indeed. I updated all languages accordingly.

2023-10-12 15:32 UTC, guillaume-dequenne-sonarsource commented on rules/S112/cfamily/rule.adoc
> +At best, this makes the code hard to understand and maintain. At worst, legitimate exceptions may be unintentionally silenced and errors may be hidden. For instance, if an exception such as `std::bad
Thanks! I added that example to the cfamily description. I kept concise examples for other languages, as I feel they may be clear enough. Let me know if you think it would make sense to add more detailed examples in the vein of this one for other languages though.

2023-10-12 16:22 UTC, frederic-tingaud-sonarsource commented on rules/S112/cfamily/rule.adoc
> +At best, this makes the code hard to understand and maintain. At worst, legitimate exceptions may be unintentionally silenced and errors may be hidden. For instance, if an exception such as `std::bad
I'm not 100% in love with my example because it's a bit verbose compared to what I usually write in rule descriptions, so I wouldn't push to generalize it.

2023-10-13 07:34 UTC, guillaume-dequenne-sonarsource commented on rules/S112/csharp/rule.adoc
> +include::../message.adoc[]
Following clarification about the scope of the rule in C#/VBNET, I'm not sure my suggestion really makes sense as-is. However I still think the message as it is could be improved, as its tone is not consistent with other languages. Wdyt @zsolt-kolbay-sonarsource? Anyway, since the message in the specification here is not used, it would require a change on the analyzer side if you want to pursue this.

2023-10-13 09:37 UTC, zsolt-kolbay-sonarsource approved these changes
LGTM

2023-10-13 09:37 UTC, zsolt-kolbay-sonarsource commented on rules/S112/csharp/rule.adoc
> +* Throw a subtype of `Exception` when one matches. For instance ``++InvalidArgumentException++`` could be raised when an unexpected argument is provided to a function.
```suggestion
* Throw a subtype of `Exception` when one matches. For instance ``++ArgumentException++`` could be raised when an unexpected argument is provided to a function.
```

2023-10-13 09:53 UTC, zsolt-kolbay-sonarsource commented on rules/S112/csharp/rule.adoc
> +include::../message.adoc[]
I think that's fine. The C# and VB.NET analyzers are covering an additional scenario (reserved exceptions), but to me, that falls into the scope of the rule (do not throw specific types of exceptions).

2023-10-13 12:57 UTC, merged