Modify S1066: Migrate to LayC - merge if
SonarSource/rspec pull request #3260
Opened 2023-10-11 17:58 UTC by frederic-tingaud-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-12 14:03 UTC, petertrr requested changes
Please see my few comments. I wonder what's the motivation to keep [non]compliant examples in the `Why is this an issue` section and not in the `How to fix it` section?

2023-10-12 16:16 UTC, frederic-tingaud-sonarsource commented on rules/S1066/description.adoc
> +Nested code - blocks of code inside blocks of code - is eventually necessary, but increases complexity. https://peps.python.org/pep-0020/[The Zen of Python], a text listing the Python philosophies, s
Changed. What do you think of that one?

2023-10-12 16:16 UTC, frederic-tingaud-sonarsource commented on rules/S1066/noncompliant.adoc
> +[source,java]
It is shared between Java and Kotlin, which have very similar syntax.

2023-10-13 07:37 UTC, zsolt-kolbay-sonarsource commented
Please change the title of the rule to `Mergeable "if" statements should be combined`
The change comes from the review and discussion on the _Clean Code for Dummies_ book.
I'll also add @ganncamp as a reviewer.

2023-10-13 08:47 UTC, petertrr commented on rules/S1066/cfamily/rule.adoc
> +  if (file.isFile() || file.isDirectory()) {   // Noncompliant
I suspect that this looks more like Java code than like C++ handling of files. For example, `file.isDirectory()` could be `std::filesystem::is_directory(path)`. I would suggest to adapt these examples.

2023-10-13 08:53 UTC, petertrr commented on rules/S1066/csharp/rule.adoc
> +=== Noncompliant code example
I believe, there should be a level 3 heading `=== Code examples` and then Noncompliant and Compliant should be level 4

2023-10-13 11:21 UTC, ganncamp approved these changes

2023-10-13 17:32 UTC, frederic-tingaud-sonarsource commented on rules/S1066/cfamily/rule.adoc
> +  if (file.isFile() || file.isDirectory()) {   // Noncompliant
That's still a kind of API you can find regularly, but I switched to a condensed STL code.

2023-10-13 17:32 UTC, frederic-tingaud-sonarsource commented on rules/S1066/csharp/rule.adoc
> +=== Noncompliant code example
Thanks, fixed

2023-10-16 08:23 UTC, petertrr approved these changes
LGTM, see my final suggestion about Python

2023-10-16 08:23 UTC, petertrr commented on rules/S1066/python/rule.adoc
> +  if file.isFile() or file.isDirectory():     # Noncompliant
More pythonic example, AFAIU, would be with [os.path](https://docs.python.org/3/library/os.path.html#os.path.isdir) methods:
```suggestion
  if file.isfile() or file.isdir():     # Noncompliant
```

2023-10-16 09:46 UTC, merged