Modify S117: Migrate to LaYC - WIP
SonarSource/rspec pull request #3263
Opened 2023-10-12 08:13 UTC by nicolas-gauthier-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-16 08:22 UTC, ADarko22 requested changes

2023-10-16 08:22 UTC, ADarko22 commented on rules/S117/what-is-the-potential-impact.adoc
> +Difficulty in Identifying Variables: If {identifier_plural} are not named according to a standard convention, it can be challenging to identify them quickly. It can slow the coding process, especiall
```suggestion
* Difficulty in Identifying Variables: {identifier_plural} that don't adhere to a standard naming convention are challenging to identify, thus the coding process slows down, especially when dealing with a large codebase.
```

similarly to the previous: use bullet points and reword to use an affirmative tone instead of hypothetical (i.e. "can"); do you agree?

2023-10-16 08:22 UTC, ADarko22 commented on rules/S117/what-is-the-potential-impact.adoc
> +Increased Risk of Errors: Inconsistent or unclear {identifier} names can lead to misunderstandings about what the variable represents. This ambiguity can lead to incorrect assumptions and, consequent
```suggestion
* Increased Risk of Errors: inconsistent or unclear {identifier} names lead to misunderstandings about what the variable represents. This ambiguity leads to incorrect assumptions and, consequently, bugs in the code.
```

2023-10-16 08:22 UTC, ADarko22 commented on rules/S117/what-is-the-potential-impact.adoc
> +Difficulty in Code Maintenance: Inconsistent naming can lead to an inconsistent codebase. The code can be difficult to understand, and making changes might feel like refactoring all the time, as you
```suggestion
* Difficulty in Code Maintenance: inconsistent naming leads to an inconsistent codebase. The code is difficult to understand, and making changes feels like refactoring all the time, as you face different naming methods. Ultimately, it makes the codebase harder to maintain.
```

2023-10-16 08:22 UTC, ADarko22 commented on rules/S117/java/rule.adoc
>  }
```suggestion
public class MyClass {
    public void doSomething(int myParam) {
      int LOCAL;    // Noncompilant
      // ...
    }
}
```

2023-10-16 08:23 UTC, ADarko22 commented
Great job! The work done on this rspec is impressive!

2023-10-16 08:49 UTC, nicolas-gauthier-sonarsource commented on rules/S117/what-is-the-potential-impact.adoc
> +Reduced Readability: When {identifier} names are inconsistent, it can make the code harder to read and understand, making it more difficult to identify the purpose of each variable, spot errors, or c
I like your rewording, and the bullet points are a good idea!

2023-10-16 08:50 UTC, nicolas-gauthier-sonarsource commented on rules/S117/java/rule.adoc
>  }
With pleasure! Thanks!

2023-10-17 07:28 UTC, ADarko22 commented
Great! I verified for Java the rendering in SQ and it's amazing! Well done!

2023-10-17 07:28 UTC, ADarko22 approved these changes

2023-10-17 07:45 UTC, merged