Modify S1125: migrate to LayC
SonarSource/rspec pull request #3265
Opened 2023-10-12 09:10 UTC by leonardo-pilastri-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-12 10:03 UTC, ADarko22 approved these changes

2023-10-12 10:05 UTC, ADarko22 commented
It looks good :)
I was wondering if adding some resources may be helpful, for instance, a link to what are boolean literals or to boolean expressions.

2023-10-12 12:50 UTC, ADarko22 requested changes

2023-10-12 14:05 UTC, leonardo-pilastri-sonarsource commented on rules/S1125/description.adoc
> +Boolean literals are used in logical expressions to represent truth values.
I don't know if it is possible to add a general definition for all languages, I wanted to avoid having to specify many different versions of that definition as it should be common among developers, and you could still infer it from the code examples in the different languages

2023-10-13 10:29 UTC, ADarko22 approved these changes

2023-10-13 11:50 UTC, merged