Modify rule S116: Migrate to LayC - Field names should comply with a naming convention
SonarSource/rspec pull request #3266
Opened 2023-10-12 09:35 UTC by ADarko22

2023-10-12 09:45 UTC, ADarko22 commented on rules/S116/csharp/rule.adoc
> +* Microsoft - https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines[.NET Naming Guidelines]
is this reference relevant?

2023-10-12 09:46 UTC, ADarko22 commented on rules/S116/flex/rule.adoc
> +* Wikipedia - https://en.wikipedia.org/wiki/Naming_convention_(programming)[Naming Convention (programming)]
could not find any specific documentation for FLEX

2023-10-12 09:46 UTC, ADarko22 commented on rules/S116/php/rule.adoc
> +* php.net - https://www.php.net/manual/en/userlandnaming.rules.php[Userland Naming Guide]
is this reference valid?

2023-10-12 09:46 UTC, ADarko22 commented on rules/S116/swift/rule.adoc
> +* Swift - https://www.swift.org/documentation/api-design-guidelines/#naming[API Design Guidelines - Naming]
are the references valid?

2023-10-12 13:02 UTC, frederic-tingaud-sonarsource requested changes
What would you think about having the code samples in the first tab? Given how straightforward this all is, I think that would work better.

2023-10-12 13:02 UTC, frederic-tingaud-sonarsource commented on rules/S116/cfamily/rule.adoc
> +== How to fix it
The description is short and the code examples are super straightforward. I think just having the code samples in "Why is this an issue?" would be simpler.

2023-10-12 13:02 UTC, frederic-tingaud-sonarsource commented on rules/S116/cfamily/rule.adoc
>    int my_field;
```suggestion
  int my_field; // Noncompliant
```

2023-10-12 13:02 UTC, frederic-tingaud-sonarsource commented on rules/S116/cfamily/rule.adoc
>    int myField;
```suggestion
  int myField;  // Compliant
```

2023-10-12 13:45 UTC, renaud-tognelli-sonarsource commented on rules/S116/csharp/rule.adoc
> +* Microsoft - https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines[.NET Naming Guidelines]
It gives weight to the rule.
Maybe point it directly to the field name convention, wdyt?
https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-fields

2023-10-12 13:55 UTC, renaud-tognelli-sonarsource commented on rules/S116/php/rule.adoc
> +* php.net - https://www.php.net/manual/en/userlandnaming.rules.php[Userland Naming Guide]
There is not much about fields here, it is a bit misleading I would say.

2023-10-12 13:55 UTC, renaud-tognelli-sonarsource commented on rules/S116/swift/rule.adoc
> +* Swift - https://www.swift.org/documentation/api-design-guidelines/#naming[API Design Guidelines - Naming]
same here

2023-10-12 14:26 UTC, ADarko22 commented on rules/S116/php/rule.adoc
> +* php.net - https://www.php.net/manual/en/userlandnaming.rules.php[Userland Naming Guide]
True, but it still brings some value to an user who wants to dig into the topic

2023-10-12 15:32 UTC, frederic-tingaud-sonarsource requested changes

2023-10-12 15:32 UTC, frederic-tingaud-sonarsource commented on rules/S116/cfamily/rule.adoc
> +=== Code examples
If we put the code in "Why is this an issue", we don't need the subtitles.

```
include::../description.adoc[]

For example with the following regular expression ``++^[a-z][a-zA-Z0-9]*$++``:

[source,cpp,diff-id=1,diff-type=noncompliant]
----
class MyClass {
  int my_field; // Noncompliant
};
----

Should be replaced with:

[source,cpp,diff-id=1,diff-type=compliant]
----
class MyClass {
  int myField;  // Compliant
};
----
```

2023-10-13 07:57 UTC, frederic-tingaud-sonarsource approved these changes

2023-10-13 08:06 UTC, merged