Modify S1117: Migrate To LayC - shadow variables
SonarSource/rspec pull request #3270
Opened 2023-10-12 12:50 UTC by marco-antognini-sonarsource

The languages for this rule fall into two categories:

 * CFamily, JS, and PLSQL: "Variables should not be shadowed" (general case of shadowing)
 * C#, Flex, Java, PHP, Swift: "Local variables should not shadow field/property/enum case/..." (narrow case of shadowing)

For CFamily, these tickets are also handled: CPP-2785 CPP-3589

## Review

A dedicated reviewer checked the rule description successfully for:

- [x] logical errors and incorrect information
- [x] information gaps and missing content
- [x] text style and tone
- [x] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-13 17:12 UTC, frederic-tingaud-sonarsource requested changes
That's a big rewritting! Kudos for that!

2023-10-13 17:12 UTC, frederic-tingaud-sonarsource commented on rules/S1117/cfamily/rule.adoc
> +  void illFormed() {
If I understand correctly, this ill-formed code is here to "prove" that it is not really a shadowing?
I think for this the text below is enough and in the time between reading that code and reading the explanation, I was confused as to the goal of the sample.

2023-10-13 17:12 UTC, frederic-tingaud-sonarsource commented on rules/S1117/cfamily/rule.adoc
> +=== Pitfalls
The section "Pitfalls" is usually in "How to fix it". I think we could have a more appropriate name for this specific section.
Perhaps "Notable cases"?

2023-10-13 18:34 UTC, yassin-kammoun-sonarsource approved these changes

2023-10-13 18:34 UTC, yassin-kammoun-sonarsource commented on rules/S1117/javascript/rule.adoc
> +Note that variables can also shadow functions.
👍

2023-10-13 18:34 UTC, yassin-kammoun-sonarsource commented on rules/S1117/javascript/rule.adoc
> +  let nested = function(items) { // Noncompliant: the parameter "items" is shadowed.
```suggestion
  function inner(items) { // Noncompliant: the parameter "items" is shadowed.
```

2023-10-13 18:34 UTC, yassin-kammoun-sonarsource commented on rules/S1117/javascript/rule.adoc
> +Note that variables can also shadow functions.
```suggestion
Note that functions in JavaScript are first-class citizens. This means that they possess the same attributes as variables, including the ability to shadow other variables and, conversely, be shadowed by them. 
```

2023-10-13 18:34 UTC, yassin-kammoun-sonarsource commented on rules/S1117/javascript/rule.adoc
> +function example(items) {
```suggestion
function outer(items) {
```

2023-10-13 18:34 UTC, yassin-kammoun-sonarsource commented on rules/S1117/javascript/rule.adoc
> +  nested(items);
```suggestion
  inner(items);
```

2023-10-16 06:15 UTC, marco-antognini-sonarsource commented on rules/S1117/swift/rule.adoc
> +To avoid these problems, rename the shadowing, shadowed, or both variables/fields/``enum case``s to accurately represent their purpose with unique and meaningful names.
I agree the current wording isn't great. From a grammar point of view, "shadowing" and "shadowed" are synonyms so I need to put a noun somewhere. Maybe this is better?
```suggestion
To avoid these problems, rename the shadowing, shadowed, or both identifiers to accurately represent their purpose with unique and meaningful names.
```

2023-10-16 06:24 UTC, marco-antognini-sonarsource commented on rules/S1117/cfamily/rule.adoc
> +=== Pitfalls
I'm fine to rename it.

I can't really put my finger on why, but "Notable cases" sounds strange... It doesn't convey the notion of trickyness.

Maybe "Caveats"?

2023-10-16 06:26 UTC, marco-antognini-sonarsource commented on rules/S1117/cfamily/rule.adoc
> +    << e.error().message() << std::endl; // Ups, I mean previous e here
It's a pitfall in the primary sense of this rule: because of the shadowing, a mistake was made. I quite like it for this reason.

I'll think of a different wording to make this more obvious.

2023-10-16 06:30 UTC, marco-antognini-sonarsource commented on rules/S1117/why-fields.adoc
> +It improves clarity and allows reasoning locally about the code without considering other software parts.
The sentence applies to the other case. When you rename the local variable to keep using it instead of the global, you can reason about the code without considering more than the current scope. But I see your point; it doesn't bring much except maybe confusion.

2023-10-16 06:31 UTC, marco-antognini-sonarsource commented on rules/S1117/why-fields.adoc
> +To avoid these problems, rename the shadowing, shadowed, or both variables/fields to accurately represent their purpose with unique and meaningful names.
Ditto, WDYT of 
```suggestion
To avoid these problems, rename the shadowing, shadowed, or both identifiers to accurately represent their purpose with unique and meaningful names.
```

2023-10-16 06:31 UTC, marco-antognini-sonarsource commented on rules/S1117/why-general.adoc
> +It improves clarity and allows reasoning locally about the code without considering other software parts.
```suggestion
```

2023-10-16 06:59 UTC, marco-antognini-sonarsource commented on rules/S1117/cfamily/rule.adoc
> +
Applied in 20ae6dbbb9. I used continuations to indent the example. Otherwise, the (small) bullet points are more hidden I think. Let me know what you think of it.

2023-10-16 06:59 UTC, marco-antognini-sonarsource commented on rules/S1117/cfamily/rule.adoc
Applied in 20ae6dbbb9.

2023-10-16 06:59 UTC, marco-antognini-sonarsource commented on rules/S1117/cfamily/rule.adoc
Applied in 20ae6dbbb9.

2023-10-16 07:13 UTC, marco-antognini-sonarsource commented on rules/S1117/cfamily/rule.adoc
> +    << e.error().message() << std::endl; // Ups, I mean previous e here
I thought a bit more about it and I disagree with my 46-minute-past self.

2023-10-16 07:22 UTC, frederic-tingaud-sonarsource commented on rules/S1117/cfamily/rule.adoc
> +=== Pitfalls
Caveats sound great!

2023-10-16 07:22 UTC, frederic-tingaud-sonarsource commented on rules/S1117/swift/rule.adoc
> +To avoid these problems, rename the shadowing, shadowed, or both variables/fields/``enum case``s to accurately represent their purpose with unique and meaningful names.
Works for me.

2023-10-16 07:45 UTC, marco-antognini-sonarsource commented on rules/S1117/cfamily/rule.adoc
> +=== Pitfalls
```suggestion
=== Caveats
```

2023-10-16 08:03 UTC, marco-antognini-sonarsource commented on rules/S1117/cfamily/rule.adoc
> +  void illFormed() {
Good point. I improved the section in a3acd1e93d.

2023-10-16 08:04 UTC, marco-antognini-sonarsource commented on rules/S1117/cfamily/rule.adoc
> +    << e.error().message() << std::endl; // Ups, I mean previous e here
I improved the section in 6f12ba791e.

2023-10-16 09:54 UTC, frederic-tingaud-sonarsource approved these changes

2023-10-16 10:04 UTC, merged