Modify S4649: Migrate to LayC
SonarSource/rspec pull request #3272
Opened 2023-10-12 13:29 UTC by victor-diez-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-12 14:33 UTC, petertrr requested changes
Nice enhancement of the text! Please see a couple of my suggestions

2023-10-12 14:33 UTC, petertrr commented on rules/S4649/css/rule.adoc
> +If none of the font names defined in a ``++font++`` or ``++font-family++`` declaration are available on the browser of the user, the browser will display the text using its default font. It's recomme
I think here and below using double backticks with plus signs is not essential and single backticks will suffice

2023-10-12 14:33 UTC, petertrr commented on rules/S4649/css/rule.adoc
> +You should always include at least one generic family name in a font-family list, since there's no guarantee that any given font is available.
I suggest to move this text to the start of `How to fix it` section before `Code examples`

2023-10-12 14:33 UTC, petertrr commented on rules/S4649/css/rule.adoc
> +* MDN - https://developer.mozilla.org/en-US/docs/Web/CSS/font[``++font++``]
Why have you removed the conditional section `ifdef::env-github,rspecator-view[]`?

2023-10-12 14:35 UTC, victor-diez-sonarsource commented on rules/S4649/css/rule.adoc
> +If none of the font names defined in a ``++font++`` or ``++font-family++`` declaration are available on the browser of the user, the browser will display the text using its default font. It's recomme
true, no special chars, I always use the full non-escaping by default. I'll change that

2023-10-12 14:36 UTC, victor-diez-sonarsource commented on rules/S4649/css/rule.adoc
> +* MDN - https://developer.mozilla.org/en-US/docs/Web/CSS/font[``++font++``]
that section is legacy containing comments from changes in the past. it was mentioned that if it did not contain valuable information it could be safely removed.

2023-10-12 14:43 UTC, petertrr commented on rules/S4649/css/rule.adoc
> +* MDN - https://developer.mozilla.org/en-US/docs/Web/CSS/font[``++font++``]
What about the `Message` section? I think it's still valuable, as the rspec is source of truth for the analyzer

2023-10-12 14:45 UTC, victor-diez-sonarsource commented on rules/S4649/css/rule.adoc
> +* MDN - https://developer.mozilla.org/en-US/docs/Web/CSS/font[``++font++``]
let me ask that in the slack channel

2023-10-13 09:30 UTC, petertrr approved these changes
LGTM
I think it can be merged now, even if the discussion about message may continue

2023-10-13 09:31 UTC, merged