Modify S1774: Migrate to LayC - remove ternary expression
SonarSource/rspec pull request #3288
Opened 2023-10-16 12:17 UTC by rudy-regazzoni-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-16 14:18 UTC, frederic-tingaud-sonarsource commented on rules/S1774/cfamily/rule.adoc
> +== How to fix it
The rule is very short and straightforward. I think having to change the tab to see the code sample reduces legibility.

2023-10-18 09:17 UTC, rudy-regazzoni-sonarsource commented on rules/S1774/cfamily/rule.adoc
> +== How to fix it
Mmhh, indeed that makes sense. I tried to simply remove the `How to fix it` section and to put examples directly in the `Why is this an issue?`, it seems to pass the test, I will go that way.

2023-10-18 09:54 UTC, frederic-tingaud-sonarsource requested changes

2023-10-18 09:54 UTC, frederic-tingaud-sonarsource commented on rules/S1774/cfamily/rule.adoc
> +=== Exceptions
Could you move this section after the code samples?

2023-10-18 09:54 UTC, frederic-tingaud-sonarsource commented on rules/S1774/cfamily/rule.adoc
> +[source,cpp,diff-id=1,diff-type=noncompliant]
```suggestion
[source,cpp]
```
The whole block will be different, diff view doesn't really help in that case.

2023-10-19 07:26 UTC, frederic-tingaud-sonarsource approved these changes

2023-10-19 08:28 UTC, merged