Modify S3457: Migrate to LayC - `printf`-style format string are misused
SonarSource/rspec pull request #3305
Opened 2023-10-17 08:44 UTC by petertrr

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-17 12:09 UTC, zsolt-kolbay-sonarsource requested changes
Nice work! Left some polishing comments.

2023-10-17 12:09 UTC, zsolt-kolbay-sonarsource commented on rules/S3457/csharp/rule.adoc
> +
Add the following:

```
Use https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/string-interpolation[string interpolation] when possible. 

Instead of 

[source,csharp]
----
string str = string.Format("Hello {0} {1}!", firstName, lastName); 
----

use

[source,csharp]
----
string str = $"Hello {firstName} {lastName}!"; 
----

With string interpolation:

* the arguments are evulated/validated at compilation time rather than runtime
* modern code editors provide auto-completion when typing the interpolation expression
```

2023-10-17 12:09 UTC, zsolt-kolbay-sonarsource commented on rules/S3457/csharp/rule.adoc
> +A composite format string is a string that contains placeholders, represented by indices inside curly braces "{0}", "{1}", etc. These placeholders are replaced by values when the string is printed or
```suggestion
A [composite format string](https://learn.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting) is a string that contains placeholders, represented by indices inside curly braces "{0}", "{1}", etc. These placeholders are replaced by values when the string is printed or logged.
```

2023-10-17 12:09 UTC, zsolt-kolbay-sonarsource commented on rules/S3457/csharp/rule.adoc
> +* No issue is raised if the format string is not a `const`.
```suggestion
* No issue is raised if the format string is not a string literal, but comes from a variable.
```

2023-10-17 12:09 UTC, zsolt-kolbay-sonarsource commented on rules/S3457/csharp/rule.adoc
> +var res = string.Format(pattern, 1, 2);
```suggestion
var res = string.Format(pattern, 1, 2); // Incorrect, but the analyzer doesn't raise any warnings here
```

2023-10-17 12:09 UTC, zsolt-kolbay-sonarsource commented on rules/S3457/cfamily/rule.adoc
> +Starting with C++20, `std::format` should be preferred, as it is more readable and validated at compile-time, making it more secure. The rule S6494 covers that.
```suggestion
Starting with C++20, `std::format` should be preferred, as it is more readable and validated at compile-time, making it more secure. Rule S6494 covers that.
```

2023-10-17 14:46 UTC, frederic-tingaud-sonarsource requested changes
Some changes for the C++ version of the rule. I didn't look at the other languages as they are very different from each others and I don't have the expertise.

2023-10-17 14:46 UTC, frederic-tingaud-sonarsource commented on rules/S3457/cfamily/rule.adoc
> +https://en.cppreference.com/w/c/io/fprintf[`printf`] format strings contain placeholders, represented by special characters such as "%s". These placeholders are replaced by values when the string is
```suggestion
https://en.cppreference.com/w/c/io/fprintf[`printf`] format strings contain placeholders, represented by special characters such as "%s". These placeholders are replaced at runtime with values.
```

2023-10-17 14:46 UTC, frederic-tingaud-sonarsource commented on rules/S3457/cfamily/rule.adoc
```suggestion

Detected problems are:

* Unused arguments
+
[source,cpp]
----
printf("Numbers: %d", 1, 2); // Noncompliant: the second argument "2" is unused
----

* Ignored flags
+
[source,cpp]
----
printf("Formatted number: %0-f", 1.2); // Noncompliant: flag "0" is ignored because of "-"
----
```

2023-10-17 14:46 UTC, frederic-tingaud-sonarsource commented on rules/S3457/cfamily/rule.adoc
> +printf("Formatted number: %-0f", 1.2);
```suggestion
printf("Formatted number: %-f", 1.2);
```

2023-10-17 14:46 UTC, frederic-tingaud-sonarsource commented on rules/S3457/cfamily/rule.adoc
> +
```suggestion

With `std::format` and `std::print`

[source,cpp]
----
std::print("Numbers: {} {}", 1, 2);
std::print("Formatted number: {:f}", 1.2);
----

With `printf`:

```

2023-10-18 06:47 UTC, zsolt-kolbay-sonarsource approved these changes
LGTM. Left some minor comments to address before you merge.

2023-10-18 06:47 UTC, zsolt-kolbay-sonarsource commented on rules/S3457/java/rule.adoc
> +* logging methods of `org.slf4j.Logger`, `java.util.logging.Logger`, `org.apache.logging.log4j.Logger`.
Add links to the documentation of these types as well.

2023-10-18 06:47 UTC, zsolt-kolbay-sonarsource commented on rules/S3457/csharp/rule.adoc
> +This rule validates the correspondence between arguments and composite formats when calling the methods of `String.Format`, `StringBuilder.AppendFormat`, `Console.Write`, `Console.WriteLine`, `TextWr
Reorganize this into bullet points with links to the documentation of each method on _learn.microsoft.com_, the same way you did with the Java spec.

2023-10-18 13:23 UTC, frederic-tingaud-sonarsource approved these changes
Just a missing linebreak.

2023-10-18 13:23 UTC, frederic-tingaud-sonarsource commented on rules/S3457/cfamily/rule.adoc
> +This rule will only work if the format string is provided as a string literal.
```suggestion

This rule will only work if the format string is provided as a string literal.
```
My previous suggestion was missing a linebreak here.

2023-10-18 13:35 UTC, merged