Modify S1118: migrate to LayC
SonarSource/rspec pull request #3308
Opened 2023-10-17 09:03 UTC by leonardo-pilastri-sonarsource

2023-10-17 13:16 UTC, zsolt-kolbay-sonarsource requested changes
Almost there. Left a few remarks to clean up.

2023-10-17 13:16 UTC, zsolt-kolbay-sonarsource commented on rules/S1118/csharp/rule.adoc
> +public class StringUtils // Compliant: the constructor is not public
Why is the constructor `protected` instead of `private`? The `protected` keyword is used when inheritance is involved, and I don't see any reason why a class with only static methods will be part of any class hierarchy.

2023-10-17 13:16 UTC, zsolt-kolbay-sonarsource commented on rules/S1118/csharp/rule.adoc
> +:lang: C#
Where is the `lang` template parameter used?

2023-10-17 13:16 UTC, zsolt-kolbay-sonarsource commented on rules/S1118/csharp/rule.adoc
> +include::../howtofix.adoc[]
C# and Java behaves somewhat differently regarding static classes:
- In Java defining an inner class as static means it will not be bound to any instance of the containing class (it cannot access its instance variables), but it can still be instantiated and works like a regular class. So whether a class in Java is static or not doesn't make a difference for this rule.
- In C# a class marked with the static keyword cannot be instantiated and can only have static members. This is relevant to the C# implementation of the rule and should be added to the `How to fix it` section. (there's already a code sample in the `Compliant solution` section, so you only need to mention it without any additional code).

2023-10-17 13:58 UTC, leonardo-pilastri-sonarsource commented on rules/S1118/csharp/rule.adoc
> +:lang: C#
In the `howtofix.adoc` file, which is shared, I mention the specific language adds implicitly a public constructor to classes, and I wanted to mention the language name there. Let me know if it makes sense to you

2023-10-17 14:14 UTC, zsolt-kolbay-sonarsource commented on rules/S1118/howtofix.adoc
> +To prevent the class from being instantiated, you should define at least one non-public constructor
```suggestion
To prevent the class from being instantiated, you should define a non-public constructor. This will prevent the compiler from implicitly generating a public parameterless constructor.
```

2023-10-17 14:16 UTC, zsolt-kolbay-sonarsource commented on rules/S1118/csharp/rule.adoc
> +:lang: C#
It sounds good to me. Personally I wouldn't use it, I would just rewrite the _How to fix it_ [like this](https://github.com/SonarSource/rspec/pull/3308#discussion_r1362199040) just to make the adoc files a little shorter. 
But I don't have a strong opinion on it. I'll leave it up to you.

2023-10-18 06:38 UTC, zsolt-kolbay-sonarsource approved these changes
LGTM

2023-10-18 06:38 UTC, zsolt-kolbay-sonarsource commented on rules/S1118/csharp/rule.adoc
> +Or the `static` keyword should be added to the class declaration to prevent inheriting it.
```suggestion
Alternatively adding the `static` keyword as class modifier will also prevent it from being instantiated.
```

Yes, a static class is sealed by definition, but the focus isn't inheritance here, it's instantiation.

2023-10-18 08:16 UTC, merged