Modify S3252: Migrate to LayC - "static" base class members should not be accessed via derived types
SonarSource/rspec pull request #3310
Opened 2023-10-17 11:45 UTC by petertrr

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-17 14:12 UTC, frederic-tingaud-sonarsource requested changes

2023-10-17 14:16 UTC, petertrr commented on rules/S3252/how-to-fix-it.adoc
> +Accessing static members of a base class via derived types is a common code smell in object-oriented programming. This practice can cause confusion as it incorrectly implies that the static member is
In the guidelines, we have 

> Before you move to the “Why is this an issue” and “How to fix it?” sections, make sure that their content will be independent and it will make sense even if the developer reads the 'How to fix it' section first or doesn't read the 'Why is this an issue' section at all.

So I'm duplicating the text a bit to address this requirement

2023-10-17 15:33 UTC, frederic-tingaud-sonarsource commented on rules/S3252/how-to-fix-it.adoc
> +Accessing static members of a base class via derived types is a common code smell in object-oriented programming. This practice can cause confusion as it incorrectly implies that the static member is
I see. Don't you think it would qualify to have all in "Why is this an issue?"?
I find the description without a code sample to be complicated and the fix to be straightforward.

2023-10-18 12:24 UTC, frederic-tingaud-sonarsource approved these changes

2023-10-18 12:29 UTC, merged