Validate asciidoc ifdef/endif
SonarSource/rspec pull request #3311
Opened 2023-10-17 11:52 UTC by marco-antognini-sonarsource

This check is slow. Therefore, it is only done on modified rules.

2023-10-17 16:16 UTC, frederic-tingaud-sonarsource requested changes

2023-10-17 16:16 UTC, frederic-tingaud-sonarsource commented on ci/asciidoc_validation/validate_environment.py
> +                self._process_close(line_index + 1, line)
I don't see a check that the env is closed at the end. Am I missing something?

2023-10-17 16:16 UTC, frederic-tingaud-sonarsource commented on ci/validate_asciidoc.sh
> +      >validate_env_commands 2>&1
This might be quite slow because Python is expensive to launch. I would recommend to output find in a file and then feed this file to the Python script. That way we only launch the Python script once even for a tooling change.

2023-10-18 06:28 UTC, marco-antognini-sonarsource commented on ci/asciidoc_validation/validate_environment.py
> +                self._process_close(line_index + 1, line)
🤦 thanks for pointing this out!

2023-10-18 07:27 UTC, marco-antognini-sonarsource commented on ci/validate_asciidoc.sh
> +      >validate_env_commands 2>&1
Indeed, from 12 minutes down to 8. Nicely spotted.

2023-10-18 08:53 UTC, frederic-tingaud-sonarsource approved these changes

2023-10-18 09:43 UTC, merged