Modify S1871: Migrate To LayC
SonarSource/rspec pull request #3315
Opened 2023-10-17 15:05 UTC by victor-diez-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [x] logical errors and incorrect information
- [x] information gaps and missing content
- [x] text style and tone
- [x] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-19 14:33 UTC, frederic-tingaud-sonarsource requested changes
I'd like to keep the current wording of the Exception for CFamily.

Also a small detail: we probably don't need the `{language}` in the source tags. We share the code samples between languages because they share the same keywords. I expect the syntax coloring to be the same no matter the value of `{language}`.

2023-10-19 14:33 UTC, frederic-tingaud-sonarsource commented on rules/S1871/common/exceptions.adoc
> +=== Exceptions
I find this exception very hard to parse. It has exceptions inside the exception inside the exception!

I spent some time changing that with what is currently the cfamily rule, where the exception to the exception is presented as part of the rule:

> (inside the rule)
> When all blocks are identical, either this rule will trigger if there is no default clause or rule [S3923](https://sonarsource.github.io/rspec#/rspec/S3923) will raise if there is a default clause.
>
> Exceptions
> Unless all blocks are identical, blocks in an if chain that contain a single line of code are ignored. The same applies to blocks in a switch statement that contains a single line of code with or without a following break. 
> [Code sample]

I would prefer if you kept that at least for CFamily.

(my opinion is that this rule is so complex to explain because it should never have been split like that from S3923)

2023-10-19 14:46 UTC, victor-diez-sonarsource commented on rules/S1871/common/exceptions.adoc
> +=== Exceptions
good catch, I think this was a copy/paste error, as none of the langs using `common/exceptions.adoc` had that exception of the exception, as you put it.

2023-10-19 14:47 UTC, victor-diez-sonarsource commented on rules/S1871/common/exceptions.adoc
> +=== Exceptions
as for the language var, I agree is an overkill, but as I put it in each lang rule.adoc, I thought it was a good idea to use it, even if all 4 common languages share the syntax

2023-10-20 07:36 UTC, yassin-kammoun-sonarsource approved these changes
Kudos for the tremendous work!

2023-10-20 07:36 UTC, yassin-kammoun-sonarsource commented on rules/S1871/swift/compliant.adoc
> +* in an `if` structure they should be combined
```suggestion
* in an `if` statement, they should be merged.
```

2023-10-20 07:36 UTC, yassin-kammoun-sonarsource commented on rules/S1871/swift/exceptions.adoc
> +if a >= 0 && a < 10 {     //Noncompliant, this might have been done on purpose but probably not
```suggestion
if a >= 0 && a < 10 {     // Noncompliant, this might have been done on purpose but probably not
```

2023-10-20 07:36 UTC, yassin-kammoun-sonarsource commented on rules/S1871/swift/exceptions.adoc
> +if a >= 0 && a < 10 {    //no issue, usually this is done on purpose to increase the readability
```suggestion
if a >= 0 && a < 10 {    // no issue, usually this is done on purpose to increase the readability
```

2023-10-20 07:36 UTC, yassin-kammoun-sonarsource commented on rules/S1871/swift/exceptions.adoc
> +
```suggestion

```

2023-10-20 07:49 UTC, victor-diez-sonarsource commented on rules/S1871/common/exceptions.adoc
> +=== Exceptions
ok, there is already a link to it in related rules, but I will add the explanation in compliant.adoc. Do you think I should do that in all langs? Many had the "exception of the exception" mentioned

2023-10-20 07:50 UTC, nicolas-gauthier-sonarsource reviewed
My comments for ABAP
Very Minor PS: There are two empty lines at the end of root `comments-and-links.adoc`, `highlighting.adoc` and `message.adoc`; one could be removed

2023-10-20 07:50 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/abap/compliant.adoc
> +----
I checked the repository and Google to find what should be the compliant example of the second case:
```suggestion
----

[source,abap,diff-id=2,diff-type=compliant]
----
CASE i.
  WHEN 1 OR 3.
    doFirst.
    doSomething.
  WHEN 2.
    doSomethingDifferent.
  WHEN OTHERS.
    doTheRest.
ENDCASE.
----

```

2023-10-20 07:50 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/abap/description.adoc
> +Having two ``++WHEN++`` in a ``++CASE++`` statement or two branches in an ``++IF++`` chain  with the same implementation is at best duplicate code, and at worst a coding error.
There is no special character, we can simplify to:
```suggestion
Having two `WHEN` in a `CASE` statement or two branches in an `IF` chain  with the same implementation is at best duplicate code, and at worst a coding error.
```

2023-10-20 07:50 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/abap/exceptions.adoc
> +Blocks in an ``++IF++`` chain or in ``++CASE++`` statement that contain a single line of code are ignored.
Can be simplified:
```suggestion
Blocks in an `IF` chain or in `CASE` statement that contain a single line of code are ignored.
```

2023-10-20 07:50 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/abap/exceptions.adoc
> +But this exception does not apply to ``++IF++`` chains without final ``++ELSE++``-s, or to ``++CASE++``-s without ``++WHEN OTHERS++`` clauses when all branches have the same single line of code. In c
Can be simplified:
```suggestion
But this exception does not apply to `IF` chains without final `ELSE`-s, or to `CASE`-s without `WHEN OTHERS` clauses when all branches have the same single line of code. In case of `IF` chains with `ELSE`-s, or of `CASE`-s with `WHEN OTHERS` clauses, rule S3923 raises a bug. 
```

2023-10-20 07:50 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/abap/exceptions.adoc
> +endif.
To keep the same uppercasing in all examples:
```suggestion
IF a >= 0 AND a < 10. //Noncompliant, this might have been done on purpose but probably not
  doTheThing.
ELSEIF a >= 10 AND a < 20.
  doTheThing.
ENDIF.
```

2023-10-20 07:50 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/abap/noncompliant.adoc
> +[source,abap]
If you add the compliant example I gave you it can be updated to:
```suggestion
[source,abap,diff-id=2,diff-type=noncompliant]
```

2023-10-20 08:12 UTC, nicolas-gauthier-sonarsource reviewed
LGTM for APEX! I just have minor formatting comments

2023-10-20 08:12 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/apex/description.adoc
> +Having two ``++when++``s in a ``++switch++`` statement or two branches in an ``++if++`` chain with the same implementation is at best duplicate code, and at worst a coding error.
Can be simplified:
```suggestion
Having two ``when``s in a `switch` statement or two branches in an `if` chain with the same implementation is at best duplicate code, and at worst a coding error.

```
(my IDE adds empty lines at the end of all files)

2023-10-20 08:12 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/apex/exceptions.adoc
> +Blocks in an ``++if++`` chain that contain a single line of code are ignored, as are blocks in a ``++switch++`` statement that contain a single line of code with or without a following ``++break++``.
Can be simplified:
```suggestion
Blocks in an `if` chain that contain a single line of code are ignored, as are blocks in a `switch` statement that contain a single line of code with or without a following `break`.
```

2023-10-20 08:12 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/apex/exceptions.adoc
> +But this exception does not apply to ``++if++`` chains without ``++else++``-s, or to ``++switch++``-es without default clauses when all branches have the same single line of code. In case of ``++if++
Can be simplified (and I added a very personal + to go to the next line, as I had some trouble understanding the different ideas while reading, so I separated the phrases):
```suggestion
But this exception does not apply to `if` chains without `else`-s, or to `switch`-es without default clauses when all branches have the same single line of code. +
In the case of `if` chains with `else`-s, or of `switch`-es with default clauses, rule S3923 raises a bug.
```

2023-10-20 08:12 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/apex/rule.adoc
This empty line can be removed

2023-10-20 08:34 UTC, victor-diez-sonarsource commented on rules/S1871/abap/compliant.adoc
> +----
thanks @nicolas-gauthier-sonarsource , can you share the link? I checked abap official docs, and didn't see anywhere how to put multiple values

2023-10-20 08:38 UTC, frederic-tingaud-sonarsource commented on rules/S1871/common/exceptions.adoc
> +=== Exceptions
If the exception to the exception explains the difference with S3923, I don't think it's necessary.

2023-10-20 08:40 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/abap/compliant.adoc
> +----
Of course!
The official https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abapcase.htm show the syntax
```
CASE operand.
  [WHEN operand1 [OR operand2 [OR operand3 [...]]].
    [statement_block1]]
  ...
  [WHEN OTHERS.
    [statement_blockn]]
ENDCASE.
```
We also have in our repository:
https://github.com/SonarSource/sonar-abap/blob/master/abap-checks/src/test/resources/check/identicalBranchesCheck-S1871.abap#L67
And in real sources:
https://github.com/SonarSource/abap-test-sources/blob/0b3fa2f5832e24ee2af0919006e1e2c32495fbae/sap/sources/d02/ZAGENETII9600.txt#L18

2023-10-20 08:43 UTC, victor-diez-sonarsource commented on rules/S1871/abap/compliant.adoc
> +----
excellent, thanks I totally missed that!

2023-10-20 08:50 UTC, leonardo-pilastri-sonarsource approved these changes
Just some optional suggestions about splitting long lines, very nice job!

2023-10-20 08:50 UTC, leonardo-pilastri-sonarsource commented on rules/S1871/common/description.adoc
> +Having two `cases` in a `switch` statement or two branches in an `if` chain with the same implementation is at best duplicate code, and at worst a coding error.
Not strong opinion, but it can be nice to split single long lines into multiple shorter ones, to facilitate future reviews
```suggestion
Having two `cases` in a `switch` statement or two branches in an `if` chain with
the same implementation is at best duplicate code, and at worst a coding error.
```

2023-10-20 08:50 UTC, leonardo-pilastri-sonarsource commented on rules/S1871/common/exceptions.adoc
> +Unless all blocks are identical, blocks in an `if` chain that contain a single line of code are ignored. The same applies to blocks in a `switch` statement that contains a single line of code with or
Same here, not a strong opinion, but could be split
```suggestion
Unless all blocks are identical, blocks in an `if` chain that contain a single line of code are ignored.
The same applies to blocks in a `switch` statement that contains a single line of code with or without a following `break`.
```

2023-10-20 08:50 UTC, leonardo-pilastri-sonarsource commented on rules/S1871/rule.adoc
> +When the same code is duplicated in two or more separate branches of a conditional, it can make the code harder to understand, maintain, and can potentially introduce bugs if one instance of the code
Same here, but ignorable
```suggestion
When the same code is duplicated in two or more separate branches of a conditional,
it can make the code harder to understand, maintain, and can potentially introduce
bugs if one instance of the code is changed but others are not.
```

2023-10-20 11:11 UTC, nicolas-gauthier-sonarsource reviewed
Cobol LGTM!
Only formatting comments

2023-10-20 11:11 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/cobol/description.adoc
> +Having two ``++WHEN++`` clauses in the same ``++EVALUATE++`` statement or two branches in the same ``++IF++`` structure with the same implementation is at best duplicate code, and at worst a coding e
Can be simplified:
```suggestion
Having two `WHEN` clauses in the same `EVALUATE` statement or two branches in the same `IF` structure with the same implementation is at best duplicate code, and at worst a coding error.

```

2023-10-20 11:11 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/cobol/exceptions.adoc
> +Blocks in an ``++IF++`` chain that contain a single line of code are ignored, as are blocks in a ``++EVALUATE++`` statement that contain a single line of code.
Can be simplified:
```suggestion
Blocks in an `IF` chain that contain a single line of code are ignored, as are blocks in a `EVALUATE` statement that contain a single line of code.
```

2023-10-20 11:11 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/cobol/exceptions.adoc
> +But this exception does not apply to ``++IF++`` chains without ``++ELSE++``-s, or to ``++EVALUATE++``-s without ``++WHEN OTHER++`` clauses when all branches have the same single line of code. In case
Can be simplified:
```suggestion
But this exception does not apply to `IF` chains without `ELSE`-s, or to `EVALUATE`-s without `WHEN OTHER` clauses when all branches have the same single line of code. In case of `IF` chains with `ELSE`-s, or of `EVALUATE`-es with `WHEN OTHER` clauses, rule S3923 raises a bug. 
```

2023-10-20 11:11 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/cobol/rule.adoc
There are two empty lines 18/19, one can be removed

2023-10-20 11:45 UTC, zsolt-kolbay-sonarsource approved these changes
LGTM. Nicely organized!

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource reviewed
Some more minor formatting comments

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/go/exceptions.adoc
> +Blocks in an ``++if++`` chain or ``++case++`` blocks that contain a single line of code are ignored.
Can be simplified:
```suggestion
Blocks in an `if` chain or `case` blocks that contain a single line of code are ignored.
```

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/kotlin/description.adoc
> +Having two clauses in a ``++when++`` statement or two branches in an ``++if++`` chain with the same implementation is at best duplicate code, and at worst a coding error.
Can be simplified:
```suggestion
Having two clauses in a `when` statement or two branches in an `if` chain with the same implementation is at best duplicate code, and at worst a coding error.
```

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/kotlin/exceptions.adoc
> +Blocks in an ``++if++`` chain or in a ``++when++`` branch that contain a single line of code are ignored.
Can be simplified:
```suggestion
Blocks in an `if` chain or in a `when` branch that contain a single line of code are ignored.
```

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/kotlin/exceptions.adoc
> +But this exception does not apply to ``++if++`` chains without ``++else++``-s, or to ``++when++``-es without ``++else++`` clauses when all branches have the same single line of code. In case of ``++i
Can be simplified:
```suggestion
But this exception does not apply to `if` chains without `else`-s, or to `when`-es without `else` clauses when all branches have the same single line of code. In case of `if` chains with `else`-s, or of `when`-es with default clauses, rule S3923 raises a bug.
```

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/kotlin/rule.adoc
One of the two empty lines can be removed

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/php/exceptions.adoc
> +Blocks in an ``++if++`` chain that contain a single line of code are ignored, as are blocks in a ``++switch++`` statement that contain a single line of code with or without a following ``++break++``.
Can be simplified:
```suggestion
Blocks in an `if` chain that contain a single line of code are ignored, as are blocks in a `switch` statement that contain a single line of code with or without a following `break`.
```

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/php/exceptions.adoc
> +But this exception does not apply to ``++if++`` chains without ``++else++``-s, or to ``++switch++``-es without default clauses when all branches have the same single line of code. In case of ``++if++
Can be simplified:
```suggestion
But this exception does not apply to `if` chains without `else`-s, or to `switch`-es without default clauses when all branches have the same single line of code. In the case of `if` chains with `else`-s, or of `switch`-es with default clauses, rule S3923 raises a bug.
```

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/php/rule.adoc
One empty line can be removed

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/plsql/exceptions.adoc
> +Branches in an ``++IF++``/``++ELSIF++`` chain with implementation that contains a single line of code are ignored.
Can be simplified:
```suggestion
Branches in an `IF`/`ELSIF` chain with implementation that contains a single line of code are ignored.
```

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/plsql/description.adoc
> +Having two branches in an ``++IF++``/``++ELSIF++`` chain with the same implementation is at best duplicate code, and at worst a coding error.
Can be simplified:
```suggestion
Having two branches in an `IF`/`ELSIF` chain with the same implementation is at best duplicate code, and at worst a coding error.
```

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/plsql/exceptions.adoc
> +But this exception does not apply to ``++IF++`` chains without ``++ELSE++``-s when all branches have the same single line of code. In case of ``++IF++`` chains with ``++ELSE++``-s rule S3923 raises a
Can be simplified:
```suggestion
But this exception does not apply to `IF` chains without `ELSE`-s when all branches have the same single line of code. In case of `IF` chains with `ELSE`-s rule S3923 raises a bug.
```

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/ruby/description.adoc
> +Having two ``++when++`` clauses in a ``++case++`` statement or two branches in an ``++if++`` chain with the same implementation is at best duplicate code, and at worst a coding error.
Can be simplified:
```suggestion
Having two `when` clauses in a `case` statement or two branches in an `if` chain with the same implementation is at best duplicate code, and at worst a coding error.
```

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/ruby/exceptions.adoc
> +Blocks in an ``++if++`` chain that contain a single line of code are ignored, as are blocks in a ``++case++`` statement that contain a single line of code.
Can be simplified:
```suggestion
Blocks in an `if` chain that contain a single line of code are ignored, as are blocks in a `case` statement that contain a single line of code.
```

2023-10-20 11:47 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/ruby/exceptions.adoc
> +But this exception does not apply to ``++if++`` chains without ``++else++``-s, or to ``++case++``-es without ``++else++`` clauses when all branches have the same single line of code. In case of ``++i
Can be simplified:
```suggestion
But this exception does not apply to `if` chains without `else`-s, or to `case`-es without `else` clauses when all branches have the same single line of code. In the case of `if` chains with `else`-s, or of `case`-es with `else` clauses, rule S3923 raises a bug. 
```

2023-10-20 12:27 UTC, frederic-tingaud-sonarsource approved these changes

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource approved these changes
LGTM!
Just minor formatting comments and apologies for not being helpful with RPG.

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/vbnet/exceptions.adoc
> +But this exception does not apply to ``++If++`` chains without ``++Else++``-s, or to ``++Select++``-s without ``++Case Else++`` clauses when all branches have the same single line of code. In case of
```suggestion
But this exception does not apply to `If` chains without `Else`-s, or to `Select`-s without `Case Else` clauses when all branches have the same single line of code. In the case of `If` chains with `Else`-s, or of `Select`-es with `Case Else` clauses, rule S3923 raises a bug.
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/vbnet/exceptions.adoc
> +Blocks in an ``++If++`` chain or ``++Case++`` clause that contain a single line of code are ignored.
```suggestion
Blocks in an `If` chain or `Case` clause that contain a single line of code are ignored.
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/vbnet/description.adoc
> +Having two ``++Cases++`` in the same ``++Select++`` statement or branches in the same ``++If++`` structure with the same implementation is at best duplicate code, and at worst a coding error.
```suggestion
Having two `Cases` in the same `Select` statement or branches in the same `If` structure with the same implementation is at best duplicate code, and at worst a coding error.
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/tsql/exceptions.adoc
> +Branches in an ``++IF++``/``++ELSE IF++`` chain with an implementation that contains a single line of code are ignored.
```suggestion
Branches in an `IF`/`ELSE IF` chain with an implementation that contains a single line of code are ignored. 
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/tsql/exceptions.adoc
> +But this exception does not apply to ``++IF++`` chains without ``++ELSE++``-s when all branches have the same single line of code. In the case of ``++IF++`` chains with ``++ELSE++``-s rule S3923 rais
```suggestion
But this exception does not apply to `IF` chains without `ELSE`-s when all branches have the same single line of code. In the case of `IF` chains with `ELSE`-s rule S3923 raises a bug.
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/tsql/description.adoc
> +Having two branches in an ``++IF++``/``++ELSE IF++`` chain with the same implementation is at best duplicate code, and at worst a coding error.
```suggestion
Having two branches in an `IF`/`ELSE IF` chain with the same implementation is at best duplicate code, and at worst a coding error.
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/swift/exceptions.adoc
> +``++case++`` labels that declare variables cannot have multiple patterns. Therefore this situation is ignored.
```suggestion
`case` labels that declare variables cannot have multiple patterns. Therefore this situation is ignored.
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/swift/exceptions.adoc
> +Blocks in an ``++if++`` chain that contain a single line of code are ignored, as are blocks in a ``++switch++`` statement that contain a single line of code with or without a following ``++break++``.
```suggestion
Blocks in an `if` chain that contain a single line of code are ignored, as are blocks in a `switch` statement that contain a single line of code with or without a following `break`.
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/swift/exceptions.adoc
> +But this exception does not apply to ``++if++`` chains without ``++else++``-s, or to ``++switch++``-es without default clauses when all branches have the same single line of code. In case of ``++if++
```suggestion
But this exception does not apply to `if` chains without `else`-s, or to `switch`-es without default clauses when all branches have the same single line of code. In the case of `if` chains with `else`-s, or of `switch`-es with default clauses, rule S3923 raises a bug. 
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/rpg/exceptions.adoc
> +But this exception does not apply to ``++if++`` chains without ``++else++``-s, or to ``++select++``-s without ``++other++`` clauses when all branches have the same single line of code. In case of ``+
```suggestion
But this exception does not apply to `if` chains without `else`-s, or to `select`-s without `other` clauses when all branches have the same single line of code. In the case of `if` chains with `else`-s, or of `select`-s with `other` clauses, rule S3923 raises a bug. 
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/rpg/exceptions.adoc
> +Blocks in an ``++if++`` chain or ``++select++`` statement that contain a single line of code are ignored.
```suggestion
Blocks in an `if` chain or `select` statement that contain a single line of code are ignored.
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/rpg/description.adoc
> +Having two ``++WHEN++`` in the same ``++SELECT++`` statement or branches in the same ``++IF++`` structure  with the same implementation is at best duplicate code, and at worst a coding error.
```suggestion
Having two `WHEN` in the same `SELECT` statement or branches in the same `IF` structure  with the same implementation is at best duplicate code, and at worst a coding error.
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/rpg/compliant.adoc
Unfortunately, I could not find compliant examples I was confident in.

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/python/description.adoc
> +Having two branches in the same ``++if++`` structure  with the same implementation is at best duplicate code, and at worst a coding error.
```suggestion
Having two branches in the same `if` structure  with the same implementation is at best duplicate code, and at worst a coding error.
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/python/exceptions.adoc
> +Blocks in an ``++if++`` chain that contain a single line of code are ignored.
```suggestion
Blocks in an `if` chain that contain a single line of code are ignored.
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/python/exceptions.adoc
> +But this exception does not apply to ``++if++`` chains without ``++else++``-s when all branches have the same single line of code. In case of ``++if++`` chains with ``++else++``-s rule S3923 raises a
```suggestion
But this exception does not apply to `if` chains without `else`-s when all branches have the same single line of code. In the case of `if` chains with `else`-s rule S3923 raises a bug. 
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/csharp/rule.adoc
This empty line can be removed

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/csharp/exceptions.adoc
> +But this exception does not apply to ``++if++`` chains without ``++else++``-s, or to ``++switch++``-es without default clauses when all branches have the same single line of code. In case of ``++if++
```suggestion
But this exception does not apply to `if` chains without `else`-s, or to `switch`-es without default clauses when all branches have the same single line of code. In the case of `if` chains with `else`-s, or of `switch`-es with default clauses, rule S3923 raises a bug. 
```

2023-10-20 12:32 UTC, nicolas-gauthier-sonarsource commented on rules/S1871/csharp/exceptions.adoc
> +Blocks in an ``++if++`` chain that contain a single line of code are ignored, as are blocks in a ``++switch++`` statement that contain a single line of code with or without a following ``++break++``.
```suggestion
Blocks in an `if` chain that contain a single line of code are ignored, as are blocks in a `switch` statement that contain a single line of code with or without a following `break`.
```

2023-10-20 13:38 UTC, victor-diez-sonarsource commented on rules/S1871/rpg/compliant.adoc
I totally understand, I tried but I prefer not to risk if I'm not confident about the code

2023-10-24 09:34 UTC, joke1196 approved these changes
LGTM for Python! Added a small suggestion. Thank you for the work!

2023-10-24 09:34 UTC, joke1196 commented on rules/S1871/python/compliant.adoc
> +If the same logic is needed for both instances the conditions should be combined.
A comma is missing after `instances`.

2023-10-24 09:34 UTC, joke1196 commented on rules/S1871/python/compliant.adoc
> +If the same logic is needed for both instances the conditions should be combined.
Maybe we could go with `If the same logic is needed for both instances, then the conditions should be combined.`

2023-10-24 12:02 UTC, merged