Rule S3059: update description and code examples
SonarSource/rspec pull request #332
Opened 2021-09-13 08:42 UTC by costin-zaharia-sonarsource

2021-09-13 09:38 UTC, mary-georgiou-sonarsource commented on rules/S3059/csharp/rule.adoc
> +This rule raises an issue when a type has methods, fields, or inner typs with higher visibility than the type itself has.
small typo here.

2021-09-13 09:51 UTC, mary-georgiou-sonarsource requested changes
There's only a small typo in line 4 (tps -> types).

2021-09-13 14:18 UTC, andrei-epure-sonarsource requested changes
Is this rule really SonarWay? 

I'm pretty sure that it's debatable, it should be evaluated on how noisy it is. AFAIK we don't respect this in our own codebase, so I can imagine other teams may not respect this.

I can imagine a philosophical debate between programmers on this topic.

2021-09-13 14:18 UTC, andrei-epure-sonarsource commented on rules/S3059/csharp/rule.adoc
> +        public bool FlipCoin() // Noncompliant: parent class is protected
```suggestion
        public bool FlipCoin() // Noncompliant: parent type is protected
```

2021-09-13 14:18 UTC, andrei-epure-sonarsource commented on rules/S3059/csharp/rule.adoc
> +internal class MyClass // Class visibility upgrade makes members compliant
```suggestion
public class MyClass // Class visibility upgrade makes members compliant
```

?

2021-09-13 14:18 UTC, andrei-epure-sonarsource commented on rules/S3059/csharp/rule.adoc
> +        protected bool FlipCoin() // visibility changed to match class
```suggestion
        protected bool FlipCoin() // visibility changed to match type
```

2021-09-13 15:08 UTC, costin-zaharia-sonarsource commented
> Is this rule really SonarWay?
> I can imagine a philosophical debate between programmers on this topic.

The rule was specified as being part of SonarWay. I agree that this can cause some frustration for some developers and that we can discuss and implement it outside of the default profile.

I still find it useful since having a public method on an internal class can cause some confusion.

There are though some exceptions we have to keep in mind:
- implicit and explicit operators always have to be public (even if they are in a type with different visibility)
- private nested types need higher visibility for their members to make them available to the parent type.

2021-09-13 15:59 UTC, andrei-epure-sonarsource approved these changes
LGTM

2021-09-14 11:33 UTC, mary-georgiou-sonarsource approved these changes
LGTM

2021-09-14 14:00 UTC, costin-zaharia-sonarsource commented on rules/S3059/csharp/rule.adoc
> +        public int PublicProperty { get; } // Noncompliant: should be internal
Not sure I understand why

2021-09-14 14:05 UTC, andrei-epure-sonarsource commented on rules/S3059/csharp/rule.adoc
> +        public int PublicProperty { get; } // Noncompliant: should be internal
because if I want the parent class to have access to the fields, I just make them public.

Either way a private inner class is private. I don't think that changing the visibility of the outer class should be reflected on the members of each private inner type.

Does it make sense? I don't know how to phrase it in words...

And actually I realize as writing that this is an argument for the rule not being in SonarWay.

If I want my type members to have "maximum visibility of the type" - I just make them public. If I change the parent type from "internal" to public, I may not want to change the visibility of each individual type member

2021-09-14 14:16 UTC, costin-zaharia-sonarsource commented on rules/S3059/csharp/rule.adoc
> +        public int PublicProperty { get; } // Noncompliant: should be internal
> Either way a private inner class is private. I don't think that changing the visibility of the outer class should be reflected on the members of each private inner type.
> If I want my type members to have "maximum visibility of the type" - I just make them public. If I change the parent type from "internal" to public, I may not want to change the visibility of each individual type member

I think that this argument can be generalized also for the members of the outer class and this will make the rule redundant.

On the other side, the visibility of the nested class members is even harder to get right (need to consider also the outer type) so raising an issue could be more helpful.

> And actually I realize as writing that this is an argument for the rule not being in SonarWay.
I agree with this rule not being in SonarWay. I will ask the team for feedback.

2021-09-14 14:28 UTC, merged