Modify S1155: Migrate to LaYC
SonarSource/rspec pull request #3327
Opened 2023-10-18 14:12 UTC by yassin-kammoun-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-18 15:18 UTC, yassin-kammoun-sonarsource commented
I realized too late that the CFamily RSPEC was already reviewed :/

2023-10-18 16:54 UTC, frederic-tingaud-sonarsource requested changes
Thanks for the improvements!

2023-10-18 16:54 UTC, frederic-tingaud-sonarsource commented on rules/S1155/cfamily/rule.adoc
> +== How to fix it
Regarding the content, I think the new text is an improvement.

Regarding the form, for this kind of rule where the title already explains how to fix, we try to keep the code in "Why is this an issue".
Here, instead of having the last sentence of "why is this an issue?" "Using `empty()` or `is_empty()` to test for emptiness should therefore be preferred over `size()`, `length()` or `count()`." 
I would rather have:

> Instead of checks on `size()`, `length()` or `count()`.
> [source,cpp,diff-id=1,diff-type=noncompliant]
> `----`
> ...
> `----`
> Prefer using `empty()`:
> [source,cpp,diff-id=1,diff-type=compliant]
> `----`
> ...
> `----`

2023-10-18 16:54 UTC, frederic-tingaud-sonarsource commented on rules/S1155/cfamily/rule.adoc
> +=== Documentation
```suggestion
=== External coding guidelines
```

2023-10-18 16:54 UTC, frederic-tingaud-sonarsource commented on rules/S1155/cfamily/rule.adoc
> +When you call `empty()` or `is_empty()`, it clearly communicates the intention of the code, which is to check if the collection is empty. Using `size() == 0` for this purpose is less direct and can m
```suggestion
When you call `empty()` or `is_empty()`, it clearly communicates the intention of the code, which is to check if the collection is empty. Using `size() == 0` for this purpose is less direct and makes the code slightly more complex.
```

2023-10-18 16:54 UTC, frederic-tingaud-sonarsource commented on rules/S1155/cfamily/rule.adoc
> +Depending on the implementation, the `size()`, `length()` or `count()` methods can have a time complexity of `O(n)` where `n` is the number of elements in the collection. On the other hand, `empty()`
```suggestion
Moreover, depending on the implementation, the `size()`, `length()`, or `count()` methods can have a time complexity of `O(n)` where `n` is the number of elements in the collection. On the other hand, `empty()` and `is_empty()` simply check if there is at least one element in the collection, which is a constant time operation, `O(1)`.
```

2023-10-18 16:54 UTC, frederic-tingaud-sonarsource commented on rules/S1155/cfamily/rule.adoc
> +Using `empty()` or `is_empty()` to test for emptiness should therefore be preferred over `size()`, `length()` or `count()`.
```suggestion
Using `empty()` or `is_empty()` to test for emptiness should therefore be preferred over `size()`, `length()`, or `count()`.
```

2023-10-19 08:40 UTC, nicolas-gauthier-sonarsource reviewed
Nice work!
Just some formatting comments and discussion :-)

2023-10-19 08:40 UTC, nicolas-gauthier-sonarsource commented on rules/S1155/cfamily/rule.adoc
> +When you call `empty()` or `is_empty()`, it clearly communicates the intention of the code, which is to check if the collection is empty. Using `size() == 0` for this purpose is less direct and can m
Minor: `the intention of the code` can be replaced by `the code's intention`

2023-10-19 08:40 UTC, nicolas-gauthier-sonarsource commented on rules/S1155/cfamily/rule.adoc
The wording suggestions of @frederic-tingaud-sonarsource look good, IMO; you could replicate them in the other `rule.adoc` as the descriptions are close.
About the deletion of the `How to fix it` part to integrate the code examples in the `Why is this an issue?` part, I personally like to keep both, even for "simple" rules, so I let you do as you prefer.

PS: an empty line can be removed at lines 52/53.

2023-10-19 08:40 UTC, nicolas-gauthier-sonarsource commented on rules/S1155/csharp/rule.adoc
There are double empty lines that can be replaced by just one:
- 65/66
- 73/74
- ...
Additionally, to help Fred removing the useless ''++++'' and replace them with '' the comments at the end of the files containing only `.()` as special symbols can be updated to use only backtick: `''++.Count()++''` -> `'.Count() '`

2023-10-19 08:40 UTC, nicolas-gauthier-sonarsource commented on rules/S1155/java/rule.adoc
> +----
These snippets can be made compilable:
```suggestion
[source,java,diff-id=1,diff-type=noncompliant]
----
public class MyClass {
  public void doSomething(Collection<String> myCollection) {
    if (myCollection.size() == 0) { // Noncompliant
      doSomethingElse();
    }
  }
}
----

==== Compliant solution

[source,java,diff-id=1,diff-type=compliant]
----
public class MyClass {
  public void doSomething(Collection<String> myCollection) {
    if (myCollection.isEmpty()) {
      doSomethingElse();
    }
  }
}
----
```

2023-10-19 08:40 UTC, nicolas-gauthier-sonarsource commented on rules/S1155/java/rule.adoc
> +
This extra empty line can be removed

2023-10-19 09:08 UTC, yassin-kammoun-sonarsource commented on rules/S1155/java/rule.adoc
> +----
👍

2023-10-19 09:09 UTC, yassin-kammoun-sonarsource commented on rules/S1155/java/rule.adoc
> +
👍

2023-10-19 11:58 UTC, nicolas-gauthier-sonarsource approved these changes
LGTM!

2023-10-19 12:15 UTC, frederic-tingaud-sonarsource approved these changes

2023-10-19 13:33 UTC, merged