Modify rule S4211: Change text to education framework format (APPSEC-1206)
SonarSource/rspec pull request #3328
Opened 2023-10-18 14:15 UTC by sebastien-andrivet-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-20 14:44 UTC, loris-s-sonarsource requested changes
I have impactful comments, and as always I am available to discuss everything

2023-10-20 14:44 UTC, loris-s-sonarsource commented on rules/S4211/csharp/rule.adoc
> +Conflicting transparency attributes in .NET Framework can lead to serious security issues.
Here, that suggestion adds the "Below.." sentence, which is normally our norm while writing. I also provide the small introduction to avoid repeating it in the section below:

```suggestion
If code that is expected to be ``++[SecurityCritical]++`` is actually made ``++[SecuritySafeCritical]++`` by the .Net runtime environment, an attacker can use it and perform unexpected malicious operations with it.

Below are some real-world scenarios that illustrate some impacts of an attacker exploiting the vulnerability.
```

2023-10-20 14:44 UTC, loris-s-sonarsource commented on rules/S4211/csharp/rule.adoc
> +
Since the most sensitive scenario in general is " a member marked as SecurityCritical but considered SecuritySafeCritical" because of its class, I suggest removing it, since it should be in the introduction.

Here I suggest borrowing some text from existing rules, to avoid unnecessarily creating new text and to maintain consistency across rules. For example, those mentioning "privilege escalation" can provide some text that help ideating, such as the deserialization rule (S5135), or the reflection injection rule (S6173)

Here is what it could look like:

```suggestion
==== Application-specific attacks

In this scenario, the attackers succeed in calling a legitimate function expecting a
trusted caller. Depending on the application business logic,  attackers can modify
the data structure or content to escalate privileges or perform unwanted actions. +
In the context of an e-commerce application, this could be changing the number
of products or prices.

==== Full application compromise

In the worst-case scenario, the attackers succeed in calling functions
that suppose the caller is trusted, and trigger code execution.

Depending on the attacker, code execution can be used with different
intentions:

* Download the internal server's data, most likely to sell it.
* Modify data, install malware, for instance, malware that mines cryptocurrencies.
* Stop services or exhaust resources, for instance, with fork bombs.

This threat is particularly insidious if the attacked organization does not
maintain a Disaster Recovery Plan (DRP).

==== Root privilege escalation and pivot

In this scenario, the attacker can do everything described in the previous
section. The difference is that the attacker additionally manages to elevate
his privileges as an administrator and attack other servers.

Here, the impact depends on how much the target company focuses on its Defense
In Depth. For example, the entire infrastructure can be compromised through a
combination of unsafe deserialization and misconfiguration:

* Docker or Kubernetes clusters
* cloud services
* network firewalls and routing
* OS access control
```

2023-10-20 14:44 UTC, loris-s-sonarsource commented on rules/S4211/csharp/rule.adoc
> +To fix this vulnerability in the .NET Framework, you need to ensure that all members of a class or structure have consistent transparency attributes.
```suggestion
```

This section should always start by the code, or if the code has some specifics in its logic, a small code rationale explaining what it does. But the fix should be after the code

2023-10-20 14:44 UTC, loris-s-sonarsource commented on rules/S4211/csharp/rule.adoc
The fix belongs here:

```suggestion

=== How does this work?

==== Never set class-level annotations

A class should never have class-level annotations if some functions have different permission levels. Instead, make sure every function has its own correct annotation. 

If no function needs a particularly distinct security annotation in a class, just set a class-level ``++[SecurityCritical]++``.

```

2023-10-24 09:30 UTC, sebastien-andrivet-sonarsource commented on rules/S4211/csharp/rule.adoc
> +Transparency attributes in .NET Framework are a set of security features designed to protect your code from unauthorized access and to protect security-critical operations. However, they can become a
The last sentence is only about a specific case and I do not think that "tends" is appropriate here. I will suggest something else.

2023-10-24 10:44 UTC, loris-s-sonarsource commented on rules/S4211/csharp/rule.adoc
> +Transparency attributes in .NET Framework are a set of security features designed to protect your code from unauthorized access and to protect security-critical operations. However, they can become a
Yes, something to note is that in general when I do a code suggestion, I do not necessarily mean "replace the text by the one I'm suggesting", It's just as suggestion of how I see it. Do as you please with it 👍

2023-10-24 13:34 UTC, sebastien-andrivet-sonarsource commented on rules/S4211/csharp/rule.adoc
The rule is more for the developer writing the (original) code the code will not do what he or she expects. It is highly counterintuitive. It is not really for future maintainers (especially since all that is mentioned in this rule is no longer supported by .NET). I will rephrase.

I agree for the code, I will remove it.

2023-10-24 13:54 UTC, sebastien-andrivet-sonarsource commented on rules/S4211/csharp/rule.adoc
> +
"Here I suggest borrowing some text from existing rules, to avoid unnecessarily creating new text". This is not much compatible with our usage of OpenAI prompts. We get different texts each time.

For me, the examples you suggest do not apply to this specific rule.

What is detected by this rule is old, out of date and no longer used by .NET. The whole original mechanism is weak by nature. So the impacts are in fact very theoretical.

2023-10-24 14:48 UTC, loris-s-sonarsource approved these changes
LGTM

2023-10-25 07:57 UTC, merged