Modify S1144: Migrate to LaYC
SonarSource/rspec pull request #3332
Opened 2023-10-19 00:53 UTC by zsolt-kolbay-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-19 07:38 UTC, frederic-tingaud-sonarsource requested changes
The content is great, just a few notes on the form.

2023-10-19 07:38 UTC, frederic-tingaud-sonarsource commented on rules/S1144/cfamily/rule.adoc
> +==== Noncompliant code example
This is not really a Noncompliant code example. You can just remove the two titles and have the text and the code together.

2023-10-19 07:38 UTC, frederic-tingaud-sonarsource commented on rules/S1144/csharp/rule.adoc
"===Exceptions" makes more sense after the code examples, when the general case has been clarified

2023-10-19 07:38 UTC, frederic-tingaud-sonarsource commented on rules/S1144/java/rule.adoc
> +Note that this rule does not take reflection into account, which means that issues will be raised on `private` methods that are only accessed using the reflection API.
I would put the note and the Exceptions after the code snippets

2023-10-19 07:38 UTC, frederic-tingaud-sonarsource commented on rules/S1144/cfamily/rule.adoc
Perhaps this could be an include to ../why.adoc

2023-10-19 07:38 UTC, frederic-tingaud-sonarsource commented on rules/S1144/python/rule.adoc
> +* methods with a name starting with a single underscore (ex: `_mymethod`) should be seen as non-public and might change without prior notice. They should not be used by third-party libraries or softw
It's dangerous to remove the ``++ with names that start with `_`. They might be converted to italic.

2023-10-19 07:38 UTC, frederic-tingaud-sonarsource commented on rules/S1144/cfamily/rule.adoc
>  ----
Below, in `== Resources`, could you also add `=== External coding guidelines` before the MISRA reference?

2023-10-19 09:11 UTC, guillaume-dequenne-sonarsource requested changes
Left a few suggestions.

2023-10-19 09:11 UTC, guillaume-dequenne-sonarsource commented on rules/S1144/apex/rule.adoc
> +    }
I think non compliant examples are best kept minimal, I'm not sure it makes sense to show in the example that issues are also raised for static methods.

2023-10-19 12:21 UTC, frederic-tingaud-sonarsource commented on rules/S1144/why.adoc
> +This rule detects functions that are never called from inside a translation unit, and cannot be called from the outside.
In case you want to split languages that do or don't refer to "Translation unit", it is the correct term for CFamily.

2023-10-19 14:19 UTC, zsolt-kolbay-sonarsource commented on rules/S1144/cfamily/rule.adoc
Which lines exactly?

2023-10-19 14:39 UTC, frederic-tingaud-sonarsource commented on rules/S1144/cfamily/rule.adoc
Line 3 to 5 are identical to the content of why.adoc so far.
But Guillaume suggested to change `why.adoc`, so that might change. If you end up changing `why.adoc`, you can ignore my comment and keep the current text as is.

2023-10-19 22:29 UTC, zsolt-kolbay-sonarsource commented on rules/S1144/why.adoc
> +This rule detects functions that are never called from inside a translation unit, and cannot be called from the outside.
I used the term _translation unit_ for every language. PHP has a separate paragraph that explains how enums are treated. So I think it's fine to leave _translation unit_ in the general description.

2023-10-20 07:21 UTC, frederic-tingaud-sonarsource approved these changes

2023-10-20 07:37 UTC, guillaume-dequenne-sonarsource approved these changes
Good improvement overall!
Left a final comment for the Python description. I don't think it's too big a problem in the grand scheme of things, but would be nice to be addressed.

2023-10-20 07:37 UTC, guillaume-dequenne-sonarsource commented on rules/S1144/why.adoc
> +This rule detects {operationName}s that are never referenced from inside a translation unit, and cannot be referenced from the outside.
_Nitpick:_ I still feel that while this sentence is great to describe the rule in a generic way, it may be a bit confusing when reading the Python version of the rule in isolation, as the next sentence directly contradicts this one (`Python has no real private methods. Every method is accessible. `: so this rule doesn't actually raise on methods that can't be referenced from the outside).

For Python I'd either remove the sentence or reuse the one in the `description.adoc` which is more accurate for the context.

2023-10-20 12:20 UTC, guillaume-dequenne-sonarsource commented on rules/S1144/python/rule.adoc
> +This rule raises an issue when a "class-private" method is never called inside the class in where it was declared.
Grammar: I think the "in" is redundant:
 `inside the class in where it was declared. ` -> `inside the class where it was declared.`

2023-10-20 13:29 UTC, merged