Modify S3334: Change text to LaYC (APPSEC-1219)
SonarSource/rspec pull request #3334
Opened 2023-10-19 08:59 UTC by gaetan-ferry-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-23 17:01 UTC, jamie-anderson-sonarsource requested changes
There are a few places where I think the wording could be changed to better meet a technical writing style.

2023-10-23 17:01 UTC, jamie-anderson-sonarsource commented on rules/S3334/php/rule.adoc
> +[source, php, diff-id=1, diff-type=compliant]
```suggestion
[source,php,diff-id=1,diff-type=compliant]
```

2023-10-24 09:03 UTC, gaetan-ferry-sonarsource commented
Thanks for the suggestion. I have been definitely too verbose here.

2023-10-24 16:28 UTC, jamie-anderson-sonarsource approved these changes
LGTM

2023-10-25 07:38 UTC, merged