Modify S2259: Migrate to LaYC - null dereference
SonarSource/rspec pull request #3337
Opened 2023-10-19 09:57 UTC by rudy-regazzoni-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-19 12:03 UTC, victor-diez-sonarsource approved these changes

2023-10-19 12:03 UTC, victor-diez-sonarsource commented on rules/S2259/javascript/rule.adoc
> +Another option is to check in a `if` condition the equality to `null` or `undefined`.
I would put this latest suggestion in before the optional chaining, putting the accent in the last (optional chaining) as it's the newest and cleanest

2023-10-19 15:31 UTC, leonardo-pilastri-sonarsource requested changes
Looks good to me, just a few formatting changes

2023-10-23 11:37 UTC, leonardo-pilastri-sonarsource approved these changes
Looks good, I think there are just some grammar typos but they are negligible

2023-10-23 11:37 UTC, leonardo-pilastri-sonarsource commented on rules/S2259/java/compliant-code.adoc
> +Ensuring the variable `myObject` has a value resolve the issue:
```suggestion
Ensuring the variable `myObject` has a value resolves the issue:
```

2023-10-23 11:37 UTC, leonardo-pilastri-sonarsource commented on rules/S2259/java/compliant-code.adoc
> +Ensuring that no unboxing of `null` value can happen resolve the issue
```suggestion
Ensuring that no unboxing of `null` value can happen resolves the issue
```

2023-10-23 11:37 UTC, leonardo-pilastri-sonarsource commented on rules/S2259/java/compliant-code.adoc
> +Ensuring that both `conn` and `stmt` are not `null` resolve the issue:
```suggestion
Ensuring that both `conn` and `stmt` are not `null` resolves the issue:
```

2023-10-23 11:37 UTC, leonardo-pilastri-sonarsource commented on rules/S2259/java/compliant-code.adoc
> +Checking the returned value of `getName()` resolve the issue:
```suggestion
Checking the returned value of `getName()` resolves the issue:
```

2023-10-23 11:37 UTC, leonardo-pilastri-sonarsource commented on rules/S2259/java/compliant-code.adoc
> +Ensuring that the provided `color` is not `null` resolve the issue:
```suggestion
Ensuring that the provided `color` is not `null` resolves the issue:
```

2023-10-23 11:37 UTC, leonardo-pilastri-sonarsource commented on rules/S2259/java/noncompliant-code.adoc
> +The unboxing triggered in the return statement will throw an `NullPointerException`:
```suggestion
The unboxing triggered in the return statement will throw a `NullPointerException`:
```

2023-10-23 12:30 UTC, merged