Modify S3336: Change text to LaYC (APPSEC-1217)
SonarSource/rspec pull request #3340
Opened 2023-10-19 13:22 UTC by gaetan-ferry-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-23 15:19 UTC, loris-s-sonarsource requested changes
Mostly layout comments

2023-10-24 13:03 UTC, gaetan-ferry-sonarsource commented on rules/S3336/php/rule.adoc
> +impersonate their account, and take advantage of their privileges.
I am not too sure about the general structure of your suggestion. I always found the introduction sentence "Below are some real-world scenarios that illustrate some impacts of an attacker exploiting the vulnerability" to be very artificial and not very fluid.

2023-10-24 13:47 UTC, gaetan-ferry-sonarsource commented on rules/S3336/php/rule.adoc
> +Note that this parameter is off by default.
That's not really how I like it done but I guess I can change, especially for this kind of issue.

2023-10-24 15:56 UTC, loris-s-sonarsource approved these changes
LGTM

2023-10-25 07:37 UTC, merged