Modify rule S1081: Change text to education framework format (APPSEC-1210)
SonarSource/rspec pull request #3341
Opened 2023-10-19 14:14 UTC by sebastien-andrivet-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-20 19:06 UTC, jamie-anderson-sonarsource requested changes

2023-10-20 19:06 UTC, jamie-anderson-sonarsource commented on rules/S1081/rationale.adoc
> +An attacker typically provides input that exceeds the expected size. This could be through a text field in a user interface, a file that the program reads, or data sent over a network. The insecure f
The start of this is good, but the second sentence lacks clarity. It just says that the input is processed and bad things happen, without saying why those bad things happen.

The following paragraph talks about buffers, so I would like to see something in this paragraph that explains where the buffers fit in.

I would also like to see some mention of this being a buffer overflow vulnerability, because buffer overflows are something that people have heard about and are known to be bad.

```suggestion
An attacker typically provides input that exceeds the expected size. This could be through a text field in a user interface, a file that the program reads, or data sent over a network. The insecure function processes this input and places the result into a provided buffer.

If the input is larger than the buffer can handle, the insecure function will overwrite the memory following the buffer. This situation is known as a buffer overflow vulnerability.
```

2023-10-20 19:06 UTC, jamie-anderson-sonarsource commented on rules/S1081/impact.adoc
> +In some scenarios, insecure functions can lead to information disclosure. For instance, if an attacker can cause a buffer overflow, they might be able to read memory that they're not supposed to have
I probably wouldn't list this as a notable impact. The vulnerable functions that this rule targets result in a buffer overrun, i.e. overwriting data. There are ways to have this turn into an information disclosure vulnerability, but code execution or DoS are far more likely targets for an attacker.

2023-10-20 19:06 UTC, jamie-anderson-sonarsource commented on rules/S1081/impact.adoc
> +Using insecure functions can lead to serious security issues.
I don't know if this sentence is needed. Going straight into the subsections is probably sufficient.

2023-10-20 19:06 UTC, jamie-anderson-sonarsource commented on rules/S1081/cfamily/rule.adoc
>  == Resources
It would be worthwhile to add a link here to the Buffer Overflow page on Wikipedia.

```suggestion
== Resources

=== Articles & blog posts

* Wikipedia - https://en.wikipedia.org/wiki/Buffer_overflow[Buffer overflow]
```

2023-10-24 07:37 UTC, sebastien-andrivet-sonarsource commented on rules/S1081/cfamily/how-to-fix-it/buffer-overflow.adoc
> +  strcpy(buffer, input);
I have not used strncpy in the example because of its weird behavior with the terminal null character. strcpy_s is probably the proper way and it has been there since C11. I will modify the example to use strcpy_s

2023-10-24 07:38 UTC, sebastien-andrivet-sonarsource commented on rules/S1081/cfamily/how-to-fix-it/buffer-overflow.adoc
> +gets_s(str, sizeof(str));
You're right. Forget about that.

2023-10-24 08:13 UTC, sebastien-andrivet-sonarsource commented on rules/S1081/impact.adoc
> +Using insecure functions can lead to serious security issues.
A side-effect of using our OpenAI template.

2023-10-24 08:34 UTC, sebastien-andrivet-sonarsource commented on rules/S1081/impact.adoc
> +In some scenarios, insecure functions can lead to information disclosure. For instance, if an attacker can cause a buffer overflow, they might be able to read memory that they're not supposed to have
Yes, you're right

2023-10-24 16:34 UTC, jamie-anderson-sonarsource commented on rules/S1081/cfamily/how-to-fix-it/buffer-overflow.adoc
> +  strcpy(buffer, input);
The odd behaviour with the null termination character is why the final byte in the buffer is always set to 0. If the string was already null-terminated, it does nothing. If the string wasn't null-terminated, it will be now.

However, I agree that `strcpy_s` is the better option in the long term (for the compilers that support it).

2023-10-24 16:37 UTC, jamie-anderson-sonarsource requested changes

2023-10-24 16:37 UTC, jamie-anderson-sonarsource commented on rules/S1081/cfamily/how-to-fix-it/buffer-overflow.adoc
> +strcpy_s(buffer, sizeof buffer, input);
There's a syntax error here with the `sizeof` operator.
```suggestion
strcpy_s(buffer, sizeof(buffer), input);
```

2023-10-25 06:57 UTC, sebastien-andrivet-sonarsource commented on rules/S1081/cfamily/how-to-fix-it/buffer-overflow.adoc
> +strcpy_s(buffer, sizeof buffer, input);
This is not a syntax error. This is the proper way to use `sizeof` in this case:
* `sizeof expression` without parenthesis when using with an expression
* `sizeof(type)` with parenthesis when using with a type

2023-10-25 08:53 UTC, jamie-anderson-sonarsource commented on rules/S1081/cfamily/how-to-fix-it/buffer-overflow.adoc
> +strcpy_s(buffer, sizeof buffer, input);
Interesting! I wrote C/C++ for several years and don't recall ever seeing this version of `sizeof` being used. I probably did see third-party code that used it as a unary operator, but I've only ever written code that uses it as a function.

It is valid to use the operator as a function all the time. When used with an expression, the compiler simply places braces around the expression rather than treating them as part of the operator.

It's worth noting that Linux Torvalds [prefers the use of braces](https://lkml.org/lkml/2012/7/11/103):

> But "sizeof()" really *is* a function. It acts exactly like a function of it's argument. There is no reason to not treat it that way. Sure, the C standard *allows* you to not have parenthesis around an expression argument, but you should treat that as the parsing oddity it is, nothing more. There is zero reason not to have the parenthesis there.

Regardless, the code is valid as-is so I'm not going to advocate for it to be changed.

2023-10-25 08:54 UTC, jamie-anderson-sonarsource approved these changes
LGTM

2023-10-25 11:43 UTC, merged