Modify rule S5798: Change text to education framework format (APPSEC-1212)
SonarSource/rspec pull request #3345
Opened 2023-10-20 07:46 UTC by jamie-anderson-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-20 14:53 UTC, gaetan-ferry-sonarsource requested changes
LGTM in general with some typos and writing suggestions.

2023-10-20 14:53 UTC, gaetan-ferry-sonarsource commented on rules/S5798/cfamily/rule.adoc
> +If a buffer contains sensitive data, such as passwords or access tokens, it is good practice to overwrite the buffer before releasing the memory. This ensures that the sensitive data is not available
I think move this paragraph at the very beginning of the file (above "why is this an issue") would be great

2023-10-20 14:53 UTC, gaetan-ferry-sonarsource commented on rules/S5798/cfamily/rule.adoc
> +When the ``++memset++`` function is used to clear sensitive data from memory and that memory is released immediately afterwards, the compiler is allowed to optimize away the ``++memset++`` call. The
```suggestion
When the ``++memset++`` function is used to clear sensitive data from memory and that memory is released immediately afterward, the compiler is allowed to optimize away the ``++memset++`` call. The sensitive data will, therefore, remain in memory.
```

2023-10-20 14:53 UTC, gaetan-ferry-sonarsource commented on rules/S5798/cfamily/rule.adoc
> +The ``++memset_s++`` function is defined in annex K of C11 and is optional for C11 compilers. It will be available if the macro ``++__STDC_LIB_EXT1__++`` is defined, and you must be enabled by defini
This sentence does not sound very clear to me.

```suggestion
The ``++memset_s++`` function is defined in annex K of C11 and is optional for C11 compilers. It will only be available if the macro ``++__STDC_LIB_EXT1__++`` is defined, and it must be enabled by defining the macro ``++__STDC_WANT_LIB_EXT1__++`` before including ``++<string.h>++``.
```

2023-10-20 14:53 UTC, gaetan-ferry-sonarsource commented on rules/S5798/cfamily/rule.adoc
> +Other platform specific functions can perform the same operation, such as https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa366877(v=vs.85)?redirectedfrom=MSDN[SecureZeroMem
```suggestion
Other platform-specific functions can perform the same operation, such as https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa366877(v=vs.85)?redirectedfrom=MSDN[SecureZeroMemory] (Windows) or https://www.freebsd.org/cgi/man.cgi?query=explicit_bzero[explicit_bzero] (FreeBSD).
```

2023-10-20 14:53 UTC, gaetan-ferry-sonarsource commented on rules/S5798/cfamily/rule.adoc
> +* OWASP - https://www.owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure[Top 10 2017 Category A3 - Sensitive Data Exposure]
Would be nice to add the TOP10 2021 reference too (and adapt the metadata accordingly)

2023-10-20 16:45 UTC, jamie-anderson-sonarsource commented on rules/S5798/cfamily/rule.adoc
> +When the ``++memset++`` function is used to clear sensitive data from memory and that memory is released immediately afterwards, the compiler is allowed to optimize away the ``++memset++`` call. The
I pasted your suggested text into a Google Doc and let Grammarly run on it, and it suggested using `afterwards` instead of `afterward`.

2023-10-20 17:08 UTC, jamie-anderson-sonarsource commented on rules/S5798/cfamily/rule.adoc
> +* OWASP - https://www.owasp.org/www-project-top-ten/2017/A3_2017-Sensitive_Data_Exposure[Top 10 2017 Category A3 - Sensitive Data Exposure]
There isn't really a suitable category any more in OWASP 2021. The previous Sensitive Data Exposure category has been renamed to Cryptographic Failures, so it no longer covers the issue here.

There is an ASVS 4.0 category that covers this issue, so I'm going to add that.

2023-10-23 14:19 UTC, gaetan-ferry-sonarsource commented on rules/S5798/cfamily/rule.adoc
> +When the ``++memset++`` function is used to clear sensitive data from memory and that memory is released immediately afterwards, the compiler is allowed to optimize away the ``++memset++`` call. The
That's weird, I suggested this change based on a Grammarly notice :thinking:

2023-10-23 17:03 UTC, merged