Modify rule S5782: Change text to education framework format (APPSEC-1211)
SonarSource/rspec pull request #3346
Opened 2023-10-20 08:19 UTC by sebastien-andrivet-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-20 14:12 UTC, gaetan-ferry-sonarsource requested changes
LGTM in general with a few improvements suggestions.

2023-10-20 14:12 UTC, gaetan-ferry-sonarsource commented on rules/S5782/cfamily/how-to-fix-it/buffer-overflow.adoc
> +In the following code example, ``memchr`` is used to find the first occurrence of the ``@`` character in a buffer, ``array``. The second argument does not match the size of this buffer, so it may fin
I would have chosen a simpler example that does not require that many explanations. Let's say a dumb buffer overflow or a buffer overread where the consequence is direct.

2023-10-20 14:12 UTC, gaetan-ferry-sonarsource commented on rules/S5782/common/resources/standards.adoc
> +* OWASP - https://owasp.org/www-project-top-ten/2017/A9_2017-Using_Components_with_Known_Vulnerabilities[OWASP Top 10 2017 Category A9 - Using Components with Known Vulnerabilities]
I don't quite get this. The components are not intrinsically vulnerable. This would have worked if the issue was about `sprintf` for example. In the case of length controlled function, they are in fact the right thing to use. TBH I don't think any OWASP entry fits here except maybe simply "Injection" and I'm not too sure.

2023-10-20 14:41 UTC, sebastien-andrivet-sonarsource commented on rules/S5782/cfamily/how-to-fix-it/buffer-overflow.adoc
> +In the following code example, ``memchr`` is used to find the first occurrence of the ``@`` character in a buffer, ``array``. The second argument does not match the size of this buffer, so it may fin
I took the existing example. It is true that `memchr` is not so often used. I can find another example (maybe `read`) but I have to check that we effectively trigger for it.

2023-10-20 14:48 UTC, sebastien-andrivet-sonarsource commented on rules/S5782/impact.adoc
> +Functions related to sockets using the type ``++socklen_t++`` are not checked. This is because these functions are using a C-style polymorphic pattern using ``++union++``. It relies on a mismatch bet
This was in the existing RSPEC. From what I understand, since socklen_t is a union, it is difficult to properly analyze and follow which fields of the union are actually used. I can perhaps make it clearer, after some experimentation. Or perhaps simply remove the last sentence.

2023-10-24 12:37 UTC, gaetan-ferry-sonarsource commented on rules/S5782/impact.adoc
> +Functions related to sockets using the type ``++socklen_t++`` are not checked. This is because these functions are using a C-style polymorphic pattern using ``++union++``. It relies on a mismatch bet
I would suggest that you either:
* rewrite this paragraph to make it easier to understand
* remove everything
My opinion is that this section only makes sense if we provide information about why we exclude some functions. I don't think it adds value to just say "We exclude this because of false positive".

2023-10-24 12:53 UTC, gaetan-ferry-sonarsource commented on rules/S5782/cfamily/how-to-fix-it/buffer-overflow.adoc
> +In the following code example, ``memchr`` is used to find the first occurrence of the ``@`` character in a buffer, ``array``. The second argument does not match the size of this buffer, so it may fin
If you think changing this example is not worth it, fine by me.

2023-10-24 14:10 UTC, merged