Modify S3333: Change text to LaYC (APPSEC-1221)
SonarSource/rspec pull request #3347
Opened 2023-10-20 09:09 UTC by gaetan-ferry-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-24 16:27 UTC, jamie-anderson-sonarsource requested changes
There are some bits of unneeded wording at the start of sentences that should be removed.

2023-10-24 16:27 UTC, jamie-anderson-sonarsource commented on rules/S3333/php/rule.adoc
> +useless.
```suggestion
Adding the current directory, denoted by "`.`", to the `open_basedir`
configuration is also dangerous. It is possible to change the current directory
within PHP scripts by calling `chdir()`, effectively removing any protection.
```

2023-10-25 14:07 UTC, gaetan-ferry-sonarsource commented on rules/S3333/php/rule.adoc
> +system-critical or otherwise sensitive files.
I tried to come up with another way of saying it.

2023-10-25 14:56 UTC, jamie-anderson-sonarsource approved these changes
LGTM

2023-10-25 15:24 UTC, merged