Modify S3281(xml): Migrate to LayC
SonarSource/rspec pull request #3372
Opened 2023-10-26 10:30 UTC by loris-s-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-26 13:05 UTC, gaetan-ferry-sonarsource requested changes
LGTM with some small improvement suggestions.

2023-10-26 13:05 UTC, gaetan-ferry-sonarsource commented on rules/S3281/xml/rule.adoc
>        <interceptor-class>com.myco.ImportantInterceptor</interceptor-class> <!-- Noncompliant; will NOT be treated as default -->
I am not too sure what "Will not be treated as default" means here.

"by default"? "as a default interceptor"?

2023-10-26 13:05 UTC, gaetan-ferry-sonarsource commented on rules/S3281/xml/rule.adoc
>  * https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration[OWASP Top 10 2017 Category A6] - Security Misconfiguration
```suggestion
* OWASP - https://owasp.org/Top10/A05_2021-Security_Misconfiguration/[Top 10 2021 Category A5 - Security Misconfiguration]
* OWASP - https://owasp.org/www-project-top-ten/2017/A6_2017-Security_Misconfiguration[Top 10 2017 Category A6 - Security Misconfiguration]
```

2023-10-26 13:08 UTC, loris-s-sonarsource commented on rules/S3281/xml/rule.adoc
>        <interceptor-class>com.myco.ImportantInterceptor</interceptor-class> <!-- Noncompliant; will NOT be treated as default -->
Good question, I kept it but wondered the same

2023-10-26 13:09 UTC, loris-s-sonarsource commented on rules/S3281/xml/rule.adoc
>        <interceptor-class>com.myco.ImportantInterceptor</interceptor-class> <!-- Noncompliant; will NOT be treated as default -->
I'm just gonna remove that part hahaha

2023-10-27 07:32 UTC, gaetan-ferry-sonarsource approved these changes
LGTM

2023-10-27 08:12 UTC, merged