Modify S3394(COBOL): Migrate to LayC
SonarSource/rspec pull request #3376
Opened 2023-10-26 14:27 UTC by loris-s-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-26 14:35 UTC, loris-s-sonarsource commented on rules/S3394/cobol/rule.adoc
> +=== How does that work?
```suggestion
=== How does this work?
```

2023-10-26 14:36 UTC, loris-s-sonarsource commented on rules/S3394/cobol/rule.adoc
> +* OWASP - https://owasp.org/www-project-top-ten/2017/A1_2017-Injection[OWASP Top 10 2017 Category A1] - Injection
```suggestion
* OWASP - https://owasp.org/Top10/A03_2021-Injection/[Top 10 2021 Category A3] - Injection
* OWASP - https://owasp.org/www-project-top-ten/2017/A1_2017-Injection[Top 10 2017 Category A1] - Injection
```

2023-10-26 14:38 UTC, loris-s-sonarsource commented on rules/S3394/cobol/rule.adoc
> +==== Intrusion attacks
```suggestion
==== Injection attacks
```

2023-10-26 14:38 UTC, loris-s-sonarsource commented on rules/S3394/cobol/rule.adoc
> +element, without any validation or cleanup.
```suggestion
element, without any validation or sanitization.
```

2023-10-26 14:40 UTC, loris-s-sonarsource commented on rules/S3394/cobol/rule.adoc
> +input data is indeed a date.
```suggestion
Before using the data coming from ACCEPT, validate the data using custom
routines. These routines should check if the data meets the expected format and
type. For example, if you're expecting a number, the routine should check if the
input data is indeed a number.
```

2023-10-27 08:38 UTC, sebastien-andrivet-sonarsource requested changes
A suggestion to fix the COBOL program. Two links are not properly formatted.

2023-10-27 08:38 UTC, sebastien-andrivet-sonarsource commented on rules/S3394/cobol/rule.adoc
> +01 USER-INPUT PIC X(4).
The program is invalid, so I suggest to make it valid:

01 WS-NUMERIC PIC X VALUE 'N'.
```suggestion
01 WS-NUMERIC PIC X VALUE 'N'.
01 USER-INPUT PIC X(4).
```

2023-10-27 08:38 UTC, sebastien-andrivet-sonarsource commented on rules/S3394/cobol/rule.adoc
> +* OWASP - https://owasp.org/www-project-top-ten/2017/A1_2017-Injection[Top 10 2017 Category A1] - Injection
The links are not properly formatted.

```suggestion
* OWASP - https://owasp.org/Top10/A03_2021-Injection/[Top 10 2021 Category A3 - Injection]
* OWASP - https://owasp.org/www-project-top-ten/2017/A1_2017-Injection[Top 10 2017 Category A1 - Injection]
```

2023-10-27 11:36 UTC, sebastien-andrivet-sonarsource approved these changes
LGTM

2023-10-27 12:26 UTC, merged