Modify S109 for JS: document exclusions
SonarSource/rspec pull request #3380
Opened 2023-10-27 13:36 UTC by saberduck

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-27 14:15 UTC, ilia-kebets-sonarsource commented on rules/S109/javascript/rule.adoc
> +    - time related constants such as 24 and 60 are excluded
```suggestion
    - time-related constants such as 24 and 60 are excluded
```

2023-10-27 14:16 UTC, ilia-kebets-sonarsource commented on rules/S109/javascript/rule.adoc
> +    - numbers used bitwise operations are excluded
```suggestion
    - numbers used in JSX elements are excluded
    - enum values, default values, and other assignments are excluded
    - arguments to `parseInt()` and `JSON.stringify()` are excluded
    - numbers used in bitwise operations are excluded
```

2023-10-27 14:17 UTC, ilia-kebets-sonarsource commented on rules/S109/javascript/rule.adoc
> +    - numbers used in arithmetic operations are excluded -1, 0, 1. As well as powers of 2 and 10
```suggestion
    - numbers used in arithmetic operations are excluded
    - -1, 0, 1, as well as powers of 2 and 10
```

2023-10-27 14:18 UTC, ilia-kebets-sonarsource requested changes
A few change proposals. Check the expected format for the CI validation https://github.com/SonarSource/rspec/blob/master/docs/description.adoc#2-learn-as-you-code-rule-format

2023-10-27 14:28 UTC, saberduck commented on rules/S109/javascript/rule.adoc
> +    - numbers used in arithmetic operations are excluded -1, 0, 1. As well as powers of 2 and 10
I don't understand this suggestion, -1,0,1 are the numbers used in arithmetic, so it should not be another item in the list

2023-10-27 14:30 UTC, ilia-kebets-sonarsource commented on rules/S109/javascript/rule.adoc
> +    - numbers used in arithmetic operations are excluded -1, 0, 1. As well as powers of 2 and 10
So that would be correct?:
- The following numbers used in arithmetic operations: -1, 0, 1, as well as powers of 2 and 10

2023-10-30 07:28 UTC, ilia-kebets-sonarsource commented on rules/S109/javascript/rule.adoc
> +- numbers used in arithmetic operations are excluded -1, 0, 1. As well as powers of 2 and 10
```suggestion
- the following numbers used in arithmetic operations: -1, 0, 1, as well as powers of 2 and 10
```

2023-10-30 08:09 UTC, ilia-kebets-sonarsource approved these changes
LGTM

2023-10-30 08:17 UTC, merged