Modify S6218: add toString case to Kotlin description
SonarSource/rspec pull request #3384
Opened 2023-10-30 13:42 UTC by erwan-serandour-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-10-30 15:56 UTC, leonardo-pilastri-sonarsource requested changes
Just a renaming but it looks good to me!
Also, I noticed that the title of the rule only mentions the equals method, while it is reporting on 3 different methods if they are missing. Do we want to change the rule's title as well? I feel like even if more verbose, it would be more clear to mention all 3 of them.

2023-10-30 15:56 UTC, leonardo-pilastri-sonarsource commented on rules/S6218/kotlin/rule.adoc
> +This rule reports an issue if a record class has an array field and is not overriding ``++equals()++``, ``++hashcode()++`` or ``++toString()++`` methods.
Let's rename `record` into `data` classes
```suggestion
This rule reports an issue if a data class has an array field and is not overriding ``++equals()++``, ``++hashcode()++`` or ``++toString()++`` methods.
```

2023-10-30 16:09 UTC, erwan-serandour-sonarsource commented on rules/S6218/kotlin/rule.adoc
> +This rule reports an issue if a record class has an array field and is not overriding ``++equals()++``, ``++hashcode()++`` or ``++toString()++`` methods.
nice catch

2023-10-31 08:28 UTC, leonardo-pilastri-sonarsource approved these changes
It's ok for me, I let you decide if we want to change the title of the rule as well, to reflect the complete behavior of it

2023-10-31 10:45 UTC, closed without merging