Modify rule S6444: Convert from hotspot to vulnerability
SonarSource/rspec pull request #3398
Opened 2023-11-02 13:29 UTC by hendrik-buchwald-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-11-07 13:19 UTC, jamie-anderson-sonarsource requested changes
Just a couple of small issues.

2023-11-07 13:19 UTC, jamie-anderson-sonarsource commented on rules/S6444/impact.adoc
> +In more severe cases, a ReDoS attack can cause the system to become
It would be worth adding something here to explain what a ReDoS is, e.g.
* `ReDoS (regular expression denial of service)`
* `regular expression denial of service (ReDoS)`

2023-11-07 13:19 UTC, jamie-anderson-sonarsource commented on rules/S6444/common/resources/standards.adoc
> +* OWASP - https://owasp.org/www-project-top-ten/2017/A1_2017-Injection[Top 10 2017 - Category A1 - Injection]
This is not an injection issue and we should probably remove A1 as a vulnerability.

Injections require unexpected commands to be processed by some sort of command interpreter. A regex is not a command interpreter, just a fancy string processor.

The 2021 Top 10 list provides a mapping of CWEs to each of their categories, and the A03 Injection category doesn't contain any sign of CWE-400 or CWE-1333. If ReDoS was an injection issue, I would expect to see it listed.

2023-11-08 14:57 UTC, hendrik-buchwald-sonarsource commented on rules/S6444/impact.adoc
> +In more severe cases, a ReDoS attack can cause the system to become
Good point, updated.

2023-11-08 15:02 UTC, hendrik-buchwald-sonarsource commented on rules/S6444/common/resources/standards.adoc
> +* OWASP - https://owasp.org/www-project-top-ten/2017/A1_2017-Injection[Top 10 2017 - Category A1 - Injection]
It has the injection resource because not having a timeout usually becomes a problem when there is some kind of injection involved. For example, the regular expression is user-controlled or the regular expression is just bad and the value that is checked is user-controlled.

Considering that the `rationale.adoc` talks about user input I think it is fine to keep the reference personally. What do you think?

2023-11-09 15:40 UTC, jamie-anderson-sonarsource approved these changes
LGTM

2023-11-09 15:45 UTC, jamie-anderson-sonarsource commented on rules/S6444/common/resources/standards.adoc
> +* OWASP - https://owasp.org/www-project-top-ten/2017/A1_2017-Injection[Top 10 2017 - Category A1 - Injection]
If the regex is user-controlled, there is a potential for an injection vulnerability here. The regex parser is the command interpreter and the regex is the command.

If the regex is under developer control, the compiled regex is just a parser/evaluator. If it's inefficient, it's no different than any other inefficient algorithm (e.g. a `O(n^2)` bubble sort on a really large data set).

I'm still not 100% convinced that this is injection, but if you see that there's an argument for keeping it then I'm not going to push for its removal.

2025-01-23 11:12 UTC, Tim-Pohlmann commented
Hey @hendrik-buchwald-sonarsource what is the state of this PR? Is it still needed?

2025-01-23 12:20 UTC, hendrik-buchwald-sonarsource commented
> Hey @hendrik-buchwald-sonarsource what is the state of this PR? Is it still needed?

Hello @Tim-Pohlmann ,

it is not clear. To my knowledge, we will keep the hotspots now. But I wouldn't bet on it either. I would just keep this open for a bit.

2025-02-27 13:03 UTC, hendrik-buchwald-sonarsource commented
Closed as requested by @nils-werner-sonarsource .

2025-02-27 13:03 UTC, closed without merging