Modify rule S5852: Convert security hotspot to vulnerability (APPSEC-1271)
SonarSource/rspec pull request #3400
Opened 2023-11-05 22:30 UTC by jamie-anderson-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-11-06 18:10 UTC, jamie-anderson-sonarsource commented on rules/S5852/metadata.json
> -    ],
I decided to remove A1 because this is not an injection issue. A command is not being injected into a command interpreter.

I considered making this a 2021 A4 (Insecure Design) issue, but it's an implementation issue rather than a design issue so it doesn't fit that either.

2023-11-06 18:10 UTC, jamie-anderson-sonarsource commented on rules/S5852/common/fix/how-does-it-work.adoc
> +Avoid nested quantifiers to prevent this problem from occurring. If they cannot be avoided, ensure that the group has a starting or ending sequence that does not have a quantifier. This reduces the n
This part took forever to write succinctly. It was originally about 5 paragraphs of text that's slowly been worked down.

I'm happy to take suggestions on how this can be improved.

2023-11-06 18:10 UTC, jamie-anderson-sonarsource commented on rules/S5852/python/rule.adoc
> +pattern = re.compile("^(a+)++$");
I tried to use the same lookaround that works for JavaScript but it doesn't work on Python 3.10. The only solution I could find was to use the newer Python version and possessive grouping.

2023-11-06 18:10 UTC, jamie-anderson-sonarsource commented on rules/S5852/common/resources/external-guidelines.adoc
> +* Microsoft - https://docs.microsoft.com/en-us/dotnet/standard/base-types/backtracking-in-regular-expressions#backtracking-with-nested-optional-quantifiers[Backtracking with Nested Optional Quantifie
I'm not sure if this counts as an article or an external coding guideline. I treated it as a coding guideline given that it's in the .NET documentation.

2023-11-07 13:22 UTC, jamie-anderson-sonarsource commented on rules/S5852/common/resources/external-guidelines.adoc
> +* Microsoft - https://docs.microsoft.com/en-us/dotnet/standard/base-types/backtracking-in-regular-expressions#backtracking-with-nested-optional-quantifiers[Backtracking with Nested Optional Quantifie
Somehow I completely missed that there was a `Documentation` section in the resources. This has now been moved to that section.

2023-11-08 16:31 UTC, hendrik-buchwald-sonarsource requested changes
The text in general looks very nice. There are some small things to change though.

2023-11-08 16:31 UTC, hendrik-buchwald-sonarsource commented on rules/S5852/common/fix/how-does-it-work.adoc
> +* Solve the problem without regular expressions
```suggestion
* Solve the problem without regular expressions.
```

Since it is a full sentence and the other points also end with a dot, I would add a dot here as well.

2023-11-08 16:31 UTC, hendrik-buchwald-sonarsource commented on rules/S5852/common/fix/how-does-it-work.adoc
> +* It is often possible to make the regex infallible by making all the parts that could fail optional, which will prevent backtracking. Of course this means that you'll accept more strings than intend
```suggestion
* It is often possible to make the regex infallible by making all the parts that could fail optional, which will prevent backtracking. Of course this means that you will accept more strings than intended, but this can be handled by using capturing groups to check whether the optional parts were matched or not and then ignoring the match if they were not. For example the regex `+x*y+` could be replaced with `+x*(y)?+` and then the call to `+str.match(regex)+` could be replaced with `+matched = str.match(regex)+` and  `+matched[1] !== undefined+`.
```

2023-11-08 16:31 UTC, hendrik-buchwald-sonarsource commented on rules/S5852/common/fix/how-does-it-work.adoc
> +* Solve the problem without regular expressions
The 3 next points seem to be duplicates from the stuff above.

2023-11-08 16:31 UTC, hendrik-buchwald-sonarsource commented on rules/S5852/common/resources/external-guidelines.adoc
> +* Microsoft - https://docs.microsoft.com/en-us/dotnet/standard/base-types/backtracking-in-regular-expressions#backtracking-with-nested-optional-quantifiers[Backtracking with Nested Optional Quantifie
```suggestion
* Microsoft Documentation - https://docs.microsoft.com/en-us/dotnet/standard/base-types/backtracking-in-regular-expressions#backtracking-with-nested-optional-quantifiers[Backtracking with Nested Optional Quantifiers]
```

I would add this part, so it matches more whats in the [link-formatting doc](https://github.com/SonarSource/rspec/blob/master/docs/link_formatting.adoc).

2023-11-09 08:26 UTC, hendrik-buchwald-sonarsource commented
I forgot to mention, validate_asciidoc and validate_metadata are also failing.

2023-11-09 16:14 UTC, jamie-anderson-sonarsource commented on rules/S5852/common/fix/how-does-it-work.adoc
> +* Solve the problem without regular expressions
These were from the old rules file and should have been deleted. They're gone now.

2023-11-10 08:53 UTC, hendrik-buchwald-sonarsource approved these changes
It's a very nice explanation of a complex problem :+1:

2023-11-10 10:53 UTC, hendrik-buchwald-sonarsource requested changes
Missed something, see comment.

2023-11-10 10:53 UTC, hendrik-buchwald-sonarsource commented on rules/S5852/metadata.json
> +  "title": "Regular expressions should performance issues due to backtracking",
I just noticed the title, is this correct? It sounds a bit odd to me.

2023-11-10 11:09 UTC, jamie-anderson-sonarsource commented on rules/S5852/metadata.json
> +  "title": "Regular expressions should performance issues due to backtracking",
Yeah, it looks like I got half-way through rewriting that then got distracted. I've just pushed a new title in the `X should Y` format.

2023-11-10 11:32 UTC, hendrik-buchwald-sonarsource approved these changes
LGTM!

2025-03-05 07:26 UTC, nils-werner-sonarsource commented
Not WIP anymore. The branch is outdated, and the context might be changed. Link to branch and closed PR is given by implementation ticket.

2025-03-05 07:26 UTC, closed without merging