Modify rule S4507: Convert from hotspot to vulnerability
SonarSource/rspec pull request #3402
Opened 2023-11-06 13:49 UTC by hendrik-buchwald-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-11-07 14:31 UTC, jamie-anderson-sonarsource requested changes
I only have a few smaller changes I'd like to see.

2023-11-07 14:31 UTC, jamie-anderson-sonarsource commented on rules/S4507/docker/rule.adoc
> +Do not enable debug features globally.
This says what the fix is, not why it works.

```suggestion
Containers created from this image will have debug features disabled by default.
Individual containers can override these settings to enable debug features when
required.
```

2023-11-07 14:31 UTC, jamie-anderson-sonarsource commented on rules/S4507/flex/rule.adoc
> +expose sensitive information.
I would suggest a single word change here.

```suggestion
output sensitive information.
```

2023-11-08 13:22 UTC, hendrik-buchwald-sonarsource commented on rules/S4507/csharp/rule.adoc
> +* Microsoft - https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.hostingenvironmentextensions.isdevelopment[IsDevelopment() method]
```suggestion
* Microsoft Learn - https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.hostingenvironmentextensions.isdevelopment[IsDevelopment() method]
```

2023-11-08 13:23 UTC, hendrik-buchwald-sonarsource commented on rules/S4507/docker/rule.adoc
> +Do not enable debug features globally.
Good point.

2023-11-08 14:46 UTC, hendrik-buchwald-sonarsource commented on rules/S4507/xml/rule.adoc
> +* Android Documentation - https://developer.android.com/studio/publish/preparing[Prepare your app for release]
I have applied this change in another commit, just in case.

2023-11-09 15:37 UTC, jamie-anderson-sonarsource approved these changes
LGTM!

2025-02-27 13:03 UTC, closed without merging

2025-02-27 13:03 UTC, hendrik-buchwald-sonarsource commented
Closed as requested by @nils-werner-sonarsource .