Modify rule S4790: Convert hotspot to vulnerability (APPSEC-1278)
SonarSource/rspec pull request #3429
Opened 2023-11-09 15:35 UTC by jamie-anderson-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-11-10 10:52 UTC, hendrik-buchwald-sonarsource requested changes
Looks good in general, some minor details are left.

2023-11-10 10:52 UTC, hendrik-buchwald-sonarsource commented on rules/S4790/common/resources/standards.adoc
> +* OWASP  - https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[Top 10 2021 Category A2 - Cryptographic Failures]
```suggestion
* OWASP - https://owasp.org/Top10/A02_2021-Cryptographic_Failures/[Top 10 2021 Category A2 - Cryptographic Failures]
```

2023-11-10 10:52 UTC, hendrik-buchwald-sonarsource commented on rules/S4790/metadata.json
>    "title": "Using weak hashing algorithms is security-sensitive",
It will need a new title.

2023-11-10 11:07 UTC, jamie-anderson-sonarsource commented on rules/S4790/metadata.json
> +  "title": "Code should use collision-resistant hash functions",
I don't know if this is the best title but it follows the `X should Y` pattern that [we require](https://docs.sonarsource.com/sonarqube/latest/extension-guide/adding-coding-rules/#titles) for rule titles.

2023-11-10 11:25 UTC, hendrik-buchwald-sonarsource commented on rules/S4790/metadata.json
> +  "title": "Code should use collision-resistant hash functions",
How about "Cryptographic hashing functions should be collision-resistant"?

2023-11-10 11:26 UTC, hendrik-buchwald-sonarsource commented on rules/S4790/common/rationale.adoc
> +* The same input data always produces the same hash.
@jamie-anderson-sonarsource this one is still open

2023-11-10 11:27 UTC, jamie-anderson-sonarsource commented on rules/S4790/metadata.json
> +  "title": "Code should use collision-resistant hash functions",
That's a better title. I'll make the change.

2023-11-10 11:33 UTC, hendrik-buchwald-sonarsource approved these changes
LGTM!

2025-03-05 07:26 UTC, nils-werner-sonarsource commented
Not WIP anymore. The branch is outdated, and the context might be changed. Link to branch and closed PR is given by implementation ticket.

2025-03-05 07:26 UTC, closed without merging