BUILD-4131 Use GitHub token from Vault instead of sonartech api token
SonarSource/rspec pull request #3438
Opened 2023-11-14 14:47 UTC by sebastienvermeille

# BUILD-4131 Use GitHub token from Vault instead of sonartech api token

## Changes
* Update pipeline to no longer use a secret from Github and use Vault instead
   That way the token can be rotated easily

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-11-15 11:05 UTC, matemoln requested changes

2023-11-15 11:05 UTC, matemoln commented on .github/workflows/update_coverage.yml
```suggestion
    permissions:
      id-token: write # required for SonarSource/vault-action-wrapper
```

2023-11-15 11:05 UTC, matemoln commented on .github/workflows/update_coverage.yml
> +          development/kv/data/slack webhook | SLACK_WEBHOOK;
```suggestion
```

2023-11-15 11:39 UTC, sebastienvermeille commented on .github/workflows/update_coverage.yml
thank you

2023-11-16 08:19 UTC, sebastienvermeille commented
As discussed with @matemoln this project require more attention. I will close this PR for now

2023-11-16 08:19 UTC, closed without merging