CPP-4790 S1242: Improve documentation with 'using'
SonarSource/rspec pull request #3447
Opened 2023-11-17 16:25 UTC by loic-joly-sonarsource

Add a how to fix it section

@frederic-tingaud-sonarsource : I assigned this PR to you because you're used to this LAYC format.

2023-11-20 17:07 UTC, frederic-tingaud-sonarsource requested changes

2023-11-20 17:07 UTC, frederic-tingaud-sonarsource commented on rules/S1242/cfamily/rule.adoc
> +== How to fix it
I like the format you went with, but I think the official one is to have one
`=== Code examples` and multiple `==== Noncompliant code example` / `==== Compliant Solution` and intertwine these with the text.

2023-11-21 17:27 UTC, loic-joly-sonarsource commented on rules/S1242/cfamily/rule.adoc
>  Overriding happens when the inherited method is virtual and a method declared in the derived class uses the same identifier as well as the same signature (the return types can be different, as long a
Since this was already there, I'd like not to do it now, and defer it to the clean code principle initiative, wdyt?

2023-11-21 17:53 UTC, loic-joly-sonarsource commented on rules/S1242/cfamily/rule.adoc
> +== How to fix it
@John-Clifton-SonarSource 
We would like to continue with the RPSEC as written. Would you oppose that?

2023-11-22 15:45 UTC, loic-joly-sonarsource commented on rules/S1242/cfamily/rule.adoc
> +== How to fix it
@frederic-tingaud-sonarsource . I realized that the version I asked you to review was not the last one I had written. Could you give your opinion on the new update?

2023-11-22 15:45 UTC, loic-joly-sonarsource commented on rules/S1242/cfamily/rule.adoc
>  Overriding happens when the inherited method is virtual and a method declared in the derived class uses the same identifier as well as the same signature (the return types can be different, as long a
Link added.

2023-11-30 17:30 UTC, frederic-tingaud-sonarsource approved these changes

2024-02-02 21:08 UTC, merged