Modify rule S6802: Add a code example
SonarSource/rspec pull request #3452
Opened 2023-11-21 13:44 UTC by sebastien-marichal

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-11-21 16:44 UTC, antonioaversa requested changes
One blocking comment. The rest are primarily suggestions and optional improvements.

2023-11-21 16:44 UTC, antonioaversa commented on rules/S6802/csharp/rule.adoc
> +[source,cs]
I am not sure that `cs` is a valid language.
Moreover, we use `csharp` in all other examples and in all other rules.
In principle, however, it should be `razor`... that probably isn't supported (I don't see it in any razor-related rule).

2023-11-21 16:44 UTC, antonioaversa commented on rules/S6802/csharp/rule.adoc
> +
This empty line seems not necessary.

2023-11-21 16:44 UTC, antonioaversa commented on rules/S6802/csharp/rule.adoc
> +[source,cs]
I would probably merge the two source blocks (the following one, and the one below) in the `==== Compliant solution` section, even if that means that the `@* MyButton.razor *@` code would become entirely green.

And actually, I think it would be more correct that way since the specific proposed solution requires introducing this `MyButton.razor` component.

That requires giving a name to the component that defines the foreach, and where `MyButton` is being used. That should also be done in the non-compliant section. For instance `index.razor`.

2023-11-21 16:49 UTC, sebastien-marichal commented on rules/S6802/csharp/rule.adoc
> +[source,cs]
My mistake!

2023-11-22 13:56 UTC, antonioaversa approved these changes
LGTM!

2023-11-22 15:12 UTC, merged