Modify S2083(java): Improve the compliant sample
SonarSource/rspec pull request #3472
Opened 2023-11-29 14:58 UTC by loris-s-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2023-11-29 15:24 UTC, gaetan-ferry-sonarsource requested changes
There seem to be some confusion between Path and File.

2023-11-29 15:25 UTC, loris-s-sonarsource commented on rules/S2083/java/how-to-fix-it/java-se.adoc
> +        File file = new Path(targetPath + filename);
```suggestion
        File file = new File(targetPath + filename);
```

2023-11-30 10:39 UTC, loris-s-sonarsource commented on rules/S2083/java/how-to-fix-it/java-se.adoc
> +    Path targetPath = new File(targetDirectory).toPath().normalize();
```suggestion
    static private String targetDirectory = "/path/to/target/directory/";
    Path targetPath                       = new File(targetDirectory).toPath().normalize();
```

2023-11-30 10:41 UTC, loris-s-sonarsource commented on rules/S2083/java/how-to-fix-it/java-se.adoc
> +    Path targetPath                       = new File(targetDirectory).toPath().normalize();
```suggestion
    private static String targetDirectory = "/path/to/target/directory/";
    private static Path targetPath        = new File(targetDirectory).toPath().normalize();
```

2023-11-30 18:06 UTC, jamie-anderson-sonarsource approved these changes
I haven't had a chance to verify that this works as expected, but the normalization of the path ensures that it can't be any worse than the previous solution.

2023-11-30 18:07 UTC, merged

2023-11-30 18:09 UTC, jamie-anderson-sonarsource commented on rules/S2083/java/how-to-fix-it/java-se.adoc
> +        File file = new File(targetPath + filename);
We may want to consider whether the following code is more reliable:
```suggestion
        File file = new File(targetPath.resolve(filename));
```

From what I can gather, `.resolve()` is the equivalent of a `path.join()` call in other languages.