Avoid mismatch between security-standard in metadata and in the resources section (RULEAPI-798)
SonarSource/rspec pull request #3494
Opened 2023-12-13 09:57 UTC by pierre-loup-tristant-sonarsource

2023-12-15 16:44 UTC, jamie-anderson-sonarsource requested changes
I can see a relatively easy to way to change the code here so that it's usable for different types of security standards.

Even if this change isn't made the two regexes need to be converted to `r"..."` strings so that the backslash escapes don't cause warnings.

2023-12-15 16:44 UTC, jamie-anderson-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +        security_standards_links[standard].append(category)
The code here currently only works for the OWASP Top 10, and I know we wanted to extend this to CWE as well.

We can make this a but more generic by having each standard define a way to format the category.
```suggestion
        standard_id = result[1]
        if "convert_id" in standard_data and callable(standard_data["convert_id"]):
          standard_id = standard_data["convert_id"](standard_id)
        if standard not in security_standards_links.keys():
          security_standards_links[standard] = []
        security_standards_links[standard].append(standard_id)
```

2023-12-15 16:44 UTC, jamie-anderson-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +  "OWASP Top 10 2021": "https://(?:www\.)?owasp\.org/Top10/A(10|0[1-9])_2021-"
This data is needed to accommodate the per-standard category formatting:
```suggestion
  "OWASP": {
    "url_pattern": r"https://(?:www\.)?owasp\.org/www-project-top-ten/2017/A(10|[1-9])_2017-",
    "convert_id": lambda value: f"A{value.lstrip('0')}",
  },
  "OWASP Top 10 2021": {
    "url_pattern": r"https://(?:www\.)?owasp\.org/Top10/A(10|0[1-9])_2021-",
    "convert_id": lambda value: f"A{value.lstrip('0')}",
  },
```
It also fixes an issue where the regexes need to be `r"..."` strings so that the `\.` escapes work correctly.

2023-12-18 14:36 UTC, pierre-loup-tristant-sonarsource commented
Thank you for your review, I applied your suggestion.
I forgot that CWE was in the initial scope of the ticket and I moved it to a separate in [https://sonarsource.atlassian.net/browse/RULEAPI-799](https://sonarsource.atlassian.net/browse/RULEAPI-799).

2024-01-03 18:14 UTC, jamie-anderson-sonarsource approved these changes
These new changed LGTM

2024-01-16 15:18 UTC, pierre-loup-tristant-sonarsource commented
I will close this branch and create a new PR as there are too many conflicts because of [APPSEC-1134](https://sonarsource.atlassian.net/browse/APPSEC-1134). A new PR was created after rebasing the changed: https://github.com/SonarSource/rspec/pull/3537

2024-01-16 15:18 UTC, closed without merging