CPP-4080 Refresh and standardize CppCoreGuidelines references
SonarSource/rspec pull request #3514
Opened 2023-12-19 10:06 UTC by frederic-tingaud-sonarsource

2023-12-19 12:55 UTC, marco-antognini-sonarsource requested changes

2023-12-19 12:55 UTC, marco-antognini-sonarsource commented on rules/S1003/cfamily/rule.adoc
> +* https://github.com/isocpp/CppCoreGuidelines/blob/e49158a/CppCoreGuidelines.md#sf7-dont-write-using-namespace-at-global-scope-in-a-header-file[{cpp} Core Guidelines SF.7] - Don't write `using namesp
According to the [docs](https://github.com/SonarSource/rspec/blob/master/docs/link_formatting.adoc):

> The hyperlink to anything apart from other Sonar rules should be applied to just the document name, with the 'source' being left as plain text. The idea is that this makes it really easy for a user to understand the source before they click on anything.

So it should look like:

```asciidoc
* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/e49158a/CppCoreGuidelines.md#sf7-dont-write-using-namespace-at-global-scope-in-a-header-file[SF.7: Don't write `using namespace` at global scope in a header file]
```

2023-12-19 12:55 UTC, marco-antognini-sonarsource commented on rules/S1003/cfamily/rule.adoc
We should also update `docs/link_formatting.adoc` to refer to `e49158a`.

2023-12-19 12:55 UTC, marco-antognini-sonarsource commented on rules/S1003/cfamily/rule.adoc
Once this PR is done, please add in the merge commit message the script that you used (or a link to it). This may be useful again in the future.

2023-12-19 13:23 UTC, frederic-tingaud-sonarsource commented on rules/S1003/cfamily/rule.adoc
done

2023-12-19 13:23 UTC, frederic-tingaud-sonarsource commented on rules/S1003/cfamily/rule.adoc
> +* https://github.com/isocpp/CppCoreGuidelines/blob/e49158a/CppCoreGuidelines.md#sf7-dont-write-using-namespace-at-global-scope-in-a-header-file[{cpp} Core Guidelines SF.7] - Don't write `using namesp
Oops, fixed

2023-12-19 13:28 UTC, frederic-tingaud-sonarsource commented on rules/S1003/cfamily/rule.adoc
done

2023-12-19 15:03 UTC, marco-antognini-sonarsource requested changes
I like how this also fixes some typos in links and so on. Almost there. :-)

2023-12-19 15:03 UTC, marco-antognini-sonarsource commented on rules/S5524/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/e49158a/CppCoreGuidelines.md#cp21-use-stdlock-or-stdscoped_lock-to-acquire-multiple-mutexes[CP.21: Use `std::lock()` or `std
```
`mutex`es
```
does not render properly. I guess the escaping isn't as strict as in the text. Thankfully, you wrote a nice check for this. :D

The CI says:

> Validation of the asciidoc description failed due to 3 errors

2023-12-19 17:36 UTC, frederic-tingaud-sonarsource commented on rules/S5946/cfamily/rule.adoc
> +* https://github.com/isocpp/CppCoreGuidelines/blob/c553535fb8dda2839d13ab5f807ffbc66b63d67b/CppCoreGuidelines.md#sl50-avoid-endl[{cpp} Core Guidelines SL.io.50] - Avoid endl
Good catch! Fixed

2023-12-20 08:12 UTC, marco-antognini-sonarsource commented on rules/S5524/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/e49158a/CppCoreGuidelines.md#cp21-use-stdlock-or-stdscoped_lock-to-acquire-multiple-mutexes[CP.21: Use `std::lock()` or `std
I've fixed the remaining issues.

2023-12-20 08:29 UTC, marco-antognini-sonarsource commented on docs/link_formatting.adoc
Files in shared_content were not updated. I'll take care of it.

2023-12-20 08:35 UTC, marco-antognini-sonarsource commented on rules/S3687/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/e49158a/CppCoreGuidelines.md#cp200-use-volatile-only-to-talk-to-non-c-memory[CP.200: Use `volatile` only to talk to non-C++
Ideally, we should also spot `C++` in asciidoc when doing validation... I'll fix those manually.

2023-12-20 08:37 UTC, marco-antognini-sonarsource commented on rules/S5019/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/e49158a/CppCoreGuidelines.md#f54-when-writing-a-lambda-that-captures-this-or-any-class-data-member-dont-use--default-capture
This does not render properly.

2023-12-20 08:59 UTC, marco-antognini-sonarsource commented on rules/S5019/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/e49158a/CppCoreGuidelines.md#f54-when-writing-a-lambda-that-captures-this-or-any-class-data-member-dont-use--default-capture
Fixed.

2023-12-20 08:59 UTC, marco-antognini-sonarsource commented on rules/S3687/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://github.com/isocpp/CppCoreGuidelines/blob/e49158a/CppCoreGuidelines.md#cp200-use-volatile-only-to-talk-to-non-c-memory[CP.200: Use `volatile` only to talk to non-C++
We have other misuse of C++ but not in this PR. I've fixed only this one for now.

2023-12-20 09:08 UTC, merged