Modify rule S6504: Clarify intention of rule (APPSEC-1350)
SonarSource/rspec pull request #3528
Opened 2024-01-04 11:58 UTC by daniel-teuchert-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-01-05 11:18 UTC, egon-okerman-sonarsource requested changes
Most changes are fine, but it should be decided if this rule should be a vulnerability or a security hotspot before this is merged.

2024-01-05 11:18 UTC, egon-okerman-sonarsource commented on rules/S6504/docker/rule.adoc
> +Ownership or write permissions for a file or directory copied to the docker image have been assigned to a user other than root.
```suggestion
Ownership or write permissions for a file or directory copied to the Docker image have been assigned to a user other than root.
```

2024-01-05 11:18 UTC, egon-okerman-sonarsource commented on rules/S6504/docker/rule.adoc
>  Write permissions enable malicious actors, who got a foothold on the container,
```suggestion
Write permissions enable malicious actors, who have a foothold on the container,
```

2024-01-05 11:18 UTC, egon-okerman-sonarsource commented on rules/S6504/docker/rule.adoc
> +* A non-root user has write permissions or ownership for the resource.
"has (...) ownership for the resource" sounds a bit strange

2024-01-05 11:18 UTC, egon-okerman-sonarsource commented on rules/S6504/metadata.json
> +    "title": "Resources copied to an image should not be modifiable by non-root users",
"X should Y" is typically used as a title in vulnerabilities, but this is still a security hotspot.

2024-01-05 12:08 UTC, daniel-teuchert-sonarsource commented
> Most changes are fine, but it should be decided if this rule should be a vulnerability or a security hotspot before this is merged.

I would still keep this rule as a security hotspot.

2024-01-31 09:35 UTC, egon-okerman-sonarsource approved these changes
LGTM

2024-01-31 09:37 UTC, merged