Modify rule S6864: Update examples and removal of LimitRange for now
SonarSource/rspec pull request #3547
Opened 2024-01-23 13:52 UTC by navendu-barua-sonarsource

updates in S6864, S6869 and S6870
## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-01-23 14:53 UTC, hendrik-buchwald-sonarsource requested changes
Hey, I am not really in favor of most of these changes. Moving the noncompliant comments seems reasonable but some of the other changes I can't comprehend.

2024-01-23 14:53 UTC, hendrik-buchwald-sonarsource commented on rules/S6864/kubernetes/rule.adoc
> +or
I don't think it makes sense to have this additional example, even if we raise an issue for it, as the code just does not make sense.

2024-01-23 14:53 UTC, hendrik-buchwald-sonarsource commented on rules/S6864/kubernetes/rule.adoc
> -container. Alternatively, a default limit for a namespace can be set with
Even if we don't detect it yet, we should still keep this sentence as it is a valid way to not be vulnerable.

2024-01-23 14:58 UTC, hendrik-buchwald-sonarsource commented
`validate_asciidoc` is also failing.

2024-01-23 15:11 UTC, navendu-barua-sonarsource commented on rules/S6869/kubernetes/rule.adoc
> +          cpu: "0.5"
While trying to find some more examples [here](https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/),  I did not find one that was with floating `resources/limits/cpu`. This is why I changed it to string. Please let me know if the float values are also acceptable

2024-01-24 10:43 UTC, jonas-wielage-sonarsource approved these changes
LGTM, please see my suggestions before merging.

2024-01-24 10:43 UTC, jonas-wielage-sonarsource commented on rules/S6869/kubernetes/rule.adoc
> +          cpu: "0.5"
I would change it back to `0.5` as this is the usual way people define this property.

2024-01-24 10:43 UTC, jonas-wielage-sonarsource commented on rules/S6870/kubernetes/rule.adoc
> +[source,yaml,diff-id=2,diff-type=noncompliant]
The examples in this file with `diff-id=2` do not provide any additional value for me. Please remove them

2024-01-24 11:26 UTC, merged