Modify rule S6226: Disable rule on Windows
SonarSource/rspec pull request #364
Opened 2021-09-17 12:58 UTC by marco-antognini-sonarsource

2021-09-17 13:58 UTC, loic-joly-sonarsource requested changes

2021-09-17 13:58 UTC, loic-joly-sonarsource commented on rules/S6226/cfamily/rule.adoc
> +NOTE: This rule is disabled on Windows because ``\[[no_unique_address]]`` isn't supported by MSVC and Clang on this platform. See https://devblogs.microsoft.com/cppblog/msvc-cpp20-and-the-std-cpp20-s
Even thjough I like it, I don't think the NOTE tag has ever been tested in our RSPECs, I'm not sure how it could be rendered on all the platforms that display rspecs. So:
- Either you replace it be something less fancy.
- Or you make a note for future you to check it on SC, SQ, SL (different variants) and rules.sonarsource.org


```suggestion
NOTE: This rule is disabled on Windows because ``\[[no_unique_address]]`` isn't supported by MSVC and Clang on this platform. See https://devblogs.microsoft.com/cppblog/msvc-cpp20-and-the-std-cpp20-switch/#c20-no_unique_address[MSVC {cpp}20 and the `/std:c++20` Switch].
```
Or maybe less visually overwhelming:
```suggestion
NOTE: This rule is disabled on Windows because ``\[[no_unique_address]]`` https://devblogs.microsoft.com/cppblog/msvc-cpp20-and-the-std-cpp20-switch/#c20-no_unique_address[isn't well supported by MSVC and Clang on this platform].
```

2021-09-17 15:06 UTC, marco-antognini-sonarsource commented on rules/S6226/cfamily/rule.adoc
> +NOTE: This rule is disabled on Windows because ``\[[no_unique_address]]`` isn't supported by MSVC and Clang on this platform. See https://devblogs.microsoft.com/cppblog/msvc-cpp20-and-the-std-cpp20-s
Thanks. I went for your second solution, it is indeed better. As for `NOTE`, I think I will keep the scope of my ticket relatively tight for now. I'll keep it mind for another time, as it could be useful generally speaking.

2021-09-18 01:10 UTC, loic-joly-sonarsource approved these changes

2021-09-20 08:31 UTC, merged