CPP-4982,CPP-4913 S871 Mention that copies are allowed.
SonarSource/rspec pull request #3659
Opened 2024-02-19 15:37 UTC by tomasz-kaminski-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-02-19 15:40 UTC, tomasz-kaminski-sonarsource commented on rules/S871/cfamily/rule.adoc
> +  process(Clazz(c));        // Compliant, copy
```suggestion
  process(auto(c));        // Compliant, copy
```

2024-02-19 16:55 UTC, frederic-tingaud-sonarsource requested changes

2024-02-19 16:55 UTC, frederic-tingaud-sonarsource commented on rules/S871/cfamily/rule.adoc
> +Void casts are allowed:
```suggestion
This rule ignores void casts. They are a common pattern to express that an expression is dropped on purpose.

```

2024-02-19 16:55 UTC, frederic-tingaud-sonarsource commented on rules/S871/cfamily/rule.adoc
> +void(call()); // Compliant
```suggestion
(void)call(); // Compliant by exception
void(call()); // Compliant by exception
```

2024-02-19 16:55 UTC, frederic-tingaud-sonarsource commented on rules/S871/cfamily/rule.adoc
> +Furthermore functional cast can be used, in case when it lead to copy or constructor call:
```suggestion
Furthermore, this rule ignores functional casts when they lead to calls to constructors, because their purpose is clear and no dangerous conversion can happen.

```

2024-02-19 16:55 UTC, frederic-tingaud-sonarsource commented on rules/S871/cfamily/rule.adoc
> +  process((int)i);  // Noncompliant, C-style cast
```suggestion
  process(Clazz(1, 2));     // Compliant: constructor call
  process(Clazz(c));        // Compliant: copy
  process(auto(c));         // Compliant: copy
  process(Clazz(create())); // Compliant: copy
  process((Clazz)c);        // Noncompliant: C-Style cast
 
  process(int(i));  // Compliant: copy
  process(auto(i)); // Compliant: copy
  process((int)i);  // Noncompliant: C-style cast
```

2024-02-19 17:43 UTC, tomasz-kaminski-sonarsource commented on rules/S871/cfamily/rule.adoc
> +Furthermore, this rule ignores functional casts when they lead to calls to constructors, because their purpose is clear and no dangerous conversion can happen.
`int(10)` is not consructor, and `Class(create())` also not. I want to capture that, what about?
```suggestion
Furthermore, this rule ignores functional casts when creating an object of the same type (copy) of the object or leads to calls to constructors, because their purpose is clear and no dangerous conversion can happen.
```

2024-02-19 17:48 UTC, frederic-tingaud-sonarsource commented on rules/S871/cfamily/rule.adoc
> +Furthermore, this rule ignores functional casts when creating an object of the same type (copy) of the object or leads to calls to constructors, because their purpose is clear and no dangerous conver
I would suggest this:
```suggestion
Furthermore, this rule ignores functional casts when creating an object of the same type (copy) or when they lead to calls to a constructor. In those cases, the purpose is clear and no dangerous conversion can happen.
```

2024-02-20 08:57 UTC, frederic-tingaud-sonarsource approved these changes

2024-02-20 10:28 UTC, merged