CPP-4951 S5500 Exception for `return p` since C++23
SonarSource/rspec pull request #3663
Opened 2024-02-20 17:42 UTC by tomasz-kaminski-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-02-22 10:19 UTC, frederic-tingaud-sonarsource requested changes

2024-02-22 10:19 UTC, frederic-tingaud-sonarsource commented on rules/S5500/cfamily/rule.adoc
> +An implicit move in case of returning a parameter or variable of rvalue reference parameter,
```suggestion
When returning a parameter or variable of rvalue reference parameter, an implicit move
```

2024-02-22 10:19 UTC, frederic-tingaud-sonarsource commented on rules/S5500/cfamily/rule.adoc
> +was introduced in {cpp}20 timeframe, and retroactively applied to previous standards.
```suggestion
was introduced in {cpp}20, and retroactively applied to previous standards. 
```

2024-02-22 10:19 UTC, frederic-tingaud-sonarsource commented on rules/S5500/cfamily/rule.adoc
> +As a consequence, the behavior of such return statements is not consistent across complies
```suggestion
As a consequence, the behavior of such return statements is not consistent across compilers
```

2024-02-22 10:19 UTC, frederic-tingaud-sonarsource commented on rules/S5500/cfamily/rule.adoc
> +returns reference:
```suggestion
returns a reference:
```

2024-02-22 10:19 UTC, frederic-tingaud-sonarsource commented on rules/S5500/cfamily/rule.adoc
> +Furthermore, with the {cpp}20 rules, the implicit move is not triggered if the function
```suggestion

Furthermore, with the {cpp}20 rules, the implicit move is not triggered if the function
```

2024-02-22 10:19 UTC, frederic-tingaud-sonarsource commented on rules/S5500/cfamily/rule.adoc
> +In contrast to returning local (stack) variables, named return value optimization (NRVO)
```suggestion

In contrast to returning local (stack) variables, named return value optimization (NRVO)
```

2024-02-22 10:19 UTC, frederic-tingaud-sonarsource commented on rules/S5500/cfamily/rule.adoc
> +does not apply to function parameters, so such explicit `std::move`call has no impact on optimizations.
```suggestion
does not apply to function parameters, so an explicit `std::move`call has no impact on optimizations.
```

2024-02-22 10:36 UTC, tomasz-kaminski-sonarsource commented on rules/S5500/cfamily/rule.adoc
> +When returning a parameter or variable of rvalue reference parameter, an implicit move
```suggestion
When returning a parameter or variable of rvalue reference type, an implicit move
```

2024-02-22 10:36 UTC, frederic-tingaud-sonarsource approved these changes

2024-02-22 10:45 UTC, frederic-tingaud-sonarsource requested changes

2024-02-22 10:45 UTC, frederic-tingaud-sonarsource commented on rules/S5500/cfamily/rule.adoc
> +does not apply to function parameters, so an explicit `std::move`call has no impact on optimizations.
```suggestion
does not apply to function parameters, so an explicit `std::move` call has no impact on optimizations.
```

2024-02-23 15:46 UTC, frederic-tingaud-sonarsource approved these changes

2024-02-26 07:57 UTC, merged