CPP-4991 S5274 Rework rule to cover only optimization inhibiting moves and not all redundant move
SonarSource/rspec pull request #3684
Opened 2024-02-26 09:05 UTC by tomasz-kaminski-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-02-26 15:17 UTC, frederic-tingaud-sonarsource requested changes

2024-02-26 15:17 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +However, in a case when the class does not provide such a constructor,
```suggestion
However, when the class does not provide such a constructor,
```

2024-02-26 15:17 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +  process(create());            // Complaint
```suggestion
  process(create());            // Compliant
```

2024-02-26 15:17 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +  processB(create());            // Complaint
```suggestion
  processB(create());            // Compliant
```

2024-02-26 15:17 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +the programmer would need to review and update all call sides and process functions,
```suggestion
the maintainers would need to review and update all call sites and process functions,
```

2024-02-26 15:17 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +To fully benefit from performance benefits change,
```suggestion
To fully benefit from the performance benefits of this change, 
```

2024-02-26 15:17 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +Moreover, if the parameter is a reference of the type to which the converted object can be converted,
```suggestion
Moreover, if the parameter is a reference to a type to which the converted object can be converted,
```

2024-02-26 15:17 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +The requirements from performing an implicit move where relaxed in {cpp}20 and {cpp}23 standards,
```suggestion
The requirements from performing an implicit move were relaxed in {cpp}20 and {cpp}23 standards,
```

2024-02-26 15:17 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +Remove  call to `std::move` flagged by the rule.
```suggestion
Remove call to `std::move` flagged by the rule.
```

2024-02-26 15:40 UTC, tomasz-kaminski-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +  asParam(createA());        // Noncompliant
Yes, added.

2024-02-26 15:40 UTC, tomasz-kaminski-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +  return A();                // Noncompliant
Yes

2024-02-27 10:13 UTC, frederic-tingaud-sonarsource approved these changes

2024-02-27 10:13 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +thus it is not applicable if the parameter is reference to the same type:
```suggestion
The copy elision optimization happens only if a new value is produced from the source,
not if the parameter is a reference to the same type:
```

2024-02-27 10:13 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +  process(std::move(create())); // Noncompliant, makes changes non-local
The sample already mentions what will be explained in the next paragraph. I think that is a bit confusing. Perhaps it should be moved after the explanation about maintainability?

2024-02-27 10:13 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +then copy elision may still happen when initializing the parameter of the converting constructor.
```suggestion
Moreover, if the parameter is a reference to a type to which the argument is converted,
then copy elision may still happen when calling the converting constructor.
```

2024-02-27 10:13 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +a call to `std::move` may or not be redundant in the return statement,
```suggestion
As a consequence depending on the standard and compiler versions, 
a call to `std::move` may or may not be redundant in the return statement,
```

2024-02-27 10:13 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +Remove call to `std::move` flagged by the rule.
```suggestion
Remove the call to `std::move` flagged by the rule.
```

2024-02-27 10:13 UTC, frederic-tingaud-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +A f() {
The function doesn't return `A` anymore.

2024-02-27 10:19 UTC, tomasz-kaminski-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +  process(std::move(create())); // Noncompliant, makes changes non-local
The process here is taken by reference, so this is an illustration for the previous paragraph. Yes, the Noncomplain have a explanation referring to what is later. I can remove it, if you would consider that cleaner.

2024-02-27 10:20 UTC, tomasz-kaminski-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +A f() {
Fixed

2024-02-27 10:24 UTC, tomasz-kaminski-sonarsource commented on rules/S5274/cfamily/rule.adoc
> +  process(std::move(create())); // Noncompliant, makes changes non-local
I would find it more confusing if that example would be after a paragraph that explained the consequences of changing something to be by value. And the section title already says that the issue is raised.

2024-02-27 10:52 UTC, merged