Modify rule S2053: Add better code examples and more how to fix sections
SonarSource/rspec pull request #3704
Opened 2024-02-28 13:54 UTC by gaetan-ferry-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-03-05 18:26 UTC, jamie-anderson-sonarsource requested changes

2024-03-05 18:26 UTC, jamie-anderson-sonarsource commented on rules/S2053/python/how-to-fix-it/cryptodome.adoc
> +salt = secrets.token_bytes(32)
I'm divided on the use of `secrets.token_bytes()` for this purpose.

According to the documentation for the `token_*` functions:
> The [secrets](https://docs.python.org/3/library/secrets.html#module-secrets) module provides functions for generating secure tokens, suitable for applications such as password resets, hard-to-guess URLs, and similar.

These functions are not really supposed to be used for unspecified random value generation. However, because they do return a cryptographically-secure sequence of bytes (because they wrap `os.urandom()` behind the scenes) they often get used for generating things like keys, salts and nonces.

I've done quite a bit of reading on this, including the email chain behind [PEP-506](https://peps.python.org/pep-0506/), and nothing clarifies the best option here.

I was going to suggest the use of `secrets.SystemRandom` / `random.SystemRandom` here but the class does not provide a method of generating random bytes.

I wish there was a better option here, but I would suggest using `os.urandom()` for generating any random value that isn't strictly being used as a token.

2024-03-05 18:26 UTC, jamie-anderson-sonarsource commented on rules/S2053/python/how-to-fix-it/cryptodome.adoc
> +cryptographically secure pseudo random number generator.
If we're ok with the use of `secrets.token_bytes` as a function:
```suggestion
length by calling the `secrets.token_bytes` function. This function internally
uses a cryptographically secure pseudo-random number generator.
```

If we switch to `os.urandom`:
```suggestion
length by calling the `os.urandom` function. This function generates random
sequences of bytes that are suitable for cryptographic use.
```

2024-03-05 18:26 UTC, jamie-anderson-sonarsource commented on rules/S2053/python/how-to-fix-it/cryptography.adoc
> +salt = secrets.token_bytes(32)
See my previous comment on this matter.

2024-03-05 18:26 UTC, jamie-anderson-sonarsource commented on rules/S2053/python/how-to-fix-it/cryptography.adoc
> +cryptographically secure pseudo random number generator.
See my previous comment on this matter.

2024-03-05 18:26 UTC, jamie-anderson-sonarsource commented on rules/S2053/python/how-to-fix-it/std.adoc
> +salt = secrets.token_bytes(32)
See my previous comment on this matter.

2024-03-05 18:26 UTC, jamie-anderson-sonarsource commented on rules/S2053/python/how-to-fix-it/std.adoc
>  cryptographically secure pseudo random number generator.
See my previous comment on this matter.

2024-03-07 10:59 UTC, egon-okerman-sonarsource commented on rules/S2053/python/how-to-fix-it/cryptodome.adoc
> +salt = secrets.token_bytes(32)
`secrets.token_bytes()` really just calls `os.urandom()` behind the scenes and does nothing more, so there is no functional difference at all. Considering `secrets` was added in Python 3.6, I would prefer `os.urandom()` only because of its better version support.

2024-03-11 11:03 UTC, gaetan-ferry-sonarsource commented on rules/S2053/python/how-to-fix-it/cryptodome.adoc
> +salt = secrets.token_bytes(32)
`token_bytes` calls `random.SystemRandom` who is only a wrapper to `os.urandom`. The `os.urandom` provides this notice:

> See also
>
> The [secrets](https://docs.python.org/3/library/secrets.html#module-secrets) module provides higher-level functions.
> For an easy-to-use interface to the random number generator provided by your platform, please see
> [random.SystemRandom](https://docs.python.org/3/library/random.html#random.SystemRandom).

I originally thought it would be better to point to a higher-level library, for example, to make sure people are aware that they exist and end up using them for general secure RNG use cases. For example, I would not like people to rely on `os.urandom` for generating numbers in a range or choosing a random array element or shuffling something, etc.

For this random.SystemRandom might be better suited. However, I like that `token_bytes` has a sane default key size.

WDYT?

2024-03-11 11:40 UTC, egon-okerman-sonarsource commented on rules/S2053/python/how-to-fix-it/cryptodome.adoc
> +salt = secrets.token_bytes(32)
> The os.urandom provides this notice
I think this is mostly a reference to methods like `token_hex` or `token_urlsafe` which are higher-level than `os.urandom`. Like you said, `secrets.token_bytes`, `random.SystemRandom` and `os.urandom` are different API calls with the same result.

> However, I like that `token_bytes` has a sane default key size.
This seems fine to me. Let's go with that.

2024-03-12 15:13 UTC, egon-okerman-sonarsource approved these changes
LGTM

2024-03-15 15:25 UTC, jamie-anderson-sonarsource approved these changes
LGTM after the discussion around `secrets.token_bytes()`

2024-03-18 08:32 UTC, merged