Modify rules S6185,S6484,S6494,S6495: RSPEC improvements (CPP-5056)
SonarSource/rspec pull request #3816
Opened 2024-03-26 08:25 UTC by marco-antognini-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-03-26 13:53 UTC, loic-joly-sonarsource requested changes

2024-03-26 13:53 UTC, loic-joly-sonarsource commented on rules/S6484/cfamily/rule.adoc
> +`std::format` accepts a format string composed of ordinary text and replacement fields (surrounded with `{}`) that are replaced with a textual representation of the following `std::format` arguments.
For me, "the following" means you're going to describe them in the next sentence...
```suggestion
`std::format` accepts a format string composed of ordinary text and replacement fields (surrounded with `{}`) that are replaced with a textual representation of the remaining `std::format` arguments.
```

2024-03-26 13:53 UTC, loic-joly-sonarsource commented on rules/S6494/cfamily/rule.adoc
> +In addition, `std::vformat`, `std::vprint_unicode`, and `std::vprint_nonunicode` report validation failures by throwing an instance of `std::format_error`.
Not sure of the "Firstly" "In addition" here. 
```suggestion
{cpp} formatting facilities perform validation of the format string against the type of the formatted argument. If the validation fails, it is reported as a compilation error for the calls of `std::print` and `std::format`. `std::vformat`, `std::vprint_unicode`, and `std::vprint_nonunicode`, that can't validate at compile-time, report failures by throwing an instance of `std::format_error`.
```

2024-03-26 13:53 UTC, loic-joly-sonarsource commented on rules/S6494/cfamily/rule.adoc
>  * {cpp} reference - https://en.cppreference.com/w/cpp/io/basic_ostream/vprint_nonunicode[`std::vprint_nonunicode(std::ostream)`]
Why only those 3? They don't seem the most relevant...
Maybe a global link to https://en.cppreference.com/w/cpp/utility/format

2024-03-26 18:13 UTC, marco-antognini-sonarsource commented on rules/S6494/cfamily/rule.adoc
> +In addition, `std::vformat`, `std::vprint_unicode`, and `std::vprint_nonunicode` report validation failures by throwing an instance of `std::format_error`.
Sounds better, indeed. One nit though: "that can't validate at at compile-time" --> it's a design choice. I would rephrase it a bit:

```suggestion
{cpp} formatting facilities perform validation of the format string against the type of the formatted argument. If the validation fails, it is reported as a compilation error for the calls of `std::print` and `std::format`. When the format string is not available at compile-time, `std::vformat`, `std::vprint_unicode`, and `std::vprint_nonunicode` can be used. They will report failures at runtime by throwing an instance of `std::format_error`.
```

WDYT?

2024-03-26 18:22 UTC, marco-antognini-sonarsource commented on rules/S6494/cfamily/rule.adoc
>  * {cpp} reference - https://en.cppreference.com/w/cpp/io/basic_ostream/vprint_nonunicode[`std::vprint_nonunicode(std::ostream)`]
The last two are from `<ostream>` and are not available from the page you linked.
I'm not sure how important that is, though. Maybe we should have fewer links...

What about a link to:
 * std::format
 * std::print
 * std::print(ostream)
 * <format>
 * <print>

and we "ignore" the rest here, assuming the reader can navigate to them?

2024-03-27 09:10 UTC, loic-joly-sonarsource commented on rules/S6494/cfamily/rule.adoc
> +In addition, `std::vformat`, `std::vprint_unicode`, and `std::vprint_nonunicode` report validation failures by throwing an instance of `std::format_error`.
LGTM

2024-03-27 09:16 UTC, marco-antognini-sonarsource commented on rules/S6185/cfamily/rule.adoc
> +``++std::format++`` is strictly superior. It is more efficient because it constructs the string in place instead of copying substrings one by one. It is also often shorter and easier to read because
It was correct before...
```suggestion
``++std::format++`` is strictly superior. It is more efficient because it constructs the string in-place instead of copying substrings one by one. It is also often shorter and easier to read because the format pattern is presented in a single piece and not scattered across the concatenation expression.
```

2024-03-27 09:19 UTC, loic-joly-sonarsource commented on rules/S6494/cfamily/rule.adoc
>  * {cpp} reference - https://en.cppreference.com/w/cpp/io/basic_ostream/vprint_nonunicode[`std::vprint_nonunicode(std::ostream)`]
I think we need `format_to`, because we use it so much in the example... (or should we change the example? For instance by returning a string?
I'm not sure of the value of having both  `std::format` and `<format>`, it's easy to navigate from one to thee other.

2024-03-27 09:28 UTC, marco-antognini-sonarsource commented on rules/S6494/cfamily/rule.adoc
>  * {cpp} reference - https://en.cppreference.com/w/cpp/io/basic_ostream/vprint_nonunicode[`std::vprint_nonunicode(std::ostream)`]
- links: std::print(ostream) `<format>` `<print>`
- update example: keep same interface with format_to_n, + alternative with format

2024-03-27 10:29 UTC, marco-antognini-sonarsource commented on rules/S6494/cfamily/rule.adoc
>  * {cpp} reference - https://en.cppreference.com/w/cpp/io/basic_ostream/vprint_nonunicode[`std::vprint_nonunicode(std::ostream)`]
1. done.
2. re-reading the examples, I found more issues. I split them into smaller functions and gave one example of redesign.

2024-03-27 10:45 UTC, loic-joly-sonarsource approved these changes
The examples are much better now.

2024-03-27 10:45 UTC, loic-joly-sonarsource commented on rules/S6494/cfamily/rule.adoc
> +void printTextIntoBuffer(char* out) {
```suggestion
void printTextIntoBuffer(char* out) { // Assumes the buffer pointed-to by out is large enough
```

2024-03-27 10:45 UTC, loic-joly-sonarsource commented on rules/S6494/cfamily/rule.adoc
> +void printTextIntoBuffer(char* out) {
```suggestion
void printTextIntoBuffer(char* out) { // Assumes the buffer pointed-to by out is large enough
```

2024-03-27 10:51 UTC, marco-antognini-sonarsource commented on rules/S6494/cfamily/rule.adoc
> +void printTextIntoBuffer(char* out) {
Makes sense. I've added the comment on a separate line to keep them short. ad02ba96e8

2024-03-27 10:58 UTC, merged