Make sure a label is added to each PR
SonarSource/rspec pull request #3834
Opened 2024-03-28 13:38 UTC by loic-joly-sonarsource

2024-03-28 15:12 UTC, frederic-tingaud-sonarsource requested changes

2024-03-28 15:12 UTC, frederic-tingaud-sonarsource commented on .github/workflows/update_coverage.yml
> +    - cron: '17 0 * * *'
This change shouldn't be here

2024-03-28 15:12 UTC, frederic-tingaud-sonarsource commented on .github/workflows/ensure_label.yml
> +    runs-on: ubuntu-20.04
Most of our workflows use ubuntu-latest and I think this one would benefit from it.
```suggestion
    runs-on: ubuntu-latest
```

2024-03-28 16:35 UTC, loic-joly-sonarsource commented on .github/workflows/update_coverage.yml
> +    - cron: '17 0 * * *'
Agreed... Not sure how it appeared...

2024-03-29 09:10 UTC, frederic-tingaud-sonarsource approved these changes

2024-03-29 09:47 UTC, merged