RULEAPI-657: Set up a cron job for rule_coverage/coverage.py
SonarSource/rspec pull request #385
Opened 2021-09-21 14:34 UTC by arseniy-sonar

It is tricky to test this script because it is supposed to run on the 'master' branch and on schedule.
If you want to try it out, you can change 
```
on:
  schedule:
    - cron: '17 0 * * *'
```
to 
```
on: push
```
and replace all mentions of `master` with this branch (`az/RULEAPI-657-coverage-cron`) or another branch if you want to preserve this one - the script does push an updated coverage file to the target branch.
I also recommend changing the name of the CI task it waits for. `validate_asciidoc` takes a long time, you can use any other task, e.g., `tooling_checks`: GitHub will not prevent the script from pushing before CI completes if your target branch is not `master`.

2021-09-22 14:02 UTC, andrei-epure-sonarsource requested changes
some minor questions

2021-09-22 14:48 UTC, arseniy-sonar commented on .github/workflows/update_coverage.yml
> +    - cron: '17 0 * * *'
To avoid the churn of lazy schedules set for midnight :)

2021-09-22 14:49 UTC, arseniy-sonar commented on .github/workflows/update_coverage.yml
> +        git push -f origin $TMP_BRANCH
I think --force-with-lease should suffice, indeed. will change that.
```suggestion
        git push --force-with-lease origin $TMP_BRANCH
```

2021-09-22 14:51 UTC, arseniy-sonar commented on .github/workflows/update_coverage.yml
> +        git push -f origin $TMP_BRANCH
Force is here for robustness against a possibly failed previous job that did not delete the branch.

2021-09-22 15:14 UTC, arseniy-sonar commented on rule_coverage/notify_failure.py
> +notify_slack('ERROR: failed to update rule coverage.\n' +
Done.

2021-09-23 08:14 UTC, andrei-epure-sonarsource approved these changes
LGTM! 🎉

2021-09-23 08:15 UTC, merged