Modify S2365: Fix code examples
SonarSource/rspec pull request #3923
Opened 2024-05-06 13:58 UTC by sebastien-marichal

See https://github.com/SonarSource/sonar-dotnet/issues/9254

2024-05-06 15:31 UTC, CristianAmbrosini requested changes

2024-05-06 15:31 UTC, CristianAmbrosini commented on rules/S2365/csharp/rule.adoc
>  private List<string> _foo = new List<string> { "a", "b", "c" };
(optional) What about adding using statements as well? Specifically the System.Linq
```cs
using System.Collections.Generic;
using System.Linq;
```

2024-05-06 15:31 UTC, CristianAmbrosini commented on rules/S2365/csharp/rule.adoc
> +private string[] _bar = new string[] { "a", "b", "c" };
I would take this opportunity to change the field names as well, they should not begin with an underscore IMO

2024-05-06 15:31 UTC, CristianAmbrosini commented on rules/S2365/vbnet/rule.adoc
> +Private _foo As New List(Of String) From {"a", "b", "c"}
Field names

2024-05-07 07:43 UTC, sebastien-marichal commented on rules/S2365/csharp/rule.adoc
>  private List<string> _foo = new List<string> { "a", "b", "c" };
The example context is implicitly set to a class.
Adding usings would be incorrect. I would rather not add them.

2024-05-07 09:55 UTC, CristianAmbrosini approved these changes
LGTM!

2024-05-07 10:27 UTC, merged