Modify rule S6973: Adding PyTorch optimizers
SonarSource/rspec pull request #3956
Opened 2024-06-03 13:46 UTC by joke1196

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-06-04 07:42 UTC, ghislainpiot requested changes
The bulk of the rule is good, it is just small details and things I did not catch in the previous sprint.

2024-06-04 07:42 UTC, ghislainpiot commented on rules/S6973/python/how-to-fix-it/pytorch.adoc
> +optimizer = Adadelta(model.parameters(), lr = 0.001, weight_decay = 0.003) # Compliant
nit: We might want to switch the exemple to Adam/AdamW to make it more relatable to users ?

2024-06-04 07:42 UTC, ghislainpiot commented on rules/S6973/python/rule.adoc
> +This rule raises an issue when a machine learning model or optimizer is instantiated without specifying the important hyperparameters.
I'm sorry I didn't catch this last time, but I don't think we should call it a "model," especially now that we are including Pytorch in the rule.

2024-06-04 07:42 UTC, ghislainpiot commented on rules/S6973/python/rule.adoc
>  [cols="1,1"]
I am also sorry for not catching this last time, but I find the table hard to read. It's the same for the `numpy.Generator` rule. I don't know how we could fix it however.

2024-06-04 09:57 UTC, joke1196 commented on rules/S6973/python/rule.adoc
>  [cols="1,1"]
I am not sure we can do much as some formatting features are disabled it seems, i.e. striping even or odd rows

2024-06-04 11:44 UTC, ghislainpiot approved these changes
LGTM!

2024-06-12 18:20 UTC, jean-jimbo-sonarsource commented on rules/S6973/python/rule.adoc
>  [cols="1,1"]
I'll follow up on formatting tables.

2024-06-12 18:22 UTC, jean-jimbo-sonarsource commented on rules/S6973/python/rule.adoc
> +When instantiating an estimator or an optimizer, it will use default values for the hyperparameters that are not specified.
Suggestion: "When instantiating an estimator or an optimizer, default values for any hyperparameters that are not specified will be used."

2024-06-12 18:22 UTC, jean-jimbo-sonarsource requested changes
Suggestion

2024-09-23 14:53 UTC, merged