S1694: Promote C# to SonarWay and remove protected constructor
SonarSource/rspec pull request #3960
Opened 2024-06-04 09:15 UTC by pavel-mikula-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-06-05 08:54 UTC, CristianAmbrosini requested changes
Let's add a How to Fix it and Resources section

2024-06-05 08:54 UTC, CristianAmbrosini commented on rules/S1694/csharp/rule.adoc
>  === Noncompliant code example
To promote it to SonarWay we should also improve a bit the documentation to LaYC standards. You can find the educational standards [here](https://github.com/SonarSource/rspec/blob/master/docs/description.adoc#3-education-format).

2024-06-05 08:54 UTC, CristianAmbrosini commented on rules/S1694/csharp/rule.adoc
>  === Noncompliant code example
```suggestion
=== Code examples
==== Noncompliant code example
[source,csharp,diff-id=1,diff-type=noncompliant]
...
```

2024-06-10 07:58 UTC, CristianAmbrosini approved these changes
Looks good! Left a few minor comments and 1 question

2024-06-10 07:58 UTC, CristianAmbrosini commented on rules/S1694/csharp/rule.adoc
> +* https://en.wikipedia.org/wiki/Polymorphism_(computer_science)[**Polymorphism**]: Interfaces allow you to use polymorphism, which means you can use an interface type to refer to any object that impl
Isn't this the same for abstract classes? [Example](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUBQCID2AyjWAKYIAWsA5gBQxMDuAAlrcAlCIDc1eoxbsY3XoIDCEBFzGTK5fABYh05m05cAgjCiQANgIjmrIgQF4AfDbsRLAOgCyEANZMDOgY6poU+ADMNsAAzgjIEADGCAJEAmYWHhQA3hQC+alRELHxSSm6Ar4BQTAhEhQAvhThUWnCAiDp7pY5eQWRAjQAbkzIyFAYTKl6VYE0wep9+bnkBWupxACcXABEAOo0NABmAIQ79asFTeTXLamEAiopnRlWvZf5A8Oj45PTlf45gsREsBCt1v0trtvEwaHwzhc1tcGkA===)

2024-06-10 07:58 UTC, CristianAmbrosini commented on rules/S1694/csharp/rule.adoc
> +`abstract` classes that contain non-abstract methods, in addition to `abstract` ones, cannot easily be converted to interfaces, and are not the subject of this rule:
Should we mention `fields` as well?

2024-06-10 07:58 UTC, CristianAmbrosini commented on rules/S1694/csharp/rule.adoc
> +  private bool switchLamp = false;
Also this field makes it compliant

2024-06-10 10:10 UTC, zsolt-kolbay-sonarsource requested changes
A few questions/polishing.

2024-06-10 10:10 UTC, zsolt-kolbay-sonarsource commented on rules/S1694/csharp/rule.adoc
> +`abstract` classes that contain non-abstract methods, in addition to `abstract` ones, cannot easily be converted to interfaces, and are not the subject of this rule:
What about abstract classes that have protected abstract methods by design? If we don't want the method to be public in the derived class? Does the rule looks at this as an exception?

``` cs
public abstract class BaseClass
{
   protected abstract void SomeMethod();
}
```

2024-06-10 10:34 UTC, antonioaversa commented on rules/S1694/csharp/rule.adoc
> +`abstract` classes that contain non-abstract methods, in addition to `abstract` ones, cannot easily be converted to interfaces, and are not the subject of this rule:
Done

2024-06-10 10:36 UTC, antonioaversa commented on rules/S1694/csharp/rule.adoc
> +`abstract` classes that contain non-abstract methods, in addition to `abstract` ones, cannot easily be converted to interfaces, and are not the subject of this rule:
@pavel-mikula-sonarsource

2024-06-10 10:37 UTC, antonioaversa commented on rules/S1694/csharp/rule.adoc
> +  private bool switchLamp = false;
Mentioned in a dedicated paragraph on field.

2024-06-10 13:10 UTC, zsolt-kolbay-sonarsource approved these changes
LGTM

2024-06-10 13:32 UTC, merged

2024-06-11 11:15 UTC, pavel-mikula-sonarsource commented on rules/S1694/csharp/rule.adoc
> +`abstract` classes that contain non-abstract methods, in addition to `abstract` ones, cannot easily be converted to interfaces, and are not the subject of this rule:
There's no exception. Please create a FP. It should take 1 line to fix, so the repro&fix could be done right away :)