RULEAPI-603 Fail ci metadata check if rule with replacement has 'ready' status
SonarSource/rspec pull request #398
Opened 2021-09-24 15:46 UTC by vilchik-elena

2021-09-27 10:42 UTC, andrei-epure-sonarsource requested changes
I left a few comments

2021-09-27 10:42 UTC, andrei-epure-sonarsource commented on rspec-tools/rspec_tools/validation/metadata.py
> +      f' status can\'t be "{status}" for a rule with the replacement rule(s)')
```suggestion
      f' status can\'t be "{status}" for a rule with replacement rule(s).')
```

(either remove `the`, or add the replacement rules in the error message `with the remplacement rule(s): SXXX, SYYY`)

2021-09-27 10:42 UTC, andrei-epure-sonarsource commented on rspec-tools/tests/validation/test_metadata_validation.py
> +def test_ready_rule_with_replacement_fails_validation(rule_language: LanguageSpecificRule):
could you add two more tests:
- when the rule status is not `beta` or `ready` and has a replacement rule? - should not fail
- when the rule has 2 replacement rules (to make sure it fails in this case, too)

2021-09-30 09:11 UTC, andrei-epure-sonarsource approved these changes
LGTM

please consider my comment

2021-09-30 09:11 UTC, andrei-epure-sonarsource commented on rspec-tools/tests/validation/test_metadata_validation.py
> +def test_ready_rule_with_replacement_fails_validation(rule_language: LanguageSpecificRule):
now you changed the test with only one replacement to test with two replacements - either way you're not testing one of the cases

I still think it would be good to test both cases

2021-09-30 09:16 UTC, vilchik-elena commented on rspec-tools/tests/validation/test_metadata_validation.py
> +def test_ready_rule_with_replacement_fails_validation(rule_language: LanguageSpecificRule):
Indeed, I did it consciously, as I don't see much value in this test and I don't want to have too many tests

2021-09-30 09:45 UTC, merged