RULEAPI-770 Fix bug due to multiple sonarpedia.json files
SonarSource/rspec pull request #3983
Opened 2024-06-06 14:31 UTC by johann-beleites-sonarsource

When there are multiple sonarpedia.json files for the same language, the rules picked up for the next sonarpedia.json file will override the ones picked up previously. With this fix, the rules are not overwritten but all are collected, so one repository can have multiple sonarpedia.json files for the same language.

2024-06-10 16:13 UTC, frederic-tingaud-sonarsource requested changes
The change is functionally good for me.
I'm no expert in Python, but I think we can make it simpler by using some nice Dictionary features.

2024-06-10 16:13 UTC, frederic-tingaud-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +      implemented_rules_in_path = get_implemented_rules(path, languages)
I see that we have the same pattern already in this file, but it can actually be simplified a bit like this:
```python
import collections
...
implemented_rules = collections.defaultdict(list)
...
for lang, rules in implemented_rules_in_path.items():
  implemented_rules[lang].append(rules)
```

2024-06-11 10:08 UTC, frederic-tingaud-sonarsource approved these changes

2024-06-11 10:15 UTC, johann-beleites-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +      implemented_rules_in_path = get_implemented_rules(path, languages)
Indeed, this is nicer, thanks for the suggestion

2024-06-11 10:15 UTC, merged