Modify rule S6929: add the PyTorch library
SonarSource/rspec pull request #3984
Opened 2024-06-07 14:18 UTC by ghislainpiot

2024-06-10 09:13 UTC, joke1196 requested changes
This looks good but I think you need to provide as well the code example for the  Tensorflow. As in SonarQube the how to fix it in <Framework> is a tab.

2024-06-10 09:13 UTC, joke1196 commented on rules/S6929/python/rule.adoc
> +
Here I think you need to provide `=== Code examples` for PyTorch. and add another Code example section under Tensorflow.

2024-06-10 09:56 UTC, joke1196 approved these changes
LGTM! All works nicely in SQ.

2024-06-12 14:15 UTC, jean-jimbo-sonarsource approved these changes

2024-09-27 10:51 UTC, merged