Improve stability of the checkout for analyzer versions(tags)
SonarSource/rspec pull request #403
Opened 2021-09-27 14:30 UTC by arseniy-sonar

`g.checkout` used to often fail for some versions especially of `sonar-dotnet` due to fantom unstaged changes, which lead to incorrect version being recorded for coverage of certain rules, for example: https://github.com/SonarSource/rspec/commit/8736e561f9fadf43d53380b9bb37d9c6a01932ec

the direct `reset` called on a `Repo` object seems to work more reliably.

2021-09-27 15:52 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> -    g.reset('--hard', version)
on `Repo` this is not necessary anymore?

2021-09-27 15:53 UTC, andrei-epure-sonarsource requested changes

2021-09-27 15:53 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +  r=Repo(repo)
could you add a comment on why `Repo` is used here and not in `checkout_repo`? because it seems both functions are checking out repositories...

2021-09-27 17:15 UTC, arseniy-sonar commented on rule_coverage/coverage.py
> -    g.reset('--hard', version)
yes, as I understand, `r.head.reset(index=True, working_tree=True)` is equivalent, and it is done on each call to `scan_version` unconditionally

2021-09-27 17:18 UTC, arseniy-sonar commented on rule_coverage/coverage.py
> +  r=Repo(repo)
Good remark. In fact, `Repo` is used here because `checkout_repo` is expected to be called before you run `scan_version`. But that makes for a poor contract, I replaced it with `checkout_repo` (which doesn't add much overhead in case it was already called before).

2021-09-28 08:11 UTC, andrei-epure-sonarsource approved these changes
LGTM

2021-09-28 09:44 UTC, merged