Modify rule S6200 Don't allow local volatile variables (M23_387) (CPP-5140)
SonarSource/rspec pull request #4042
Opened 2024-07-05 18:52 UTC by loic-joly-sonarsource

2024-07-08 08:09 UTC, frederic-tingaud-sonarsource approved these changes

2024-07-08 08:09 UTC, frederic-tingaud-sonarsource commented on rules/S6200/cfamily/rule.adoc
> +Additionally, even if the meaning of a `volatile` local variable or data member is well-defined, it does not really serve any purpose. Such variables are totally within the purview of the {cpp} langu
```suggestion
Additionally, even if the meaning of a `volatile` local variable or data member is well-defined, it does not serve any purpose. Such variables are totally within the purview of the {cpp} language and can't change value without compiler knowledge.
```

2024-07-08 08:10 UTC, frederic-tingaud-sonarsource approved these changes

2024-07-08 08:10 UTC, frederic-tingaud-sonarsource commented on rules/S6200/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#cp200-use-volatile-only-to-talk-to-non-c-memory[CP.200: Use volatile only to talk to non-C++ memory]
```suggestion
* {cpp} Core Guidelines - https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#cp200-use-volatile-only-to-talk-to-non-c-memory[CP.200: Use volatile only to talk to non-{cpp} memory]
```

2024-07-09 12:17 UTC, marco-antognini-sonarsource requested changes
nits

2024-07-09 12:17 UTC, marco-antognini-sonarsource commented on rules/S3687/cfamily/rule.adoc
> +If the intent is to share those variables between threads, race conditions can be avoided by using synchronization primitives (such as `std::mutex`) or atomic types (``++_Atomic++`` in C11/ `std::ato
```suggestion
If the intent is to share those variables between threads, race conditions can be avoided by using synchronization primitives (such as `std::mutex`) or atomic types (``++_Atomic++`` in C11, `std::atomic<T>` in {cpp}11).
```

2024-07-09 12:17 UTC, marco-antognini-sonarsource commented on rules/S3687/cfamily/rule.adoc
> +Since local variables and data members are totalIy within the purview of the {cpp}language, they can't change their value without compiler knowledge: It makes no sense for them to be `volatile`.
```suggestion
Since local variables and data members are totally within the purview of the {cpp}language, they can't change their value without compiler knowledge: It makes no sense for them to be `volatile`.
```

"purview" is not an easy word. Maybe we can simplify the sentence a bit. A couple of suggestions.

```suggestion
Local variables and data members are completely controlled by the {cpp} language. This means they can't change their value without the compiler knowing about it. Therefore, it doesn't make sense for them to be marked as `volatile`.
```

```suggestion
Since local variables and data members cannot change their value without the compiler knowing about it, it makes no sense for them to be `volatile`.
```

```suggestion
Since only the compiler can mutate local variables and data members, it makes no sense for them to be `volatile`.
```

```suggestion
In {cpp}, local variables and data members can't change without the compiler's knowledge, so marking them as `volatile` is pointless.
```

2024-07-09 12:17 UTC, marco-antognini-sonarsource commented on rules/S6200/cfamily/rule.adoc
> +* S3687 covers the use of `volatile` local variables and data members
The format should be `* <SXXX> - title` according to https://github.com/SonarSource/rspec/blob/master/docs/link_formatting.adoc#link-formatting.

2024-07-09 12:17 UTC, marco-antognini-sonarsource commented on rules/S6200/cfamily/rule.adoc
> +* {cpp} Core Guidelines - https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#cp200-use-volatile-only-to-talk-to-non-c-memory[CP.200: Use volatile only to talk to non-{cpp} memory]
We use version `e49158a` everywhere.

2024-07-09 12:18 UTC, marco-antognini-sonarsource commented on rules/S6200/cfamily/rule.adoc
> +=== Related rules
Might be good to link the other rule to S6200 too.

2024-07-09 13:00 UTC, loic-joly-sonarsource commented on rules/S6200/cfamily/rule.adoc
> +* S3687 covers the use of `volatile` local variables and data members
I hate it... It means we can only mention another rule, not say why we mention it... :(

2024-07-09 13:05 UTC, loic-joly-sonarsource commented on rules/S6200/cfamily/rule.adoc
> +=== Related rules
We discussed about it, but did not really see the point.

2024-07-11 14:46 UTC, marco-antognini-sonarsource approved these changes
LGTM

2024-07-11 14:51 UTC, merged