RULEAPI-691: Rule coverage: Track the last version of an analyzer implementing a rule along with the first version
SonarSource/rspec pull request #407
Opened 2021-09-28 09:20 UTC by arseniy-sonar

The big number of changes in the covered_rules.json are due to the incidental correction for the version traversal order: it used to be arbitrary (or lexicographical), now it is chronological, so the implementation versions for many rules are corrected.

2021-09-28 14:03 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +canonical_names={
[education] what is this for?

2021-09-28 14:10 UTC, arseniy-sonar commented on rule_coverage/coverage.py
> +canonical_names={
This coalesces the language names of the same language used in different versions or different analyzers.
Without canonicalizing the language names, they are considered different languages, which leads to apparent end-of-support for all rules when an analyzer switches from one language name to another (as is the case for "Web" -> "HTML"), or confusion if the language is implemented by multiple analyzers using different names (which is the case for "JAVASCRIPT" in SonarJS vs. "JS" in sonar-security).

2021-09-28 15:47 UTC, andrei-epure-sonarsource requested changes

2021-09-28 15:47 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +def simplify_spec_for_rules_that_are_still_supported():
please add a comment mentioning that this implies that `master` will be the last in the array, so the rules needs to be sorted for this function to work.

2021-09-29 07:06 UTC, arseniy-sonar commented on rule_coverage/coverage.py
>    if "compatibleLanguages" in rule:
Some analyzers implement rules for multiple languages: C-family and JS/TS. However, not all rules implemented are compatible with all the languages the analyzer supports. This field specifies what languages out of the set supported by the analyzer are compatible.

2021-09-29 07:10 UTC, arseniy-sonar commented on rule_coverage/coverage.py
>        store_rule(name, rule, language, repoAndVersion)
Oups. I missed that one. Thanks!
Better to call it inside `store_rule` to avoid such omissions.

2021-09-29 07:14 UTC, arseniy-sonar commented on rule_coverage/coverage.py
> +def simplify_spec_for_rules_that_are_still_supported():
Done.

2021-09-29 10:36 UTC, arseniy-sonar commented on rule_coverage/coverage.py
>  def store_rule(name, rule, language, repoAndVersion):
I agree, the code is confusing at best. I reengineered the whole script.

2021-09-29 10:36 UTC, arseniy-sonar commented on rule_coverage/coverage.py
> +    rules[language][name] = {'since': repoAndVersion, 'until': repoAndVersion}
Is it simpler now, after the refactoring?

2021-09-29 15:37 UTC, andrei-epure-sonarsource requested changes
Thank you for doing the refactoring of the coverage.py script - it was very hard to understand and it's a true blessing to see object oriented programming! 💯 🥇 🥂 👍 🚀 

I still have some comments, however I'm pretty sure they're the last (🤞 ).

2021-09-29 15:37 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +        for language in rule_languages(rule, languages):
This logic is cumbersome.

I suggest to rename `rule_languages` to `swap_with_compatible_if_present` and make it a different variable to give the result enough sense

```
ruleLanguages = swap_with_compatible_if_present(rule, languages)
for ruleLanguage in ruleLanguages :
  if ruleLanguage not in implemented_rules:
    implemented_rules[ruleLanguage ] = []
  implemented_rules[ruleLanguage ].append(ruleId)

```

_(I apologize for the long review, but I think clean-as-you-code is the right thing to do with this file)_

2021-09-29 15:37 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +def get_implemented_rules(path, languages):
```suggestion
def get_implemented_rules(path, languagesFromSonarPedia):
```

2021-09-29 15:37 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +def get_implemented_rules(path, languages):
(clean as you code)

And please add a function comment stating that:
- normally the rules should apply for the languages in SonarPedia
- there are some repositories where some rules are implemented for a subset of the languages in SonarPedia, which is contained in  `compatibleLanguages`

It took me a while to understand this logic and a comment would have saved a lot of time.

2021-09-29 15:37 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +        for language in rule_languages(rule, languages):
Also, I am highly confused - what is the case where the rule language might not be in SonarPedia, but be present in compatibleRules?

2021-09-29 15:37 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +  # Rule implementations for some langauges are spread across multiple repositories
```suggestion
  # Rule implementations for some languages are spread across multiple repositories
```

2021-09-29 15:37 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +    for language in implemented_rules:
this is a bit confusing for a non-python developer (because in Java/C# you'd have `for language in implemented_rules.keys` or smth similar), IMO I have two possible suggestions:

- rename `implemented_rules` to `implemented_rules_per_language` would make it clearer it's a dictionary
OR
- add a comment saying that the parameter is a dictionary where `language` is the key and `list of rules` is the value.

2021-09-29 15:37 UTC, andrei-epure-sonarsource commented on frontend/src/RulePage.tsx
> +              <span>(until {range['until']}) </span></li>
the `until` is a bit small here... I still see `sonar-abap 3.7` and my brain intuitively ignores what's with strikethrough because... well, it's cut text so it's not necessary.

So my brain sees "Covered Since until sonar-abap 7.3..."

Is it possible to make this w/o strikethrough and something like

"Not covered in ABAP anymore. Was covered from version X to version Y."

![image](https://user-images.githubusercontent.com/38876598/135301094-72f7b0e0-5142-4ad4-b653-fffd59a73f8d.png)

```suggestion
              <span>(was covered until {range['until']}, not covered anymore) </span></li>
```

2021-09-29 15:42 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +    rules[language][name] = {'since': repoAndVersion, 'until': repoAndVersion}
yes, it is much, much better

2021-09-29 15:59 UTC, arseniy-sonar commented on frontend/src/RulePage.tsx
> +              <span>(until {range['until']}) </span></li>
done.

2021-09-29 16:05 UTC, arseniy-sonar commented on rule_coverage/coverage.py
> +def get_implemented_rules(path, languages):
I have this comment on the `rule_languages` (`compatible_languages` now). Do you think it is enough (after renaming the function to `compatible_languages` and the argument to `languagesFromSonarPedia`)?

2021-09-29 16:09 UTC, arseniy-sonar commented on rule_coverage/coverage.py
> +        for language in rule_languages(rule, languages):
How about just `compatible_languages`?
I don't think there can is a rule with `compatibleLanguages` containing a language that is not listed in sonarpedia. I think at the moment it is a subset.

I am not sure whether we should make sure to always use a subset of the languages in sonarpedia, or if a developer specified a language not listed in sonarpedia go ahead and add it the rule as implemented for that language. This is what the coverage script does right now.

2021-09-29 16:09 UTC, arseniy-sonar commented on rule_coverage/coverage.py
> +    for language in implemented_rules:
renamed.

2021-09-30 07:27 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +def get_implemented_rules(path, languages):
I think it's enough

2021-09-30 07:30 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +        self.rule_implemented(ruleId, language, analyzer, version)
```suggestion
      for rule_id in implemented_rules_per_language[language]:
        self.rule_implemented(rule_id , language, analyzer, version)
```

I wonder why tests didn't fail... this isn't covered?

2021-09-30 07:45 UTC, arseniy-sonar commented on rule_coverage/coverage.py
> +        self.rule_implemented(ruleId, language, analyzer, version)
There are no automated tests for this script (I am adding them as part of RULEAPI-573), and I admit I haven't try to run the script after this last change.

2021-09-30 08:00 UTC, andrei-epure-sonarsource approved these changes
LGTM! great to see this!

2021-09-30 08:00 UTC, andrei-epure-sonarsource commented on rule_coverage/coverage.py
> +  ruleId = filename[:-5]
nitpick: sonarlint complains about python naming convention:
- ruleId -> rule_id
- languagesFromSonarPedia -> languages_from_sonarpedia

2021-09-30 08:38 UTC, arseniy-sonar commented on rule_coverage/coverage.py
> +  ruleId = filename[:-5]
Done.

2021-09-30 08:59 UTC, merged