CPP-5564 S2335 Make more characters properly terminate an escape sequence
SonarSource/rspec pull request #4115
Opened 2024-08-05 22:50 UTC by loic-joly-sonarsource

See also https://github.com/SonarSource/sonar-cpp/pull/3880

2024-08-06 14:34 UTC, frederic-tingaud-sonarsource requested changes

2024-08-06 14:34 UTC, frederic-tingaud-sonarsource commented on rules/S2335/cfamily/rule.adoc
> +int c2 = '\141\t'; // Compliant (with a different value) - terminated by another escape
I don't understand what this means.

2024-08-06 16:36 UTC, loic-joly-sonarsource commented on rules/S2335/cfamily/rule.adoc
> +int c2 = '\141\t'; // Compliant (with a different value) - terminated by another escape
This is supposed to be the compliant version of some non-compliant code, but the value of `c2` is not the same as in the non-compliant code.

Once again, the framework of having non-compliant followed by compliant makes it more complex to write the RSPEC. Without these titles, I would have move this compliant example right after the non-compliant one, with a different variable name.

```
[source,cpp]
----
const char *s1 = "\x41g";  // Noncompliant
int c1 = '\141t'; // Noncompliant
int c2 = '\141\t'; // Compliant - terminated by another escape
----
```

2024-08-06 16:43 UTC, frederic-tingaud-sonarsource commented on rules/S2335/cfamily/rule.adoc
> +int c2 = '\141\t'; // Compliant (with a different value) - terminated by another escape
I preferred the previous version, without `(with a different value)`. The Compliant code block shows various examples of compliant declarations, there is no need to try to create a link between `c1` and `c2`.

2024-08-21 11:48 UTC, marco-antognini-sonarsource approved these changes

2024-08-21 11:50 UTC, merged