Modify rule S6195: Fix grammar and typo in code
SonarSource/rspec pull request #417
Opened 2021-09-29 12:14 UTC by marco-antognini-sonarsource

2021-09-29 12:31 UTC, tomasz-kaminski-sonarsource commented
I would suggest mentoning the if-constexpr rule in see also, while we are editing the rspec.

2021-09-29 12:32 UTC, tomasz-kaminski-sonarsource requested changes
I would suggest mentoning the if-constexpr rule in see also, while we are editing the rspec, simliary how it is done here:
https://github.com/SonarSource/rspec/pull/384/files

2021-09-30 11:36 UTC, marco-antognini-sonarsource commented
Let me know if the format is as expected.

2021-09-30 11:42 UTC, tomasz-kaminski-sonarsource requested changes

2021-09-30 11:42 UTC, tomasz-kaminski-sonarsource commented on rules/S6195/cfamily/rule.adoc
> +* S6017
The foirmat should be:
`` S6021 for when it might be a bad idea to use transparent comparators.``
I.e. something like:
`` S6017 to see when enable_if could be replaced with if constexpr`.

2021-09-30 11:53 UTC, tomasz-kaminski-sonarsource approved these changes

2021-09-30 11:54 UTC, marco-antognini-sonarsource commented on rules/S6195/cfamily/rule.adoc
> +* S6017
Oh, okay. It seems we are not very consistent then -- `git grep` shows that most rules are referred without additional explanations.

2021-09-30 11:56 UTC, merged