Add RSPEC for S2612
SonarSource/rspec pull request #4356
Opened 2024-10-01 09:12 UTC by sebastien-andrivet-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-10-07 14:26 UTC, pierre-loup-tristant-sonarsource commented on rules/S2612/ansible/metadata.json
> +      732
What's the rationale for removing CWE-266: Incorrect Privilege Assignment?

2024-10-07 16:05 UTC, pierre-loup-tristant-sonarsource requested changes
Please have a look at the discussion in https://sonarsource.atlassian.net/browse/APPSEC-2157?focusedCommentId=670196 and, if needed, remove the code example where the  `mode` argument is omitted.

2024-10-07 16:05 UTC, pierre-loup-tristant-sonarsource commented on rules/S2612/ansible/rule.adoc
> +        dest: /etc/demo/demo.conf
I made a comment in https://sonarsource.atlassian.net/browse/APPSEC-2157 to discuss if we should raise in the absence or the `mode` argument.

2024-10-08 07:14 UTC, sebastien-andrivet-sonarsource commented on rules/S2612/ansible/rule.adoc
> +        dest: /etc/demo/demo.conf
We should not.

2024-10-08 08:18 UTC, pierre-loup-tristant-sonarsource approved these changes
LGTM

2024-10-08 08:18 UTC, pierre-loup-tristant-sonarsource commented
Validation of links are failing but non are in the "see" section of S2612

2024-10-08 08:51 UTC, merged