Modify S6781(C#): Add alternative message
SonarSource/rspec pull request #4362
Opened 2024-10-02 14:15 UTC by loris-s-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-10-03 18:34 UTC, jamie-anderson-sonarsource requested changes
I think that this message needs improvement.

2024-10-03 18:34 UTC, jamie-anderson-sonarsource commented on rules/S6781/csharp/rule.adoc
> +** Make sure that the config file containing the secret is inacessible to unauthorized users.
I think that it would be better if the message mentioned JWT secret keys. There's only a concern when it comes to production secrets, so I've had a go at incorporating that into the message.

```suggestion
** Make sure that production JWT secret keys are not stored in source control.
```

2024-10-03 18:34 UTC, jamie-anderson-sonarsource commented on rules/S6781/csharp/rule.adoc
> +** Make sure that the config file containing the secret is inacessible to unauthorized users.
I should also not that `inaccessible` is incorrectly spelled in the original message.

2024-10-04 11:12 UTC, daniel-teuchert-sonarsource commented on rules/S6781/csharp/rule.adoc
> +** Make sure that the config file containing the secret is inacessible to unauthorized users.
I agree with Jamie's suggestion.

2024-10-04 11:15 UTC, jamie-anderson-sonarsource approved these changes
LGTM with the suggestion applied

2024-10-04 11:20 UTC, merged