Improve rule metadata validation
SonarSource/rspec pull request #44
Opened 2021-02-22 12:44 UTC by nicolas-harraudeau-sonarsource

This adds the command `rspect-tools validate-rules`.
There are quite a few `rule.adoc` and `metadata.json` files because I copied a few rules in tests to avoid having tests rely on production rules.

2021-02-22 14:45 UTC, arseniy-sonar requested changes
Impressive
I would mention in the PR title that it concerns only the metadata validation.

2021-02-22 14:45 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/cli.py
> +  '''Create a new rule.'''
Looks like a C&P artifact

2021-02-22 14:45 UTC, arseniy-sonar commented on validate_asciidoc_and_metadata.sh
> +# Validate metadata
This looks like an independent part of the script that could be put directly into the .cirrus.yml (perhaps even into a separate `script_` section) for better CI UX

2021-02-22 14:45 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/rules.py
> +class RuleLanguage:
I find this name confusing w.r.t. to what this class represents, especially when used as return type for `Rule.languages`. For a `Language` and `RuleLanguage` I'd expect only details about the language (that might be specific to a rule), and not a rule specific to the language.
How about `LanguageSpecificRule`, or just `SpecificRule` (with the symmetric renaming of `Rule` to `GenericRule`)?

2021-02-22 14:45 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/rules.py
> +  def languages(self) -> Generator[RuleLanguage, None, None]:
It is confusing when this function returns something other than just languages. I think a name like `languageSpecificRules` or `specificRules` or `specializations` would be more obvious (regardless of the comment on the `RuleLanguage` class)

2021-02-22 14:45 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/cli.py
> +def validate_rules(rules):
As far as I can tell, current version only validates the metadata.json and ignores the asciidoc description.
Furthermore, validation of the asciidoc description is planned in the future.
I think it is more appropriate to speak only about metadata validation for now, and use names like `validate_rules_metadata` to clearly delineate the scope of the tool.
Once asciidoc validation is in place (e.g., `validate_rules_description`), we could merge the two into `validate_rules` or keep them separate.

2021-02-23 13:08 UTC, nicolas-harraudeau-sonarsource commented on rspec-tools/rspec_tools/cli.py
> +  '''Create a new rule.'''
Indeed

2021-02-23 13:32 UTC, nicolas-harraudeau-sonarsource commented on validate_asciidoc_and_metadata.sh
> +# Validate metadata
Works for me.

2021-02-23 13:33 UTC, nicolas-harraudeau-sonarsource commented on rspec-tools/rspec_tools/rules.py
> +class RuleLanguage:
Good idea, ok for `LanguageSpecificRule` and `GenericRule`.

2021-02-23 19:41 UTC, merged