Add guidelines to format references to code elements
SonarSource/rspec pull request #4413
Opened 2024-10-14 09:05 UTC by loic-joly-sonarsource

Since the information is split into different files, I thought it better to duplicate the new guideline (I did not want to fully reorganize the doc...)

2024-10-14 10:21 UTC, frederic-tingaud-sonarsource requested changes

2024-10-14 10:21 UTC, frederic-tingaud-sonarsource commented on docs/description.adoc
> +cout << noexcept(++i); // Noncompliant, "i" is not incremented -> Double quotes, ok
I wouldn't write down bad examples here.
This documentation is already large and people skim through it. Unless you read very carefully, it is hard to see the small "ok" vs "bad" at the very end of the line.
On top of that, the rest of the doc doesn't have the same "ok / bad" pattern.

2024-10-14 10:21 UTC, frederic-tingaud-sonarsource commented on docs/styling_guide.adoc
> +// Avoid
Same here

2024-10-14 14:17 UTC, loic-joly-sonarsource commented on docs/styling_guide.adoc
> +// Avoid
Discussed: Not the same. We'll keep it that way.

2024-10-15 14:52 UTC, frederic-tingaud-sonarsource approved these changes

2024-10-15 20:29 UTC, merged