Modify rule S6602: Update benchmark
SonarSource/rspec pull request #4438
Opened 2024-10-24 16:15 UTC by martin-strecker-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-10-28 14:25 UTC, CristianAmbrosini requested changes

2024-10-28 14:25 UTC, CristianAmbrosini commented on rules/S6602/metadata.json
> +  "defaultQualityProfiles": [],
Should we downgrade it to non-SonarWay also for VB.NET?

2024-10-28 14:25 UTC, CristianAmbrosini commented on rules/S6602/resources-dotnet.adoc
> +| Method                      | Runtime              | Categories       | Mean       | StdDev    | Allocated
```suggestion
| Method                      | Runtime              | Categories       | Mean       | Standard Deviation    | Allocated
```

2024-10-29 08:11 UTC, martin-strecker-sonarsource commented on rules/S6602/metadata.json
> +  "defaultQualityProfiles": [],
Yes. I think so. This is the top-level file, and the language-specific `metadata.json` files are empty. So there is nothing to do here, right?

2024-10-29 08:14 UTC, CristianAmbrosini commented on rules/S6602/metadata.json
> +  "defaultQualityProfiles": [],
Yeah that's why I asked, this way we are downgrading for both languages and I wanted to be sure it was intentional

2024-10-29 09:01 UTC, CristianAmbrosini approved these changes
LGTM

2024-10-29 11:32 UTC, martin-strecker-sonarsource commented on rules/S6602/resources-dotnet.adoc
> +| Method                      | Runtime              | Categories       | Mean       | Standard Deviation    | Allocated
Yes. This is all a bit unfortunate:
* You can only have multiple baselines if you also use categories
* The different baselines give you "Ratio" and "Memory Ratio" outputs, but we hide these columns
* The category columns can not be hidden by the BenchmarkDotNet configuration

So we end up with the worst of all worlds and the category isn't bringing much value. Let's keep it this way. It is closest to the benchmarkdotnet output and copy/paste friendly. It is also better suited for future changes to the benchmark (like bringing the Ratio columns back).

2024-10-29 11:33 UTC, merged