Modify S6327: Improve the recommended fix
SonarSource/rspec pull request #4543
Opened 2024-11-26 16:46 UTC by loris-s-sonarsource

## Review

A dedicated reviewer checked the rule description successfully for:

- [ ] logical errors and incorrect information
- [ ] information gaps and missing content
- [ ] text style and tone
- [ ] PR summary and labels follow [the guidelines](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule)

2024-11-26 16:46 UTC, loris-s-sonarsource commented on rules/S6327/recommended.adoc
> +key, called `KmsMasterKeyId` in diverse SDKs, the SNS topic is not encrypted by deafult.
```suggestion
key, the SNS topic is not encrypted by default.
```

2024-11-27 08:21 UTC, hendrik-buchwald-sonarsource commented on rules/S6327/recommended.adoc
> +To do so, create a master key and affect the SNS topic to it. Without a master
Is "affect" the right word here?

2024-11-27 08:38 UTC, hendrik-buchwald-sonarsource commented on rules/S6327/recommended.adoc
> +key, the SNS topic is not encrypted by default.
Using the negative version is usually a bit harder to understand than the positive version: "With a master key, the SNS topic is encrypted by default".

2024-11-27 09:02 UTC, hendrik-buchwald-sonarsource requested changes
I would recommend a little bit of rewording.

2024-11-27 09:53 UTC, loris-s-sonarsource commented on rules/S6327/recommended.adoc
> +key, the SNS topic is not encrypted by default.
I removed it, the goal was to say that by default no encryption applied but I am starting to think this sentence, at this location could be confusing. I replaced it with notable information instead

2024-11-27 11:01 UTC, hendrik-buchwald-sonarsource approved these changes
LGTM!

2024-11-27 11:04 UTC, merged