RULEAPI-816 Create a rule / product mapping file
SonarSource/rspec pull request #4575
Opened 2024-12-12 17:14 UTC by frederic-tingaud-sonarsource

2024-12-13 11:12 UTC, marco-antognini-sonarsource requested changes

2024-12-13 11:12 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +  build_rule_per_product(rules_dir, bundle_map, plugin_versions)
I'm concern we do not sort things consistently with `collect_coverage_for_all_versions` (committed date vs tag).

Maybe the rest of the code handle this nicely, in which case I would remove this sort and test the implementation with a shuffle to make sure it's resilient.

I also think we can have a lightweight test here that cover scenarios like:

* SQS 2025.1 is released with plugin X.1 and thus S1
* (Assume 2025.1 is an LTA)
* SQS 2025.2 is released with plugin X.2 and drops S1
* bugfix SQS 2025.1.1 is released still with X.1 (or X.1.1) and with S1

or this one:

* SQS 2025.1 is released with plugin X.1 and _no_ S1
* (Assume 2025.1 is an LTA)
* SQS 2025.2 is released with plugin X.2 and introduces S1
* bugfix SQS 2025.1.1 is released still with X.1 (or X.1.1) and thus without S1

In terms of test implementation, I would suggest:

1. pass the `git_repo` as a parameter
2. create a fake `sonar-entreprise` for a couple of scenarios -- we just need tags & specific files.
3. create a fake plugin coverage JSON file for those scenarios
4. a big of pytest magic should be enough -- we may not even need to mock/patch anything

I appreciate we do not want complicated unit tests for each function (although it would be nice), but we can strike a balance between having nothing and something that cover the main corner cases from end-to-end.

2024-12-13 11:12 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
In terms of schema design, I realise now after the various changes that we have a suboptimal schema. Having `'SonarQube Server': { 'edition': 'Developer', 'version': xyz }` would be easier to consume than looking at which keys exists in the JSON object.

2024-12-13 11:12 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/repo_plugin_mapping.json
We should document this file and share its existance.

2024-12-13 13:27 UTC, frederic-tingaud-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +    with pushd(repo_dir):
We need to access build.gradle from inside the sonar-enterprise repository folder otherwise git commands will not work.

2024-12-13 14:01 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +    with pushd(repo_dir):
I don't I follow. We do `g.show(f'{version}:build.gradle')`, so we're not looking at the files on disk. And I would expect `g` to know which directory to use (otherwise, I'd git GitPython 🥇 for being crap :p).

2024-12-16 06:57 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +  with pushd(repo_dir):
discussed: `g` does not work when the PWD is not the expected one... sad about GitPython here.

2024-12-16 06:59 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +BUNDLED_SIMPLE = r'''['"](?:com|org)\.sonarsource\.(?:[\w.-]+):(?P<plugin_name>[\w-]+)['"]'''
```suggestion
BUNDLED_SIMPLE = r'''['"](?:com|org)\.sonarsource\.[\w.-]+:(?P<plugin_name>[\w-]+)['"]'''
```

2024-12-16 07:04 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +      if not isinstance(since, str):
```suggestion
      if not isinstance(since, str):
        # The rule has an "until", therefore it does not exist anymore
        # and we don't need to report it in the produce mapping.
```

2024-12-16 08:39 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +  return list(map(int, v.split('.')))
Let's make the flow more linear between condition and action
```suggestion
  if is_version_tag(v):
    return list(map(int, v.split('.')))
  if v == 'master':
    return [0]
  sys.exit(f'Unexpected version {key}')
  
```

2024-12-16 08:46 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +        if m.groupdict()['plugin_name'] != None:
I'll make some minor adjustments: `m.groupdict()['plugin_name']` can be simplified with `m['plugin_name']`.

2024-12-16 09:04 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +      }
We'll get a hard error (thanks to the `sys.exit`) if a rule is released for the first time in a Community Build.

2024-12-16 12:11 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +BUNDLED_SIMPLE = r'''['"](?:com|org)\.sonarsource\.(?:[\w.-]+):(?P<plugin_name>[\w-]+)['"]'''
e056c0f888

2024-12-16 12:13 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +  return list(map(int, v.split('.')))
f5d9bbf6ab

2024-12-16 14:21 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +DEPENDENCY_RE = re.compile(r'''\bdependency\s+['"](?:com|org)\.sonarsource\.[\w.-]+:(?P<plugin_name>[\w-]+):(?P<version>\d+(\.\d+)+)['"]''')
Right now, in the code, we say `major >= 8` however this regex does not match for all plugins.

Example:
https://github.com/SonarSource/sonar-enterprise/blob/f869d840f12a4dfa69533e17d3b27558617a7f82/build.gradle#L128C35-L128C41

2024-12-16 14:23 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +DEPENDENCY_RE = re.compile(r'''\bdependency\s+['"](?:com|org)\.sonarsource\.[\w.-]+:(?P<plugin_name>[\w-]+):(?P<version>\d+(\.\d+)+)['"]''')
9.x looks compatible though: https://github.com/SonarSource/sonar-enterprise/blob/ce743843018827cb30c05735e7971523de34bb48/build.gradle#L171-L209

2024-12-16 14:28 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +DEPENDENCY_RE = re.compile(r'''\bdependency\s+['"](?:com|org)\.sonarsource\.[\w.-]+:(?P<plugin_name>[\w-]+):(?P<version>\d+(\.\d+)+)['"]''')
Starting 10.0 we have an entry that does not match the regex but we should not care about this one so that's fine: https://github.com/SonarSource/sonar-enterprise/blob/75dae6a655f49ac78b0a786f6c19b15085561af9/build.gradle#L218

10.1 introduced a second one, but again we should be good. https://github.com/SonarSource/sonar-enterprise/blob/53c01c35c264c7e3d76cf5fb955de406f36b115e/build.gradle#L254-L255

2024-12-16 14:41 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +DEPENDENCY_RE = re.compile(r'''\bdependency\s+['"](?:com|org)\.sonarsource\.[\w.-]+:(?P<plugin_name>[\w-]+):(?P<version>\d+(\.\d+)+)['"]''')
I've pushed 3b745315e4 to:

1. support `>=9` only
2. detect missing versions if variables are re-introduced for plugins in the future.

_If_ we need older coverage, we can accommodate that in a later PR. @frederic-tingaud-sonarsource can you validate this is OK for now?

2024-12-16 15:05 UTC, frederic-tingaud-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +      }
Oh, good point!
One cool thing we could do is handle it gracefully and return something like "Coming soon" or "Next release" in that case.

2024-12-16 15:05 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +      }
I would suggest keeping this as-is for now and fixing this with RULEAPI-830 and a proper test (i.e., after RULEAPI-828) to focus on the essential right now.

2024-12-16 15:07 UTC, frederic-tingaud-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +DEPENDENCY_RE = re.compile(r'''\bdependency\s+['"](?:com|org)\.sonarsource\.[\w.-]+:(?P<plugin_name>[\w-]+):(?P<version>\d+(\.\d+)+)['"]''')
Thanks for catching these! It looks good to me.

2024-12-16 15:50 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +  build_rule_per_product(rules_dir, bundle_map, plugin_versions)
Tests will be covered by RULEAPI-828

2024-12-17 17:28 UTC, frederic-tingaud-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +      }
I made the change because it is a scenario that is supposed to happen very quickly after the release of the first LTA, as SQ Community Builds have a shorter cycle than SQ Enterprise.
I also realized that there was a bug in how we handled "master" branches, which once fixed, would trigger the same exception.

2024-12-18 16:25 UTC, marco-antognini-sonarsource requested changes

2024-12-18 16:25 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +      target_repo, version = since.split(' ')
We should probably skip the `master` version here since it's not available in the product anyway and we do not look at `master` versions of sonar-enterprise.

2024-12-18 16:25 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
I had a look at the data we produce and there is something fishy. I'll hold off merging this because I don't want the script to cause trouble during the holidays when we are not there -- it would not be a nice Xmas gift.

Looking at [S100](https://github.com/SonarSource/rspec/blob/e9a57f6817528b0bf4c5ad755e022082bef3026e/frontend/public/rule_product_mapping.json#L2C1-L122C5) (_very_ old rule), we say:

* for C/C++/ObjC: introduced in 9.0 Dev edition ✅ 
* for Apex: enterprise edition (probably correct), introduced in 10.7: does not match [reality](https://peach.aws-prd.sonarsource.com/coding_rules?languages=apex&q=S100&open=apex%3AS100) SQS report it being there since Nov 02, 2018.
* for C#: Dev edition (sounds correct) but introduced in SQS 10.8 / sqcb-24.12 but SQ [reports](https://peach.aws-prd.sonarsource.com/coding_rules?languages=cs&q=S100&open=csharpsquid%3AS100) the rule being introduced in 2015...

I don't know where we do things incorrectly...

2025-02-10 10:13 UTC, closed without merging