Modify rule S2222[CSharp]: improve descrption and code example
SonarSource/rspec pull request #635
Opened 2021-12-01 16:16 UTC by csaba-sagi-sonarsource

2021-12-01 17:56 UTC, andrei-epure-sonarsource commented on rules/S2222/compliant.adoc
> +    Monitor.Enter(obj); // Noncompliant
this is the compliant solution ... it should contain lock

2021-12-01 18:01 UTC, andrei-epure-sonarsource requested changes

2021-12-01 18:01 UTC, andrei-epure-sonarsource commented on rules/S2222/csharp/description.adoc
> +The types tracked by the rule are: Monitor, Mutex, ReaderWriterLock, ReaderWriterLockSlim and SpinLock.
```suggestion
The types tracked by the rule are: Monitor, Mutex, ReaderWriterLock, ReaderWriterLockSlim and SpinLock from the `System.Threading` namespace. 
```

2021-12-01 18:01 UTC, andrei-epure-sonarsource commented on rules/S2222/compliant.adoc
> +    Monitor.Enter(obj); // Noncompliant
maybe give a simple example with `ReaderWriterLockSlim` , just to have it (both Noncompliant and Compliant) - because in this example the fix is not to use Monitor at all

2021-12-02 10:32 UTC, andrei-epure-sonarsource requested changes
Also, now that you are on the rspec, could you also add the VB .NET version of the rule?

this should help https://converter.telerik.com/

We'll want to implement both if time allows (as this will validate the fact that the engine is language-independent). So better just to get done with the RSPEC at this point.

2021-12-02 10:32 UTC, andrei-epure-sonarsource commented on rules/S2222/noncompliant.adoc
> +or
IMO you can avoid the `or` part and add the two samples in the same `MyClass` because they are using different APIs for different purposes (they're not alternatives)
```
----
class MyClass 
{
  private object obj = new object();
  public void DoSomethingWithMonitor() 
  {
    Monitor.Enter(obj); // Noncompliant
    if (IsInitialized())
    {
      // ...
      Monitor.Exit(obj);
    }
  }
  
  private ReaderWriterLockSlim lockObj = new ReaderWriterLockSlim();
  public void DoSomethingWithReaderWriteLock() 
  {
    lockObj.EnterReadLock(); // Noncompliant
    // do something without releasing in the same method
  }
}
----
```

2021-12-02 10:33 UTC, andrei-epure-sonarsource commented on rules/S2222/noncompliant.adoc
> +or
alternatively you can do the VB .NET in a different PR

2021-12-02 10:33 UTC, andrei-epure-sonarsource commented on rules/S2222/noncompliant.adoc
> +or
just to finish with this one

2021-12-02 12:33 UTC, csaba-sagi-sonarsource commented on rules/S2222/noncompliant.adoc
> +or
I am working on the VBNET part but It will be part of a new PR.

2021-12-02 13:18 UTC, andrei-epure-sonarsource approved these changes
LGTM

2021-12-02 13:29 UTC, merged