Create rule S5147[Java]: NoSQL operations should not be vulnerable to injections
SonarSource/rspec pull request #668
Opened 2021-12-21 10:33 UTC by loris-s-sonarsource

2021-12-21 18:06 UTC, pierre-loup-tristant-sonarsource requested changes

2021-12-21 18:06 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/description.adoc
> +can be exploited similarly to regular SQL injection bugs.
Unvalidated = tainted 
```suggestion
Applications that perform NoSQL operations based on tainted data can be exploited similarly to regular SQL injection bugs.
```

2021-12-21 18:06 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/description.adoc
> +string operations.
Sorry but I think it's longer and less clear that "an attacker could inject NoSQL objects to access sensitive information or compromise data integrity."

2021-12-21 18:14 UTC, pierre-loup-tristant-sonarsource requested changes
See the comments.

2021-12-21 18:14 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/description.adoc
> +or by validating user-supplied data based on its size or allowable characters.
"allowable characters" sound strange. Why not "allowed characters"?

2021-12-21 18:14 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/description.adoc
> -The problem could be mitigated by ensuring the type of the input is a String or sanitizing the user-provided data.
"ensuring the type of the input is a String" for JavaScript I think it still make sens but nit for Java.

2021-12-21 18:14 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/description.adoc
> +This problem can be mitigated by using an Object Document Mapper (ODM) library
Which one? Maybe MongoDB Java Driver have an ODM API?
If not we should advise an ODM library and maybe add a code example to illustrate it.
Maybe a more practical advise would be to only use the "safe" API from MongoDB Java Driver

2021-12-22 14:25 UTC, loris-s-sonarsource commented on rules/S5147/description.adoc
> +or by validating user-supplied data based on its size or allowable characters.
```suggestion
or by validating user-supplied data based on its size or allowed characters.
```

2021-12-22 14:29 UTC, loris-s-sonarsource commented on rules/S5147/description.adoc
> +This problem can be mitigated by using an Object Document Mapper (ODM) library
https://github.com/MorphiaOrg/morphia

2021-12-22 14:37 UTC, loris-s-sonarsource commented on rules/S5147/description.adoc
> +string operations.
My goal here is to separate different information, namely the risks (the why of the attacker), and the how(its technics). The initial sentence is really long and could use a little breath between informations

```suggestion
Depending on the code, the same risks exist as with SQL injections: The attacker
aims to access sensitive information or compromise data integrity. The
attacks may involve the injection of query operators, JavaScript code, or
string operations.
```

2021-12-22 15:32 UTC, loris-s-sonarsource commented on rules/S5147/description.adoc
> +This problem can be mitigated by using an Object Document Mapper (ODM) library
I added them in the See section, I don't think it makes sense to add them in the code snippets though, since we add already a "native" example

2022-01-03 09:49 UTC, pierre-loup-tristant-sonarsource requested changes
Migrate JS specific content to a separate `adoc` file.
Remove necessary newlines.

2022-01-03 09:49 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/java/rule.adoc
> +    collection.find(query);
Minor: this line could be removed

2022-01-03 09:49 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/java/rule.adoc
> +    }
Minor: these lines could be removed

2022-01-03 09:49 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/description.adoc
> +query operators, JavaScript code, or string operations.
Please remove necessary new lines

2022-01-03 09:49 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/description.adoc
> +Javascript and PHP), user-supplied data should be validated as strings.
Language specific content should be migrated to a language specific `adoc` file

2022-01-03 09:49 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/see.adoc
> +* https://mongoosejs.com/[Mongoose] JavaScript ODM
NoSQL injection are possible using Mongoose. See https://github.com/SonarSource/security-expected-issues/blob/fd0a0c5c1fae226b684ff7b4e334fe1a70b71198/javascript/express.js/RSPEC-5147/mongoose/noncompliant.js#L11

2022-01-04 15:36 UTC, loris-s-sonarsource commented on rules/S5147/description.adoc
> +Javascript and PHP), user-supplied data should be validated as strings.
Does it matter for such a short line ?

2022-01-04 15:49 UTC, loris-s-sonarsource commented on rules/S5147/description.adoc
> +Javascript and PHP), user-supplied data should be validated as strings.
done

2022-01-05 08:22 UTC, pierre-loup-tristant-sonarsource requested changes
Java rule has a duplicated "See" section in-between the description and the non-compliant code example.

2022-01-05 08:22 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/java/rule.adoc
>  include::../rule.adoc[]
```suggestion
include::../description.adoc[]
```

2022-01-12 19:09 UTC, pierre-loup-tristant-sonarsource requested changes
Now the See section is missing from the Java rule.

2022-01-12 19:09 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/java/rule.adoc
> +
```suggestion
include::../see.adoc[]
```

2022-01-13 09:44 UTC, pierre-loup-tristant-sonarsource approved these changes
LGTM. 
Please make a last adjustement to the JS see section as it containes a reference to a Java library.

2022-01-13 09:44 UTC, pierre-loup-tristant-sonarsource commented on rules/S5147/see.adoc
> +* https://morphia.dev[Morphia] Java ODM
This link should not be displayed in the JS rule.

2022-01-13 10:37 UTC, loris-s-sonarsource commented
> LGTM. Please make a last adjustement to the JS see section as it containes a reference to a Java library.

@pierre-loup-tristant-sonarsource : Done

2022-01-14 16:55 UTC, marco-antognini-sonarsource requested changes

2022-01-14 16:55 UTC, marco-antognini-sonarsource commented on rules/S5147/php/rule.adoc
> +include::see.adoc[]
```suggestion
include::../see.adoc[]
```

This causes the `asciidoc_tests` validation to fail on this PR, but it also causes (non-fatal) errors when building on `master` since this PR is merged locally when building.

For references:
* https://github.com/SonarSource/rspec/runs/4819220397?check_suite_focus=true#step:3:139
* https://jira.sonarsource.com/browse/RULEAPI-682?focusedCommentId=254487&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-254487

2022-01-26 09:23 UTC, loris-s-sonarsource commented on rules/S5147/java/rule.adoc
> +    MongoClient mongoClient = new MongoClient();
```suggestion
protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws UnknownHostException
{
    String input = req.getParameter("input");
    MongoClient mongoClient = new MongoClient();
```

2022-01-26 09:23 UTC, loris-s-sonarsource commented on rules/S5147/java/rule.adoc
> +    MongoClient mongoClient = new MongoClient();
```suggestion
{
    String input = req.getParameter("input");
    MongoClient mongoClient = new MongoClient();
```

2022-01-26 09:27 UTC, loris-s-sonarsource commented on rules/S5147/java/rule.adoc
> +    MongoClient mongoClient = new MongoClient();
```suggestion
    String input = req.getParameter("input");
    
    MongoClient mongoClient = new MongoClient();
```

2022-01-26 09:27 UTC, loris-s-sonarsource commented on rules/S5147/java/rule.adoc
> +    MongoClient mongoClient = new MongoClient();
```suggestion
{
    String input = req.getParameter("input");
    
    MongoClient mongoClient = new MongoClient();
```

2022-01-31 10:01 UTC, merged