Create rule S1155: VB.NET
SonarSource/rspec pull request #686
Opened 2022-01-10 15:53 UTC by pavel-mikula-sonarsource

2022-01-10 16:15 UTC, csaba-sagi-sonarsource commented on rules/S1155/vbnet/rule.adoc
> +Private Function HasContent(Strings As IEnumerable(Of String)) As Boolean
Why isn't there a compliant solution for `HasContent2`?

2022-01-10 16:15 UTC, csaba-sagi-sonarsource requested changes
Two minor comments left. Both are applicable for the C# part too.

2022-01-11 09:27 UTC, pavel-mikula-sonarsource commented on rules/S1155/vbnet/rule.adoc
> +Private Function HasContent(Strings As IEnumerable(Of String)) As Boolean
Because it's the same as `HasContent`. It was like this in the C# version of the rule as well. I can add both.

2022-01-11 09:33 UTC, csaba-sagi-sonarsource commented on rules/S1155/vbnet/rule.adoc
> +Private Function HasContent(Strings As IEnumerable(Of String)) As Boolean
I don't have a strong opinion but it might be confusing for the users. If you agree please add it, otherwise ignore the comment.

2022-01-11 09:58 UTC, csaba-sagi-sonarsource reviewed
LGTM!

2022-01-11 10:14 UTC, csaba-sagi-sonarsource approved these changes
OK, this time I'll approve too :)

2022-01-18 06:48 UTC, merged