Modify rule S6321: Add GCP examples
SonarSource/rspec pull request #689
Opened 2022-01-11 12:06 UTC by hendrik-buchwald-sonarsource

Implementation ticket: https://jira.sonarsource.com/browse/SONARIAC-311

2022-01-12 13:59 UTC, loris-s-sonarsource requested changes
This text starts by describing what a security group is, but a "security group" can have an ambiguous meaning for GCP - I think we should work to make it more generic

2022-01-12 13:59 UTC, loris-s-sonarsource commented on rules/S6321/metadata.json
>      "aws",
```suggestion
```

2022-01-12 13:59 UTC, loris-s-sonarsource commented on rules/S6321/metadata.json
> +    "aws"
```suggestion
    "aws",
    "gcp",
    "azure"
```

2022-01-12 13:59 UTC, loris-s-sonarsource commented on rules/S6321/description.adoc
> +A security group is a virtual firewall for cloud services to control inbound and outbound traffic. An ingress/security rule allowing traffic from all IP addresses to standard network ports on which a
This text starts by describing what a security group is, but a "security group" can have an ambiguous meaning for GCP

2022-01-12 14:01 UTC, loris-s-sonarsource commented on rules/S6321/terraform/metadata.json
> +    "aws",
non unique element : "aws" is mentioned twice, so I suggest removing it from the beginning and add it with "gcp" and "azure" as last tags

2022-01-12 15:22 UTC, hendrik-buchwald-sonarsource commented on rules/S6321/description.adoc
> +A security group is a virtual firewall for cloud services to control inbound and outbound traffic. An ingress/security rule allowing traffic from all IP addresses to standard network ports on which a
True, I will try to rewrite it. The text changes come from the Azure-related PR. I just merged the changes in this PR.

2022-01-12 16:40 UTC, loris-s-sonarsource commented on rules/S6321/description.adoc
> +A security group is a virtual firewall for cloud services to control inbound and outbound traffic. An ingress/security rule allowing traffic from all IP addresses to standard network ports on which a
Nice ! I'm adding a suggestion of [hard line break](https://docs.asciidoctor.org/asciidoc/latest/blocks/hard-line-breaks/) because I think the sentences are long, and of a minor typo

2022-01-12 16:41 UTC, loris-s-sonarsource commented on rules/S6321/description.adoc
> +Cloud platforms such as AWS, Azure, or GCP support virtual firewalls that can be used to restrict access to services by controlling inbound and outbound traffic. An firewall rule allowing traffic fro
Suggestion:

```suggestion
Cloud platforms such as AWS, Azure, or GCP support virtual firewalls that can be used to restrict access to services by controlling inbound and outbound traffic. +
Any firewall rule allowing traffic from all IP addresses to standard network ports on which administration services traditionally listen, such as 22 for SSH, can expose these services to exploits and unauthorized access.
```

Note: The "+" character is supposed to be a [hard line break](https://docs.asciidoctor.org/asciidoc/latest/blocks/hard-line-breaks/) in ASCIIdocs standards.

2022-01-12 16:42 UTC, loris-s-sonarsource commented on rules/S6321/description.adoc
> +Cloud platforms such as AWS, Azure, or GCP support virtual firewalls that can be used to restrict access to services by controlling inbound and outbound traffic. An firewall rule allowing traffic fro
I also changed "An" to "Any"

2022-01-13 09:49 UTC, hendrik-buchwald-sonarsource commented on rules/S6321/description.adoc
> +A security group is a virtual firewall for cloud services to control inbound and outbound traffic. An ingress/security rule allowing traffic from all IP addresses to standard network ports on which a
Good idea!

2022-01-13 10:45 UTC, loris-s-sonarsource approved these changes
LGTM! 
A question: Why did you also fill "rules/S6321/terraform/metadata.json"?

2022-01-13 10:45 UTC, loris-s-sonarsource commented on rules/S6321/see.adoc
> +* https://docs.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview[Azure Documentation] - Network security groups
```suggestion
* https://docs.microsoft.com/en-us/azure/virtual-network/network-security-groups-overview[Azure Documentation] - Network security groups
* https://cloud.google.com/vpc/docs/using-firewalls[GCP Documentation] - Firewalls
```

2022-01-13 11:00 UTC, hendrik-buchwald-sonarsource commented
> A question: Why did you also fill "rules/S6321/terraform/metadata.json"?

I override the tags in `terraform/metadata.json` to avoid having the GCP tag in the CloudFormation part of the rule, since CloudFormation does not support GCP.

2022-02-11 08:19 UTC, merged