RULEAPI-705 differentiate closed and obsolete rules in the UI
SonarSource/rspec pull request #704
Opened 2022-01-12 18:21 UTC by frederic-tingaud-sonarsource

2022-01-13 11:15 UTC, arseniy-sonar requested changes

2022-01-13 11:15 UTC, arseniy-sonar commented on frontend/src/deployment/metadata.ts
> +  }
It is a nice trick, but I would avoid doing that.
When I see a call
```
const metadata = generate_rule_metadata(dir, 'C', all_languages);
```
The last thing I expect is that `all_languages` gets updated (it is also not documented in the the doc comment).

I propose to collect languages and status to `allLanguages` first, and then `generate_rule_metadata` for each language without changing this array.

2022-01-13 16:10 UTC, frederic-tingaud-sonarsource commented on frontend/src/types/IndexStore.ts
> +export type Status = 'default'|'ready'|'closed'|'deprecated'|'superseded';
I updated the coverage computation to handle superseded and make it a deprecated rule.

2022-01-13 16:10 UTC, frederic-tingaud-sonarsource commented on frontend/src/types/RuleMetadata.ts
> +export interface Language {
I went with LanguageSupport because it's mainly a Language, with an additional information of what it's level of support is at the moment.

2022-01-13 16:11 UTC, frederic-tingaud-sonarsource commented on frontend/src/utils/useRuleCoverage.ts
>    }
Fixed

2022-01-13 16:11 UTC, frederic-tingaud-sonarsource commented on frontend/src/deployment/metadata.ts
> +  }
I changed that.

2022-01-14 14:23 UTC, arseniy-sonar requested changes
Nice job! I appreciate the thorough tests and refactoring of the index generation. There is still things to adjust, though.

On another note, please, do not force-push to this branch, at least not the commits that I've reviewed, so that when doing the next review, I can clearly see the changes since my last review (i.e. since this moment). See also our [review process](https://xtranet-sonarsource.atlassian.net/wiki/spaces/LANG/pages/2165211172/PR+Review+Process).

2022-01-14 14:23 UTC, arseniy-sonar commented on frontend/src/deployment/__tests__/metadata.test.ts
> +      fs.readdirSync(dstPath).forEach(ruleDir => fs.readdirSync(`${dstPath}/${ruleDir}`).
I would also check that `readdirSync` returns a non-empty list. Otherwise, this test is not checking anything. Or perhaps add a count variable, and check its value at the end.

2022-01-14 14:23 UTC, arseniy-sonar commented on frontend/src/SearchHit.tsx
> +    : <Typography key="closed-marker" variant="body2" component="div" classes={{ root: classes.language }}>
```suggestion
    : <Typography key="deprecated-marker" variant="body2" component="div" classes={{ root: classes.language }}>
```

2022-01-14 14:52 UTC, frederic-tingaud-sonarsource commented on frontend/src/deployment/searchIndex.ts
> +}
Ohhh!

2022-01-17 09:55 UTC, frederic-tingaud-sonarsource commented on frontend/src/deployment/utils.ts
> +    .map(f => ({name: f, status: 'default'} as LanguageSupport))
Fixed

2022-01-17 09:55 UTC, frederic-tingaud-sonarsource commented on frontend/src/deployment/searchIndex.ts
> +          {langs: all.langs, tags: all.tags, qualityProfiles: all.qualityProfiles}];
Fixed

2022-01-17 09:56 UTC, frederic-tingaud-sonarsource commented on frontend/src/deployment/searchIndex.ts
> +  all: IndexStats) {
Fixed

2022-01-17 10:10 UTC, frederic-tingaud-sonarsource commented on frontend/src/RulePage.tsx
> +    languagesTabs = metadataJSON.languages_support.map(lang => {
fixed

2022-01-17 10:19 UTC, frederic-tingaud-sonarsource commented on frontend/src/deployment/searchIndex.ts
> +  : [string, IndexedRuleWithDescription] | null {
> update `all` separately
done

> this return type specification : `blabla | null` superior to the syntax of optional : `blabla?`
The `?` is attached to a value, not its type. I think the `| null` is the expected way to declare something that can be null (that's code I just moved, I'm not really an expert on this).

2022-01-17 10:31 UTC, frederic-tingaud-sonarsource commented on frontend/src/deployment/__tests__/metadata.test.ts
> +      fs.readdirSync(dstPath).forEach(ruleDir => fs.readdirSync(`${dstPath}/${ruleDir}`).
fixed

2022-01-17 17:13 UTC, arseniy-sonar requested changes
It's coming together. Just a few small nits, and a surprising discovery of a `beta` status.

2022-01-17 17:13 UTC, arseniy-sonar commented on frontend/src/deployment/searchIndex.ts
> +  ruleDir: string) {
```suggestion
function buildOneRuleRecord(allLanguages: string[], rulesPath: string, ruleDir: string) {
```
Feel free to discard this stylistic edit. Personally I find it more readable to have arguments on one line when they fit.

2022-01-17 17:13 UTC, arseniy-sonar commented on frontend/src/deployment/searchIndex.ts
> +    supportedLanguages.push({name: lang, status: metadata.status ?? 'ready'});
In what circumstance is `metadata.status` `null`?

2022-01-17 17:13 UTC, arseniy-sonar commented on frontend/src/types/RuleMetadata.ts
> +export type Status = 'ready' | 'closed' | 'deprecated' | 'superseded';
Sorry to pick on it again, but I was surprised myself, turns out [there is](https://github.com/SonarSource/rspec/blob/master/rspec-tools/rspec_tools/validation/rule-metadata-schema.json#L17) one more value for status: `beta` (until now no rule used it, now we have [one](https://github.com/SonarSource/rspec/blob/master/rules/S6389/text/metadata.json#L4)). I think it should be handled identically to `ready`.

2022-01-17 17:46 UTC, frederic-tingaud-sonarsource commented on frontend/src/types/RuleMetadata.ts
> +export type Status = 'ready' | 'closed' | 'deprecated' | 'superseded';
;_;
fixed

2022-01-17 17:47 UTC, frederic-tingaud-sonarsource commented on frontend/src/deployment/searchIndex.ts
> +    supportedLanguages.push({name: lang, status: metadata.status ?? 'ready'});
I don't know why I thought I saw missing statuses, but you're right, I put an assert, rerun the predeploy script and didn't get any error.

2022-01-17 17:48 UTC, frederic-tingaud-sonarsource commented on frontend/src/deployment/metadata.ts
> +   allMetadata.map(m => ({name: m.language, status: m.metadata.status ?? 'ready'} as LanguageSupport));
you're right. fixed

2022-01-17 19:12 UTC, arseniy-sonar approved these changes

2022-01-17 19:13 UTC, merged