RULEAPI-682: Index multiple types and rules with no languages
SonarSource/rspec pull request #728
Opened 2022-01-19 17:27 UTC by marco-antognini-sonarsource

This lacks some end-to-end testing, such as search.

2022-01-20 10:01 UTC, marco-antognini-sonarsource commented
(This ain't ready for review -- just an attempt at triggering the CI jobs.)

2022-01-21 10:33 UTC, marco-antognini-sonarsource commented
@arseniy-sonar this is now ready. FWIW There are two code smells I'm not sure how to address.

2022-01-21 17:39 UTC, arseniy-sonar requested changes
Nice job testing the deployment scripts!
Mostly good, I just left a few nitpicks and refactoring suggestions.

2022-01-21 17:39 UTC, arseniy-sonar commented on frontend/src/deployment/metadata.ts
>  }
Frankly, I think "parent" and "child" names a swapped here. The semantics is correct, but it is mindboggling to think of the root rule directory as a "child" and the language subdirectory as a "parent". If you agree do you mind swapping the names (as you are rewriting this function anyway)?

2022-01-21 17:39 UTC, arseniy-sonar commented on frontend/src/deployment/metadata.ts
> +  fs.writeFileSync(file, JSON.stringify(metadata), { encoding: 'utf8' });
```suggestion
  fs.writeFileSync(file, JSON.stringify(metadata, null, 2), { encoding: 'utf8' });
```
I agree with keeping the `rule-index-store.json` short - with no line breaks or indentation. However, I think we should keep the metadata for each rule readable, in case some want's to inspect the `language-metadata.json` file, or download it somewhere else.
These files are relatively short, so I don't think this adds much overhead, but substantially improves readability.

2022-01-21 17:39 UTC, arseniy-sonar commented on frontend/src/deployment/metadata.ts
> +function getAllKeys(allMetadata: { metadata: any }[]) {
Regarding the codesmells on SQ, I think you can specify that you expect the `metadata` to be of a type that has an `sqKey` field and an (optional) `extra` field that is an object that has an (optional) `legacyKeys` field, just like you did for the `allMetadata` type.

2022-01-21 17:39 UTC, arseniy-sonar commented on frontend/src/deployment/metadata.ts
> +function generateGenericMetadata(srcDir: string, dstDir: string, branch: string, prUrl?: string) {
If it is not forbidden yet, it should be forbidden to open a new-rule PR with no language, so you don't need to handle the `prUrl` parameter for rules with no language.

By "forbidden" I mean checked by CI validation. the deployment probably shouldn't crash, just emit a warning, to avoid having one broken PR to prevent the entire frontend from deployment.

2022-01-21 17:39 UTC, arseniy-sonar commented on frontend/src/deployment/description.ts
> +function getRuleAdoc(srcDir: string, language?: string) {
This looks like a false abstraction. AFAIK, you call this `getRuleAdoc` from two places, and in one place you provide the `language` argument in another - not. Inside the function you branch on whether the argument is provided. So looks like you are trying to smash together two different functions `getSpecificRuleAdoc` and `getGenericRuleAdoc`. They might share some logic, but their differences unnecessarily multiply the complexity of the function body.

2022-01-21 17:39 UTC, arseniy-sonar commented on frontend/src/deployment/__tests__/searchIndex.test.ts
> +  }
should this be a part of an "afterEach" fixture?

2022-01-21 17:39 UTC, arseniy-sonar commented on frontend/src/deployment/__tests__/searchIndex.test.ts
> +// These search functions mimic the behaviors of useSearch.ts.
How painful is it to factor out the "behaviors of useSearch.ts" and call them from this test? (To make sure they faithfully mimic these behaviors)

2022-01-24 15:31 UTC, marco-antognini-sonarsource reviewed
Thanks for the feedback. :-)

2022-01-24 15:31 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/metadata.ts
> +  fs.writeFileSync(file, JSON.stringify(metadata), { encoding: 'utf8' });
Currently, AFAICT, those JSON files are not easily downloadable. At least I couldn't find links to them (although if you know where they are you can handcraft the URLs). So I wouldn't expect people to download them. If someone really wants them, they can easily reformat them too (using `python -m json.tool` for example).

In numbers, I just measured a reduction of 30%: before we had 10.14MB of `*-metadata.json` files, now about 7.03MB.

The readability aspect isn't modified by this change: they are pretty printed anyway in `RulePage.tsx` anyway.

2022-01-24 15:31 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/metadata.ts
> +function generateGenericMetadata(srcDir: string, dstDir: string, branch: string, prUrl?: string) {
Thanks, I knew I was forgetting something! I'll check and improve this.

2022-01-24 15:31 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/metadata.ts
>  }
Sure, sounds good. 👍

2022-01-24 17:24 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/metadata.ts
>  }
Should be better now. I've used other names to remove any ambiguity. Hopefully, that helps.

2022-01-24 17:24 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/metadata.ts
> +function getAllKeys(allMetadata: { metadata: any }[]) {
I've improved this a bit thanks to your advice.

2022-01-24 17:27 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/__tests__/searchIndex.test.ts
> +// These search functions mimic the behaviors of useSearch.ts.
Yup, that was a good idea -- I realized some of the testing I wrote wasn't meaningful. If you wonder, I had to replace "be should" with "should be used" to avoid triggering a match on the third rule. The new testing is a bit more relaxed but it fits more closely what the search page is doing.

2022-01-24 17:28 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/metadata.ts
> +function generateGenericMetadata(srcDir: string, dstDir: string, branch: string, prUrl?: string) {
(If you're reading the update I just pushed, wonder not: this wasn't addressed yet.)

2022-01-25 16:39 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/metadata.ts
> +function generateGenericMetadata(srcDir: string, dstDir: string, branch: string, prUrl?: string) {
This wasn't trivial as I had to learn a bit about pytest and Cirrus along the way, but it should be better now: the CI job will run additional checks only on modified rules. As written, the additional checks are simple: there must be one language. Later we could add more specific checks if needed. In other words, this new check is not run on rules already on master.

2022-01-25 16:40 UTC, marco-antognini-sonarsource commented on .cirrus.yml
> +  env:
This is required otherwise `git merge-base` fails.

2022-01-25 16:41 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/metadata.ts
> +type Metadata = any;
This is still using `any`. Hopefully, this is okay. Let me know if you have a better idea.

2022-01-25 16:42 UTC, marco-antognini-sonarsource commented on frontend/src/utils/useSearch.ts
> +import lunr from 'lunr';
I took the opportunity to some of the clean existing code smells. :-)

2022-01-25 16:43 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/cli.py
> +def validate_modified_rule_metadata(rule_key: str):
SQ coverage fails because of that function. I'm not sure how it should be tested... Maybe we should have a dedicated ticket to improve this coverage?

2022-01-26 07:27 UTC, arseniy-sonar reviewed
I did not have time to finish the review before the interview. I left some small notes and one that calls for some thinking. Feel free to address them now. I'll have another look after lunch.

2022-01-26 07:27 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/cli.py
> +  '''
Something is bothering me with this differentiation: "validation for all metadata" vs. "validation for metadata of changed rules":
- if a rule did not change, why validate its metadata again (as in "validation for all metadata")?
- why run some validation for the changed rules (which does not look at what changed specifically) - will it fail for a rule once it is no longer changing?

I understand that you implemented this to make sure some validation is run for PRs introducing new rules, but if I didn't discuss it with you, I would look at this (as it happened when I looked at this before remembering our discussion) and be perplexed.

IMO, running metadata validation only on the subset of rules that changed makes sense. It wasn't done before only because metadata validation is cheap and there was no need to optimize it (unlike adoc validation). However, it would be simpler to understand if running validation for a rule would always give the same result: valid/invalid regardless of whether this rule was just created, or is an old one; modified or not; on the `master` or on a fresh branch.

I don't see a solution that would reconcile the wishes above and the distinction we wanted to make between the old rules with no language and introducing a new rule/removing the last language from an existing rule. Maybe hardcode the list of rules for which it is OK to have no language? Or allow all the `closed` rules to have no language?

2022-01-26 08:48 UTC, marco-antognini-sonarsource commented on ci/validate_metadata.sh
> +modifiedRules="$(git diff --name-only "${base}" -- rules | sed -Ee 's#rules/(S[0-9]+)/.*#\1#' | sort -u)"
> Why does one require the CIRRUS_CLONE_DEPTH setting and the other one not?

Both actually do, and that's how I figured out how to fix the CI failures.

> How is this different from the similar snippet in validate_asciidoc.sh ?

In terms of main differences: here we only look at `rules/` and no other directories, which allows writing a simpler command.

Aside from that, here I followed shellcheck's recommendations for quotes and error handling.

> Also, like in validate_asciidoc.sh I'd extend the modifiedRules set to all rules if any relevant script is modified.

The purpose of my change was to run an extra set of checks on modified rules only, in addition to running the existing checks for all rules. So following the same logic as `validate_asciidoc.sh` was not necessary. Let's discuss whether/how we want to modify this in your other comment.

2022-01-26 08:56 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/cli.py
> +  '''
> I understand that you implemented this to make sure some validation is run for PRs introducing new rules, but if I didn't discuss it with you, I would look at this (as it happened when I looked at this before remembering our discussion) and be perplexed.
> [...]
> However, it would be simpler to understand if running validation for a rule would always give the same result: valid/invalid regardless of whether this rule was just created, or is an old one; modified or not; on the master or on a fresh branch.

That's a very fair point indeed.

> IMO, running metadata validation only on the subset of rules that changed makes sense. It wasn't done before only because metadata validation is cheap and there was no need to optimize it (unlike adoc validation).

That's simple enough to do it, so why not indeed. 👍 

> I don't see a solution that would reconcile the wishes above and the distinction we wanted to make between the old rules with no language and introducing a new rule/removing the last language from an existing rule. Maybe hardcode the list of rules for which it is OK to have no language? Or allow all the closed rules to have no language?

To keep things as simple as possible, and therefore easily modifiable in the future, a fixed list of known exception might be better. At least, when a new rule is introduced and the test fails, someone will have to acknowledge what they are doing is probably not adequate. Also, it seems to follow more closely the historical evolution of this project.

With a generic exception for closed rules, someone may remove (by mistake) language specification.

2022-01-26 09:59 UTC, marco-antognini-sonarsource commented on ci/validate_metadata.sh
> +invalid=0
done in 99ee0cc

2022-01-26 10:00 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/metadata.ts
> +  extra: undefined | { legacyKeys: undefined | string[] },
done in 3c90f6e

2022-01-26 12:43 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/cli.py
> +def validate_modified_rule_metadata(rule_key: str):
> Maybe we should have a dedicated ticket to improve this coverage?

I should rephrase that: we _should_ do it. I'll open a ticket for this. Reason being: `validate_rules_metadata` was incorrect already: `rule.key` should have been `rule.id`, for example.

2022-01-26 12:45 UTC, marco-antognini-sonarsource commented on ci/validate_metadata.sh
> +fi
I'll leave this as-is for now to avoid more scope creep, but these commands could be extracted to a shared file and reused in `validate_asciidoc.sh`.

2022-01-26 12:52 UTC, marco-antognini-sonarsource commented on ci/validate_metadata.sh
> +modifiedRules="$(git diff --name-only "${base}" -- rules | sed -Ee 's#rules/(S[0-9]+)/.*#\1#' | sort -u)"
BTW, there seems to be an existing check already: https://github.com/SonarSource/rspec/blob/1ca56eaf428fbd35c3eced18fb1b98f3a906049a/ci/validate_asciidoc.sh#L50-L56
However, I was not expecting to find metadata checks in asciidoc validation code, and I'm not sure how robust it is. For these reasons, I went ahead and updated the python scripts to properly validate metadata.

2022-01-26 14:22 UTC, arseniy-sonar approved these changes
Great job! I left a few comments and suggestions. I probably won't be able to do another review before leaving today, but that's not needed. Whether or not you take action on my comments, it is good to go.

2022-01-26 14:22 UTC, arseniy-sonar commented on frontend/src/utils/useSearch.ts
> +export function filterTypes(q: lunr.Query, type: string) {
This family of functions, modify its first argument, which might surprise someone like me reading the code.
You might want to rename them using a more "impure" verb. for example: `addFilterForTypes`.
Even better, IMO, would be to subclass `lunr.Query` and define these functions as member-functions.

So for a function that modifies `q`, for me in order from the least surprise to the most would be the call sites:
- `q.addFilterForTypes(type)`
- `q.filterTypes(type)`
- `addFilterTypes(q, type)`
- `filterTypes(q, type)`

2022-01-26 14:22 UTC, arseniy-sonar commented on frontend/src/utils/useSearch.ts
> +export function filterTypes(q: lunr.Query, type: string) {
btw, the function name mentions `types`, but the argument is called `type` - something does not match here.

2022-01-26 14:22 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/metadata.py
> +def validate_rule_metadata(rule: GenericRule):
The name is confusing here: `validate_metadata` vs `validate_rule_metadata`, although the argument types help.
How about renaming into: `validate_rule_metadata` and `validate_metadata_of_language_specific_rule`, or along those lines? To make it clear when looking at the two which one you should use in each case.

2022-01-26 14:22 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/validation/metadata.py
> +      raise RuleValidationError(f'Rule {rule.id} should have no specializations')
Perhaps add the (shorter version of) the comment to the error message?
e.g.
```suggestion
      # When this triggers, ask yourself whether the rule should be removed from RULES_WITH_NO_LANGUAGES
      raise RuleValidationError(f'Rule {rule.id} should have no specializations. Forgot to remove it from the list?')
```

2022-01-26 14:23 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/cli.py
> +  '''
Agreed.

2022-01-26 15:20 UTC, marco-antognini-sonarsource commented on frontend/src/utils/useSearch.ts
> +export function filterTypes(q: lunr.Query, type: string) {
Good idea to rename the function. Will do.

Regarding `types` vs `type`, it's because a rule can have multiple types but the user filters using one type only. It's a bit awkward indeed.

2022-01-26 15:22 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/validation/metadata.py
> +def validate_rule_metadata(rule: GenericRule):
What about `validate_rule_metadata` vs `validate_rule_specialization_metadata` to reuse existing terminology?

2022-01-26 16:36 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/validation/metadata.py
> +      raise RuleValidationError(f'Rule {rule.id} should have no specializations')
Done in d8ab57a.

2022-01-26 16:36 UTC, marco-antognini-sonarsource commented on frontend/src/utils/useSearch.ts
> +export function filterTypes(q: lunr.Query, type: string) {
Done in c44ce47.

2022-01-26 16:37 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/validation/metadata.py
> +def validate_rule_metadata(rule: GenericRule):
done in c44ce47

2022-01-27 15:15 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/cli.py
> +def validate_modified_rule_metadata(rule_key: str):
https://jira.sonarsource.com/browse/RULEAPI-735

2022-01-28 08:51 UTC, merged