Modify Rule S6329: Make generic and add GCP
SonarSource/rspec pull request #733
Opened 2022-01-20 13:31 UTC by hendrik-buchwald-sonarsource

Implementation ticket: https://jira.sonarsource.com/browse/SONARIAC-325

2022-01-20 13:39 UTC, hendrik-buchwald-sonarsource commented
@loris-s-sonarsource I have only added Compute instance for now. Do you think that is sufficient or should I add all the other possible resources as well?

2022-01-20 13:50 UTC, loris-s-sonarsource requested changes
Oh no, I started a review, but there is already a PR open for this: https://github.com/SonarSource/rspec/pull/655

2022-01-20 13:50 UTC, loris-s-sonarsource commented on rules/S6329/terraform/rule.adoc
> +      // Ephemeral public IP
```suggestion
    access_config {  # Sensitive
      # Ephemeral public IP
```

2022-01-20 13:55 UTC, loris-s-sonarsource commented
> @loris-s-sonarsource I have only added Compute instance for now, as an example. Do you think that is sufficient or should I add all the other possible resources as well?

@hendrik-buchwald-sonarsource Yes, I think that GCP doesn't seem to have resources with a clear public IP management (except maybe [notebooks_instance#no_public_ip](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/notebooks_instance#no_public_ip))

2022-01-20 13:57 UTC, hendrik-buchwald-sonarsource commented
@loris-s-sonarsource ah, I will rebase this tomorrow on your changes. I have some resources with public IP, see the security-expected-issues PR. I checked more resources but discarded them for some reason or another.

2022-01-21 08:46 UTC, loris-s-sonarsource approved these changes
LGTM! Minor suggestion on snippet comments

2022-03-03 08:41 UTC, merged