Use a more readable form to display parameters
SonarSource/rspec pull request #747
Opened 2022-01-25 15:31 UTC by frederic-tingaud-sonarsource

2022-01-26 15:13 UTC, marco-antognini-sonarsource requested changes
Overall, looks good. Could you share a screenshot or two to see what it will look like?

2022-01-26 15:13 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +          continue
Regarding the (missing) coverage and code smells, I think it's fine. I made a comment about low coverage on cli.py in https://github.com/SonarSource/rspec/pull/728#discussion_r791913044, so at least for that file, I wouldn't invest too much energy right now.

2022-01-26 15:37 UTC, arseniy-sonar requested changes
I went through about 60% of the changed files, so I think I've seen most of the quirks, and left comments. I see that Marco has also left some comments, so I'll leave it to him to continue, but I think once you take the suggestions into account, it is ready to be merged. 

Please also describe in the README the required format of parameters. It might be very frustrating to have a CI failure on the parameter specification and not know how they should look like.

2022-01-26 15:37 UTC, arseniy-sonar commented on rules/S100/php/parameters.adoc
> +*format * [ `+^[a-z][a-zA-Z0-9]*$+` ]::
Should it be
```suggestion
*format* [ `+^[a-z][a-zA-Z0-9]*$+` ]::
```
or
```suggestion
*format*: [ `+^[a-z][a-zA-Z0-9]*$+` ]::
```
or
```suggestion
*format*: * [ `+^[a-z][a-zA-Z0-9]*$+` ]::
```

2022-01-26 15:37 UTC, arseniy-sonar commented on rules/S1067/vbnet/parameters.adoc
> +*max * [ `+3+` ]::
See my previous comment. I feel that in many cases, when the parameter has no type specified, the second `*` should go immediately after the parameter name, otherwise the formatting seems to be off (at least on github)

2022-01-26 15:37 UTC, arseniy-sonar commented on rules/S6192/cfamily/parameters.adoc
> +  The maximum authorized complexity.
I guess your script got confused by the second empty `key`
```suggestion
```
Please check for other parameters with empty keys.

2022-01-26 15:37 UTC, arseniy-sonar commented on rules/S4328/javascript/parameters.adoc
> +
Here the input was incorrect, but the output got more incorrect.

2022-01-26 15:37 UTC, arseniy-sonar commented on rules/S3921/parameters.adoc
> +*ignoredDataItemRegex* [ `+false+` ]::
```suggestion
*ignoredDataItemRegex*::
```
Default wasn't specified for this second parameter.

2022-01-26 15:37 UTC, arseniy-sonar commented on rules/S2149/parameters.adoc
> +*coverage_threshold* [ `+250+` ]::
Again, no default was specified for this second parameter.

2022-01-26 15:37 UTC, arseniy-sonar commented on rules/S1642/parameters.adoc
> +*format *: STRING [ `+^[A-Z][a-zA-Z0-9]*$+` ]::
Even for typed params, it seems to be the stray space at the end of the parameter key that gets in between the key and the closing `*` (for bold) thus breaking the formatting.

2022-01-26 15:51 UTC, frederic-tingaud-sonarsource commented on ci/validate_asciidoc.sh
> +    affected_rules="rules/*"
According to shellcheck, it doesn't expand in either case, so they recommend the quoted version to make it clear: https://www.shellcheck.net/wiki/SC2125

2022-01-26 15:53 UTC, frederic-tingaud-sonarsource commented on ci/validate_asciidoc.sh
> +      exit_code=1
fixed

2022-01-26 15:54 UTC, frederic-tingaud-sonarsource commented on ci/validate_asciidoc.sh
> +  cd rspec-tools || exit 1
fixed

2022-01-26 15:56 UTC, frederic-tingaud-sonarsource commented on ci/validate_asciidoc.sh
> +  cd rspec-tools || exit 1
If the folder is not here or not accessible, the `cd` will fail and the rest of the script will execute and write stuff in the wrong directory.
That's all ShellCheck speaking, I'm just a noob following his static analyzer tools :)

2022-01-26 16:06 UTC, frederic-tingaud-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +          continue
I agree completely.

2022-01-26 16:06 UTC, frederic-tingaud-sonarsource commented on rules/S100/abap/parameters.adoc
> +*format*: STRING [ `+^([A-Z0-9_]*|[a-z0-9_]*)$+` ]::
There are other ways to display it unformatted, but on another line. I liked the condensed look of that, but it's true it's not the simplest.

2022-01-26 16:06 UTC, frederic-tingaud-sonarsource commented on rules/S1067/vbnet/parameters.adoc
> +*max * [ `+3+` ]::
Thanks for catching that!

2022-01-26 16:06 UTC, frederic-tingaud-sonarsource commented on rules/S116/parameters.adoc
>  === Parameters
Yes for other languages like C# and JS.
The ascii_validator.sh should protect us against any unused file.

2022-01-26 16:06 UTC, frederic-tingaud-sonarsource commented on rules/S2149/parameters.adoc
> +*coverage_threshold* [ `+250+` ]::
Wow, thanks for catching that.

2022-01-26 16:37 UTC, frederic-tingaud-sonarsource commented on rules/S1642/parameters.adoc
> +*format *: STRING [ `+^[A-Z][a-zA-Z0-9]*$+` ]::
script fixed

2022-01-26 16:37 UTC, frederic-tingaud-sonarsource commented on rules/S3921/parameters.adoc
> +*ignoredDataItemRegex* [ `+false+` ]::
script fixed, thanks for noticing it.

2022-01-26 16:38 UTC, frederic-tingaud-sonarsource commented on rules/S100/cfamily/parameters.adoc
> -* key = format
After fixing the problems Arsenyi found: https://github.com/SonarSource/languages-experimental-tooling/blob/master/personal/fred-tingaud/rspec/clean.py

2022-01-27 08:50 UTC, marco-antognini-sonarsource commented on ci/validate_asciidoc.sh
> +    affected_rules="rules/*"
I think there's a mistake on that wiki page.

> var=*.png or var={1..9} will just assign the literal strings '*.png' and '{1..9}'.

This is true for `var={1..9}` but not always true for `var=*.png`: if there is at least one matching png file, it will expand.

I haven't dug into bash's man page to validate this, but that's what happens in practice for me with `affected_rules=rules/*`: executing this from the root of the git repo works as expected.

Since you reverted that change, I'll mark the discussion as resolved. To be further investigated when we cleanup this bash script I suppose. :-)

2022-01-27 08:51 UTC, marco-antognini-sonarsource commented on ci/validate_asciidoc.sh
> +    find "$dir" -name "*.adoc" ! -name 'rule.adoc' -exec sh -c 'realpath $1' shell {} \; > created
> That's the shellcheck recommended pattern to avoid filenames with weird characters breaking everything.

That's good to know! :-)

2022-01-27 08:52 UTC, marco-antognini-sonarsource commented on rules/S100/abap/parameters.adoc
> +*format*: STRING [ `+^([A-Z0-9_]*|[a-z0-9_]*)$+` ]::
Thanks for exploring other solutions. The proposed solution is regular enough to get used to it, I believe. And if it's confusing too many people we can revisit. 👍

2022-01-27 11:48 UTC, marco-antognini-sonarsource requested changes
I can see you put a good deal of effort into this! Huge step forward in terms of normalization! 🎉 

I ran locally your script (which looks fine) and looked at the diff & unhandled lines. No big issues, only a quirk or two.

2022-01-27 11:48 UTC, marco-antognini-sonarsource commented on rules/S1578/cobol/parameters.adoc
> +*format* [ `+[A-Z]+ +` ]::
There's an extra space there. 🙈

2022-01-27 15:40 UTC, frederic-tingaud-sonarsource commented on rules/S1545/pli/parameters.adoc
> +*regularExpression* [ `+[a-zA-Z0-9_]{plus}{plus}+` ]::
Double backquotes are not necessary. What is needed is backquote plus.
I ran a simple regex to replace the `{plus}` in default parameters.

2022-01-27 15:40 UTC, frederic-tingaud-sonarsource commented on rules/S1578/cobol/parameters.adoc
> +*format* [ `+[A-Z]+ +` ]::
Indeed. Fixed on all (2) files with this problem.

2022-01-27 15:40 UTC, frederic-tingaud-sonarsource commented on docs/description.adoc
> +
Done.

2022-01-27 15:41 UTC, frederic-tingaud-sonarsource commented on docs/description.adoc
> +* Deprecated
I put an adoc in docs with just this list, that is used by the validation script.

2022-01-27 15:41 UTC, frederic-tingaud-sonarsource commented on README.adoc
> -====
I created a dedicated file

2022-01-28 13:55 UTC, marco-antognini-sonarsource requested changes

2022-01-28 13:55 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/validation/description.py
> +SECTION_NAMES_FILE=open(SECTION_NAMES_PATH, 'r', encoding='utf-8').readlines()
`open(...)` may leak and therefore should be closed. In some context, a warning may be emitted I think. Instead, you can try something like this:

```suggestion
SECTION_NAMES_PATH = Path(__file__).parent.parent.parent.parent.joinpath('docs/section_names.adoc')
SECTION_NAMES_FILE = SECTION_NAMES_PATH.read_text(encoding='utf-8').split('\n')
```

2022-01-28 13:55 UTC, marco-antognini-sonarsource commented on rules/S1545/pli/parameters.adoc
> +*regularExpression* [ `+[a-zA-Z0-9_]{plus}{plus}+` ]::
Unfortunately, it seems broken: https://github.com/SonarSource/rspec/blob/77f3c56ac522d43ea569150967e414cf62866437/rules/S139/vb6/parameters.adoc

2022-02-01 09:39 UTC, marco-antognini-sonarsource commented on rules/S1545/pli/parameters.adoc
> +*regularExpression* [ `+[a-zA-Z0-9_]{plus}{plus}+` ]::
The update addressed this, thanks.

2022-02-01 10:08 UTC, marco-antognini-sonarsource approved these changes
Thanks for the update, LGTM. Some minor suggestions, ready to merge when you feel like it. 👍

2022-02-01 10:08 UTC, marco-antognini-sonarsource commented on rules/S1912/cfamily/parameters.adoc
> +asctime,crypt,ctermid,ctime,fgetgrent,fgetpwent,fgetspent,getgrent,getgrgid,getgrnam,gethostbyaddr,gethostbyname,gethostbyname2,gethostent,getlogin,getnetbyaddr,getnetbyname,getnetent,getnetgrent,get
This generates a monstrous line.
I think we can ignore this corner case for now.

2022-02-01 10:08 UTC, marco-antognini-sonarsource commented on rules/S1928/html/parameters.adoc
> +\http://java.sun.com/jstl/sql
```suggestion
http://java.sun.com/jstl/sql
```

I wonder if it was a typo in the first place.

2022-02-01 10:17 UTC, arseniy-sonar commented on rules/S1928/html/parameters.adoc
> +\http://java.sun.com/jstl/sql
I think this came from Jira's url escaping

2022-02-01 10:39 UTC, frederic-tingaud-sonarsource commented on rspec-tools/tests/resources/invalid-rules/S100/cfamily/rule.html
> +<body class="book">
RULEAPI-738 created

2022-02-01 10:48 UTC, frederic-tingaud-sonarsource commented on rules/S1912/cfamily/parameters.adoc
> +asctime,crypt,ctermid,ctime,fgetgrent,fgetpwent,fgetspent,getgrent,getgrgid,getgrnam,gethostbyaddr,gethostbyname,gethostbyname2,gethostent,getlogin,getnetbyaddr,getnetbyname,getnetent,getnetgrent,get
indeed. It would wordwrap if there was any whitespace, but there are none. I think handling this specific case better than it currently is would break others (a coma is not the correct splitting point for a regex for example).

2022-02-01 10:48 UTC, frederic-tingaud-sonarsource commented on rules/S1928/html/parameters.adoc
> +\http://java.sun.com/jstl/sql
I'll make a different PR for the escaped JIRA URLs, because we have a lot of them.

2022-02-01 12:25 UTC, merged

2022-02-01 12:26 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/resources/invalid-rules/S100/cfamily/rule.html
> +<body class="book">
Thanks!