RULEAPI-633: Autolink RSPECs
SonarSource/rspec pull request #770
Opened 2022-02-01 16:38 UTC by marco-antognini-sonarsource

2022-02-01 16:43 UTC, marco-antognini-sonarsource commented on frontend/src/RulePage.tsx
> +    // This should be moved somewhere else... here it is not executed when the page is loaded.
I wrote something like this before 500a488b041c9d8e198c229af4375ffa6d2602d8 and it "worked" -- i.e. the links href were populated as expected. Now it doesn't work anymore. This is way outside my zone of comfort, so probably a completely different solution is required anyway.

@frederic-tingaud-sonarsource do you have any advice on how I can modify the description when it's loaded?

2022-02-01 18:17 UTC, frederic-tingaud-sonarsource commented on frontend/src/RulePage.tsx
> +    // This should be moved somewhere else... here it is not executed when the page is loaded.
I think when you run this, the page is not updated yet. So document.getElementByClassName gets nothing.
I was looking at this library: https://www.npmjs.com/package/html-react-parser
If we use that instead of dangerouslySetInnerHTML, you could have the DOM of descHTML before we render it. It would also help for code highlighting.

2022-02-02 08:11 UTC, marco-antognini-sonarsource commented on frontend/src/RulePage.tsx
> +    // This should be moved somewhere else... here it is not executed when the page is loaded.
Thanks. Looks promising indeed. I'll try to give it a shot.

2022-02-02 17:27 UTC, marco-antognini-sonarsource commented on frontend/src/RulePage.tsx
> +  // FIXME implement me.
I need to create a follow-up ticket for that -- I'd rather have a basic feature now than extend the scope of investigation further -- and update the comment.

2022-02-02 17:29 UTC, marco-antognini-sonarsource commented on frontend/src/RulePage.tsx
> +    // This should be moved somewhere else... here it is not executed when the page is loaded.
Your work in #771 was exactly what I needed, thanks!

As it stands, this PR will conflict with yours. I don't mind in which order they are handled. I suppose, given the size of yours, it's best to go ahead with #771 first.

2022-02-02 19:10 UTC, frederic-tingaud-sonarsource commented on frontend/src/RulePage.tsx
> +  // FIXME implement me.
My issue with this FIXME, is that it hints in a direction that might not be the right one. I think the check will need to be asynchronous, so I don't expect `doesRuleExistForLanguage` to be used as-is.
Perhaps it would be simpler to put the FIXME in `getRspecPath` and not use `language` at all.

2022-02-03 08:43 UTC, marco-antognini-sonarsource commented on frontend/src/RulePage.tsx
> +  // FIXME implement me.
That's a very good point. I've opened the ticked and removed unnecessary code.

2022-02-03 08:48 UTC, arseniy-sonar commented on frontend/src/RulePage.tsx
> +    // This should be moved somewhere else... here it is not executed when the page is loaded.
Beware that #771 is contingent on releasing rule-api that ignores the changes from #771, so it might take a while to arrive.

2022-02-03 09:42 UTC, marco-antognini-sonarsource commented on frontend/src/RulePage.tsx
> +    // This should be moved somewhere else... here it is not executed when the page is loaded.
I don't mind waiting a bit, given the size of #771 it's probably the best thing to do in terms of collective work.

2022-02-04 08:16 UTC, marco-antognini-sonarsource commented
(requesting review to be ready once #771 is merged and speed up the process a tiny bit.)

2022-02-04 15:09 UTC, frederic-tingaud-sonarsource requested changes
I see an issue with the code sections.

2022-02-04 15:09 UTC, frederic-tingaud-sonarsource commented on frontend/src/deployment/description.ts
> +  return html.replace(
I don't think we can do it blindly like that, because there are rules mentioning RSPEC ids in their code sections. See for example https://sonarsource.github.io/rspec/#/rspec/S3470

2022-02-04 15:21 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/description.ts
> +  return html.replace(
Seems to work fine: https://marco-antognini-sonarsource.github.io/rspec/#/rspec/S3470/cfamily (aside from the fact this implemented rule refers to a rule that isn't implemented yet...)

What issue could we expect?

2022-02-04 17:42 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/description.ts
> +  return html.replace(
I've included #771 and fixed the merge conflicts. But I'll need to investigate more. It seems to work fine on GitHub (cf my fork), but when running locally I get some strange issues.

1. go to http://localhost:3000/rspec#/rspec/S3470/cfamily
2. click on a link to S5963 (the one in the code snippet is not clickable, but the one under Comments And Links is)
3. in the console I get errors such as:
```
react-dom.development.js:10301 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```
but if I reload or copy/paste the link, it works...

2022-02-07 10:58 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/description.ts
> +  return html.replace(
I still don't know why locally I get errors but I don't on my fork's github pages...

However, I've made the following observation using the same testing protocol as above:
* removing the `data-rspec-id` attributes from links in `frontend/public/rules/S5963/default-description.html` doesn't change a thing (so I restored them back)
* removing the `data-lang` attributes from `<code>` removes the errors.

I've also checked, there are no nested links in `code` on S5963.

In other words, the issue seems to happen when triggering the links on S3470 but because of `<Highlight>`.

Looking at the stacktraces, I'm not sure how to debug this... :/

2022-02-07 11:28 UTC, frederic-tingaud-sonarsource commented on frontend/src/deployment/__tests__/resources/metadata/S1000/cfamily-description.html
> +     // I am an auto link in some source code: <a data-rspec-id="S987" class="rspec-auto-link">S987</a>.
We want the opposite. Inside a <pre> section, this link should not be generated as it will not work.

2022-02-07 11:33 UTC, frederic-tingaud-sonarsource commented on frontend/src/deployment/description.ts
> +  return html.replace(
The problems I see: Inside a `<pre>` section, we shouldn't do the change. Another problem I see when clicking on your link is that you should also disable it inside other urls like Evgeny's comment on S3470.

2022-02-07 15:36 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/description.ts
> +  return html.replace(
Okay, so I followed your suggestion and it does indeed solve the problem. I believe it was a bug in the highlighting component because `<a>` are allowed in `<pre>` according to the [spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-pre-element) (as any other "Phrasing content"), but solving that would be more tedious than not having the links. (Let's keep that pandora box closed for now.)

The new implementation also doesn't make replacements within existing URLs.

2022-02-07 15:36 UTC, marco-antognini-sonarsource commented on frontend/src/deployment/__tests__/resources/metadata/S1000/cfamily-description.html
> +     // I am an auto link in some source code: <a data-rspec-id="S987" class="rspec-auto-link">S987</a>.
done.

2022-02-07 15:37 UTC, marco-antognini-sonarsource commented
The fork preview was updated at https://marco-antognini-sonarsource.github.io/rspec/#/rspec/S3470

2022-02-07 15:38 UTC, frederic-tingaud-sonarsource approved these changes
That looks pretty cool and robust to me!

2022-02-07 18:16 UTC, merged