Update readme
SonarSource/rspec pull request #79
Opened 2021-05-31 13:59 UTC by amelie-renard-sonarsource

2021-06-01 12:43 UTC, arseniy-sonar requested changes
Can you please, also, reformulate these sentences:
```
Go to the Search Page to find the rules that have already been merged in the master branch.

Go the the GitHub pull-request tab to find the rules that have not been merged yet. You can use the "Search in unimplemented" link on the Search Page to repeat your search in the PRs.
```

And fix the typo: "create a PR entitled" -> "create a PR named".

2021-06-01 12:43 UTC, arseniy-sonar commented on README.adoc
> +* Add two files in this subdirectory and write down the parts that need to be overwritten:
Unlike Jira, you just write down the whole description in the rule.adoc (possibly including some parts using `include::` syntax).
Only metadata.json automatically inherits the parent metadata.json and overwrites parts of it.

2021-06-01 12:43 UTC, arseniy-sonar commented on README.adoc
> +The rule must contain subdirectories corresponding to all the languages this rule is implemented for.
```suggestion
The rule must contain subdirectories corresponding to all the languages this rule is implemented for (by the time the PR is merged).
```

2021-06-01 15:08 UTC, arseniy-sonar requested changes

2021-06-01 15:08 UTC, arseniy-sonar commented on README.adoc
> +You found a bug, something is bothering you or you have an idea to improve the project? First have a look at all the https://jira.sonarsource.com/projects/RULEAPI/issues/RULEAPI-324?filter=allopeniss
```suggestion
You found a bug, something is bothering you or you have an idea how to improve the project? First, have a look at all the https://jira.sonarsource.com/projects/RULEAPI/issues/RULEAPI-324?filter=allopenissues[open tickets]. If you don't see anything related to your subject, please open a new ticket in the backlog, with `backlog` as the fix version.
```

2021-06-01 15:08 UTC, arseniy-sonar commented on README.adoc
> +** `rule.adoc`: write down the whole description of the rule. If you want to include already existing parts (that are in the parent directory for example), use the `include::` syntax.
```suggestion
** `rule.adoc`: write down the whole description of the rule. If you want to include already existing parts (that are in the current or the parent directory), use the `include::` syntax.
```
rule-api does not support inclusion of files from any other directory, if I am not mistaken.

2021-06-02 07:42 UTC, arseniy-sonar commented on README.adoc
> +You found a bug, something is bothering you or you have an idea to improve the project? First have a look at all the https://jira.sonarsource.com/projects/RULEAPI/issues/RULEAPI-324?filter=allopeniss
You are right, I think "of" is missing there as well. I meant to shift the meaning from

An idea to improve the project: "Hey, let's improve the project!"

to

An idea of how to improve the project: "Hey, let's add a script that would open a PR to add a language to an RSPEC automatically!"

2021-06-02 07:53 UTC, amelie-renard-sonarsource commented on README.adoc
> +You found a bug, something is bothering you or you have an idea to improve the project? First have a look at all the https://jira.sonarsource.com/projects/RULEAPI/issues/RULEAPI-324?filter=allopeniss
Oh, ok, makes sense

2021-06-02 09:16 UTC, merged