Update code example for S107 Cshapr
SonarSource/rspec pull request #792
Opened 2022-02-08 10:15 UTC by mary-georgiou-sonarsource

Update code example for rule S107 to reflect the case where the parameters of a constructor intended for the base class do not count in the total sum of parameters.

2022-02-08 11:03 UTC, arseniy-sonar requested changes
@mary-georgiou-sonarsource , please update the PR title according to our [naming convention](https://github.com/SonarSource/rspec/#to-modify-an-existing-rule), and also add the `dotnet` label before merging.

2022-02-08 13:01 UTC, arseniy-sonar approved these changes
Thank you.

2022-02-08 16:23 UTC, andrei-epure-sonarsource requested changes

2022-02-08 16:23 UTC, andrei-epure-sonarsource commented on rules/S107/csharp/rule.adoc
> +}
I don't understand what `TestClass` is ? what's the return value of the function?

and what's the inner `TestClass`?

2022-02-08 17:01 UTC, mary-georgiou-sonarsource commented on rules/S107/csharp/rule.adoc
> +}
Apologies, the keyword `void` is a "typo".
My understanding is to leave only the first part of the example with the comment?
I agree the non-compliant example is too much.

2022-02-08 19:43 UTC, andrei-epure-sonarsource requested changes

2022-02-08 19:43 UTC, andrei-epure-sonarsource commented on rules/S107/csharp/rule.adoc
> +public BaseClass(int param1)
```suggestion
public class BaseClass(int param1)
```

2022-02-08 19:43 UTC, andrei-epure-sonarsource commented on rules/S107/csharp/rule.adoc
> +public ExtensionClass : BaseClass
```suggestion
public class ExtensionClass : BaseClass
```

2022-02-09 08:31 UTC, andrei-epure-sonarsource approved these changes
LGTM.

2022-02-09 08:36 UTC, merged