Modify rule S1172: Match the behiavour of TypeScript compiler for JS/TS
SonarSource/rspec pull request #827
Opened 2022-02-16 11:02 UTC by yassin-kammoun-sonarsource

2022-02-17 08:59 UTC, vilchik-elena requested changes
I believe just example with `_` is not enough, we need to describe the reasoning behind it

2022-02-17 14:21 UTC, vilchik-elena commented on rules/S1172/javascript/rule.adoc
> +Also the rule ignores all parameters whose name starts with an underscore (``++_++``).
@yassin-kammoun-sonarsource wdyt?

2022-02-18 08:06 UTC, yassin-kammoun-sonarsource commented on rules/S1172/javascript/rule.adoc
> +Also the rule ignores all parameters whose name starts with an underscore (``++_++``).
I would add a comma after `Also`, and the suggestion is on the wrong line, but still, I like it.

2022-02-18 08:09 UTC, yassin-kammoun-sonarsource commented on rules/S1172/javascript/rule.adoc
> +Also the rule ignores all parameters whose name starts with an underscore (``++_++``).
Never mind, I missed your commit.

2022-02-18 08:15 UTC, vilchik-elena approved these changes

2022-02-18 08:15 UTC, merged