RULEAPI-748: Introduce GitHub Action to update quickfix status
SonarSource/rspec pull request #847
Opened 2022-02-23 14:51 UTC by marco-antognini-sonarsource

This can be tested at https://github.com/marco-antognini-sonarsource/rspec/actions/workflows/update_quickfix_status.yml

2022-02-24 08:14 UTC, arseniy-sonar requested changes
This looks like a really useful action!
Besides the comments below, some documentation is missing for this new action. You can simply mention it in the [section about the quickfix field](https://github.com/SonarSource/rspec/blob/master/docs/metadata.adoc#quickfix-field)

2022-02-24 08:14 UTC, arseniy-sonar commented on rspec-tools/tests/test_create_rule.py
> +  assert status != initial_metadata.get('quickfix', 'unknown')
I feel this assertion, as well as the one on l. 101 is too weak. As you are controlling the test inputs, you should know whether `quickfix` is present in the `initial_metadata` and `new_metadata` dictionaries, and you can assert that it is what you think it is.

2022-02-24 08:14 UTC, arseniy-sonar commented on rspec-tools/tests/test_create_rule.py
> +      assert initial_metadata[key] == new_metadata[key]
Perhaps also assert that no other file is changed

2022-02-24 08:14 UTC, arseniy-sonar commented on rspec-tools/tests/test_create_rule.py
> +def test_update_rule_quickfix_status(mockRuleCreator):
A docstring?

2022-02-24 08:14 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/create_rule.py
> +    file.write_text(json.dumps(metadata, indent=2))
I'd be cautious with ignoring the "/" vs. "\\/" syntax. While they are equivalent w.r.t. JSON spec, they might be treated differently by the tools we use to work with JSON. I think this topic deserves clarification as a separate task, not as a part of this PR.
For example, here's what [rule-api does](https://github.com/SonarSource/sonar-rule-api/blob/master/src/main/java/com/sonarsource/ruleapi/services/RuleFilesService.java#L119) when GSON the library it uses to work with JSON outputs just "/":
```
gson.toJson(metadata).replace("/", "\\/")
```

2022-02-24 08:16 UTC, arseniy-sonar commented
BTW, I do not have a button to trigger the "update quickfix status" action on your repository.

2022-02-24 08:56 UTC, marco-antognini-sonarsource commented
> BTW, I do not have a button to trigger the "update quickfix status" action on your clone.

Ah, that's a bummer... I just added you as a collaborator on my fork, hoping that would allow you to trigger it.

2022-02-24 09:55 UTC, arseniy-sonar commented
Thanks, I was able to run a few tests. Optionally, you could also validate that the new quick-fix status is different from the status quo.

2022-02-24 10:06 UTC, marco-antognini-sonarsource reviewed
Thanks for the feedback

2022-02-24 10:06 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/create_rule.py
> +      f'You can preview this rule [here](https://sonarsource.github.io/rspec/#/rspec/S{rule_number}/{language}) (updated a few minutes after each push).',
Hum.. I've mixed feeling there -- I agree it is unlikely to be useful all the time, but still, it could be handy to some people. For example, the PR starts as simply updating the quick fix status but later someone spots a typo in the RSPEC while implementing the quick fix and updates the PR to include the fix for the typo. At the very least, I don't think it hurts to keep it.

2022-02-24 10:06 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_create_rule.py
> +  assert status != initial_metadata.get('quickfix', 'unknown')
You mean, using this instead?

```suggestion
  assert status != initial_metadata.get('quickfix')
```

2022-02-24 10:10 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/cli.py
> +from rspec_tools.create_rule import create_new_rule, add_language_to_rule, update_rule_quickfix_status
Sure they all operate on rules that's what the whole `rspec-tools` project is for. I think `rule_factory` might be associated with the factory design pattern and would be misleading. They do perform git commands and PR creation, but IMO that is an implementation detail, rather than the categorical factor. I don't mind the refactoring size if you make it on top of what's already in the PR.

2022-02-24 10:13 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/create_rule.py
> +      f'You can preview this rule [here](https://sonarsource.github.io/rspec/#/rspec/S{rule_number}/{language}) (updated a few minutes after each push).',
At the moment we don't preview changes to a rule see [RULEAPI-655](https://jira.sonarsource.com/browse/RULEAPI-655).
From this standpoint, this link is misleading, and that's why I think it is doing a disservice to the users.
At least it should be renamed to something like "See the original rule [here]"

2022-02-24 10:18 UTC, arseniy-sonar commented on rspec-tools/tests/test_create_rule.py
> +  assert status != initial_metadata.get('quickfix', 'unknown')
That's an equivalently weak version for this case, since if the `quickfix` field is not present in `initial_metadata` and if the `quickfix` is bound to a value different from `status` the assertion would be satisfied and I am not sure which one you are asserting here.
I'd go for two assertions.
```suggestion
  assert 'quickfix' in initial_metadata
  assert status != initial_metadata['quickfix']
```

2022-02-24 10:41 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/create_rule.py
> +      f'You can preview this rule [here](https://sonarsource.github.io/rspec/#/rspec/S{rule_number}/{language}) (updated a few minutes after each push).',
Right, I did not consider this indeed.

2022-02-24 10:41 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_create_rule.py
> +  assert status != initial_metadata.get('quickfix', 'unknown')
Right, that's better indeed! I forgot that `dict.get` never raises an exception...

2022-02-24 10:41 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/cli.py
> +from rspec_tools.create_rule import create_new_rule, add_language_to_rule, update_rule_quickfix_status
Fair enough. I'll see how to improve things.

2022-02-24 12:30 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/create_rule.py
> +    file.write_text(json.dumps(metadata, indent=2))
Raised [RULEAPI-750](https://jira.sonarsource.com/browse/RULEAPI-750)

2022-02-24 12:36 UTC, marco-antognini-sonarsource reviewed
An update before doing the refactoring.

2022-02-24 12:36 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_create_rule.py
> +def test_update_rule_quickfix_status(mockRuleCreator):
Improved with 00c8e4ef9b49268715434a7280ee415ae96cf499.

2022-02-24 12:36 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_create_rule.py
> +      assert initial_metadata[key] == new_metadata[key]
Improved with 00c8e4ef9b49268715434a7280ee415ae96cf499.

2022-02-24 12:36 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_create_rule.py
> +  assert status != initial_metadata.get('quickfix', 'unknown')
Improved with 00c8e4ef9b49268715434a7280ee415ae96cf499.

2022-02-24 12:36 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/create_rule.py
> +      f'You can preview this rule [here](https://sonarsource.github.io/rspec/#/rspec/S{rule_number}/{language}) (updated a few minutes after each push).',
Improved with 00c8e4ef9b49268715434a7280ee415ae96cf499.

2022-02-24 12:36 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/create_rule.py
> +    file.write_text(json.dumps(metadata, indent=2))
Improved with 00c8e4ef9b49268715434a7280ee415ae96cf499.

2022-02-24 12:36 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/cli.py
> +from rspec_tools.create_rule import create_new_rule, add_language_to_rule, update_rule_quickfix_status
I think I've addressed your other comments. I've left this out for now. Once we are happy about the functional changes and testing, I'll start this.

2022-02-24 14:59 UTC, marco-antognini-sonarsource commented on .github/workflows/update_quickfix_status.yml
> +name: Update quick fix status
Forgot about:

> You can simply mention it in the [section about the quickfix field](https://github.com/SonarSource/rspec/blob/master/docs/metadata.adoc#quickfix-field)

(Making this a thread to avoid forgetting about it.)

2022-02-24 15:59 UTC, marco-antognini-sonarsource commented on .github/workflows/update_quickfix_status.yml
> +name: Update quick fix status
Done with db90dee.

2022-02-24 16:26 UTC, arseniy-sonar approved these changes

2022-02-24 16:26 UTC, arseniy-sonar commented on docs/metadata.adoc
> +endif::[]
This is something that wasn't properly moved when the documentation was split up. I hope you don't mind me inserting it directly into your PR :pray: 
Feel free to remove or use different emojis

2022-02-24 16:26 UTC, arseniy-sonar commented on rspec-tools/tests/test_create_rule.py
> +  metadata_path = Path(mock_rspec_repo.working_dir) / sub_path
Interesting syntax :+1:

2022-02-24 17:11 UTC, marco-antognini-sonarsource commented on docs/metadata.adoc
> +endif::[]
Ha, looks better! 👍

2022-02-25 16:34 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/cli.py
> +from rspec_tools.create_rule import create_new_rule, add_language_to_rule, update_rule_quickfix_status
I've now pushed the refactoring -- see the commits after 750c650. Hopefully, it's still reviewable... Before merging, I'll squash the commits into two: the new functionality and the refactoring.

2022-02-25 17:14 UTC, arseniy-sonar approved these changes
I love the new structure!
This is a huge change indeed. I checked it commit-by-commit, but I am too impatient to follow every detail. One thing that might be improved is the name (yeah, I know, naming :sweat_smile: ) of the `conftest.py` file. I understand from its content that it stores the common configuration for tests, like various mock structures. But from the name, I assumed it would be testing configuration.
How about "test_config.py" or "common_test_config.py" ?

2022-02-28 08:33 UTC, marco-antognini-sonarsource commented
> One thing that might be improved is the name (yeah, I know, naming 😅 ) of the `conftest.py` file. I understand from its content that it stores the common configuration for tests, like various mock structures. But from the name, I assumed it would be testing configuration.

I agree, it's probably not the best name... but I'm not sure we can change it as it's a special name w.r.t. pytest. https://docs.pytest.org/en/latest/reference/fixtures.html#conftest-py-sharing-fixtures-across-multiple-files

2022-02-28 11:08 UTC, merged