Modify rule S3574: add Sonar Way quality profile
SonarSource/rspec pull request #912
Opened 2022-03-25 14:06 UTC by marco-antognini-sonarsource

Relates to https://github.com/SonarSource/sonar-cpp/pull/1861

2022-03-30 06:21 UTC, tomasz-kaminski-sonarsource requested changes
Why did you remove rules/S3574/cfamily/message.adoc?

2022-03-30 09:18 UTC, marco-antognini-sonarsource reviewed
> Why did you remove rules/S3574/cfamily/message.adoc?

I've removed this file and `highlighting.adoc` because they are outdated and AFAIK artifacts from Jira's initial description. Instead of updating them and doing back and forth with the implementation and the RSPEC, it's easier to delete them as they brind little to no value.

2022-03-30 09:18 UTC, marco-antognini-sonarsource commented on rules/S3574/cfamily/rule.adoc
> +There are a few exceptions to this rule, such as coroutine lambdas, which require an explicit return type.
I wanted to sleep over it before asking for review, but you make a great point! 👍

2022-03-30 09:32 UTC, marco-antognini-sonarsource commented on rules/S3574/cfamily/rule.adoc
> +There are a few exceptions to this rule, such as coroutine lambdas, which require an explicit return type.
Should be better with c28bc45.

2022-03-30 13:26 UTC, tomasz-kaminski-sonarsource commented on rules/S3574/cfamily/rule.adoc
> +Finally, it does not trigger if removing the explicit return type would result in ill-formed programs.
Thanks, I think I merged two cases: the compiler would deduce type by different (most likely), the compiler does not deduce return type. I no longer think that is the case.

But still think, that deduction being ill-formed is two vague, maybe say something like: The issue is not raised, in cases when deduction of return type will fail: e.g. when lambda is a coroutine or have multiple returns, with different types that are convertible to return type.

2022-03-30 16:24 UTC, marco-antognini-sonarsource commented on rules/S3574/cfamily/rule.adoc
> +== Exceptions
This ain't documented in https://github.com/SonarSource/rspec/blob/master/docs/description.adoc#sections.

Maybe @arseniy-sonar knows whether sections should be in a particular order?

2022-03-31 16:40 UTC, arseniy-sonar commented on rules/S3574/cfamily/rule.adoc
> +== Exceptions
Nice, thanks for digging it up, @marco-antognini-sonarsource :)
Perhaps we should update the RSPEC doc to say that (and also validate the order?)

2022-03-31 16:52 UTC, marco-antognini-sonarsource commented on rules/S3574/cfamily/rule.adoc
> +== Exceptions
I'll check if we have already a ticket and if not raise one. 😉

2022-03-31 16:53 UTC, marco-antognini-sonarsource commented on rules/S3574/cfamily/rule.adoc
> +== Exceptions
Marking this particular discussion as resolved since the exception section is now at the end, before the "See" section.

2022-03-31 16:54 UTC, marco-antognini-sonarsource commented on rules/S3574/cfamily/rule.adoc
> +Finally, it does not trigger if removing the explicit return type would result in ill-formed programs.
I've completely reworked the text and decided to make the implicit explicit. Let me know what you think.

2022-04-01 06:12 UTC, tomasz-kaminski-sonarsource approved these changes

2022-04-01 06:13 UTC, tomasz-kaminski-sonarsource commented on rules/S3574/cfamily/rule.adoc
> +Finally, it does not trigger if removing the explicit return type would result in ill-formed programs.
I really like how this looks like. The main body is mall and enught to see why I may have a ticket, but the exception is a nice bit of C++ knowledge for you hidden in rule.

2022-04-01 12:08 UTC, merged

2022-04-01 14:01 UTC, marco-antognini-sonarsource commented on rules/S3574/cfamily/rule.adoc
> +== Exceptions
https://jira.sonarsource.com/browse/RULEAPI-754 for the jira ticket.