Mock analyzer repos for the coverage test
SonarSource/rspec pull request #927
Opened 2022-04-04 05:41 UTC by arseniy-sonar

This removes the dependency on online repositories (on GitHub),
and speeds up the test by stripping the number of versions and files in them to a minimum.

2022-04-04 15:55 UTC, marco-antognini-sonarsource requested changes
Looks good, some minor things only.

2022-04-04 15:55 UTC, marco-antognini-sonarsource commented on rspec-tools/rspec_tools/coverage.py
> +  os.chdir(repo_dir)
In `collect_coverage_for_version`, `repo` got renamed into `analyzer_name`.

In `collect_coverage_for_all_versions`, it's not clear to me that `repo` is actually the name of an analyzer when calling `collect_coverage_for_version`.

Should that variable be renamed? Is the `print` command really necessary? Could type annotations help? -- Just a few thoughts.

2022-04-04 15:55 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_coverage.py
> +# so FS is not convenient. use json instead:
What is FS?

2022-04-04 15:55 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_coverage.py
> +JSTS_SONARPEDIA='{"rules-metadata-path": "r", "languages":["JS", "TS"]}'
"r" is very short. If it appears in an error message, it may not bring enough context to help understand the issue.

2022-04-04 15:55 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_coverage.py
> +# Need to keep the tags ordered, and set the commit dates,
If this is a hard requirement, we should have a test to verify this in case someone breaks the sorting in the future.

2022-04-04 15:55 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_coverage.py
> +    return mocked_repos[repo_url.split('/')[-1]]
Will that work on Windows? (If we care about Windows.)

2022-04-04 15:55 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_coverage.py
> +MOCK_REPOS=[{'name':'SonarJS',
An alternative format could be based on git patches (generated with `git format-patch` and applied with `git am`). I'm not asking you to change the design -- just an idea to consider whether it could help the future changes you have in mind.

2022-04-04 15:55 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_coverage.py
>      assert 'S103' in cov['XML']
Seems these two are duplicated with new test just below, right?

2022-04-04 15:55 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_coverage.py
> +    assert 'failed to collect implemented rules for' in capsys.readouterr().out
Didn't know about `capsys`, that's smart! 👍

2022-04-04 15:55 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_coverage.py
> +def test_update_coverage_no_sonarpedia(tmpdir, mock_git_analyzer_repos, capsys):
It has the same name as above.

2022-04-04 16:51 UTC, arseniy-sonar commented on rspec-tools/tests/test_coverage.py
> +def test_update_coverage_no_sonarpedia(tmpdir, mock_git_analyzer_repos, capsys):
fixed.

2022-04-04 16:52 UTC, arseniy-sonar commented on rspec-tools/tests/test_coverage.py
> +    assert 'failed to collect implemented rules for' in capsys.readouterr().out
I believe it stands for "CAPture SYstem Streams"

2022-04-04 16:53 UTC, arseniy-sonar commented on rspec-tools/tests/test_coverage.py
>      assert 'S103' in cov['XML']
Indeed. Deduped

2022-04-04 16:55 UTC, arseniy-sonar commented on rspec-tools/tests/test_coverage.py
> +MOCK_REPOS=[{'name':'SonarJS',
Indeed, that is a possibility that did not cross my mind.
I think it would end up having more boilerplate and less amenable to inspection/manipulation within python (not that it needs to be amenable to it at the moment)

2022-04-04 16:56 UTC, arseniy-sonar commented on rspec-tools/tests/test_coverage.py
> +    return mocked_repos[repo_url.split('/')[-1]]
It must work because these are URLs that are platform-independent. (unlike filesystem paths)

2022-04-04 16:59 UTC, arseniy-sonar commented on rspec-tools/tests/test_coverage.py
> +# so FS is not convenient. use json instead:
acronym for file-system. In fact, this comment does not add anything, just my own reasoning, so I'll remove it.

2022-04-04 17:13 UTC, arseniy-sonar commented on rspec-tools/tests/test_coverage.py
> +# Need to keep the tags ordered, and set the commit dates,
Added a test.

2022-04-04 17:21 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/coverage.py
> +  os.chdir(repo_dir)
Renamed it to a more accurate "repo_name"
The print command helps to keep track of the coverage-collection progress. It's been there before

2022-04-04 17:22 UTC, arseniy-sonar commented
@marco-antognini-sonarsource , if you are going to merge this PR, please put its description to the commit message

2022-04-05 07:42 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_coverage.py
> +    return mocked_repos[repo_url.split('/')[-1]]
Of course, silly me. 👍

2022-04-05 07:42 UTC, marco-antognini-sonarsource approved these changes
Thanks for the update, LGTM!

2022-04-05 07:44 UTC, merged