Add styling guide to docs
SonarSource/rspec pull request #930
Opened 2022-04-04 13:32 UTC by hendrik-buchwald-sonarsource

This PR adds a styling guide as discussed in the ["Language styling guide for RSPEC"](https://discuss.sonarsource.com/t/language-styling-guide-for-rspec/9640) circle.

This document aims to specify the most common use cases that we encounter, similar to the ["Associated Press Style Quick Reference Guide"](https://www.codot.gov/business/grants/safetygrants/assets/APStyleGuideCheatSheet.pdf). It is not and does not aim to be a full reference for every possible case.

2022-04-04 13:52 UTC, arseniy-sonar commented on docs/styling_guide.adoc
> +> The function throws exceptions of the type `RuntimeException`.
I would appreciate a few examples of what should not be put in `backticks`. E.g.: 

> Compiling source file "src/MyClass.cpp" break an assert in GTest framework.

2022-04-04 14:15 UTC, hendrik-buchwald-sonarsource commented on docs/styling_guide.adoc
> +> It is not the first time I have written a rule description.
Yes, the `>` parts are supposed to be examples of how it looks right. For example, the wrong version would have been "It's not ..." or "It isn't ...". I will try to think of something to improve this.

2022-04-04 15:27 UTC, hendrik-buchwald-sonarsource commented on docs/styling_guide.adoc
> +> The function throws exceptions of the type `RuntimeException`.
For now, I have just added paths as an additional case.

2022-04-04 16:46 UTC, arseniy-sonar commented on docs/styling_guide.adoc
> +> The function throws exceptions of the type `RuntimeException`.
Here is the section in our meeting notes document.
```
> Use the monospaced font (backticks) only for: Variable/method/class names, keywords (i.e. it is code and exactly matching the code; valid code)
Do NOT use the monospaced font for anything else
```

2022-04-04 16:48 UTC, arseniy-sonar commented
I think negative examples would add to this document. E.g.:

```
Write:: It is an issue I have specified.

Avoid:: It's an issue I've specified.
```

2022-04-04 16:48 UTC, arseniy-sonar requested changes
I think negative examples would add to this document. E.g.:

```
Write:: It is an issue I have specified.

Avoid:: It's an issue I've specified.
```

2022-04-05 07:25 UTC, hendrik-buchwald-sonarsource commented on docs/styling_guide.adoc
> +> The function throws exceptions of the type `RuntimeException`.
Okay, I think that is fine. To me, the important thing is to have a standard for this but it could be with or without. I have now removed it to keep it simple. "Highlight code" is pretty clear.

2022-04-05 07:43 UTC, hendrik-buchwald-sonarsource commented
@arseniy-sonar okay, done!

2022-04-05 07:56 UTC, arseniy-sonar approved these changes
Looks great!

2022-04-05 08:49 UTC, loris-s-sonarsource approved these changes
LGTM!

2022-04-05 08:49 UTC, loris-s-sonarsource commented on docs/styling_guide.adoc
> +Following it should be considered a goal to work towards to to get more homogenous texts.
```suggestion
Following it should be considered a goal to work towards to get more homogenous texts.
```

2022-04-05 08:49 UTC, loris-s-sonarsource commented on docs/styling_guide.adoc
> +Do not add punctutation for enumerations.
```suggestion
Do not add punctuation for enumerations.
```

2022-04-05 10:13 UTC, merged