RULEAPI-753: Use modern ids and coalesce the coverage for legacy ids
SonarSource/rspec pull request #941
Opened 2022-04-08 15:35 UTC by arseniy-sonar

2022-04-12 15:54 UTC, marco-antognini-sonarsource requested changes
Looks nice! Some minor comments.

2022-04-12 15:54 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_coverage.py
> +      if f != '.git':
Previously, `.git` was never removed. Now it can if it's a file. (This can happen when using git-worktree, for example.) This particular change might be a bit dangerous. If not necessary, I'd keep the old version of `clear_working_dir`.

2022-04-12 15:54 UTC, marco-antognini-sonarsource commented on rspec-tools/tests/test_coverage.py
> +                          ['rules/MethodName.json', '{}'], ['rules/S1145.json', '{}'],
It may be good to have a test to ensure `MethodName` isn't part of the coverage, as opposed to the already existing test `assert 'S100' in cov['JAVASCRIPT']`.

2022-04-13 04:57 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/coverage.py
> +  rules_dir.resolve()
indeed. thanks. removed.

2022-04-13 04:59 UTC, arseniy-sonar commented on rspec-tools/rspec_tools/coverage.py
> +  (_, rule_dirs, _) = os.walk(rules_dir).__next__()
Looks reasonable. I didn't like the `os.walk` line. I used your version.

2022-04-13 05:07 UTC, arseniy-sonar commented on rspec-tools/tests/test_coverage.py
> +      if f != '.git':
Today I've learned about `git worktree` :)
Thanks, reverted.

2022-04-13 05:12 UTC, arseniy-sonar commented on rspec-tools/tests/test_coverage.py
> +                          ['rules/MethodName.json', '{}'], ['rules/S1145.json', '{}'],
Indeed. Added to all three tests that test the presence of S100

2022-04-13 05:52 UTC, arseniy-sonar commented
@marco-antognini-sonarsource 
I also piggy-backed mocking of the temporary RSPEC repo for create_rule and modify_rule tests, as they were failing on my machine otherwise. Let me know if you think I should push this change separately

2022-04-13 06:22 UTC, marco-antognini-sonarsource approved these changes
Thanks for the update, LGTM!

> I also piggy-backed mocking of the temporary RSPEC repo for create_rule and modify_rule tests, as they were failing on my machine otherwise. Let me know if you think I should push this change separately

I think this deserves its own commit. But no need to go through another PR. I'll let you squash & split commits as necessary before merging. 👍

2022-04-13 07:28 UTC, merged