Modify rule S5131: Add PHP text
SonarSource/rspec pull request #943
Opened 2022-04-11 13:48 UTC by hendrik-buchwald-sonarsource

This is a draft for the Progressive Education Framework.

2022-04-13 08:44 UTC, loris-s-sonarsource commented on rules/S5131/php/laravel/rule.adoc
> +In case the response consists of HTML code, it is highly recommended to use a template engine like https://laravel.com/docs/9.x/blade[Blade] to generate it.
While I agree, if the customer has a specific use case for really sending HTML from code, we are basically telling them to change the whole architecture of the program, is it reasonable in this case?

2022-04-13 08:45 UTC, loris-s-sonarsource commented on rules/S5131/php/laravel/rule.adoc
> +
This section is shared between multiple PHP descriptions, and I think it could really fit into a common text, for all languages actually. I think I could use it for C# too

2022-04-13 08:48 UTC, loris-s-sonarsource commented on rules/S5131/php/native/rule.adoc
>  ----
The end result of having two code samples would be a diff. So, I agree It wouldn't make sense in a sequential configuration to add a simple concatenation sample, but it would be worth adding in the other case

2022-04-13 08:50 UTC, loris-s-sonarsource commented on rules/S5131/php/native/rule.adoc
> +----
I think it would be worth having a subsection title there, like "PHP-specific Encoding pitfalls"

2022-04-13 08:51 UTC, loris-s-sonarsource commented on rules/S5131/php/laravel/rule.adoc
> +
"Content-Type Pitfalls"

2022-04-13 08:53 UTC, loris-s-sonarsource commented on rules/S5131/php/symfony/rule.adoc
> +A proper template engine does not only separate the view from the business logic and thus results in a more maintainable application.
My comment is the same that the previous one; this is architectural advice, and maybe not adapted in the rule description. It would 100% fit in the "Going The Extra Mile" section

2022-04-13 08:53 UTC, loris-s-sonarsource commented on rules/S5131/php/laravel/rule.adoc
> +In case the response consists of HTML code, it is highly recommended to use a template engine like https://laravel.com/docs/9.x/blade[Blade] to generate it.
It would 100% fit in the "Going The Extra Mile" section

2022-04-13 09:00 UTC, hendrik-buchwald-sonarsource commented on rules/S5131/php/laravel/rule.adoc
> +In case the response consists of HTML code, it is highly recommended to use a template engine like https://laravel.com/docs/9.x/blade[Blade] to generate it.
Maybe it makes more sense in another section. My thought process was the following: I don't think it is very likely that someone actually wants to return HTML here. Blade is included in Laravel, so there is really no reason not to use it to generate the HTML code, and I would say every Laravel developer that has written a web application is aware of that. But just for the rare chance that someone really wants to return HTML code manually for some odd reason, I mentioned it so that they know what direction to take.
I was considering also mentioning `htmlspecialchars` but I consider it a bad practice to generate the HTML code manually in a Laravel application, so I decided against it. I don't want to confuse the reader by showing solutions that I would not recommend them to use.

2022-04-13 09:40 UTC, hendrik-buchwald-sonarsource commented on rules/S5131/php/laravel/rule.adoc
> +
Yep, I agree, I wanted to move this to a shared directory.

2022-04-15 16:20 UTC, loris-s-sonarsource commented on rules/S5131/php/laravel/rule.adoc
> +
Here are some other types: https://github.com/BlackFan/content-type-research/blob/master/XSS.md

2022-04-19 07:15 UTC, hendrik-buchwald-sonarsource commented on rules/S5131/php/laravel/rule.adoc
> +
Interesting, `multipart/x-mixed-replace` works in FF. The other 2 we left out on purpose [here](https://github.com/SonarSource/security-expected-issues/blob/master/rule-modeling/common/browsers.md), since they did not meet the requirements in that doc (if I remember correctly).

2022-04-19 08:14 UTC, hendrik-buchwald-sonarsource commented on rules/S5131/php/native/rule.adoc
>  ----
Yes, in a diff form it would be nice. I will add it as a separate box for now with the idea that it will be a diff-box later.

2022-04-19 11:29 UTC, hendrik-buchwald-sonarsource commented on rules/S5131/php/native/rule.adoc
> +----
Okay, done.

2022-04-20 06:36 UTC, pierre-loup-tristant-sonarsource commented on rules/S5131/php/laravel/rule.adoc
> +In case the response consists of HTML code, it is highly recommended to use a template engine like https://laravel.com/docs/9.x/blade[Blade] to generate it.
I follow @hendrik-buchwald-sonarsource here. Since there is a built-in template engine, the best practice is to use it.

2022-04-20 08:13 UTC, pierre-loup-tristant-sonarsource requested changes
The content looks good. 
My main suggestion is to move most of the fix explanation to "How does it work"

2022-04-21 14:08 UTC, hendrik-buchwald-sonarsource commented on rules/S5131/php/native/rule.adoc
Do you have an example what you mean?

2022-04-22 07:33 UTC, hendrik-buchwald-sonarsource commented on rules/S5131/php/laravel/rule.adoc
> +Thus, the response is not vulnerable to reflected Cross-Site Scripting.
Done.

2022-04-22 14:29 UTC, hendrik-buchwald-sonarsource commented
@pierre-loup-tristant-sonarsource should be the case, did I miss it somewhere?

2022-04-22 14:37 UTC, pierre-loup-tristant-sonarsource commented
Sorry I missed it. Everything looks good.

2022-04-22 15:28 UTC, merged