Modify S6377: Enhance the Noncompliant / Compliant examples
SonarSource/rspec pull request #946
Opened 2022-04-11 15:14 UTC by agigleux

2022-04-11 15:41 UTC, loris-s-sonarsource requested changes
Nice! We are almost there.

Also, I suggest changing the content of `message.adoc` to what you specified in the Jira Ticket.

> Set the ‘org.jcp.xml.dsig.secureValidation’ property to true on the ‘DOMValidateContext’ to validate this XML signature securely.

2022-04-11 15:41 UTC, loris-s-sonarsource commented on rules/S6377/java/rule.adoc
> +valContext.setProperty("org.jcp.xml.dsig.secureValidation", Boolean.TRUE); // Compliant
the "Compliant" comment is deprecated

```suggestion
valContext.setProperty("org.jcp.xml.dsig.secureValidation", Boolean.TRUE);
```

2022-04-11 15:41 UTC, loris-s-sonarsource commented on rules/S6377/description.adoc
> -In addition, the ``jdk.xml.dsig.secureValidationPolicy`` Security Property can be used to control and fine-tune the restrictions listed previously or add additional restrictions.
Agreed on the deletion. We do not demonstrate it, but demonstrating would be out-of-scope for this description.

2022-04-11 15:41 UTC, loris-s-sonarsource commented on rules/S6377/java/rule.adoc
> -The Java XML Digital Signature API doesn't use a strong signature validation mode by default (except when the application runs with a security manager):
+1, agreed on the deletion

2022-04-11 15:41 UTC, loris-s-sonarsource commented on rules/S6377/java/rule.adoc
> +boolean signatureValidity = signature.validate(valContext);
Oh, honestly I think that the code was short but I'm not sure about adding all of this. Now that you did it I would say that it should stay.

However, I suggest we move the comment to the very top of the description, as Ann suggested

2022-04-11 15:41 UTC, loris-s-sonarsource commented on rules/S6377/description.adoc
>  As with any other parsing process, unrestricted validation of third-party XML signatures can lead to security vulnerabilities. In this case, threats range from denial of service to confidentiality br
```suggestion
As with any other parsing process, unrestricted validation of third-party XML signatures can lead to security vulnerabilities. In this case, threats range from denial of service to confidentiality breaches.

By default, the Java XML Digital Signature API does not apply restrictions on XML signature validation, unless the application runs with a security manager. +
```

I suggest we take the comment from the noncompliant section and modify it to add it here.

2022-04-11 15:41 UTC, loris-s-sonarsource commented on rules/S6377/description.adoc
> +To protect the application from these vulnerabilities, the DOMValidateContext's ``org.jcp.xml.dsig.secureValidation`` attribute from the Java XML Digital Signature API enforces the following restrict
Honestly, I'd say that adding the namespace instead of paraphrasing could be even more concise and clear:

```suggestion
To protect the application from these vulnerabilities, set the ``org.jcp.xml.dsig.secureValidation`` attribute with the``javax.xml.crypto.dsig.dom.DOMValidateContext.setProperty`` method. +
This attribute ensures that the code enforces the following restrictions:
```

WDYT?

2022-04-11 15:41 UTC, loris-s-sonarsource commented on rules/S6377/java/rule.adoc
> +boolean signatureValidity = signature.validate(valContext);
```suggestion
NodeList signatureElement = doc.getElementsByTagNameNS(XMLSignature.XMLNS, "Signature");

XMLSignatureFactory fac = XMLSignatureFactory.getInstance("DOM");
DOMValidateContext valContext = new DOMValidateContext(new KeyValueKeySelector(), signatureElement.item(0)); // Noncompliant
XMLSignature signature = fac.unmarshalXMLSignature(valContext);

boolean signatureValidity = signature.validate(valContext);
```

I think removing it will also ease code reading (The suggestion removes the comment line).

2022-04-11 15:41 UTC, loris-s-sonarsource commented on rules/S6377/java/rule.adoc
>  The Java XML Digital Signature API offers a secure validation mode to protect against various https://docs.oracle.com/en/java/javase/14/security/java-xml-digital-signature-api-overview-and-tutorial.h
```suggestion
```

I didn't see it in my first review. We should remove this line since we already list the security issues in the description (it's the same list).

2022-04-11 16:21 UTC, agigleux commented on rules/S6377/description.adoc
> +To protect the application from these vulnerabilities, the DOMValidateContext's ``org.jcp.xml.dsig.secureValidation`` attribute from the Java XML Digital Signature API enforces the following restrict
I really prefer this version:

To protect the application from these vulnerabilities, the DOMValidateContext's ``org.jcp.xml.dsig.secureValidation`` attribute from the Java XML Digital Signature API enforces the following restrictions:

2022-04-12 07:22 UTC, loris-s-sonarsource commented on rules/S6377/description.adoc
> +To protect the application from these vulnerabilities, the DOMValidateContext's ``org.jcp.xml.dsig.secureValidation`` attribute from the Java XML Digital Signature API enforces the following restrict
Ok! My opinion is that not having the method to actually add it might slow down the fix.

Here are two more arguments:

1. It's a duplicate explanation since the message already states:
    > Set the ‘org.jcp.xml.dsig.secureValidation’ property to true on the ‘DOMValidateContext’ to validate this XML signature securely.
2. Writing both "Java XML Digital Signature API" and "org.jcp.xml.dsig.secureValidation" is also a duplicate of the same meaning

2022-04-12 19:57 UTC, merged