RULEAPI-760: Add a new language identifier for kubernetes rules
SonarSource/rspec pull request #992
Opened 2022-05-16 09:40 UTC by loris-s-sonarsource

Full name: Add a new language identifier for kubernetes YAML misconfiguration detection rules

---

# References
[RULEAPI-760](https://jira.sonarsource.com/browse/RULEAPI-760)

2022-05-20 10:09 UTC, arseniy-sonar requested changes
Regarding rspec-tools/rspec_tools/utils.py: `LANG_TO_SOURCE`, is there a highlighting mode in highlight.js supporting Kubernetes? Maybe just YAML?

2022-05-20 10:09 UTC, arseniy-sonar commented on supported_languages.adoc
> +`abap`, `apex`, `cfamily`, `cobol`, `csharp`, `css`, `flex`, `go`, `html`, `java`, `javascript`, `kotlin`, `php`, `pli`, `plsql`, `python`, `rpg`, `ruby`, `rust`, `scala`, `secrets`, `solidity`, `swi
One of the uses of this list is the validation of subfolders in a rule folder. I.e., a rule folder `rules/S100` can have only language-specific subfolders, and only for the supported languages - that are listed here. So for Kubernetes that would make it look for `kubernetes yamls` subfolder (with a space).
Even though we live in 2022, I still strongly advise against spaces in the paths when there is no strong need for them.
Moreover to keep the style consistent with other languages, I suggest using only `[a-z0-9]` characters. How about just `kubernetes` as you used in other places?

2022-05-20 10:11 UTC, arseniy-sonar commented
Also, PTAL at the test failures, I think you can use them for guidance of what other places need to be updated with the new "language"

2022-05-23 08:59 UTC, loris-s-sonarsource commented on supported_languages.adoc
> +`abap`, `apex`, `cfamily`, `cobol`, `csharp`, `css`, `flex`, `go`, `html`, `java`, `javascript`, `kotlin`, `php`, `pli`, `plsql`, `python`, `rpg`, `ruby`, `rust`, `scala`, `secrets`, `solidity`, `swi
Thanks for this. The "or" made me think that this list was just intended to be converted to html.

2022-05-25 07:29 UTC, arseniy-sonar approved these changes
Looks good :+1:

2022-05-25 08:04 UTC, merged